/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojcollapsible"],function(a,f){(function(){a.Fa("oj.ojAccordion",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{multiple:!1,expanded:null,beforeExpand:null,expand:null,beforeCollapse:null,collapse:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-accordion oj-component").attr("role","group");this.Pb()},Zg:function(a,d){a.show(d,{launcher:this.element.find(".oj-collapsible-header-icon").first(),focus:"menu"})},_destroy:function(){this.element.removeClass("oj-accordion oj-component").removeAttr("role");
this.element.children().removeClass("oj-accordion-collapsible");this.element.children(".oj-accordion-created").removeClass("oj-accordion-created").ojCollapsible("destroy")},_setOption:function(a,d,c){"multiple"===a?!1==d&&!0==this.options.multiple&&this.mg.hasClass("oj-expanded").first().siblings(".oj-collapsible").trigger("ojcollapse"):"expanded"===a&&this.DR(d);this._super(a,d,c);"disabled"===a&&((d=!!d)&&this.mg.each(function(){null==f(this).ojCollapsible("option",a)&&f(this).ojCollapsible("option",
a,d)}),this.element.toggleClass("oj-disabled",d))},refresh:function(){this._super();this.Pb()},Pb:function(){this.PP();this._setOption("disabled",this.options.disabled);this._setOption("expanded",this.options.expanded);this.pj()},PP:function(){this.element.children(":oj-collapsible").each(function(){f(this).ojCollapsible("option","expandArea","header")});this.mg=this.element.children().not(":oj-ojCollapsible").ojCollapsible({expandArea:"header"}).addClass("oj-accordion-created").end().addClass("oj-accordion-collapsible")},
pj:function(){var a={keydown:this.hj,ojbeforeexpand:this.WK,ojexpand:this.JM,ojbeforecollapse:this.VK,ojcollapse:this.tL};this._off(this.mg);this._on(this.mg,a)},hj:function(a){if(!a.altKey&&!a.ctrlKey&&(f(a.target).hasClass("oj-collapsible-header")||f(a.target).hasClass("oj-collapsible-header-icon"))){var d=f.ui.keyCode,c=this.mg.not(".oj-disabled"),e=c.length,g=f(a.target).closest(".oj-collapsible"),h=c.index(g),k=!1;if(0<=h)switch(a.keyCode){case d.RIGHT:case d.DOWN:k=c[(h+1)%e];break;case d.LEFT:case d.UP:k=
c[(h-1+e)%e];break;case d.HOME:k=c[0];break;case d.END:k=c[e-1]}k&&(g&&f(g).trigger("ojfocusout"),f(k).trigger("ojfocus"),a.preventDefault())}},eB:function(a){return!this.options.multiple&&(a=f(a.target).closest(".oj-collapsible"),a.parent().is(":oj-ojAccordion"))?a.siblings(".oj-collapsible.oj-expanded").map(function(){return f(this).data("oj-ojCollapsible")}):f()},WK:function(a){if(!this.nq(a))return!0;var d,c=this,e;this.eB(a).each(function(){var g=this.element;e=c.xk(g,f(a.target));g={header:g.find(".oj-collapsible-header"),
content:g.find(".oj-collapsible-content")};return d=this._trigger("beforeCollapse",a,g)});e||(e=c.xk(null,f(a.target)));this.options.multiple||this._trigger("beforeExpand",a,e);return d},JM:function(a,d){if(this.nq(a)){var c,e=this;this.eB(a).each(function(){this.collapse(!1,a,d);c=e.xk(this.element,f(a.target))});c||(c=e.xk(null,f(a.target)));this.options.multiple||this._trigger("expand",a,c);this.aw()}},VK:function(a,d){return this.nq(a)&&!this.options.multiple?this._trigger("beforeCollapse",a,
this.lC(a,d)):!0},tL:function(a,d){if(this.nq(a)){var c=this.lC(a,d);this.options.multiple||this._trigger("collapse",a,c);this.aw()}},xk:function(a,d){return{fromCollapsible:a,toCollapsible:d}},lC:function(a,d){var c;if(d.toCollapsible)c=d;else{if(a.originalEvent&&a.originalEvent.target){var e=f(a.originalEvent.target);e.hasClass("oj-collapsible")&&(c=this.xk(f(a.target),e))}c||(c=this.xk(f(a.target),null))}return c},nq:function(a){return f(a.target).is(this.mg)},aw:function(){var a=[];this.mg.each(function(d){f(this).ojCollapsible("option",
"expanded")&&a.push(d)});this.options.expanded=a},UV:function(a,d,c){void 0===c&&(c=d.index());c=a.indexOf(c);return-1!=c?c:a.indexOf(d.attr("id"))},DR:function(a){var d={};this.mg.each(function(a){var b=f(this).attr("id");b&&(d[b]=a)});var c=[];Array.isArray(a)&&a.each(function(a){"string"===typeof this?void 0!==d[this]&&(c[d[this]]=!0):"number"===typeof this&&(c[a]=!0)});for(a=0;a<c.length;a++)f(this.mg[a]).ojCollapsible("option","expanded",!!this);this.aw()},getNodeBySubId:function(a){if(null==
a)return this.element?this.element[0]:null;var d=a.subId;a=this.mg[a.index];switch(d){case "oj-accordion-content":d="oj-collapsible-content";break;case "oj-accordion-header":d="oj-collapsible-header";break;case "oj-accordion-header-icon":d="oj-collapsible-header-icon";break;case "oj-accordion-collapsible":return a;default:return null}return f(a).ojCollapsible("getNodeBySubId",{QW:d})}})})()});
//# sourceMappingURL=oj-modular.map