/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){function b(a,b){var c=a.name,d=a.form;c?(c=c.replace(/'/g,"\\'"),c=":radio[name\x3d'"+c+"']:oj-button",d=b?b.filter(c):d?f(d).find(c):f(c,a.ownerDocument).filter(function(){return!this.form})):d=(b?b.filter(a):f(a)).filter(":oj-button");return d}a.Fa("oj.ojButton",f.oj.baseComponent,{defaultElement:"\x3cbutton\x3e",widgetEventPrefix:"oj",options:{disabled:null,display:"all",label:null,icons:{start:null,end:"auto"},menu:null},
_create:function(){this.element.closest("form").unbind("reset"+e).bind("reset"+e,function(){var a=f(this);setTimeout(function(){a.find(":oj-button").each(function(){f(this).data("oj-ojButton").ep(!1)}).length||a.unbind("reset"+e)},1)});"boolean"!==typeof this.options.disabled&&(this.options.disabled=!!this.element.prop("disabled"));this.Yn=this.eventNamespace+"menu";this.YO();this.Ow=!!this.Db.attr("title");var a=this,b=this.options,h="checkbox"===this.type||"radio"===this.type,k=h?"":"oj-active";
this.Db.addClass(g);this.hc.bind("mouseenter"+this.eventNamespace,function(){b.disabled||(this===d&&a.Db.addClass("oj-active"),a.Db.addClass("oj-hover").removeClass("oj-default"))}).bind("mouseleave"+this.eventNamespace,function(){a.Db.removeClass("oj-hover");b.disabled||(a.Db.removeClass(k),a.$f())}).bind("click"+this.eventNamespace,function(a){b.disabled&&(a.preventDefault(),a.stopImmediatePropagation())});this.element.attr("role","button").bind("focus"+this.eventNamespace,function(){a.Db.addClass("oj-focus").removeClass("oj-default")}).bind("blur"+
this.eventNamespace,function(){a.Db.removeClass("oj-focus");a.$f()});h&&(this.element.bind("change"+this.eventNamespace,function(b){a.ep(!0);var c=f(this).closest(":oj-buttonset").data("oj-ojButtonset"),d=c&&c.Kt(c.Dc);c&&void 0!==d&&(c.lD=b,c._setOption("checked",d))}),this.hc.bind("mousedown"+this.eventNamespace,function(){b.disabled||(c=this,a.document.one("mouseup",function(){c=null}))}).bind("mouseup"+this.eventNamespace,function(){b.disabled||this!==c||a.element.focus()}));"checkbox"===this.type?
(this.hc.bind("click"+this.eventNamespace,function(){if(b.disabled)return!1}),this.element.bind("keyup"+this.eventNamespace,function(c){c.keyCode===f.ui.keyCode.ENTER&&(b.disabled||a.element.click())})):"radio"===this.type?(this.hc.bind("click"+this.eventNamespace,function(){if(b.disabled)return!1}),this.element.bind("keyup"+this.eventNamespace,function(c){c.keyCode!==f.ui.keyCode.ENTER||a.element[0].checked||b.disabled||(a.element[0].checked=!0,a.element.change(),a.element.click())})):(this.hc.bind("mousedown"+
this.eventNamespace,function(c){if(b.disabled)return!1;1===c.which&&(f(this).addClass("oj-active").removeClass("oj-default"),d=this,a.document.one("mouseup",function(){d=null}))}).bind("mouseup"+this.eventNamespace,function(){if(b.disabled)return!1;f(this).removeClass("oj-active");a.$f()}).bind("keydown"+this.eventNamespace,function(a){if(b.disabled)return!1;a.keyCode!==f.ui.keyCode.SPACE&&a.keyCode!==f.ui.keyCode.ENTER||f(this).addClass("oj-active").removeClass("oj-default")}).bind("keyup"+this.eventNamespace+
" blur"+this.eventNamespace,function(){f(this).removeClass("oj-active");a.$f()}),this.hc.is("a")&&(h=this.hc.attr("tabindex"),("undefined"===h||null===h||isNaN(h)||0>parseInt(h,10))&&this.hc.attr("tabindex","0"),this.hc.bind("keyup"+this.eventNamespace,function(a){a.keyCode===f.ui.keyCode.SPACE&&f(this).click()})));this._setOption("disabled",b.disabled);this.FO();this.ME();this.$f();this._super()},YO:function(){var a;if(this.element.is("input[type\x3dcheckbox]"))this.type="checkbox";else if(this.element.is("input[type\x3dradio]"))this.type=
"radio";else if(this.element.is("input[type\x3dbutton],input[type\x3dsubmit],input[type\x3dreset]"))this.type="input";else if(this.element.is("button,a"))this.type="button";else throw Error("JET Button not supported on this element type");"checkbox"===this.type||"radio"===this.type?(a="label[for\x3d'"+this.element.attr("id")+"']",this.hc=this.element.siblings().filter(a).addClass("oj-button-label"),this.element.addClass("oj-helper-hidden-accessible").add(this.hc).wrapAll("\x3cspan\x3e\x3c/span\x3e"),
this.Db=this.element.parent(),(a=this.element[0].checked)&&this.Db.addClass("oj-selected").removeClass("oj-default"),this.element.attr("aria-pressed",a)):this.Db=this.hc=this.element},widget:function(){return this.Db},_destroy:function(){this.dE();this.element.removeClass("oj-helper-hidden-accessible").removeAttr("role").removeAttr("aria-pressed");var a="checkbox"===this.type||"radio"===this.type;a||this.Db.removeClass(g+" "+h+" "+k);this.hc.html(this.hc.find(".oj-button-text").html());if(a){this.hc.removeClass("oj-button-label");
var b=this;setTimeout(function(){b.Db.parent().length&&b.element.unwrap()},0)}else this.Ow||this.Db.removeAttr("title");c===this.hc[0]&&(c=null)},Gy:function(){this.Db.removeClass("oj-active oj-hover oj-focus");this.$f()},_setOption:function(a,b,c){this._super(a,b,c);switch(a){case "disabled":b=!!b;this.element.is("a")||(this.element.prop("disabled",b),this.widget().toggleClass("oj-enabled",!b),this.Db.removeAttr("aria-disabled"));b?(this.widget().removeClass("oj-active oj-default oj-hover oj-focus"),
this.vt(null,null,!0)):this.$f();break;case "label":this.IR();break;case "display":"input"!==this.type&&this.Fq();break;case "icons":this.DE(!0);break;case "menu":"auto"===this.options.icons.end&&this.DE(!1),this.ME()}},refresh:function(){this._super()},ep:function(a){"radio"===this.type?(a?b(this.element[0]):this.element).each(function(){var a=f(this).data("oj-ojButton");this.checked?(a.Db.addClass("oj-selected").removeClass("oj-default"),a.element.attr("aria-pressed","true")):(a.Db.removeClass("oj-selected"),
a.$f(),a.element.attr("aria-pressed","false"))}):"checkbox"===this.type&&(this.element[0].checked?(this.Db.addClass("oj-selected").removeClass("oj-default"),this.element.attr("aria-pressed","true")):(this.Db.removeClass("oj-selected"),this.$f(),this.element.attr("aria-pressed","false")))},FO:function(){var a=!1;null===this.options.label&&(a=!0,this.options.label="input"===this.type?this.hc.val():this.hc.html());if("input"===this.type)this.FE();else{var a=this.GR(a),b=this.Gq(!0),c=this.Gq(!1);this.Fq(a,
b,c)}},GR:function(a){var b=this.hc,c=f("\x3cspan class\x3d'oj-button-text'\x3e\x3c/span\x3e",this.document[0]);a?c.append(b.contents()):(b.empty(),c.text(this.options.label));b.append(c);return c},IR:function(){if("input"===this.type)this.FE();else{var a=this.hc.find(".oj-button-text");a.text(this.options.label);this.Fq(a)}},FE:function(){this.options.label&&this.element.val(this.options.label)},DE:function(a){if("input"!==this.type){var b;a&&(b=this.Gq(!0));a=this.Gq(!1);this.Fq(void 0,b,a)}},Gq:function(a){if(a){a=
"oj-button-icon-start";var b=this.options.icons.start,c="_lastStartIcon",d="prependTo"}else a="oj-button-icon-end",b=this.vB(),c="_lastEndIcon",d="appendTo";var e=this.hc.find("."+a);b?(e.length?e.removeClass(this[c]):e=f("\x3cspan\x3e\x3c/span\x3e").addClass(a)[d](this.hc),e.addClass(b)):e.remove();this[c]=b;return!!b},vB:function(){var a=this.options.icons;return"auto"===a.end?this.Qp()?"oj-component-icon oj-button-menu-dropdown-icon":null:a.end},Fq:function(a,b,c){void 0===a&&(a=this.hc.find(".oj-button-text"));
void 0===b&&(b=!!this.options.icons.start);void 0===c&&(c=!!this.vB());var d=b&&c;c=b||c;var e="icons"===this.options.display;c&&e?(a.addClass("oj-helper-hidden-accessible"),this.Ow||(a=a.text(),this.Db.attr("title",f.trim(a)))):(a.removeClass("oj-helper-hidden-accessible"),this.Ow||this.Db.removeAttr("title"));b=c?e?d?"oj-button-icons-only":"oj-button-icon-only":d?"oj-button-text-icons":b?"oj-button-text-icon-start":"oj-button-text-icon-end":"oj-button-text-only";this.Db.removeClass(k).addClass(b)},
ME:function(){this.dE();var a=this.Qp();if(a){var b=this;this.element.attr("aria-haspopup",!0).on("keydown"+this.Yn,function(c){return c.which===f.ui.keyCode.DOWN?(b.SE(c,"firstItem",a),!1):c.which===f.ui.keyCode.ESCAPE?(b.vt(c,a),!1):!0}).on("click"+this.Yn,function(c){a.Zo||b.jS(c,a);return a.Zo=!1});a.widget().on("oj__dismiss"+this.Yn,function(a){b.UC(a)}).on("ojbeforeshow"+this.Yn,function(a){b.IC||b.UC(a);b.IC=!1})}},dE:function(){this.element.removeAttr("aria-haspopup").off(this.Yn)},Qp:function(){var a=
this.options.menu;a&&(a=f(a).data("oj-ojMenu"));return a&&this.element.not("input")?a:null},SE:function(a,b,c){this.options.disabled||(c||(c=this.Qp()),c&&(this.Db.addClass("oj-selected").removeClass("oj-default"),this.IC=!0,c.show(a,{launcher:this.element,focus:b}),this.VC=!0))},vt:function(a,b,c){if(c||!this.options.disabled)b||(b=this.Qp()),b&&(b.Ds(a,!0),b.Yo(a))},UC:function(){"button"===this.type&&(this.Db.removeClass("oj-selected"),this.$f());this.VC=!1},jS:function(a,b){this.VC?this.vt(a,
b):this.SE(a,"none",b)},$f:function(){this.Db.is(".oj-active, .oj-disabled, .oj-selected, .oj-hover, .oj-focus")?this.Db.removeClass("oj-default"):this.Db.addClass("oj-default")}});a.Fa("oj.ojButtonset",f.oj.baseComponent,{Ou:"button, input[type\x3dbutton], input[type\x3dsubmit], input[type\x3dreset], input[type\x3dcheckbox], input[type\x3dradio], a",widgetEventPrefix:"oj",options:{checked:void 0,focusManagement:"oneTabstop",optionChange:null},wE:function(a,b){var c=f.type(a);if("string"===c||"null"===
c)return(c=((c=b[0].name)||1>=b.length)&&b.filter("input[type\x3dradio][name\x3d"+c+"]").length===b.length&&(null===a||b.filter("[value\x3d"+a+"]").length))&&b.each(function(){this.checked=this.value===a}),c;if("array"===c){var c=b.filter("input[type\x3dcheckbox]").length===b.length,d;(c=c&&a.concat().sort().every(function(a){var c=a!==d&&b.filter("[value\x3d"+a+"]").length;d=a;return c}))&&b.each(function(){this.checked=-1<a.indexOf(this.value)});return c}return!1},Kt:function(a){var b=void 0,c=
null,d=null;a.each(function(){if("input"!==this.tagName.toLowerCase())return b=void 0,!1;var a=this.type.toLowerCase(),e;if("radio"===a)a=!0,e=this.name.toLowerCase();else if("checkbox"===a)a=!1,e=null;else return b=void 0,!1;if(void 0!==b&&(a!==c||e!==d||c&&!d))return b=void 0,!1;void 0===b?(b=a?this.checked?this.value:null:this.checked?[this.value]:[],c=a,d=e):this.checked&&(c?b=this.value:b.push(this.value))});return b},kL:function(a,b){return a===b?!0:"array"===f.type(a)&&"array"===f.type(b)&&
!f(a).not(b).length&&!f(b).not(a).length},_create:function(){this.element.addClass("oj-buttonset oj-component").attr("role","group");this.Cb(!0);this._super()},Zg:function(a,b){a.show(b,{launcher:this.element.find(":oj-button[tabindex\x3d0]"),focus:"menu"})},_setOption:function(a,b){var c=!1,d=this.lD;this.lD=null;"disabled"===a&&this.Dc.ojButton("option",a,b);"checked"!==a||d||null===b&&void 0===this.Kt(this.Dc)||(this.wE(b,this.Dc)?this.Dc.each(function(){f(this).data("oj-ojButton").ep(!1)}):c=
!0);c||(c=this.options[a],this._super(a,b),"checked"===a&&this.dg(a,c,b,this.kL,d))},dg:function(a,b,c,d,e){d.call(this,b,c)||this._trigger("optionChange",e,{option:a,previousValue:b,value:c,optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}})},refresh:function(){this._super();this.Cb(!1)},Cb:function(a){var b=this;this.zj="rtl"===this.uc();this.Dc=this.element.find(this.Ou);if(a&&!this.wE(this.options.checked,this.Dc)){var c=this.Kt(this.Dc);this.options.checked=void 0===c?null:c}this.Dc.filter(":oj-button").ojButton("refresh").each(function(){f(this).data("oj-ojButton").ep(!1)}).end().not(":oj-button").ojButton().end().map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-corner-start oj-buttonset-corner-end").filter(":first").addClass("oj-buttonset-corner-start").end().filter(":last").addClass("oj-buttonset-corner-end").end().end();
a&&this.options.disabled&&this.Dc.ojButton("option","disabled",!0);"oneTabstop"===this.options.focusManagement&&(this.Dc.unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){b.xu(a,f(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){f(this).ojButton("option","disabled")||b.nj(f(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.nj(f(this))}),this.xg=this.Dc.filter(function(){return!f(this).ojButton("option",
"disabled")}),this.Gu(a))},Gu:function(a){var b=f(this.ij);this.ij=void 0;this.Dc.attr("tabindex","-1");a=a||!b.is(this.xg)?this.xg.first():b;this.nj(a)},Uu:function(a){var c=this.xg;return a.map(function(a,d){if("radio"!=d.type||d.checked||""==d.name)return d;var e=b(d,c).filter(":checked");return e.length?e[0]:d})},nj:function(a){a=this.Uu(a);var b=a[0],c=this.ij;b!==c&&(f(c).attr("tabindex","-1"),a.attr("tabindex","0"),this.ij=b)},xu:function(a,b){switch(a.which){case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.preventDefault();
var c=this.xg,d=c.length;if(2>d)break;var e=c.index(b);c.eq((e+(a.which==f.ui.keyCode.RIGHT^this.zj?1:-1)+d)%d).focus();break;case f.ui.keyCode.UP:case f.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-buttonset oj-component").removeAttr("role");"oneTabstop"===this.options.focusManagement&&this.Dc.attr("tabindex","0");this.Dc.map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-corner-start oj-buttonset-corner-end").end().ojButton("destroy")}});
var d,c,e=".ojButton",g="oj-button oj-component oj-enabled oj-default",h="oj-hover oj-active oj-selected",k="oj-button-icons-only oj-button-icon-only oj-button-text-icons oj-button-text-icon-start oj-button-text-icon-end oj-button-text-only"})()});
//# sourceMappingURL=oj-modular.map