/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtChart"],function(a,f){a.yh=function(a){this.f=a};o_("ChartAxis",a.yh,a);a.yh.prototype.getTitle=function(){return this.f?this.f.title:null};a.b.g("ChartAxis.prototype.getTitle",{getTitle:a.yh.prototype.getTitle});a.yh.prototype.oi=function(){return this.f?this.f.bounds:null};a.b.g("ChartAxis.prototype.getBounds",{oi:a.yh.prototype.oi});a.Re=function(a){this.f=a};o_("SparkChartDataItem",a.Re,a);a.Re.prototype.Cn=
function(){return this.f?this.f.borderColor:null};a.b.g("SparkChartDataItem.prototype.getBorderColor",{Cn:a.Re.prototype.Cn});a.Re.prototype.nd=function(){return this.f?this.f.color:null};a.b.g("SparkChartDataItem.prototype.getColor",{nd:a.Re.prototype.nd});a.Re.prototype.getDate=function(){return this.f?this.f.date:null};a.b.g("SparkChartDataItem.prototype.getDate",{getDate:a.Re.prototype.getDate});a.Re.prototype.getFloatValue=function(){return this.f?this.f.floatValue:null};a.b.g("SparkChartDataItem.prototype.getFloatValue",
{getFloatValue:a.Re.prototype.getFloatValue});a.Re.prototype.pg=function(){return this.f?this.f.value:null};a.b.g("SparkChartDataItem.prototype.getValue",{pg:a.Re.prototype.pg});a.Fa("oj.ojChart",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{categoryFilter:null,categoryHighlight:null,select:null,viewportChange:null},pf:function(a,d,c){return DvtChart.newInstance(a,d,c)},Uy:function(){this._super();this.options.styleDefaults||(this.options.styleDefaults={});if(!this.options.styleDefaults.colors){var b=
new a.zg;this.options.styleDefaults.colors=b.ll()}},Ue:function(){var a=this._super();a.push("oj-chart");return a},Ki:function(){var a=this._super();a["oj-chart-footnote"]={path:"footnote/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-slice-label"]={path:"styleDefaults/sliceLabelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-subtitle"]={path:"subtitle/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-title"]={path:"title/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-xaxis-tick-label"]=
{path:"xAxis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-xaxis-title"]={path:"xAxis/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-yaxis-tick-label"]={path:"yAxis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-yaxis-title"]={path:"yAxis/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-y2axis-tick-label"]={path:"y2Axis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-y2axis-title"]={path:"y2Axis/titleStyle",property:"CSS_TEXT_PROPERTIES"};
a["oj-legend"]={path:"legend/textStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-legend-title"]={path:"legend/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-pan-icon"]={path:"_resources/panUp",property:"CSS_URL"};a["oj-chart-pan-icon oj-active"]={path:"_resources/panDown",property:"CSS_URL"};a["oj-chart-select-icon"]={path:"_resources/selectUp",property:"CSS_URL"};a["oj-chart-select-icon oj-active"]={path:"_resources/selectDown",property:"CSS_URL"};a["oj-chart-zoom-icon"]={path:"_resources/zoomUp",
property:"CSS_URL"};a["oj-chart-zoom-icon oj-active"]={path:"_resources/zoomDown",property:"CSS_URL"};return a},Rl:function(){var a=this._super();a["DvtChartBundle.DEFAULT_GROUP_NAME"]=this.vc("labelDefaultGroupName",["groupName"]);a["DvtChartBundle.EMPTY_TEXT"]=this.vc("msgNoData");a["DvtChartBundle.LABEL_SERIES"]=this.vc("labelSeries",["seriesName"]);a["DvtChartBundle.LABEL_GROUP"]=this.vc("labelGroup",["groupName"]);a["DvtChartBundle.LABEL_VALUE"]=this.vc("labelValue",["value"]);a["DvtChartBundle.LABEL_TARGET_VALUE"]=
this.vc("labelTargetValue",["targetValue"]);a["DvtChartBundle.LABEL_X"]=this.vc("labelX",["x"]);a["DvtChartBundle.LABEL_Y"]=this.vc("labelY",["y"]);a["DvtChartBundle.LABEL_Z"]=this.vc("labelZ",["z"]);a["DvtChartBundle.LABEL_LOW"]=this.vc("labelLow",["low"]);a["DvtChartBundle.LABEL_HIGH"]=this.vc("labelHigh",["high"]);a["DvtChartBundle.LABEL_OTHER"]=this.vc("labelOther");a["DvtChartBundle.PAN"]=this.vc("tooltipPan");a["DvtChartBundle.MARQUEE_SELECT"]=this.vc("tooltipSelect");a["DvtChartBundle.MARQUEE_ZOOM"]=
this.vc("tooltipZoom");return a},Li:function(a){var d=a&&a.getType?a.getType():null;if(d===DvtSelectionEvent.TYPE){if(d=a.getSelection()){for(var c=[],e=0;e<d.length;e++){var f={id:d[e].getId(),series:d[e].getSeries(),group:d[e].getGroup()};c.push(f)}this.options.selectedItems=c;a={items:c,endGroup:a.getEndGroup(),startGroup:a.getStartGroup(),xMax:a.getXMax(),xMin:a.getXMin(),yMax:a.getYMax(),yMin:a.getYMin()};this._trigger("select",null,a)}}else if(d===DvtCategoryHideShowEvent.TYPE_HIDE||d===DvtCategoryHideShowEvent.TYPE_SHOW){c=
d===DvtCategoryHideShowEvent.TYPE_HIDE?"out":"in";f=this.options.series;for(e=0;e<f.length;e++)f[e].name==a.getCategory()&&(f[e].visibility=d===DvtCategoryHideShowEvent.TYPE_HIDE?"hidden":"visible");this._trigger("categoryFilter",null,{category:a.getCategory(),type:c})}else d===DvtCategoryRolloverEvent.TYPE_OVER||d===DvtCategoryRolloverEvent.TYPE_OUT?(e=d===DvtCategoryRolloverEvent.TYPE_OVER?"on":"off",this._trigger("categoryHighlight",null,{categories:[a.getCategory()],type:e})):d===DvtChartViewportChangeEvent.TYPE?
(a={endGroup:a.getEndGroup(),startGroup:a.getStartGroup(),xMax:a.getXMax(),xMin:a.getXMin(),yMax:a.getYMax(),yMin:a.getYMin()},this._trigger("viewportChange",null,a)):this._super(a)},ns:function(){null==this.options._resources&&(this.options._resources={});var b=this.options._resources;b.overviewGrippy=a.ha.ab("resources/internal-deps/dvt/chart/drag_horizontal.png");b.panCursorDown=a.ha.ab("resources/internal-deps/dvt/chart/hand-closed.cur");b.panCursorUp=a.ha.ab("resources/internal-deps/dvt/chart/hand-open.cur")},
getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getTitle:function(){return this.ta.getAutomation().getTitle()},getGroup:function(a){return this.ta.getAutomation().getGroup(a)},getSeries:function(a){return this.ta.getAutomation().getSeries(a)},getGroupCount:function(){return this.ta.getAutomation().getGroupCount()},getSeriesCount:function(){return this.ta.getAutomation().getSeriesCount()},getDataItem:function(b,d){var c=this.ta.getAutomation();return new a.Fb(c.getDataItem(b,
d))},getLegend:function(){var b=this.ta.getAutomation();return new a.Jj(b.getLegend())},getPlotArea:function(){var b=this.ta.getAutomation();return new a.to(b.getPlotArea())},getXAxis:function(){var b=this.ta.getAutomation();return new a.yh(b.getXAxis())},getYAxis:function(){var b=this.ta.getAutomation();return new a.yh(b.getYAxis())},getY2Axis:function(){var b=this.ta.getAutomation();return new a.yh(b.getY2Axis())}});a.to=function(a){this.f=a};o_("ChartPlotArea",a.to,a);a.to.prototype.oi=function(){return this.f?
this.f.bounds:null};a.b.g("ChartPlotArea.prototype.getBounds",{oi:a.to.prototype.oi});a.Jj=function(a){this.f=a};o_("ChartLegend",a.Jj,a);a.Jj.prototype.getTitle=function(){return this.f?this.f.title:null};a.b.g("ChartLegend.prototype.getTitle",{getTitle:a.Jj.prototype.getTitle});a.Jj.prototype.oi=function(){return this.f?this.f.bounds:null};a.b.g("ChartLegend.prototype.getBounds",{oi:a.Jj.prototype.oi});a.Fa("oj.ojSparkChart",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",pf:function(a,
d,c){return DvtSparkChart.newInstance(a,d,c)},Ue:function(){var a=this._super();a.push("oj-sparkchart");return a},Zf:function(){this.options.shortDesc=this.element.attr("title");this._super()},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getDataItem:function(b){var d=this.ta.getAutomation();return new a.Re(d.getDataItem(b))}});a.Fb=function(a){this.f=a};o_("ChartDataItem",a.Fb,a);a.Fb.prototype.getGroup=function(){return this.f?this.f.group:null};
a.b.g("ChartDataItem.prototype.getGroup",{getGroup:a.Fb.prototype.getGroup});a.Fb.prototype.getSeries=function(){return this.f?this.f.series:null};a.b.g("ChartDataItem.prototype.getSeries",{getSeries:a.Fb.prototype.getSeries});a.Fb.prototype.Cn=function(){return this.f?this.f.borderColor:null};a.b.g("ChartDataItem.prototype.getBorderColor",{Cn:a.Fb.prototype.Cn});a.Fb.prototype.nd=function(){return this.f?this.f.color:null};a.b.g("ChartDataItem.prototype.getColor",{nd:a.Fb.prototype.nd});a.Fb.prototype.je=
function(){return this.f?this.f.label:null};a.b.g("ChartDataItem.prototype.getLabel",{je:a.Fb.prototype.je});a.Fb.prototype.pg=function(){return this.f?this.f.value:null};a.b.g("ChartDataItem.prototype.getValue",{pg:a.Fb.prototype.pg});a.Fb.prototype.EG=function(){return this.f?this.f.targetValue:null};a.b.g("ChartDataItem.prototype.getTargetValue",{EG:a.Fb.prototype.EG});a.Fb.prototype.le=function(){return this.f?this.f.tooltip:null};a.b.g("ChartDataItem.prototype.getTooltip",{le:a.Fb.prototype.le});
a.Fb.prototype.HG=function(){return this.f?this.f.x:null};a.b.g("ChartDataItem.prototype.getX",{HG:a.Fb.prototype.HG});a.Fb.prototype.IG=function(){return this.f?this.f.y:null};a.b.g("ChartDataItem.prototype.getY",{IG:a.Fb.prototype.IG});a.Fb.prototype.JG=function(){return this.f?this.f.z:null};a.b.g("ChartDataItem.prototype.getZ",{JG:a.Fb.prototype.JG});a.Fb.prototype.isSelected=function(){return this.f?this.f.selected:!1};a.b.g("ChartDataItem.prototype.isSelected",{isSelected:a.Fb.prototype.isSelected})});
//# sourceMappingURL=oj-modular.map