/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(a,f){a.Fa("oj.ojCheckboxset",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:null},refresh:function(){this._super();this.wg=this.Dp().filter(".oj-checkbox")._ojRadioCheckbox("refresh").end().not(".oj-checkbox")._ojRadioCheckbox().end();this.Cb()},widget:function(){return this.OH},_ComponentCreate:function(){this._super();if(this.element.is("fieldset"))throw Error("ojCheckboxset cannot be bound to a fieldset. Use a div instead.");
this.wg=this.Dp()._ojRadioCheckbox();this.OH=this.element.addClass("oj-checkboxset oj-component").attr("role","group");this._on(this.vf);this.Cb()},Dp:function(){var b=this.element.find("input[type\x3dcheckbox]:first");0===b.length&&a.T.warn("Could not find any input type\x3dcheckbox within this element");b=b.attr("name");return void 0===b?this.element.find("input[type\x3dcheckbox]").not("[name]"):this.element.find("input[type\x3dcheckbox][name\x3d"+b+"]")},Zg:function(a,d){var c=this.element.find("input[type\x3dcheckbox]"),
e=c.filter(":checked"),c=e.length?e:c.first();a.show(d,{launcher:c,focus:"menu"})},Cb:function(){this.options.disabled&&this.disable()},vf:{change:function(a){this.Lo(a)}},Lo:function(a){this._super(a)},zh:function(){return this.Rj()},Hg:function(a){this.wg._ojRadioCheckbox("option","checked",!1);if(null!=a)for(var d=0;d<a.length;d++){var c="[value\x3d'"+a[d]+"']";void 0!==c&&void 0!==this.wg&&(c=this.wg.filter(c),void 0!==c&&0<c.length&&(c.prop("checked")||c._ojRadioCheckbox("option","checked",!0)))}},
Rj:function(){var a=[],d=this.wg.filter(":checked");if(0===d.length)return null;d.each(function(){a.push(f(this).val())});return a},_InitOptions:function(b,d){var c,e=[];this._super(b,d);a.ud.vi([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"title",defaultOptionValue:""},{attribute:"placeholder",defaultOptionValue:""},{attribute:"required",defaultOptionValue:"optional",coerceDomValue:!0,validateOption:!0}],d,this);null==this.options.value&&(c=this.Dp(),c=c.filter(":checked"),
0===c.length?c=null:(c.each(function(){e.push(f(this).val())}),c=e),this.options.value=c)},_GetDefaultStyleClass:function(){return"oj-checkboxset"},rf:function(){return this.Dp()},xs:function(a){var d=this.OH;(a="required"==a?!0:!1)&&d?d.attr("aria-required",a):d.removeAttr("aria-required")},_setOption:function(a,d,c){this._super(a,d,c);"disabled"===a&&this.wg._ojRadioCheckbox("option",a,d)},getNodeBySubId:function(a){var d=this._super(a);return d||(a=a.subId,"oj-checkboxset-inputs"!==a)?d||null:
this.wg},_destroy:function(){this._super();this.element.removeClass("oj-checkboxset oj-enabled oj-component").removeAttr("role");this.wg&&this.wg._ojRadioCheckbox("destroy")}})});
//# sourceMappingURL=oj-modular.map