/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){var b=0;a.Fa("oj.ojCollapsible",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{expanded:!1,disabled:null,expandOn:"click",expandArea:"disclosureIcon",beforeExpand:null,expand:null,beforeCollapse:null,collapse:null,optionChange:null},_ComponentCreate:function(){this._super();this.AF=f();this.element.addClass("oj-collapsible oj-component");this.wD();this.Pb()},Zg:function(a,b){a.show(b,{launcher:this.element.find(".oj-collapsible-header-icon").first(),
focus:"menu"})},EL:function(){var a=this.options.expanded?"oj-collapsible-open-icon":"oj-collapsible-close-icon";(this.ye()?f("\x3cspan\x3e"):f("\x3ca href\x3d'#'\x3e")).addClass("oj-component-icon oj-clickable-icon oj-collapsible-header-icon "+a).attr("aria-labelledby",this.header.attr("id")).prependTo(this.header)},JA:function(){this.header.children(".oj-collapsible-header-icon").remove()},_destroy:function(){this.cA();this.element.removeClass("oj-collapsible oj-component oj-expanded oj-collapsed oj-disabled");
this.ye()&&this.sm(this.header).removeAttr("tabIndex");this.header.removeClass("oj-collapsible-header").each(function(){/^oj-collapsible/.test(this.id)&&this.removeAttribute("id")});this.rm().removeAttr("role").removeAttr("aria-controls").removeAttr("aria-expanded").removeAttr("aria-disabled");this.JA();this.sm(this.content).removeAttr("tabIndex");this.content.css("display","").removeAttr("aria-hidden").removeAttr("tabIndex").removeClass("oj-component-content oj-collapsible-content").each(function(){/^oj-collapsible/.test(this.id)&&
this.removeAttribute("id")})},cA:function(){this.ln();this.content&&(this.content.unwrap(),this.vg=null)},ye:function(){return this.element.hasClass("oj-disabled")},wB:function(){return"header"==this.options.expandArea?"\x3e .oj-collapsible-header":"\x3e .oj-collapsible-header \x3e .oj-collapsible-header-icon"},_setOption:function(a,b,e){"expanded"===a?this.zR(b):("expandOn"===a||"expandArea"===a?(this.ln(),this._super(a,b,e),this.pj()):this._super(a,b,e),"disabled"===a&&(this.header.add(this.header.next()),
this.element.toggleClass("oj-disabled",!!b)))},hj:function(a){if(!a.altKey&&!a.ctrlKey){var b=f.ui.keyCode;switch(a.keyCode){case b.SPACE:case b.ENTER:this.jF(a)}}},refresh:function(){this._super();this.cA();this.wD();this.JA();this.Pb()},wD:function(){this.header=this.element.children(":first-child").addClass("oj-collapsible-header");this.content=this.header.next().addClass("oj-collapsible-content oj-component-content");this.content.wrap("\x3cdiv\x3e\x3c/div\x3e");this.vg=this.content.parent().addClass("oj-collapsible-wrapper");
this.options.disabled&&this.element.addClass("oj-disabled");this.ye()&&this.sm(this.header).attr("tabIndex",-1)},Pb:function(){var a=this.header,c=this.content,e=this.options,f="oj-collapsible-"+(this.element.attr("id")||++b),h=a.attr("id"),k=c.attr("id");h||a.attr("id",f+"-header");k||(k=f+"-content",c.attr("id",k));this.EL();a=this.rm();a.attr("role","button").attr("aria-controls",k);this.ye()&&a.attr("aria-disabled",!0);this.ye()||this.zE(e.expanded?"0":"-1");e.expanded?(this.element.removeClass("oj-collapsed"),
this.element.addClass("oj-expanded"),c.attr({"aria-hidden":"false"}),a.attr("aria-expanded","true")):(this.element.removeClass("oj-expanded"),this.element.addClass("oj-collapsed"),this.vg.css({"max-height":0,"overflow-y":"hidden",display:"none"}),this.vg.css("max-height",0),c.attr({"aria-hidden":"true"}),a.attr("aria-expanded","false"));this.pj()},zR:function(a){a!==this.options.expanded&&(a?this.expand(!0):this.collapse(!0))},pj:function(){var a={keydown:this.hj},b=this.options.expandOn;if(b){var e=
this;f.each(b.split(" "),function(b,c){a[c]=e.jF})}b=this.element.find(this.wB());this._on(b,a);this._on(this.vg,{transitionend:this.Pq,webkitTransitionEnd:this.Pq,otransitionend:this.Pq,oTransitionEnd:this.Pq});this.ye()||(this._on(this.element,{ojexpand:this.ZA,ojcollapse:this.ZA,ojfocus:this.iB,ojfocusout:this.iB}),this._hoverable(b),this._focusable(b),this.sK(b))},ln:function(){this._off(this.element.find(this.wB()));this.vg&&this._off(this.vg);this._off(this.element.add(this.content))},jF:function(a){this.ye()||
(this.options.expanded?this.collapse(!0,a):this.expand(!0,a),a.preventDefault(),a.stopPropagation(),this.header.find(".oj-collapsible-header-icon").focus())},ZA:function(a){if(!this.ye()&&a.target===this.element[0]&&!a.isDefaultPrevented()){var b=this.element,e=this.options,f=this.content,h=this.vg,k="ojcollapse"===a.type;a.preventDefault();e.expanded=!k;h.br=h.outerHeight();k?(h.removeClass("oj-collapsible-transition"),h.css({"max-height":h.br,"overflow-y":"hidden"}),setTimeout(function(){h.addClass("oj-collapsible-transition").css({"max-height":0});
b.removeClass("oj-expanded");b.addClass("oj-collapsed")},10)):(h.show(),setTimeout(function(){h.br+=f.outerHeight();h.addClass("oj-collapsible-transition").css({"max-height":h.br});b.removeClass("oj-collapsed");b.addClass("oj-expanded")},1));this.header.find(".oj-collapsible-header-icon").toggleClass("oj-collapsible-open-icon",!k).toggleClass("oj-collapsible-close-icon",k||!1).end();this.content.attr("aria-hidden",k);this.rm().attr("aria-expanded",!k);this.zE(k?"-1":"0")}},iB:function(a){if(this.ye())return null;
"ojfocusout"==a.type?(this.rm().attr("tabIndex",-1),a.preventDefault(),a.stopPropagation()):"ojfocus"==a.type&&(this.rm().attr("tabIndex",0).focus(),a.preventDefault(),a.stopPropagation())},rm:function(){return this.sm(this.header).first()},zE:function(a){return this.sm(this.content).attr("tabIndex",a)},sm:function(a){return this.ye()?a.find("span"):a.find("a,:input")},expand:function(a,b){if(!this.ye()){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeExpand",b,e)||(this._trigger("expand",
b,e),this.dg("expanded",!1,!0,b?!0:!1))}},collapse:function(a,b){if(!this.ye()){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeCollapse",b,e)||(this._trigger("collapse",b,e),this.dg("expanded",!0,!1,b?!0:!1))}},Pq:function(a){this.ye()||("max-height"==(a.originalEvent?a.originalEvent.propertyName:null)&&(a.preventDefault(),a.stopPropagation()),this.options.expanded?this.vg.css({"max-height":9999,"overflow-y":""}):this.vg.hide(),this.vg.removeClass("oj-collapsible-transition"))},
sK:function(a){this.AF=this.AF.add(a);this._on(a,{mousedown:function(a){f(a.currentTarget).addClass("oj-active")},mouseup:function(a){f(a.currentTarget).removeClass("oj-active")}})},dg:function(a,b,e,f){this._trigger("optionChange",f,{option:a,previousValue:b,value:e,optionMetadata:{writeback:f?"shouldWrite":"shouldNotWrite"}})},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-collapsible-content":return this.content;case "oj-collapsible-header":return this.header;
case "oj-collapsible-header-icon":return this.header.find("."+a)[0]}return null}})})()});
//# sourceMappingURL=oj-modular.map