var o_a=this;function o_(a,f,b){a=a.split(".");b=b||o_a;a[0]in b||!b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===f?b=b[d]?b[d]:b[d]={}:b[d]=f};define(["require","ojL10n!ojtranslations/nls/ojtranslations"],function(a,f){var b={};"undefined"!==typeof window?b=window:"undefined"!==typeof self&&(b=self);var d=b.oj,c=b.oj={version:"1.0",build:"2787",revision:"8613",noConflict:function(){b.oj=d}};c.T={};o_("Logger",c.T,c);c.T.jI=0;o_("Logger.LEVEL_NONE",c.T.jI,c);c.T.yo=1;o_("Logger.LEVEL_ERROR",c.T.yo,c);c.T.Mj=2;o_("Logger.LEVEL_WARN",c.T.Mj,c);c.T.Rx=3;o_("Logger.LEVEL_INFO",c.T.Rx,c);c.T.Sx=4;o_("Logger.LEVEL_LOG",
c.T.Sx,c);c.T.vJ="error";c.T.yJ="warn";c.T.wJ="info";c.T.xJ="log";c.T.FA={level:c.T.yo,writer:null};c.T.Ra=c.T.FA;c.T.error=function(b){c.T.sn(c.T.yo,c.T.vJ,arguments)};o_("Logger.error",c.T.error,c);c.T.info=function(b){c.T.sn(c.T.Rx,c.T.wJ,arguments)};o_("Logger.info",c.T.info,c);c.T.warn=function(b){c.T.sn(c.T.Mj,c.T.yJ,arguments)};o_("Logger.warn",c.T.warn,c);c.T.log=function(b){c.T.sn(c.T.Sx,c.T.xJ,arguments)};o_("Logger.log",c.T.log,c);c.T.option=function(b,a){var d={},k;if(0==arguments.length){for(k in c.T.Ra)c.T.Ra.hasOwnProperty(k)&&
(d[k]=c.T.Ra[k]);return d}if("string"===typeof b&&void 0===a)return void 0===c.T.Ra[b]?null:c.T.Ra[b];if("string"===typeof b)c.T.Ra[b]=a;else for(k in b)b.hasOwnProperty(k)&&c.T.option(k,b[k])};o_("Logger.option",c.T.option,c);c.T.sn=function(b,a,d){if(!(c.T.option("level")<b)){var k=c.T.fO();null!=k&&(1==d.length&&d[0]instanceof Function&&(d=[d[0]()]),k[a]&&k[a].apply?k[a].apply(k,d):k[a]&&(k[a]=Function.prototype.bind.call(k[a],k),c.T.sn(b,a,d)))}};c.T.fO=function(){var b=null;c.T.option("writer")?
b=c.T.option("writer"):void 0!==window&&void 0!==window.console&&(b=window.console);return b};c.T.mW=function(b){return void 0!==c.T.FA[b]};c.b=function(){this.Init()};o_("Object",c.b,c);c.b.t=null;c.b.Wv="oj.Object";c.b.VI=/function\s+([\w\$][\w\$\d]*)\s*\(/;c.b.prototype={};c.b.prototype.constructor=c.b;c.b.g=function(b,a){var d=null,k=null,l;for(l in a)if(a.hasOwnProperty(l)){d=l;k=a[l];break}var f=b.split(".");l=c[f[0]];f=f[2];if(d!=f&&null!=d){var m=l.qv;m||(m={},l.qv=m);m[d]=f;l.prototype[f]=
k}};c.b.oa=function(b,a,d){c.i.ii(b);c.i.FF(a);c.i.HF(d);void 0===a&&(a=c.b);c.i.assert(b!==a,"Class can't extend itself");var k=c.b.fS;k.prototype=a.prototype;b.prototype=new k;b.prototype.constructor=b;b.t=b.superclass=a.prototype;d&&(b.Wv=d)};o_("Object.createSubclass",c.b.oa,c);c.b.cT=function(b,a){var d;c.i.ii(b);c.i.assert(null!=a,"source object cannot be null");for(d in a)a.hasOwnProperty(d)&&(b.prototype[d]=a[d])};o_("Object.copyPropertiesForClass",c.b.cT,c);c.b.fS=function(){};c.b.prototype.iG=
function(b){if(void 0===b)b=this;else if(null===b)return null;return b.constructor};c.b.g("Object.prototype.getClass",{iG:c.b.prototype.iG});c.b.prototype.clone=function(){var b=new this.constructor;c.Ec.dh(b,this);return b};c.b.g("Object.prototype.clone",{clone:c.b.prototype.clone});c.b.prototype.toString=function(){return this.Dx()};c.b.g("Object.prototype.toString",{toString:c.b.prototype.toString});c.b.prototype.Dx=function(){return this.getTypeName()+" Object"};c.b.g("Object.prototype.toDebugString",
{Dx:c.b.prototype.Dx});c.b.getTypeName=function(b){c.i.ii(b);var a=b.Wv;null==a&&(a=b.toString(),a=(a=c.b.VI.exec(a))?a[1]:"anonymous",b.Wv=a);return a};o_("Object.getTypeName",c.b.getTypeName,c);c.b.prototype.getTypeName=function(){return c.b.getTypeName(this.constructor)};c.b.g("Object.prototype.getTypeName",{getTypeName:c.b.prototype.getTypeName});c.b.prototype.Init=function(){c.i.Eb&&c.i.assert(this.getTypeName,"Not an oj.Object");var b=this.constructor;b.fq||c.b.Fu(b)};c.b.g("Object.prototype.Init",
{Init:c.b.prototype.Init});c.b.vT=function(b){c.i.ii(b);b.fq||c.b.Fu(b)};o_("Object.ensureClassInitialization",c.b.vT,c);c.b.prototype.ni=function(b){return this===b};c.b.g("Object.prototype.equals",{ni:c.b.prototype.ni});c.b.An=function(b,a){c.i.ii(a);var d;c.i.vn(a[c.i.vo]);d=new Function("var f\x3darguments.callee; return f._func.apply(f._owner, arguments);");d._owner=b;d._func=a;return d};o_("Object.createCallback",c.b.An,c);c.b.Az=function(b,a){var d=c.i.vo,k=c.i.Hx,l,f;for(l in b)b.hasOwnProperty(l)&&
(f=b[l],"function"!==typeof f||f.hasOwnProperty(d)||(f[d]=l,f[k]=a))};c.b.Fu=function(b){c.i.Eb&&(c.i.ii(b),c.i.assert(!b.fq));b.fq=!0;var a=b.t,d;a&&((a=a.constructor)&&!a.fq&&c.b.Fu(a),c.b.LK(b));a=c.b.getTypeName(b);try{(d=b.InitClass||null)||(d=b.InitClass),d&&d.call(b)}finally{c.i.Eb&&(c.b.Az(b.prototype,a),c.b.Az(b,"static "+a))}};c.b.Zq=function(b,a){if(b===a)return!0;if(typeof b!==typeof a||null===b||null===a)return!1;if(b.constructor===a.constructor){if(Array.isArray(b))return c.b.vL(b,a);
if(b.constructor===Object)return c.b.Ni(b,a);if(b.valueOf&&"function"===typeof b.valueOf)return b.valueOf()===a.valueOf()}return!1};o_("Object.compareValues",c.b.Zq,c);c.b.vL=function(b,a){if(b.length!==a.length)return!1;for(var d=0,k=b.length;d<k;d++)if(!c.b.Zq(b[d],a[d]))return!1;return!0};c.b.Ni=function(b,a){var d,k=!1;if(b===a)return!0;if(!(b instanceof Object&&a instanceof Object)||b.constructor!==a.constructor)return!1;for(d in b)if(k||(k=!0),b.hasOwnProperty(d)&&(!a.hasOwnProperty(d)||b[d]!==
a[d]&&("object"!==typeof b[d]||!c.b.Ni(b[d],a[d]))))return!1;for(d in a)if(k||(k=!0),a.hasOwnProperty(d)&&!b.hasOwnProperty(d))return!1;return k?!0:JSON.stringify(b)===JSON.stringify(a)};c.b.isEmpty=function(b){var a;if(void 0===b||null===b)return!0;for(a in b)if(b.hasOwnProperty(a))return!1;return!0};c.b.LK=function(b){c.b.qv&&c.b.Bz(b,b.t)};c.b.Bz=function(b,a){if(a){var d=a.constructor;c.b.Bz(b,d.t);var d=d.qv,k;if(d)for(k in d)if(d.hasOwnProperty(k)){var l=d[k];if(k!=l){var f=b.prototype;!f.hasOwnProperty(k)&&
f.hasOwnProperty(l)?f[k]=f[l]:!f.hasOwnProperty(l)&&f.hasOwnProperty(k)&&(f[l]=f[k])}}}};c.Vl=function(){return"function"===typeof define&&define.amd};c.i={};o_("Assert",c.i,c);c.i.yT=function(){c.i.Eb=c.i.DEBUG=!0};o_("Assert.forceDebug",c.i.yT,c);c.i.vo="_funcName";c.i.Hx="_className";c.i.uJ=20;c.i.assert=function(b,a){if(c.i.Eb&&!b){var d=a||"",k;if(2<arguments.length){d+="(";for(k=2;k<arguments.length;k+=1)d+=arguments[k];d+=")"}c.i.zc(d,1)}};o_("Assert.assert",c.i.assert,c);c.i.fa=function(){c.i.Eb&&
c.i.zc("Abstract function called",1)};o_("Assert.failedInAbstractFunction",c.i.fa,c);c.i.mb=function(b,a,d){var k;c.i.Eb&&(null!==b?(c.i.Be(a,"function",null,1,!1),k=a.prototype,k.isPrototypeOf(b)||c.i.zc("object '"+b+"' doesn't match prototype "+k,1,d)):c.i.zc("null object doesn't match prototype "+k,1,d))};o_("Assert.assertPrototype",c.i.mb,c);c.i.TS=function(b,a,d){var k;c.i.Eb&&null!==b&&(null!==b?(c.i.Be(a,"function",null,1,!1),k=a.prototype,k.isPrototypeOf(b)||c.i.zc("object '"+b+"' doesn't match prototype "+
k,1,d)):c.i.zc("null object doesn't match prototype "+k,1,d))};o_("Assert.assertPrototypeOrNull",c.i.TS,c);c.i.US=function(b,a,d,k){c.i.Eb&&(a=a.prototype,d=d.prototype,a.isPrototypeOf(b)||d.isPrototypeOf(b)||c.i.zc("object '"+b+"' doesn't match prototype "+a+" or "+d,1,k))};o_("Assert.assertPrototypes",c.i.US,c);c.i.MS=function(b,a){c.i.Eb&&b&&void 0===b.nodeType&&c.i.zc(b+" is not a DOM Node",a+1)};o_("Assert.assertDomNodeOrNull",c.i.MS,c);c.i.hw=function(b,a){c.i.Eb&&(b&&void 0!==b.nodeType||c.i.zc(b+
" is not a DOM Node",a+1))};o_("Assert.assertDomNode",c.i.hw,c);c.i.$e=function(b,a){c.i.Eb&&(c.i.hw(b,1),1!==b.nodeType?c.i.zc(b+" is not a DOM Element",1):a&&b.nodeName!==a&&c.i.zc(b+" is not a "+a+" Element",1))};o_("Assert.assertDomElement",c.i.$e,c);c.i.LS=function(b,a){c.i.Eb&&null!==b&&(c.i.hw(b,1),1!==b.nodeType?c.i.zc(b+" is not a DOM Element",1):a&&b.nodeName!==a&&c.i.zc(b+" is not a "+a+" Element",1))};o_("Assert.assertDomElementOrNull",c.i.LS,c);c.i.Be=function(b,a,d,k,l){!c.i.Eb||null===
b&&l||typeof b===a||(b=b+" is not of type "+a,d&&(b=d+b),k||(k=0),c.i.zc(b,k+1))};o_("Assert.assertType",c.i.Be,c);c.i.Pd=function(b,a){c.i.Eb&&c.i.Be(b,"object",a,1,!1)};o_("Assert.assertObject",c.i.Pd,c);c.i.RS=function(b,a){c.i.Eb&&c.i.Be(b,"object",a,1,!0)};o_("Assert.assertObjectOrNull",c.i.RS,c);c.i.GF=function(b,a){c.i.Eb&&(c.i.Be(b,"string",a,1,!1),c.i.assert(0<b.length,"empty string"))};o_("Assert.assertNonEmptyString",c.i.GF,c);c.i.vn=function(b,a){c.i.Eb&&c.i.Be(b,"string",a,1,!1)};o_("Assert.assertString",
c.i.vn,c);c.i.HF=function(b,a){c.i.Eb&&c.i.Be(b,"string",a,1,!0)};o_("Assert.assertStringOrNull",c.i.HF,c);c.i.ii=function(b,a){c.i.Eb&&c.i.Be(b,"function",a,1,!1)};o_("Assert.assertFunction",c.i.ii,c);c.i.FF=function(b,a){c.i.Eb&&c.i.Be(b,"function",a,1,!0)};o_("Assert.assertFunctionOrNull",c.i.FF,c);c.i.EF=function(b,a){c.i.Eb&&c.i.Be(b,"boolean",a,1,!1)};o_("Assert.assertBoolean",c.i.EF,c);c.i.$b=function(b,a){c.i.Eb&&c.i.Be(b,"number",a,1,!1)};o_("Assert.assertNumber",c.i.$b,c);c.i.PS=function(b,
a){c.i.Eb&&c.i.Be(b,"number",a,1,!0)};o_("Assert.assertNumberOrNull",c.i.PS,c);c.i.gw=function(b,a){c.i.Eb&&!Array.isArray(b)&&(void 0===a&&(a=b+" is not an array"),c.i.zc(a,1))};o_("Assert.assertArray",c.i.gw,c);c.i.un=function(b,a){c.i.Eb&&null!==b&&!Array.isArray(b)&&(void 0===a&&(a=b+" is not an array"),c.i.zc(a,1))};o_("Assert.assertArrayOrNull",c.i.un,c);c.i.OS=function(b,a){c.i.Eb&&!isNaN(b)&&(void 0===a&&(a=b+" is convertible to a number"),c.i.zc(a,1))};o_("Assert.assertNonNumeric",c.i.OS,
c);c.i.QS=function(b,a){c.i.Eb&&isNaN(b)&&(void 0===a&&(a=b+" is not convertible to a number"),c.i.zc(a,1))};o_("Assert.assertNumeric",c.i.QS,c);c.i.NS=function(b,a,d){var k;if(null===b||void 0===a[b.toString()]){if(void 0===d){d=" is not in set: {";for(k in a)a.hasOwnProperty(k)&&(d+=k,d+=",");d=b+(d+"}")}c.i.zc(d,1)}};o_("Assert.assertInSet",c.i.NS,c);c.i.zc=function(b,a,d){a||(a=0);var k="Assertion";d&&(k+=" ("+d+")");k+=" failed: ";void 0!==b&&(k+=b);b=c.i.mu(a+1);b=c.i.RB(b);k+="\nStackTrace:\n"+
b;b=Error(k);window.alert(k);throw b;};o_("Assert.assertionFailed",c.i.zc,c);c.i.getFunctionName=function(b){var a=b[c.i.vo],d,k;void 0===a&&(a=b.toString(),d=a.indexOf("("),k=a.lastIndexOf(" ",d),a=a.substring(k+1,d),a.length||(a=null),b[c.i.vo]=a);return a};o_("Assert.getFunctionName",c.i.getFunctionName,c);c.i.OT=function(){return c.i.RB(c.i.mu(1))};o_("Assert.getStackString",c.i.OT,c);c.i.mu=function(b){void 0===b&&(b=0);c.i.assert(0<=b);var a=[],d;try{for(d=c.i.mu.caller;d&&a.length<c.i.uJ;)b?
b-=1:a.push(d),d=d.caller}catch(k){}return a};c.i.zB=function(b){var a=b[c.i.Ty],d,k;void 0===a&&(a=b.toString(),d=a.indexOf("("),k=a.indexOf(")",d+1),a=a.substring(d,k+1),a=a.replace(/\s+/g,""),a.length||(a=null),b[c.i.Ty]=a);return a};c.i.RB=function(b){if(!b)return"";var a=b.length,d=[],k,l,f,m,q,t,p,r,s;for(k=0;k<a;k+=1){l=b[k];(f=c.i.getFunctionName(l))||(f="anonymous");(m=l[c.i.Hx])&&(f=m+"."+f);m=c.i.zB(l);q=l.arguments;t=q.length;l=null;if(t)for(l=[],p=0;p<t;p+=1)r=q[p],"function"===typeof r&&
((s=c.i.getFunctionName(r))||(s="anonymous"),r=c.i.zB(r),r="function "+s+r),l[p]=r;q=[];q[0]=f;q[1]=m;l&&(q[2]="\n",q[3]="[",q[4]=c.i.rR(l),q[5]="]");d[k]=q.join("")}return d.join("\n")};c.i.rR=function(b){var a=b.length,d="",c,l;for(c=0;c<a;c+=1)l=(l=b[c])?l.toString?l.toString():"Unknown":"(empty)",d+=l,c<a-1&&(d+=",");return d};c.i.Ty="_funcParams";c.ha={};o_("Config",c.ha,c);c.ha.De=function(){var b;if(c.Vl())return c.i.assert(void 0!==f,"ojtranslations module must be defined"),b=f._ojLocale_,
"root"==b?"en":b;b=c.ha.Dk;null==b&&((b=document.documentElement.lang)||(b=void 0===navigator?"en":(navigator.language||navigator.userLanguage||"en").toLowerCase()),c.ha.Dk=b=b.toLowerCase());return b};o_("Config.getLocale",c.ha.De,c);c.ha.SU=function(b,d){if(c.Vl()){var h=["ojL10n!ojtranslations/nls/"+b+"/ojtranslations"];c.Ca&&h.push("ojL10n!ojtranslations/nls/"+b+"/localeElements");a(h,function(b,a){f=b;a&&c.Ca.rK(a);d&&d()})}else c.ha.Dk=b,d&&d()};o_("Config.setLocale",c.ha.SU,c);c.ha.ab=function(b){var d=
/^\/|:/;return null==b||d.test(b)?b:(d=c.ha.nR)?d+("/"==d.charAt(d.length-1)?"":"/")+b:c.Vl()?(d=a.toUrl("ojs/_foo_"),d.replace(/[^\/]*$/,"../"+b)):b};o_("Config.getResourceUrl",c.ha.ab,c);c.ha.TU=function(b){c.ha.nR=b};o_("Config.setResourceBaseUrl",c.ha.TU,c);c.ha.RU=function(b){c.ha.QK=b};o_("Config.setAutomationMode",c.ha.RU,c);c.ha.gG=function(){return c.ha.QK};o_("Config.getAutomationMode",c.ha.gG,c);c.fb={};o_("StringUtils",c.fb,c);c.fb.qK=/^\s*|\s*$/g;c.fb.isEmpty=function(b){return null===
b?!0:0===c.fb.trim(b).length};o_("StringUtils.isEmpty",c.fb.isEmpty,c);c.fb.VG=function(b){return void 0===b||c.fb.isEmpty(b)?!0:!1};o_("StringUtils.isEmptyOrUndefined",c.fb.VG,c);c.fb.Fd=function(b){return null!==b&&("string"===typeof b||b instanceof String)};o_("StringUtils.isString",c.fb.Fd,c);c.fb.trim=function(b){return c.fb.Fd(b)?b.replace(c.fb.qK,""):b};o_("StringUtils.trim",c.fb.trim,c);c.Ec={};o_("CollectionUtils",c.Ec,c);c.Ec.dh=function(b,a,d,k,l){return c.Ec.mA(b,a,d,k,l,0)};o_("CollectionUtils.copyInto",
c.Ec.dh,c);c.Ec.isPlainObject=function(b){if("object"===typeof b)try{if(b.constructor&&b.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!0}catch(a){}return!1};o_("CollectionUtils.isPlainObject",c.Ec.isPlainObject,c);c.Ec.mA=function(b,a,d,k,l,f){var m,q;if(b&&a&&b!==a)for(m in a)if(a.hasOwnProperty(m)){q=d?d(m):m;var t=a[m],p=!1;if(k&&f<l){var r=b[q];c.Ec.isPlainObject(r)&&c.Ec.isPlainObject(t)&&(p=!0,c.Ec.mA(r,t,d,!0,l,f+1))}if(!p)try{b[q]=t}catch(s){}}return b};c.da={};o_("Translations",
c.da,c);c.da.tx=function(b){c.da.Ps=b};o_("Translations.setBundle",c.da.tx,c);c.da.Hc=function(b){return c.da.NB(b)};o_("Translations.getResource",c.da.Hc,c);c.da.pb=function(b,a){return null==b?null:c.da.$M(b,a)};o_("Translations.applyParameters",c.da.pb,c);c.da.C=function(b,a){var d=c.da.NB(b);if(null==d)return b;var k={};2<arguments.length?k=Array.prototype.slice.call(arguments,1):2==arguments.length&&(k=arguments[1],"object"===typeof k||k instanceof Array||(k=[k]));return c.da.pb(d,k)};o_("Translations.getTranslatedString",
c.da.C,c);c.da.ir=function(b){b=c.da.lB()[b];var a,d;if(null==b)return{};a={};for(d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a};o_("Translations.getComponentTranslations",c.da.ir,c);c.da.NB=function(b){b=b?b.split("."):[];var a=c.da.lB(),d=b.length,k=0,l=b[k];for(c.i.Pd(a);0<--d&&a;)a=a[l],k++,l=b[k];return a?a[l]||null:null};c.da.$M=function(b,a){var d=b.length,c=[],l=null,f=!1,m=!1,q=!1,t=!1,p,r;for(r=0;r<d;r++){var s=b.charAt(r),u=!1;if(f)u=!0,f=!1;else switch(s){case "$":f=!0;break;case "{":t||
(m||(p=!1,l=[]),m=!0);break;case "}":m&&0<l.length&&(m=a[l.join("")],c.push(void 0===m?"null":m));m=!1;break;case "[":m||(q?t=!0:q=!0);break;case "]":t?t=!1:q=!1;break;default:u=!0}u&&(m?","==s||" "==s?p=!0:p||l.push(s):t||c.push(s))}return c.join("")};c.da.lB=function(){var b=c.da.Ps;return b?b:c.Vl()?(c.i.assert(void 0!==f,"ojtranslations module must be defined"),f):{}};return c});
//# sourceMappingURL=oj-modular.map