/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){window.adf||(window.adf={});var b=window.adf;b.Q=b.Q||{};b.Q.R=b.Q.R||{};b.Q.R.V=b.Q.R.V||{};b.Q.R.V.W=function(a,b,e,f,h,k){this.Ih=a;this.iQ=b;this.gm=e;this.hp=f;h&&(h.AU&&(this.wQ=h.AU),h.tU&&(this.eQ=h.tU),h.qH&&(this.xQ=h.qH),h.jH&&(this.fQ=h.jH),h.pH&&(this.vQ=h.pH),h.iH&&(this.dQ=h.iH));k&&(k.yH&&(this.pE=k.yH),k.xT&&(this.Ft=k.xT),k.VS&&(this.Qi=k.VS),k.bh&&(this.dp=k.bh),k.vl&&(this.Cq=k.vl));this.Ls=!0;this.jk=0;a=navigator.userAgent.toLowerCase();
if(-1!==a.indexOf("gecko/"))this.RK=!0;else if(-1!==a.indexOf("opera"))this.SK=!0;else if(-1!==a.indexOf("applewebkit")||-1!==a.indexOf("safari"))this.TK=!0};b.Q.R.V.W.prototype.WU=function(a){var c=this,e=b.Q.R.V.W;if(a){this.FL();this.ZL(this.wQ,this.xQ,this.vQ);this.HL(this.eQ,this.fQ,this.dQ);var f=this.vq,h=this.Mq;h?(this.kp=h.offsetWidth,this.jp=f.offsetHeight):(h=this.Vq,this.kp=f.offsetWidth,this.jp=h.offsetHeight);this.aq();this.$p();this.Vm=function(a){c.JO(a)};e.Kg(this.Ih,"mousewheel",
this.Vm);e.Kg(this.Ih,"wheel",this.Vm);this.Uv=function(a){c.RO(a)};e.Kg(this.Fc,"touchstart",this.Uv);this.Tv=function(a){c.QO(a)};e.Kg(this.Fc,"touchmove",this.Tv);this.pn=function(){c.PO()};e.Kg(this.Fc,"touchend",this.pn);e.Kg(this.Fc,"touchcancel",this.pn);this.ev=0}else this.YD();this.ct();this.vz(a);this.Rh(!0);a&&this.dp&&(this.uk=function(){c.Rh(!1)},this.dp.call(this.Qi,this.Ih,this.uk),this.dp.call(this.Qi,this.Eh,this.uk))};b.Q.R.V.W.prototype.destroy=function(){var a=this.Ih,c=b.Q.R.V.W;
c.Nk(a,"mousewheel",this.Vm);c.Nk(a,"wheel",this.Vm);c.Nk(this.Fc,"touchstart",this.Uv);c.Nk(this.Fc,"touchmove",this.Tv);c.Nk(this.Fc,"touchend",this.pn);c.Nk(this.Fc,"touchcancel",this.pn);this.pn=this.Tv=this.Uv=this.Vm=null;this.Cq&&this.uk&&(this.Cq.call(this.Qi,a,this.uk),this.Cq.call(this.Qi,this.Eh,this.uk));this.uk=null;c.kR(this.it,a);this.Ez=null;this.Rv?a.removeChild(this.Rv):(a.removeChild(this.Fc),a.removeChild(this.Vq),a.removeChild(this.cw));this.Vq=this.cw=this.$u=this.lv=this.Mq=
this.Ov=this.Rv=this.it=this.Fc=this.Eh=this.kv=this.vq=null;this.ct();this.Qi=this.Cq=this.dp=this.Ft=this.pE=this.Ih=null};b.Q.R.V.W.lR=function(a,c,e){var f=b.Q.R.V.W,h=null;e&&(h=f.nt(),c.appendChild(h));var k=null;for(a=a.childNodes;0<a.length;){k||(k=[]);var l=a[0];if(1===l.nodeType){e||(h=f.nt(),c.appendChild(h));var n=f.wp();n.appendChild(l);h.appendChild(n);k.push(l)}else e?h.appendChild(l):c.appendChild(l)}return k};b.Q.R.V.W.kR=function(a,b){if(a)for(var e=a.childNodes;0<e.length;){var f=
e[0];if(1===f.nodeType){for(var h=f.childNodes;0<h.length;){var k=h[0];1===k.nodeType?(b.appendChild(k.firstChild),f.removeChild(k)):b.appendChild(k)}a.removeChild(f)}else b.appendChild(f)}};b.Q.R.V.W.qB=function(a){var b=a.ownerDocument.defaultView,e=null;return e=b?b.getComputedStyle(a,null):a.currentStyle};b.Q.R.V.W.sN=function(a){var c=b.Q.R.V.W;a=c.qB(a);return c.mB(a.width)};b.Q.R.V.W.rN=function(a){var c=b.Q.R.V.W;a=c.qB(a);return c.mB(a.height)};b.Q.R.V.W.mB=function(a){return 0<a.length&&
"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};b.Q.R.V.W.Kg=function(a,b,e){a.addEventListener?a.addEventListener(b,e,!1):a.attachEvent&&a.attachEvent("on"+b,e)};b.Q.R.V.W.Nk=function(a,b,e){a.removeEventListener?a.removeEventListener(b,e,!1):a.detachEvent&&a.detachEvent("on"+b,e)};b.Q.R.V.W.eO=function(a){var b=0;return b=null!=a.wheelDelta?a.wheelDelta:null!=a.deltaY?-a.deltaY:-a.detail};b.Q.R.V.W.tA=function(){var a=document.createElement("div");a.style.display="table";return a};b.Q.R.V.W.nt=
function(){var a=document.createElement("div");a.style.display="table-row";return a};b.Q.R.V.W.wp=function(){var a=document.createElement("div");a.style.display="table-cell";return a};b.Q.R.V.W.zF=function(a,b,e,f){var h=document.createElement("div"),k=h.style;k.display="inline-block";h.appendChild(a);b.appendChild(h);e&&(k.maxWidth=h.offsetWidth+"px");f&&(k.maxHeight=h.offsetHeight+"px");return h};b.Q.R.V.W.prototype.kd=function(){return"horizontal"===this.iQ};b.Q.R.V.W.prototype.sP=function(){return!this.rB().hasChildNodes()};
b.Q.R.V.W.prototype.YD=function(){this.ev=this.we();this.gA();this.Fv(0);this.aq();this.$p()};b.Q.R.V.W.prototype.ct=function(){this.Kq=this.Bf=null};b.Q.R.V.W.prototype.Rh=function(a){a||this.YD();this.ct();this.Bf&&this.Kq||(this.Bf=this.TC());a||this.vz();a=this.Bf;this.CK(a.Xc,a.kh)};b.Q.R.V.W.prototype.CK=function(a,b){var e=this.vq.style,f=this.kv.style;if(this.kd()){var h=.5*(b-this.jp);e.top=h+"px";f.top=h+"px"}else h=.5*(a-this.kp),this.hp?(e.left=-h+"px",f.left=-h+"px"):(e.left=h+"px",f.left=
h+"px")};b.Q.R.V.W.prototype.vz=function(a){var c=this.Eh,e=this.kd(),f=b.Q.R.V.W,f=e?f.sN(this.Ih):f.rN(this.Ih);(e?c.offsetWidth:c.offsetHeight)>f&&this.IE(f);this.Um=0;this.Rm=e?c.offsetWidth-f+this.kp:c.offsetHeight-f+this.jp;0>this.Rm&&(this.Rm=0);this.aq();this.$p();this.Rk(a?this.Um:this.ev,!0);this.ev=0};b.Q.R.V.W.prototype.FL=function(){var a=this,c=this.kd(),e=document.createElement("div");this.Fc=e;var f=e.style;f.overflow="hidden";f.display=this.vm();f.position="relative";c&&(f.verticalAlign=
"top");var h=this.Ih,k=b.Q.R.V.W,l=document.createElement("div");this.Eh=l;var n=l.style;n.position="relative";c&&(n.display="inline-block");e.appendChild(l);n=null;if(c){this.Rv=n=k.tA();var m=k.nt(),q=k.wp();this.Ov=q;var t=k.wp(),p=k.wp();this.Mq=p;var r=p.style;q.style.verticalAlign="top";r.verticalAlign="top";t.appendChild(e);m.appendChild(q);m.appendChild(t);m.appendChild(p);n.appendChild(m)}m=k.tA();q=k.lR(h,m,c);if(this.gm)for(q=[],t=this.gm.children,p=t.length,r=0;r<p;r++){var s=t[r];1===
s.nodeType&&q.push(s)}(this.Ez=q)&&0<q.length&&(this.it=m,l.appendChild(m));n?h.appendChild(n):(this.cw=n=document.createElement("div"),this.Vq=m=document.createElement("div"),h.appendChild(n),h.appendChild(e),h.appendChild(m));c&&(c=e.offsetHeight,l=l.offsetHeight,c>l&&(f.marginBottom=l-c+"px"));k.Kg(e,"scroll",function(b){a.yu(b)})};b.Q.R.V.W.prototype.vm=function(){return this.kd()?"inline-block":"block"};b.Q.R.V.W.prototype.ZL=function(a,c,e){var f=this,h=document.createElement("div");this.kv=
h;a&&h.setAttribute("id",a);h.setAttribute("class",c);h.setAttribute("aria-hidden","true");c=h.style;c.display=this.vm();c.position="relative";if(a=this.kd())c.verticalAlign="top";c=b.Q.R.V.W;c.Kg(h,"click",function(){f.rE()});this.Ov?this.lv=c.zF(h,this.Ov,a,!a):this.cw.appendChild(h);e&&h.appendChild(e)};b.Q.R.V.W.prototype.HL=function(a,c,e){var f=this,h=document.createElement("div");this.vq=h;a&&h.setAttribute("id",a);h.setAttribute("class",c);h.setAttribute("aria-hidden","true");c=h.style;c.display=
this.vm();c.position="relative";if(a=this.kd())c.verticalAlign="top";c=b.Q.R.V.W;c.Kg(h,"click",function(){f.qE()});this.Mq?this.$u=c.zF(h,this.Mq,a,!a):this.Vq.appendChild(h);e&&h.appendChild(e)};b.Q.R.V.W.prototype.rB=function(){var a=this.gm;a||(a=this.Eh);return a};b.Q.R.V.W.prototype.TC=function(){var a=this.it,b=this.Ez,e={Xc:0,kh:0},f=[];if(this.rB().hasChildNodes()&&a&&b&&0<b.length)for(var a=this.kd(),h=0,h=this.Eh.offsetWidth,k=0,l=null,n=0;n<b.length;n++){var m=b[n];if(1===m.nodeType){var q=
m.offsetWidth,t=m.offsetHeight,p={Xc:q,kh:t,id:m.id};if(a){var r=m.offsetLeft;this.gm||0!==r||(m=m.parentNode,r=m.offsetLeft);p.start=this.hp?h-(r+q):r;0===n&&(k=p.start);p.start-=k;e.Xc=p.start+q;e.kh=Math.max(e.kh,t);p.end=e.Xc-1}else r=m.offsetTop,this.gm||0!==r||(m=m.parentNode,r=m.offsetTop),p.start=r,e.Xc=Math.max(e.Xc,q),e.kh=p.start+t,p.end=e.kh-1;l&&l.end>=p.start&&(q=l.end-(p.start-1),l.end-=q,a?l.Xc-=q:l.kh-=q);f.push(p);l=p}}this.Kq=f;return e};b.Q.R.V.W.prototype.rk=function(){if(!this.Kq){var a=
this.TC();this.Bf||(this.Bf=a)}return this.Kq};b.Q.R.V.W.prototype.bu=function(){return this.$u?this.$u:this.vq};b.Q.R.V.W.prototype.gu=function(){return this.lv?this.lv:this.kv};b.Q.R.V.W.prototype.WR=function(){this.bu().style.display=this.vm()};b.Q.R.V.W.prototype.YR=function(){this.gu().style.display=this.vm()};b.Q.R.V.W.prototype.$p=function(){this.bu().style.display="none"};b.Q.R.V.W.prototype.aq=function(){this.gu().style.display="none"};b.Q.R.V.W.prototype.lq=function(){return"none"!==this.bu().style.display};
b.Q.R.V.W.prototype.Lu=function(){return"none"!==this.gu().style.display};b.Q.R.V.W.prototype.It=function(){return this.kd()?this.kp:this.jp};b.Q.R.V.W.prototype.rS=function(a){var b=this.It(),e=this.we(),f=this.mk(),h=this.uq();a<=this.Um?(this.Lu()&&(f+=b,e-=b),this.aq()):h&&(this.Lu()||(f-=b,e+=b),this.YR());a>=this.Rm?(this.lq()&&(f+=b),this.$p()):h&&(this.lq()||(f-=b),this.WR());this.Fv(e);h?this.IE(f):this.gA()};b.Q.R.V.W.prototype.IE=function(a){var b=this.Fc.style;a+="px";this.kd()?b.maxWidth=
a:b.maxHeight=a};b.Q.R.V.W.prototype.gA=function(){var a=this.Fc.style;this.kd()?a.maxWidth="":a.maxHeight=""};b.Q.R.V.W.prototype.Fv=function(a){var b=this.Fc;this.kd()?b.scrollLeft=this.jt(a):b.scrollTop=a};b.Q.R.V.W.prototype.mk=function(){var a=this.Fc;return this.kd()?a.offsetWidth:a.offsetHeight};b.Q.R.V.W.prototype.Rk=function(a,b){this.Dh||(this.Ls=!1,this.AE(a,b))};b.Q.R.V.W.prototype.AE=function(a,c){if(!this.sP()){this.Dh=!0;a=this.wL(a);this.rS(a);var e=this.pE;if(c||!e||a===this.we())this.gD(a);
else{var f=this;e.call(this.Qi,this.Fc,this.jt(a),Math.abs(this.we()-a)/b.Q.R.V.W.YJ,function(){f.gD(a)})}}};b.Q.R.V.W.prototype.we=function(){var a=this.Fc;return this.kd()?this.AL(a.scrollLeft):a.scrollTop};b.Q.R.V.W.prototype.uq=function(){var a=this.Eh,b=this.Fc;return this.kd()?a.offsetWidth>b.offsetWidth:a.offsetHeight>b.offsetHeight};b.Q.R.V.W.prototype.wL=function(a){!this.uq()||a<this.Um?a=this.Um:a>this.Rm&&(a=this.Rm);return a};b.Q.R.V.W.prototype.JO=function(a){var c=this.Dh;if(this.uq()&&
!this.Dh){var e=b.Q.R.V.W.eO(a);0>e&&this.lq()?(c=!0,this.qE()):0<e&&this.Lu()&&(c=!0,this.rE())}c&&(a.preventDefault(),a.stopPropagation())};b.Q.R.V.W.prototype.RO=function(a){a=a.touches;this.uq()&&!this.Dh&&1===a.length&&(this.ip=!0,a=a[0],this.kS=this.kd()?a.pageX:a.pageY,this.kF=this.we(),this.lS=this.Wz(),this.mS=this.Xz())};b.Q.R.V.W.prototype.QO=function(a){if(this.ip){var c=this.kd();a=a.touches[0];a=(c?a.pageX:a.pageY)-this.kS;var e=this.Fc;Math.abs(a)<b.Q.R.V.W.ZJ*(c?e.offsetWidth:e.offsetHeight)?
this.Rk(this.kF-a,!0):(this.Rk((c&&this.hp?0<a:0>a)?this.lS:this.mS),this.ip=!1)}};b.Q.R.V.W.prototype.PO=function(){this.ip&&this.Rk(this.kF);this.ip=!1};b.Q.R.V.W.prototype.yu=function(){this.Ls&&!this.Dh&&this.AE(this.we(),!0)};b.Q.R.V.W.prototype.gD=function(a){this.Fv(a);this.ER();this.Dh=!1;if(this.Ft){this.jk=this.Uz();a=this.Vz();var b=this.rk(),e=b[this.jk];this.jk!==a&&this.we()>e.start&&this.jk<b.length-2&&(this.jk++,e=b[this.jk]);this.XM=e.id;this.Ft.call(this.Qi,this.XM)}};b.Q.R.V.W.prototype.ER=
function(){var a=this;window.setTimeout(function(){a&&(a.Ls=!0)},0)};b.Q.R.V.W.prototype.qE=function(){this.Dh||this.Rk(this.Wz())};b.Q.R.V.W.prototype.rE=function(){this.Dh||this.Rk(this.Xz())};b.Q.R.V.W.prototype.Wz=function(){var a=this.eL(),b=0;return b=a===this.Uz()?this.we()+this.mk():this.gL(a)};b.Q.R.V.W.prototype.Xz=function(){var a=this.fL(),b=0,b=a===this.Vz()?this.we()-this.mk():this.dL(a);this.lq()||(b+=this.It());b<this.It()&&(b=this.Um);return b};b.Q.R.V.W.prototype.gL=function(a){return this.rk()[a].start};
b.Q.R.V.W.prototype.dL=function(a){return this.rk()[a].end-this.mk()+1};b.Q.R.V.W.prototype.Uz=function(){var a=this.mp(this.we());return 0>a?0:a};b.Q.R.V.W.prototype.Vz=function(){var a=this.mp(this.we()+this.mk()-1),b=this.rk();return 0>a?b.length-1:a};b.Q.R.V.W.prototype.fL=function(){var a=this.mp(this.we()-1);return 0>a?0:a};b.Q.R.V.W.prototype.eL=function(){var a=this.mp(this.we()+this.mk()),b=this.rk();return 0>a?b.length-1:a};b.Q.R.V.W.prototype.mp=function(a){for(var b=this.rk(),e=0;e<b.length;e++)if(a<=
b[e].end)return e;return-1};b.Q.R.V.W.prototype.jt=function(a){var b=a;if(this.hp&&this.kd())if(this.RK)b=-a;else if(this.TK||this.SK)b=this.Eh.offsetWidth-this.Fc.offsetWidth-a;return b};b.Q.R.V.W.prototype.AL=function(a){return this.jt(a)};b.Q.R.V.W.YJ=1.1;b.Q.R.V.W.ZJ=.33;(function(){a.Fa("oj.ojConveyorBelt",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{orientation:"horizontal",contentParent:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-conveyorbelt oj-component")},
_init:function(){this.Cb(!0)},refresh:function(){this._super();var a="rtl"===this.uc()!==this.Gz;a&&this.tt();this.Cb(a)},Cb:function(b){this.Gz="rtl"===this.uc();var c=this.element,e=this.options;if(b&&!this.np){var g=e.orientation,h=null,k=null,l=null,n=null,m=null;"vertical"!==g?(h="oj-enabled oj-conveyorbelt-overflow-indicator oj-start oj-default",k="oj-enabled oj-conveyorbelt-overflow-indicator oj-end oj-default",l=this.tp("oj-conveyorbelt-overflow-icon oj-start"),n=this.tp("oj-conveyorbelt-overflow-icon oj-end"),
m=this.HK):(h="oj-enabled oj-conveyorbelt-overflow-indicator oj-top oj-default",k="oj-enabled oj-conveyorbelt-overflow-indicator oj-bottom oj-default",l=this.tp("oj-conveyorbelt-overflow-icon oj-top"),n=this.tp("oj-conveyorbelt-overflow-icon oj-bottom"),m=this.IK);var q={};q.qH=h;q.jH=k;q.pH=l;q.iH=n;h={};h.bh=a.Aa.bh;h.vl=a.Aa.vl;"enabled"!==a.ha.gG()&&(h.yH=m);m=null;e.contentParent&&(m=f(e.contentParent)[0]);this.np=new window.adf.Q.R.V.W(c[0],g,m,this.Gz,q,h)}this.np.WU(b);if(b)for(b=c.find(".oj-conveyorbelt-overflow-indicator"),
c=b.size(),e=0;e<c;e++)g=b.get(e),this.UR(g)},_destroy:function(){this.tt();this.element.removeClass("oj-conveyorbelt oj-component");this._super()},_setOption:function(a,b,e){var f=!1;switch(a){case "containerParent":case "orientation":f=!0}f&&this.tt();this._super(a,b,e);f&&this.Cb(!0)},tt:function(){var a=this.np;a&&a.destroy();this.np=null},UR:function(a){this._on(a,{mousedown:function(a){f(a.currentTarget).addClass("oj-active")},mouseup:function(a){f(a.currentTarget).removeClass("oj-active")},
mouseenter:function(a){a=a.currentTarget;f(a).addClass("oj-hover");f(a).removeClass("oj-default")},mouseleave:function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active");f(a).addClass("oj-default")}})},tp:function(a){var b=document.createElement("span");b.setAttribute("class","oj-component-icon oj-clickable-icon "+a);return b},HK:function(a,b,e,g){var h={};h.scrollLeft=b;f(a).animate(h,e,"swing",g)},IK:function(a,b,e,g){var h={};h.scrollTop=b;f(a).animate(h,e,"swing",
g)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-conveyorbelt-start-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-start")[0]:"oj-conveyorbelt-end-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-end")[0]:"oj-conveyorbelt-top-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-top")[0]:"oj-conveyorbelt-bottom-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-bottom")[0]:
null}})})()});
//# sourceMappingURL=oj-modular.map