/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define("ojs/ojcore jquery ojs/ojeditablevalue ojs/ojinputtext ojs/ojvalidation ojs/ojpopup ojs/ojbutton".split(" "),function(a,f){function b(b){return b.delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a","mouseout",function(){f(this).removeClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a",
"mouseover",function(){f(this).addClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a","focus",function(){f(this).addClass("oj-focus")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a",
"blur",function(){f(this).removeClass("oj-focus")})}function d(b,a){var c=b.filter("span");a?c.addClass("oj-disabled").removeClass("oj-enabled oj-default"):c.removeClass("oj-disabled").addClass("oj-enabled oj-default")}var c=a.ba.ji(a.Pf.CONVERTER_TYPE_DATETIME).createConverter({year:"numeric"});a.Fa("oj.ojInputDate",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-only oj-component oj-inputdatetime",_INPUT_HELPER_KEY:"inputHelp",
_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],Bs:"oj-inputdatetime-input-trigger",oK:"oj-inputdatetime-calendar-icon",hy:"oj-datepicker-current-day",es:"oj-datepicker-days-cell-over",ez:"oj-datepicker-unselectable",jy:"oj-datepicker-desc",cs:"oj-datepicker-calendar",tJ:"oj-datepicker-div",ZI:"oj-datepicker-inline",aJ:" oj-inputdatetime-input-container",options:{buttonPanel:"none",calculateWeek:function(b){var a=new Date(b.getTime());a.setDate(a.getDate()+4-(a.getDay()||7));b=a.getTime();a.setMonth(0);
a.setDate(1);return Math.floor(Math.round((b-a)/864E5)/7)+1},changeMonth:"select",changeYear:"select",converter:a.ba.ji(a.Pf.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit"}),currentMonthPos:0,dayMetaData:null,daysOutsideMonth:"hidden",max:void 0,min:void 0,numberOfMonths:1,showOn:"image",stepMonths:"block",stepBigMonths:12,weekDisplay:"none",yearRange:"c-10:c+10"},_InitOptions:function(b,c){function d(b){var a=null;try{a=Date.parse(b),isNaN(a)||(a=new Date(a))}catch(c){}return a}
var f=[{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"title",defaultOptionValue:""},{attribute:"placeholder",defaultOptionValue:""},{attribute:"value",defaultOptionValue:null,coerceDomValue:d},{attribute:"required",defaultOptionValue:"optional",coerceDomValue:!0,validateOption:!0},{attribute:"min",defaultOptionValue:null,coerceDomValue:d},{attribute:"max",defaultOptionValue:null,coerceDomValue:d}];this._super(b,c);a.ud.vi(f,c,this)},Mo:function(){this.ve=!1;this.Rc=this.Cf=
null;this.Eu=!1;this.Qm=4;this.Hh=this.Ye=this.Rg=this.We=this.uf=0;this.jm={};var a=this.element[0].nodeName.toLowerCase();this.Rc="div"===a||"span"===a;this.Yb=b(f("\x3cdiv id\x3d'"+this.Ah(this.tJ)+"' role\x3d'region' aria-describedby\x3d'"+this.Ah(this.jy)+"' class\x3d'oj-datepicker-content'\x3e\x3c/div\x3e"));f("body").append(this.Yb);if(this.Rc)this._CLASS_NAMES="";else{this._WIDGET_CLASS_NAMES+=this.aJ;var c=this;this.rD=this.Yb.ojPopup({initialFocus:"none",rootAttributes:{"class":"datetimepicker-dropdown"},
open:function(){c.Yb.find(".oj-datepicker-calendar").focus()}})}},_ComponentCreate:function(){this.Mo();var b=this._super();this.Eq(this.nk());this.Rc?(this.element.append(this.Yb),this.element.addClass(this.ZI),this.ve=!0,this.ee(this.nk(),{},{Or:this.Ig.Ll}),this.Yb.css("display","block")):this.Ks();return b},_setOption:function(b,c,d){var f=null,l={},l={};if("value"===b)return c||(c=null),f=this._super(b,c,d),this.Eq(c),f;f=this._superApply(arguments);"currentMonthPos"===b&&this.Eq(this.options.value);
"disabled"===b?this.rM(c):"max"===b||"min"===b?(l={min:this.options.min,max:this.options.max,converter:this.wd()},this.jm[a.kc.VALIDATOR_TYPE_DATETIMERANGE]=a.ba.wh(a.kc.VALIDATOR_TYPE_DATETIMERANGE).createValidator(l),this.Tl()):"dayMetaData"===b&&(l={dayMetaData:this.options.dayMetaData,converter:this.wd()},this.jm[a.kc.VALIDATOR_TYPE_DATERESTRICTION]=a.ba.wh(a.kc.VALIDATOR_TYPE_DATERESTRICTION).createValidator(l),this.Tl());return f},_destroy:function(){var b=this._super();this.element.off("focus");
this.Cf&&this.Cf.remove();this.Rc&&(this.element.removeProp("disabled"),this.element.removeProp("readonly"));this.Yb.remove();return b},Ks:function(){var b=this.options.showOn,a=f(f("\x3cspan\x3e").addClass(this.Bs));if("focus"===b)this.element.on("focus",f.proxy(this.show,this));b=f(f("\x3cspan/\x3e").addClass(this.oK+" oj-clickable-icon oj-component-icon"));a.append(b);var c=this;b.on("click",function(){c.ve?c.hide():c.show();return!1}).on("mouseenter",function(){f(this).addClass("oj-hover")}).on("mousedown",
function(){f(this).addClass("oj-active")}).on("mouseleave",function(){f(this).removeClass("oj-hover oj-active")});this.Cf=a;this.element.after(a)},yM:function(b){var a;a=!1;var c=f.ui.keyCode,d=this.No();if(this.ve)switch(b.keyCode){case 84:b.altKey&&b.ctrlKey&&(this.Yb.find(".oj-datepicker-current").focus(),a=!0);break;case 68:b.altKey&&b.ctrlKey&&(this.Yb.find(".oj-datepicker-close").focus(),a=!0);break;case c.TAB:this.hide();break;case c.ENTER:return a=f("td."+this.es+":not(."+this.hy+")",this.Yb),
a[0]&&this.sE(this.We,this.Ye,a[0],b),b.preventDefault(),b.stopPropagation(),!1;case c.ESCAPE:this.hide();this.element.focus();a=!0;break;case c.PAGE_UP:b.ctrlKey&&b.altKey?this.xd(-this.options.stepBigMonths,"M",!0):b.altKey?this.xd(-1,"Y",!0):this.xd(-this.Em(),"M",!0);a=!0;break;case c.PAGE_DOWN:b.ctrlKey&&b.altKey?this.xd(+this.options.stepBigMonths,"M",!0):b.altKey?this.xd(1,"Y",!0):this.xd(+this.Em(),"M",!0);a=!0;break;case c.END:this.uf=this.Np(this.Ye,this.We);this.rj(!0);a=!0;break;case c.HOME:this.uf=
1;this.rj(!0);a=!0;break;case c.LEFT:this.xd(d?1:-1,"D",!0);b.originalEvent.altKey&&this.xd(b.ctrlKey?-this.options.stepBigMonths:-this.Em(),"M",!0);a=!0;break;case c.UP:this.xd(-7,"D",!0);a=!0;break;case c.RIGHT:this.xd(d?-1:1,"D",!0);b.originalEvent.altKey&&this.xd(b.ctrlKey?+this.options.stepBigMonths:+this.Em(),"M",!0);a=!0;break;case c.DOWN:this.xd(7,"D",!0),a=!0}else b.keyCode===c.HOME&&b.ctrlKey&&(this.show(),a=!0);a&&(b.preventDefault(),b.stopPropagation())},rj:function(b){this.Qm=4;var a=
this.bN();this.Yb.empty().append(a.html);var c=f("button",this.Yb);0<c.length&&f.each(c,function(b,a){f(a).ojButton()});this.OK();this.Yb.find("."+this.es+" a").mouseover();a.XF&&this.Yb.find(".oj-datepicker-calendar").attr("aria-activedescendant",a.XF);a=this.cu();c=a[1];this.Yb.removeClass("oj-datepicker-multi-2 oj-datepicker-multi-3 oj-datepicker-multi-4").width("");1<c&&this.Yb.addClass("oj-datepicker-multi-"+c).css("width",17*c+"em");this.Yb[(1!==a[0]||1!==a[1]?"add":"remove")+"Class"]("oj-datepicker-multi");
this.ve&&this.element.is(":visible")&&!this.element.is(":disabled")&&(b||this.Rc?(b=this.Yb.find(".oj-datepicker-calendar"),b[0]!==document.activeElement&&b.focus()):this.element[0]!==document.activeElement&&this.element.focus())},xd:function(b,a,c){this.options.disabled||(this.uz(b+("M"===a?this.options.currentMonthPos:0),a),this.rj(c))},gO:function(){var b=new Date;this.uf=b.getDate();this.Rg=this.We=b.getMonth();this.Hh=this.Ye=b.getFullYear();this.xd()},tE:function(b,a){var d=parseInt(b.options[b.selectedIndex].value,
10);"M"===a?this.We=this.Rg=d:this.Ye=this.Hh=d;f("#"+this.Ah(this.cs)).html(this.options.monthWide[this.Rg]+" "+c.format(new Date(this.Hh,this.Rg,1)));this.xd()},sE:function(b,a,c,d){f(c).hasClass(this.ez)||this.options.disabled||(this.uf=f("a",c).html(),this.We=b,this.Ye=a,(b=this.options.value)?(a=new Date(this.Ye,this.We,this.uf),this.nA(b,a),b=a):b=new Date(this.Ye,this.We,this.uf),this.Hg(this.wd().format(b)),this.ee(b,d,{Or:this.Ig.Ll}),this.hide())},ut:function(b,a){var c;null==b||""===b?
c=a:"number"===typeof b?isNaN(b)?c=a:(c=this.qu(),c.setDate(c.getDate()+b)):c=new Date(b.getTime());return c=c||a},Eq:function(b){b=this.ut(b,this.qu());this.uf=b.getDate();this.Rg=this.We=b.getMonth();this.Hh=this.Ye=b.getFullYear();this.uz()},EV:function(){return this.Ye&&""!==this.element.val()?new Date(this.Ye,this.We,this.uf):null},Em:function(){var b=this.options.stepMonths;return f.isNumeric(b)?b:this.options.numberOfMonths},OK:function(){var b=this.Em(),a=this;this.Yb.find("[data-handler]").map(function(){f(this).bind(this.getAttribute("data-event"),
{prev:function(){a.xd(-b,"M",!0)},next:function(){a.xd(+b,"M",!0)},hide:function(b){if("keyup"===b.type&&13===b.keyCode||"click"===b.type)a.hide(),b.preventDefault(),b.stopPropagation()},today:function(b){if("keyup"===b.type&&13===b.keyCode||"click"===b.type)a.gO(),b.preventDefault(),b.stopPropagation()},selectDay:function(b){a.sE(+this.getAttribute("data-month"),+this.getAttribute("data-year"),this,b);return!1},selectMonth:function(){a.tE(this,"M");return!1},selectYear:function(){a.tE(this,"Y");
return!1},calendarKey:function(b){a.yM(b)}}[this.getAttribute("data-handler")])})},bN:function(){var b,a,c,d,f,n=this.options.dayWide,m=this.options.dayNarrow,q=this.options.monthWide,t=this.options.monthAbbreviated,p=this.options.firstDayOfWeek,r,s,u,v,w,x,E,A,Q="",B,z,F,M,y,J,I,D,G=new Date,G=new Date(G.getFullYear(),G.getMonth(),G.getDate()),N=this.No();f=this.options.buttonPanel;var K=this.cu(),C=this.options.currentMonthPos,X=this.options.dayMetaData;D=null;var O=1!==K[0]||1!==K[1],S=this.pk("min"),
T=this.pk("max"),C=this.Rg-C,P=this.Hh,ca=new Date(this.Ye,this.We,this.uf),R=this.nk(),Y=R.getDate(),L=R.getMonth(),aa=R.getFullYear(),V=this.options.disabled,da=this.C("weekText");R.setHours(0);R.setMinutes(0);R.setSeconds(0);R.setMilliseconds(0);0>C&&(C+=12,P--);if(T)for(b=new Date(T.getFullYear(),T.getMonth()-K[0]*K[1]+1,T.getDate()),b=S&&b<S?S:b;new Date(P,C,1)>b;)C--,0>C&&(C=11,P--);this.Rg=C;this.Hh=P;b=this.C("prevText");b=this.Yz(-1,P,C)&&!V?"\x3ca href\x3d'#' class\x3d'oj-datepicker-prev-icon oj-enabled oj-default oj-component-icon oj-clickable-icon' data-handler\x3d'prev' data-event\x3d'click' title\x3d'"+
b+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-prev-icon oj-disabled oj-component-icon oj-clickable-icon' title\x3d'"+b+"'\x3e\x3c/a\x3e";a=this.C("nextText");a=this.Yz(1,P,C)&&!V?"\x3ca href\x3d'#' class\x3d'oj-datepicker-next-icon oj-enabled oj-default oj-component-icon oj-clickable-icon' data-handler\x3d'next' data-event\x3d'click' title\x3d'"+a+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-next-icon oj-disabled oj-component-icon oj-clickable-icon' title\x3d'"+a+"'\x3e\x3c/a\x3e";c=this.C("currentText");
d=this.Rc?"":"\x3cbutton type\x3d'button' class\x3d'oj-datepicker-close oj-priority-primary' data-handler\x3d'hide' data-event\x3d'click keyup'\x3e"+this.C("closeText")+"\x3c/button\x3e";f="default"===f?"\x3cdiv class\x3d'oj-datepicker-buttonpane'\x3e"+(N?d:"")+(this.AC(G)?"\x3cbutton type\x3d'button' class\x3d'oj-datepicker-current oj-priority-secondary' data-handler\x3d'today' data-event\x3d'click keyup'\x3e"+c+"\x3c/button\x3e":"")+(N?"":d)+"\x3c/div\x3e":"";c=this.options.weekDisplay;d=this.options.daysOutsideMonth;
r="";s="all";for(u=0;u<K[0];u++){v="";this.Qm=4;for(w=0;w<K[1];w++){s="all";B="";if(O){B+="\x3cdiv class\x3d'oj-datepicker-group";if(1<K[1])switch(w){case 0:B+=" oj-datepicker-group-first";s=N?"right":"left";break;case K[1]-1:B+=" oj-datepicker-group-last";s=N?"left":"right";break;default:B+=" oj-datepicker-group-middle",s=""}B+="'\x3e"}B+="\x3cdiv class\x3d'oj-datepicker-header"+(V?" oj-disabled ":" oj-enabled oj-default ")+"'\x3e"+(/all|left/.test(s)&&0===u?N?a:b:"")+(/all|right/.test(s)&&0===u?
N?b:a:"")+this.cN(C,P,S,T,0<u||0<w,q,t)+"\x3c/div\x3e\x3ctable class\x3d'oj-datepicker-calendar"+(V?" oj-disabled ":" oj-enabled oj-default ")+"' tabindex\x3d-1 data-handler\x3d'calendarKey' data-event\x3d'keydown' aria-readonly\x3d'true' role\x3d'grid' aria-labelledby\x3d'"+this.Ah(this.cs)+"'\x3e\x3cthead role\x3d'presentation'\x3e\x3ctr role\x3d'row'\x3e";z="number"===c?"\x3cth class\x3d'oj-datepicker-week-col'\x3e"+this.C("weekHeader")+"\x3c/th\x3e":"";for(s=0;7>s;s++)F=(s+parseInt(p,10))%7,z+=
"\x3cth role\x3d'columnheader' aria-label\x3d'"+n[F]+"'"+(5<=(s+p+6)%7?" class\x3d'oj-datepicker-week-end'":"")+"\x3e\x3cspan title\x3d'"+n[F]+"'\x3e"+m[F]+"\x3c/span\x3e\x3c/th\x3e";B+=z+"\x3c/tr\x3e\x3c/thead\x3e\x3ctbody role\x3d'presentation'\x3e";z=this.Np(P,C);P===aa&&C===L&&(Y=Math.min(Y,z));s=(this.tN(P,C)-p+7)%7;z=Math.ceil((s+z)/7);this.Qm=z=O?this.Qm>z?this.Qm:z:z;F=new Date(P,C,1-s);for(M=0;M<z;M++){B+="\x3ctr role\x3d'row'\x3e";s=this.options.calculateWeek(F);y="none"===c?"":"\x3ctd class\x3d'oj-datepicker-week-col' role\x3d'rowheader' aria-label\x3d'"+
da+" "+s+"'\x3e"+s+"\x3c/td\x3e";for(s=0;7>s;s++){I=F.getMonth()!==C;x=F.getTime()===R.getTime();E="oj-dp-"+M+"-"+s;(A=F.getTime()===ca.getTime()&&C===this.We)&&(Q=E);J=[!0,""];D=F.getFullYear();var W=F.getMonth(),ba=F.getDate(),ea=function H(b,a,c){if(!b||a===c.length)return b;var d=a+1;return H(b[c[a]],d,c)||H(b["*"],d,c)};X&&(D=ea(X,0,[D,W+1,ba]))&&(J=[!D.disabled,D.className||""],D.tooltip&&J.push(D.tooltip));W=F.getTime()===R.getTime();D=I&&"selectable"!==d||!J[0]||S&&F<S||T&&F>T;y+="\x3ctd role\x3d'gridcell' aria-disabled\x3d'"+
!!D+"' aria-selected\x3d'"+x+"' id\x3d'"+E+"' class\x3d'"+(5<=(s+p+6)%7?" oj-datepicker-week-end":"")+(I?" oj-datepicker-other-month":"")+(A?" "+this.es:"")+(D||V?" "+this.ez+" oj-disabled":" oj-enabled ")+(I&&"hidden"===d?"":" "+J[1]+(x?" "+this.hy:"")+(F.getTime()===G.getTime()?" oj-datepicker-today":""))+"'"+(I&&"hidden"===d||!J[2]?"":" title\x3d'"+J[2].replace(/'/g,"\x26#39;")+"'")+(D?"":" data-handler\x3d'selectDay' data-event\x3d'click' data-month\x3d'"+F.getMonth()+"' data-year\x3d'"+F.getFullYear()+
"'")+"\x3e"+(I&&"hidden"===d?"\x26#xa0;":D||V?"\x3cspan class\x3d'oj-disabled'\x3e"+F.getDate()+"\x3c/span\x3e":"\x3ca class\x3d'oj-enabled"+(W?" oj-selected":"")+(I?" oj-priority-secondary":"")+"' "+(W||A?"":"tabindex\x3d'-1' ")+" href\x3d'#'\x3e"+F.getDate()+"\x3c/a\x3e")+"\x3c/td\x3e";F.setDate(F.getDate()+1)}B+=y+"\x3c/tr\x3e"}C++;11<C&&(C=0,P++);B+="\x3c/tbody\x3e\x3c/table\x3e"+(O?"\x3c/div\x3e"+(0<K[0]&&w===K[1]-1?"\x3cdiv class\x3d'oj-datepicker-row-break'\x3e\x3c/div\x3e":""):"");v+=B}r+=
v}return{html:r+f,XF:Q}},cN:function(b,d,f,k,l,n,m){var q,t,p,r,s=this.options.changeMonth,u=this.options.changeYear,v=a.Ca.YG()?"before":"after",w="\x3cdiv class\x3d'oj-datepicker-title' role\x3d'header'\x3e",x="",E=this.options.disabled;if(l||"none"===s)x+="\x3cspan class\x3d'oj-datepicker-month'\x3e"+n[b]+"\x3c/span\x3e";else{q=f&&f.getFullYear()===d;t=k&&k.getFullYear()===d;x+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-month "+(E?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectMonth' data-event\x3d'change' role\x3d'listbox'\x3e";
for(p=0;12>p;p++)(!q||p>=f.getMonth())&&(!t||p<=k.getMonth())&&(x+="\x3coption role\x3d'option' value\x3d'"+p+"' aria-selected\x3d'"+(p===b?"true' selected\x3d'selected'":"false'")+"\x3e"+m[p]+"\x3c/option\x3e");x+="\x3c/select\x3e"}"before"===v&&(w+=x+(l||"select"!==s||"select"!==u?"\x26#xa0;":""));if(!this.xh)if(this.xh="",l||"none"===u)w+="\x3cspan class\x3d'oj-datepicker-year'\x3e"+c.format(new Date(d,b,1))+"\x3c/span\x3e";else{q=this.options.yearRange.split(":");r=(new Date).getFullYear();t=
function(b){b=b.match(/c[+\-].*/)?d+parseInt(b.substring(1),10):b.match(/[+\-].*/)?r+parseInt(b,10):parseInt(b,10);return isNaN(b)?r:b};m=t(q[0]);q=Math.max(m,t(q[1]||""));m=f?Math.max(m,f.getFullYear()):m;q=k?Math.min(q,k.getFullYear()):q;for(this.xh+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-year "+(E?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectYear' data-event\x3d'change' role\x3d'listbox'\x3e";m<=q;m++)this.xh+="\x3coption role\x3d'option' value\x3d'"+m+"' aria-selected\x3d'"+
(m===d?"true' selected\x3d'selected'":"false'")+"\x3e"+c.format(new Date(m,b,1))+"\x3c/option\x3e";this.xh+="\x3c/select\x3e";w+=this.xh;this.xh=null}"after"===v&&(w+=(l||"select"!==s||"select"!==u?"\x26#xa0;":"")+x);w+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+this.Ah(this.cs)+"'\x3e"+n[b]+" "+c.format(new Date(d,b,1))+"\x3c/span\x3e";w+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+this.Ah(this.jy)+"'\x3e"+this.C("datePicker")+"\x3c/span\x3e";return w+"\x3c/div\x3e"},
uz:function(b,a){var c=this.Hh+("Y"===a?b:0),d=this.Rg+("M"===a?b:0),f=Math.min(this.uf,this.Np(c,d))+("D"===a?b:0),c=new Date(c,d,f);this.uf=c.getDate();this.Rg=this.We=c.getMonth();this.Hh=this.Ye=c.getFullYear()},cu:function(){var b=this.options.numberOfMonths,b="string"===typeof b?parseInt(b,10):b;return null==b?[1,1]:"number"===typeof b?[1,b]:b},pk:function(b){return this.ut(this.options[b],null)},Np:function(b,a){return 32-(new Date(b,a,32)).getDate()},tN:function(b,a){return(new Date(b,a,1)).getDay()},
Yz:function(b,a,c){var d=this.cu();a=new Date(a,c+(0>b?b:d[0]*d[1]),1);0>b&&a.setDate(this.Np(a.getFullYear(),a.getMonth()));return this.AC(a)},AC:function(b){var a,c,d=this.pk("min"),f=this.pk("max"),n=null,m=null;if(a=this.options.yearRange)a=a.split(":"),c=(new Date).getFullYear(),n=parseInt(a[0],10),m=parseInt(a[1],10),a[0].match(/[+\-].*/)&&(n+=c),a[1].match(/[+\-].*/)&&(m+=c);return(!d||b.getTime()>=d.getTime())&&(!f||b.getTime()<=f.getTime())&&(!n||b.getFullYear()>=n)&&(!m||b.getFullYear()<=
m)},CV:function(b){function a(b){return{$W:1,BW:2,ZW:3}[b]||b}return[parseFloat(a(b.css("border-left-width"))),parseFloat(a(b.css("border-top-width")))]},rM:function(b){!this.Rc&&this.Cf&&d(this.Cf.children(),b);this.ve&&this.rj()},$r:function(){this.Rc||this._superApply(arguments)},cv:function(b){this.Rc||(this._superApply(arguments),this.ve&&this.Yb.find(".oj-datepicker-calendar").focus())},wq:function(b){if(!this.Rc){this._superApply(arguments);var a=f.ui.keyCode,c=!1;if(this.ve)switch(b.keyCode){case a.TAB:this.hide();
break;case a.ESCAPE:this.hide();c=!0;break;case a.UP:case a.DOWN:this.Yb.find(".oj-datepicker-calendar").focus(),c=!0}else switch(b.keyCode){case a.UP:case a.DOWN:this.show(),c=!0}if(c)return b.preventDefault(),b.stopPropagation(),!1}},ee:function(b,a,c){var d=this._superApply(arguments);d&&(this.Eq(this.nk()),this.ve&&this.rj());return d},Hg:function(b){this.Rc||this._superApply(arguments)},Rj:function(){return this.options.value||""},_GetDefaultStyleClass:function(){return"oj-inputdate"},Jo:function(){var b=
this._superApply(arguments),c=this.pk("min"),d=this.pk("max"),k={},k={};if(null!=c||null!=d)k={min:this.options.min,max:this.options.max,converter:this.wd()},this.jm[a.kc.VALIDATOR_TYPE_DATETIMERANGE]=a.ba.wh(a.kc.VALIDATOR_TYPE_DATETIMERANGE).createValidator(k);null!=this.options.dayMetaData&&(k={dayMetaData:this.options.dayMetaData,converter:this.wd()},this.jm[a.kc.VALIDATOR_TYPE_DATERESTRICTION]=a.ba.wh(a.kc.VALIDATOR_TYPE_DATERESTRICTION).createValidator(k));return f.extend(this.jm,b)},nA:function(b,
a){a.setHours(b.getHours());a.setMinutes(b.getMinutes());a.setSeconds(b.getSeconds());a.setMilliseconds(b.getMilliseconds())},qu:function(){var b=new Date;b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);return b},nk:function(){return this.ut(this.options.value,this.qu())},dW:function(){return this.Rc},getNodeBySubId:function(b){var a=this._superApply(arguments);if(a)return a;var a=b.subId,c=this.Yb;if(a)switch(a){case "oj-datepicker-content":return c;case "oj-inputdatetime-calendar-icon":return f(".oj-inputdatetime-calendar-icon",
this.Cf);case "oj-datepicker-prev-icon":return f(".oj-datepicker-prev-icon",c);case "oj-datepicker-next-icon":return f(".oj-datepicker-next-icon",c);case "oj-datepicker-month":return f(".oj-datepicker-month",c);case "oj-datepicker-year":return f(".oj-datepicker-year",c);case "oj-datepicker-current":return f(".oj-datepicker-current",c);case "oj-datepicker-close":return f(".oj-datepicker-close",c)}return null},hide:function(){this.ve&&!this.Rc&&(this.rD.ojPopup("close"),this.ve=!1,"focus"===this.options.showOn&&
(this.Eu=!0),this.element.focus());return this},refresh:function(){this._superApply(arguments);this.rj();return this},show:function(){if(!this.ve&&!this.options.disabled)if(this.Eu)this.Eu=!1;else{var b=this.No();this.Yb.empty();this.rj();this.rD.ojPopup("open",this.element,{my:b?"right top":"left top",at:b?"right bottom":"left bottom",collision:"fit"});this.ve=!0;return this}},calendarDisplay:function(){return this.Yb}});a.Components.ux({ojInputDate:{firstDayOfWeek:a.Components.vj(function(){return a.Ca.qG()}),
dayWide:a.Components.vj(function(){return a.Ca.Dw("wide")}),dayNarrow:a.Components.vj(function(){return a.Ca.Dw("narrow")}),monthWide:a.Components.vj(function(){return a.Ca.kr("wide")}),monthAbbreviated:a.Components.vj(function(){return a.Ca.kr("abbreviated")})}});a.Fa("oj.ojInputTime",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",_WIDGET_CLASS_NAMES:"oj-inputdatetime-time-only oj-component oj-inputdatetime oj-inputdatetime-input-container",_INPUT_HELPER_KEY:"inputHelp",
_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],dK:"ojInputTime",Bs:"oj-inputdatetime-input-trigger",pK:"oj-inputdatetime-time-icon",options:{converter:a.ba.ji(a.Pf.CONVERTER_TYPE_DATETIME).createConverter({hour:"2-digit",hour12:!0,minute:"2-digit"}),datePicker:null,timeIncrement:"T00:30:00:00"},_InitOptions:function(b,c){this._super(b,c);a.ud.vi([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"title",defaultOptionValue:""},{attribute:"placeholder",defaultOptionValue:""},
{attribute:"value",defaultOptionValue:null,coerceDomValue:function(b){var a=null;try{a=Date.parse(b),isNaN(a)||(a=new Date(a))}catch(c){}return a}},{attribute:"required",defaultOptionValue:"optional",coerceDomValue:!0,validateOption:!0}],c,this)},Mo:function(){this.fi=!1;this.ek=this.options.datePicker;this.md=f("\x3cdiv id\x3d'"+this.Ah(this.dK)+"' class\x3d'oj-listbox-drop' style\x3d'display:none'\x3e\x3c/div\x3e");f("body").append(this.md);var b=this;this.sD=this.md.ojPopup({initialFocus:"none",
rootAttributes:{"class":"datetimepicker-dropdown"},open:function(){var a=f("[aria-selected]",b.md);1===a.length&&f(a);f("ul",b.md).focus()}})},_ComponentCreate:function(){this.Mo();var b=this._superApply(arguments);this.Ak()&&!this.Ju()&&(this._CLASS_NAMES="");this.Ks();return b},_setOption:function(b,a,c){var f=null;if("value"===b&&!a)return f=this._super(b,null,c);f=this._superApply(arguments);"disabled"===b?d(this.Cf.children(),a):"timeIncrement"===b&&this.Ip();return f},_destroy:function(){var b=
this._super();this.Cf&&this.Cf.remove();this.md.remove();return b},$r:function(){this.Bk()&&this._superApply(arguments)},cv:function(b){this.Bk()&&(this._superApply(arguments),this.fi&&f("ul",this.md).focus())},wq:function(b){if(this.Bk()){this._superApply(arguments);var a=f.ui.keyCode,c=!1;if(this.fi)switch(b.keyCode){case a.TAB:this.hide();break;case a.ESCAPE:this.hide();c=!0;break;case a.UP:case a.DOWN:f("ul",this.md).focus(),c=!0}else switch(b.keyCode){case a.UP:case a.DOWN:this.show(),c=!0}if(c||
b.keyCode===a.ENTER)return b.preventDefault(),b.stopPropagation(),!1}},Ks:function(){var b=this.Bk(),a=b?f(f("\x3cspan\x3e").addClass(this.Bs)):f("+ span",this.element),c=f(f("\x3cspan/\x3e").addClass(this.pK+" oj-clickable-icon oj-component-icon"));a.append(c);var d=this;c.on("click",function(){d.fi?d.hide():d.show()}).on("mouseenter",function(){f(this).addClass("oj-hover")}).on("mousedown",function(){f(this).addClass("oj-active")}).on("mouseleave",function(){f(this).removeClass("oj-hover oj-active")});
this.Cf=a;b&&this.element.after(a)},Ip:function(){var b=this.options.value?new Date(this.options.value):new Date,a=f("\x3cul class\x3d'oj-listbox-results' tabindex\x3d'-1' role\x3d'listbox'\x3e\x3c/ul\x3e"),c=this.uN(),d=[],l;b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);d=this.cO(b);c=c||d[0].value;this.md.empty();b=0;for(l=d.length;b<l;b++){var n=d[b].value,m=f("\x3cli class\x3d'oj-listbox-result' role\x3d'presentation'\x3e"),q=this.uuid+"_sel"+b,t=f("\x3cdiv class\x3d'oj-listbox-result-label' data-value\x3d'"+
n+"' role\x3d'option' id\x3d'"+q+"'\x3e"+d[b].label+"\x3c/li\x3e");c===n&&(t.attr("aria-selected","true"),m.addClass("oj-hover"),a.attr("aria-activedescendant",q));m.append(t);a.append(m)}this.md.append(a);f(".oj-listbox-result",a).on("mousemove",function(){f(".oj-hover",a).removeClass("oj-hover");var b=f(this);b.addClass("oj-hover");a.attr("aria-activedescendant",b.children()[0].id)});var p=this;a.on("click",function(b){p.hide();p.zD(b)}).on("keydown",function(b){p.gS(b)})},cO:function(b){var a=
[],c=this.wd();if(b){var d=this.options.timeIncrement;if(4===d.split(":").length){if(d=this.bO(d)){var f=new Date(b),n="";do n=c.format(f),a.push({label:n,value:n}),f.setHours(f.getHours()+d.XT),f.setMinutes(f.getMinutes()+d.rU),f.setSeconds(f.getSeconds()+d.PU),f.setMilliseconds(f.getMilliseconds()+d.qU);while(f.getDate()===b.getDate())}}else throw Error("timeIncrement value should be in the format of Thh:mm:ss:SS");}return a},bO:function(b){var a=null;b=b.split(":");4===b.length&&(a={XT:parseInt(b[0].substring(1),
10),rU:parseInt(b[1],10),PU:parseInt(b[2],10),qU:parseInt(b[3],10)});return a},gS:function(b){if(this.fi){var a=f.ui.keyCode,c=!1;switch(b.keyCode){case a.TAB:this.hide();break;case a.ESCAPE:this.hide();this.element.focus();c=!0;break;case a.UP:this.vD(b,"prev");c=!0;break;case a.DOWN:this.vD(b,"next");c=!0;break;case a.ENTER:this.zD(b),c=!0}if(c)return b.preventDefault(),b.stopPropagation(),!1}},vD:function(b,a){var c=f(".oj-hover",this.md),d=f("ul",this.md);if(1===c.length){var l=f(c)[a]();1===
l.length&&(c.removeClass("oj-hover"),l.addClass("oj-hover"),d.attr("aria-activedescendant",l.children()[0].id))}},GV:function(b){var a=this.Ak()?this.ek.widget.option("value"):this.options.value;b=b?this.wd().parse(b):new Date;a&&(b.setMonth(a.getMonth()),b.setDate(a.getDate()),b.setFullYear(a.getFullYear()));return b},zD:function(b){var a=this.md,c=f("[aria-selected]",a),d=f("ul",a),a=f(".oj-hover div",a);1===a.length&&(1===c.length&&(c.removeAttr("aria-selected"),c.parent().removeClass("oj-hover")),
a.attr("aria-selected","true"),a.parent().addClass("oj-hover"),this.Hg(a.attr("data-value")),this.ee(a.attr("data-value"),b),d.attr("aria-activedescendant",a[0].id),this.hide(),this.element.focus(),this.Ak()&&this.ek.widget.hide())},show:function(){if(!this.options.disabled){this.Ak()&&this.ek.widget.hide();0===this.md.children().length&&this.Ip();this.md.width(this.element.parent().width());this.md.css({position:"relative"});this.fi=!0;var b=this.No();this.sD.ojPopup("open",this.element,{my:b?"right top":
"left top",at:b?"right bottom":"left bottom",collision:"fit"})}},hide:function(){this.fi&&(this.sD.ojPopup("close"),this.fi=!1,this.element.focus())},refresh:function(){this._superApply(arguments);this.Ip();return this},Hg:function(b){this.Ak()?this.Ju()&&this._superApply([this.wd().format(this.options.value)]):this._superApply(arguments)},ee:function(b,a,c){var d=this._superApply(arguments);d&&this.fi&&this.Ip();return d},Ql:function(){return this.Bk()},Bk:function(){return!this.Ak()||this.Ju()},
_GetDefaultStyleClass:function(){return"oj-inputtime"},Rj:function(){return this.options.value||""},zV:function(){},uN:function(){var b=this.wd(),a=this.options.value;return a?b.format(a):""},Ak:function(){return null!==this.ek},Ju:function(){return this.ek.inline},getNodeBySubId:function(b){var a=this._superApply(arguments);if(a)return a;a=b.subId;return"oj-listbox-drop"===a?this.md:"oj-inputdatetime-time-icon"===a?f(".oj-inputdatetime-time-icon",this.Cf):null},timeDisplay:function(){return this.md},
widget:function(){return this.Bk()?this._super():this.ek.widget.widget()}});a.Fa("oj.ojInputDateTime",f.oj.ojInputDate,{version:"1.0.0",widgetEventPrefix:"oj",_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-time oj-component oj-inputdatetime",_INPUT_HELPER_KEY:"inputHelpBoth",options:{converter:a.ba.ji(a.Pf.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit",hour:"2-digit",hour12:!0,minute:"2-digit"}),timeIncrement:"T00:30:00:00"},Mo:function(){this._super();this.nn=
this.element;this.Nq=this.Ae=null},_ComponentCreate:function(){var b=this._super(),a=this.WB(this.wd());if(null===a)throw Error("Plase use ojInputDate if you do not have time portion");if(this.Rc){var c=f("\x3cinput type\x3d'text'\x3e");c.insertAfter(this.element);this.nn=c}this.Ae=this.nn.ojInputTime({converter:a,optionChange:f.proxy(this.hS,this),timeIncrement:this.options.timeIncrement,datePicker:{widget:this,inline:this.Rc}});return b},Oj:function(){var b=this._superApply(arguments);this.Ae.ojInputTime("option",
"disabled",this.options.disabled);this.Rc&&this.nn.ojInputTime("option","value",this.nk());return b},_setOption:function(b,a,c){this.Ae&&("timeIncrement"===b||"disabled"===b?this.Ae.ojInputTime("option",b,a,c):"converter"===b&&(this.Nq=null,this.Ae.ojInputTime("option",b,this.WB(a),c)));return this._superApply(arguments)},_destroy:function(){var b=this._super();this.Ae.ojInputTime("destroy");this.Rc&&this.nn.remove();return b},WB:function(b){if(null!==this.Nq)return this.Nq;b=b.resolvedOptions();
var c={},d="hour hour12 minute second millisecond timeFormat".split(" "),k,l;k=0;for(l=d.length;k<l;k++)d[k]in b&&("timeFormat"===d[k]&&(c.formatType="time"),c[d[k]]=b[d[k]]);return f.isEmptyObject(c)?null:this.Nq=b=a.ba.ji(a.Pf.CONVERTER_TYPE_DATETIME).createConverter(c)},hS:function(b,a){if("value"===a.option){var c=new Date(this.nk());this.nA(a.value||new Date,c);this.ee(c,b,{Or:this.Ig.Ll})}},wq:function(b){var a=f.ui.keyCode,c=!1;if(!this.ve)switch(b.keyCode){case a.UP:case a.DOWN:b.shiftKey&&
(this.Ae.ojInputTime("show"),c=!0)}return c?(b.preventDefault(),b.stopPropagation(),!1):this._superApply(arguments)},show:function(){this.Ae.ojInputTime("hide");return this._super()},showTimePicker:function(){this.hide();return this.Ae.ojInputTime("show")},hideTimePicker:function(){return this.Ae.ojInputTime("hide")},timeDisplay:function(){return this.Ae.ojInputTime("timeDisplay")},refresh:function(){this._superApply(arguments);this.Ae.ojInputTime("refresh");return this},getNodeBySubId:function(b){return this._superApply(arguments)||
this.Ae.ojInputTime("getNodeBySubId",b)},_GetMessagingLauncherElement:function(){return this.Rc?this.nn:this._super()},_GetDefaultStyleClass:function(){return"oj-inputdatetime"},ly:function(){return"oj-ojInputDate"}})});
//# sourceMappingURL=oj-modular.map