/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery"],function(a,f){a.Mc=function(b){this.data=b;this.Init()};o_("DataSource",a.Mc,a);a.b.oa(a.Mc,a.b,"oj.DataSource");a.Mc.prototype.Init=function(){this.Nb=[];a.Mc.t.Init.call(this)};a.b.g("DataSource.prototype.Init",{Init:a.Mc.prototype.Init});a.Mc.prototype.on=function(b,a){var c=!1,e;for(e=0;e<this.Nb.length;e++)if(this.Nb[e].eventType==b&&this.Nb[e].eventHandlerFunc==a){c=!0;break}c||this.Nb.push({eventType:b,eventHandlerFunc:a})};a.b.g("DataSource.prototype.on",{on:a.Mc.prototype.on});
a.Mc.prototype.off=function(b,a){var c;for(c=this.Nb.length-1;0<=c;c--)if(this.Nb[c].eventType==b&&this.Nb[c].eventHandlerFunc==a){this.Nb.splice(c,1);break}};a.b.g("DataSource.prototype.off",{off:a.Mc.prototype.off});a.Mc.prototype.handleEvent=function(b,a){var c;for(c=0;c<this.Nb.length;c++){var e=this.Nb[c];e.eventType==b&&e.eventHandlerFunc(a)}};a.b.g("DataSource.prototype.handleEvent",{handleEvent:a.Mc.prototype.handleEvent});a.Mc.prototype.getCapability=function(){return null};a.b.g("DataSource.prototype.getCapability",
{getCapability:a.Mc.prototype.getCapability});a.sc=function(b){a.sc.t.constructor.call(this,b)};o_("TreeDataSource",a.sc,a);a.b.oa(a.sc,a.Mc,"oj.TreeDataSource");a.sc.prototype.df=function(){return-1};a.sc.prototype.Sd=function(){a.i.fa()};a.b.g("TreeDataSource.prototype.fetchChildren",{Sd:a.sc.prototype.Sd});a.sc.prototype.eh=function(){a.i.fa()};a.b.g("TreeDataSource.prototype.fetchDescendants",{eh:a.sc.prototype.eh});a.sc.prototype.sort=function(){a.i.fa()};a.b.g("TreeDataSource.prototype.sort",
{sort:a.sc.prototype.sort});a.sc.prototype.Gn=function(){return{key:null,direction:"none"}};a.b.g("TreeDataSource.prototype.getSortCriteria",{Gn:a.sc.prototype.Gn});a.sc.prototype.move=function(){a.i.fa()};a.b.g("TreeDataSource.prototype.move",{move:a.sc.prototype.move});a.sc.prototype.$n=function(){return"valid"};a.b.g("TreeDataSource.prototype.moveOK",{$n:a.sc.prototype.$n});a.sc.prototype.getCapability=function(){return null};a.b.g("TreeDataSource.prototype.getCapability",{getCapability:a.sc.prototype.getCapability});
a.ia=function(b,d){this.Hd=b;this.Xn=d;a.ia.t.constructor.call(this)};o_("FlattenedTreeDataSource",a.ia,a);a.b.oa(a.ia,a.Mc,"oj.FlattenedTreeDataSource");a.ia.prototype.Init=function(){var b;a.ia.t.Init.call(this);this.Hd.on("change",this.IO.bind(this));this.oh=parseInt(this.Xn.fetchSize,10);isNaN(this.oh)&&(this.oh=25);this.ph=parseInt(this.Xn.maxCount,10);isNaN(this.ph)&&(this.ph=500);b=this.Xn.expanded;Array.isArray(b)?this.nh=b:("all"===b&&(this.nl=[]),this.nh=[]);this.xi=[]};a.b.g("FlattenedTreeDataSource.prototype.Init",
{Init:a.ia.prototype.Init});a.ia.prototype.handleEvent=function(b,d){a.ia.t.handleEvent.call(this,b,d)};a.b.g("FlattenedTreeDataSource.prototype.handleEvent",{handleEvent:a.ia.prototype.handleEvent});a.ia.prototype.uo=function(){delete this.xi;delete this.nh;this.Hd.off("change");this.Hd.uo&&this.Hd.uo()};a.b.g("FlattenedTreeDataSource.prototype.Destory",{uo:a.ia.prototype.uo});a.ia.prototype.nG=function(){return this.nh};a.b.g("FlattenedTreeDataSource.prototype.getExpandedKeys",{nG:a.ia.prototype.nG});
a.ia.prototype.lr=function(b){return null!=this.Xn?this.Xn[b]:null};a.b.g("FlattenedTreeDataSource.prototype.getOption",{lr:a.ia.prototype.lr});a.ia.prototype.getWrappedDataSource=function(){return this.Hd};a.b.g("FlattenedTreeDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.ia.prototype.getWrappedDataSource});a.ia.prototype.$F=function(b,a){this.iq()?this.QM(b,a):this.PM(b,a)};a.ia.prototype.PM=function(b,d){var c,e,g,f,k,l;if(b.start>this.Pc()){c=this.Zt();if(0>this.Pc()){b.count=
Math.min(c,b.count);this.Hd.Sd(null,b,{success:function(a){this.Zp(a,null,0,b,0,d)}.bind(this)});return}if(0<c){e=this.CB();g=e.parent;f=this.Hd.df(g);k=e.index;l=e.depth;-1===f||k<f-1?(b.start=k+1,b.count=-1===f?this.oh:Math.min(c,Math.min(this.oh,f-b.start)),this.Hd.Sd(g,b,{success:function(a){this.Zp(a,g,l,b,f,d)}.bind(this)})):k===f-1?(c=new a.Yc(null,b.start),null!=d&&null!=d.success&&d.success.call(null,c)):(c=this.dB(g,l,d,c),c||(c=new a.Yc(null,b.start),null!=d&&null!=d.success&&d.success.call(null,
c)));return}}this.Mw(b,d)};a.ia.prototype.Zt=function(){return this.ph-(this.Pc()+1)};a.ia.prototype.Zp=function(b,d,c,e,g,f){var k;k=[];b=new a.cd(b,this.Ln.bind(this),e);this.AQ(b,d,c,k);-1===g&&0===b.Y()&&null!=d&&0<c?(d=this.dB(d,c,f))||null!=f&&null!=f.success&&f.success.call(null,b):(null!=f&&null!=f.success&&f.success.call(null,b),this.KM(k))};a.ia.prototype.dB=function(b,a,c,e){var g,f,k,l,n,m,q,t;void 0===e&&(e=this.Zt());this.wC()&&(g={queueOnly:!0});f=this.oh;for(k=this.Pc()-1;0<=k;k--)if(l=
this.xe(k),n=l.depth,n<a&&(b=l.parent,m=this.Hd.df(b),l=l.index,(q=-1===m)||l<m-1)){t={};t.start=l+1;q?(t.count=Math.min(e,Math.max(0,f)),g=void 0):t.count=Math.min(e,Math.min(f,m-t.start));if(0==t.count)break;this.Hd.Sd(b,t,{success:function(a){this.Zp(a,b,n,t,m,c)}.bind(this)},g);a=n;f=Math.max(0,f-t.count);if(q||0===n||0===f)break}void 0!=g&&this.Hd.Sd(b,{start:t.count,count:0},{success:function(a){this.Zp(a,b,n,t,m,c)}.bind(this)});return f!=this.oh};a.ia.prototype.AQ=function(b,a,c,e){var g,
f,k,l;g=b.Da();f=b.Y();for(k=0;k<f;k++)l=b.getMetadata(g+k),l=l.key,this.ap(l,c,g+k,a),this.jq(l)&&e.push(l)};a.ia.prototype.Ln=function(b,a){this.jq(b)&&!a.leaf?a.state="expanded":a.state=a.leaf?"leaf":"collapsed"};a.ia.prototype.QM=function(b,a){var c={maxCount:this.ph};0<=this.Pc()&&(c.start=this.xe(this.Pc()).key);this.Hd.eh(null,{success:function(c){this.sO(c,b,a)}.bind(this)},c)};a.ia.prototype.sO=function(b,d,c){var e,g,f;d.start>this.Pc()?(e=this.Zt(),g=Math.min(e,d.count),b=new a.cd(b,this.Ln.bind(this)),
0<=this.Pc()?(f=this.CB(),e={index:0,found:!1,count:0},this.mv(b,null,0,f,g,e),g=e.index+1):(e={count:0},this.mv(b,null,0,null,g,e),g=0),null!=c&&null!=c.success&&(b=null!=e?0===e.count?new a.Yc(null,d.start):new a.Zc(b,g):new a.Zc(b),c.success.call(null,b))):this.Mw(d,c)};a.ia.prototype.mv=function(b,a,c,e,g,f){var k,l,n,m,q;k=b.Da();l=b.Y();for(n=0;n<l&&f.count!=g;n++){m=b.getMetadata(k+n);q=m.key;f.checkDepth&&e.depth===c&&(f.found=!0,f.checkDepth=!1);if(null==e||f.found)this.ap(q,c,k+n,a),f.count+=
1,m.state=m.leaf?"leaf":"expanded";null==e||f.found||(q===e.key?m.leaf||this.jq(q)?f.found=!0:f.checkDepth=!0:f.index+=1);b.Ed&&(m=b.Ed(n),null!=m&&this.mv(m,q,c+1,e,g,f))}};a.ia.prototype.expand=function(b){this.cg(b)};a.b.g("FlattenedTreeDataSource.prototype.expand",{expand:a.ia.prototype.expand});a.ia.prototype.cg=function(b,d){var c,e,g;c=this.Hd.df(b);e=Math.min(this.oh,-1==c?this.oh:c);if(this.Pc()+1===this.ph&&(g=this.gl(b),g==this.ph-1)){this.Lw(b,new a.Yc(b,0),0,d);return}0==e?this.Lw(b,
new a.Yc(b,0),0,d):this.Hd.Sd(b,{start:0,count:e},{success:function(a){this.Lw(b,a,c,d)}.bind(this)})};a.ia.prototype.collapse=function(b){var a,c,e,g,f;a=this.gl(b)+1;c=this.xe(a-1);e=0;c=c.depth;g=this.Pc();for(f=a;f<g+1;f++){var k=this.xe(f).depth;if(k>c)e+=1;else if(k==c)break}if(0!=e){this.iq()?this.nl.push(b):this.aR(b);g=[];for(c=0;c<e;c++)g.push({key:this.xe(a+c).key,index:a+c});this.$D(a,e);this.Er(g);this.handleEvent("collapse",{rowKey:b})}};a.b.g("FlattenedTreeDataSource.prototype.collapse",
{collapse:a.ia.prototype.collapse});a.ia.prototype.jq=function(b){return this.iq()?this.nl&&0<this.nl.length?-1===this.nB(b):!0:this.nh&&0<this.nh.length?-1<this.xB(b):!1};a.ia.prototype.nB=function(b){return this.BB(this.nl,b)};a.ia.prototype.xB=function(b){return this.BB(this.nh,b)};a.ia.prototype.BB=function(b,a){var c,e;e=-1;for(c=0;c<b.length;c++)b[c]===a&&(e=c);return e};a.ia.prototype.aR=function(b){b=this.xB(b);-1<b&&this.nh.splice(b,1)};a.ia.prototype.WQ=function(b){b=this.nB(b);-1<b&&this.nl.splice(b,
1)};a.ia.prototype.Lw=function(b,d,c,e){var g,f,k,l,n,m,q,t,p,r,s;d=new a.cd(d,this.Ln.bind(this));f=g=this.gl(b)+1;k=d.Da();l=d.Y();n=this.xe(g-1);m=n.depth+1;t=[];for(p=k;p<l;p++)k=d.getMetadata(p),q=k.key,this.jq(q)&&t.push(q),this.uC(g,k,n.key,p,m),g++;this.iq()?this.WQ(b):-1===this.nh.indexOf(b)&&this.nh.push(b);void 0!=e&&(r=e.queue,s=e.prevNodeSetInfo);void 0!=s&&(d=new a.ce(s.nodeSet,d,b));if(0!=t.length||void 0!==r&&0!=r.length)void 0===r&&(r=[]),0<t.length&&r.push(t),void 0===s&&(s={},s.firstIndex=
f,s.firstKey=b,s.keys=[]),s.nodeSet=d,s.keys.push(b),this.cS(r,s);else{void 0!=s?this.qr(s.firstIndex,s.firstKey,d):this.qr(f,b,d);-1===c&&l===this.oh||c>l||g==this.ph?this.st(g):this.Pc()>=this.ph&&this.st(this.ph);if(void 0!=s)for(d=0;d<s.keys.length;d++)this.handleEvent("expand",{rowKey:s.keys[d]});this.handleEvent("expand",{rowKey:b})}};a.ia.prototype.cS=function(b,a){var c,e;c=b[b.length-1];e=c.shift();0===c.length&&b.pop();this.cg(e,{prevNodeSetInfo:a,queue:b})};a.ia.prototype.KM=function(b){var a,
c;this.wC()&&(a={queueOnly:!0});for(c=0;c<b.length;c++)c==b.length-1?this.cg(b[c]):this.cg(b[c],a)};a.ia.prototype.uC=function(b,a,c,e,g){a=a.key;b<=this.Pc()?this.ap(a,g,e,c,b):this.ap(a,g,e,c)};a.ia.prototype.st=function(b,a){var c;void 0==a&&(a=this.Pc()+1-b);c=[];for(var e=0;e<a;e++)c.push({row:this.xe(b+e).key});this.$D(b,a);this.Er(c)};a.ia.prototype.IO=function(b){var a,c,e;a=b.operation;c=b.parent;c=Array.isArray(c)?c[c.length-1]:c;e=b.index;"insert"===a?this.vO(c,e,b.data):"delete"===a?this.pO(c,
e):"refresh"===a&&this.KO(c)};a.ia.prototype.vO=function(b,a,c){var e,g;e=this.gl(b);g=this.xe(e).depth+1;e=e+a+1;c=c.getMetadata(c.Da());this.uC(e,c,b,a,g)};a.ia.prototype.pO=function(b,d){var c,e,g,f,k;c=this.gl(b);e=this.xe(c);c+=d;g=this.xe(c);a.i.assert(g.parent===e&&g.depth===e.depth+1);e=c+1;for(f=this.Pc();e<=f;){k=this.xe(e);if(k.depth!=g.depth)break;e++}this.st(c,1)};a.ia.prototype.KO=function(b){null==b&&this.refresh()};a.ia.prototype.iq=function(){var b=this.Hd.getCapability("fetchDescendants");
return void 0!=this.nl&&null!=b&&"disable"!=b};a.ia.prototype.wC=function(){return"enable"===this.Hd.getCapability("batchFetch")};a.ia.prototype.refresh=function(){this.lL()};a.ia.prototype.gl=function(b){var a,c,e;a=this.Pc();for(c=0;c<=a;c++)if(e=this.xe(c),e.key==b)return c;return-1};a.ia.prototype.getKey=function(b){return 0>b||b>this.Pc()?null:this.xe(b).key};a.ia.prototype.pG=function(){return{start:0,end:this.Pc()+1}};a.ia.prototype.Mw=function(b,a){null!=a&&null!=a.error&&a.error.call(null)};
a.ia.prototype.qr=function(){a.i.fa()};a.ia.prototype.Er=function(){a.i.fa()};a.ia.prototype.Pc=function(){return this.xi.length-1};a.ia.prototype.CB=function(){return this.xi[this.Pc()]};a.ia.prototype.xe=function(b){return this.xi[b]};a.ia.prototype.ap=function(b,a,c,e,g){var f={};f.key=b;f.depth=a;f.index=c;f.parent=e;void 0===g?this.xi.push(f):this.xi.splice(g,0,f)};a.ia.prototype.$D=function(b,a){this.xi.splice(b,a)};a.ia.prototype.lL=function(){this.xi.length=0};a.Tj=function(){this.id=null;
this.depth=0;this.parent=null;this.children=[];this.Yw=this.attr=this.title=null};a.Tj.prototype.NK=function(b){return function(a,c){return a.attr&&c.attr&&a.attr[b]&&c.attr[b]?a.attr[b]<c.attr[b]?0:1:a[b]<c[b]?0:1}};a.Tj.prototype.lM=function(b){return function(a,c){return a.attr&&c.attr&&a.attr[b]&&c.attr[b]?a.attr[b]<c.attr[b]?1:0:a[b]<c[b]?1:0}};a.Tj.prototype.XE=function(b){var a=b.key;"ascending"===b.direction?this.children.sort(this.NK(a)):"descending"===b.direction&&this.children.sort(this.lM(a));
for(var a=0,c=this.children.length;a<c;a++)this.children[a].XE(b)};a.Ub=function(b){var d;d=new a.Tj;b.id||(d.id="root");this.data=this.vA(0,d,b);a.Ub.t.constructor.call(this,d)};o_("JsonTreeDataSource",a.Ub,a);a.b.oa(a.Ub,a.sc,"oj.JsonTreeDataSource");a.Ub.prototype.Init=function(){a.Ub.t.Init.call(this)};a.b.g("JsonTreeDataSource.prototype.Init",{Init:a.Ub.prototype.Init});a.Ub.prototype.vA=function(b,d,c,e){var g,f,k,l,n,m,q;e||(e=0);for(l in c)if("children"==l||0==e&&c instanceof Array)for(g=
0==e&&c instanceof Array?c:c[l],e++,q=0;q<g.length;q++){k=g[q];f=new a.Tj;k.id||(b++,k.attr?k.attr.id||(k.attr.id="rid_"+b):f.id="rid_"+b);for(n in k)for(m in f)n==m&&"children"!=n&&(f[m]=k[n]),"depth"==m&&(f[m]=e);d.children.push(f);for(m in k)"children"==m&&this.vA(b,d.children[q],k,e)}return d};a.Ub.prototype.df=function(b){b||(b=this.data.id);b=this.$h(this.data,b);return b.children?b.children.length:0};a.b.g("JsonTreeDataSource.prototype.getChildCount",{df:a.Ub.prototype.df});a.Ub.prototype.Sd=
function(b,d,c){var e,g,f,k,l;f=[];b||(b=this.data.id);k=this.$h(this.data,b);d||(d=[],d.start=0,d.count=k.children.length);d.count||(d.count=k.children.length);d.start||(d.start=0);e=d.start;g=Math.min(k.children.length,e+d.count);for(d=e;d<g;d+=1)l=new a.Tj,k.children[d].attr&&(l.attr=k.children[d].attr),k.children[d].id&&(l.id=k.children[d].id),k.children[d].depth&&(l.depth=k.children[d].depth),k.children[d].title&&(l.title=k.children[d].title),k.children[d].parent&&(l.parent=k.children[d].parent),
l.Yw=0<k.children[d].children.length?!1:!0,f.push(l);b=new a.bd(e,g,f,b);null!=c&&null!=c.success&&c.success.call(null,b)};a.b.g("JsonTreeDataSource.prototype.fetchChildren",{Sd:a.Ub.prototype.Sd});a.Ub.prototype.eh=function(b,d){var c,e,g,f;g=[];b||(b=this.data.id);f=this.$h(this.data,b);c=[];c.start=0;c.count=f.children.length;e=c.start;for(c=Math.min(f.children.length,e+c.count);e<c;e+=1)f.children[e].Yw=0<f.children[e].children.length?!1:!0,g.push(f.children[e]);g=new a.bd(0,g.length,g,b);null!=
d&&null!=d.success&&d.success.call(null,g)};a.b.g("JsonTreeDataSource.prototype.fetchDescendants",{eh:a.Ub.prototype.eh});a.Ub.prototype.move=function(b,a,c,e){var g;g=a;if(!g||g==this.data.id){if("inside"!=c){console.log("Error: root can not be the reference node if position equals to "+c);return}g||(g=this.data.id)}b=this.$h(null,b);this.$h(b,g)?console.log("Error: the node to move contains the reference node as its sub-tree."):(a=this.$h(null,g),g=this.fu(g),this.bR(b),"inside"==c?(this.$g(b,b.depth-
(a.depth+1)),a.children.push(b)):"before"==c?(this.$g(b,b.depth-a.depth),c=g.children.indexOf(a),-1<c&&(0!=c?g.children.splice(c-1,0,b):g.children.unshift(b))):"after"==c?(this.$g(b,b.depth-a.depth),c=g.children.indexOf(a),-1<c&&g.children.splice(c,0,b)):"first"==c?(this.$g(b,b.depth-a.depth),g.children.unshift(b)):"last"==c&&(this.$g(b,b.depth-a.depth),g.children.push(b)),null!=e&&null!=e.success&&e.success.call(null,this.data))};a.b.g("JsonTreeDataSource.prototype.move",{move:a.Ub.prototype.move});
a.Ub.prototype.sort=function(b,a){var c;c=this.$h(this.data,this.data.id);c.XE(b);null!=a&&null!=a.success&&a.success.call(null,c)};a.b.g("JsonTreeDataSource.prototype.sort",{sort:a.Ub.prototype.sort});a.Ub.prototype.fu=function(b,a){var c,e=null;if(b==this.data.id)return null;a||(a=this.data);if(a.children&&0<a.children.length){for(c=0;c<a.children.length;c++)if(a.children[c].id&&a.children[c].id==b||a.children[c].attr&&a.children[c].attr.id==b)return a;for(c=0;c<a.children.length&&!(e=this.fu(b,
a.children[c]));c++);}return e};a.Ub.prototype.$h=function(b,a){var c,e=null;b||(b=this.data);if(b.id&&b.id==a||b.attr&&b.attr.id==a)return b;if(null!=b.children)for(c=0;c<b.children.length&&!e;c++)e=b.children[c].id&&b.children[c].id==a||b.children[c].attr&&b.children[c].attr.id==a?b.children[c]:this.$h(b.children[c],a);return e};a.Ub.prototype.$g=function(b,a){var c;b.depth-=a;if(b.children&&0!=b.children.length)for(c=0;c<b.children.length;c++)this.$g(b.children[c],a)};a.Ub.prototype.bR=function(b){var a;
b.id?a=b.id:b.attr&&(a=b.attr.id);(a=this.fu(a))||(a=this.data);b=a.children.indexOf(b);-1<b&&a.children.splice(b,1)};a.Ub.prototype.getCapability=function(b){return"fetchDescendants"===b?"enable":"sort"===b?"default":"batchFetch"===b?"disable":"move"===b?"full":null};a.b.g("JsonTreeDataSource.prototype.getCapability",{getCapability:a.Ub.prototype.getCapability});a.eb=function(b,d){a.eb._init(this,b,d,null)};o_("Row",a.eb,a);a.b.oa(a.eb,a.b,"Row.Row");a.eb.prototype.Init=function(){a.eb.t.Init.call(this)};
a.eb.prototype.attributes={};a.b.g("Row.prototype.attributes",{attributes:a.eb.prototype.attributes});a.eb.prototype.context={};a.b.g("Row.prototype.context",{context:a.eb.prototype.context});a.eb.prototype.id=null;a.b.g("Row.prototype.id",{id:a.eb.prototype.id});a.eb.prototype.He=null;a.b.g("Row.prototype.idAttribute",{He:a.eb.prototype.He});a.eb._init=function(b,a,c,e){a=null;b.Init();b.index=-1;c=c||{};b.attributes={};for(a in e)e.hasOwnProperty(a)&&(b[a]=e[a]);b.rowSet=c.rowSet;b.context=c.context};
a.eb.prototype.clone=function(){a.i.fa();return null};a.b.g("Row.prototype.clone",{clone:a.eb.prototype.clone});a.eb.prototype.get=function(){a.i.fa();return null};a.b.g("Row.prototype.get",{get:a.eb.prototype.get});a.eb.prototype.set=function(){a.i.fa();return null};a.b.g("Row.prototype.set",{set:a.eb.prototype.set});a.eb.prototype.keys=function(){a.i.fa();return null};a.b.g("Row.prototype.keys",{keys:a.eb.prototype.keys});a.eb.prototype.values=function(){a.i.fa();return null};a.b.g("Row.prototype.values",
{values:a.eb.prototype.values});a.eb.prototype.pairs=function(){a.i.fa();return null};a.b.g("Row.prototype.pairs",{pairs:a.eb.prototype.pairs});a.U=function(b,d){a.U._init(this,b,d,null)};o_("RowSet",a.U,a);a.U.prototype.af=null;a.b.g("RowSet.prototype.comparator",{af:a.U.prototype.af});a.U.prototype.Mf=!0;a.b.g("RowSet.prototype.sortSupported",{Mf:a.U.prototype.Mf});a.b.oa(a.U,a.b,"RowSet.RowSet");a.U.prototype.Init=function(){a.U.t.Init.call(this)};a.U._init=function(b,a,c,e){var g;b.Nb=[];b.Init();
if(e)for(g in e)e.hasOwnProperty(g)&&(b[g]=e[g])};a.U.prototype.at=function(){a.i.fa();return null};a.b.g("RowSet.prototype.at",{at:a.U.prototype.at});a.U.prototype.fetch=function(){a.i.fa()};a.b.g("RowSet.prototype.fetch",{fetch:a.U.prototype.fetch});a.U.prototype.get=function(){a.i.fa();return null};a.b.g("RowSet.prototype.get",{get:a.U.prototype.get});a.U.prototype.hasMore=function(){a.i.fa();return!1};a.b.g("RowSet.prototype.hasMore",{hasMore:a.U.prototype.hasMore});a.U.prototype.indexOf=function(){a.i.fa();
return 0};a.b.g("RowSet.prototype.indexOf",{indexOf:a.U.prototype.indexOf});a.U.prototype.isEmpty=function(){a.i.fa();return!0};a.b.g("RowSet.prototype.isEmpty",{isEmpty:a.U.prototype.isEmpty});a.U.prototype.size=function(){a.i.fa();return 0};a.b.g("RowSet.prototype.size",{size:a.U.prototype.size});a.U.prototype.sort=function(){a.i.fa()};a.b.g("RowSet.prototype.sort",{sort:a.U.prototype.sort});a.U.prototype.totalSize=function(){a.i.fa();return 0};a.b.g("RowSet.prototype.totalSize",{totalSize:a.U.prototype.totalSize});
a.U.prototype.on=function(b,a){var c=!1,e;for(e=0;e<this.Nb.length;e++)if(this.Nb[e].eventType==b&&this.Nb[e].eventHandlerFunc==a){c=!0;break}c||this.Nb.push({eventType:b,eventHandlerFunc:a})};a.b.g("RowSet.prototype.on",{on:a.U.prototype.on});a.U.prototype.off=function(b,a){var c;for(c=0;c<this.Nb.length;c++)if(this.Nb[c].eventType==b&&this.Nb[c].eventHandlerFunc==a){this.Nb.remove(this.Nb[c]);break}};a.b.g("RowSet.prototype.off",{off:a.U.prototype.off});a.U.prototype.xc=function(b,a){var c;for(c=
0;c<this.Nb.length;c++){var e=this.Nb[c];e.eventType==b&&e.eventHandlerFunc(a)}};a.U.v={ADD:"add",REMOVE:"remove",RESET:"reset",REFRESH:"refresh",SORT:"sort",CHANGE:"change",REQUEST:"request",SYNC:"sync",ERROR:"error"};o_("RowSet.EventType",a.U.v,a);a.U.VJ={kV:"added",pV:"deleted",vV:"updated",sV:"none"};o_("RowSet._ROW_STATUSES",a.U.VJ,a);a.Ja=function(b,d){a.Ja._init(this,b,d,null)};o_("ArrayRow",a.Ja,a);a.b.oa(a.Ja,a.eb,"ArrayRow.ArrayRow");a.Ja.prototype.Init=function(){a.Ja.t.Init.call(this)};
a.Ja.prototype.attributes={};a.b.g("ArrayRow.prototype.attributes",{attributes:a.Ja.prototype.attributes});a.Ja.prototype.id=null;a.b.g("ArrayRow.prototype.id",{id:a.Ja.prototype.id});a.Ja.prototype.He=null;a.b.g("ArrayRow.prototype.idAttribute",{He:a.Ja.prototype.He});a.Ja._init=function(b,a,c,e){var g=null;b.Init();b.index=-1;c=c||{};b.attributes=a;for(g in e)e.hasOwnProperty(g)&&(b[g]=e[g]);b.idAttribute=c.idAttribute;b.context=c.context;b.Jv()};a.Ja.prototype.clone=function(){var b=new this.constructor,
d;for(d in this)this.hasOwnProperty(d)&&this[d]!==this.attributes&&(b[d]=this[d]);b.attributes=a.Ja.Og(this.attributes,null);b.Jv();return b};a.b.g("ArrayRow.prototype.clone",{clone:a.Ja.prototype.clone});a.Ja.prototype.get=function(b){return this.attributes[b]};a.b.g("ArrayRow.prototype.get",{get:a.Ja.prototype.get});a.Ja.prototype.set=function(b,d,c){var e={},g=!1;if(arguments&&0<arguments.length)if(1<arguments.length&&arguments[arguments.length-1]&&(g=!0,e=arguments[arguments.length-1]||{}),a.Ja.cj(b))this.Sk(b,
e);else for(e=0;e<arguments.length;e+=2)(void 0!==arguments[e]||e<arguments.length-1||!g&&e===arguments.length-1)&&this.Sk(arguments[e],arguments[e+1]);return this};a.b.g("ArrayRow.prototype.set",{set:a.Ja.prototype.set});a.Ja.prototype.keys=function(){var b,a=[];for(b in this.attributes)this.attributes.hasOwnProperty(b)&&a.push(b);return a};a.b.g("ArrayRow.prototype.keys",{keys:a.Ja.prototype.keys});a.Ja.prototype.values=function(){var b,a=[];for(b in this.attributes)this.attributes.hasOwnProperty(b)&&
a.push(this.get(b));return a};a.b.g("ArrayRow.prototype.values",{values:a.Ja.prototype.values});a.Ja.prototype.pairs=function(){var b,a=[],c;for(b in this.attributes)this.attributes.hasOwnProperty(b)&&(c=[],c.push(b),c.push(this.get(b)),a.push(c));return a};a.b.g("ArrayRow.prototype.pairs",{pairs:a.Ja.prototype.pairs});a.Ja.prototype.Ut=function(){return this.idAttribute||"id"};a.Ja.prototype.hu=function(b){return this[b]instanceof Function?this[b]():this[b]};a.Ja.cj=function(b){var a;if(b&&b instanceof
Object)for(a in b)if(b.hasOwnProperty(a))return!0;return!1};a.Ja.prototype.Jv=function(){var b=this.Ut();if("string"===f.type(b))this.id=this.attributes[b];else if(f.isArray(b)){var a;this.id=[];for(a=0;a<b.length;a++)this.id[a]=this.attributes[b[a]]}};a.Ja.prototype.Gv=function(b,d){return a.b.Ni(this.attributes[b],d)?!1:(this.attributes[b]=d,this.Jv(),a.Z.t.xc.call(this.rowSet,a.U.v.CHANGE,this),!0)};a.Ja.prototype.Sk=function(b,a){if(null==b)return!0;var c={},e;if(1<arguments.length)c[b]=a;else for(e in b)b.hasOwnProperty(e)&&
(c[e]=b[e]);for(e in c)c.hasOwnProperty(e)&&this.Gv(e,c[e]);return!0};a.Ja.Og=function(b,d){var c;d=d||{};for(c in b)b.hasOwnProperty(c)&&("object"!==typeof b[c]?d.hasOwnProperty(c)?void 0!==b[c]&&(d[c]=b[c]):d[c]=b[c]:d[c]=a.Ja.Og(b[c],null));return d};a.Z=function(b,d){a.Z._init(this,b,d,null)};o_("ArrayRowSet",a.Z,a);a.Z.prototype.af=null;a.b.g("ArrayRowSet.prototype.comparator",{af:a.Z.prototype.af});a.Z.prototype.Mf=!0;a.b.g("ArrayRowSet.prototype.sortSupported",{Mf:a.Z.prototype.Mf});a.b.oa(a.Z,
a.U,"ArrayRowSet.ArrayRowSet");a.Z.prototype.Init=function(){a.Z.t.Init.call(this)};a.Z._init=function(b,d,c,e){var g;b.Nb=[];b.O=0;b.Init();if(e)for(g in e)e.hasOwnProperty(g)&&(b[g]=e[g]);c=c||{};b.sb=[];b.Xg=[];null!=d&&void 0!==d&&(b.Hm="id",null!=c&&null!=c.idAttribute&&(b.Hm=c.idAttribute),b.f=d instanceof Array?d:d(),b.sb=a.Z.SN(b.f,b.Hm,b),b.Bf=b.f.length,d instanceof Array||d.subscribe(function(c){var e,g,f=0;g=!0;for(e=0;e<c.length;e++)"deleted"!=c[e].status&&(g=!1);if(0==d().length&&g)b.reset();
else{for(e=0;e<c.length;e++)"deleted"===c[e].status&&(g=new a.Ja(c[e].value,{idAttribute:b.Hm}),b.Zh(g,c[e].index-f),f++);for(e=0;e<c.length;e++)"added"===c[e].status&&(g=new a.Ja(c[e].value,{idAttribute:b.Hm}),b.add(g,{at:c[e].index}))}},null,"arrayChange"))};a.Z.prototype.add=function(b,a){a=a||{};var c=a.deferred;this.AK(b,a.at,a);return c?f.Deferred().resolve().promise():null};a.b.g("ArrayRowSet.prototype.add",{add:a.Z.prototype.add});a.Z.prototype.at=function(b,a){a=a||{};if(0>b||b>=this.sb.length)return null;
var c=this.sb[b];return a.deferred?f.Deferred().resolve(c).promise():c};a.b.g("ArrayRowSet.prototype.at",{at:a.Z.prototype.at});a.Z.prototype.clone=function(){var b=new this.constructor,a,c;for(a=0;a<this.sb.length;a+=1)(c=this.at(a,null))&&b.add(c.clone(),{at:a});return b};a.b.g("ArrayRowSet.prototype.clone",{clone:a.Z.prototype.clone});a.Z.prototype.fetch=function(b){b=b||{};this.Nv();this.lb=0<b.pageSize?b.pageSize:-1;this.O=null!=b?null!=b.startIndex?b.startIndex:0:0;this.Xg=a.Z.eu(this.sb,this.O,
this.lb);b.pageSize=this.lb;b.startIndex=this.O;b.refresh=!0;this.qm(b)};a.b.g("ArrayRowSet.prototype.fetch",{fetch:a.Z.prototype.fetch});a.Z.prototype.get=function(b,a){a=a||{};var c=a.deferred,e,g,h,k=null;for(e=0;e<this.sb.length;e+=1)if(h=this.sb[e],void 0!==h){if(f.isArray(h.id)&&f.isArray(b)){if(h.id.length==b.length){var l=!0;for(g=0;g<b.length;g++)if(h.id[g]!=b[g]){l=!1;break}l&&(k=h)}}else h.id==b&&(k=h);if(null!=k)return c?f.Deferred().resolve(k):k}return null};a.b.g("ArrayRowSet.prototype.get",
{get:a.Z.prototype.get});a.Z.prototype.hasMore=function(){return!1};a.b.g("ArrayRowSet.prototype.hasMore",{hasMore:a.Z.prototype.hasMore});a.Z.prototype.indexOf=function(b,a){a=a||{};return a.deferred?this.get(b.id,null).then(function(b){return b.index}):this.get(b.id).index};a.b.g("ArrayRowSet.prototype.indexOf",{indexOf:a.Z.prototype.indexOf});a.Z.prototype.isEmpty=function(){return 0===this.Xg.length};a.b.g("ArrayRowSet.prototype.isEmpty",{isEmpty:a.Z.prototype.isEmpty});a.Z.prototype.remove=function(b,
a){a=a||{};this.Zh(b,-1,a)};a.b.g("ArrayRowSet.prototype.remove",{remove:a.Z.prototype.remove});a.Z.prototype.reset=function(b,d){var c;d=d||{};d.previousRows=this.sb;var e=d.silent;if(void 0===b||null==b||b instanceof Array&&0==b.length){for(c=0;c<this.sb.length;c+=1)this.sb[c]&&(this.sb[c].rowSet=null);this.sb=[];this.Bf=0}else if(this.sb=[],this.Bf=0,b instanceof Array)for(c=0;c<b.length;c+=1)this.add(b[c],d);else this.add(b,d);e||a.Z.t.xc.call(this,a.U.v.RESET,null)};a.b.g("ArrayRowSet.prototype.reset",
{reset:a.Z.prototype.reset});a.Z.prototype.size=function(){return this.Xg.length};a.b.g("ArrayRowSet.prototype.size",{size:a.Z.prototype.size});a.Z.prototype.sort=function(){var b=this.comparator,d;this.zu()&&(d=this,this.sb.sort(function(c,e){return a.Z.WE(c,e,b,d,d)}),this.rv(this.sb),this.Xg=a.Z.eu(this.sb,this.O,this.lb),this.YE=!0,a.Z.t.xc.call(this,a.U.v.SORT,null))};a.b.g("ArrayRowSet.prototype.sort",{sort:a.Z.prototype.sort});a.Z.prototype.totalSize=function(){return this.Bf};a.b.g("ArrayRowSet.prototype.totalSize",
{totalSize:a.Z.prototype.totalSize});a.Z.prototype.AK=function(b,d,c){var e,g;c=c||{};var f=c.silent;b instanceof Array||(b=[b]);for(c=0;c<b.length;c++){g=b[c];g instanceof a.Ja||(g=new a.Ja(g,{idAttribute:this.Hm}));this.Xg&&0!=this.Xg.length||(this.Xg=a.Z.eu(this.sb,this.O,this.lb));if(!0==this.YE)for(e=0;e<this.sb.length;e++)if(0>a.Z.WE(g,this.sb[e],this.comparator,this,this)){this.sb.splice(e,0,g);g.index=e;break}else{if(e==this.sb.length-1){this.sb.push(g);g.index=e+1;break}}else void 0===d?
(this.sb.push(g),g.index=this.sb.length-1):(this.sb.splice(d+c,0,g),g.index=d+c);g.rowSet=this;g.index<=a.Z.Ot(this.sb,this.O,this.lb)&&this.Xg.splice(g.index,0,g);this.Bf++;this.rv(this.sb);f||a.Z.t.xc.call(this,a.U.v.ADD,g)}};a.Z.prototype.ku=function(b){return void 0===b?[]:b.split(",")};a.Z.prototype.lu=function(){return-1===this.sortDirection?"dsc":"asc"};a.Z.prototype.zu=function(){var b=this.comparator;return void 0!==b&&null!==b};a.Z.prototype.rv=function(b){for(var a,c=0;c<b.length;c++)(a=
b[c])&&(a.index=c)};a.Z.prototype.Zh=function(b,d,c){var e,g;c=c||{};var f=c.silent;b instanceof Array||(b=[b]);for(e=0;e<b.length;e++)if(g=b[e],(0>d||!0==this.YE)&&null!=this.get(g.id)&&(d=this.get(g.id).index),-1<d){void 0!==g&&g.MU===this&&(g.MU=null);var k=a.Z.Ot(this.sb,this.O,this.lb);this.sb.splice(d,1);d<=k&&this.Xg.splice(d,1);this.Bf--;this.rv(this.sb);f||(c.index=d,void 0!==g&&(f||a.Z.t.xc.call(this,a.U.v.REMOVE,g)))}return g};a.Z.prototype.Nv=function(){a.Z.t.xc.call(this,a.U.v.REQUEST,
null)};a.Z.prototype.qm=function(b){a.Z.t.xc.call(this,a.U.v.SYNC,b)};a.Z.Pg=function(b,a,c){if(-1===c){if(b<a)return 1;if(a<b)return-1}else{if(b>a)return 1;if(a>b)return-1}return 0};a.Z.Ot=function(b,a,c){var e=b.length-1;0<c&&(e=a+c-1,e=e>b.length-1?b.length-1:e);return e};a.Z.zm=function(b,d){return b instanceof a.eb?b.get(d):f.isFunction(b[d])?b[d]():b[d]};a.Z.eu=function(b,d,c){d=a.Z.Ot(b,d,c);c=[];var e,g;for(e=0;e<=d;e++)g=b[e],g.index=e,c[e]=g;return c};a.Z.SN=function(b,d,c){var e=b.length-
1,g=[],f,k;for(f=0;f<=e;f++){var l={},n=null,n=b[f]instanceof a.eb?b[f].pairs():b[f];for(k in n)n.hasOwnProperty(k)&&(l[k]=n[k]);l=new a.Ja(l,{idAttribute:d});l.index=f;g[f]=l;l.rowSet=c}return g};a.Z.WE=function(b,d,c,e,g){var h,k,l;if(f.isFunction(c)){if(1===c.length){h=c.call(g,b);k=c.call(g,d);h=a.fb.Fd(h)?h.split(","):[h];var n=a.fb.Fd(k)?k.split(","):[k];for(l=0;l<h.length;l++)if(k=a.Z.Pg(h[l],n[l],e.sortDirection),0!==k)return k}return c.call(g,b,d)}if(a.fb.Fd(c))for(c=c.split(","),l=0;l<c.length;l++)if(h=
a.Z.zm(b,c[l]),k=a.Z.zm(d,c[l]),k=a.Z.Pg(h,k,e.sortDirection),0!==k)return k;return 0};a.Yc=function(b,a){this.oU=b;this.Jc=a};o_("EmptyNodeSet",a.Yc,a);a.Yc.prototype.getParent=function(){return this.oU};a.b.g("EmptyNodeSet.prototype.getParent",{getParent:a.Yc.prototype.getParent});a.Yc.prototype.Da=function(){return this.Jc};a.b.g("EmptyNodeSet.prototype.getStart",{Da:a.Yc.prototype.Da});a.Yc.prototype.Y=function(){return 0};a.b.g("EmptyNodeSet.prototype.getCount",{Y:a.Yc.prototype.Y});a.Yc.prototype.getData=
function(){return null};a.b.g("EmptyNodeSet.prototype.getData",{getData:a.Yc.prototype.getData});a.Yc.prototype.getMetadata=function(){return null};a.b.g("EmptyNodeSet.prototype.getMetadata",{getMetadata:a.Yc.prototype.getMetadata});a.ce=function(b,a,c){this.zi=b;this.bx=a;this.ax=this.VM(c)};o_("MergedNodeSet",a.ce,a);a.ce.prototype.VM=function(b){var a,c,e;a=this.zi.Da();for(c=a+this.zi.Y();a<c;a++)if(e=this.zi.getMetadata(a).key,b===e)return a;return c-1};a.ce.prototype.getParent=function(){return this.zi.getParent()};
a.b.g("MergedNodeSet.prototype.getParent",{getParent:a.ce.prototype.getParent});a.ce.prototype.Da=function(){return this.zi.Da()};a.b.g("MergedNodeSet.prototype.getStart",{Da:a.ce.prototype.Da});a.ce.prototype.Y=function(){return this.zi.Y()+this.bx.Y()};a.b.g("MergedNodeSet.prototype.getCount",{Y:a.ce.prototype.Y});a.ce.prototype.getData=function(b){b=this.LB(b);return b.set.getData(b.index)};a.b.g("MergedNodeSet.prototype.getData",{getData:a.ce.prototype.getData});a.ce.prototype.getMetadata=function(b){b=
this.LB(b);return b.set.getMetadata(b.index)};a.b.g("MergedNodeSet.prototype.getMetadata",{getMetadata:a.ce.prototype.getMetadata});a.ce.prototype.LB=function(b){if(b<=this.ax)return{set:this.zi,index:b};var a=this.bx.Y();return b>this.ax+a?{set:this.zi,index:b-a}:{set:this.bx,index:b-(this.ax+1)}};a.cd=function(b,a,c){this.bb=b;this.Gf=a;this.ol=c};o_("NodeSetWrapper",a.cd,a);a.cd.prototype.getParent=function(){return this.bb.getParent()};a.b.g("NodeSetWrapper.prototype.getParent",{getParent:a.cd.prototype.getParent});
a.cd.prototype.Da=function(){return null!=this.ol?this.ol.start:this.bb.Da()};a.b.g("NodeSetWrapper.prototype.getStart",{Da:a.cd.prototype.Da});a.cd.prototype.Y=function(){var b,a;b=this.bb.Da();a=this.bb.Y();null!=this.ol&&(this.ol.start>b?a=Math.min(0,a-(this.ol.start-b)):this.ol.start<b&&(a=0));return a};a.b.g("NodeSetWrapper.prototype.getCount",{Y:a.cd.prototype.Y});a.cd.prototype.getData=function(b){return this.bb.getData(b)};a.b.g("NodeSetWrapper.prototype.getData",{getData:a.cd.prototype.getData});
a.cd.prototype.getMetadata=function(b){var a;a=this.bb.getMetadata(b);a.index=b;a.parentKey=this.getParent();this.Gf.call(null,a.key,a);return a};a.b.g("NodeSetWrapper.prototype.getMetadata",{getMetadata:a.cd.prototype.getMetadata});a.cd.prototype.Ed=function(b){return this.bb.Ed&&(b=this.bb.Ed(b),null!=b)?new a.cd(b,this.Gf):null};a.b.g("NodeSetWrapper.prototype.getChildNodeSet",{Ed:a.cd.prototype.Ed});a.bd=function(b,d,c,e){a.i.$b(b,null);a.i.$b(d,null);this.nU=e;this.ur=b;this.$w=d;this.Gd=c};
o_("JsonNodeSet",a.bd,a);a.bd.prototype.getParent=function(){return this.nU};a.b.g("JsonNodeSet.prototype.getParent",{getParent:a.bd.prototype.getParent});a.bd.prototype.Da=function(){return this.ur};a.b.g("JsonNodeSet.prototype.getStart",{Da:a.bd.prototype.Da});a.bd.prototype.Y=function(){return Math.max(0,this.$w-this.ur)};a.b.g("JsonNodeSet.prototype.getCount",{Y:a.bd.prototype.Y});a.bd.prototype.getData=function(b){a.i.assert(b<=this.$w&&b>=this.ur);return this.Gd[b]?this.Gd[b].attr:null};a.b.g("JsonNodeSet.prototype.getData",
{getData:a.bd.prototype.getData});a.bd.prototype.getMetadata=function(b){var d=[];a.i.assert(b<=this.$w&&b>=this.ur);d.key=this.Gd[b].id?this.Gd[b].id:this.Gd[b].attr.id;d.leaf=this.Gd[b].Yw;d.depth=this.Gd[b].depth;null==d.leaf&&(d.leaf=this.Gd[b].children&&0<this.Gd[b].children.length?!1:!0);return d};a.b.g("JsonNodeSet.prototype.getMetadata",{getMetadata:a.bd.prototype.getMetadata});a.bd.prototype.$g=function(b,a){var c;a++;b.depth=a;if(b.children&&0!=b.children.length)for(c=0;c<b.children.length;c++)this.$g(b.children[c],
a)};a.bd.prototype.Ed=function(b){var d,c,e;c=this.Gd[b].depth;d=this.Gd[b].children;if(0==d.length)return null;b=this.Gd[b].id?this.Gd[b].id:this.Gd[b].attr.id;for(e=0;e<d.length;e++)this.$g(d[e],c);return new a.bd(0,d.length,d,b)};a.b.g("JsonNodeSet.prototype.getChildNodeSet",{Ed:a.bd.prototype.Ed});a.Zc=function(b,a){this.bb=b;this.Jc=a};o_("FlattenedNodeSet",a.Zc,a);a.Zc.prototype.getParent=function(){return this.bb.getParent()};a.b.g("FlattenedNodeSet.prototype.getParent",{getParent:a.Zc.prototype.getParent});
a.Zc.prototype.Da=function(){return void 0!=this.Jc?this.Jc:this.bb.Da()};a.b.g("FlattenedNodeSet.prototype.getStart",{Da:a.Zc.prototype.Da});a.Zc.prototype.Y=function(){void 0===this.sr&&(this.sr=this.sB(this.bb,0),void 0!=this.Jc&&(this.sr-=this.Jc));return this.sr};a.b.g("FlattenedNodeSet.prototype.getCount",{Y:a.Zc.prototype.Y});a.Zc.prototype.sB=function(b,a){var c,e,g,f;c=b.Da();e=b.Y();a+=e;if(b.Ed)for(g=0;g<e;g++)f=b.Ed(g+c),null!=f&&(a=this.sB(f,a));return a};a.Zc.prototype.getData=function(b){return this.Mt(this.bb,
b,{index:this.bb.Da()},this.Ka)};a.b.g("FlattenedNodeSet.prototype.getData",{getData:a.Zc.prototype.getData});a.Zc.prototype.getMetadata=function(b){return this.Mt(this.bb,b,{index:this.bb.Da()},this.FN)};a.b.g("FlattenedNodeSet.prototype.getMetadata",{getMetadata:a.Zc.prototype.getMetadata});a.Zc.prototype.FN=function(b,a){return b.getMetadata(a)};a.Zc.prototype.Ka=function(b,a){return b.getData(a)};a.Zc.prototype.Mt=function(b,a,c,e){var g,f,k,l;g=b.Da();f=b.Y();for(k=0;k<f;k++){l=c.index;if(l===
a)return e.call(this,b,k+g);c.index=l+1;if(b.Ed&&(l=b.Ed(k+g),null!=l&&(l=this.Mt(l,a,c,e),null!=l)))return l}return null};a.fc=function(b){a.fc.t.constructor.call(this,b)};o_("DataGridDataSource",a.fc,a);a.b.oa(a.fc,a.Mc,"oj.DataGridDataSource");a.fc.prototype.Y=function(){return 0};a.b.g("DataGridDataSource.prototype.getCount",{Y:a.fc.prototype.Y});a.fc.prototype.ef=function(){return"exact"};a.b.g("DataGridDataSource.prototype.getCountPrecision",{ef:a.fc.prototype.ef});a.fc.prototype.Td=function(){a.i.fa()};
a.b.g("DataGridDataSource.prototype.fetchHeaders",{Td:a.fc.prototype.Td});a.fc.prototype.Rd=function(){a.i.fa()};a.b.g("DataGridDataSource.prototype.fetchCells",{Rd:a.fc.prototype.Rd});a.fc.prototype.keys=function(){a.i.fa();return null};a.b.g("DataGridDataSource.prototype.keys",{keys:a.fc.prototype.keys});a.fc.prototype.Wd=function(){a.i.fa();return null};a.b.g("DataGridDataSource.prototype.indexes",{Wd:a.fc.prototype.Wd});a.fc.prototype.sort=function(){a.i.fa()};a.b.g("DataGridDataSource.prototype.sort",
{sort:a.fc.prototype.sort});a.fc.prototype.getCapability=function(){return null};a.b.g("DataGridDataSource.prototype.getCapability",{getCapability:a.fc.prototype.getCapability})});
//# sourceMappingURL=oj-modular.map