/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define("ojs/ojcore jquery ojs/internal-deps/datagrid/DvtDataGrid ojs/ojcomponentcore ojs/ojdatacollection-common ojs/ojinputnumber ojs/ojmenu ojs/ojdialog ojs/ojpagingcontrol".split(" "),function(a,f,b){a.Wa=function(b,c){null!=c&&(this.Fj=c.rowHeader);a.Wa.t.constructor.call(this,b)};o_("ArrayDataGridDataSource",a.Wa,a);a.b.oa(a.Wa,a.fc,"oj.ArrayDataGridDataSource");a.Wa.prototype.Init=function(){this.columns=this.jN(this.data);this.mP();a.Wa.t.Init.call(this)};a.b.g("ArrayDataGridDataSource.prototype.Init",
{Init:a.Wa.prototype.Init});a.Wa.prototype.mP=function(){var b;this.Yd=[];for(b=0;b<this.data.length;b+=1)this.Yd[b]=b.toString()};a.Wa.prototype.jN=function(b){var a,e;if("number"!==typeof b.length||0===b.length)return[];e=[];for(a in b[0])b[0].hasOwnProperty(a)&&(void 0!=this.Fj&&a==this.Fj||e.push(a));return e};a.Wa.prototype.Y=function(b){return"row"===b?this.data.length:"column"===b?this.columns.length:0};a.b.g("ArrayDataGridDataSource.prototype.getCount",{Y:a.Wa.prototype.Y});a.Wa.prototype.sG=
function(b,a){if("row"===b)return void 0!=this.Fj?this.data[a][this.Fj]:0<this.data.length&&this.data[0]instanceof Array?void 0===this.Yd[a]?a.toString():this.Yd[a]:null;if("column"===b)return this.columns[a]};a.Wa.prototype.HT=function(b,a){return"row"===b&&void 0!=this.Fj?{key:a.toString()}:{key:this.sG(b,a)}};a.Wa.prototype.Td=function(b,c,e){var g,f,k;g=b.axis;f=b.start;k=b.count;a.i.assert("row"===g||"column"===g);a.i.assert(f<this.Y(g));a.i.assert(0<k);f=Math.max(0,f);k="column"===g?Math.min(this.columns.length,
f+k):void 0!==this.Fj||0<this.data.length&&this.data[0]instanceof Array?Math.min(this.data.length,f+k):f;g=new a.qe(f,k,g,this);null!=c&&null!=c.success&&(null==e&&(e={}),c.success.call(e.success,g,b))};a.b.g("ArrayDataGridDataSource.prototype.fetchHeaders",{Td:a.Wa.prototype.Td});a.Wa.prototype.CT=function(b,a){return this.data[b][this.columns[a]]};a.Wa.prototype.DT=function(b,a){return{keys:{row:this.Yd[b],column:this.columns[a]}}};a.Wa.prototype.Rd=function(b,c,e){var g,f,k,l,n,m;for(g=0;g<b.length;g+=
1)f=b[g],a.i.assert("row"===f.axis||"column"===f.axis),a.i.assert(f.start<this.Y(f.axis)),a.i.assert(0<f.count),"row"===f.axis?(k=f.start,l=Math.min(this.data.length,k+f.count)):"column"===f.axis&&(n=f.start,m=Math.min(this.columns.length,n+f.count));void 0===l||void 0===m?null!=c&&null!=c.error&&(null==e&&(e={}),c.error.call(e.error)):(g=new a.ae(k,l,n,m,this),null!=c&&null!=c.success&&(null==e&&(e={}),c.success.call(e.success,g,b)))};a.b.g("ArrayDataGridDataSource.prototype.fetchCells",{Rd:a.Wa.prototype.Rd});
a.Wa.prototype.keys=function(b){return{row:this.Yd[b.row],column:this.columns[b.column]}};a.b.g("ArrayDataGridDataSource.prototype.keys",{keys:a.Wa.prototype.keys});a.Wa.prototype.Wd=function(b){var a=b.column;return{row:this.Yd.indexOf(b.row),column:this.columns.indexOf(a)}};a.b.g("ArrayDataGridDataSource.prototype.indexes",{Wd:a.Wa.prototype.Wd});a.Wa.prototype.sort=function(b,a,e){var g=[],f=[],k=[],l=[],n=[],m,q;m=b.axis;q=b.key;b=b.direction;null!=a&&null==e&&(e={});if("column"===m){q=this.columns.indexOf(q);
for(m=0;m<this.data.length;m+=1)g[m]=this.data[m][this.columns[q]],f[m]=m;f.sort(this.fD(g,b));for(m=0;m<this.data.length;m+=1)k[m]=this.data[f[m]],n[m]=this.Yd[f[m]];this.data=k;this.Yd=n;null!=a&&null!=a.success&&a.success.call(e.success)}else if("row"===m){q=this.Yd.indexOf(q);for(m=0;m<this.columns.length;m+=1)g[m]=this.data[q][this.columns[m]],f[m]=m;f.sort(this.fD(g,b));for(m=0;m<this.columns.length;m+=1)l[m]=this.columns[f[m]];this.columns=l;null!==a&&null!=a.success&&a.success.call(e.success)}else null!==
a&&null!=a.error&&a.error.call(e.error,"Invalid axis value")};a.b.g("ArrayDataGridDataSource.prototype.sort",{sort:a.Wa.prototype.sort});a.Wa.prototype.getCapability=function(b){return"sort"===b?"column":"move"===b?"row":null};a.b.g("ArrayDataGridDataSource.prototype.getCapability",{getCapability:a.Wa.prototype.getCapability});a.Wa.prototype.fD=function(b,a){if("ascending"===a)return function(a,c){var f,k;a=b[a];c=b[c];f=isNaN(a);k=isNaN(c);a instanceof Date&&(a=a.toISOString(),f=!0);c instanceof
Date&&(c=c.toISOString(),k=!0);return f&&k?a<c?-1:a===c?0:1:f?1:k?-1:a-c};if("descending"===a)return function(a,c){var f,k;a=b[a];c=b[c];f=isNaN(a);k=isNaN(c);a instanceof Date&&(a=a.toISOString(),f=!0);c instanceof Date&&(c=c.toISOString(),k=!0);return f&&k?a>c?-1:a===c?0:1:f?-1:k?1:c-a}};a.Wa.prototype.move=function(b,a){var e,g;e=this.Yd.indexOf(b);this.Yd.splice(e,1);e=this.data.splice(e,1)[0];g={source:this,operation:"delete",keys:{row:b,column:null}};this.handleEvent("change",g);null===a?(this.Yd.push(b),
this.data.push(e)):(g=this.Yd.indexOf(a),this.Yd.splice(g,0,b),this.data.splice(g,0,e));g={source:this,operation:"insert",keys:{row:b,column:null}};this.handleEvent("change",g)};a.b.g("ArrayDataGridDataSource.prototype.move",{move:a.Wa.prototype.move});a.Wa.prototype.vG=function(){return this.Fj};a.b.g("ArrayDataGridDataSource.prototype.getRowHeaderKey",{vG:a.Wa.prototype.vG});a.Wa.prototype.pi=function(){return this.columns};a.b.g("ArrayDataGridDataSource.prototype.getColumns",{pi:a.Wa.prototype.pi});
a.Wa.prototype.wG=function(){return this.Yd};a.b.g("ArrayDataGridDataSource.prototype.getRowKeys",{wG:a.Wa.prototype.wG});a.Wa.prototype.getData=function(){return this.data};a.b.g("ArrayDataGridDataSource.prototype.getData",{getData:a.Wa.prototype.getData});a.Ne=function(b,c){this.NU=b;this.fV=c;this.La={};this.La.datagrid="oj-datagrid";this.La.cell="oj-datagrid-cell";this.La.banded="oj-datagrid-banded";this.La.row="oj-datagrid-row";this.La.databody="oj-datagrid-databody";this.La.topcorner="oj-datagrid-top-corner";
this.La.bottomcorner="oj-datagrid-bottom-corner";this.La.rowheaderspacer="oj-datagrid-row-header-spacer";this.La.colheaderspacer="oj-datagrid-column-header-spacer";this.La.status="oj-datagrid-status";this.La.emptytext="oj-datagrid-empty-text";this.La.header="oj-datagrid-header";this.La.headercell="oj-datagrid-header-cell";this.La.headercellcontent="oj-datagrid-header-cell-content";this.La.rowheader="oj-datagrid-row-header";this.La.colheader="oj-datagrid-column-header";this.La.colheadercell="oj-datagrid-column-header-cell";
this.La.rowheadercell="oj-datagrid-row-header-cell";this.La["scroller-mobile"]="oj-datagrid-scroller-touch";this.La.scroller="oj-datagrid-scroller";this.La.scrollers="oj-datagrid-scrollers";this.La.focus="oj-focus";this.La.hover="oj-hover";this.La.active="oj-active";this.La.selected="oj-selected";this.La.disabled="oj-disabled";this.La.enabled="oj-enabled";this.La["default"]="oj-default";this.La.sortcontainer="oj-datagrid-sort-icon-container";this.La.sortascending="oj-datagrid-sort-ascending-icon";
this.La.sortdescending="oj-datagrid-sort-descending-icon";this.La.icon="oj-component-icon";this.La.clickableicon="oj-clickable-icon-nocontext";this.La.info="oj-helper-hidden-accessible";this.La.rowexpander="oj-rowexpander";this.La.cut="oj-datagrid-cut";this.La.move="oj-datagrid-move";this.La.droptarget="oj-datagrid-drop-target";this.La.selectaffordancetop="oj-datagrid-touch-selection-affordance-top";this.La.selectaffordancebottom="oj-datagrid-touch-selection-affordance-bottom";this.La.toucharea="oj-datagrid-touch-area";
this.Ce={};this.Ce.sortCol="oj-datagrid-sortCol";this.Ce.sortColAsc="oj-datagrid-sortColAsc";this.Ce.sortColDsc="oj-datagrid-sortColDsc";this.Ce.sortRow="oj-datagrid-sortRow";this.Ce.sortRowAsc="oj-datagrid-sortRowAsc";this.Ce.sortRowDsc="oj-datagrid-sortRowDsc";this.Ce.resize="oj-datagrid-resize";this.Ce.resizeWidth="oj-datagrid-resizeWidth";this.Ce.resizeHeight="oj-datagrid-resizeHeight";this.Ce.cut="oj-datagrid-cut";this.Ce.paste="oj-datagrid-paste";this.attributes={};this.attributes.key="data-oj-key";
this.attributes.resizable="data-oj-resizable";this.attributes.sortable="data-oj-sortable";this.attributes.sortDir="data-oj-sortdir";this.attributes.expander="data-oj-expander";this.attributes.expanderIndex="data-oj-expander-index";this.attributes.container=a.Components.So};o_("DataGridResources",a.Ne,a);a.Ne.prototype.ZG=function(){return"rtl"===this.NU?!0:!1};a.b.g("DataGridResources.prototype.isRTLMode",{ZG:a.Ne.prototype.ZG});a.Ne.prototype.FG=function(b,a){return this.fV(b,a)};a.b.g("DataGridResources.prototype.getTranslatedText",
{FG:a.Ne.prototype.FG});a.Ne.prototype.Gw=function(b){return null!=b?this.La[b]:null};a.b.g("DataGridResources.prototype.getMappedStyle",{Gw:a.Ne.prototype.Gw});a.Ne.prototype.jr=function(b){return null!=b?this.Ce[b]:null};a.b.g("DataGridResources.prototype.getMappedCommand",{jr:a.Ne.prototype.jr});a.Ne.prototype.Fw=function(b){return null!=b?this.attributes[b]:null};a.b.g("DataGridResources.prototype.getMappedAttribute",{Fw:a.Ne.prototype.Fw});a.Fa("oj.ojDataGrid",f.oj.baseComponent,{widgetEventPrefix:"oj",
options:{bandingInterval:{row:0,column:0},data:null,emptyText:null,gridlines:{horizontal:"visible",vertical:"visible"},scrollPosition:null,selectionMode:null,dnd:{wl:{row:"disable"}},header:{row:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null},column:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null}},cell:{className:null,renderer:null,style:null},select:null,resize:null,sort:null},_create:function(){f(this.root).addClass("oj-component");
this._super();this.root=this.element[0];this.me=this.root.getAttribute("id");this.grid=new b;this.mx={data:"all",header:["className","renderer","style","template"]}},_init:function(){var b=this;f(this.root).empty();this._super();this.Ej=new a.Ne(this.uc(),this.XB.bind(b));this.BE();this.uK();null!=this.Bc&&this.grid.SetDataSource(this.Bc);this.grid.SetOptions(this.options);this.grid.SetResources(this.Ej);this.grid.SetCreateContextCallback(this.VP.bind(b));this.grid.addListener("resize",function(a){b._trigger("resize",
a.event,a.ui)});this.grid.addListener("select",function(a){b._trigger("select",a.event,a.ui)});this.grid.addListener("sort",function(a){b._trigger("sort",a.event,a.ui)});this.grid.addListener("keydown",function(a){b._trigger("keydown",a.event,a.ui)});this.grid.addListener("active",function(a){b._trigger("active",a.event,a.ui)});this.grid.render(this.root);this.dn(this.root)},refresh:function(){this._super();f(this.root).empty();this.BE();null!=this.Bc&&this.grid.SetDataSource(this.Bc);this.grid.SetOptions(this.options);
this.grid.SetResources(this.Ej);this.grid.refresh(this.root)},_destroy:function(){this.grid.destroy();f(this.root).empty()},_setOptions:function(b,a){var e;if(this.Bc)this.SR(b,a);else for(e in b)this._setOption(e,b[e],a)},SR:function(b,c){var e,g,f,k,l,n;f=!1;for(g in b)if(g in this.mx)if("header"==g)for(k in b.header){if("column"==k||"row"==k||"cell"==k)for(l in b.header[k]){for(e=0;e<this.mx.header.length;e++)if(l==this.mx.header[e])for(n in this.options.header[k])if(n==l&&b.header[k][l]!=this.options.header[k][l]){f=
!0;break}if(f)break}if(f)break}else if("data"!=g)for(n in this.options)if(n==g&&!a.b.Zq(b[g],this.options[n])){f=!0;break}for(g in b)this._setOption(g,b[g],c);f?this.refresh():this.grid.UpdateOptions(b)},_setOption:function(b,a,e){this._super(b,a,e)},Ck:function(b,a){return"disable"!==this.options.header[b].resizable[a]},EC:function(b){return"disable"!==this.options.header[b].sortable},uK:function(){var b,a,e=null,g=null,h=null,k;b=this;if(null==this.options.contextMenu){if(null!=this.Bc){a=f("\x3cul\x3e");
a.css("display","none").attr("id",this.me+"contextmenu");f(this.root).append(a);if(this.Ck("column","width")||this.Ck("column","height")||this.Ck("row","width")||this.Ck("row","height"))e=this.Mg("resize");k=this.Bc.getCapability("sort");!this.EC("column")||"column"!==k&&"full"!==k||(g=this.Mg("sortCol"));!this.EC("row")||"row"!==k&&"full"!==k||(g=null!=g?g.add(this.Mg("sortRow")):this.Mg("sortRow"));if("enable"===this.options.dnd.reorder)switch(this.Bc.getCapability("move")){case "none":break;default:h=
f(this.fe("cut")).add(f(this.fe("paste")))}a.append(e).append(g).append(h);a.ojMenu();this._setOption("contextMenu","#"+a.attr("id"));a.on("ojbeforeshow",this.Ph.bind(this));a.on("ojselect",this.Qh.bind(this))}}else a=f(this.options.contextMenu),e=a.find("[data-oj-command]"),e.each(function(){var a;0===f(this).children("a").length&&(a=f(this).attr("data-oj-command").split("-"),f(this).replaceWith(b.Mg(a[a.length-1])))}),a.ojMenu("refresh"),a.on("ojbeforeshow",this.Ph.bind(this)),a.on("ojselect",this.Qh.bind(this))},
Mg:function(b){if("resize"===b)return f(this.fe("resize")).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.fe("resizeWidth"))).append(f(this.fe("resizeHeight"))));if("sortCol"===b)return f(this.fe("sortCol")).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.fe("sortColAsc"))).append(f(this.fe("sortColDsc"))));if("sortRow"===b)return f(this.fe("sortRow")).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.fe("sortRowAsc"))).append(f(this.fe("sortRowDsc"))));if(-1!=Object.keys(this.Ej.Ce).indexOf(b))return f(this.fe(b))},
fe:function(b){return"\x3cli data-oj-command\x3d"+this.Sg(b)+"\x3e"+this.Ns(b)+"\x3c/li\x3e"},Ns:function(b){b="label"+b.charAt(0).toUpperCase()+b.slice(1);return'\x3ca href\x3d"#"\x3e'+this.XB(b)+"\x3c/a\x3e"},Lt:function(){return f(this.options.contextMenu).get(0)},XB:function(b,a){return this.C(b,a)},LO:function(){var b=f("#"+this.me+"spinner").ojInputNumber("option","value");f("#"+this.me+"dialog").ojDialog("destroy");f("#"+this.me+"spinner").ojInputNumber("destroy");this.grid.handleContextMenuReturn(this.Df,
this.rg,b);this.Df.target.focus()},bL:function(b,a){var e,g,h,k,l;e=f("#"+this.me+"dialog");h=f("#"+this.me+"spinner");if(0===e.length||0===h.length)e=f("\x3cdiv\x3e"),e.attr("id",this.me+"dialog"),e.attr("title",b),g=f('\x3cdiv class\x3d"oj-dialog-body"\x3e\x3c/div\x3e'),k=f('\x3cdiv class\x3d"oj-dialog-footer"\x3e\x3c/div\x3e'),e.append(g).append(k),h=f('\x3cinput id\x3d"'+this.me+'spinner"/\x3e'),l=f("\x3cbutton\x3e"),g.append(h),k.append(l),f(this.root).append(e),l.ojButton({xa:"ojButton",label:"OK"}),
l.on("click",this.LO.bind(this));h.ojInputNumber({xa:"ojInputNumber",max:1E3,min:20,step:1,value:a});e.ojDialog({initialVisibility:"show",position:{my:"center center",at:"center center",collision:"none",of:f(this.root)}})},Qh:function(b,a){var e;this.rg=a.item.attr("data-oj-command");if(this.rg===this.Sg("sortColAsc")||this.rg===this.Sg("sortColDsc")||this.rg===this.Sg("cut")||this.rg===this.Sg("paste"))this.grid.handleContextMenuReturn(this.Df,this.rg,null);else if(this.rg===this.Sg("resizeWidth")||
this.rg===this.Sg("resizeHeight"))e=this.Dt(f(this.Df.target),"oj-datagrid-headercell"),e=null!=e?this.rg===this.Sg("resizeWidth")?e.outerWidth():e.outerHeight():this.rg===this.Sg("resizeWidth")?f(this.Df.target).outerWidth():f(this.Df.target).outerHeight(),this.bL(a.item.text(),e)},Ph:function(b){var a;a=f(this.Lt());this.Df=b.originalEvent.originalEvent;"keydown"===this.Df.type?a.ojMenu("option","menuPosition",{my:"left top",at:"left bottom",of:this.Df.target}):a.ojMenu("option","menuPosition",
{my:"left top",at:"left bottom"});b=this.Dt(f(this.Df.target).eq(0),this.ok("cell"));null!=b?b=this.eN(b):(b=this.Dt(f(this.Df.target).eq(0),this.ok("headercell")),b=this.wN(b));this.QP(b)},vK:function(b){var a;a=f(this.Lt());a.find("[data-oj-command\x3d"+b+"]").hasClass("oj-disabled")||a.find("[data-oj-command\x3d"+b+"]").addClass("oj-disabled")},YQ:function(b){f(this.Lt()).find("[data-oj-command\x3d"+b+"]").removeClass("oj-disabled")},QP:function(b){var a,e;for(a in b)b.hasOwnProperty(a)&&(e=this.Ej.jr(a),
"disable"===b[a]?this.vK(e):this.YQ(e))},Dt:function(b,a){var e;if(b.hasClass(a))return b;e=b.parents("."+a);return 0!=e.length?e.eq(0):null},TM:function(b){var a;a=b.parent();b=a.children().index(b);return{rowIndex:a.parent().children().index(a)-1,columnIndex:b}},UM:function(b){var a;a=this.TN().children().eq(0).children().eq(b.rowIndex+1);b=this.iN().children().eq(0).children().eq(b.columnIndex);return{rowHeader:a,columnHeader:b}},HV:function(){return f(this.root)},iN:function(){return f("#"+this.me+
"\\:columnHeader")},TN:function(){return f("#"+this.me+"\\:rowHeader")},FV:function(){return f("#"+this.me+"\\:databody")},lN:function(){return f("#"+this.me+"\\:databody ."+this.ok("row"))},eN:function(b){var a,e;b=this.TM(b);a=this.UM(b);b={JU:"disable",IU:"disable",YU:"disable",XU:"disable"};e=a.rowHeader;a=a.columnHeader;0!==a.length&&("true"===a.attr(this.Lh("resizable"))&&(b.resizeWidth="enable"),"true"===a.attr(this.Lh("sortable"))&&(b.sortCol="enable"));0!==e.length&&("true"===e.attr(this.Lh("resizable"))&&
(b.resizeHeight="enable"),"true"===e.attr(this.Lh("sortable"))&&(b.sortRow="enable"));return b},wN:function(b){var a;a={JU:"disable",IU:"disable",YU:"disable",XU:"disable"};null!==b&&(b.hasClass(this.ok("colheadercell"))?("true"===b.attr(this.Lh("resizable"))&&(a.resizeWidth="enable"),a.resizeHeight=this.Ck("column","height")?"enable":"disable","true"===b.attr(this.Lh("sortable"))&&(a.sortCol="enable")):("true"===b.attr(this.Lh("resizable"))&&(a.resizeHeight="enable"),a.resizeWidth=this.Ck("row",
"width")?"enable":"disable","true"===b.attr(this.Lh("sortable"))&&(a.sortRow="enable")));return a},BE:function(){this.Bc=null!=this.options.data?this.options.data:null},VP:function(b){b.component=this},vE:function(b){this.grid.SetAccessibleContext(b)},dn:function(b){if(b&&!this.Mm){var c=this;a.Aa.bh(b,function(b,a){0<b&&0<a&&c.grid.HandleResize(b,a)});this.Mm=!0}},selection:function(b){if(void 0===b)return this.grid.GetSelection();this.grid.SetSelection(b)},getNodeBySubId:function(b){var a,e;if(null==
b)return this.element?this.element[0]:null;a=b.subId;switch(a){case "oj-datagrid-cell":e=this.ok("cell");break;case "oj-datagrid-header":e=this.ok("headercell");break;case "oj-datagrid-sort-ascending":e="oj-datagrid-sort-ascending-icon";break;case "oj-datagrid-sort-descending":e="oj-datagrid-sort-descending-icon";break;default:return null}if("oj-datagrid-cell"===a)return e=b.rowIndex,b=b.columnIndex,this.lN().eq(e).children().eq(b);a=b.axis;b=b.index;return"column"===a?f("#"+this.me+"\\:columnHeader ."+
e).eq(b):"row"===a?f("#"+this.me+"\\:rowHeader ."+e).eq(b):null},ok:function(b){return this.Ej.Gw(b)},Lh:function(b){return this.Ej.Fw(b)},Sg:function(b){return this.Ej.jr(b)}});a.Oe=function(b,c,e,g,f,k){a.i.$b(b,null);a.i.$b(c,null);a.i.$b(e,null);a.i.$b(g,null);a.i.un(k);this.If=b;this.Aj=c;this.kf=e;this.mh=g;this.bb=f;this.Ic=k};o_("FlattenedTreeCellSet",a.Oe,a);a.Oe.prototype.getData=function(b){var c;c=this.KB(b);if(null==c)return null;b=c[0];c=c[1];a.i.assert(b<this.bb.Da()+this.bb.Y()&&c<
this.Ic.length);c=this.Ic[c];b=this.bb.getData(b);return null!=b?b.get?b.get(c):b[c]:null};a.b.g("FlattenedTreeCellSet.prototype.getData",{getData:a.Oe.prototype.getData});a.Oe.prototype.getMetadata=function(b){var c;c=this.KB(b);if(null==c)return null;b=c[0];c=c[1];a.i.assert(b<this.bb.Da()+this.bb.Y()&&c<this.Ic.length);c=this.Ic[c];b=this.bb.getMetadata(b);b.keys={row:b.key,column:c};return b};a.b.g("FlattenedTreeCellSet.prototype.getMetadata",{getMetadata:a.Oe.prototype.getMetadata});a.Oe.prototype.KB=
function(b){var c;a.i.Pd(b);if(null==this.bb||0==this.bb.length)return null;c=b.row-this.If+this.bb.Da();b=b.column;a.i.$b(c,null);a.i.$b(b,null);a.i.assert(0<=c&&0<=b);return[c,b]};a.Oe.prototype.Da=function(b){return"row"===b?this.If:"column"===b?this.kf:0};a.b.g("FlattenedTreeCellSet.prototype.getStart",{Da:a.Oe.prototype.Da});a.Oe.prototype.Y=function(b){return"row"===b?Math.min(this.Aj-this.If,this.bb.Y()):"column"===b?this.mh-this.kf:0};a.b.g("FlattenedTreeCellSet.prototype.getCount",{Y:a.Oe.prototype.Y});
a.Ag=function(b,c,e,g,f){a.i.$b(b,null);a.i.$b(c,null);a.i.un(e);this.Jc=b;this.Hf=c;this.tr=e;this.bb=g;this.jf=f};o_("FlattenedTreeHeaderSet",a.Ag,a);a.Ag.prototype.getData=function(b){a.i.assert(b<=this.Hf&&b>=this.Jc);return null!=this.jf&&null!=this.bb?(b=this.bb.getData(b),null!=b?b.get(this.jf):null):this.tr[b]};a.b.g("FlattenedTreeHeaderSet.prototype.getData",{getData:a.Ag.prototype.getData});a.Ag.prototype.getMetadata=function(b){return null!=this.jf&&null!=this.bb?this.bb.getMetadata(b):
{key:this.getData(b)}};a.b.g("FlattenedTreeHeaderSet.prototype.getMetadata",{getMetadata:a.Ag.prototype.getMetadata});a.Ag.prototype.Y=function(){return null!=this.jf&&null!=this.bb?Math.min(this.bb.Y(),this.Hf-this.Jc):Math.max(0,this.Hf-this.Jc)};a.b.g("FlattenedTreeHeaderSet.prototype.getCount",{Y:a.Ag.prototype.Y});a.ae=function(b,c,e,g,f){a.i.$b(b,null);a.i.$b(c,null);a.i.$b(e,null);a.i.$b(g,null);this.If=b;this.Aj=c;this.kf=e;this.mh=g;this.Gf=f};o_("ArrayCellSet",a.ae,a);a.ae.prototype.getData=
function(b){return this.Gf.CT(b.row,b.column)};a.b.g("ArrayCellSet.prototype.getData",{getData:a.ae.prototype.getData});a.ae.prototype.getMetadata=function(b){return this.Gf.DT(b.row,b.column)};a.b.g("ArrayCellSet.prototype.getMetadata",{getMetadata:a.ae.prototype.getMetadata});a.ae.prototype.Da=function(b){return"row"==b?this.If:"column"==b?this.kf:-1};a.b.g("ArrayCellSet.prototype.getStart",{Da:a.ae.prototype.Da});a.ae.prototype.Y=function(b){return"row"===b?Math.max(0,this.Aj-this.If):"column"===
b?Math.max(0,this.mh-this.kf):0};a.b.g("ArrayCellSet.prototype.getCount",{Y:a.ae.prototype.Y});a.ae.prototype.In=function(){return this.If};a.b.g("ArrayCellSet.prototype.getStartRow",{In:a.ae.prototype.In});a.ae.prototype.Hn=function(){return this.kf};a.b.g("ArrayCellSet.prototype.getStartColumn",{Hn:a.ae.prototype.Hn});a.Ga=function(b,c){a.Ga.t.constructor.call(this,b,c)};o_("FlattenedTreeDataGridDataSource",a.Ga,a);a.b.oa(a.Ga,a.ia,"oj.FlattenedTreeDataGridDataSource");a.Ga.prototype.Init=function(){a.Ga.t.Init.call(this);
this.Ic=a.Ga.t.lr.call(this,"columns");this.jf=a.Ga.t.lr.call(this,"rowHeader")};a.b.g("FlattenedTreeDataGridDataSource.prototype.Init",{Init:a.Ga.prototype.Init});a.Ga.prototype.ef=function(b){return"row"===b?"estimate":"actual"};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCountPrecision",{ef:a.Ga.prototype.ef});a.Ga.prototype.Y=function(b){return"row"===b?-1:"column"===b?this.Ic.length:0};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCount",{Y:a.Ga.prototype.Y});a.Ga.prototype.Td=
function(b,c,e){var g,f;g=b.axis;if("column"===g)f=new a.Ag(b.start,b.start+b.count,this.Ic);else if("row"===g){if(null!=this.jf){this.qg={range:b,callbacks:c,callbackObjects:e};return}f=new a.qe(b.start,b.start,g,null)}null!=f&&null!=c&&null!=c.success&&(null==e&&(e={}),c.success.call(e.success,f,b))};a.b.g("FlattenedTreeDataGridDataSource.prototype.fetchHeaders",{Td:a.Ga.prototype.Td});a.Ga.prototype.Rd=function(b,c,e){var g,f,k,l;for(g=0;g<b.length;g++)if(f=b[g],"row"==f.axis){k=f.start;l=f.count;
break}a.Ga.t.$F.call(this,{start:k,count:l},{success:function(a){this.Yp(a,b,c,e,0)}.bind(this),error:function(b){this.tO(b,{start:k,count:l},c,e)}.bind(this)})};a.b.g("FlattenedTreeDataGridDataSource.prototype.fetchCells",{Rd:a.Ga.prototype.Rd});a.Ga.prototype.keys=function(b){var c;c=b.row;b=b.column;return c>a.Ga.t.pG.call(this).end||b>this.Ic.length?null:{row:a.Ga.t.getKey.call(this,c),column:this.Ic[b]}};a.b.g("FlattenedTreeDataGridDataSource.prototype.keys",{keys:a.Ga.prototype.keys});a.Ga.prototype.Wd=
function(b){var c,e,g;c=b.row;b=b.column;c=a.Ga.t.gl.call(this,c);for(g=0;g<this.Ic.length;g++)if(this.Ic[g]===b){e=g;break}return 0<=c&&0<=e?{row:c,column:e}:null};a.b.g("FlattenedTreeDataGridDataSource.prototype.indexes",{Wd:a.Ga.prototype.Wd});a.Ga.prototype.sort=function(b,c,e){return a.Ga.t.getWrappedDataSource.call(this).sort(b,{success:function(){this.NO(c,e)}.bind(this),error:c.error})};a.b.g("FlattenedTreeDataGridDataSource.prototype.sort",{sort:a.Ga.prototype.sort});a.Ga.prototype.NO=function(b,
a){this.refresh();b.success&&(null==a&&(a={}),b.success.call(a.success))};a.Ga.prototype.move=function(b,c,e,g){a.Ga.t.getWrappedDataSource.call(this).move(b,c,e,g)};a.b.g("FlattenedTreeDataGridDataSource.prototype.move",{move:a.Ga.prototype.move});a.Ga.prototype.getCapability=function(b){return"default"===a.Ga.t.getWrappedDataSource.call(this).getCapability(b)?"column":"none"};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCapability",{getCapability:a.Ga.prototype.getCapability});a.Ga.prototype.Ln=
function(b,c){a.Ga.t.Ln.call(this,b,c)};a.Ga.prototype.Yp=function(b,c,e,g){var f,k,l,n,m,q;for(f=0;f<c.length;f++)k=c[f],"row"==k.axis?(l=k.start,n=k.count):"column"==k.axis&&(m=k.start,q=k.count);this.qg&&(f=this.qg.range,f.start==l&&f.count==n&&this.MO(b,f,this.qg.callbacks,this.qg.callbackObjects),this.qg=null);b=new a.Oe(l,l+n,m,m+q,b,this.Ic);e.success&&(null==g&&(g={}),e.success.call(g.success,b,c))};a.Ga.prototype.tO=function(b,a,e,g){var f;this.qg&&(f=this.qg.range,f.start==a.start&&f.count==
a.count&&(a=this.qg.callbacks,f=this.qg.callbackObjects,a.error&&(null==f&&(f={}),a.error.call(f.error,b))),this.qg=null);e.error&&(null==g&&(g={}),e.success.call(g.error,b))};a.Ga.prototype.MO=function(b,c,e,g){b=new a.Ag(c.start,c.start+c.count,this.Ic,b,this.jf);e.success&&(null==g&&(g={}),e.success.call(g.success,b,c))};a.Ga.prototype.qr=function(b,c,e){b=new a.Oe(b,b+e.Y(),0,this.Ic.length,e,this.Ic);e={source:this,operation:"insert"};e.result=b;e.keys={row:c};a.Ga.t.handleEvent.call(this,"change",
e)};a.Ga.prototype.Er=function(b){var c,e;c=[];for(e=0;e<b.length;e++)c.push({row:b[e].key});b={source:this,operation:"delete"};b.keys=c;a.Ga.t.handleEvent.call(this,"change",b)};a.Ga.prototype.Mw=function(b,c){c.success.call(null,new a.Yc(null,b.start))};a.Ma=function(b){if(!(b instanceof a.ga))throw new a.N("Not a datagridatasource","Not a datagridatasource",a.N.kb.ERROR);this.Oa=b;this.O=0;this.Init()};o_("PagingDataGridDataSource",a.Ma,a);a.b.oa(a.Ma,a.jb,"oj.PagingDataGridDataSource");a.Ma.prototype.Init=
function(){a.Ma.t.Init.call(this)};a.b.g("PagingDataGridDataSource.prototype.Init",{Init:a.Ma.prototype.Init});a.Ma.prototype.fetch=function(b){this.O=b.startIndex;this.Oa.setPageSize(this.Oc);this.Oa.fetch(b)};a.b.g("PagingDataGridDataSource.prototype.fetch",{fetch:a.Ma.prototype.fetch});a.Ma.prototype.hasMore=function(){return this.Oa.hasMore()};a.b.g("PagingDataGridDataSource.prototype.hasMore",{hasMore:a.Ma.prototype.hasMore});a.Ma.prototype.next=function(){this.Oa.totalSize()>this.O&&(this.Oc+=
this.lb,this.Oa.setPageSize(this.Oc),this.fetch({startIndex:this.O}))};a.b.g("PagingDataGridDataSource.prototype.next",{next:a.Ma.prototype.next});a.Ma.prototype.previous=function(){if(0!=this.O||-1!=this.O)this.O-=this.lb,this.O=0>this.O?0:this.O,this.Oc+=this.lb,this.Oa.setPageSize(this.Oc),this.fetch({startIndex:this.O})};a.b.g("PagingDataGridDataSource.prototype.previous",{previous:a.Ma.prototype.previous});a.Ma.prototype.setPageSize=function(b){this.lb=b;this.Oc=this.O+b;this.Oa.setPageSize(this.Oc)};
a.Ma.prototype.startIndex=function(){return this.O};a.b.g("PagingDataGridDataSource.prototype.startIndex",{startIndex:a.Ma.prototype.startIndex});a.Ma.prototype.Y=function(b){return this.Oa.Y(b)};a.b.g("PagingDataGridDataSource.prototype.getCount",{Y:a.Ma.prototype.Y});a.Ma.prototype.ef=function(b){return this.Oa.ef(b)};a.b.g("PagingDataGridDataSource.prototype.getCountPrecision",{ef:a.Ma.prototype.ef});a.Ma.prototype.Td=function(b,a,e){return this.Oa.Td(b,a,e)};a.b.g("PagingDataGridDataSource.prototype.fetchHeaders",
{Td:a.Ma.prototype.Td});a.Ma.prototype.Rd=function(b,a,e){return this.Oa.Rd(b,a,e)};a.b.g("PagingDataGridDataSource.prototype.fetchCells",{Rd:a.Ma.prototype.Rd});a.Ma.prototype.keys=function(b){return this.Oa.keys(b)};a.b.g("PagingDataGridDataSource.prototype.keys",{keys:a.Ma.prototype.keys});a.Ma.prototype.Wd=function(b){return this.Oa.Wd(b)};a.b.g("PagingDataGridDataSource.prototype.indexes",{Wd:a.Ma.prototype.Wd});a.Ma.prototype.on=function(b,a){return this.Oa.on(b,a)};a.b.g("PagingDataGridDataSource.prototype.on",
{on:a.Ma.prototype.on});a.Ma.prototype.off=function(b,a){return this.Oa.off(b,a)};a.b.g("PagingDataGridDataSource.prototype.off",{off:a.Ma.prototype.off});a.Ma.prototype.getCapability=function(b){return this.Oa.getCapability(b)};a.b.g("PagingDataGridDataSource.prototype.getCapability",{getCapability:a.Ma.prototype.getCapability});a.Ma.prototype.size=function(){return this.Oa.size()};a.b.g("PagingDataGridDataSource.prototype.size",{size:a.Ma.prototype.size});a.Ma.prototype.sort=function(b,a,e){this.Oa.sort(b,
a,e)};a.b.g("PagingDataGridDataSource.prototype.sort",{sort:a.Ma.prototype.sort});a.Ma.prototype.totalSize=function(){return this.Oa.totalSize()};a.b.g("PagingDataGridDataSource.prototype.totalSize",{totalSize:a.Ma.prototype.totalSize});a.Ma.prototype.move=function(b,a){return this.Oa.move(b,a)};a.qe=function(b,c,e,g){a.i.$b(b,null);a.i.$b(c,null);this.Jc=b;this.Hf=c;this.dH=e;this.Gf=g};o_("ArrayHeaderSet",a.qe,a);a.qe.prototype.getData=function(b){if(null==this.Gf)return null;a.i.assert(b<=this.Hf&&
b>=this.Jc);return this.Gf.sG(this.dH,b)};a.b.g("ArrayHeaderSet.prototype.getData",{getData:a.qe.prototype.getData});a.qe.prototype.getMetadata=function(b){if(null==this.Gf)return null;a.i.assert(b<=this.Hf&&b>=this.Jc);return this.Gf.HT(this.dH,b)};a.b.g("ArrayHeaderSet.prototype.getMetadata",{getMetadata:a.qe.prototype.getMetadata});a.qe.prototype.Y=function(){return null==this.Gf?0:Math.max(0,this.Hf-this.Jc)};a.b.g("ArrayHeaderSet.prototype.getCount",{Y:a.qe.prototype.Y});a.qe.prototype.Da=function(){return this.Jc};
a.b.g("ArrayHeaderSet.prototype.getStart",{Da:a.qe.prototype.Da})});
//# sourceMappingURL=oj-modular.map