/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojvalidation","ojs/ojpopup"],function(a,f){a.cb=function(b){this.Init(b)};a.Sa.nx(a.Sa.ed.Ao,a.cb);a.b.oa(a.cb,a.Vb,"oj.PopupMessagingStrategy");a.cb.Ol={ojRadioset:{position:"launcher",fl:{open:"focusin mouseover",close:"mouseout"}},ojCheckboxset:{position:"launcher",fl:{open:"focusin mouseover",close:"mouseout"}},"default":{fl:{open:"focusin"}}};a.cb.II="oj-component-icon oj-message-status-icon ";a.cb.prototype.Init=function(b){a.cb.t.Init.call(this,
b)};a.cb.prototype.hi=function(b,d,c){a.cb.t.hi.call(this,b,d,c);this.eP();this.update(c)};a.cb.prototype.update=function(b){a.cb.t.update.call(this,b)};a.cb.prototype.ng=function(b){var d=a.cb.Ol[this.ta.widgetName],d=d?d.fl:a.cb.Ol["default"].fl;d.open&&this.gb.off(d.open,this.kD);d.close&&this.gb.off(d.close,this.jA);this.qM();a.cb.t.ng.call(this,b)};a.cb.prototype.getNodeBySubId=function(b,a){return this.mq()?"oj-messaging-popup-content"===b?this.Kd[0]:"oj-messaging-popup-message"===b?this.Kd.find(".oj-message \x3e .oj-message-content")[a||
0]:"oj-messaging-popup-validator-hint"===b?this.Kd.find(".oj-form-control-hints \x3e .oj-form-control-hint-validator")[a||0]:"oj-messaging-popup-converter-hint"===b?this.Kd.find(".oj-form-control-hints \x3e .oj-form-control-hint-converter")[0]:"oj-messaging-popup-title"===b?this.Kd.find(".oj-form-control-hints \x3e .oj-form-control-hint-title")[0]:null:null};a.cb.prototype.kD=function(b){b=b.data&&b.data.strategy;var a,c=b.aL();b.mq()&&c&&(a=b.Kd[0],a.innerHTML="",a.innerHTML=c,b.Kd.ojPopup("open",
b.gb))};a.cb.prototype.jA=function(b){b=b.data&&b.data.strategy;b.Kd.ojPopup("close",b.gb)};a.cb.prototype.eP=function(){if(!this.mq()){var b=this.gb,d=this.ON(),c=a.cb.Ol[this.ta.widgetName],c=c?c.fl:a.cb.Ol["default"].fl;this.ta.widget();this.Kd=f("\x3cdiv class\x3d'oj-messaging-popup-container'\x3e\x3c/div\x3e");f("body").append(this.Kd);this.Kd.ojPopup({rootAttributes:{"class":"oj-messaging-popup"},initialFocus:"none",tail:"simple",autoDismiss:"focusLoss",position:{my:"start bottom",at:"end top",
collision:"flipfit",of:d}});if(c.open)b.on(c.open,{strategy:this},this.kD);if(c.close)b.on(c.close,{strategy:this},this.jA)}};a.cb.prototype.ON=function(){var b=a.cb.Ol[this.ta.widgetName];return b&&b.position&&"launcher"===b.position?this.gb:this.ta.widget()};a.cb.prototype.qM=function(){this.mq()&&this.Kd&&(this.Kd.ojPopup("destroy"),this.Kd.remove())};a.cb.prototype.aL=function(){var b="",a=this.ta.document[0],c=[],e=!1,g=this;this.vI()&&c.push(this.$K());(this.Xr()||this.Wx()||this.Vx())&&c.push(this.ZK(a));
f.each(c,function(c,f){f&&(e?b=b.concat(g.WN(a)):e=!0,b=b.concat(f))});return b};a.cb.prototype.$K=function(){var b,d="",c,e,g,h,f;e=this.Nx();var l,n={};b=[];if(this.Px()){b=this.Ox();for(c=0;c<b.length;c++)f=b[c],f=f instanceof a.N?f:new a.N(f.summary,f.detail,f.severity),h=a.N.jl(f.severity),n[h]||(n[h]=[]),n[h].push(f);for(c=e;c>=a.N.kb.CONFIRMATION;c--)for(b=n[c]||[],e=0;e<b.length;e++)f=b[e],a.i.mb(f,a.N),h=a.N.jl(f.severity),g=this.YN(h),l=f.summary||g,f=f.detail||"",d=d.concat("\x3cdiv class\x3d'oj-message'\x3e").concat("\x3cspan class\x3d'"+
this.XN(h)+"' title\x3d'"+g+"' role\x3d'img'\x3e\x3c/span\x3e").concat("\x3cspan class\x3d'oj-message-content'\x3e").concat("\x3cdiv class\x3d'oj-message-summary'\x3e"+l+"\x3c/div\x3e"),f&&(d=d.concat("\x3cdiv class\x3d'oj-message-detail'\x3e"+f+"\x3c/div\x3e")),d=d.concat("\x3c/div\x3e")}return d};a.cb.prototype.ZK=function(b){var a=[],c,e="";this.Xr()&&(a=this.Mx(),a=a.length?a[0]:"",e+=this.Os(b,"oj-form-control-hint-converter",a));if(this.Wx())for(a=this.hI(),c=0;c<a.length;c++)e+=this.Os(b,"oj-form-control-hint-validator",
a[c]);this.Vx()&&(e+=this.Os(b,"oj-form-control-hint-title",this.gI()));return e?"\x3cdiv class\x3d'oj-form-control-hints'\x3e"+e+"\x3c/div\x3e":""};a.cb.prototype.Os=function(b,a,c){var e,g="oj-form-control-hint";c&&(e=f(b.createElement("div")),e.addClass(g+(" "+a)),e.append(this.xN(b,c)));return e?e.get(0).outerHTML:""};a.cb.prototype.xN=function(b,d){var c=null;a.Aa.hU(d)?c=a.Aa.$S(d.substring(6,d.length-7)):(c=f(b.createElement("div")),c.text(d),c=c.get(0));return c};a.cb.prototype.WN=function(b){return(b=
f(b.createElement("hr")))?b.get(0).outerHTML:""};a.cb.prototype.YN=function(b){var d;switch(b){case a.N.kb.FATAL:d=a.da.C("oj-message.fatal");break;case a.N.kb.ERROR:d=a.da.C("oj-message.error");break;case a.N.kb.WARNING:d=a.da.C("oj-message.warning");break;case a.N.kb.INFO:d=a.da.C("oj-message.info");break;case a.N.kb.CONFIRMATION:d=a.da.C("oj-message.confirmation")}return d};a.cb.prototype.XN=function(b){var d;switch(b){case a.N.kb.FATAL:d="oj-message-error-icon";break;case a.N.kb.ERROR:d="oj-message-error-icon";
break;case a.N.kb.WARNING:d="oj-message-warning-icon";break;case a.N.kb.INFO:d="oj-message-info-icon";break;case a.N.kb.CONFIRMATION:d="oj-message-confirmation-icon"}return a.cb.II+d};a.cb.prototype.mq=function(){return this.Kd?this.Kd.is(":oj-popup"):!1};a.Fa("oj.editableValue",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{disabled:void 0,help:{definition:null,source:null},messagesComponent:void 0,messagesCustom:void 0,messagingDisplayOptions:void 0,required:void 0,title:void 0,validators:void 0,
value:void 0,optionChange:void 0},getMessages:function(){for(var b=[],d,b=this.options.messagesComponent.concat(this.options.messagesCustom),c=0;c<b.length;c++)d=b[c],d instanceof a.Tb||d instanceof a.N?d.display=d.wn()?"immediate":"deferred":d instanceof Object&&(d.display="immediate");return b},getNodeBySubId:function(b){var a=this._super(b),c,e=0;if(!a)switch(c=b.subId,e=b.index||0,b=this.Jh(),c){case "oj-messaging-popup-content":case "oj-messaging-popup-converter-hint":case "oj-messaging-popup-title":a=
b.getNodeBySubId(c);break;case "oj-messaging-popup-validator-hint":case "oj-messaging-popup-message":a=b.getNodeBySubId(c,e)}return a||null},isValid:function(){return void 0===this.Gs?!0:this.Gs},refresh:function(){this._super();this.PA(!0)},reset:function(){var b=this.options.value;this.$s();this.vF(b)},showMessages:function(){var b=this.Gk,d,c=!1,e,g=[];for(e=0;e<b.length;e++)d=b[e],d instanceof a.Tb&&(c=c||d.ZM()),g.push(d.clone());c&&(this.options.messagesComponent=g,this.Xo("messagesComponent",
b,!1))},validate:function(){var b=this.Ig.Ll;if(this.isValid())return this.RA(this.options.value,void 0,b,this.tf.YH),this.isValid()?!0:!1;this.showMessages();return!1},Ig:{Kx:1,Ll:2,Tx:3},_InitOptions:function(b,a){this._super(b,a);this.dv=[]},_ComponentCreate:function(){var b=this.element,a=this.js(b);this._super();this.options.messagesComponent=this.options.messagesComponent||[];this.options.messagesCustom=this.options.messagesCustom||[];this.Gk=[];"boolean"===typeof this.options.disabled&&b.prop("disabled",
this.options.disabled);this.options.placeholder&&this._SetPlaceholder(this.options.placeholder);f.each(["required","title"],function(c,e){e in a&&b.removeAttr(e)})},Oj:function(){this._super();this.IL();this.PA(!1);this.cq();this.wM();this.xM();this.widget().addClass("oj-form-control")},_destroy:function(){var b=this.widget();this.$s(null,!0);this.Jh().ng(this.$i());f.each(this.Yf,function(){b.removeClass(this.toString())});b.removeClass("oj-form-control");this.element.removeAttr("aria-required");
this.Lb&&this.Lb._ojLabel("destroy");return this._super()},Focus:function(){this.rf().focus();return!0},_setOption:function(b,a,c){var e,g,h=!0,k=!1,l=!1;e=!1;if("string"===typeof b&&void 0!==a)switch(b){case "value":g=this.options.value;break;case "messagesComponent":e=!0;break;case "messagesCustom":g=this.options.messagesCustom||[];break;case "messagingDisplayOptions":g=f.extend({},this.options.messagingDisplayOptions)}if(e)return this;e=this._superApply(arguments);switch(b){case "converter":k=
!0;this.BL();break;case "messagesCustom":this.ZC(g,c);break;case "messagingDisplayOptions":this.cq();break;case "placeholder":h=!1;this.rQ(c);break;case "required":l=!0;break;case "title":this.Jh().update(this.$i(this.ue.Xx));break;case "validators":this.Tl();h=!1;break;case "value":l=k=!0,this.CS(g,c)}h&&(this.ws(b,a,k),this.ID(b,a),this.uv(b,a));l&&this.BM(b,c);return e},rf:function(){return this.element},WI:function(){var b=this.kB(this.element);if(null!==b&&0!==b.length)return b;b=this.element.prop("id");
if(void 0!==b&&(b=f("label[for\x3d'"+b+"']"),0!==b.length))return b;b=this.element.closest("[aria-labelledby]");return 0!==b.length&&(b=this.kB(b),null!==b&&0!==b.length)?b:null},Rj:function(){return this.element.val()},_GetMessagingLauncherElement:function(){return this.rf()},wd:function(){this.Es||(this.Es=a.$c.getConverterInstance(this.options.converter));return this.Es||null},Jo:function(){this.jz||(this.jz={});return this.jz},zh:function(){return this.rf().val()},ky:function(){if(!this.Ul){var b=
[],d=this.options.validators,c,e=!0,g=this.Jo(),h=[],k,l;for(l in g)g.hasOwnProperty(l)&&h.push(g[l]);b=b.concat(h);if(d){h=[];for(l=0;l<d.length;l++)c=d[l],"object"===typeof c?(c.validate&&"function"===typeof c.validate||(e=!1),e||(k=c.type)&&"string"===typeof k&&((g=a.ba.wh(k))?(c=f.extend({},c.options)||{},c.converter=c.converter||this.wd(),c.label=c.label||this.Wt(),c=g.createValidator(c)):a.T.error("Unable to locate a validatorFactory for the requested type: "+k)),h.push(c)):a.T.error("Unable to parse the validator provided:"+
c);b=b.concat(h)}this.Ul=b}return this.Ul||[]},Tl:function(){this.Ul&&(this.Ul.length=0);this.Ul=null;this.Jh().update(this.$i(this.ue.Yx))},ks:function(){return"required"===this.options.required},Lo:function(b){var a=this.zh();this.ee(a,b)},ws:function(b,a,c){switch(b){case "converter":a=this.options.value;this.KD(a,c);break;case "value":this.KD(a,c);break;case "required":this.Lb&&this.Lb._ojLabel("option","required",a);break;case "help":b=this.options.help.definition,a=this.options.help.source,
c=this.Fz(a),this.Lb&&(this.Lb._ojLabel("option","describedById",c),this.Lb._ojLabel("option","help",{definition:b,source:a}))}},xs:function(b){var a=this.rf();(b="required"==b?!0:!1)&&a?a.attr("aria-required",b):a.removeAttr("aria-required")},Hg:function(b){this.rf().val(b)},ee:function(b,d,c){if(void 0===b)return a.T.warn("Attempt to set a value of undefined"),!1;if(this.iy()){c=c&&c.Or?c.Or:this.Ig.Kx;if(b!==this.lz){if(this.$s(d),this.GE(b),b=this.RA(b,d,c,this.tf.xI),!this.isValid())return!1}else return a.T.Zw>
a.T.Mj&&a.T.info("Validation skipped and value option not updated as submitted value '"+b.toString?b.toString():b+" same as previous."),!1;this.vF(b,d)}return!0},iy:function(){return this.options.disabled?!1:!0},Vy:function(){this.iz={};this.Tl()},_SetPlaceholder:function(b){this.rf().attr("placeholder",b)},cJ:function(b,a){this.dv.push({option:b,previousValue:a})},Xo:function(b,d,c,e){a.i.GF(b,"");c=c?{writeback:"shouldWrite"}:{writeback:"shouldNotWrite"};d={option:b,component:a.Components.pr(this.element),
previousValue:d,value:this.options[b],optionMetadata:c};switch(b){case "messagesComponent":case "messagesCustom":this._trigger("optionChange",e||null,d);this.Jh().update(this.$i());break;case "value":this._trigger("optionChange",e||null,d)}},fz:function(b,d){return a.b.Zq(b,d)},_GetDefaultStyleClass:function(){return"oj-editablevalue"},ue:{Cl:1,Zx:2,Ix:3,Yx:4,Xx:5},Yf:{disabled:"oj-disabled",required:"oj-required"},tf:{Pr:1,Zr:2,Ur:3,xI:4,YH:5},$s:function(b,a){a?(this.Gk=[],this.options.messagesComponent=
[],this.options.messagesCustom=[]):(this.dt(b),this.oL(b))},dt:function(b){var a={};b&&(a._oj_originalEvent=b);a.changed=!this.$C(this.Gk,[]);this.Gk=[];this.options.messagesComponent=[];this.Xu(this.options.messagesComponent,a)},oL:function(b){var a={},c={};a.messagesCustom=[];b&&(c._oj_originalEvent=b);this.option(a,c)},BL:function(){this.Es=null;this.Jh().update(this.$i(this.ue.Ix))},IL:function(){if(this.Lb=this.WI()){var b=this.options.help.definition,a=this.options.help.source,c=this.Fz(a);
this.Lb._ojLabel({rootAttributes:{"class":this._GetDefaultStyleClass()+"-label"},describedById:c,required:this.options.required,help:{definition:b,source:a}})}},wM:function(){var b=this;f.each(this.dv,function(a,c){b.Xo(c.option,c.previousValue,!0)});this.dv=null},xM:function(){var b=this.Bv(this.tf.Pr);b?this.Rq(b):this.Xu(this.options.messagesComponent,{changed:!0});this.ZC(this.options.messagesCustom,{changed:!0})},BM:function(b,a){var c;c=!1;switch(b){case "value":a&&(c=a._oj_originalEvent?!0:
!1);c||(this.dt(null),(c=this.Bv(this.tf.Zr))&&this.Rq(c));break;case "required":this.dt(null),this.ks()&&this.Bv(this.tf.Ur)}},PA:function(b){b&&(this.Lb&&this.Lb._ojLabel("refresh"),this.Vy(),this.cq());this.ws("value",this.options.value);this.ID("required",this.options.required);this.uv("required",this.options.required);this.uv("disabled",this.options.disabled)},AM:function(b,a){var c=this.options.value;try{this.yF(c,this.Ig.Tx)}catch(e){throw c=this.nv(e,a,b),c;}return c},RA:function(b,a,c,e){var g=
b;try{c===this.Ig.Kx&&(g=this.gv(b)),this.yF(g,c===this.Ig.Tx)}catch(h){b=this.nv(h,a,e),this.Rq(b,a)}return g},LV:function(){return this.mz},MV:function(){return this.lz},kB:function(b){b=b.attr("aria-labelledby");return void 0!==b?f("label[id\x3d'"+b+"']"):null},Fz:function(b){this.element.uniqueId();var a=this.element.prop("id")+"Icons";b&&this.rf().each(function(){var b=f(this).attr("aria-describedby");b?f(this).attr("aria-describedby",b+" "+a):f(this).attr("aria-describedby",a)});return a},Rp:function(){return this.options.messagesCustom.concat(this.Gk)},
Wt:function(){if(this.Lb)return this.Lb.text()},ZB:function(){this.oz||(this.oz=new a.Me(this.isValid(),this.Rp()));return this.oz},Au:function(){return a.N.gh(this.Rp())>=a.N.kb.ERROR?!0:!1},cq:function(){var b=this.Jh(),a=this._GetMessagingLauncherElement(),c=this.$i(this.ue.Cl);this.hz||(this.options.placeholder="");b.hi(a,c)},Xu:function(b,a){this.YC("messagesComponent",b,a)},ZC:function(b,a){this.YC("messagesCustom",b,a)},YC:function(b,a,c){var e=!1,g=this.options[b],h=!1,f;c&&(e=c.changed||
!1,h=(f=c._oj_originalEvent||null)?!0:!1);this.xS();this.Jh().update(this.$i());!e&&this.$C(a,g)||this.Xo(b,a,h,f)},rQ:function(b){b=b&&b._oj_messaging_update?!1:!0;this._SetPlaceholder(this.options.placeholder);b?(this.hz=!0,this.cq()):this.hz=!1},KR:function(b){this.mz=b},GE:function(b){this.lz=b},Rq:function(b,d){var c={};a.i.mb(b,a.N);b&&(this.Gk.push(b),this.options.messagesComponent.push(b.clone()),c.changed=!0);d&&(c._oj_originalEvent=d);this.Xu(this.options.messagesComponent,c)},vF:function(b,
a){var c={},e={};c.value=b;a&&(e._oj_originalEvent=a);this.option(c,e)},xS:function(){var b=this.Rp(),b=b&&0!==b.length;this.Gs=!0;b&&(this.Gs=!this.Au())},CS:function(b,a){var c=this.options.value,e=!1,g=!1,h;a&&(e=a.changed||!1,h=a._oj_originalEvent||null,g=a._oj_originalEvent?!0:!1);!e&&this.fz(b,c)||this.Xo("value",b,g,h)},aN:function(b){var d=b,c=this.wd();c&&"object"===typeof c&&(c.format&&"function"===typeof c.format?d=c.format(b):a.T.Zw>a.T.Mj&&a.T.info("converter does not support the format method."));
return d},Jh:function(){this.gz||(this.gz=new a.Sa(this));return this.gz},uB:function(){var b;this.iz={label:this.Wt()};return(b=a.ba.wh(a.kc.VALIDATOR_TYPE_REQUIRED))?b.createValidator(this.iz):null},yN:function(b){var a,c=[];a="";var e;this.ks()&&(a=this.eC(b),a||(a=this.uB(),a.getHint&&"function"===typeof a.getHint&&(a=a.getHint())&&c.push(a)));for(e=0;e<b.length;e++)a=b[e],"object"===typeof a&&a.getHint&&"function"===typeof a.getHint&&(a=a.getHint())&&c.push(a);return c},$i:function(b){var a=
{},c=this.wd(),e=[];b=b||this.ue.Zx;if(b===this.ue.Cl||b===this.ue.Zx)e=this.Rp(),this.ZB().update(this.isValid(),e),a.validityState=this.ZB();(b===this.ue.Cl||b===this.ue.Ix)&&c&&"object"===typeof c&&c.getHint&&"function"===typeof c.getHint&&(c=c.getHint()||"",a.converterHint=c);if(b===this.ue.Cl||b===this.ue.Yx)c=this.ky(),e=this.yN(c)||[],a.validatorHint=e;if(b===this.ue.Cl||b===this.ue.Xx)a.title=this.options.title||"";return a},eC:function(b){var d=null,c,e=null;for(c=0;c<b.length;c++)if(d=b[c],
d instanceof a.Nc){e=d;break}return e},$C:function(b,d){var c=-1,e,g=!0,h=f.extend([],b),k=f.extend([],d);if(h===k)return!0;if(null==h||null==k||h.length!==k.length)return!1;f.each(h,function(b,d){e=d instanceof a.N?d:new a.N(d.summary,d.detail,d.severity);c=-1;f.each(k,function(b,a){e.ni(a)&&(c=b)});-1<c?k.splice(c,1):g=!1});return g},gv:function(b){var d=this.wd(),c=b;d&&"object"===typeof d&&(d.parse&&"function"===typeof d.parse?c=d.parse(b):a.T.Zw>a.T.Mj&&a.T.info("converter does not support the parse method."));
return c},nv:function(b,d,c){var e,g={};b instanceof a.sd||b instanceof a.te?(b=b.il(),a.i.mb(b,a.N),e=b.severity,d=b.summary,b=b.detail):(e=a.N.kb.ERROR,d=a.da.C("oj-message.error"),b=b.message||a.da.C("oj-converter.detail"));g.context=c||0;switch(c){case this.tf.Pr:case this.tf.Zr:case this.tf.Ur:g.display=a.Tb.Kj.Qr;break;default:g.display=a.Tb.Kj.Tr}return new a.Tb(d,b,e,g)},ID:function(b,a){switch(b){case "required":this.xs(a)}},KD:function(b,a){var c=b||this.options.value,e;e=this.mz;(a||c!==
e)&&this.tS(c)},uv:function(b,a){this.Yf.hasOwnProperty(b)&&("required"!==b?this.widget().toggleClass(this.Yf[b],!!a):this.widget().toggleClass(this.Yf[b],"required"===a))},Bv:function(b){var a;switch(b){case this.tf.Zr:case this.tf.Ur:case this.tf.Pr:try{this.AM(b)}catch(c){a=c}}return a||null},tS:function(b,a){var c,e;this.KR(b);c=b;try{c=this.aN(b)}catch(g){e=this.nv(g,a),this.Rq(e,a)}this.Hg(c);this.GE(this.zh())},yF:function(b,d){if(this.isValid()){var c=this.ky(),e,g,h=!1;this.ks()&&((e=this.eC(c))||
(e=this.uB()),e.validate(b),h=!0);if(!d)for(g=0;g<c.length;g++)e=c[g],"object"===typeof e&&(e.validate&&"function"===typeof e.validate?e instanceof a.Nc&&h||e.validate(b):a.T.Zw>a.T.Mj&&a.T.info("validator does not support the validate method."))}}});a.Components.ux({editableValue:{messagingDisplayOptions:a.Components.vj(function(){return{messages:["notewindow"],converterHint:["placeholder","notewindow"],validatorHint:["notewindow"],title:["notewindow"]}})}});a.Fa("oj._ojLabel",f.oj.baseComponent,
{version:"1.0.0",defaultElement:"\x3clabel\x3e",widgetEventPrefix:"oj",options:{describedById:null,help:{definition:null,source:null},required:null,rootAttributes:void 0},Xa:{lK:"tooltipHelp",nK:"tooltipRequired"},widget:function(){return this.Ij},refresh:function(){this._super();this.OD();this.LD()},_create:function(){this._super();this.At()},At:function(){this.Ij=this.element.wrap(this.oS()).closest(".oj-component");this.bQ();if(this.options.help.definition||this.options.help.source)this.tC(),this.pz();
"required"===this.options.required&&this.element.before(this.hE())},bQ:function(){var b=this.element.attr("class");this.ex=[];if(b)for(var b=b.split(/\s+/),a=b.length,c=0;c<a;c++){var e=b[c];0<e.indexOf("-label")&&(this.Ij.addClass(e),this.element.removeClass(e),this.ex.push(e))}},oS:function(){var b;this.options.rootAttributes&&(b=this.options.rootAttributes["class"]);return null!==b?"\x3cdiv class\x3d'oj-label oj-component "+b+"'\x3e\x3cdiv class\x3d'oj-label-group'\x3e\x3c/div\x3e\x3c/div\x3e":
"\x3cdiv class\x3d'oj-label oj-component'\x3e\x3cdiv class\x3d'oj-label-group'\x3e\x3c/div\x3e\x3c/div\x3e"},hE:function(){return"\x3cspan class\x3d'oj-label-required-icon oj-component-icon' title\x3d'"+this.C(this.Xa.nK)+"'\x3e\x3c/span\x3e"},XO:function(b,a,c){if(a){var e;e="\x3cspan id\x3d'"+c+"'\x3e"+("\x3ca href\x3d'"+a+"' target\x3d'_blank'\x3e\x3cspan class\x3d");e+="'oj-label-help-icon oj-component-icon oj-clickable-icon' title\x3d'";b||(b=this.C(this.Xa.lK));e+=b;e+="' role\x3d'img'\x3e\x3c/span\x3e";
e+="\x3c/a\x3e\x3c/span\x3e"}return e},pz:function(){var b=this.options.help.definition;if(b){this.element.addClass("oj-label-help-def");var a=this.element.attr("title");a?this.element.attr("title",a+" "+b):this.element.attr("title",b)}},cE:function(){this.element.removeClass("oj-label-help-def");this.element.attr("title","")},tC:function(){var b=this.options.help.source;if(b){var a=this.options.help.definition;this.Ij.find(".oj-label-group").prepend(this.XO(a,b,this.options.describedById))}},LD:function(){null!==
this.options.describedById&&this.Ij.find("#"+this.options.describedById).remove();this.cE();this.tC();this.pz()},OD:function(){"required"===this.options.required?0===this.Ij.find(".oj-label-required-icon").length&&this.element.before(this.hE()):this.Ij.find(".oj-label-required-icon").remove()},_setOption:function(b,a){this._superApply(arguments);"required"===b&&this.OD();"help"===b&&this.LD()},getNodeBySubId:function(b){var a=this._super(b);a||(b=b.subId,"oj-label-help-icon"===b&&(a=this.widget().find(".oj-label-help-icon")[0]),
"oj-label-help-icon-anchor"===b&&(a=this.widget().find(".oj-label-help-icon").parent()[0]),"oj-label-required-icon"===b&&(a=this.widget().find(".oj-label-required-icon")[0]));return a||null},_destroy:function(){this._super();for(var b=0;b<this.ex.length;b++)this.element.addClass(this.ex[b]);this.cE();this.Ij.replaceWith(this.element)}});a.ud={};o_("EditableValueUtils",a.ud,a);a.ud.zT=function(b,a){var c,e,g={};if(b&&a)switch(a){case "disabled":c=void 0!==b.attr("disabled")?!!b.prop("disabled"):void 0;
break;case "pattern":c=b.prop("pattern")||void 0;break;case "placeholder":c=b.prop("placeholder")||void 0;break;case "readonly":c=void 0!==b.attr("readonly")?!!b.prop("readonly"):void 0;break;case "required":c=b.attr("required");e=b.prop("required");c=void 0!==c?void 0!==e?!!e:!!c:void 0;break;case "title":c=b.prop("title");break;case "value":c=b.val()||void 0;break;default:c=b.attr(a)||void 0}void 0!==c?(g.dG=!0,g.value=c):g.dG=!1;return g};a.ud.vi=function(b,d,c){f.each(b,function(b,g){var h=g.attribute,
f=g.option||h,l=g.coerceDomValue,n=g.validateOption,m=c.element,q=c.options[f];void 0===d[f]&&(q=c.options[f],h=a.ud.zT(m,h),h.dG?(h=h.value,l&&("boolean"===typeof l?h=a.ud.bT(f,h):"function"===typeof l&&(h=l.call(c,h))),c.options[f]=h,c.cJ(f,q)):void 0===q&&(c.options[f]=g.defaultOptionValue));n&&("boolean"===typeof n?a.ud.iV(f,c.options[f]):"function"===typeof n&&n.call(c))})};a.ud.iV=function(b,a){var c=!1;switch(b){case "required":"required"!==a&&"optional"!==a&&(c=!0);break;case "readOnly":case "disabled":null!==
a&&"boolean"!==typeof a&&(c=!0)}if(c)throw"Option '"+b+" 'has invalid value set: "+a;};a.ud.bT=function(b,a){var c=a;switch(b){case "required":c=a?"required":"optional"}return c}});
//# sourceMappingURL=oj-modular.map