/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a,f){a.Fa("oj.inputBase",f.oj.editableValue,{version:"1.0.0",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"",_WIDGET_CLASS_NAMES:"",_INPUT_HELPER_KEY:"",options:{converter:void 0,placeholder:void 0,readOnly:void 0},Wy:function(b){var a=this._superApply(arguments);this.zQ();return a},_InitOptions:function(b,d){this._super(b,d);a.ud.vi([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"pattern",defaultOptionValue:""},
{attribute:"placeholder",defaultOptionValue:""},{attribute:"value",defaultOptionValue:null},{attribute:"readonly",option:"readOnly",defaultOptionValue:!1,validateOption:!0},{attribute:"required",defaultOptionValue:"optional",coerceDomValue:!0,validateOption:!0},{attribute:"title",defaultOptionValue:""}],d,this)},_ComponentCreate:function(){var b=this.element,a=this._superApply(arguments),c=this.js(b);"boolean"===typeof this.options.readOnly&&this.element.prop("readonly",this.options.readOnly);this.Ql()&&
this.DS();"pattern"in c&&b.removeAttr("pattern");return a},Oj:function(){var b=this._superApply(arguments),a=this;this._CLASS_NAMES&&this.element.addClass(this._CLASS_NAMES);this.element.on("blur",f.proxy(this.cv,this));this.element.on("keydown",f.proxy(this.wq,this));this.element.on("drop",function(){this.focus()});this.$r();f.each(["disabled","readOnly"],function(b,e){a._setOption(e,a.options[e])});return b},_setOption:function(b,a){var c=this._superApply(arguments);"disabled"===b&&this.element.prop("disabled",
a);"readOnly"===b&&(this.element.prop("readonly",a),this.zq("readOnly",a));"pattern"===b&&(this.Fs.pattern=a);return c},_destroy:function(){var b=this._superApply(arguments);this.element.off("blur drop keydown");this.Iu&&this.Iu.remove();this.Ql()&&this.element.unwrap();this.XJ();return b},Yf:{readOnly:"oj-read-only"},zQ:function(){for(var b=this._ATTR_CHECK,a=0,c=b.length;a<c;a++){var e=b[a].attr;"setMandatory"in b[a]&&this.element.attr(e,b[a].setMandatory)}},cv:function(b){this.ee(this.zh(),b)},
wq:function(b){b.keyCode===f.ui.keyCode.ENTER&&this.ee(this.zh(),b)},Ql:function(){return this._WIDGET_CLASS_NAMES},DS:function(){f(this.element).wrap(f("\x3cdiv\x3e").addClass(this._WIDGET_CLASS_NAMES));this.ES=this.element.parent()},$r:function(){if(this._INPUT_HELPER_KEY&&this.Ql()){var b=this.element.attr("aria-describedby")||"",a=this.Ah(this._INPUT_HELPER_KEY);this.element.attr("aria-describedby",b+(" "+a));this.Iu=f("\x3cdiv class\x3d'oj-helper-hidden-accessible' id\x3d'"+a+"'\x3e"+this.C(this._INPUT_HELPER_KEY)+
"\x3c/div\x3e");this.widget().append(this.Iu)}},Vy:function(){this.Fs={};this._super()},Jo:function(){var b=this._superApply(arguments),d={};this.options.pattern&&(d[a.kc.VALIDATOR_TYPE_REGEXP]=this.mN());return f.extend(d,b)},zq:function(b,a){this.Yf.hasOwnProperty(b)&&this.widget().toggleClass(this.Yf[b],!!a)},mN:function(){var b;this.Fs={pattern:this.options.pattern,label:this.Wt()};return(b=a.ba.wh(a.kc.VALIDATOR_TYPE_REGEXP))?b.createValidator(this.Fs):null},Ah:function(b){return this.uuid+"_"+
b},No:function(){return"rtl"===this.uc()},getNodeBySubId:function(b){return this._super(b)},widget:function(){return this.Ql()?this.ES:this.element}});a.Fa("oj.ojInputText",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],_CLASS_NAMES:"oj-inputtext-input",_WIDGET_CLASS_NAMES:"oj-inputtext oj-form-control oj-component",options:{pattern:void 0},_GetDefaultStyleClass:function(){return"oj-inputtext"}});a.Fa("oj.ojTextArea",
f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3ctextarea\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"oj-textarea-input",_WIDGET_CLASS_NAMES:"oj-textarea oj-form-control oj-component",options:{pattern:void 0},_GetDefaultStyleClass:function(){return"oj-textarea"}});a.Fa("oj.ojInputPassword",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"password"}],_CLASS_NAMES:"oj-inputpassword-input",_WIDGET_CLASS_NAMES:"oj-inputpassword oj-form-control oj-component",
options:{pattern:void 0},_GetDefaultStyleClass:function(){return"oj-inputpassword"}})});
//# sourceMappingURL=oj-modular.map