/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","knockout"],function(a,f,b){function d(b,a){var d={};d.value=a.value;return d}function c(b,a){var d={},c=a.optionMetadata;c&&"shouldWrite"===c.writeback&&(d[a.option]=a.value);return d}function e(){this.Init()}function g(b,a,d){this.Init(b,a,d)}function h(a,d){return function(c){var e,g;e=c.parentElement;g=a.createChildContext(c.data,null,function(b){b.$key=c.key;b.$metadata=c.metadata;b.$headerContext=c});b.renderTemplate(d,g,null,e);return null}}function k(a,d){return function(c){var e,
g;e=c.parentElement;g=a.createChildContext(c.data,null,function(b){b.$keys=c.keys;b.$metadata=c.metadata;b.$cellContext=c});b.renderTemplate(d,g,null,e);return null}}function l(a,d,c){var e={};(function(d,c){e=function(e){var g=null,f=null;"header"==c?(g=a.extend({$column:e.column,$headerContext:e.headerContext}),f=e.headerContext.parentElement):"cell"==c&&(g=a.createChildContext(e.row,null,function(b){b.$column=e.column;b.$cellContext=e.cellContext}),f=e.cellContext.parentElement);"footer"==c&&(g=
a.extend({$column:e.column,$footerContext:e.footerContext}),f=e.footerContext.parentElement);b.renderTemplate(d,g,null,f,"replaceNode")}})(c,d);return e}function n(a,d){return function(c){var e=a.createChildContext(c.row,null,function(b){b.$rowContext=c.rowContext});b.renderTemplate(d,e,null,c.rowContext.parentElement,"replaceNode")}}a.$=function(b,a){this.Init(b,a)};o_("ComponentBinding",a.$,a);a.b.oa(a.$,a.b,"oj.ComponentBinding");a.$.create=function(d,c){if(null==d)throw"Binding name is required!";
var e=new a.$(d,c),g=b.bindingHandlers,f,h=Array.isArray(d)?d:[d];for(f=0;f<h.length;f++)g[h[f]]=e;return e};o_("ComponentBinding.create",a.$.create,a);a.$.od=function(){return a.$.bJ};o_("ComponentBinding.getDefaultInstance",a.$.od,a);a.$.prototype.rd=function(b){var d=b["for"],d=null==d?"@global":d;a.T.option("level")>=a.T.yo&&this.pq[d]&&a.T.error("Managed Attributes for '%s' are redefined",d);this.pq[d]=b};a.b.g("ComponentBinding.prototype.setupManagedAttributes",{rd:a.$.prototype.rd});a.$.ww=
function(){a.$.Zz.ww()};o_("ComponentBinding.deliverChanges",a.$.ww,a);a.$.prototype.Init=function(b,d){a.$.t.Init.call(this);"string"===typeof d&&(d={componentName:d});this.Ms=d||{};this.XK=Array.isArray(b)?b:[b];this.init=a.b.An(this,this._init);this.update=a.b.An(this,this.Zv);this.pq={}};a.$.ps="_ojNeedsJUIBInit";a.$.prototype._init=function(d,c,e,g,h){b.applyBindingsToDescendants(h,d);f(d).data(a.$.ps,!0);return{controlsDescendantBindings:!0}};a.$.prototype.Zv=function(b,d,c,e,g){e=f(b);e.data(a.$.ps)&&
(e.data(a.$.ps,null),this.mC(b,e,d,c,g))};a.$.prototype.mC=function(e,f,h,p,l){var k=h(),n=null,v=!1,w=[],x=null,E=null,A=a.$.dN(this.XK,e,l),Q=0,B={},z=this.Ms.componentName;if(null==z){n="component";if(!A[n]&&(n="role",!A[n])){a.T.error("component attribute is required for the ojComponent binding");return}var F=k[n];if(null==F){a.T.error("non-null component attribute is required for the ojComponent binding");return}b.computed(function(){a.$.Bt(A[n],n,B,l);if(0==Q)z=b.utils.unwrapObservable(F);else{v=
!0;A=null;a.$.qS(f);if(E){x.YF();x=null;var d=this.Ms.beforeDestroy;d&&d(e,E,h,p,l);E("destroy");E=null;for(d=0;d<w.length;d++)w[d].YF();w=null}this.mC(e,f,h,p,l)}return null},this,{disposeWhenNodeIsRemoved:e})}if(null!=z)if(E=f[z],"function"===typeof E){var E=E.bind(f),M=a.$.kE(this.pq,A,z),y=a.$.od();this!==y&&(y=y.CN(A,z),a.Ec.dh(y,M),M=y);var J={},x=new g(E,e,a.$.Zz),y={"^slider$":[{event:"slidechange",getter:d}],"^oj*":[{event:"ojoptionchange",getter:c}]},I=function(){var b=this.EQ,d=A[b];d&&
a.$.Bt(d,b,B,l);if(0===Q){var c=a.$.Oq(k[b]);null!=M[b]?(d=M[b].ZT,null!=d&&(b=d(b,c,e,E,h,p,l)||{},a.Ec.dh(J,b))):J[b]=c}else if(!v)if(d=a.$.Oq(h()[b]),null!=M[b]){var g=M[b].update;if(null!=g)for(c in b=g(b,d,e,E,h,p,l)||{},b)b.hasOwnProperty(c)&&x.BF(c,b[c])}else x.BF(b,d);return null},D;for(D in k)k.hasOwnProperty(D)&&D!==n&&w.push(b.computed(I,{EQ:D},{disposeWhenNodeIsRemoved:e}));a.$.UQ(f,z,y,h,A,x,l);D=a.$.$A(J);E(J);for(var G in D)E("option",G,D[G]);(G=this.Ms.afterCreate)&&G(e,E,h,p,l);J=
null}else a.T.error("Component %s is not found",z);Q=1};a.$.dN=function(a,d,c){var e={},g=null,g=b.bindingProvider.instance,f;f=null;var h,g=g.AT?g.AT(d,c):d.getAttribute("data-bind");if(!g)return e;d=b.jsonExpressionRewriting.parseObjectLiteral(g);c=/^(\s|\u00A0)+|(\s|\u00A0)+$/g;for(g=0;g<d.length;g+=1){h=d[g];var l=h.key.replace(c,"");if(0<=a.indexOf(l)){f=h.value;break}}if(!f)return e;d=b.jsonExpressionRewriting.parseObjectLiteral(f);for(a=0;a<d.length;a+=1)f=d[a],e[f.key.replace(c,"")]=f.value.replace(c,
"");return e};a.$.Bt=function(b,a,d,c){var e=d[a];void 0===e&&("string"!==typeof b&&(b=b()),e=null,null!==b&&(e=new Function("$context","with($context){with($data||{}){return "+b+";}}")),d[a]=e);return e?e(c):null};a.$.prototype.CN=function(b,d){return a.$.kE(this.pq,b,d)};a.$.kE=function(b,a,d){function c(a){a=b[a];if(null!=a){g.push(a);a=a.use;var d;if(null!=a)for(a=Array.isArray(a)?a:[a],d=0;d<a.length;d++)c(a[d])}}var e={},g=[];c(d);d=b["@global"];var f;d&&g.push(d);if(0<g.length)for(f in a)if(a.hasOwnProperty(f))for(d=
0;d<g.length;d++){var h=g[d],l=h.attributes;if(null!=l&&0<=l.indexOf(f)){e[f]={ZT:h.init,update:h.update};break}}return e};a.$.ny=".ojWriteback";a.$.qS=function(b){b&&b.off(a.$.ny)};a.$.UQ=function(b,d,c,e,g,f,h){var l={},k;for(k in c)if(d.match(k)){d=c[k];for(c=0;c<d.length;c++)k=d[c],b.on(k.event+a.$.ny,{ST:k.getter},function(b,d){b.stopPropagation();var c=b.data.ST(b,d);f.bV();try{for(var k in c)a.$.FS(k,e()[k],c[k],g[k],h,l)}finally{f.KU()}});break}};a.$.PN=function(b){var a=["true","false","null",
"undefined"];if(null==b||0<=a.indexOf(b))return null;a=b.match(/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i);return null===a?null:"function(v){"+(a[1]?"Object("+a[1]+")"+a[2]:b)+"\x3dv;}"};a.$.FS=function(d,c,e,g,f,h){null!=c&&b.isObservable(c)?b.isWriteableObservable(c)&&c(e):(d=a.$.Bt(function(){return a.$.PN(g)},d,h,f))&&d(e)};a.$.Oq=function(d){d=b.utils.unwrapObservable(d);(Array.isArray(d)||a.Ec.isPlainObject(d))&&d.ojConvertToJS&&(d=b.toJS(d));return d};a.$.$A=function(b){var a={},
d;for(d in b)0<=d.indexOf(".")&&(a[d]=b[d]);for(var c in a)delete b[c];return a};a.b.oa(e,a.b,"ComponentBinding.GlobalChangeQueue");e.prototype.Init=function(){e.t.Init.call(this);this.Ri=[]};e.prototype.GU=function(b){-1===this.Ri.indexOf(b)&&(this.Ri.push(b),this.xp||(this.xp=setTimeout(a.b.An(this,this.IA),1)))};e.prototype.HU=function(b){b=this.Ri.indexOf(b);0<=b&&this.Ri.splice(b,1)};e.prototype.ww=function(){this.xp&&clearTimeout(this.xp);this.IA()};e.prototype.IA=function(){var b;this.xp=null;
try{for(b=0;b<this.Ri.length;b+=1)this.Ri[b]()}finally{this.Ri=[]}};a.b.oa(g,a.b,"ComponentBinding.ComponentChangeTracker");g.prototype.Init=function(b,d,c){g.t.Init.call(this);this.ta=b;this.CM=d;this.DD=c;this.pF=a.b.An(this,this.MK);this.op={};this.Vk=0};g.prototype.BF=function(b,a){this.wP()||this.tM||(this.op[b]=a,this.DD.GU(this.pF))};g.prototype.YF=function(){this.DD.HU(this.pF);this.tM=!0};g.prototype.KU=function(){a.i.assert(0<this.Vk,"ComponentChangeTracker._suspendCount underflow");this.Vk-=
1};g.prototype.bV=function(){this.Vk+=1};g.prototype.wP=function(){return 1<=this.Vk};g.prototype.MK=function(){try{if(null!=a.Components.pr(this.CM)){var b=a.$.$A(this.op),d={changed:!0};this.ta("option",this.op,d);for(var c in b)this.ta("option",c,b[c],d)}}finally{this.op={}}};a.$.Zz=new e;a.$.bJ=a.$.create(["ojComponent","jqueryUI"]);a.Vw={};o_("koStringTemplateEngine",a.Vw,a);a.Vw.dU=function(){function a(b){this.Wk=b;this.text=function(b){if(!b)return d[this.Wk];d[this.Wk]=b};this.data=function(b,
a){c[this.Wk]||(c[this.Wk]={});if(1===arguments.length)return c[this.Wk][b];c[this.Wk][b]=a}}var d={},c={},e=new b.nativeTemplateEngine;e.makeTemplateSource=function(d,c){if("string"==typeof d){c=c||document;var e=c.getElementById(d);return e?new b.templateSources.domElement(e):new a(d)}if(d&&1==d.nodeType||8==d.nodeType)return new b.templateSources.anonymousTemplate(d)};b.templates=d;b.setTemplateEngine(e)};o_("koStringTemplateEngine.install",a.Vw.dU,a);a.$.od().rd({attributes:["header","cell"],
init:function(b,a,d,c,e,g,f){"header"===b?(b=a.row,null!=b&&(d=b.template,null!=d&&(b.renderer=h(f,d))),b=a.column,null!=b&&(d=b.template,null!=d&&(b.renderer=h(f,d))),c({header:a})):"cell"===b&&(b=a.template,null!=b&&(a.renderer=k(f,b)),c({cell:a}))},update:function(b,a,d,c,e,g,f){return"header"===b?(b=a.row,null!=b&&(d=b.template,null!=d&&(b.renderer=h(f,d))),b=a.column,null!=b&&(d=b.template,null!=d&&(b.renderer=h(f,d))),{header:a}):"cell"===b?(b=a.template,null!=b&&(a.renderer=k(f,b)),{cell:a}):
null},"for":"ojDataGrid"});b.bindingHandlers.ojContextMenu={update:function(a,d){f(a).off(".ojContextMenu");var c=b.utils.unwrapObservable(d());"string"!==f.type(c)&&(c=a.getAttribute("contextmenu"))&&(c="#"+c);c&&(c=f(c).data("oj-ojMenu"));if(c){var e=f(a);e.on("keydown.ojContextMenu contextmenu.ojContextMenu",function(b){return"contextmenu"===b.type||121==b.which&&b.shiftKey?(c.show(b,{launcher:e,focus:"menu"}),!1):!0})}}};a.$.od().rd({attributes:["columns","columnsDefault","rowTemplate"],init:function(b,
a,d,c,e,g,f){if("columns"==b||"columnsDefault"==b){var h;for(d=0;d<a.length;d++){var k=a[d];e=k.template;g=k.footerTemplate;h=k.headerTemplate;null!=e&&(k.renderer=l(f,"cell",e));null!=g&&(k.footerRenderer=l(f,"footer",g));null!=h&&(k.headerRenderer=l(f,"header",h))}"columns"==b?c({columns:a}):c({columnsDefault:a})}else"rowTemplate"==b&&c({rowRenderer:n(f,a)})},update:function(b,a,d,c,e,g,f){if("columns"==b||"columnsDefault"==b){var h;for(d=0;d<a.length;d++){var k=a[d];e=k.template;g=k.footerTemplate;
h=k.headerTemplate;null!=e&&(k.renderer=l(f,"cell",e));null!=g&&(k.footerRenderer=l(f,"footer",g));null!=h&&(k.headerRenderer=l(f,"header",h))}"columns"==b?c({columns:a}):c({columnsDefault:a})}else if("rowTemplate"==b)return{rowRenderer:n(f,a)};return null},"for":"ojTable"})});
//# sourceMappingURL=oj-modular.map