/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtLegend"],function(a,f){a.Gl=function(a){this.f=a};o_("LegendItem",a.Gl,a);a.Gl.prototype.getText=function(){return this.f?this.f.text:null};a.b.g("LegendItem.prototype.getText",{getText:a.Gl.prototype.getText});a.Fa("oj.ojLegend",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{categoryFilter:null,categoryHighlight:null},pf:function(a,d,c){return DvtLegend.newInstance(a,d,c)},Ki:function(){var a=
this._super();a["oj-legend"]={path:"textStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-legendTitle"]={path:"titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-legendSectionTitle"]={path:"_sectionTitleStyle",property:"CSS_TEXT_PROPERTIES"};return a},Li:function(a){var d=a&&a.getType?a.getType():null;d===DvtCategoryHideShowEvent.TYPE_HIDE||d===DvtCategoryHideShowEvent.TYPE_SHOW?(d=d===DvtCategoryHideShowEvent.TYPE_HIDE?"out":"in",this.qF(this.options.sections,a.getCategory(),d),this._trigger("categoryFilter",
null,{category:a.getCategory(),type:d})):d===DvtCategoryRolloverEvent.TYPE_OVER||d===DvtCategoryRolloverEvent.TYPE_OUT?(d=d===DvtCategoryRolloverEvent.TYPE_OVER?"on":"off",this._trigger("categoryHighlight",null,{categories:[a.getCategory()],type:d})):this._super(a)},qF:function(a,d,c){if(a)for(var e=0;e<a.length;e++)if(a[e].items)for(var f=a[e].items,h=0;h<f.length;h++){if(f[h].id&&f[h].id==d||!f[h].id&&f[h].text==d)f[h].categoryVisibility="out"==c?"hidden":"visible"}else this.qF(a[e].sections,d,
c)},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getTitle:function(){return this.ta.getAutomation().getTitle()},getSection:function(b){var d=this.ta.getAutomation();return new a.Bg(d.getSection(b))},getItem:function(b){var d=this.ta.getAutomation();return new a.Gl(d.getItem(b))}});a.Bg=function(a){this.f=a};o_("LegendSection",a.Bg,a);a.Bg.prototype.getTitle=function(){return this.f?this.f.title:null};a.b.g("LegendSection.prototype.getTitle",{getTitle:a.Bg.prototype.getTitle});
a.Bg.prototype.getSection=function(b){return this.f.sections?new a.Bg(this.f.sections[b]):null};a.b.g("LegendSection.prototype.getSection",{getSection:a.Bg.prototype.getSection});a.Bg.prototype.getItem=function(b){return this.f.items?new a.Gl(this.f.items[b]):null};a.b.g("LegendSection.prototype.getItem",{getItem:a.Bg.prototype.getItem})});
//# sourceMappingURL=oj-modular.map