/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){a.Fa("oj.ojMenu",f.oj.baseComponent,{defaultElement:"\x3cul\x3e",delay:300,role:"menu",widgetEventPrefix:"oj",Qo:"ojMenuClickAwayHandler",options:{menuPosition:{my:"start top",at:"start bottom"},menuSelector:"ul",submenuPosition:{my:"start top",at:"end top"},beforeShow:null,blur:null,focus:null,select:null},_create:function(){this.sj=this.element;this.dx=!1;this.element.uniqueId().addClass("oj-menu oj-component").toggleClass("oj-menu-icons",
!!this.element.find(".oj-component-icon").length).attr({role:this.role,tabIndex:"0"});this._on(!0,{"mousedown .oj-menu-item":function(a){this.options.disabled&&a.preventDefault()},click:function(a){this.options.disabled&&a.preventDefault()},keydown:function(a){this.options.disabled&&a.keyCode===f.ui.keyCode.ESCAPE&&this.gb&&this.Gt(a)}});this.options.disabled&&this.element.addClass("oj-disabled").attr("aria-disabled","true");this._on({"mousedown .oj-menu-item \x3e a":function(a){a.preventDefault()},
"click .oj-disabled \x3e a":function(a){a.preventDefault()},click:function(){this.dx=!1},"click .oj-menu-item:has(a)":function(a){var b=f(a.target).closest(".oj-menu-item");!this.dx&&b.not(".oj-disabled").length&&(this.dx=!0,a.preventDefault(),this.la&&this.la.closest(b).length&&this.la.get(0)!=b.get(0)||(b.has(".oj-menu").length?this.expand(a):(this.select(a),this.element.is(":focus")||(this.element.trigger("focus",[!0]),this.la&&1===this.la.parents(".oj-menu").length&&clearTimeout(this.Nf)))))},
"mouseenter .oj-menu-item":function(a){var b=f(a.currentTarget);b.siblings().children(".oj-active").removeClass("oj-active");this.focus(a,b)},mouseleave:this.collapseAll,"mouseleave .oj-menu":this.collapseAll,focus:function(a,b){var e=this.la||this.element.children(".oj-menu-item").eq(0);b||this.focus(a,e)},keydown:this.hj,keyup:function(a){if(a.keyCode==f.ui.keyCode.ENTER||a.keyCode==f.ui.keyCode.SPACE)this.Zo=!1}});this.Cb();this.QQ();this._super()},QQ:function(){var a=this.document.data(this.Qo);
a||(a=function(a){if("focus"===a.type||"mousedown"===a.type||93==a.which||121==a.which&&a.shiftKey||93==a.keyCode){var d=b.slice(0,b.length);f.each(d,function(b,d){!f(a.target).closest(d.element).length&&("keydown"===a.type||"mousedown"===a.type&&3===a.which||!f(a.target).closest(d.gb).length||d.qP&&"mousedown"===a.type&&3!==a.which)&&(d.collapseAll(a),d.gb&&d.Yo(a))})}},this.document.data(this.Qo,a),this.document[0].addEventListener("keydown",a,!0),this.document[0].addEventListener("mousedown",a,
!0),this.document[0].addEventListener("focus",a,!0))},pS:function(){var a=this.document.data(this.Qo);a&&1===f(":oj-menu").length&&(this.document[0].removeEventListener("keydown",a,!0),this.document[0].removeEventListener("mousedown",a,!0),this.document[0].removeEventListener("focus",a,!0),this.document.removeData(this.Qo))},_destroy:function(){this.element.removeAttr("aria-activedescendant").find(".oj-menu").addBack().removeClass("oj-menu oj-component oj-menu-icons").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();
this.element.find(".oj-menu-item").removeClass("oj-menu-item").removeAttr("role").children("a").removeAttr("aria-disabled").removeUniqueId().removeClass("oj-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=f(this);a.data("oj-ojMenu-submenu-icon")&&a.remove()});this.element.find("a").removeAttr("aria-expanded");this.element.find(".oj-menu-divider").removeClass("oj-menu-divider").removeAttr("role");this.pS();0<=b.indexOf(this)&&b.splice(b.indexOf(this),
1)},hj:function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")}var e,g,h,k,l=!0;switch(a.keyCode){case f.ui.keyCode.HOME:this.tq("first","first",a);break;case f.ui.keyCode.END:this.tq("last","last",a);break;case f.ui.keyCode.UP:this.previous(a);break;case f.ui.keyCode.DOWN:this.next(a);break;case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.keyCode===f.ui.keyCode.RIGHT^this.zj?this.la&&!this.la.is(".oj-disabled")&&this.expand(a):this.collapse(a);break;case f.ui.keyCode.ENTER:case f.ui.keyCode.SPACE:this.Zj(a);
this.Zo=!0;var n=this;setTimeout(function(){n.Zo=!1},100);break;case f.ui.keyCode.ESCAPE:this.gb?(g=this.element.attr("aria-activedescendant"),h="#"+this.element.attr("id")+"\x3e*\x3ea",g&&!f("#"+g).is(h)?this.collapse(a):this.Gt(a)):this.collapse(a);break;default:l=!1,e=this.Cr||"",g=String.fromCharCode(a.keyCode),h=!1,clearTimeout(this.wT),g===e?h=!0:g=e+g,k=new RegExp("^"+b(g),"i"),e=this.sj.children(".oj-menu-item").filter(function(){return k.test(f(this).children("a").text())}),e=h&&-1!==e.index(this.la.next())?
this.la.nextAll(".oj-menu-item"):e,e.length||(g=String.fromCharCode(a.keyCode),k=new RegExp("^"+b(g),"i"),e=this.sj.children(".oj-menu-item").filter(function(){return k.test(f(this).children("a").text())})),e.length?(this.focus(a,e),1<e.length?(this.Cr=g,this.wT=this._delay(function(){delete this.Cr},1E3)):delete this.Cr):delete this.Cr}l&&a.preventDefault()},Zj:function(a){this.la.is(".oj-disabled")||(this.la.children("a[aria-haspopup\x3d'true']").length?this.expand(a):this.select(a))},refresh:function(){this._super();
this.Cb()},Cb:function(){this.zj="rtl"===this.uc();var a=this,b=this.element.find(this.options.menuSelector);b.filter(":not(.oj-menu)").addClass("oj-menu oj-component").hide().attr({role:this.role,"aria-hidden":"true"}).each(function(){var b=f(this),c=a.nu(b),h=f("\x3cspan\x3e");h.addClass("oj-menu-submenu-icon oj-component-icon").data("oj-ojMenu-submenu-icon",!0);c.attr("aria-haspopup","true").attr("aria-expanded","false").prepend(h);c=c.attr("id");b.attr("aria-labelledby",c)});b=b.add(this.element).children();
b.filter(".oj-menu-divider").has("a").removeClass("oj-menu-divider oj-menu-item").removeAttr("role");b.filter(":not(.oj-menu-item):has(a)").addClass("oj-menu-item").attr("role","presentation").children("a").uniqueId().attr({tabIndex:"-1",role:"menuitem"});b.filter(":not(.oj-menu-item)").each(function(){var a=f(this);/[^\-\u2014\u2013\s]/.test(a.text())||a.addClass("oj-menu-divider").attr("role","separator")});b.filter(".oj-disabled").children("a").attr("aria-disabled","true");b.filter(":not(.oj-disabled)").children("a").removeAttr("aria-disabled");
this.la&&!f.contains(this.element[0],this.la[0])&&this.blur()},nu:function(a){return a.prev("a")},hW:function(){return"menuitem"},focus:function(a,b){var e;this.blur(a,a&&"focus"===a.type);this.la=b.first();e=this.la.children("a").addClass("oj-focus");this.role&&this.element.attr("aria-activedescendant",e.attr("id"));this.la.parent().closest(".oj-menu-item").children("a:first").addClass("oj-active");a&&"keydown"===a.type?this.fm():this.Nf=this._delay(function(){this.fm()},this.delay);e=b.children(".oj-menu");
e.length&&a&&/^mouse/.test(a.type)&&!this.la.hasClass("oj-disabled")&&this.$R(e);this.sj=b.parent();this._trigger("focus",a,{item:b})},blur:function(a,b){b||clearTimeout(this.Nf);this.la&&(this.la.children("a").removeClass("oj-focus"),this.la=null,this._trigger("blur",a,{item:this.la}))},Gt:function(a){this.gb.focus();this.Yo(a)},Yo:function(a){this.element.hide().attr("aria-hidden","true");this.gb=void 0;this._trigger("__dismiss",a,{});0<=b.indexOf(this)&&b.splice(b.indexOf(this),1)},show:function(d,
c){this.tQ||(this.sQ(),this.tQ=!0);if(c&&c.launcher){this.qP=d?("mousedown"===d.type||"contextmenu"===d.type)&&3===d.which||93==d.which||121==d.which&&d.shiftKey:!1;var e=c.launcher;if(this._trigger("beforeShow",d,{launcher:e})){var e="string"===f.type(e)?f("#"+e):e,g=this.element[0],h=b.slice(0,b.length);f.each(h,function(a,b){b.element[0]!==g&&(b.collapseAll(d),b.gb&&b.Yo(d))});h=a.Eg.co(this.options.menuPosition,this.zj);null==h.of&&(h.of=d&&"contextmenu"===d.type?d:e);this.element.show().removeAttr("aria-hidden").position(h);
((h=!c.focus||"firstItem"===c.focus)||"menu"===c.focus)&&this.element.focus();h?this.focus(d,this.element.children().first()):this.blur(d);this.gb=e;b.push(this)}}},sQ:function(){this.element.css({position:"absolute"})},$R:function(a){clearTimeout(this.Nf);"true"===a.attr("aria-hidden")&&(this.Nf=this._delay(function(){this.fm();this.jD(a)},this.delay))},jD:function(d){var c=f.extend({of:this.la},a.Eg.co(this.options.submenuPosition,this.zj));clearTimeout(this.Nf);this.element.find(".oj-menu").not(d.parents(".oj-menu")).hide().attr("aria-hidden",
"true");d.show().removeAttr("aria-hidden").position(c);this.nu(d).attr("aria-expanded","true");!this.gb&&0>b.indexOf(this)&&b.push(this)},collapseAll:function(a,b){this.Ds(a,b,this.delay)},Ds:function(a,b,e){function g(){var e=b?h.element:f(a&&a.target).closest(h.element.find(".oj-menu"));e.length||(e=h.element);h.fm(e);h.blur(a);h.sj=e}clearTimeout(this.Nf);var h=this;e?this.Nf=this._delay(g,e):g()},fm:function(a){a||(a=this.la?this.la.parent():this.element);var c=a.find(".oj-menu");c.hide().attr("aria-hidden",
"true");this.nu(c).attr("aria-expanded","false");a.find("a.oj-active").removeClass("oj-active");this.gb||0<=b.indexOf(this)&&a===this.element&&b.splice(b.indexOf(this),1)},collapse:function(a){var b=this.sj&&this.sj.closest(".oj-menu-item",this.element);b&&b.length&&(this.fm(),this.focus(a,b))},expand:function(a){var b=this.la&&this.la.children(".oj-menu ").children(".oj-menu-item").first();b&&b.length&&(this.jD(b.parent()),this._delay(function(){this.focus(a,b)}))},next:function(a){this.tq("next",
"first",a)},previous:function(a){this.tq("prev","last",a)},cW:function(){return this.la&&!this.la.prevAll(".oj-menu-item").length},eW:function(){return this.la&&!this.la.nextAll(".oj-menu-item").length},tq:function(a,b,e){var f;this.la&&(f="first"===a||"last"===a?this.la["first"===a?"prevAll":"nextAll"](".oj-menu-item").eq(-1):this.la[a+"All"](".oj-menu-item").eq(0));f&&f.length&&this.la||(f=this.sj.children(".oj-menu-item")[b]());this.focus(e,f)},select:function(b){if(!this.la&&b&&b.target){var c=
f(b.target).closest(".oj-menu-item");c.closest(this.element).length&&(this.la=c)}!this.la||this.la.has(".oj-menu").length||this.la.is(".oj-disabled")?a.T.warn("Selecting a disabled item or parent menu item is not allowed."):(c={item:this.la},this.Ds(b,!0),this.gb&&this.Gt(b),this._trigger("select",b,c))}});var b=[]})()});
//# sourceMappingURL=oj-modular.map