/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery"],function(a,f){a.N=function(b,a,c){this.Init(b,a,c)};o_("Message",a.N,a);a.N.Uf={CONFIRMATION:"confirmation",INFO:"info",WARNING:"warning",ERROR:"error",FATAL:"fatal"};o_("Message.SEVERITY_TYPE",a.N.Uf,a);a.N.kb={FATAL:5,ERROR:4,WARNING:3,INFO:2,CONFIRMATION:1};o_("Message.SEVERITY_LEVEL",a.N.kb,a);a.b.oa(a.N,a.b,"oj.Message");a.N.prototype.Init=function(b,d,c){a.N.t.Init.call(this);this.summary=b;this.detail=d;this.severity=c||a.N.Uf.ERROR};a.b.g("Message.prototype.Init",
{Init:a.N.prototype.Init});a.N.prototype.wn=function(){return!0};a.N.prototype.ni=function(b){return b&&a.N.jl(this.severity)===a.N.jl(b.severity)&&this.summary===b.summary&&this.detail===b.detail?!0:!1};a.b.g("Message.prototype.equals",{ni:a.N.prototype.ni});a.N.prototype.clone=function(){return new a.N(this.summary,this.detail,this.severity)};a.b.g("Message.prototype.clone",{clone:a.N.prototype.clone});a.N.jl=function(b){b&&("string"===typeof b?(b=a.N.ms.indexOf(b,1),b=-1===b?a.N.kb.ERROR:b):"number"===
typeof b&&b<a.N.kb.CONFIRMATION&&b>a.N.kb.FATAL&&(b=a.N.kb.ERROR));return b?b:a.N.kb.ERROR};o_("Message.getSeverityLevel",a.N.jl,a);a.N.NT=function(b){var d;b&&("string"===typeof b?(d=a.N.ms.indexOf(b,1),-1===d&&(b=a.N.Uf.ERROR)):"number"===typeof b&&(b=b<a.N.kb.CONFIRMATION&&b>a.N.kb.FATAL?a.N.Uf.ERROR:a.N.ms[b]));return b||a.N.Uf.ERROR};o_("Message.getSeverityType",a.N.NT,a);a.N.gh=function(b){var d=-1,c;b&&0<b.length&&f.each(b,function(b,g){g&&(c=a.N.jl(g.severity));d=d<c?c:d});return d};o_("Message.getMaxSeverity",
a.N.gh,a);a.N.isValid=function(b){return a.N.gh(b)>=a.N.kb.ERROR?!1:!0};o_("Message.isValid",a.N.isValid,a);a.N.ms=["none",a.N.Uf.CONFIRMATION,a.N.Uf.INFO,a.N.Uf.WARNING,a.N.Uf.ERROR,a.N.Uf.FATAL];a.Tb=function(b,a,c,e){this.Init(b,a,c,e)};a.b.oa(a.Tb,a.N,"oj.ComponentMessage");a.Tb.Kj={Tr:"immediate",Qr:"deferred"};a.Tb.HI={display:a.Tb.Kj.Tr,context:""};a.Tb.prototype.Init=function(b,d,c,e){a.Tb.t.Init.call(this,b,d,c);this.Ra=f.extend({},a.Tb.HI,e)};a.Tb.prototype.ni=function(b){return a.Tb.t.ni.call(this,
b)&&this.Ra.display===b.Ra.display};a.Tb.prototype.clone=function(){return new a.Tb(this.summary,this.detail,this.severity,this.Ra)};a.Tb.prototype.wn=function(){return!(this.Ra&&this.Ra.display&&this.Ra.display===a.Tb.Kj.Qr)};a.Tb.prototype.ZM=function(){return this.Ra&&a.Tb.Kj.Qr===this.Ra.display?(this.Ra.display=a.Tb.Kj.Tr,!0):!1}});
//# sourceMappingURL=oj-modular.map