/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery"],function(a,f){a.X=window.oj.Events={on:function(b,a,c){return this.Dg(b,a,c,!1,!1)},off:function(b,a,c){return this.bv(b,a,c,!1)},trigger:function(b){var d=Array.prototype.slice.call(arguments);d.unshift(!1);return a.X.Mb.apply(this,d)},once:function(b,a,c){return this.iD(b,a,c,!1)},listenTo:function(b,d,c){var e,g,h,k,l={};d.constructor===String?l[d]=c:l=d;for(k in l)if(l.hasOwnProperty(k))for(d=a.X.Yi(k),c=0;c<d.length;c+=1)e=d[c].event,g=d[c].Gb,h={event:e,Gb:g,object:b,
ac:l[k]},this.Xs(this.Rb,h,a.X.KC),e=g?e+":"+g:e,void 0===this.Rb&&(this.Rb=[]),this.Rb.push(h),b.Dg(e,l[k],null,!0,!1);return this},listenToOnce:function(b,d,c){var e,g,h,k,l={};d.constructor===String?l[d]=c:l=d;for(k in l)if(l.hasOwnProperty(k))for(d=a.X.Yi(k),c=0;c<d.length;c+=1)e=d[c].event,g=d[c].Gb,h={event:e,Gb:g,object:b,ac:l[k]},this.Xs(this.Rb,h,a.X.KC),e=g?e+":"+g:e,void 0===this.Rb&&(this.Rb=[]),this.Rb.push(h),b.iD(e,l[k],null,!0);return this},stopListening:function(b,d,c){var e,g={},
h,k,l,f,m,q,t,p,r;if(null==arguments||0==arguments.length){m=this.Rb?this.Rb.length:0;for(p=0;p<m;p++)q=this.Rb[p].object.bv,q.apply(this.Rb[p].object,[this.Rb[p].event,this.Rb[p].ac,this.Rb[p].context,!0]);this.Rb=[];return this}e=d;b&&b.constructor===String&&(e=b);e.constructor===String?g[e]=c:g=e;for(r in g)if(g.hasOwnProperty(r))for(e=a.X.Yi(r),h=0;h<e.length;h+=1)for(k=e[h].event,l=e[h].Gb,m=this.Rb?this.Rb.length:0,p=m-1;0<=p;p-=1)f=this.Rb[p],m=b?b===f.object:!0,q=k?k===f.event:!0,t=c?g[r]===
f.ac:!0,f=l?l===f.Gb:!0,m&&q&&t&&f&&(q=this.Rb[p].object.bv,q.apply(this.Rb[p].object,[this.Rb[p].event,this.Rb[p].ac,this.Rb[p].context,!0]),this.Rb.splice(p,1));return this}};a.X.bind=a.X.on;a.X.unbind=a.X.off;a.X.v={ADD:"add",REMOVE:"remove",RESET:"reset",REFRESH:"refresh",SORT:"sort",CHANGE:"change",DESTROY:"destroy",REQUEST:"request",SYNC:"sync",ERROR:"error",INVALID:"invalid",ALL:"all"};o_("Events.EventType",a.X.v,a);a.X.zo=function(b,a){var c,e=a||this;for(c in e)"function"===typeof e[c]&&
(b[c]=e[c]);b.bc={};b.Rb=[]};a.X.iD=function(b,a,c,e){var g,h,k,l;k=this.Pt(b,a);for(l in k)if(k.hasOwnProperty(l))for(b=this.Yi(l),a=0;a<b.length;a+=1)g=b[a].event,h=b[a].Gb,void 0===this.bc&&(this.bc=[]),void 0===this.bc[g]&&(this.bc[g]=[]),this.bc[g].push({ac:k[l],context:c,Gb:h,rh:!0,fired:!1,wi:e});return this};a.X.PE=function(b){return b.rh?b.fired?!1:b.fired=!0:!0};a.X.Mb=function(b,d){var c=this.Yi(d),e,g,h,k,l,f;k=[];for(e=0;e<c.length;e+=1)g=c[e].event,h=c[e].Gb,k.push({event:g,Gb:h});for(e=
0;e<k.length;e+=1){l=this.Pp(this.bc,a.X.v.ALL);c=a.X.Pp(this.bc,k[e].event,!1);for(g=0;g<(c?c.length:0);g+=1)c[g].Gb===k[e].Gb&&c[g].ac&&(h=Array.prototype.slice.call(arguments),c&&c[g]&&c[g].rh&&this.bE(a.X.Pp(this.bc,k[e].event,!0),c[g]),c&&c[g]&&this.PE(c[g])&&(f=c[g].ac,b&&!c[g].PG||f.apply(c[g].context||this,h.slice(2))));for(g=0;g<(l?l.length:0);g+=1)h=Array.prototype.slice.call(arguments),0<h.length&&(h[1]=k[e].Gb?k[e].event+":"+k[e].Gb:k[e].event),l&&l[g]&&l[g].ac&&this.PE(l[g])&&(f=l[g].ac,
b&&!l[g].PG||f.apply(l[g].context||this,h.slice(1))),l&&l[g]&&l[g].rh&&this.bE(this.Pp(this.bc,a.X.v.ALL,!0),l[g])}return this};a.X.Dg=function(b,d,c,e,g){var h,k,l,f;b=this.Pt(b,d);for(h in b)if(b.hasOwnProperty(h))for(d=this.Yi(h),k=0;k<d.length;k+=1)l=d[k].event,f=d[k].Gb,void 0===this.bc&&(this.bc=[]),void 0===this.bc[l]&&(this.bc[l]=[]),f={ac:b[h],context:c,Gb:f,wi:e,PG:g},-1===this.Xs(this.bc[l],f,a.X.SO)&&this.bc[l].push(f);return this};a.X.bv=function(b,a,c,e){var g,h;if(null==arguments||
0==arguments.length)return this.bc={},this;if(null==b)return this.aE(b,a,c,e),this;g=this.Pt(b,a);for(h in g)g.hasOwnProperty(h)&&this.aE(h,g[h],c,e);return this};a.X.Pt=function(b,a){var c={};b.constructor===String?c[b]=a:c=b;return c};a.X.aE=function(b,d,c,e){var g=[],h,k,l,f,m,q,t,p;if(b)g=a.X.Yi(b);else if(void 0!==this.bc)for(k in this.bc)this.bc.hasOwnProperty(k)&&g.push({event:k});for(b=0;b<g.length;b+=1)if(k=g[b].event,l=g[b].Gb,void 0!==this.bc&&this.bc[k]instanceof Array){f=this.bc[k];for(h=
f.length-1;0<=h;h-=1)m=void 0===d||null===d||f[h].ac==d,q=void 0===c||null===c||f[h].context==c,t=void 0===l||null===l||f[h].Gb==l,p=void 0===e||null===e||f[h].wi==e,m&&q&&t&&p&&f.splice(h,1);0===f.length&&delete this.bc[k]}};a.X.bE=function(b,a){var c,e,g,h,k,l;for(c=b.length-1;0<=c;c-=1)e=void 0===a.ac||null===a.ac||b[c].ac==a.ac,g=void 0===a.context||null===a.context||b[c].context==a.context,h=void 0===a.Gb||null===a.Gb||b[c].Gb==a.Gb,k=void 0===a.wi||null===a.wi||b[c].wi==a.wi,l=void 0===a.rh||
null===a.rh||b[c].rh==a.rh,e&&g&&h&&k&&l&&b.splice(c,1)};a.X.Yi=function(b){b=b?b.split(" "):[];var a=[],c,e,g;for(c=0;c<b.length;c+=1)e=b[c].split(":"),g=e[0],e=1<e.length?e[1]:null,a.push({event:g,Gb:e});return a};a.X.SO=function(b,a){return b.ac===a.ac&&b.Gb===a.Gb&&b.context===a.context&&b.wi===a.wi&&b.rh===a.rh};a.X.KC=function(b,a){return b.event===a.event&&b.Gb===a.Gb&&b.context===a.context&&b.object===a.object};a.X.Xs=function(b,a,c){var e;if(void 0===b)return-1;for(e=0;e<b.length;e+=1)if(c(b[e],
a))return e;return-1};a.X.Pp=function(b,a,c){if(b&&b[a]instanceof Array){if(c)return b[a];c=[];var e;for(e=0;e<b[a].length;e++)c.push(b[a][e]);return c}return null};a.q=function(b,d){a.q._init(this,b,d,null)};o_("Model",a.q,a);a.b.oa(a.q,a.b,"Model.Model");a.q.prototype.Init=function(){a.q.t.Init.call(this)};a.q.prototype.attributes={};a.b.g("Model.prototype.attributes",{attributes:a.q.prototype.attributes});a.q.prototype.pc={};a.b.g("Model.prototype.defaults",{pc:a.q.prototype.pc});a.q.prototype.id=
null;a.b.g("Model.prototype.id",{id:a.q.prototype.id});a.q.prototype.He=null;a.b.g("Model.prototype.idAttribute",{He:a.q.prototype.He});a.q.prototype.TH=null;a.b.g("Model.prototype.urlRoot",{TH:a.q.prototype.TH});a.q.prototype.Ff=null;a.b.g("Model.prototype.customURL",{Ff:a.q.prototype.Ff});a.q.Du=0;a.q._init=function(b,d,c,e){var g=null,h;if(!a.q.Nm){b.Init();a.X.zo(b);b.ak();b.Br={};b.xr=!1;b.index=-1;c=c||{};b.attributes={};b.defaults&&(b.attributes=a.q.Og(a.q.ad(b.defaults)?b.defaults():b.defaults,
null));for(g in e)e.hasOwnProperty(g)&&(b[g]=e[g]);if(d)if(e=c.parse,a.q.ad(e)&&(b.parse=e),h=a.q.Og(d,b.attributes),h=e?b.parse(h):h,null==h||void 0===h)b.attributes={};else for(g in h)h.hasOwnProperty(g)&&b.Sk(g,h[g],!1,!1,c);b.Bo();b.Il(c.collection);c.customURL&&(b.customURL=c.customURL);c.url&&(b.url=c.url);c.urlRoot&&(b.urlRoot=c.urlRoot);b.initialize&&b.initialize(d,c);b.Fg()}};a.q.extend=function(b,d){a.q.Nm=!0;var c,e;c=new a.q;a.q.Nm=!1;a.X.zo(c,this.prototype);b=b||{};for(e in b)b.hasOwnProperty(e)&&
(c[e]=b[e]);var g;g=b&&b.constructor&&b.hasOwnProperty("constructor")?b.constructor:function(d,c){a.q._init(this,d,c,b)};g.prototype=c;g.extend=a.q.extend;g.prototype.constructor=g;a.X.zo(g,this);if(d)for(e in d)d.hasOwnProperty(e)&&(g[e]=d[e]);return g};o_("Model.extend",a.q.extend,a);a.q.prototype.Mb=function(){};a.q.prototype.Bo=function(){this.Lj()||(this.cid="id"+a.q.Du,a.q.Du+=1)};a.q.prototype.Lj=function(){return this.cid};a.q.prototype.Vr=function(b){this.index=b};a.q.prototype.Wr=function(b){this.uU=
b};a.q.prototype.Co=function(b){var a=this.kx;this.kx=b;return a};a.q.prototype.lI=function(b,d,c){var e,g=!1,h=a.fb.Fd(d),k,l=!1;for(e in b.attributes)b.attributes.hasOwnProperty(e)&&(k=this.attributes[e]!=b.attributes[e],h?e===d&&k&&(g=!0):k&&(g=!0),k&&(l=!0,this.attributes[e]=b.attributes[e],this.Is(e,b.attributes[e]),this.Fp(e,this.attributes[e],null,c)));this.Fg();l&&this.Gp(null,c);return g};a.q.cj=function(b){var a;if(b&&b instanceof Object)for(a in b)if(b.hasOwnProperty(a))return!0;return!1};
a.q.prototype.Il=function(b){null==b?delete this.collection:this.collection=b};a.q.prototype.xo=function(){return this.collection};a.q.prototype.Fp=function(b,d,c,e){null!=b&&this.Mb(e,a.X.v.CHANGE+":"+b,this,d,c)};a.q.prototype.Gp=function(b,d){this.Mb(d,a.X.v.CHANGE,this,b,null)};a.q.prototype.Fg=function(){this.id=this.attributes[this.Ut()]};a.q.prototype.Gv=function(b,d,c){var e=a.b.Ni(this.attributes[b],d);return c||!e?(this.attributes[b]=d,this.Fg(),!e):!1};a.q.prototype.ak=function(){this.changed=
{}};a.q.prototype.Is=function(b,a){this.changed[b]=a};a.q.prototype.Sk=function(b,d,c,e,g){if(null==b)return!0;var h={},k,l=this.xr;g=a.q.rp(g);if(e)for(k in b)b.hasOwnProperty(k)&&(h[k]=b[k]);else h[b]=d;g=g||{};if(!this.dm(h,{validate:g.validate},!1))return!1;l||(this.ak(),this.mw=[]);this.xr||(this.Br=a.q.Og(this.attributes,null));this.xr=!0;for(k in h)h.hasOwnProperty(k)&&(this.Gv(k,h[k],c)?(this.Is(k,h[k]),this.mw.push(k)):delete h[k]);b=g.silent;for(k in h)h.hasOwnProperty(k)&&(!b&&(0<this.mw.length||
l&&-1===this.mw.indexOf(k))&&(this.lH=!0),this.Fp(k,h[k],g,b));if(l)return!0;if(!b&&!l)for(;this.lH;)this.lH=!1,this.Gp(g,b);this.xr=!1;return!0};a.q.prototype.clear=function(b){var d,c={silent:!0},e;b=b||{};e=b.silent;c.validate=b.validate;this.ak();for(d in this.attributes)if(this.attributes.hasOwnProperty(d)){if(!this.Qq(d,c,!0))return!1;this.Mb(e,a.X.v.CHANGE+":"+d,this,void 0,null)}this.attributes={};this.Fg();this.Fp(null,null,null,e);this.Gp(null,e);return this};a.b.g("Model.prototype.clear",
{clear:a.q.prototype.clear});a.q.Og=function(b,d){var c;if(null===b)return null;d=d||{};var e=!1;for(c in b)if(e=!0,b.hasOwnProperty(c))if("object"!==typeof b[c])d.hasOwnProperty(c)?void 0!==b[c]&&(d[c]=b[c]):d[c]=b[c];else if(a.q.El(b[c]))if(null===b[c])d[c]=null;else if(d[c]=[],0===b[c].length)d[c]=b[c];else for(var g=0;g<b[c].length;g++)d[c].push(a.q.Og(b[c][g],null));else d[c]=a.q.Og(b[c],null);return e||"object"===typeof b?d:b};a.q.prototype.clone=function(){var b=new this.constructor,d;for(d in this)this.hasOwnProperty(d)&&
this[d]!==this.attributes&&(b[d]=this[d]);b.attributes=a.q.Og(this.attributes,null);delete b.cid;b.Bo();b.Fg();return b};a.b.g("Model.prototype.clone",{clone:a.q.prototype.clone});a.q.prototype.Nj=function(b,a){var c=this.re();if(void 0!==c&&c==b)return!0;c=this.cid;return void 0!==c&&c==a?!0:!1};a.q.prototype.set=function(b,d,c){var e={},g=!1,h,k=!0;if(arguments&&0<arguments.length)if(1<arguments.length&&arguments[arguments.length-1]&&(g=!0,e=arguments[arguments.length-1]||{}),a.q.cj(b))if(e.unset)for(h in b)b.hasOwnProperty(h)&&
this.Qq(h,null,!1);else this.Sk(b,null,!0,!0,e)||(k=!1);else for(h=0;h<arguments.length;h+=2)if(void 0!==arguments[h]||h<arguments.length-1||!g&&h===arguments.length-1)e.unset?this.Qq(arguments[h],null,!1):this.Sk(arguments[h],arguments[h+1],!1,!1,e)||(k=!1);return k?this:!1};a.b.g("Model.prototype.set",{set:a.q.prototype.set});a.q.prototype.RH=function(b,a){return this.Qq(b,a,!1)};a.b.g("Model.prototype.unset",{RH:a.q.prototype.RH});a.q.prototype.Qq=function(b,a,c){a=a||{};var e=a.silent,g={};if(this.has(b)){if(!this.dm(g,
a,!1))return!1;c||this.ak();delete this.attributes[b];this.Is(b,void 0);this.Fp(b,null,null,e);this.Gp(null,e)}this.Fg();return!0};a.q.prototype.get=function(b){return this.attributes[b]};a.b.g("Model.prototype.get",{get:a.q.prototype.get});a.q.prototype.has=function(b){return void 0!==this.attributes[b]&&null!==this.attributes[b]};a.b.g("Model.prototype.has",{has:a.q.prototype.has});a.q.prototype.fetch=function(b){b=b||{};var d=b.success,c=b.error,e=this,g;g=a.q.rp(b);g.error=function(d,g,l){e.Mb(!1,
a.X.v.ERROR,e,d,b);c&&c.call(e,arguments)};g.success=function(c){a.q.Hp(e,c,g);a.q.ad(this.parse)&&this.set(this.parse(c),g);d&&d.call(e,this,c,b)};a.q.Lm("read",this,g)};a.b.g("Model.prototype.fetch",{fetch:a.q.prototype.fetch});a.q.prototype.parse=function(b){return b};a.q.prototype.url=function(){var b=this.YB(),d=this.re();if(b)return d?b+"/"+encodeURIComponent(d):b;if(b=this.collection)return b=a.q.ad(b.url)?b.url():b.url,d&&b?(d="/"==a.q.zN(b)?"":"/",b+d+encodeURIComponent(this.re())):b;throw"No URL defined";
};a.b.g("Model.prototype.url",{url:a.q.prototype.url});a.q.prototype.keys=function(){var b,a=[];for(b in this.attributes)this.attributes.hasOwnProperty(b)&&a.push(b);return a};a.b.g("Model.prototype.keys",{keys:a.q.prototype.keys});a.q.prototype.values=function(){var b,a=[];for(b in this.attributes)this.attributes.hasOwnProperty(b)&&a.push(this.get(b));return a};a.b.g("Model.prototype.values",{values:a.q.prototype.values});a.q.prototype.pairs=function(){var b,a=[],c;for(b in this.attributes)this.attributes.hasOwnProperty(b)&&
(c=[],c.push(b),c.push(this.get(b)),a.push(c));return a};a.b.g("Model.prototype.pairs",{pairs:a.q.prototype.pairs});a.q.prototype.kH=function(b){var a=[],c,e,g={};if(b instanceof Array)a=b;else if(arguments)for(c=0;c<arguments.length;c++)a.push(arguments[c]);else return this.pairs();for(e in this.attributes)this.attributes.hasOwnProperty(e)&&-1==a.indexOf(e)&&(g[e]=this.get(e));return g};a.b.g("Model.prototype.omit",{kH:a.q.prototype.kH});a.q.prototype.mH=function(b){var a=[],c,e={};if(b instanceof
Array)a=b;else if(arguments)for(c=0;c<arguments.length;c++)a.push(arguments[c]);else return this.pairs();for(c=0;c<a.length;c++)this.attributes.hasOwnProperty(a[c])&&(e[a[c]]=this.get(a[c]));return e};a.b.g("Model.prototype.pick",{mH:a.q.prototype.mH});a.q.prototype.TG=function(){var b,a={},c;for(b in this.attributes)this.attributes.hasOwnProperty(b)&&(c=this.get(b),a[c]=b);return a};a.b.g("Model.prototype.invert",{TG:a.q.prototype.TG});a.q.zN=function(b){return b.charAt(b.length-1)};a.q.prototype.tR=
function(){var b=this.YB();return b?b:this.xo()?this.xo().url:null};a.q.prototype.YB=function(){return a.q.ad(this.urlRoot)?this.urlRoot():this.urlRoot};a.q.prototype.parseSave=function(b){return b};a.q.prototype.isValid=function(){var b={};b.validate=this.validate;return this.dm(this.attributes,b,!1)};a.b.g("Model.prototype.isValid",{isValid:a.q.prototype.isValid});a.q.yP=function(b,a){b=b||{};return void 0!==b.validate&&null!==b.validate?b.validate:a};a.q.prototype.dm=function(b,d,c){var e=this.validate;
return e&&a.q.yP(d,c)&&(this.validationError=e.call(this,b,d))?(this.Mb(!1,a.X.v.INVALID,this,this.validationError,d),!1):!0};a.q.yQ=function(b){var d=!1,c={},e,g={};if(b&&0<b.length){1<b.length&&b[b.length-1]&&a.q.cj(b[b.length-1])&&(d=!0,c=b[b.length-1]||{});if(null==b[0])return{attributes:null,options:c};if(a.q.cj(b[0]))for(e in b[0])b[0].hasOwnProperty(e)&&(g[e]=b[0][e]);else for(e=0;e<b.length;e+=2)if(void 0!==b[e]||e<b.length-1||!d&&e===b.length-1)g[b[e]]=b[e+1]}return{attributes:g,options:c}};
a.q.rp=function(b){var a={},c;b=b||{};for(c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a};a.q.prototype.save=function(b,d){var c,e,g,h,k,l;c=a.q.yQ(arguments);var f,m,q;q=void 0===b?void 0:c.attributes;f=a.q.rp(c.options);f.wait||this.set(q);if(!this.dm(this.attributes,f,!0))return!1;c=void 0===f.forceNew?!1:f.forceNew;h=this;k=f.error;l=f.patch;f.error=function(b,c,e){h.Mb(!1,a.X.v.ERROR,h,b,d);k&&k.call(h,arguments)};f.saveAttrs=f.wait?this.PK(q):this.attributes;m=this.attributes;this.attributes=
f.saveAttrs;f.saveAttrs=this.toJSON();this.attributes=m;if(!c&&!this.rr())return e=f.success,f.success=function(b){var c;b&&(c=a.q.ad(this.parse)?this.parse(b):b,h.attributes=c,h.Fg());a.q.Hp(h,b,f);e&&e.call(a.q.Sf(f,h),h,b,d);h.ak()},f.attrs=void 0===q?void 0:l?q:f.saveAttrs,a.q.Lm(l?"patch":"update",this,f);g=a.q.SB(f);f.success=function(b){var c;if(b){c=a.q.ad(h.parse)?h.parse(b):b;if(!h.dm(c,f,!0))return;h.attributes=c;h.Fg()}f.wait&&h.set(q);a.q.Hp(h,b,f);g&&g.call(a.q.Sf(f,h),h,b,d);h.ak()};
f.attrs=f.saveAttrs;f.parse=!0;return a.q.Lm("create",this,f)};a.b.g("Model.prototype.save",{save:a.q.prototype.save});a.q.prototype.PK=function(b){var a={},c;for(c in this.attributes)this.attributes.hasOwnProperty(c)&&(a[c]=this.attributes[c]);for(c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a};a.q.El=function(b){return null!=b&&b.constructor===Array};a.q.ad=function(b){return b instanceof Function};a.q.Qx=function(b){return b&&b.hasOwnProperty("value")&&b.hasOwnProperty("comparator")};a.q.prototype.UO=
function(b){for(var d in b)if(b.hasOwnProperty(d)){if(!this.attributes.hasOwnProperty(d))return!1;for(var c=a.q.El(b[d])?b[d]:[b[d]],e=0;e<c.length;e++)if(a.q.Qx(c[e])){var g=c[e].comparator,h=c[e].value;if(a.fb.Fd(g))throw Error("String comparator invalid for local where/findWhere");if(!g(this,d,h))return!1}else if(b[d]!==this.attributes[d])return!1}return!0};a.q.prototype.aI=function(b){b=b.constructor===Array?b:[b];var a;for(a=0;a<b.length;a++)if(this.UO(b[a]))return!0;return!1};a.q.SB=function(b){return null!=
b&&b.success?b.success:null};a.q.Sf=function(b,a){return void 0!==b&&void 0!==b.context?b.context:a};a.q.prototype.rr=function(){return void 0==this.re()};a.b.g("Model.prototype.isNew",{rr:a.q.prototype.rr});a.q.prototype.Ut=function(){return this.idAttribute||"id"};a.q.prototype.re=function(){return this.id};a.q.prototype.lw=function(b){if(b){var d={},c;for(c in b)b.hasOwnProperty(c)&&(a.b.Ni(b[c],this.attributes[c])||(d[c]=b[c]));return a.b.isEmpty(d)?!1:d}return a.b.isEmpty(this.changed)?!1:this.changed};
a.b.g("Model.prototype.changedAttributes",{lw:a.q.prototype.lw});a.q.prototype.Nw=function(b){return void 0!==b?a.q.cj(this.changed)&&this.changed.hasOwnProperty(b):a.q.cj(this.changed)};a.b.g("Model.prototype.hasChanged",{Nw:a.q.prototype.Nw});a.q.prototype.destroy=function(b){b=b||{};var d=b.wait,c,e=b.error,g=this,h,f;f=a.q.rp(b);c=a.q.SB(f);f.success=function(e){d&&g.Et();a.q.Hp(g,e,f);c&&c.call(a.q.Sf(f,g),g,e,b)};f.error=function(b,d,c){g.Mb(!1,a.X.v.ERROR,g,b,f);e&&e.call(g,arguments)};if(!this.rr())return h=
a.q.Lm("delete",this,f),d||this.Et(),h;d||this.Et();c&&c.call(a.q.Sf(f,g),g,null,b);return!1};a.b.g("Model.prototype.destroy",{destroy:a.q.prototype.destroy});a.q.prototype.Et=function(){this.Mb(!1,a.X.v.DESTROY,this,this.collection,null)};a.q.Hp=function(b,d,c){b.Mb(!1,a.X.v.SYNC,b,d,c)};a.q.prototype.toJSON=function(){var b={},a;for(a in this.attributes)this.attributes.hasOwnProperty(a)&&(Array.isArray(this.attributes[a])?b[a]=this.attributes[a].slice(0):b[a]=this.attributes[a]);return b};a.b.g("Model.prototype.toJSON",
{toJSON:a.q.prototype.toJSON});a.q.prototype.previous=function(b){return this.Br[b]};a.b.g("Model.prototype.previous",{previous:a.q.prototype.previous});a.q.prototype.rH=function(){return this.Br};a.b.g("Model.prototype.previousAttributes",{rH:a.q.prototype.rH});a.q.prototype.sH=function(){return this.Br};a.b.g("Model.prototype.previousChanges",{sH:a.q.prototype.sH});a.q.prototype.sync=function(b,a,c){return window.oj.sync(b,a,c)};a.q.Lm=function(b,a,c){c=c||{};a.oauth&&(c.oauthHeader=a.oauth.getHeader());
!c.dataType&&a.dataType&&(c.dataType=a.dataType);!c.jsonpCallback&&a.jsonpCallback&&(c.jsonpCallback=a.jsonpCallback);if("create"===b||"patch"===b||"update"===b)c.jx=a.parseSave.call(a,"patch"===b?a.changed:c.saveAttrs);return a.sync(b,a,c)};a.cV=function(b,d,c){c=c||{};var e,g=c.success,h=c.error;e=d.customURL;if("create"===b.valueOf())return e=new a.Ab(d.tR(),e),e.JS(c.jx,h,c,d);if("read"===b.valueOf()){if(d instanceof a.q)return e=new a.Ab(d.url(),e),e.JT(g,h,d.re(),c,a.q.Sf(c,d));e=new a.Ab(d.fI(c),
e);return e.KT(g,h,c,d)}e=new a.Ab(d.url(),e);var f=null;d instanceof a.q&&(f=d.re());return"update"===b.valueOf()?e.SH(g,f,c.jx,h,c,d,!1):"patch"===b.valueOf()?e.SH(g,f,c.jx,h,c,d,!0):"delete"===b.valueOf()?e.sT(f,h,c,d):null};o_("sync",a.cV,a);a.q.zS=function(b){if(!b.url)throw Error("The url property or function must be specified");};a.ajax=function(){arguments&&0<arguments.length&&a.q.zS(arguments[0]);return f.ajax.apply(window.oj,arguments)};a.j=function(b,d){a.j.Nm||a.j._init(this,b,d,null)};
o_("Collection",a.j,a);a.j.prototype.Id=null;a.b.g("Collection.prototype.model",{Id:a.j.prototype.Id});a.j.prototype.length=0;a.b.g("Collection.prototype.length",{length:a.j.prototype.length});a.j.prototype.hH=[];a.b.g("Collection.prototype.models",{hH:a.j.prototype.hH});a.j.prototype.url=null;a.b.g("Collection.prototype.url",{url:a.j.prototype.url});a.j.prototype.Ff=function(){return null};a.b.g("Collection.prototype.customURL",{Ff:a.j.prototype.Ff});a.j.prototype.VF=function(){return null};a.b.g("Collection.prototype.customPagingOptions",
{VF:a.j.prototype.VF});a.j.prototype.cH=0;a.b.g("Collection.prototype.lastFetchSize",{cH:a.j.prototype.cH});a.j.prototype.hasMore=!1;a.b.g("Collection.prototype.hasMore",{hasMore:a.j.prototype.hasMore});a.j.prototype.NH=0;a.b.g("Collection.prototype.totalResults",{NH:a.j.prototype.NH});a.j.prototype.bH=0;a.b.g("Collection.prototype.lastFetchCount",{bH:a.j.prototype.bH});a.j.prototype.gH=-1;a.b.g("Collection.prototype.modelLimit",{gH:a.j.prototype.gH});a.j.prototype.offset=0;a.b.g("Collection.prototype.offset",
{offset:a.j.prototype.offset});a.j.prototype.yw=-1;a.b.g("Collection.prototype.fetchSize",{yw:a.j.prototype.yw});a.j.prototype.yx=1;a.b.g("Collection.prototype.sortDirection",{yx:a.j.prototype.yx});a.j.prototype.af=null;a.b.g("Collection.prototype.comparator",{af:a.j.prototype.af});a.j.prototype.Mf=!0;a.b.g("Collection.prototype.sortSupported",{Mf:a.j.prototype.Mf});a.b.oa(a.j,a.b,"Collection.Collection");a.j.prototype.Init=function(){a.j.t.Init.call(this)};a.j.extend=function(b){a.j.Nm=!0;var d=
new a.j;a.j.Nm=!1;var c;c=b&&b.constructor&&b.hasOwnProperty("constructor")?b.constructor:function(d,c){a.j._init(this,d,c,b)};c.prototype=d;return c.prototype.constructor=c};o_("Collection.extend",a.j.extend,a);a.j._init=function(b,d,c,e){var g,h;b.Init();a.X.zo(b);if(e)for(g in e)e.hasOwnProperty(g)&&(b[g]=e[g]);c=c||{};h=["url","comparator","model",a.j.fd,"modelLimit","customURL"];for(g=0;g<h.length;g++)c.hasOwnProperty(h[g])&&void 0!==c[h[g]]&&(b[h[g]]=c[h[g]]);void 0===b.wm(null)&&b.Fr(-1);void 0===
b.modelLimit&&b.vx(-1);b.hasMore=!1;b.hf=0;b.mj([]);c.parse&&(d=b.parse(d));if(null!=d&&void 0!==d)for(h=d instanceof Array?d:[d],g=0;g<h.length;g+=1)b.add(h[g],c);b.bi();e&&e.initialize&&e.initialize.call(b,d,c)};a.j.prototype.on=function(){};a.j.prototype.Dg=function(){};a.j.prototype.Mb=function(){};a.j.prototype.mj=function(b){this.models=b};a.j.prototype.wb=function(){return this.models};a.j.prototype.jd=function(){return this.wb().length};a.j.prototype.jQ=function(b){return b<this.jd()||this.Va()&&
(!this.vk()||0===this.jd())?!1:!0};a.j.prototype.vk=function(){return void 0!==this.totalResults&&null!=this.totalResults};a.j.prototype.GQ=function(b){this.Tu(b);this.wb().push(b);this.hf++;b.Vr(this.jd()-1)};a.j.prototype.GD=function(b){if(b)for(var a=0;a<b.length;a++)b[a]&&this.hf--};a.j.prototype.$E=function(b,a,c){for(var e=b;e<b+a;e++)this.eE(this.wb()[e]);void 0===c?this.GD(this.wb().splice(b,a)):(this.GD(this.wb().splice(b,a,c)),this.Tu(c));0>this.hf&&(this.hf=0);this.FD(b)};a.j.prototype.Ob=
function(b){return this.wb()[b]};a.j.prototype.FD=function(b){this.wb().forEach(function(a,c){c>=b&&a&&a.Vr(c)})};a.j.prototype.eE=function(b){if(b){var a=b.kx;b=b.uU;a?a.Wr(b):this.head=b;b?b.Co(a):this.tail=a}};a.j.prototype.Tu=function(b){b.Wr(this.head);this.head?this.head.Co(b):this.tail=b;b.Co(null);this.head=b};a.j.prototype.NR=function(b,a){var c=this.wb()[b];this.eE(c);c||this.hf++;this.wb()[b]=a;a.Vr(b);this.Tu(a)};a.j.prototype.qL=function(b){var a=this.tail,c,e,g=0;for(this.tail=null;a&&
g<b;)c=a.index,(e=this.wb()[c])&&e.Nw()?(this.tail||(this.tail=a),a=a.kx):(this.hf--,-1<c&&(this.wb()[c]=void 0),a.Wr(null),a=a.Co(null),g++);this.tail||(this.tail=a);0>this.hf&&(this.hf=0);0===this.hf&&(this.tail=this.head=null)};a.j.prototype.gn=function(){this.hf=0;this.tail=this.head=null};a.j.prototype.Vh=function(b){if(this.Va()){var a=this.FB();-1<a&&this.hf+b>a&&this.qL(this.hf+b-a)}};a.j.prototype.clone=function(){return this.iA(!0)};a.b.g("Collection.prototype.clone",{clone:a.j.prototype.clone});
a.j.prototype.iA=function(b){var a=new this.constructor,c;this.Va()&&(a=this.CL(a),a.iE());if(b)for(b=0;b<this.Qc();b+=1)(c=this.Ch(b,null,!0,!1))&&a.Lg(c.clone(),{at:b},!0,!1);return a};a.j.prototype.CL=function(b){var d=["totalResults","hasMore",a.j.fd],c,e;for(e=0;e<d.length;e++)c=d[e],b[c]=this[c];return b};a.j.prototype.Qc=function(){return this.length};a.j.prototype.bi=function(){var b=this.jd();this.length=b;this.Va()||(this.totalResults=b)};a.j.prototype.Wm=function(b,d,c){var e=null;c=c||
{};c.GW=!d;e=b instanceof a.q?b:this.model?a.q.ad(this.model)?new this.model(b,c):new this.model.constructor(b,c):new a.q(b,c);return c.validate&&e.validate&&(b=e.validate(e.attributes))?(c.validationError=b,this.Mb(!1,a.X.v.INVALID,this,b,c),null):e};a.j.prototype.add=function(b,a){this.Vh(1);return this.Lg(b,a,!1,(a||{}).deferred)};a.b.g("Collection.prototype.add",{add:a.j.prototype.add});a.j.prototype.Lg=function(b,d,c,e){function g(b,e,g,h,f){var k,w=null;!m&&p&&g?(s=g.lI(e,b.comparator,n),w=
g):(m||(k=b.DB(h))&&c&&l!==k.index&&a.T.warn("Duplicate ID fetched or added without merging, the id \x3d "+k.re()),void 0===k?(void 0===l?(b.GQ(h),q=b.jd()-1,b.Ob(q).Bo()):(q=l,b.Va()&&c?b.NR(q,h):b.$E(q,0,h),b.Ob(q).Bo(),l+=1),void 0===h.xo()&&h.Il(b),b.bi(),b.EP(h),u=!0,w=h):w=k);c&&(d=d||{},d.fillIn=!0);s&&void 0===k&&!r&&void 0===l&&1<b.Qc()&&(-1<q&&(t=b.Ob(q).cid),e={},a.Ec.dh(e,d),e.add=!0,b.sort(e),-1<q&&(q=b.indexOf(b.Bw(t),f)));u&&(h?h.Mb(n,a.X.v.ADD,h,b,d):g.Mb(n,a.X.v.ADD,g,b,d));return w}
function h(b,e,h){var l=b.Wm(e,!0,d),f=null,k=null;if(null!=l){q=-1;l.Fg();f=e instanceof a.q?e:l;if(h)return m?(g(b,f,void 0,l,h),a.j.Zb().resolve()):b.Zi(f,null,h,!0).done(function(a){k=a.m;a=g(b,f,k,l,h);v.push(a)});!m&&p&&(k=c?b.DB(f):b.get(f));(e=g(b,f,k,l,h))&&v.push(e)}}d=d||{};var k=[],l=d.at,n=d.silent,m=d.force,q,t,p=d.merge||!1,r=d.sort,s=!0,u=!1,v=[];b instanceof Array?k=b:k.push(b);if(!c&&(this.Va()||e)){var w=this,x=function(b){var d=a.j.Zb();h(w,k[b],!0).done(function(){d.resolve(b)});
return d.promise()};e=x(0);var E=function(b){return x(b+1)};for(b=1;b<k.length;b++)e=e.then(E);var A=a.j.Zb();f.when(e).done(function(){A.resolve(a.j.oE(v))});return A.promise()}for(b=0;b<k.length;b++)h(this,k[b],!1);return a.j.oE(v)};a.j.oE=function(b){return 1===b.length?b[0]:b};a.j.prototype.zu=function(){var b=this.comparator;return void 0!==b&&null!==b};a.j.prototype.sort=function(b){b=b||{};var d=b.silent,c=this.comparator,e;this.zu()&&(this.Va()&&this.WO()?(b=this.totalResults,void 0!==b?this.mj(Array(b)):
(this.mj([]),this.gn(),this.bi())):(e=this,this.wb().sort(function(b,d){return a.j.Yr(b,d,c,e,e)}),this.FD(0),this.Mb(d,a.X.v.SORT,this,b.add?{add:!0}:null,null)))};a.b.g("Collection.prototype.sort",{sort:a.j.prototype.sort});a.j.zm=function(b,d){return b instanceof a.q?b.get(d):a.q.ad(b[d])?b[d]():b[d]};a.j.Yr=function(b,d,c,e,g){var h,f,l;if(a.q.ad(c)){if(1===c.length){h=c.call(g,b);f=c.call(g,d);h=a.fb.Fd(h)?h.split(","):[h];var n=a.fb.Fd(f)?f.split(","):[f];for(l=0;l<h.length;l++)if(f=a.j.Pg(h[l],
n[l],e.sortDirection),0!==f)return f}return c.call(g,b,d)}if(a.fb.Fd(c))for(c=c.split(","),l=0;l<c.length;l++)if(h=a.j.zm(b,c[l]),f=a.j.zm(d,c[l]),f=a.j.Pg(h,f,e.sortDirection),0!==f)return f;return 0};a.j.prototype.EH=function(b,d){var c=d?d:this.comparator,e;if(!c)return-1;this.ze("sortedIndex");e=this;return a.j.SM(this.wb(),b,function(b,d){var f,l;if(a.q.ad(c)){if(1===c.length){f=c.call(e,b);l=c.call(e,d);f=a.fb.Fd(f)?f.split(","):[f];l=a.fb.Fd(l)?l.split(","):[l];var n,m;for(m=0;m<f.length;m++)if(n=
a.j.Pg(f[m],l[m],e.sortDirection),0!==n)return n}return c.call(e,b,d)}return a.fb.Fd(c)?(f=b.get(c),l=d.get(c),a.j.Pg(f,l,e.sortDirection)):0})};a.b.g("Collection.prototype.sortedIndex",{EH:a.j.prototype.EH});a.j.SM=function(b,a,c){function e(g,h){var f,l;if(g>h)return-1;f=a.Lj();l=a.re();if(b[g].Nj(l,f))return g;if(b[h].Nj(l,f))return h;f=Math.floor((h+g)/2);return-1===c(b[f],a)?e(g+1,f):1===c(b[f],a)?e(f,h-1):f}return e(0,b.length-1)};a.j.Pg=function(b,a,c){if(-1===c){if(b<a)return 1;if(a<b)return-1}else{if(b>
a)return 1;if(a>b)return-1}return 0};a.j.prototype.unshift=function(b,d){var c={};a.Ec.dh(c,d||{});c.at||(c.at=0);this.Vh(1);return this.Lg(b,c,!1,c.deferred)};a.b.g("Collection.prototype.unshift",{unshift:a.j.prototype.unshift});a.j.prototype.shift=function(b){var a=this.Nd(b);if(this.Va()||a){var c=this;return this.at(0,b).then(function(a){return c.Zh(a,0,b)})}return this.Zh(this.at(0),0,b)};a.b.g("Collection.prototype.shift",{shift:a.j.prototype.shift});a.j.prototype.QG=function(b){void 0===b&&
(b=1);var a=[],c;for(c=0;c<this.Qc()-b;c+=1)a.push(this.at(c));return a};a.b.g("Collection.prototype.initial",{QG:a.j.prototype.QG});a.j.prototype.Nd=function(b){return(b||{}).deferred};a.j.prototype.last=function(b,a){var c=this.Nd(a);void 0===b&&(b=1);if(1===b){var e=this.jd();0===e&&(e=b);return 0<e?this.at(e-1,c):null}var g=[],e=this.Qc();if(c||this.Va())return g=e-b,0>g&&(g=0),0===e&&(e=b),this.Fl(g,e);for(c=e-b;c<e;c+=1)g.push(this.at(c));return g};a.b.g("Collection.prototype.last",{last:a.j.prototype.last});
a.j.prototype.Fl=function(b,d){function c(b){return e(b+1)}function e(b){var d=a.j.Zb();k.rt(b,null).done(function(a){g.push(a);d.resolve(b)});return d.promise()}var g=[],h,k=this,l=e(b);for(h=b+1;h<d;h++)l=l.then(c);return f.when(l).then(function(){return g})};a.j.prototype.tB=function(b){return void 0===b||null===b?this[a.j.fd]:b};a.j.prototype.hL=function(){var b=this.lastFetchCount;if(void 0===b||null===b)b=this[a.j.fd];return void 0===this.offset||null===this.offset?b:this.offset+b};a.j.prototype.next=
function(b,d){d=d||{};d[a.j.fd]=this.tB(b);var c=this.hL(),e=this.Qc();if(0===e&&0<d[a.j.fd])c=0;else if(c>=e)return d.success&&d.success.call(a.q.Sf(d,this),this,null,d),null;d.startIndex=c;return this.fetch(d)};a.b.g("Collection.prototype.next",{next:a.j.prototype.next});a.j.prototype.iL=function(b){return void 0===this.offset||null===this.offset?0:this.offset-b};a.j.prototype.previous=function(b,d){d=d||{};if(0===this.offset)return d.success&&this.lastFetchCount&&d.success.call(a.q.Sf(d,this),
this,null,d),null;d[a.j.fd]=this.tB(b);var c=this.iL(d[a.j.fd]);0>c&&(d[a.j.fd]=this.offset,c=0);d.startIndex=c;return this.fetch(d)};a.b.g("Collection.prototype.previous",{previous:a.j.prototype.previous});a.j.prototype.vx=function(b){this.modelLimit=b;this.Vh(0)};a.b.g("Collection.prototype.setModelLimit",{vx:a.j.prototype.vx});a.j.prototype.FB=function(){return this.modelLimit};a.j.prototype.Fr=function(b){this[a.j.fd]=b};a.b.g("Collection.prototype.setFetchSize",{Fr:a.j.prototype.Fr});a.j.prototype.wH=
function(b,a){var c=this.Nd(a);void 0===b&&(b=1);var e=[];if(this.Va()||c)return this.Fl(b,this.Qc());for(c=b;c<this.Qc();c+=1)e.push(this.at(c));return e};a.b.g("Collection.prototype.rest",{wH:a.j.prototype.wH});a.j.prototype.remove=function(b,a){a=a||{};var c=[],e;b instanceof Array?c=b:c.push(b);for(e=c.length-1;0<=e;e-=1)this.Zh(c[e],-1,a)};a.b.g("Collection.prototype.remove",{remove:a.j.prototype.remove});a.j.prototype.Zh=function(b,d,c){c=c||{};b=-1==d?this.Zi(b):a.j.Tg(d,b);var e=c.silent;
d=b.index;if(-1<d){var g=b.m;void 0!==g&&g.xo()===this&&g.Il(null);this.$E(d,1);this.bi();var h={};a.Ec.dh(h,c);h.index=d;void 0!==g&&g.Mb(e,a.X.v.REMOVE,g,this,h);this.Xv(g)}return b.m};a.j.prototype.Xv=function(b){void 0!==b&&b.off(null,null,this)};a.j.prototype.EP=function(b){b.Dg(a.X.v.ALL,this.TP,this,!1,!0)};a.j.prototype.TP=function(b,d,c,e){b===a.X.v.DESTROY&&this.remove(d);void 0!==c&&c instanceof a.j&&c!==this||(Array.prototype.slice.call(arguments),this.Mb(e&&e.silent,b,d,c,e))};a.j.prototype.refresh=
function(b){b=b||{};var d=a.j.Zb();if(!this.Va()){this.reset(null,{silent:!0});var c=this;this.fetch({success:function(b,c,e){this.Mb(void 0!==e.silent&&e.silent,a.X.v.REFRESH,this,e,null);d.resolve(b,c,e)},error:function(b,a,e){d.reject(c,b,a,e)}});return d}var e=this.totalResults;void 0!==e&&(this.mj(Array(e)),this.gn());this.Mb(void 0!==b.silent&&b.silent,a.X.v.REFRESH,this,b,null);return d.resolve()};a.b.g("Collection.prototype.refresh",{refresh:a.j.prototype.refresh});a.j.prototype.reset=function(b,
d){d=d||{};d.previousModels=this.wb();this.wb().forEach(function(b){b&&(this.Xv(b),b.Il(null))},this);this.mj([]);this.gn();if(b)if(d.parse&&(b=this.parse(b)),b instanceof Array){this.Vh(b.length);for(var c=0;c<b.length;c+=1)this.Lg(b[c],d,!0,!1)}else this.Vh(1),this.Lg(b,d,!0,!1);this.bi();this.Mb(void 0!==d.silent&&d.silent,a.X.v.RESET,this,d,null)};a.b.g("Collection.prototype.reset",{reset:a.j.prototype.reset});a.j.prototype.at=function(b,a){return this.Ch(b,a,!1,this.Nd(a))};a.b.g("Collection.prototype.at",
{at:a.j.prototype.at});a.j.prototype.Ch=function(b,a,c,e){return 0>b||this.jQ(b)?null:c||!this.Va()&&!e?this.Ob(b):this.rt(b,a).promise()};a.j.prototype.rt=function(b,d){function c(){g.resolve(e.Ob(b))}var e=this,g=a.j.Zb(),h=this.Ob(b);return void 0===h?(h={},a.Ec.dh(h,d||{}),h.context=this,h.startIndex=b,h.error=function(b,a){g.reject(a)},this.Cp(h,-1,!1).then(c,function(b){g.reject(b)}),g):a.j.Zb().resolve(h)};a.j.prototype.Bw=function(b){var a=null;this.wb().some(function(c){return void 0!==c&&
b===c.cid?(a=c,!0):!1});if(a)return a;if(this.Va())throw Error("Not found locally and not supported by server for virtual collections");return null};a.b.g("Collection.prototype.getByCid",{Bw:a.j.prototype.Bw});a.j.prototype.get=function(b,d){var c=this.Zi(b,d,this.Nd(d));if(c){if(f.isFunction(c.promise))return c.then(function(b){return b.m});if(this.Va())return a.j.Zb().resolve(c.m);if(c.hasOwnProperty("m"))return c.m}return null};a.b.g("Collection.prototype.get",{get:a.j.prototype.get});a.j.prototype.DB=
function(b){return(b=this.EB(b))?b.m:null};a.j.prototype.EB=function(b){var d=b;b instanceof a.q?(d=b.Lj(),b=b.re()):void 0!==b&&null!=b&&void 0!==b.id&&(b=b.id);var c=null;this.wb().some(function(e,g){return void 0!==e&&e.Nj(b,d)?(c=a.j.Tg(g,e),!0):!1});return c?c:a.j.Tg(-1,void 0)};a.j.prototype.Zi=function(b,d,c,e){var g=b;void 0===e&&(e=!1);b instanceof a.q?(g=b.Lj(),b=b.re()):void 0!==b&&null!=b&&void 0!==b.id&&(b=b.id);var h=null;this.wb().some(function(d,e){if(void 0!==d&&d.Nj(b,g)){var l=
a.j.Tg(e,d);if(c)return h=a.j.Zb().resolve(l),!0;h=l;return!0}return!1});if(h)return h;if(this.Va()){if(void 0===b&&void 0!==g){var f=a.j.Zb();return f.resolve(a.j.Tg(-1,void 0))}var f=a.j.Zb(),l=this,n={};a.Ec.dh(n,d||{});n.context=this;n.startID=b;n.error=function(b,a){f.reject(a)};this.Cp(n,-1,e).then(function(d){if(null!=d){d=l.du();var c=l.Ob(d);void 0!==c&&c.Nj(b,g)?f.resolve(a.j.Tg(d,c)):f.resolve(a.j.Tg(-1,void 0))}else f.resolve(a.j.Tg(-1,void 0))},function(b){f.reject(b)});return f}d=a.j.Tg(-1,
void 0);return c?a.j.Zb().resolve(d):d};a.j.Zb=function(){return f.Deferred()};a.j.Tg=function(b,a){return{index:b,m:a}};a.j.prototype.parse=function(b){var a;if(b instanceof Array||!b)return b;for(a in b)if(b.hasOwnProperty(a)&&b[a]instanceof Array)return b[a];return b};a.j.prototype.Gr=function(b,d){var c=this.Yt(b,d);if(c.start===b&&c.count===d)return a.j.Zb().resolve(c.start,c.count);c=this.FB();-1<c&&c<d&&(this.modelLimit=d);c=a.j.Zb();return this.KE(b,d,-1,{start:b,count:d},c,!0)};a.b.g("Collection.prototype.setRangeLocal",
{Gr:a.j.prototype.Gr});a.j.prototype.KE=function(b,d,c,e,g,h){var f=this,l=this.$t(b,d);this[a.j.fd]&&this[a.j.fd]>l-b&&(l=this[a.j.fd]+b);!this.vk()&&l<b+d&&(l=b+d);var n=this.yB(b,l);n>b&&(b=n,l=this.$t(n,d));l=this.Va()?{context:this,startIndex:b,fetchSize:l-b}:{context:this};l.error=function(b,a){g.reject(a)};this.Cp(l,c,-1<c).then(function(){var a=f.Yt(e.start,e.count);if(h&&f.vk()&&a.count<e.count){var c=a.start+a.count,l=b+d;l<f.totalResults?f.KE(l,d,c,e,g,h):g.resolve(a.start,a.count)}else g.resolve(a.start,
a.count)},function(b){g.reject(b)});return g};a.j.prototype.$t=function(b,a){var c=this.jd();return 0===c?b+a:b+a>c?c:b+a};a.j.prototype.$G=function(b,a){var c=this.Yt(b,a);return b===c.start&&a===c.count};a.b.g("Collection.prototype.isRangeLocal",{$G:a.j.prototype.$G});a.j.prototype.Yt=function(b,a){if(!this.Va())return 0<this.jd()?{start:b,count:a}:{start:b,count:0};var c=this.$t(b,a);if(!this.vk()&&c<b+a||0===c)return{start:b,count:0};c=this.yB(b,c);return-1<c?{start:b,count:c-b}:{start:b,count:a}};
a.j.prototype.yB=function(b,a){for(var c=b;c<a;c++)if(void 0===this.Ob(c))return c;return-1};a.j.prototype.fetch=function(b){return this.Cp(b,-1,!1)};a.b.g("Collection.prototype.fetch",{fetch:a.j.prototype.fetch});a.j.prototype.Cp=function(b,d,c){function e(b,a,d){b.Va()?d||b.iE():a.add||a.Fx||b.reset()}var g=b||{},h=g.success,f;g.set&&(g.Fx=g.set?!0:!1);void 0===g.parse&&(g.parse=!0);f=this;g.success=function(l){f.OR(l,b);var n=f.parse(l,b),m=null;if(g.add||f.model){e(f,g,c);try{t=!1,-1===d&&(t=
!0,d=f.du()),m=f.RM(n,d,t,g)}catch(q){g.error&&g.error.call(a.q.Sf(b,f),f,q,b);return}}else if(!c)if(f.Va()){e(f,g,c);var t=!1;-1===d&&(t=!0,d=f.du());m=f.HQ(n,d,t)}else g.Fx?f.Ev(n,!1,g,!1):f.reset(n);f.Va()&&m&&(f.lastFetchCount=m.length);f.Mb(!1,a.X.v.SYNC,f,l,g);h&&h.call(a.q.Sf(b,f),f,l,g)};return this.bB(g)};a.j.prototype.HQ=function(b,a,c){var e;if(b){e=b instanceof Array?b:[b];b={};c&&this.Vh(e.length);c=this.Va();for(var g=null,h=0;h<e.length;h+=1)c&&(b={at:a},g=this.Ch(a,null,!0,!1)),b.silent=
!0,this.Lg(e[h],b,!0,!1),this.Ch(a,null,!0,!1)!==g&&a++}return e};a.j.prototype.RM=function(b,d,c,e){e=e||{};var g=e.parse,h=a.j.rA(this);if(b){var f=b instanceof Array?b:[b];b={};c&&this.Vh(f.length);c=this.Va();if(e.Fx&&!c){for(var l=0;l<f.length;l+=1)d=h&&g?h.parse(f[l]):f[l],f[l]=d;this.Ev(f,!1,e,!1)}else{e=null;for(var n=d,l=0;l<f.length;l+=1)d=h&&g?h.parse(f[l]):f[l],c&&(b={at:n},e=this.Ch(n,b,!0,!1)),b.silent=!0,this.Lg(d,b,!0,!1),this.Ch(n,null,!0,!1)!==e&&n++}}return f};a.j.prototype.OM=
function(b){var d=b||{},c=d.success,e,g;void 0===d.parse&&(d.parse=!0);g=this;d.success=function(h){var f,l;f=g.parse(h,b);var n=null,m=[];if(d.add||g.model)if(l=a.j.rA(g),f)for(n=f instanceof Array?f:[f],f=0;f<n.length;f+=1)e=l&&d.parse?l.parse(n[f]):n[f],m.push(g.Wm(e));g.Mb(!1,a.X.v.SYNC,g,h,d);c&&c.call(a.q.Sf(b,g),g,m,d)};this.bB(d)};a.j.rA=function(b){if(b.model)return a.q.ad(b.model)?new b.model:new b.model.constructor};a.j.prototype.bB=function(b){try{return a.q.Lm("read",this,b)}catch(d){throw this.Mb(!1,
a.X.v.ERROR,this,null,b),d;}};a.j.prototype.iE=function(){var b=this.totalResults;void 0!==b&&this.jd()!==b&&(this.mj(Array(b)),this.gn(),this.bi())};a.j.prototype.wm=function(b){b=b||{};return b[a.j.fd]||this[a.j.fd]};a.j.prototype.WO=function(){return void 0!==this.hasMore&&this.hasMore};a.j.prototype.Va=function(){return-1<this.wm(null)};a.j.prototype.Vp=function(b,d,c,e,g){b=parseInt(a.j.hu(b,d,c),10);return void 0===b||null===b||isNaN(b)?e?e:g:b};a.j.prototype.OR=function(b,d){var c={};this.customPagingOptions&&
((c=this.customPagingOptions.call(this,b))||(c={}));d=d||{};this.lastFetchSize=this.Vp(c,b,"limit",d.fetchSize,this.fetchSize);this.offset=this.Vp(c,b,"offset",d.startIndex,0);this.lastFetchCount=this.Vp(c,b,"count",this.lastFetchCount,this.lastFetchCount);this.totalResults=this.Vp(c,b,"totalResults",this.totalResults,this.totalResults);this.hasMore=this.vN(a.j.hu(c,b,"hasMore"),this.offset,this.lastFetchSize,this.totalResults);!this.Va()&&this.lastFetchSize&&this.Fr(this.lastFetchSize)};a.j.prototype.vN=
function(b,a,c,e){return b&&void 0!==b?b:a+c>e?!1:!0};a.j.hu=function(b,a,c){return b.hasOwnProperty(c)?b[c]:a?a[c]:void 0};a.j.prototype.du=function(){return void 0!==this.offset?this.offset:0};a.j.prototype.create=function(b,d){function c(c,e,g,h){return!1===e.save(b instanceof a.q?null:b,h)&&(d.validationError=e.validationError,c.Mb(!1,a.X.v.INVALID,c,e.validationError,h),g)?(c.Xv(e),c.remove(e),!1):e}var e=this.Nd(d);d=d||{};var g=this.Wm(b,!0,d),h=d.success,f=d.context,l=d.validate;d.context=
this;d.success=function(b,a,d){h&&h.call(null!=f?f:this,b,a,d)};if(null==g)return!1;d.forceNew=null!=g.re();g.Il(this);var n=this;if(e||this.Va()){var m=a.j.Zb();this.add(g,{merge:!0,deferred:!0}).done(function(){d.success=function(b,a,d){h&&h.call(null!=f?f:this,b,a,d);m.resolve(b)};var b=c(n,g,l,d);b||m.resolve(b)});return m.promise()}this.add(g,{merge:!0});return c(this,g,l,d)};a.b.g("Collection.prototype.create",{create:a.j.prototype.create});a.j.prototype.oH=function(b){var a=[],c;this.ze("pluck");
for(c=0;c<this.Qc();c+=1)a.push(this.at(c).get(b));return a};a.b.g("Collection.prototype.pluck",{oH:a.j.prototype.oH});a.j.prototype.zl=function(b,d){d=d||{};var c=this.Nd(d);if(this.Va()){var e=a.j.Zb();this.OM({query:b,all:!0,success:function(b,a){e.resolve(a)}});return e.promise()}var g=[],h,f;for(h=0;h<this.Qc();h+=1)f=this.at(h),f.aI(b)&&g.push(f);return c?a.j.Zb().resolve(g):g};a.b.g("Collection.prototype.where",{zl:a.j.prototype.zl});a.j.prototype.UH=function(b,d){d=d||{};var c=this.Nd(d),
e=this;if(this.Va()||c){var g=a.j.Zb();this.zl(b,d).done(function(b){b=e.RC(b);g.resolve(b)});return g.promise()}c=this.zl(b,d);c=this.RC(c);c[a.j.fd]=-1;c.bi();return c};a.b.g("Collection.prototype.whereToCollection",{UH:a.j.prototype.UH});a.j.prototype.RC=function(b){var a=this.iA(!1);a.mj(b);a.gn();a.bi();return a};a.j.prototype.ze=function(b){if(this.Va())throw Error(b+" not valid on a virtual Collection");};a.j.prototype.map=function(b,a){var c=[],e;this.ze("map");this.wb().forEach(function(g){e=
b.call(a||this,g);c.push(e)});return c};a.b.g("Collection.prototype.map",{map:a.j.prototype.map});a.j.prototype.each=function(b,a){this.ze("each");this.wb().forEach(b,a)};a.b.g("Collection.prototype.each",{each:a.j.prototype.each});a.j.prototype.size=function(){return this.Qc()};a.b.g("Collection.prototype.size",{size:a.j.prototype.size});a.j.prototype.DH=function(b,d){var c=[],e;this.ze("sortBy");this.wb().forEach(function(b){c.push(b)});e=this;c.sort(function(c,h){var f,l;if(a.q.ad(b))return f=
b.call(d||e,c),l=b.call(d||e,h),a.j.Pg(f,l,e.sortDirection);f=c.get(b);l=h.get(b);return a.j.Pg(f,l,e.sortDirection)});return c};a.b.g("Collection.prototype.sortBy",{DH:a.j.prototype.DH});a.j.prototype.KG=function(b,d){var c={},e;this.ze("groupBy");this.wb().forEach(function(g){e=a.q.ad(b)?b.call(d||this,g):g.get(b);void 0===c[e]&&(c[e]=[]);c[e].push(g)},this);return c};a.b.g("Collection.prototype.groupBy",{KG:a.j.prototype.KG});a.j.prototype.min=function(b,a){var c={},e,g;this.ze("min");if(0==this.jd())return null;
c=this.Ob(0);e=b.call(a||this,this.Ob(0));this.wb().forEach(function(h,f){1<=f&&(g=b.call(a||this,h),g<e&&(c=h,e=g))},this);return c};a.b.g("Collection.prototype.min",{min:a.j.prototype.min});a.j.prototype.max=function(b,a){var c={},e,g;this.ze("max");if(0==this.jd())return null;c=this.Ob(0);e=b.call(a,this.Ob(0));this.wb().forEach(function(h,f){1<=f&&(g=b.call(a||this,h),g>e&&(c=h,e=g))},this);return c};a.b.g("Collection.prototype.max",{max:a.j.prototype.max});a.j.prototype.filter=function(b,a){var c=
[];this.ze("filter");this.wb().forEach(function(e){b.call(a||this,e)&&c.push(e)});return c};a.b.g("Collection.prototype.filter",{filter:a.j.prototype.filter});a.j.prototype.VH=function(b){var a=[],c,e;this.ze("without");return arguments?(this.wb().forEach(function(b){e=!0;for(c=0;c<arguments.length;c+=1)if(b.Nj(arguments[c].re(),arguments[c].Lj())){e=!1;break}e&&a.push(b)}),a):this.wb()};a.b.g("Collection.prototype.without",{VH:a.j.prototype.VH});a.j.prototype.isEmpty=function(){return 0===this.Qc()};
a.b.g("Collection.prototype.isEmpty",{isEmpty:a.j.prototype.isEmpty});a.j.prototype.DF=function(b,a){this.ze("any");for(var c,e=0;e<this.jd();e+=1)if(c=this.Ob(e),b.call(a||this,c))return!0;return!1};a.b.g("Collection.prototype.any",{DF:a.j.prototype.DF});a.j.prototype.aG=function(b,d){var c=this.Nd(d);if(this.Va()||c){var e=a.j.Zb();this.zl(b,d).done(function(b){b&&0<b.length&&e.resolve(b[0]);e.resolve(null)});return e.promise()}c=this.zl(b);return 0<c.length?c[0]:null};a.b.g("Collection.prototype.findWhere",
{aG:a.j.prototype.aG});a.j.prototype.slice=function(b,a,c){var e=this.Nd(c);c=[];if(void 0===a){if(this.Va&&!this.vk())throw Error("End must be set for virtual collections with no totalResults");a=this.jd()}if(e||this.Va())return this.Fl(b,a);for(;b<a;b+=1)c.push(this.Ob(b));return c};a.b.g("Collection.prototype.slice",{slice:a.j.prototype.slice});a.j.prototype.set=function(b,a){return this.Ev(b,!0,a,this.Nd(a)||this.Va())};a.b.g("Collection.prototype.set",{set:a.j.prototype.set});a.j.ZD=function(b,
a,c,e){if(a)for(a=b.jd()-1;0<=a;a-=1)-1==c.indexOf(a)&&b.Zh(b.Ob(a),a,e)};a.j.prototype.Ev=function(b,d,c,e){c=c||{};var g=void 0===c.add?!0:c.add,h=void 0===c.remove?!0:c.remove,f=void 0===c.merge?!0:c.merge,l=[],n=null,m;d&&(b=this.parse(b));m=a.q.El(b)?b:[b];if(e)return this.jM(m,c,h,g,f,d);for(b=0;b<m.length;b+=1)n=this.sF(this.Wm(m[b],d,c),g,f,e),-1!==n&&l.push(n);a.j.ZD(this,h,l,c)};a.j.prototype.jM=function(b,d,c,e,g,h){function k(b){return l(b+1)}function l(c){var f=a.j.Zb();q.sF(q.Wm(b[c],
h,d),e,g,!0).done(function(b){-1!==b&&n.push(b);f.resolve(c)});return f.promise()}var n=[],m,q=this,t=l(0);for(m=1;m<b.length;m+=1)t=t.then(k);return f.when(t).then(function(){a.j.ZD(q,c,n,d)})};a.j.prototype.sF=function(b,d,c,e){function g(e,g,h){var f=g?g.index:-1;if(g&&g.m){if(c){g={merge:c};if(h){var k=a.j.Zb();e.Lg(b,g,!1,!0).done(function(){k.resolve(f)});return k.promise()}e.add(b,g)}}else if(d){if(h)return k=a.j.Zb(),e.add(b,{deferred:!0}).done(function(){k.resolve(e.Qc()-1)}),k.promise();
e.add(b);f=e.Qc()-1}return f}if(e||this.Va()){var h=this,f=a.j.Zb();this.Zi(b,null,e).done(function(b){g(h,b,!0).done(function(b){f.resolve(b)})});return f.promise()}e=this.Zi(b);return g(this,e,!1)};a.j.prototype.toJSON=function(){var b=[];this.ze("toJSON");this.wb().forEach(function(a){b.push(a.toJSON())});return b};a.b.g("Collection.prototype.toJSON",{toJSON:a.j.prototype.toJSON});a.j.prototype.first=function(b,a){var c=this.Nd(a),e=this.Qc(),g=[];b?e=b:b=1;c=this.Va()||c;if(1===b)return c?this.rt(0,
null).promise():0<this.jd()?this.Ob(0):null;e>this.jd()&&(!this.Va()||this.vk())&&(e=this.jd());if(c)return this.Fl(0,e);for(c=0;c<e;c+=1)g.push(this.Ob(c));return g};a.b.g("Collection.prototype.first",{first:a.j.prototype.first});a.j.prototype.indexOf=function(b,a){var c=this.Nd(a);return this.Va()||c?this.Zi(b,null,!0).then(function(b){return b.index}):this.Zi(b).index};a.b.g("Collection.prototype.indexOf",{indexOf:a.j.prototype.indexOf});a.j.prototype.NP=function(b){b=this.EB(b);return void 0!==
b?b.index:-1};a.j.prototype.pop=function(b){var a=this.Nd(b);if(this.Va()||a){var c=this;return this.at(this.Qc()-1,{deferred:a}).then(function(a){c.remove(a,b);return a})}a=this.at(this.Qc()-1);this.remove(a,b);return a};a.b.g("Collection.prototype.pop",{pop:a.j.prototype.pop});a.j.prototype.push=function(b,a){var c=this.Nd(a);this.Vh(1);return this.Lg(b,a,!1,c)};a.b.g("Collection.prototype.push",{push:a.j.prototype.push});a.j.prototype.lastIndexOf=function(b,d){var c;this.ze("lastIndexOf");void 0===
d&&(d=0);for(c=this.Qc()-1;c>=d;c-=1)if(a.b.Ni(b,this.at(c)))return c;return-1};a.b.g("Collection.prototype.lastIndexOf",{lastIndexOf:a.j.prototype.lastIndexOf});a.j.prototype.ku=function(b){return void 0===b?[]:b.split(",")};a.j.QN=function(b){b=a.q.El(b)?b:[b];var d="",c,e,g,h;for(g=0;g<b.length;g++){c=b[g];for(h in c)if(c.hasOwnProperty(h))for(var f=a.q.El(c[h])?c[h]:[c[h]],l=0;l<f.length;l++){if(a.q.Qx(f[l])){e=f[l].value;var n=null,n=f[l].comparator,n=a.q.ad(n)?n(null,h,e):n;e=h+n+e}else e=h+
"\x3d"+c[h];d+=e+"+"}d=d.substring(0,d.length-1)+","}return","===d.substring(d.length-1)?d.substring(0,d.length-1):d};a.j.prototype.pI=function(b){var d={},c;for(c in b)b.hasOwnProperty(c)&&(d[c]=b[c]);if((b=this.comparator)&&a.fb.Fd(b)){b=this.ku(b);for(c=0;c<b.length;c++)d.sort=0===c?b[c]:d.sort+(","+b[c]);d.sortDir=this.lu()}this.Va()&&(d[a.j.fd]=this.wm(d));return d};a.j.prototype.fI=function(b){var d=a.q.ad(this.url)?this.url():this.url;if(this.Va()){var c=b.all,e=null;e=c?(e=this.totalResults)?
e:this.wm(b):this.wm(b);d+="?limit\x3d"+e;c||(b.startIndex&&(d+="\x26offset\x3d"+b.startIndex),b.startID&&(d+="\x26fromID\x3d"+b.startID),b.since&&(d+="\x26since\x3d"+b.since),b.until&&(d+="\x26until\x3d"+b.until));b.query&&(b=a.j.QN(b.query))&&0<b.length&&(d+="\x26q\x3d"+b);if(b=this.comparator)for(b=this.ku(b),c=this.lu(),e=0;e<b.length;e++)d=0===e?d+("\x26orderBy\x3d"+b[e]+":"+c):d+(","+b[e]+":"+c);d+="\x26totalResults\x3dtrue"}return d};a.j.prototype.lu=function(){return-1===this.sortDirection?
"dsc":"asc"};a.j.prototype.sync=function(b,a,c){return window.oj.sync(b,a,c)};a.j.fd="fetchSize";a.Ab=function(b,a){this.jo=b;this.Ff=a;jQuery.support.cors=!0};a.Ab.Sj="headers";a.Ab.tn=function(b,d,c){var e;b=f.extend(!0,b,c);for(e in d)d.hasOwnProperty(e)&&"oauthHeader"!==e&&(b.hasOwnProperty(e)||(b[e]=d[e]),e===a.Ab.Sj&&(b[e]=f.extend(!0,b[e],d[e])));if(d.oauthHeader)for(e in b[a.Ab.Sj]||(b[a.Ab.Sj]={}),d.oauthHeader)d.oauthHeader.hasOwnProperty(e)&&(b[a.Ab.Sj].hasOwnProperty(e)||(b[a.Ab.Sj][e]=
d.oauthHeader[e]));return b};a.Ab.prototype.KT=function(b,d,c,e){c=c||{};var g="jsonp"===c.dataType,h=this.Fm("read",this.jo,this.Ff,null,e,c);b={crossDomain:c.crossDomain||!g,dataType:c.dataType||"json",jsonpCallback:c.jsonpCallback,context:null!==e?e:this,success:b,error:d};b=this.bp(b);b=a.Ab.tn(b,c,h);c.xhr=this.ajax(b);return c.xhr};a.Ab.prototype.bp=function(b){b[a.Ab.Sj]={"Accept-Language":this.De()};return b};a.Ab.prototype.JT=function(b,d,c,e,g){e=e||{};var h="jsonp"===e.dataType;c=this.Fm("read",
this.jo,this.Ff,c,g,e);b={crossDomain:e.crossDomain||!h,dataType:e.dataType||"json",jsonpCallback:e.jsonpCallback,context:null!==g?g:this,success:b,error:d};b=this.bp(b);b=a.Ab.tn(b,e,c);e.xhr=this.ajax(b);return e.xhr};a.Ab.prototype.SH=function(b,d,c,e,g,h,f){g=g||{};var l="jsonp"===g.dataType;d=this.Fm(f?"patch":"update",this.jo,this.Ff,d,h,g);b={crossDomain:g.crossDomain||!l,contentType:g.contentType||"application/json",dataType:g.dataType||"json",jsonpCallback:g.jsonpCallback,data:JSON.stringify(c),
success:b,error:e,context:null!==h?h:this};b=this.bp(b);b=a.Ab.tn(b,g,d);g.xhr=this.ajax(b);return g.xhr};a.Ab.prototype.Rt=function(b,a){return a.type?a.type:"create"===b?"POST":"delete"===b?"DELETE":"patch"===b?"PATCH":"update"===b?"PUT":"GET"};a.Ab.prototype.CR=function(b,d,c){d=d instanceof a.j?d.pI(c):{};b&&(d.recordID=b);return d};a.Ab.prototype.Fm=function(b,d,c,e,g,h){if(a.q.ad(c)){c=c.call(this,b,g,this.CR(e,g,h));if(a.fb.Fd(c))return{url:c,type:this.Rt(b,h)};if(c)return c.url=c.hasOwnProperty("url")?
c.url:d,c.type=c.hasOwnProperty("type")?c.type:this.Rt(b,h),c}return{url:d,type:this.Rt(b,h)}};a.Ab.prototype.sT=function(b,d,c,e){c=c||{};var g="jsonp"===c.dataType;b=this.Fm("delete",this.jo,this.Ff,b,e,c);d={crossDomain:c.crossDomain||!g,success:c.success,error:d,context:null!==e?e:this};d=a.Ab.tn(d,c,b);c.xhr=this.ajax(d);return c.xhr};a.Ab.prototype.JS=function(b,d,c,e){c=c||{};var g=JSON.stringify(b),h="jsonp"===c.dataType;b=this.Fm("create",this.jo,this.Ff,null,e,c);d={crossDomain:c.crossDomain||
!h,contentType:c.contentType||"application/json",dataType:c.dataType||"json",jsonpCallback:c.jsonpCallback,data:g,success:c.success,error:d,context:null!==e?e:this};d=this.bp(d);d=a.Ab.tn(d,c,b);c.xhr=this.ajax(d);return c.xhr};a.Ab.prototype.De=function(){return a.ha.De()};a.Ab.prototype.ajax=function(b){return window.oj.ajax(b)};a.Za=function(b,d){d=d||{};a.Za._init(this,d,b||"Authorization")};o_("OAuth",a.Za,a);a.b.oa(a.Za,a.b,"OAuth.OAuth");a.Za.prototype.Init=function(){a.Za.t.Init.call(this)};
a.Za.prototype.rG=function(){var b={};this.gi.access_token||this.pw();b[this.kg.JF]="Bearer "+this.gi.access_token;return b};a.b.g("OAuth.prototype.getHeader",{rG:a.Za.prototype.rG});a.Za.prototype.XG=function(){return this.gi.nW?!0:!1};a.b.g("OAuth.prototype.isInitialized",{XG:a.Za.prototype.XG});a.Za.prototype.pw=function(){var b={},d=this;b[d.kg.JF]="Basic "+a.Za.UK(d.kg.client_id+":"+d.kg.client_secret);f.ajax({type:"POST",async:!1,url:this.kg.bearer_url,data:"grant_type\x3dclient_credentials",
headers:b,success:function(b){a.Za.Jm(d.gi,b)},error:function(b){throw Error(b.responseText);}})};a.b.g("OAuth.prototype.clientCredentialGrant",{pw:a.Za.prototype.pw});a.Za.prototype.AH=function(b){a.Za.Jm(this.gi,b)};a.b.g("OAuth.prototype.setAccessTokenResponse",{AH:a.Za.prototype.AH});a.Za.prototype.fG=function(){return this.gi};a.b.g("OAuth.prototype.getAccessTokenResponse",{fG:a.Za.prototype.fG});a.Za.prototype.NF=function(){a.Za.aA(this.gi)};a.b.g("OAuth.prototype.cleanAccessTokenResponse",
{NF:a.Za.prototype.NF});a.Za.prototype.zH=function(b){a.Za.Jm(this.kg,b)};a.b.g("OAuth.prototype.setAccessTokenRequest",{zH:a.Za.prototype.zH});a.Za.prototype.eG=function(){return this.kg};a.b.g("OAuth.prototype.getAccessTokenRequest",{eG:a.Za.prototype.eG});a.Za.prototype.MF=function(){a.Za.aA(this.kg)};a.b.g("OAuth.prototype.cleanAccessTokenRequest",{MF:a.Za.prototype.MF});a.Za._init=function(b,d,c){b.Init();b.kg={};b.gi={};d.access_token?a.Za.Jm(b.gi,d):d.client_id&&d.client_secret&&d.bearer_url&&
a.Za.Jm(b.kg,d);b.kg.JF=c};a.Za.Jm=function(b,a){var c;a=a||{};for(c in a)b[c]=a[c]};a.Za.aA=function(b){for(var a in b)b.hasOwnProperty(a)&&"auth_header"!==a&&(b[a]=null,delete b[a])};a.Za.UK=function(b){var a,c,e,g,h=0,f=0,l=[];do a=b.charCodeAt(h++),c=b.charCodeAt(h++),e=b.charCodeAt(h++),g=a<<16|c<<8|e,a=g>>18&63,c=g>>12&63,e=g>>6&63,g&=63,l[f++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(c)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(g);while(h<b.length);l=l.join("");a=b.length%3;return(a?l.slice(0,a-3):l)+"\x3d\x3d\x3d".slice(a||3)}});
//# sourceMappingURL=oj-modular.map