/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","knockout","ojs/ojpagingcontrol","ojs/ojknockout-model"],function(a,f,b){a.qb=function(a){this.ka=a;this.current=0;this.Init();this.cf=[];this.setPageSize(10)};o_("CollectionPagingDataSource",a.qb,a);a.b.oa(a.qb,a.jb,"oj.CollectionPagingDataSource");a.qb.prototype.Init=function(){a.qb.t.Init.call(this)};a.b.g("CollectionPagingDataSource.prototype.Init",{Init:a.qb.prototype.Init});a.qb.prototype.ju=function(){return this.hasMore()?this.pageSize:this.totalSize()-this.startIndex()};
a.qb.prototype.Yg=function(){this.cf=Array(this.ju());var a=this;return this.ka.Fl(this.startIndex(),this.startIndex()+this.cf.length).then(function(b){for(var e=0;e<b.length;e++)a.cf[e]=b[e];a.an()})};a.qb.prototype.an=function(){if(void 0!==this.Jf){this.Jf.removeAll();for(var b=0;b<this.cf.length;b++)this.Jf.push(a.Ta.map(this.cf[b]))}};a.qb.prototype.yj=function(){return this.cf};a.b.g("CollectionPagingDataSource.prototype.getWindow",{yj:a.qb.prototype.yj});a.qb.prototype.Kn=function(){void 0===
this.Jf&&(this.Jf=b.observableArray(),this.an());return this.Jf};a.b.g("CollectionPagingDataSource.prototype.getWindowObservable",{Kn:a.qb.prototype.Kn});a.qb.prototype.fetch=function(a){var b=a||{};void 0!==b.startIndex&&(this.current=b.startIndex);void 0!==b.pageSize&&(this.pageSize=b.pageSize);var e=this;try{this.ka.fetch({success:function(){e.Yg().then(function(){e.Zm(b)})}})}catch(f){e.Yg().then(function(){e.Zm(b)})}};a.b.g("CollectionPagingDataSource.prototype.fetch",{fetch:a.qb.prototype.fetch});
a.qb.prototype.Zm=function(a){a=a||{};this.handleEvent("sync",null);a.success&&a.success()};a.qb.prototype.handleEvent=function(b,c){a.qb.t.handleEvent.call(this,b,c)};a.qb.prototype.hasMore=function(){return this.startIndex()+this.pageSize<this.totalSize()};a.b.g("CollectionPagingDataSource.prototype.hasMore",{hasMore:a.qb.prototype.hasMore});a.qb.prototype.next=function(){if(this.hasMore()){this.current+=this.pageSize;var a=this;return this.Yg().then(function(){a.Zm(null)})}this.Zm(null)};a.b.g("CollectionPagingDataSource.prototype.next",
{next:a.qb.prototype.next});a.qb.prototype.previous=function(){0>this.startIndex()-this.pageSize?this.current=0:this.current-=this.pageSize;var a=this;return this.Yg().then(function(){a.Zm(null)})};a.b.g("CollectionPagingDataSource.prototype.previous",{previous:a.qb.prototype.previous});a.qb.prototype.setPageSize=function(a){this.pageSize=a};a.qb.prototype.startIndex=function(){return this.current};a.b.g("CollectionPagingDataSource.prototype.startIndex",{startIndex:a.qb.prototype.startIndex});a.qb.prototype.size=
function(){var a=this.yj();return a?a.length:0};a.b.g("CollectionPagingDataSource.prototype.size",{size:a.qb.prototype.size});a.qb.prototype.totalSize=function(){return this.ka.length};a.b.g("CollectionPagingDataSource.prototype.totalSize",{totalSize:a.qb.prototype.totalSize});a.ub=function(a){this.data=a;this.current=0;this.Init();this.setPageSize(10)};o_("ArrayPagingDataSource",a.ub,a);a.b.oa(a.ub,a.jb,"oj.ArrayPagingDataSource");a.ub.prototype.Init=function(){a.ub.t.Init.call(this)};a.b.g("ArrayPagingDataSource.prototype.Init",
{Init:a.ub.prototype.Init});a.ub.prototype.ju=function(){return this.hasMore()?this.pageSize:this.totalSize()-this.startIndex()};a.ub.prototype.Yg=function(){this.cf=Array(this.ju());for(var a=0;a<this.cf.length;a++)this.cf[a]=this.data[this.startIndex()+a];this.an();this.handleEvent("sync",null)};a.ub.prototype.an=function(){if(void 0!==this.Jf){this.Jf.removeAll();for(var a=0;a<this.cf.length;a++)this.Jf.push(this.cf[a])}};a.ub.prototype.handleEvent=function(b,c){a.ub.t.handleEvent.call(this,b,
c)};a.ub.prototype.yj=function(){return this.cf};a.b.g("ArrayPagingDataSource.prototype.getWindow",{yj:a.ub.prototype.yj});a.ub.prototype.Kn=function(){void 0===this.Jf&&(this.Jf=b.observableArray(),this.an());return this.Jf};a.b.g("ArrayPagingDataSource.prototype.getWindowObservable",{Kn:a.ub.prototype.Kn});a.ub.prototype.fetch=function(a){a=a||{};void 0!==a.startIndex&&(this.current=a.startIndex);void 0!==a.pageSize&&(this.pageSize=a.pageSize);this.Yg()};a.b.g("ArrayPagingDataSource.prototype.fetch",
{fetch:a.ub.prototype.fetch});a.ub.prototype.hasMore=function(){return this.startIndex()+this.pageSize<this.totalSize()};a.b.g("ArrayPagingDataSource.prototype.hasMore",{hasMore:a.ub.prototype.hasMore});a.ub.prototype.next=function(){this.hasMore()&&(this.current+=this.pageSize,this.Yg())};a.b.g("ArrayPagingDataSource.prototype.next",{next:a.ub.prototype.next});a.ub.prototype.previous=function(){0>this.startIndex()-this.pageSize?this.current=0:this.current-=this.pageSize;this.Yg()};a.b.g("ArrayPagingDataSource.prototype.previous",
{previous:a.ub.prototype.previous});a.ub.prototype.setPageSize=function(a){this.pageSize=a;this.Yg()};a.ub.prototype.startIndex=function(){return this.current};a.b.g("ArrayPagingDataSource.prototype.startIndex",{startIndex:a.ub.prototype.startIndex});a.ub.prototype.size=function(){return this.yj().length};a.b.g("ArrayPagingDataSource.prototype.size",{size:a.ub.prototype.size});a.ub.prototype.totalSize=function(){return this.data.length};a.b.g("ArrayPagingDataSource.prototype.totalSize",{totalSize:a.ub.prototype.totalSize})});
//# sourceMappingURL=oj-modular.map