/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdatacollection-common"],function(a,f){a.jb=function(b){this.Oa=b;this.Init()};o_("PagingDataSource",a.jb,a);a.b.oa(a.jb,a.Mc,"oj.PagingDataSource");a.jb.prototype.Init=function(){a.jb.t.Init.call(this)};a.b.g("PagingDataSource.prototype.Init",{Init:a.jb.prototype.Init});a.jb.prototype.fetch=function(){a.i.fa()};a.b.g("PagingDataSource.prototype.fetch",{fetch:a.jb.prototype.fetch});a.jb.prototype.hasMore=function(){a.i.fa();return!1};a.b.g("PagingDataSource.prototype.hasMore",
{hasMore:a.jb.prototype.hasMore});a.jb.prototype.next=function(){a.i.fa()};a.b.g("PagingDataSource.prototype.next",{next:a.jb.prototype.next});a.jb.prototype.previous=function(){a.i.fa()};a.b.g("PagingDataSource.prototype.previous",{previous:a.jb.prototype.previous});a.jb.prototype.setPageSize=function(){a.i.fa()};a.jb.prototype.startIndex=function(){a.i.fa();return 0};a.b.g("PagingDataSource.prototype.startIndex",{startIndex:a.jb.prototype.startIndex});a.jb.prototype.size=function(){a.i.fa();return 0};
a.b.g("PagingDataSource.prototype.size",{size:a.jb.prototype.size});a.jb.prototype.totalSize=function(){a.i.fa();return 0};a.b.g("PagingDataSource.prototype.totalSize",{totalSize:a.jb.prototype.totalSize});a.jb.v={ADD:"add",REMOVE:"remove",RESET:"reset",SYNC:"sync",REFRESH:"refresh"};o_("PagingDataSource.EventType",a.jb.v,a);(function(){a.Fa("oj.ojPagingControl",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,pageSize:25,pageOptions:{layout:["auto"],
maxPageLinks:6},loadMoreOptions:{maxCount:500},mode:"page"},Xa:{lJ:"labelAccPaging",gJ:"labelAccNavFirstPage",hJ:"labelAccNavLastPage",iJ:"labelAccNavNextPage",kJ:"labelAccNavPreviousPage",jJ:"labelAccNavPage",mJ:"labelLoadMore",nJ:"labelNavInputPage",oJ:"labelNavInputPageMax",pJ:"labelNavInputPageSummary",Ey:"msgItemRange",AJ:"msgItemRangeUnknown",fK:"tipNavInputPage",iK:"tipNavPageLink",hK:"tipNavNextPage",jK:"tipNavPreviousPage",eK:"tipNavFirstPage",gK:"tipNavLastPage",QI:"pageInvalid.summary",
OI:"pageInvalid.detail",hs:"dataInvalidType.summary",gs:"dataInvalidType.detail",NI:"maxPageLinksInvalid.summary",MI:"maxPageLinksInvalid.detail"},Na:{Cs:"oj-component",nf:"oj-active",Ji:"oj-clickable-icon",vb:"oj-disabled",de:"oj-enabled",qf:"oj-focus",Ko:"oj-hover",Xb:"oj-selected"},ma:{HJ:"oj-pagingcontrol",Iy:"oj-pagingcontrol-acc-label",Jy:"oj-pagingcontrol-content",Ky:"oj-pagingcontrol-loadmore",Ly:"oj-pagingcontrol-loadmore-link",My:"oj-pagingcontrol-loadmore-range",Oy:"oj-pagingcontrol-nav",
To:"oj-pagingcontrol-nav-arrow",Ny:"oj-pagingcontrol-nav-arrow-section",RJ:"oj-pagingcontrol-nav-page",QJ:"oj-pagingcontrol-nav-page-acc-label",KJ:"oj-pagingcontrol-nav-label",Ry:"oj-pagingcontrol-nav-input-section",Py:"oj-pagingcontrol-nav-input",Qy:"oj-pagingcontrol-nav-input-max",rs:"oj-pagingcontrol-nav-input-summary",PJ:"oj-pagingcontrol-nav-pages-section",Sy:"oj-pagingcontrol-nav-pages-links",qs:"oj-pagingcontrol-nav-first",IJ:"oj-pagingcontrol-nav-first-acc-label",vs:"oj-pagingcontrol-nav-previous",
SJ:"oj-pagingcontrol-nav-previous-acc-label",us:"oj-pagingcontrol-nav-next",NJ:"oj-pagingcontrol-nav-next-acc-label",ts:"oj-pagingcontrol-nav-last",LJ:"oj-pagingcontrol-nav-last-acc-label",JJ:"oj-pagingcontrol-nav-first-icon",TJ:"oj-pagingcontrol-nav-previous-icon",OJ:"oj-pagingcontrol-nav-next-icon",MJ:"oj-pagingcontrol-nav-last-icon",Mi:"oj-component-icon",sf:"oj-helper-hidden-accessible"},FI:"data-oj-pagenum",Md:"enabled",Hy:"disabled",os:{Dy:"loadMore",FJ:"page"},Ve:{Ii:"auto",$I:"input",UJ:"rangeText",
GJ:"pages",Fy:"nav"},firstPage:function(){var b=this.Ka();if(null!=b){try{this.O=0,b.fetch({startIndex:0})}catch(a){return!1}return!0}return!1},previousPage:function(){var b=this.Ka();if(null!=b){var a=this.wf();try{this.O=this.sk(a-1),b.fetch({startIndex:this.O})}catch(c){return!1}return!0}return!1},nextPage:function(){var b=this.Ka();if(null!=b){var a=this.wf();try{this.O=this.sk(a+1),b.fetch({startIndex:this.O})}catch(c){return!1}return!0}return!1},lastPage:function(){var b=this.Ka();if(null!=
b){try{this.O=this.sk(this.xf()),b.fetch({startIndex:this.O})}catch(a){return!1}return!0}return!1},page:function(b){try{this.O=this.sk(b),this.Ka().fetch({startIndex:this.O})}catch(a){return!1}return!0},loadNext:function(){if(null!=this.Ka()){try{this.Ka().next()}catch(b){return!1}return!0}return!1},refresh:function(){this._super();null!=this.Xi&&(this.Xi=null,this.Ka().fetch({startIndex:this.O}));this.Pb(!0)},getNodeBySubId:function(b){if(null==b)return this.element?this.element[0]:null;var a=b.subId;
return"oj-pagingcontrol-nav-input"===a?this.JN():"oj-pagingcontrol-nav-input-max"===a?this.Ze().find("."+this.ma.Qy):"oj-pagingcontrol-nav-input-summary"===a?this.Ze().find("."+this.ma.rs):"oj-pagingcontrol-nav-first"===a?this.Ze().find("."+this.ma.qs):"oj-pagingcontrol-nav-next"===a?this.Ze().find("."+this.ma.us):"oj-pagingcontrol-nav-previous"===a?this.Ze().find("."+this.ma.vs):"oj-pagingcontrol-nav-last"===a?this.Ze().find("."+this.ma.ts):"oj-pagingcontrol-nav-page"===a?(b=b.index,this.Ze().find("["+
this.FI+"\x3d"+b+"]")):null},_ComponentCreate:function(){this._super();this.cn();this.km();this.dn(this.Ze());this._on(this.vf);var b=this;setInterval(function(){null!=b.UD&&(b.MD(),b.UD=null)},50);setInterval(function(){null!=b.Xi&&(b.Ka().fetch({startIndex:b.O}),b.Xi=null)},100)},_destroy:function(){this.qj()},km:function(){var b=this.options;this.element.addClass(this.ma.HJ);this.element.addClass(this.Na.Cs);this.O=0;this.KL();this.SL();b.mode==this.os.Dy?(this.TL(),this.VL(),this.pA()):this.qA();
null!=this.Ka()&&0==this.Ka().size()&&(this.Ka().setPageSize(b.pageSize),this.Ka().fetch({startIndex:this.O}))},vf:{"click .oj-pagingcontrol-loadmore-link":function(b){this.loadNext();b.preventDefault()},"click .oj-pagingcontrol-nav-page":function(b){var a=f(b.target).attr("data-oj-pagenum");this.page(a);b.preventDefault()},"click .oj-pagingcontrol-nav-first":function(b){this.firstPage();b.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(b){this.previousPage();b.preventDefault()},
"click .oj-pagingcontrol-nav-next":function(b){this.nextPage();b.preventDefault()},"click .oj-pagingcontrol-nav-last":function(b){this.lastPage();b.preventDefault()},"mousedown .oj-pagingcontrol-nav-first":function(b){f(b.target).addClass(this.Na.nf);b.preventDefault()},"mousedown .oj-pagingcontrol-nav-previous":function(b){f(b.target).addClass(this.Na.nf);b.preventDefault()},"mousedown .oj-pagingcontrol-nav-next":function(b){f(b.target).addClass(this.Na.nf);b.preventDefault()},"mousedown .oj-pagingcontrol-nav-last":function(b){f(b.target).addClass(this.Na.nf);
b.preventDefault()},"mouseup .oj-pagingcontrol-nav-first":function(b){f(b.target).removeClass(this.Na.nf);b.preventDefault()},"mouseup .oj-pagingcontrol-nav-previous":function(b){f(b.target).removeClass(this.Na.nf);b.preventDefault()},"mouseup .oj-pagingcontrol-nav-next":function(b){f(b.target).removeClass(this.Na.nf);b.preventDefault()},"mouseup .oj-pagingcontrol-nav-last":function(b){f(b.target).removeClass(this.Na.nf);b.preventDefault()},"change .oj-pagingcontrol-nav-input":function(b){try{var d=
parseInt(f(b.target).val(),10);this.page(d)}catch(c){throw b=this.C(this.Xa.QI),d=this.C(this.Xa.OI),new a.N(b,d,a.N.kb.ERROR);}}},Pb:function(b){b?this.MD():this.UD=!0},MD:function(){this.f!=this.options.data&&(this.bt(),this.Xi=!0);if(this.options.mode==this.os.Dy){var b=this.Ka(),a=this.Bm();null!=b&&b.size()==b.totalSize()?a.css("display","none"):(a.css("display",""),this.KQ())}else this.LQ()},_setOption:function(b,a){this._superApply(arguments);this.Pb(!0)},bt:function(){null!=this.f&&this.qj();
this.f=null},mL:function(){this.Qs=null},nL:function(){this.Ts=this.Ss=this.Rs=null},wf:function(){return 0==this.O?1:Math.ceil((this.O+1)/this.options.pageSize)},Ka:function(){if(!this.f&&null!=this.options.data){var b=this.options.data;if(b instanceof a.jb)this.f=b;else{var b=this.C(this.Xa.hs),d=this.C(this.Xa.gs);throw new a.N(b,d,a.N.kb.ERROR);}this.f.setPageSize(this.options.pageSize);this.cn()}return this.f},AB:function(){var b=this.Ka(),a=this.C(this.Xa.Ey,{pageFrom:this.O,pageTo:0,pageTotal:0});
null!=b&&(a=-1!=b.totalSize()?this.C(this.Xa.Ey,{pageFrom:this.O+1,pageTo:this.O+b.size(),pageTotal:b.totalSize()}):this.C(this.Xa.AJ,{pageFrom:this.O+1,pageTo:this.O+b.size()}));return a},DN:function(){return this.options.pageOptions.maxPageLinks},sk:function(b){var a=(b-1)*this.options.pageSize,c=this.xf();if(0>a)throw"Value must be greater than 0";if(0<c&&b>c)throw"Value cannot be greater than the total number of pages";return a},xf:function(){var b=this.Ka(),a=0;null!=b&&(a=b.totalSize());return-1==
a?-1:Math.ceil(a/this.options.pageSize)},tu:function(){this.Pb()},uu:function(){this.O=0;this.Ka().setPageSize(this.options.pageSize);this.Pb(!0);this.Ka().fetch({startIndex:this.O})},mO:function(){this.Pb();this.Ka().fetch({startIndex:this.O})},vu:function(b){if(this.options.mode==this.os.FJ){var a=this.Ka(),c=0;null!=a&&(c=a.totalSize());a=this.options.pageSize;b=b.index;var e=this.sk(this.wf());if(e!=this.O||b>=e&&b<e+a&&c>a)this.O=e,this.Xi=!0}this.Pb()},wu:function(){0>=this.xf()?this.O=0:this.wf()>
this.xf()&&(this.O=this.sk(this.xf()),this.Xi=!0);1<this.xf()&&(this.Xi=!0);this.Pb()},KQ:function(){var b=this.IN();b[0].parentNode.removeChild(b[0]);this.pA();this.mL()},LQ:function(){var b=this.options.pageOptions.layout;this.Am().empty();this.nL();this.qA();this.MQ();if(-1<f.inArray(this.Ve.Ii,b)){var b=this.element.width(),a=this.HB(),c=this.KN(),e=this.MN(),g=this.LN(),c=a[0].offsetWidth+c[0].offsetWidth;c>b?c-e.width()<=b?e.css("display","none"):c-e.width()-g.width()<=b?(e.css("display","none"),
g.css("display","none")):(e.css("display","none"),g.css("display","none"),a.css("display","none")):0<c&&(e.css("display",""),g.css("display",""),a.css("display",""))}},MQ:function(){var b=this.HB(),a=b.children("."+this.ma.qs);a&&0<a.length&&(a=f(a[0]),1==this.wf()?(a.addClass(this.Na.vb),a.removeClass(this.Na.de),a.attr("tabindex","-1")):(a.addClass(this.Na.de),a.removeClass(this.Na.vb),a.attr("tabindex","0")));(a=b.children("."+this.ma.vs))&&0<a.length&&(a=f(a[0]),1==this.wf()?(a.addClass(this.Na.vb),
a.removeClass(this.Na.de),a.attr("tabindex","-1")):(a.addClass(this.Na.de),a.removeClass(this.Na.vb),a.attr("tabindex","0")));(a=b.children("."+this.ma.ts))&&0<a.length&&(a=f(a[0]),this.wf()==this.xf()?(a.addClass(this.Na.vb),a.removeClass(this.Na.de),a.attr("tabindex","-1")):(a.addClass(this.Na.de),a.removeClass(this.Na.vb),a.attr("tabindex","0")));(b=b.children("."+this.ma.us))&&0<b.length&&(b=f(b[0]),this.wf()==this.xf()?(b.addClass(this.Na.vb),b.removeClass(this.Na.de),b.attr("tabindex","-1")):
(b.addClass(this.Na.de),b.removeClass(this.Na.vb),b.attr("tabindex","0")))},cn:function(){var b=this.Ka();if(null!=b){this.qj();this.Bb=[];this.Bb.push({eventType:a.jb.v.ADD,eventHandler:this.vu.bind(this)});this.Bb.push({eventType:a.jb.v.REMOVE,eventHandler:this.wu.bind(this)});this.Bb.push({eventType:a.jb.v.RESET,eventHandler:this.uu.bind(this)});this.Bb.push({eventType:a.jb.v.REFRESH,eventHandler:this.mO.bind(this)});this.Bb.push({eventType:a.jb.v.SYNC,eventHandler:this.tu.bind(this)});var d;for(d=
0;d<this.Bb.length;d++)b.on(this.Bb[d].eventType,this.Bb[d].eventHandler)}},dn:function(b){if(!this.Mm){var d=this;a.Aa.bh(b[0],function(){d.Pb()});this.Mm=!0}},qj:function(){var b=this.Ka();if(null!=this.Bb&&null!=b){var a;for(a=0;a<this.Bb.length;a++)b.off(this.Bb[a].eventType,this.Bb[a].eventHandler)}},dk:function(b,a){var c=f(document.createElement("span"));c.addClass(a);c.addClass(this.ma.sf);c.append(b);return c},KL:function(){var b=this.Ze(),a=this.C(this.Xa.lJ),a=this.dk(a,this.ma.Iy),c=this.element.attr("id")+
"_oj_pgCtrl_acc_label";a.attr("id",c);b.append(a);return a},QL:function(){var b=this.C(this.Xa.jJ);return this.dk(b,this.ma.QJ)},ML:function(){var b=this.C(this.Xa.gJ);return this.dk(b,this.ma.IJ)},NL:function(){var b=this.C(this.Xa.hJ);return this.dk(b,this.ma.LJ)},PL:function(){var b=this.C(this.Xa.iJ);return this.dk(b,this.ma.NJ)},RL:function(){var b=this.C(this.Xa.kJ);return this.dk(b,this.ma.SJ)},SL:function(){var b=this.Ze(),a=f(document.createElement("div"));a.addClass(this.ma.Jy);var c=this.HN().attr("id");
a.attr("role","navigation");a.attr("aria-labelledby",c);b.append(a);return a},TL:function(){var b=this.Am(),a=f(document.createElement("div"));a.addClass(this.ma.Ky);b.append(a);return a},VL:function(){var b=this.Bm(),a=f(document.createElement("a"));a.addClass(this.ma.Ly);var c=this.C(this.Xa.mJ);a.append(c);a.attr("tabindex","0");a.attr("href","#");b.append(a);return a},pA:function(){this.Ka();var b=this.Bm(),a=f(document.createElement("span"));a.addClass(this.ma.My);var c=this.AB();a.append(c);
b.append(a);return a},qA:function(){var b=this.options.pageOptions.layout;null==b&&(b=[this.Ve.Ii]);var a=this.Am(),c=f(document.createElement("div"));c.addClass(this.ma.Oy);a.append(c);if(-1!=f.inArray(this.Ve.Ii,b)||-1!=f.inArray(this.Ve.$I,b)){a=f(document.createElement("div"));a.addClass(this.ma.Ry);c.append(a);var e=f(document.createElement("label"));e.addClass(this.ma.KJ);var g=this.C(this.Xa.nJ);e.append(g);a.append(e);g=f(document.createElement("input"));g.addClass(this.ma.Py);var h=this.C(this.Xa.fK);
this._focusable(this.element);g.attr("title",h);g.attr("tabindex","0");g.val(this.wf());e.append(g);0<this.xf()&&(e=f(document.createElement("span")),e.addClass(this.ma.Qy),g=this.C(this.Xa.oJ,{pageMax:this.xf()}),e.append(g),a.append(e));if(-1!=f.inArray(this.Ve.Ii,b)||-1!=f.inArray(this.Ve.UJ,b))e=f(document.createElement("span")),e.addClass(this.ma.rs),g=this.AB(),g=this.C(this.Xa.pJ,{pageSummary:g}),e.append(g),a.append(e)}a=f(document.createElement("div"));a.addClass(this.ma.Ny);c.append(a);
if(-1!=f.inArray(this.Ve.Ii,b)||-1!=f.inArray(this.Ve.Fy,b))e=f(document.createElement("a")),e.addClass(this.ma.To),e.addClass(this.ma.qs),e.addClass(this.ma.JJ),e.addClass(this.ma.Mi),e.addClass(this.Na.Ji),e.addClass(this.Na.vb),g=this.C(this.Xa.eK),this._hoverable(e),this._focusable(e),e.attr("title",g),e.attr("tabindex","0"),e.attr("href","#"),g=this.ML(),e.append(g),a.append(e),e=f(document.createElement("a")),e.addClass(this.ma.To),e.addClass(this.ma.vs),e.addClass(this.ma.TJ),e.addClass(this.ma.Mi),
e.addClass(this.Na.Ji),e.addClass(this.Na.vb),g=this.C(this.Xa.jK),this._hoverable(e),this._focusable(e),e.attr("title",g),e.attr("tabindex","0"),e.attr("href","#"),g=this.RL(),e.append(g),a.append(e);if(-1!=f.inArray(this.Ve.Ii,b)||-1!=f.inArray(this.Ve.GJ,b))e=f(document.createElement("div")),e.addClass(this.ma.PJ),a.append(e),this.WL(e,this.DN());if(-1!=f.inArray(this.Ve.Ii,b)||-1!=f.inArray(this.Ve.Fy,b))b=f(document.createElement("a")),b.addClass(this.ma.To),b.addClass(this.ma.us),b.addClass(this.ma.OJ),
b.addClass(this.ma.Mi),b.addClass(this.Na.Ji),b.addClass(this.Na.vb),e=this.C(this.Xa.hK),this._hoverable(b),this._focusable(b),b.attr("title",e),b.attr("tabindex","0"),b.attr("href","#"),e=this.PL(),b.append(e),a.append(b),b=f(document.createElement("a")),b.addClass(this.ma.To),b.addClass(this.ma.ts),b.addClass(this.ma.MJ),b.addClass(this.ma.Mi),b.addClass(this.Na.Ji),b.addClass(this.Na.vb),e=this.C(this.Xa.gK),this._hoverable(b),this._focusable(b),b.attr("title",e),b.attr("tabindex","0"),b.attr("href",
"#"),e=this.NL(),b.append(e),a.append(b);return c},WL:function(b,d){if(5>d){var c=this.C(this.Xa.NI),e=this.C(this.Xa.MI);throw new a.N(c,e,a.N.kb.ERROR);}c=f(document.createElement("div"));c.addClass(this.ma.Sy);b.append(c);var e=this.xf(),g=this.wf(),h=d,k=[];if(1<=g){if(-1!=e&&e<=h)for(h=k[0]=1;h<e;h++)k[h]=h+1;else{k.push(1);1!=g&&k.push(g);g!=e&&-1!=e&&k.push(e);var h=h-k.length,l=g-1,n=1;if(g==e||g==e-1)n=0;for(;h>n&&1<l;)k.push(l),l--,h--;g+=1;for(-1==e&&(h=1);0<h&&(g<=e||-1==e);)k.push(g),
g++,h--}k.sort(function(b,a){return b-a});for(h=0;h<k.length;h++)g=k[h],this.mt(c,g),h!=k.length-1&&g!=k[h+1]-1&&this.mt(c,-1);-1==e&&this.mt(c,-1)}return c},mt:function(b,a){var c=this.wf(),e=null;-1==a?(e=f(document.createElement("span")),e.append("...")):(c==a?(e=f(document.createElement("div")),e.addClass(this.Na.Xb),e.addClass(this.Na.nf),e.addClass(this.Na.vb),e.removeClass(this.Na.de)):(e=f(document.createElement("a")),e.removeClass(this.Na.Xb),e.removeClass(this.Na.nf),e.removeClass(this.Na.vb),
e.addClass(this.Na.de)),e.attr("data-oj-pagenum",a),e.addClass(this.ma.RJ),c=this.C(this.Xa.iK,{pageNum:a.toString()}),this._hoverable(e),this._focusable(e),e.attr("title",c),e.attr("tabindex","0"),e.attr("href","#"),c=this.QL(),e.append(c),e.append(a.toString()),this._hoverable(e));b.append(e);return e},HN:function(){var b=this.Ze(),a=null;b&&(a=b.find("."+this.ma.Iy))&&0<a.length&&(a=f(a.get(0)));return a},Ze:function(){return f(this.element)},Am:function(){if(!this.Kz){var b=this.Ze(),a=null;b&&
(a=b.find("."+this.ma.Jy))&&0<a.length&&(this.Kz=f(a.get(0)))}return this.Kz},Bm:function(){if(!this.Lz){var b=this.Am(),a=null;b&&(a=b.children("."+this.ma.Ky))&&0<a.length&&(this.Lz=f(a.get(0)))}return this.Lz},PV:function(){if(!this.Mz){var b=this.Bm(),a=null;b&&(a=b.children("."+this.ma.Ly))&&0<a.length&&(this.Mz=f(a.get(0)))}return this.Mz},IN:function(){if(!this.Qs){var b=this.Bm(),a=null;b&&(a=b.children("."+this.ma.My))&&0<a.length&&(this.Qs=f(a.get(0)))}return this.Qs},Cm:function(){if(!this.Rs){var b=
this.Am(),a=null;b&&(a=b.children("."+this.ma.Oy))&&0<a.length&&(this.Rs=f(a.get(0)))}return this.Rs},JN:function(){if(!this.Ss){var b=this.Cm(),a=null;b&&(a=b.find("."+this.ma.Py))&&0<a.length&&(this.Ss=f(a.get(0)))}return this.Ss},LN:function(){if(!this.Ts){var b=this.Cm(),a=null;b&&(a=b.find("."+this.ma.rs))&&0<a.length&&(this.Ts=f(a.get(0)))}return this.Ts},MN:function(){var b=this.Cm(),a=null;b&&(a=b.find("."+this.ma.Sy))&&0<a.length&&(a=f(a.get(0)));return a},HB:function(){var b=this.Cm(),a=
null;b&&(a=b.find("."+this.ma.Ny))&&0<a.length&&(a=f(a.get(0)));return a},KN:function(){var b=this.Cm(),a=null;b&&(a=b.find("."+this.ma.Ry))&&0<a.length&&(a=f(a.get(0)));return a}})})()});
//# sourceMappingURL=oj-modular.map