define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){var b="oj-left oj-center oj-right oj-top oj-middle oj-bottom".split(" "),d={"right-top":"oj-right oj-top","right-middle":"oj-right oj-middle","right-bottom":"oj-right oj-bottom","left-top":"oj-left oj-top","left-middle":"oj-left oj-middle","left-bottom":"oj-left oj-bottom","center-top":"oj-center oj-top","center-middle":"oj-left oj-middle","center-bottom":"oj-center oj-bottom"};a.Fa("oj.ojPopup",f.oj.baseComponent,{widgetEventPrefix:"oj",
options:{autoDismiss:"focusLoss",chrome:"default",initialFocus:"none",position:{my:"start top",at:"start bottom",of:"",collision:"flip"},tail:"none",beforeOpen:null,open:null,beforeClose:null,close:null,focus:null},_ComponentCreate:function(){this._super();var a=f("\x3cdiv\x3e");this.ld=a.hide().addClass("oj-popup").attr("aria-hidden","true");a.addClass("oj-helper-reset-inheritable oj-component");var b=f("\x3cdiv\x3e").addClass("oj-popup-content");b.appendTo(a);this.element.after(a);this.element.appendTo(b);
this.element.show();this.uA();this.xE();this.GL();this.xF=f.proxy(this.AS,this)},_destroy:function(){this._super();this.isOpen()&&this.close();this.MA();this.oM();delete this.xF;this.ld.replaceWith(this.element);this.element.hide()},widget:function(){return this.ld},open:function(b,d){if(this.isOpen()&&(this.close(),this.isOpen()))return;this.MR(b);var g=this.ld;b=this.gb;a.i.mb(g,jQuery);a.i.mb(b,jQuery);a.fb.VG(g.attr("id"))&&g.uniqueId();if(!1!==this._trigger("beforeOpen")){this.JE(d);var h=this.options;
this.Dv(h.autoDismiss);this._on(!0,f(window),{resize:this.zv});this._on(!0,g,{keydown:this.HC});this._on(!0,b,{keydown:this.HC});this.xK();g.removeAttr("aria-hidden");g.attr("role","tooltip");d=h.position;g.show();var k="rtl"===this.uc();g.position(a.Eg.co(d,k));this._trigger("open");this.vC();g=this.C("none"===h.initialFocus?"ariaLiveRegionInitialFocusNone":"ariaLiveRegionInitialFocusFirstFocusable");this.wz(g)}},close:function(){if(this.isOpen()&&!1!==this._trigger("beforeClose")){this.pR();var b=
this.gb,d=this.ld;a.i.mb(d,jQuery);a.i.mb(b,jQuery);d.hide();d.attr("aria-hidden","true");this.ZQ();this.Dv();this._off(f(window),"resize");this._off(d,"keydown");this._off(b,"keydown");delete this.gb;b=this.options.position;b._ofo&&(delete b._ofo,delete b.of);this.wz(null);this._trigger("close")}},isOpen:function(){return this.ld.is(":visible")},_setOption:function(a,b){var d=this.options;switch(a){case "tail":b!==d.tail&&this.QR(b);break;case "chrome":b!==d.chrome&&this.xE(b);break;case "position":this.JE(b);
this.isOpen()&&this.zv();return;case "autoDismiss":this.isOpen()&&b!==d.autoDismiss&&this.Dv(b)}this._superApply(arguments)},QV:function(){return"oj-popup"},QR:function(a){this.MA();this.uA(a);this.zv()},uA:function(b){b=b?b:this.options.tail;if("none"!==b){b=["oj-popup-tail",b].join("-");var d=f("\x3cdiv\x3e").hide().addClass("oj-popup-tail").addClass(b);this.fF="#"+d.uniqueId().attr("id");var g=this.ld;a.i.mb(g,jQuery);d.appendTo(g);g.addClass(b)}},VB:function(){var a=this.fF;return a?f(a):null},
MA:function(){var b=this.VB();b&&b.remove();delete this.fF;var b=["oj-popup-tail",this.options.tail].join("-"),d=this.ld;a.i.mb(d,jQuery);d.removeClass(b)},xE:function(b){b=b?b:this.options.chrome;var d=this.ld;a.i.mb(d,jQuery);"default"===b&&d.hasClass("oj-popup-no-chrome")?d.removeClass("oj-popup-no-chrome"):"none"!==b||d.hasClass("oj-popup-no-chrome")||d.addClass("oj-popup-no-chrome")},MR:function(b){b?"string"===f.type(b)?b=f(b):1===b.nodeType&&(b=f(b)):b=f(document.activeElement);if(b instanceof
jQuery&&1<b.length){var d=this.ld;a.i.mb(d,jQuery);for(var g=0;g<b.length;g++){var h=b[0];if(!a.Aa.Mn(d[0],h)){b=f(h);break}}}else if(!(b instanceof jQuery)||b instanceof jQuery&&0===b.length)b=f(document.activeElement);a.i.mb(b,jQuery);this.gb=b},JE:function(b){var d=this.options;b&&(d.position=f.extend(d[b],b));b=d.position;d=this.xF;a.i.ii(d);f.isFunction(b.using)&&b.using!==d&&(b.origUsing=b.using);b.using=d;d=this.gb;a.i.mb(d,jQuery);b.of||(b.of=d,b._ofo=!0)},AS:function(c,e){var f=e.element.element;
a.i.mb(f,jQuery);var h=this.VB();if(h){h.hide();for(var k=0;k<b.length;k++)h.removeClass(b[k]),f.removeClass(b[k]);h.removeAttr("style");k=d[[e.horizontal,e.vertical].join("-")];a.i.vn(k);h.addClass(k);f.addClass(k);h.show();"left"===e.horizontal||"right"===e.horizontal?(k=(h.outerWidth()-1)*("left"===e.horizontal?1:-1),c.left+=k):"center"===e.horizontal&&(k=(h.outerHeight()-1)*("top"===e.vertical?1:-1),c.top+=k);f.css(c);"middle"===e.vertical?(f=f.height(),f=Math.round((f/2-h.outerHeight()/2)/f*
100),h.css({top:f+"%"})):"center"===e.horizontal&&(f=f.width(),f=Math.round((f/2-h.outerWidth()/2)/f*100),h.css({left:f+"%"}));(h=this.options.position.origUsing)&&h(c,e)}else f.css(c)},zv:function(){var b=this.ld;a.i.mb(b,jQuery);var d=this.options.position;a.i.Pd(d);var f="rtl"===this.uc();b.position(a.Eg.co(d,f))},vC:function(b){var d=this.options;if(b||"none"!==d.initialFocus)if(b||"firstFocusable"===d.initialFocus)b=this.element.find(":focusable"),0<b.length?(b=b[0],a.i.$e(b),f(b).focus()):(b=
this.ld,a.i.mb(b,jQuery),b.attr("tabindex","-1"),b.focus()),this._trigger("focus")},Ku:function(b){b||(b=document.activeElement);a.i.$e(b);if(!b)return!1;var d=this.ld;a.i.mb(d,jQuery);return a.Aa.Mn(d[0],b)},tP:function(b){b||(b=document.activeElement);a.i.$e(b);var d=this.gb;a.i.mb(d,jQuery);return a.Aa.Mn(d[0],b)},pR:function(){if(this.Ku()){var b=this.gb;a.i.mb(b,jQuery);b.focus()}},HC:function(b){if(!b.isDefaultPrevented()){var d=b.target;a.i.$e(d);if(27===b.keyCode)b.preventDefault(),this.close();
else if(117===b.keyCode)this.Ku(d)?(b.preventDefault(),b=this.gb,a.i.mb(b,jQuery),b.focus()):this.tP(d)&&(b.preventDefault(),this.vC(!0));else if(9===b.keyCode&&this.Ku(d)){var g=this.element.find(":tabbable");if(0<g.length){var h=g[0];a.i.$e(h);g=g[g.length-1];a.i.$e(g);h===d&&b.shiftKey?(b.preventDefault(),f(g).focus()):g!==d||b.shiftKey||(b.preventDefault(),f(h).focus())}else b.preventDefault(),b=this.gb,a.i.mb(b,jQuery),b.focus()}}},Dv:function(a){var b=document.documentElement,d=this.jB;d&&(b.removeEventListener("mousedown",
d,!0),b.removeEventListener("focus",d,!0),delete this.jB);"focusLoss"===a&&(d=this.jB=f.proxy(this.sM,this),b.addEventListener("mousedown",d,!0),b.addEventListener("focus",d,!0))},sM:function(b){var d=this.gb,f=this.ld;a.i.mb(d,jQuery);a.i.mb(f,jQuery);b=b.target;a.i.$e(b);a.Aa.Mn(d[0],b)||a.Aa.Mn(f[0],b)||this.close()},xK:function(){var b=this.gb,d=this.ld;a.i.mb(b,jQuery);a.i.mb(d,jQuery);var d=d.attr("id"),g=b.attr("aria-describedby"),g=g?g.split(/\s+/):[];g.push(d);g=f.trim(g.join(" "));b.attr("aria-describedby",
g)},ZQ:function(){var b=this.gb,d=this.ld;a.i.mb(b,jQuery);a.i.mb(d,jQuery);var d=d.attr("id"),g=b.attr("aria-describedby"),g=g?g.split(/\s+/):[],d=f.inArray(d,g);-1!==d&&g.splice(d,1);(g=f.trim(g.join(" ")))?b.attr("aria-describedby",g):b.removeAttr("aria-describedby")},GL:function(){var b=this.ld;a.i.mb(b,jQuery);var d=this.$N("ariaLive"),g=this.Qu=f("\x3cdiv\x3e");g.attr({id:d,role:"log","aria-live":"polite","aria-relevant":"additions"});g.addClass("oj-helper-hidden-accessible");g.appendTo(document.body);
b.data("oj-aria-controls",d)},wz:function(b){var d=this.Qu;a.i.mb(d,jQuery);d.children().remove();a.fb.isEmpty(b)||f("\x3cdiv\x3e").text(b).appendTo(d)},oM:function(){var b=this.Qu;a.i.mb(b,jQuery);b.remove();delete this.Qu;b=this.ld;a.i.mb(b,jQuery);b.removeData("oj-aria-controls")},$N:function(a){return this.uuid+"_"+a}})})()});
//# sourceMappingURL=oj-modular.map