/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a,f){a.Fa("oj._ojRadioCheckbox",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{disabled:null,checked:null,type:null},label:function(){void 0===this.Lb&&(this.Lb=this.Xt());return this.Lb},refresh:function(){this._super();var a=this.element.is(":disabled");a!==this.options.disabled&&this._setOption("disabled",a);this.Cb()},widget:function(){return this.PH},_create:function(){this._super();
"boolean"!==typeof this.options.checked&&(this.options.checked=!!this.element.prop("checked"));"boolean"!==typeof this.options.disabled&&(this.options.disabled=!!this.element.prop("disabled"));this.options.type=this.element.prop("type");this.At();this._on(this.vf)},_init:function(){this._super();this.Cb()},Cb:function(){this.options.disabled?this.disable():this.enable();this.options.checked?this._setOption("checked",!0):this._setOption("checked",!1)},vf:{},At:function(){var a=this.options.type;"checkbox"==
a?(this.PH=this.element.addClass("oj-checkbox oj-component"),this.Lb=this.Xt(),this.Lb.addClass("oj-checkbox-label")):"radio"==a&&(this.PH=this.element.addClass("oj-radio oj-component"),this.Lb=this.Xt(),this.Lb.addClass("oj-radio-label"));var d=this;this._hoverable(this.element);this._focusable(this.element);this.Hs(this.element);f.each(d.Lb,function(){d._hoverable(this);d._focusable(this);d.Hs(this)})},_setOption:function(a,d){this._superApply(arguments);"disabled"===a&&((d=!!d)?(this.element.prop("disabled",
!0).removeAttr("aria-disabled").removeClass("oj-enabled").addClass("oj-disabled"),this.Lb.removeClass("oj-enabled").addClass("oj-disabled")):(this.element.prop("disabled",!1).removeAttr("aria-disabled").removeClass("oj-disabled").addClass("oj-enabled"),this.Lb.addClass("oj-enabled").removeClass("oj-disabled")));"checked"===a&&(d?this.element.prop("checked",!0):this.element.prop("checked",!1),this.element.toggleClass("oj-selected",d))},Xt:function(){var a=this.element.closest("label"),d="label[for\x3d'"+
this.element.prop("id")+"']";return a.add(f(d))},getNodeBySubId:function(a){var d=this._super(a);d||(a=a.subId,"oj-radiocheckbox-input"===a&&(d=this.element[0]),"oj-radiocheckbox-label"===a&&(d=this.label()[0]));return d||null},_destroy:function(){this._super();var a=this.options.type;"checkbox"==a?(this.element.removeClass("oj-checkbox oj-selected oj-disabled oj-enabled oj-component"),this.Lb.removeClass("oj-enabled oj-disabled oj-checkbox-label")):"radio"==a&&(this.element.removeClass("oj-radio oj-selected oj-disabled oj-enabled oj-component"),
this.Lb.removeClass("oj-enabled oj-disabled oj-radio-label"))}})});
//# sourceMappingURL=oj-modular.map