/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojmodel","ojs/ojdatacollection-common"],function(a,f){a.Fa("oj.ojRowExpander",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{context:null,indent:10,expand:null,collapse:null},Zk:{root:"oj-rowexpander",icon:"oj-component-icon",clickable:"oj-clickable-icon",expand:"oj-rowexpander-expand-icon",collapse:"oj-rowexpander-collapse-icon",leaf:"oj-rowexpander-leaf-icon",lazyload:"oj-rowexpander-lazyload-icon"},_create:function(){this._super();
this.element.addClass(this.Zk.root)},_init:function(){var a=this,d;this._super();this.yK();d=this.options.context;this.xa=d.component;this.Bc=d.datasource;this.depth=d.depth;this.YT=(this.depth-1)*this.options.indent;this.si=d.state;this.Ei=d.key;this.index=d.index;this.ix=d.parentKey;this.FR();this.Hq();if("expanded"===this.si||"collapsed"===this.si)f(this.icon).on("click",function(){a.fB()}),f(this.element).on("keypress",function(c){((c.keyCode||c.which)===f.ui.keyCode.ENTER||f.ui.keyCode.SPACE)&&
a.fB()}),null!=this.xa&&(this.OG=this.wO.bind(this),f(this.xa.element).on("ojkeydown",this.OG)),null!=this.Bc&&(this.NG=this.rO.bind(this),this.MG=this.iO.bind(this),this.Bc.on("expand",this.NG,this),this.Bc.on("collapse",this.MG,this));null!=this.xa&&(this.LG=this.hO.bind(this),f(this.xa.element).on("ojactive",this.LG))},refresh:function(){this.element.empty();this._init()},_destroy:function(){null!=this.xa&&(f(this.xa.element).off("ojkeydown",this.OG),f(this.xa.element).off("ojactive",this.LG));
null!=this.Bc&&(this.Bc.off("expand",this.NG,this),this.Bc.off("collapse",this.MG,this));this.removeClass(this.Zk.root);this.element.empty()},yK:function(){this.icon=f("\x3ca\x3e\x3c/a\x3e").addClass(this.Zk.icon).addClass(this.Zk.clickable);this.element.append(this.icon)},cp:function(a){this.icon.addClass(this.Zk[a])},Bq:function(a){this.icon.removeClass(this.Zk[a])},Hq:function(){switch(this.si){case "leaf":this.cp("leaf");break;case "collapsed":this.cp("expand");this.fp(!1);break;case "expanded":this.cp("collapse");
this.fp(!0);break;case "loading":this.cp("lazyload")}},xv:function(){switch(this.si){case "leaf":this.Bq("leaf");break;case "collapsed":this.Bq("expand");break;case "expanded":this.Bq("collapse");break;case "loading":this.Bq("lazyload")}},hO:function(a,d){var c;null!=d.activeKey&&(c=d.activeKey.rowKey,this.Ei!==c||null!=d.previousActiveKey&&d.previousActiveKey.row==d.activeKey.row||!this.xa.vE||(c=this.C("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.Bc.getWrappedDataSource().df(this.ix)}),
this.xa.vE({message:c})))},wO:function(a,d){var c;this.Ei===d.rowKey&&(c=a.keyCode||a.which,a.ctrlKey&&(c==f.ui.keyCode.RIGHT?(this.Su(),this.Bc.expand(this.Ei)):c==f.ui.keyCode.LEFT&&(this.Su(),this.Bc.collapse(this.Ei))))},Su:function(){this.xv();this.si="loading";this.Hq()},rO:function(a){a.rowKey===this.Ei&&(this.xv(),this.si="expanded",this.Hq(),this.fp(!0),this._trigger("expand"))},iO:function(a){a.rowKey===this.Ei&&(this.xv(),this.si="collapsed",this.Hq(),this.fp(!1),this._trigger("collapse"))},
fB:function(){var a=this.si;this.Su();"collapsed"===a?this.Bc.expand(this.Ei):"expanded"===a&&this.Bc.collapse(this.Ei)},FR:function(){this.uc();this.element.width(this.element.width()+this.YT+"px")},fp:function(a){this.icon.attr("aria-expanded",a)}})});
//# sourceMappingURL=oj-modular.map