/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtSunburst"],function(a,f){a.Se=function(a){this.f=a};o_("SunburstNode",a.Se,a);a.Se.prototype.nd=function(){return this.f?this.f.color:null};a.b.g("SunburstNode.prototype.getColor",{nd:a.Se.prototype.nd});a.Se.prototype.je=function(){return this.f?this.f.label:null};a.b.g("SunburstNode.prototype.getLabel",{je:a.Se.prototype.je});a.Se.prototype.Fn=function(){return this.f?this.f.size:null};a.b.g("SunburstNode.prototype.getSize",
{Fn:a.Se.prototype.Fn});a.Se.prototype.le=function(){return this.f?this.f.tooltip:null};a.b.g("SunburstNode.prototype.getTooltip",{le:a.Se.prototype.le});a.Se.prototype.isSelected=function(){return this.f?this.f.selected:!1};a.b.g("SunburstNode.prototype.isSelected",{isSelected:a.Se.prototype.isSelected});a.Fa("oj.ojSunburst",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{rotate:null,rotateInput:null,select:null},pf:function(a,d,c){return DvtSunburst.newInstance(a,d,c)},Ue:function(){var a=
this._super();a.push("oj-sunburst");return a},Ki:function(){var a=this._super();a["oj-sunburst-attribute-type-text"]={path:"styleDefaults/_attributeTypeTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-attribute-value-text"]={path:"styleDefaults/_attributeValueTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-node"]={path:"nodeDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-node oj-hover"]={path:"nodeDefaults/hoverColor",property:"border-top-color"};a["oj-sunburst-node oj-selected"]=
[{path:"nodeDefaults/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/selectedInnerColor",property:"border-bottom-color"}];return a},Rl:function(){var a=this._super();a["DvtSunburstBundle.COLOR"]=this.vc("labelColor");a["DvtSunburstBundle.SIZE"]=this.vc("labelSize");return a},Li:function(a){var d=a&&a.getType?a.getType():null,c,e;if(d===DvtSelectionEvent.TYPE){d=[];a=a.getSelection();for(e=0;e<a.length;e++)c={id:a[e]},d.push(c);this.options.selectedNodes=a;this._trigger("select",
null,{items:d})}else d===DvtSunburstRotationEvent.TYPE?(this.options.startAngle=a.getStartAngle(),this._trigger("rotate",null,{value:a.getStartAngle()})):d===DvtSunburstRotationEvent.TYPE_INPUT?this._trigger("rotateInput",null,{value:a.getStartAngle()}):this._super(a)},ns:function(){null==this.options._resources&&(this.options._resources={});this.options._resources.rotateCursor=a.ha.ab("resources/internal-deps/dvt/sunburst/rotate.cur")},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},
getNode:function(b){var d=this.ta.getAutomation();return new a.Se(d.getNode(b))}})});
//# sourceMappingURL=oj-modular.map