/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojmodel","ojs/ojdatacollection-common","ojs/ojtable"],function(a,f){a.nb=function(b,d){a.nb._init(this,b,d,null)};o_("ModelRow",a.nb,a);a.b.oa(a.nb,a.eb,"ModelRow.ModelRow");a.nb.prototype.Init=function(){a.eb.t.Init.call(this)};a.nb.prototype.attributes={};a.b.g("ModelRow.prototype.attributes",{attributes:a.nb.prototype.attributes});a.nb.prototype.id=null;a.b.g("ModelRow.prototype.id",{id:a.nb.prototype.id});a.nb.prototype.He=null;a.b.g("ModelRow.prototype.idAttribute",
{He:a.nb.prototype.He});a.nb._init=function(a,d,c,e){var f=null;a.Init();a.jj=d;a.id=d.id;a.He=d.He;a.attributes=d.attributes;a.index=d.index;c=c||{};for(f in e)e.hasOwnProperty(f)&&(a[f]=e[f]);a.context=c.context};a.nb.prototype.clone=function(){return this.jj.clone()};a.b.g("ModelRow.prototype.clone",{clone:a.nb.prototype.clone});a.nb.prototype.get=function(a){return this.jj.get(a)};a.b.g("ModelRow.prototype.get",{get:a.nb.prototype.get});a.nb.prototype.Hw=function(){return this.jj};a.b.g("ModelRow.prototype.getModel",
{Hw:a.nb.prototype.Hw});a.nb.prototype.set=function(a,d,c){return this.jj.set(a,d,c)};a.b.g("ModelRow.prototype.set",{set:a.nb.prototype.set});a.nb.prototype.keys=function(){return this.jj.keys()};a.b.g("ModelRow.prototype.keys",{keys:a.nb.prototype.keys});a.nb.prototype.values=function(){return this.jj.values()};a.b.g("ModelRow.prototype.values",{values:a.nb.prototype.values});a.nb.prototype.pairs=function(){return this.jj.pairs()};a.b.g("ModelRow.prototype.pairs",{pairs:a.nb.prototype.pairs});a.Ea=
function(b,d){a.Ea._init(this,b,d,null)};o_("CollectionRowSet",a.Ea,a);a.Ea.prototype.af=null;a.b.g("CollectionRowSet.prototype.comparator",{af:a.Ea.prototype.af});a.Ea.prototype.Mf=!0;a.b.g("CollectionRowSet.prototype.sortSupported",{Mf:a.Ea.prototype.Mf});a.b.oa(a.Ea,a.U,"CollectionRowSet.CollectionRowSet");a.Ea.prototype.Init=function(){a.Ea.t.Init.call(this)};a.Ea._init=function(a,d,c,e){var f;a.Nb=[];a.O=0;a.Init();if(e)for(f in e)e.hasOwnProperty(f)&&(a[f]=e[f]);a.lc=d;a.tK()};a.Ea.prototype.at=
function(b,d){var c=this.lc.at(b,d);if(null!=c){if(c instanceof a.q)return new a.nb(c);var e=f.Deferred();f.when(c).done(function(b){e.resolve(new a.nb(b))});return e}return null};a.b.g("CollectionRowSet.prototype.at",{at:a.Ea.prototype.at});a.Ea.prototype.fetch=function(a){if(this.jL.call(this)){this.Nv.call(this);a=a||{};var d=this,c=null!=a.startIndex?!0:!1;this.O=c?a.startIndex:0;var e=0<a.pageSize?a.pageSize:-1;a.pageSize=e;a.startIndex=this.O;a.refresh=!0;c?this.lc.Gr(this.O,e).done(function(){d.qm.call(d,
a)}):this.lc.fetch({success:function(c){d.lc=c;d.qm.call(d,a)}})}};a.b.g("CollectionRowSet.prototype.fetch",{fetch:a.Ea.prototype.fetch});a.Ea.prototype.get=function(b,d){return new a.nb(this.lc.get(b,d))};a.b.g("CollectionRowSet.prototype.get",{get:a.Ea.prototype.get});a.Ea.prototype.getCollection=function(){return this.lc};a.b.g("CollectionRowSet.prototype.getCollection",{getCollection:a.Ea.prototype.getCollection});a.Ea.prototype.hasMore=function(){return this.lc.hasMore};a.b.g("CollectionRowSet.prototype.hasMore",
{hasMore:a.Ea.prototype.hasMore});a.Ea.prototype.indexOf=function(a,d){return this.lc.indexOf(a.Hw(),d)};a.b.g("CollectionRowSet.prototype.indexOf",{indexOf:a.Ea.prototype.indexOf});a.Ea.prototype.isEmpty=function(){return this.lc.isEmpty()};a.b.g("CollectionRowSet.prototype.isEmpty",{isEmpty:a.Ea.prototype.isEmpty});a.Ea.prototype.size=function(){return this.lc.size()};a.b.g("CollectionRowSet.prototype.size",{size:a.Ea.prototype.size});a.Ea.prototype.sort=function(){this.lc.comparator=this.comparator;
return this.lc.sort(null)};a.b.g("CollectionRowSet.prototype.sort",{sort:a.Ea.prototype.sort});a.Ea.prototype.totalSize=function(){return this.lc.totalResults};a.b.g("CollectionRowSet.prototype.totalSize",{totalSize:a.Ea.prototype.totalSize});a.Ea.prototype.tK=function(){var b=this;this.lc.on(a.X.v.ADD,function(d){a.Ea.t.xc.call(b,a.U.v.ADD,new a.nb(d))});this.lc.on(a.X.v.REMOVE,function(d){a.Ea.t.xc.call(b,a.U.v.REMOVE,new a.nb(d))});this.lc.on(a.X.v.RESET,function(d){a.Ea.t.xc.call(b,a.U.v.RESET,
d)});this.lc.on(a.X.v.SORT,function(d,c){null!=c&&c.add||a.Ea.t.xc.call(b,a.U.v.SORT,d)});this.lc.on(a.X.v.CHANGE,function(d){a.Ea.t.xc.call(b,a.U.v.CHANGE,new a.nb(d))});this.lc.on(a.X.v.DESTROY,function(d){a.Ea.t.xc.call(b,a.U.v.REMOVE,d)});this.lc.on(a.X.v.REFRESH,function(d){a.Ea.t.xc.call(b,a.U.v.REFRESH,d)});this.lc.on(a.X.v.ERROR,function(d){a.Ea.t.xc.call(b,a.U.v.ERROR,d);b.qm.call(b,{refresh:!1})})};a.Ea.prototype.jL=function(){return!this.xC};a.Ea.prototype.Nv=function(){this.xC=!0;a.Ea.t.xc.call(this,
a.U.v.REQUEST,null)};a.Ea.prototype.qm=function(b){this.xC=!1;a.Ea.t.xc.call(this,a.U.v.SYNC,b)};a.Sb=function(b,d){this.data={};if(!(b instanceof a.j))throw Error(a.D.wc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.D.wc._ERR_DATA_INVALID_TYPE_DETAIL);a.Sb.t.constructor.call(this,b,d);this.ca=new a.Ea(b,this.options);this.Yl();this.Init();if(null!=d&&("enabled"==d.startFetch||null==d.startFetch)||null==d){var c=this;setTimeout(function(){c.fetch({startFetch:"enabled"})},0)}};o_("CollectionTableDataSource",
a.Sb,a);a.b.oa(a.Sb,a.D,"oj.CollectionTableDataSource");a.Sb.prototype.Init=function(){a.Sb.t.Init.call(this)};a.b.g("CollectionTableDataSource.prototype.Init",{Init:a.Sb.prototype.Init});a.Sb.prototype.at=function(a){return this.ca.at(a)};a.b.g("CollectionTableDataSource.prototype.at",{at:a.Sb.prototype.at});a.Sb.prototype.fetch=function(b){b=b||{};null!=b.startIndex&&a.Sb.t.startIndex.call(this,b.startIndex);"enabled"==b.startFetch?(this.ca.isEmpty()||"undefined"===typeof this.ca.size())&&this.ca.fetch(b):
this.ca.fetch(b)};a.b.g("CollectionTableDataSource.prototype.fetch",{fetch:a.Sb.prototype.fetch});a.Sb.prototype.get=function(a){return this.ca.get(a)};a.b.g("CollectionTableDataSource.prototype.get",{get:a.Sb.prototype.get});a.Sb.prototype.hasMore=function(){return null!=this.ca?this.ca.hasMore():!1};a.b.g("CollectionTableDataSource.prototype.hasMore",{hasMore:a.Sb.prototype.hasMore});a.Sb.prototype.indexOf=function(a){return this.ca.indexOf(a)};a.b.g("CollectionTableDataSource.prototype.indexOf",
{indexOf:a.Sb.prototype.indexOf});a.Sb.prototype.size=function(){return this.ca.size()};a.b.g("CollectionTableDataSource.prototype.size",{size:a.Sb.prototype.size});a.Sb.prototype.sort=function(a){var d=a.key;a=a.direction;var c=null;"ascending"==a?c=function(a){return f.isFunction(a.get)?a.get(d):a[d]()}:"descending"==a&&(c=function(a,b){var c,k;f.isFunction(a.get)?(c=a.get(d),k=b.get(d)):(c=a[d](),k=b[d]());return c===k?0:c>k?-1:1});this.ca.comparator=c;this.ca.sort()};a.b.g("CollectionTableDataSource.prototype.sort",
{sort:a.Sb.prototype.sort});a.Sb.prototype.totalSize=function(){return this.ca.totalSize()};a.b.g("CollectionTableDataSource.prototype.totalSize",{totalSize:a.Sb.prototype.totalSize});a.Sb.prototype.Yl=function(){var b=this;this.ca.on(a.U.v.ADD,function(d){b.Tc=!1;a.D.t.handleEvent.call(b,a.D.v.ADD,d)});this.ca.on(a.U.v.REMOVE,function(d){b.Tc=!1;a.D.t.handleEvent.call(b,a.D.v.REMOVE,d)});this.ca.on(a.U.v.REQUEST,function(d){b.Tc=!0;a.D.t.handleEvent.call(b,a.D.v.REQUEST,d)});this.ca.on(a.U.v.RESET,
function(d){b.Tc=!1;a.D.t.handleEvent.call(b,a.D.v.RESET,d)});this.ca.on(a.U.v.REFRESH,function(d){b.Tc=!1;a.D.t.handleEvent.call(b,a.D.v.REFRESH,d)});this.ca.on(a.U.v.SORT,function(d){b.Tc=!1;a.D.t.handleEvent.call(b,a.D.v.SORT,d)});this.ca.on(a.U.v.CHANGE,function(d){b.Tc=!1;a.D.t.handleEvent.call(b,a.D.v.CHANGE,d)});this.ca.on(a.U.v.SYNC,function(d){b.Tc=!1;a.D.t.handleEvent.call(b,a.D.v.SYNC,d)});this.ca.on(a.U.v.ERROR,function(d){b.Tc=!1;a.D.t.handleEvent.call(b,a.D.v.ERROR,d)})}});
//# sourceMappingURL=oj-modular.map