/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtThematicMap"],function(a,f){a.Fa("oj.ojThematicMap",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{select:null,load:null},jn:{},Ru:[],cm:[],bS:"ar cs da de el es fi fr hu it iw ja ko nl no pl pt pt_BR ro ru sk sv th tr zh_CN zh_TW".split(" "),pf:function(a,d,c){return DvtThematicMap.newInstance(a,d,c)},Ue:function(){var a=this._super();a.push("oj-thematicmap");return a},Ki:function(){var a=
this._super();a["oj-dvtbase oj-thematicmap"]={path:"animationDuration",property:"animation-duration"};a["oj-thematicmap-arealayer"]=[{path:"styleDefaults/areaStyle",property:"CSS_BACKGROUND_PROPERTIES"},{path:"styleDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"}];a["oj-thematicmap-area"]={path:"styleDefaults/dataAreaDefaults/borderColor",property:"border-top-color"};a["oj-thematicmap-area oj-hover"]={path:"styleDefaults/dataAreaDefaults/hoverColor",property:"border-top-color"};a["oj-thematicmap-area oj-selected"]=
[{path:"styleDefaults/dataAreaDefaults/selectedInnerColor",property:"border-top-color"},{path:"styleDefaults/dataAreaDefaults/selectedOuterColor",property:"border-bottom-color"}];a["oj-thematicmap-marker"]=[{path:"styleDefaults/dataMarkerDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"},{path:"styleDefaults/dataMarkerDefaults/color",property:"background-color"},{path:"styleDefaults/dataMarkerDefaults/opacity",property:"opacity"},{path:"styleDefaults/dataMarkerDefaults/borderStyle",property:"border-style"},
{path:"styleDefaults/dataMarkerDefaults/borderColor",property:"border-top-color"},{path:"styleDefaults/dataMarkerDefaults/borderWidth",property:"border-width"}];return a},Zf:function(){this.FP();for(var a=0;a<this.cm.length;a++)if(!this.Ru[this.cm[a]])return;this.cm=[];this._super();this._trigger("load",null,null)},FP:function(){var b=this.options.basemap;if(b){var d=a.ha.De(),b=b.charAt(0).toUpperCase()+b.slice(1),c=this.options.areaLayers;if(c)for(var e=0;e<c.length;e++){var f=c[e].layer;f&&(f=
f.charAt(0).toUpperCase()+f.slice(1),this.LC(b,f,d))}(c=this.options.pointDataLayers)&&0<c.length&&this.LC(b,"Cities",d)}},OC:function(b){if(!this.Ru[b]){var d=a.ha.ab(b),c=this,e=this.Ru;f.getScript(d,function(){e[b]=!0;c.Zf()})}},LC:function(a,d,c){var e="resources/internal-deps/dvt/thematicMap/basemaps/DvtBaseMap"+a+d+".js";this.cm.push(e);if(-1===c.indexOf("en")){var f=c.split("_");c=[];for(var h=0;h<f.length;h++){for(var k="",l=0;l<h+1;l++)0!=l&&(k+="_"),k+=f[l];c.push(k)}a="resources/internal-deps/dvt/thematicMap/resourceBundles/"+
a+d+"Bundle";for(d=c.length-1;0<=d;d++)if(-1!==this.bS.indexOf(c[d])){c=a+"_"+c[d]+".js";this.cm.push(c);this.OC(c);break}}this.OC(e)},Li:function(a){var d,c,e;if((a&&a.getType?a.getType():null)===DvtSelectionEvent.TYPE){d=[];c=a.getSelection();var f=a.getParamValue("clientId");for(a=0;a<c.length;a++)e={id:c[a],dataLayerId:f},d.push(e),this.jn[f]=c;this.wS();this._trigger("select",null,{items:d})}else this._super(a)},wS:function(){var a=this.options.pointDataLayers;if(a)for(var d=0;d<a.length;d++)this.jn[a[d].id]&&
(a[d].selectedItems=this.jn[a[d].id]);a=this.options.areaLayers;for(d=0;d<a.length;d++){var c=a[d].areaDataLayer;this.jn[c.id]&&(c.selectedItems=this.jn[c.id])}},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getArea:function(b,d){var c=this.ta.getAutomation();return new a.Vf(c.getData(b,"area",d))},getMarker:function(b,d){var c=this.ta.getAutomation();return new a.Wf(c.getData(b,"marker",d))}});a.Wf=function(a){this.f=a};o_("ThematicMapMarker",
a.Wf,a);a.Wf.prototype.nd=function(){return this.f?this.f.color:null};a.b.g("ThematicMapMarker.prototype.getColor",{nd:a.Wf.prototype.nd});a.Wf.prototype.le=function(){return this.f?this.f.tooltip:null};a.b.g("ThematicMapMarker.prototype.getTooltip",{le:a.Wf.prototype.le});a.Wf.prototype.je=function(){return this.f?this.f.label:null};a.b.g("ThematicMapMarker.prototype.getLabel",{je:a.Wf.prototype.je});a.Wf.prototype.isSelected=function(){return this.f?this.f.isSelected:!1};a.b.g("ThematicMapMarker.prototype.isSelected",
{isSelected:a.Wf.prototype.isSelected});a.Vf=function(a){this.f=a};o_("ThematicMapArea",a.Vf,a);a.Vf.prototype.nd=function(){return this.f?this.f.color:null};a.b.g("ThematicMapArea.prototype.getColor",{nd:a.Vf.prototype.nd});a.Vf.prototype.le=function(){return this.f?this.f.tooltip:null};a.b.g("ThematicMapArea.prototype.getTooltip",{le:a.Vf.prototype.le});a.Vf.prototype.je=function(){return this.f?this.f.label:null};a.b.g("ThematicMapArea.prototype.getLabel",{je:a.Vf.prototype.je});a.Vf.prototype.isSelected=
function(){return this.f?this.f.isSelected:!1};a.b.g("ThematicMapArea.prototype.isSelected",{isSelected:a.Vf.prototype.isSelected})});
//# sourceMappingURL=oj-modular.map