/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){function b(a,b){var e=a.name,g=a.form;e?(e=e.replace(/'/g,"\\'"),e=":radio[name\x3d'"+e+"']:oj-button",g=b?b.filter(e):g?f(g).find(e):f(e,a.ownerDocument).filter(function(){return!this.form})):g=(b?b.filter(a):f(a)).filter(":oj-button");return g}a.Fa("oj.ojToolbar",f.oj.baseComponent,{Ou:"button, input[type\x3dbutton], input[type\x3dsubmit], input[type\x3dreset], input[type\x3dcheckbox], input[type\x3dradio], a",widgetEventPrefix:"oj",
options:{},_create:function(){this.element.addClass("oj-toolbar oj-component").attr("role","toolbar");this.Cb(!0);this._super()},Zg:function(a,b){a.show(b,{launcher:this.element.find(":oj-button[tabindex\x3d0]"),focus:"menu"})},_setOption:function(a,b){"disabled"===a&&this.Dc.ojButton("option",a,b);this._superApply(arguments)},refresh:function(){this._super();this.Cb(!1)},Cb:function(a){var b=this;this.zj="rtl"===this.uc();this.Dc=this.element.find(this.Ou).unbind("keydown"+this.eventNamespace).bind("keydown"+
this.eventNamespace,function(a){b.xu(a,f(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){f(this).ojButton("option","disabled")||b.nj(f(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.nj(f(this))});this.xg=this.Dc.filter(function(){return!f(this).ojButton("option","disabled")});this.Gu(a)},Gu:function(a){var b=f(this.ij);this.ij=void 0;this.Dc.attr("tabindex","-1");a=a||!b.is(this.xg)?this.xg.first():b;this.nj(a)},
Uu:function(a){var c=this.xg;return a.map(function(a,d){if("radio"!=d.type||d.checked||""==d.name)return d;var f=b(d,c).filter(":checked");return f.length?f[0]:d})},nj:function(a){a=this.Uu(a);var b=a[0],e=this.ij;b!==e&&(f(e).attr("tabindex","-1"),a.attr("tabindex","0"),this.ij=b)},xu:function(a,b){switch(a.which){case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.preventDefault();var e=this.xg,g=e.length;if(2>g)break;var h=e.index(b);e.eq((h+(a.which==f.ui.keyCode.RIGHT^this.zj?1:-1)+g)%g).focus();
break;case f.ui.keyCode.UP:case f.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-toolbar oj-component").removeAttr("role");this.Dc.attr("tabindex","0").map(function(){return f(this).ojButton("widget")[0]})}})})()});
//# sourceMappingURL=oj-modular.map