/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){function b(a){var b=!1,c=!0;a.Ir&&(a.title&&(b=f("style[id\x3d'"+a.title+"-stylesheet']")[0]),b?c=!1:(b=document.createElement("style"),b.setAttribute("type","text/css"),a.title&&b.setAttribute("id",a.title+"-stylesheet")),b.styleSheet?c?(document.getElementsByTagName("head")[0].appendChild(b),b.styleSheet.cssText=a.Ir):b.styleSheet.cssText=b.styleSheet.cssText+" "+a.Ir:(b.appendChild(document.createTextNode(a.Ir)),document.getElementsByTagName("head")[0].appendChild(b)))}
function d(a){m.push(a);f(a.uE).keydown(c)}function c(a){var b="";a.ctrlKey?b+="ctrl+":a.shiftKey&&(b+="shift+");var c=a.which;switch(c){case 32:b+="space";break;case 37:b+="left";break;case 38:b+="up";break;case 39:b+="right";break;case 40:b+="down";break;case 46:b+="del";break;case 33:b+="pgup";break;case 34:b+="pgdn";break;case 35:b+="end";break;case 36:b+="home";break;case 56:b="*";break;case 113:b+="f"+(1-(112-c))}if(0!==b.length){var d=void 0;f.each(m,function(c,e){if(e.hF.f.ui.Ud&&e.dC[b])return a.preventDefault(),
d=e.dC[b].call(e.hF,a),!1});return d}}function e(a){f.each(m,function(b){if(m[b].uE===a)return f(a).off("keydown"),m[b]=null,m.splice(b,1),!1})}var g={cut:"ojtreecut",copy:"ojtreecopy",paste:"ojtreepaste",remove:"ojtreeremove",rename:"ojtreerename"},h="select deselect hover dehover expand collapse loaded move remove deselectAll rename refresh expandAll collapseAll destroy create before remove cut copy paste".split(" "),k,l,n;f(function(){/msie/.test(navigator.userAgent.toLowerCase())?(l=f('\x3ctextarea cols\x3d"10" rows\x3d"2"\x3e\x3c/textarea\x3e').css({position:"absolute",
top:-1E3,left:0}).appendTo("body"),n=f('\x3ctextarea cols\x3d"10" rows\x3d"2" style\x3d"overflow: hidden;"\x3e\x3c/textarea\x3e').css({position:"absolute",top:-1E3,left:0}).appendTo("body"),k=l.width()-n.width(),l.add(n).remove()):(l=f("\x3cdiv /\x3e").css({width:100,height:100,overflow:"auto",position:"absolute",top:-1E3,left:0}).prependTo("body").append("\x3cdiv /\x3e").find("div").css({width:"100%",height:200}),k=100-l.width(),l.parent().remove())});var m=[],q=-1,t=[];a.Fa("oj.ojTree",f.oj.baseComponent,
{version:"1.0.0",widgetEventPrefix:"oj",defaultElement:"\x3cdiv\x3e",options:{animDuration:500,dnd:{wl:"disable"},expandParents:!1,initExpanded:null,$T:[],selectionMode:"single",selectedParentCollapse:!1,selectedParentExpand:!0,selectPrevOnDelete:!1,data:null,emptyText:null,icons:!0,types:null,before:null,collapse:null,create:null,collapseAll:null,cut:null,dehover:null,remove:null,deselect:null,deselectAll:null,destroy:null,expand:null,expandAll:null,hover:null,loaded:null,move:null,paste:null,refresh:null,
rename:null,select:null},collapse:function(a,b){a=this.na(a);var c=b||this.options.animDuration,d=this;if(!a.length||-1===a||!a.hasClass("oj-tree-open")||this.f.F.locked||a.hasClass("oj-disabled"))return!1;var e=this.wa({obj:a,func:"collapse"},"before");if("boolean"!=typeof e||e)c&&a.children("ul").attr("style","display:block !important"),a.removeClass("oj-tree-open").addClass("oj-tree-closed").attr("aria-expanded","false"),c?a.children("ul").stop(!0,!0).slideUp(c,function(){this.style.display="";
d.after_close(a)}):d.after_close(a),this.wa({obj:a},"collapse")},collapseAll:function(a,b){var c=a?a:-1,d=this;if(!this.f.F.locked&&((a=a?this.na(a):this.ea)&&-1!==c&&(c=a),a&&-1!==c||(a=this.aa),!a.hasClass("oj-disabled"))){var e;-1!==c&&this.isExpanded(a)&&(e=a[0]);var f=a.find("li.oj-tree-open");f.length&&f.each(function(){d.collapse(this,!b)});e&&(this.collapse(e,!b),f.splice(0,0,e));f.length&&this.wa({obj:f,targ:c},"collapseAll")}},expand:function(a,b){this.cg(a,!1,b)},expanded:function(a,b){var c,
d,e=this;if(a&&"array"===f.type(a)){if(this.f.F.locked)return null;d=a.length;f.each(a,function(a,c){e.cg(c,!1,b)});return null}a=this.aa.find("li.oj-tree-open");d=a.length;c=[];for(var g=0;g<d;g++)c.push(a[g]);return f(c)},expandAll:function(a,b){this.Ct(a,b)},toggleExpand:function(a,b){a=this.na(a);if(-1!==a&&!a.hasClass("oj-disabled")&&!this.f.F.locked){if(a.hasClass("oj-tree-closed"))return this.expand(a,b);if(a.hasClass("oj-tree-open"))return this.collapse(a,b)}},deselect:function(a){a=this.na(a);
if(!a.length)return!1;a.hasClass("oj-disabled")||this.f.F.locked||!this.isSelected(a)||(a.children("a").removeClass("oj-tree-clicked"),a.removeAttr("aria-selected"),this.f.ui.selected=this.f.ui.selected.not(a),this.f.ui.Ib.get(0)===a.get(0)&&(this.f.ui.Ib=this.f.ui.selected.eq(0)),this.wa({obj:a},"deselect"))},deselectAll:function(a){this.f.F.locked||this.mM(a,!1)},select:function(a){this.Pk(a)},selected:function(a){if(this.f.F.locked)return null;if(void 0===a)return this.VN();if(void 0!==a.length){var b=
this;f.each(a,function(a,c){c&&b.Pk(c,!0)})}return null},toggleSelect:function(a){a=this.na(a);if(!a.length)return!1;a.hasClass("oj-disabled")||this.f.F.locked||(this.isSelected(a)?this.deselect(a):this.Pk(a,!0))},isCollapsed:function(a){return(a=this.na(a))&&-1!==a&&a.hasClass("oj-tree-closed")},isExpanded:function(a){return(a=this.na(a))&&-1!==a&&a.hasClass("oj-tree-open")},isLeaf:function(a){return this.BC(a)},isSelected:function(a){return 0<=this.f.ui.selected.index(this.na(a))},create:function(a,
b,c){return this.ot(a,b,c)},remove:function(a){a=this.na(a);if(!a.length||a.hasClass("oj-disabled")||this.f.F.locked)return!1;var b=this.wa({obj:a,func:"remove"},"before");if("boolean"==typeof b&&!b)return!1;this.Oi();var b=this.Nh(a),c=f([]),d=this,e=this.Vg(a);a.each(function(){c=c.add(d.Vg(this))});a=a.detach();-1!==b&&0===b.find("\x3e ul \x3e li").length&&b.removeClass("oj-tree-open oj-tree-closed").addClass("oj-tree-leaf").removeAttr("aria-expanded");this.ge(b);this.wa({obj:a,prev:e,parent:b},
"remove");return a},getText:function(a){a=this.na(a);if(!a.length)return!1;var b=this.f.F.ml;a=a.children("a:eq(0)");if(b)return a=a.clone(),a.children("INS").remove(),a.html();a=a.find("span:eq(0)");return a[0].textContent},rename:function(a,b){this.gE(a,b)},hover:function(a){a=this.na(a);if(!a.length)return!1;if(!a.hasClass("oj-disabled")&&!this.f.F.locked){var b=this.wa({obj:a,func:"hover"},"before");if("boolean"!=typeof b||b)a.hasClass("oj-tree-hovered")||this.dehover(),this.f.ui.zb=a.children("a").addClass("oj-tree-hovered").parent(),
this.aa.attr("aria-activedescendant",this.f.ui.zb.attr("id")),this.hB(a),this.wa({obj:a},"hover")}},dehover:function(){var a=this.f.ui.zb,b;if(!a||!a.length)return!1;a.hasClass("oj-disabled")||this.f.F.locked||(b=a.children("a").removeClass("oj-tree-hovered").parent(),this.aa.removeAttr("aria-activedescendant"),this.f.ui.zb[0]===b[0]&&(this.f.ui.zb=null),this.wa({obj:a},"dehover"))},getPath:function(a,b){var c=[],d=this;a=this.na(a);if(-1===a||!a||!a.length)return!1;a.parentsUntil(".oj-tree","li").each(function(){c.push(b?
this.id:d.getText(this))});c.reverse();c.push(b?a.attr("id"):this.getText(a));return c},getRoot:function(){return this.ea.children("ul:eq(0)")},refresh:function(a){this._super();this.f.F.locked||this.Pb(a)},move:function(a,b,c,d){this.Hk(a,b,c,d)},getType:function(a){return this.ru(a)},setType:function(a,b){return this.RR(a,b)},getNodeBySubId:function(a){return a?this.DQ(a):this.element?this.element[0]:null},getParent:function(a){return(a=this.Nh(a))&&0<a.length?a:null},getPrevSibling:function(a){return(a=
this.Vg(a,!0))&&0<a.length?a:null},getNextSibling:function(a){return(a=this.aj(a,!0))&&0<a.length?a:null},getChildren:function(a){return(a=this.fN(a?a:-1))&&0<a.length?a:null},destroy:function(){this.wa({obj:-1},"destroy");this._super()},_ComponentCreate:function(){this._super();this.WA="#"+this.element.attr("id");var a;a=(a=this.WA)?a.replace(/[!"$%&'()*+,.\/:;<=>?@\[\]\^`{|}~]/g,"\\$\x26"):"";this.ea=f(a);this.aa=null;this.f={};this.gF=null;this.yd=this.cQ();t.push(this);this.zf="rtl"===this.uc();
this.gP()},_destroy:function(){this.sL();this.f.html.pl&&(this.ea.append(this.f.html.pl),this.f.html.vr.remove(),this.f.html.vr=!1,this.f.html.Mr=!1);this.f.za.type=0;this._super()},_setOption:function(a,b,c){var d;if("selectionMode"===a)"none"===b?d=0:"single"===b?d=1:"multiple"===b?d=-1:(d=0,b="none"),d!=this.f.F.Zd&&(this.f.F.Zd=d);else if("icons"===a)"boolean"==f.type(b)&&b!=this.f.Ia.icons&&((this.f.Ia.icons=b)?this.Kv():this.Cu());else if("contextMenu"===a)this.pp(),b&&this.Km(b);else if("disabled"===
a)this.qO(b);else{if("data"===a){this._super(a,b,c);this.oC();this.pC();this.NC();return}if("dnd"===a){this._super(a,b,c);this.qC();return}}this._super(a,b,c)},sL:function(){var a=this.yd;this.ea.unbind(".oj-tree").undelegate(".oj-tree").removeData("oj-tree-instance-id").find("[class^\x3d'oj-tree']").addBack().attr("class",function(){return this.className.replace(/oj-tree[^ ]*|$/ig,"")});var b=this.ea.attr("class"),b=b.trim();0===b.length&&this.ea.removeAttr("class");e(this.aa);f(document).unbind(".oj-tree-"+
a).undelegate(".oj-tree-"+a);this.aa.remove();this.aa=null},OV:function(a){var b=f(a,this.ea);if(b.is(".oj-tree")||-1==a)return-1;b=b.closest("li",this.ea);return b.length?b:!1},na:function(a,b){if("undefined"===typeof a||null===a)return b?this.f.ui.selected:this.f.ui.Ib;var c=f(a,this.ea);if(c.is(".oj-tree")||-1===a)return-1;c=c.closest("li",this.ea);return c.length?c:!1},Vg:function(a,b){a=this.na(a);if(-1===a)return this.ea.find("\x3e ul \x3e li:last-child");if(!a.length)return!1;if(b)return 0<
a.prevAll("li").length?a.prevAll("li:eq(0)"):!1;if(a.prev("li").length){for(a=a.prev("li").eq(0);a.hasClass("oj-tree-open");)a=a.children("ul:eq(0)").children("li:last");return a}var c=a.parentsUntil(".oj-tree","li:eq(0)");return c.length?c:!1},aj:function(a,b){a=this.na(a);return-1===a?this.ea.find("\x3e ul \x3e li:first-child"):a.length?b?0<a.nextAll("li").size()?a.nextAll("li:eq(0)"):!1:a.hasClass("oj-tree-open")?a.find("li:eq(0)"):0<a.nextAll("li").size()?a.nextAll("li:eq(0)"):a.parentsUntil(".oj-tree",
"li").next("li").eq(0):!1},Nh:function(a){a=this.na(a);if(-1==a||!a.length)return!1;a=a.parentsUntil(".oj-tree","li:eq(0)");return a.length?a:-1},fN:function(a){a=this.na(a);return-1===a?this.ea.children("ul:eq(0)").children("li"):a.length?a.children("ul:eq(0)").children("li"):!1},BC:function(a){return(a=this.na(a))&&-1!==a&&a.hasClass("oj-tree-leaf")},HD:function(a){a.parents("div").eq(0);return this},yz:function(a,b){void 0!=a&&void 0!=b&&f.each(b,function(b,c){void 0==a[b]&&(a[b]=c)})},qO:function(a){var b=
this.aa.hasClass("oj-disabled");b||(b=!1);"undefined"!==typeof a&&b!=a&&(a?(this.aa.addClass("oj-disabled"),this.aa.prop("disabled","disabled")):(this.aa.removeClass("oj-disabled"),this.aa.removeAttr("disabled")),this.OP(a))},OP:function(a){a?(this.f.F.locked=!0,this.f.ui.opacity=this.ea.children("ul").css("opacity"),this.aa.addClass("oj-tree-locked").css("opacity","0.9")):(this.f.F.locked=!1,this.aa.removeClass("oj-tree-locked").css("opacity",this.f.ui.opacity))},Kk:function(a,b,c,d,e){var f={Dj:this};
f.Ya=f.Dj.na(a);f.ua=-1===b?-1:this.na(b);f.th="undefined"===typeof c||!1===c?"last":c;if(!e&&this.f.F.qd.Ya&&this.f.F.qd.Ya[0]===f.Ya[0]&&this.f.F.qd.ua[0]===f.ua[0]&&this.f.F.qd.th===f.th)this.wa(this.f.F.qd),d&&d.call(this,this.f.F.qd);else{f.Dj=this;f.xl=this;if(-1!==f.ua&&f.ua){if(!/^(before|after)$/.test(f.th)&&!this.Wg(f.ua))return this.hg(f.ua,function(){this.Kk(a,b,c,d,!0)});switch(f.th){case "before":f.Ef=f.ua.index();f.uj=f.xl.Nh(f.ua);break;case "after":f.Ef=f.ua.index()+1;f.uj=f.xl.Nh(f.ua);
break;case "inside":case "first":f.Ef=0;f.uj=f.ua;break;case "last":f.Ef=f.ua.find(" \x3e ul \x3e li").length;f.uj=f.ua;break;default:f.Ef=f.th,f.uj=f.ua}}else switch(f.uj=-1,f.th){case "first":case "before":case "inside":f.Ef=0;break;case "after":case "last":f.Ef=f.xl.ea.find(" \x3e ul \x3e li").length;break;default:f.Ef=f.th}f.qh=-1==f.uj?f.xl.ea:f.uj;f.sh=f.Dj.Nh(f.Ya);f.pW=f.Ya.index();-1===f.sh&&(f.sh=f.Dj?f.Dj.ea:this.ea);!/^(before|after)$/.test(f.th)&&f.sh&&f.qh&&f.sh[0]===f.qh[0]&&f.Ya.index()<
f.Ef&&f.Ef++;f.gx=f.qh.find(" \x3e ul \x3e li:nth-child("+(f.Ef+1)+")");this.f.F.qd=f;this.wa(this.f.F.qd,"prepare_move");d&&d.call(this,this.f.F.qd,"prepare_move")}},check_move:function(){var a=this.f.F.qd,b=!0,c;c=-1===a.ua?this.ea:a.ua;if(!a||!a.Ya||a.gx[0]===a.Ya[0])return!1;if(!a.WF){if(a.sh&&a.qh&&a.sh[0]===a.qh[0]&&a.Ef-1===a.Ya.index())return!1;a.Ya.each(function(){if(-1!==c.parentsUntil(".oj-tree","li").addBack().index(this))return b=!1})}return b},gE:function(a,b){var c;a=this.na(a);this.Oi();
c=this.getText(a);if(a&&a.length){var d=this.wa({obj:a,func:"rename",title:b,prevTitle:c},"before");if("boolean"==typeof d&&!d)return}a&&a.length&&this.Hv.apply(this,Array.prototype.slice.call(arguments))&&this.wa({obj:a,title:b,prevTitle:c},"rename")},Hk:function(a,b,c,d,e,g){if(!(a.hasClass&&a.hasClass("oj-disabled")||this.f.F.locked)){if(!e)return this.Kk(a,b,c,function(a){this.Hk(a,!1,!1,d,!0,g)});d&&(this.f.F.qd.WF=!0);if(!g&&!this.check_move())return!1;this.Oi();b=!1;d?(b=a.Ya.clone(!0),b.find("*[id]").addBack().each(function(){this.id&&
(this.id="copy_"+this.id)})):b=a.Ya;a.gx.length?a.gx.before(b):(a.qh.children("ul").length||f("\x3cul /\x3e").appendTo(a.qh),a.qh.children("ul:eq(0)").append(b));try{a.Dj.ge(a.sh),a.xl.ge(a.qh),a.sh.find("\x3e ul \x3e li").length||a.sh.removeClass("oj-tree-open oj-tree-closed").removeAttr("aria-expanded").addClass("oj-tree-leaf").children("ul").remove()}catch(h){}d&&(this.f.F.qd.WF=!0,this.f.F.qd.JW=b);b=f.extend(!0,{},this.f.F.qd);b.obj=a.Ya;this.wa(b,"move");return this.f.F.qd}},NV:function(){return this.f.Hb.qd},
ru:function(a){var b=null;this.options.types&&(b=this.na(a));return b&&b.length?b.attr(this.options.types.attr)||"default":!1},RR:function(a,b){var c=this.options.types,d=!1;b=this.na(b);(d=c?b.length&&a?b.attr(this.options.types.attr,a):!1:!1)&&this.wa({obj:b,type:a},"settype");return d},$z:function(a,b,c){b=this.na(b);var d=!1,e=this.ru(b),g=0,h=this,k=this.Ug().types,l=!1;if(-1===b)if(k[a])d=k[a];else return;else{if(!1===e)return;(l=this.f.types.pc.useData?b.data("oj-tree"):!1)&&l.types&&"undefined"!==
typeof l.types[a]?d=l.types[a]:k.types[e]&&"undefined"!==typeof k.types[e][a]?d=k.types[e][a]:k.types["default"]&&"undefined"!==typeof k.types["default"][a]&&(d=k.types["default"][a])}f.isFunction(d)&&(d=d.call(this,b));var m=this.f.types.pc.maxDepth;"maxDepth"===a&&-1!==b&&!1!==c&&-2!==this.f.types.pc.maxDepth&&0!==d&&b.children("a:eq(0)").parentsUntil(".oj-tree","li").each(function(b){if(-1!==m&&0>=m-(b+1))return d=0,!1;g=0===b?d:h.$z(a,this,!1);if(-1!==g&&0>=g-(b+1))return d=0,!1;0<=g&&(g-(b+1)<
d||0>d)&&(d=g-(b+1));0<=m&&(m-(b+1)<d||0>d)&&(d=m-(b+1))});return d},ge:function(a){a=a&&-1!=a?f(a):this.aa;a=a.is("li")?a.find("li").addBack():a.find("li");a.removeClass("oj-tree-last").filter("li:last-child").addClass("oj-tree-last").end().filter(":has(li)").not(".oj-tree-open").removeClass("oj-tree-leaf").addClass("oj-tree-closed").attr("aria-expanded","false");a.not(".oj-tree-open, .oj-tree-closed").addClass("oj-tree-leaf").children("ul").remove();this.wa({obj:a},"clean_node")},ot:function(a,
b,c,d,e){a=this.na(a);if(-1!==a&&!a.length)return!1;b="undefined"===typeof b?"last":b;var g=f("\x3cli /\x3e"),h;if(!e&&!this.Wg(a))return this.hg(a,function(){this.ot(a,b,c,d,!0)}),!1;this.Oi();"string"===typeof c&&(c={data:c});c||(c={});c.attr&&g.attr(c.attr);c.metadata&&g.data(c.metadata);c.state&&g.addClass("oj-tree-"+("expanded"===c.state?"open":"closed"));c.data||(c.data=void 0!==c.title?c.title:this.C("m_newnode"));f.isArray(c.data)||(h=c.data,c.data=[],c.data.push(h));var k=this;f.each(c.data,
function(a,b){h=f("\x3ca /\x3e");f.isFunction(b)&&(b=b.call(this,c));if("string"==typeof b)h.attr("href","#")[k.f.F.ml?"html":"text"](b);else b.attr||(b.attr={}),b.attr.href||(b.attr.href="#"),h.attr(b.attr)[k.f.F.ml?"html":"text"](b.title),b.language&&h.addClass(b.language);h.prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e");!b.icon&&c.icon&&(b.icon=c.icon);b.icon&&(-1===b.icon.indexOf("/")?h.children("ins").addClass(b.icon):h.children("ins").css("background","url('"+b.icon+"') center center no-repeat"));
g.append(h)});g.prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e");-1===a&&(a=this.ea,"before"===b&&(b="first"),"after"===b&&(b="last"));switch(b){case "before":a.before(g);h=this.Nh(a);break;case "after":a.after(g);h=this.Nh(a);break;case "inside":case "first":a.children("ul").length||a.append("\x3cul /\x3e");a.children("ul").prepend(g);h=a;break;case "last":a.children("ul").length||a.append("\x3cul /\x3e");a.children("ul").append(g);h=a;break;default:a.children("ul").length||a.append("\x3cul /\x3e"),
b||(b=0),h=a.children("ul").children("li").eq(b),h.length?h.before(g):a.children("ul").append(g),h=a}if(-1===h||h.get(0)===this.ea.get(0))h=-1;this.ge(h);this.wa({obj:g,parent:h},"create_node");d&&d.call(this,g);return g},cg:function(a,b,c){a=this.na(a);if(!a.length)return!1;if(!a.hasClass("oj-disabled")&&!this.f.F.locked){if(!a.hasClass("oj-tree-closed"))return b&&b.call(),!1;var d=this.wa({obj:a,func:"expand"},"before");if("boolean"!=typeof d||d){var d=c||this.options.animDuration,e=this;this.Wg(a)?
(this.options.expandParents&&a.parentsUntil(".oj-tree",".oj-tree-closed").each(function(){e.expand(this,!1,!0)}),d&&a.children("ul").css("display","none"),a.removeClass("oj-tree-closed").addClass("oj-tree-open").attr("aria-expanded","true").children("a").removeClass("oj-tree-loading"),d?a.children("ul").stop(!0,!0).slideDown(d,function(){this.style.display="";e.after_open(a)}):e.after_open(a),this.wa({obj:a},"expand"),b&&b.call()):(a.children("a").addClass("oj-tree-loading"),this.hg(a,function(){e.expand(a,
b,c)},b))}}},Ct:function(a,b,c){var d=a?a:-1;(a=a?this.na(a):-1)&&-1!==a?d=a:a=this.aa;c?a=a.find("li.oj-tree-closed"):(c=a,a=a.is(".oj-tree-closed")?a.find("li.oj-tree-closed").addBack():a.find("li.oj-tree-closed"));var e=this;a.each(function(){var a=this;e.Wg(this)?e.cg(this,!1,!b):e.expand(this,function(){e.Ct(a,b,c)},!b)});0===c.find("li.oj-tree-closed").length&&this.wa({obj:a,targ:d},"expandAll")},Pk:function(a,b,c){if(0==this.f.F.Zd)return!1;a=this.na(a);if(-1==a||!a||!a.length)return!1;if(!a.hasClass("oj-disabled")&&
!this.f.F.locked){var d=this.wa({obj:a,func:"select"},"before");if("boolean"!=typeof d||d){var d=this.options,e=this.f.ui.pc.selectMultipleModifier,f=this.f.ui.pc.selectRangeModifier,g=this.f.ui.pc.disableSelectingChildren,e="on"==e||!1!==e&&c&&c[e+"Key"],f=!1!==f&&c&&c[f+"Key"]&&this.f.ui.Ib&&this.f.ui.Ib[0]!==a[0]&&this.f.ui.Ib.parent()[0]===a.parent()[0],h=this.isSelected(a),k=!0,l=this;if(b){if(g&&e&&(a.parentsUntil(".oj-tree","li").children("a.oj-tree-clicked").length||a.children("ul").find("a.oj-tree-clicked:eq(0)").length))return!1;
k=!1;switch(!0){case f:this.f.ui.Ib.addClass("oj-tree-last-selected");a=a[a.index()<this.f.ui.Ib.index()?"nextUntil":"prevUntil"](".oj-tree-last-selected").addBack();-1==this.f.F.Zd||a.length<this.f.F.Zd?(this.f.ui.Ib.removeClass("oj-tree-last-selected"),this.f.ui.selected.each(function(){this!==l.f.ui.Ib[0]&&l.deselect(this)}),h=!1,k=!0):k=!1;break;case h&&!e:this.deselectAll();this.f.ui.zx||(h=!1);k=!0;break;case !h&&!e:c?this.f.ui.selected&&1==this.f.ui.selected.length?this.deselect(this.f.ui.selected):
this.deselectAll(this.f.ui.selected):1===this.f.F.Zd?this.deselect(this.f.ui.selected):1<this.f.F.Zd&&this.deselectAll();k=!0;break;case h&&e:this.deselect(a);break;case !h&&e:if(-1==this.f.F.Zd||this.f.ui.selected.length+1<=this.f.F.Zd)k=!0}}k&&!h&&(f||(this.f.ui.Ib=a),a.children("a").addClass("oj-tree-clicked"),a.attr("aria-selected","true"),d.selectedParentExpand&&a.parents(".oj-tree-closed").each(function(){l.expand(this,!1,!0)}),this.f.ui.selected=this.f.ui.selected.add(a),this.hB(a.eq(0)),this.wa({obj:a,
e:c},"select"))}}},mM:function(a,b){if(!this.f.F.locked)if(b){if(d=a?a:-1,e=a?f(a).find("a.oj-tree-clicked").parent():this.ea.find("a.oj-tree-clicked").parent(),!e.hasClass("oj-disabled")){var c=this;f.each(e,function(){c.deselect(this)})}}else{var d=a?a:-1,e=a?f(a).find("a.oj-tree-clicked").parent():this.ea.find("a.oj-tree-clicked").parent();e.hasClass("oj-disabled")||(e.children("a.oj-tree-clicked").removeClass("oj-tree-clicked"),e.removeAttr("aria-selected"),this.f.ui.selected=f([]),this.f.ui.Ib=
!1,e.length&&this.wa({obj:e,targ:d},"deselectAll"))}},Pb:function(a){this.WD(a)},WD:function(a){var b=a?a:-1,c=this;this.uR();a||(a=-1);(a=this.na(a))?b=a:a=-1;-1!==a?a.children("UL").remove():(this.aa.empty(),this.uD());this.hg(a,function(){c.wa({obj:b},"refresh");c.Aq()})},vv:function(a){this.save_selected();this.WD(a)},after_open:function(a){this.wa({obj:a},"after_open")},after_close:function(a){this.wa({obj:a},"after_close")},jR:function(){var a=this;this.f.F.qc.length&&f.each(this.f.F.qc,function(b,
c){a.cg(c,!1,!0)});this.wa({},"reopen")},VN:function(a){return a?f(a).find("a.oj-tree-clicked").parent():this.f.ui.selected},Hv:function(a,b){a=this.na(a);if(!a.length)return!1;a=a.children("a:eq(0)");if(this.f.F.ml){var c=a.children("INS").clone();a.html(b).prepend(c);this.wa({obj:a,name:b},"set_text");return!0}a=a.find("span:eq(0)");this.wa({obj:a,name:b},"set_text");return a[0].textContent=b},NC:function(){0!==this.f.za.type&&-1!==this.f.za.type?this.hg(-1,function(){this.PC();this.Aq()}):(this.JK(),
this.PC())},hg:function(a){this.wa({obj:a},"load_node")},Wg:function(){return!0},HP:function(a,b,c){var d=this;this.MP(a,function(){d.wa({obj:d.na(a)},"load_node");b.call(this)},c)},zP:function(a){a=this.na(a);return-1===a||!a||a.is(".oj-tree-open, .oj-tree-leaf")||0<a.children("ul").children("li").length},OQ:function(a){(a=this.na(a))&&-1!==a&&a.removeData("oj-tree-children");return this.vv(a)},JP:function(a,b,c){var d=this;this.LP(a,function(){d.wa({obj:d.na(a)},"load_node");b.call(this)},c)},BP:function(a){var b=
this.options.data;a=this.na(a);return-1==a||!a||!b.ajax&&!this.f.za.lx&&!f.isFunction(b.data)||a.is(".oj-tree-open, .oj-tree-leaf")||0<a.children("ul").children("li").length},IP:function(a,b,c){var d=this;this.KP(a,function(){d.wa({obj:d.na(a)},"load_node");b.call(this)},c)},AP:function(a){var b=this.options.data,c=null,d=null;b&&(c=b.data||null,d=b.ajax||null);a=this.na(a);return-1==a||!a||!d&&!f.isFunction(c)||a.is(".oj-tree-open, .oj-tree-leaf")||0<a.children("ul").children("li").size()},reselect:function(){var a=
this,b=this.f.ui.Kr,b=f.map(f.makeArray(b),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});f.each(b,function(b,c){c&&"#"!==c&&a.select(c)});this.f.ui.selected=this.f.ui.selected.filter(function(){return this.parentNode});this.wa(null,"reselect")},save_selected:function(){var a=this;this.f.ui.Kr=[];this.f.ui.selected.each(function(){this.id&&a.f.ui.Kr.push("#"+this.id.toString().replace(/^#/,
"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:"))});this.wa(this.f.ui.Kr,"save_selected")},rollback:function(a){a&&(f.isArray(a)||(a=[a]),f.each(a,function(){}))},get_rollback:function(){this.wa(null,"get_rollback");return{wW:this.yd,kh:this.ea.children("ul").clone(!0),qW:this.data}},set_rollback:function(a,b){this.ea&&this.aa&&this.aa.empty().append(a);this.data=b;this.wa(null,"set_rollback")},MP:function(a,b){var c=this.ty(a);if(c.success&&
c.Wn){var d=!a||-1===a,e=this.options.data;if(e.data&&!e.ajax||e.data&&e.ajax&&d)d&&((c=this.Xh(c.Wn,a))?(this.aa.empty().append(c.children()),this.ge()):this.f.za.Qd&&this.aa.empty()),b&&b.call(this);else if(!e.data&&e.ajax||e.data&&e.ajax&&!d)(c=this.Xh(c.Wn,a))?(d?(d=this.aa,d.empty().append(c.children()),d.attr("role","tree").attr("tabindex","0").css("outline","none"),-1===this.f.F.Zd&&d.attr("aria-multiselectable",!0)):(a.append(c).children("a.oj-tree-loading").removeClass("oj-tree-loading"),
a.removeData("oj-tree-is-loading")),this.ge(a),b&&b.call(this)):d?this.f.za.Qd&&(this.aa.empty(),b&&b.call(this)):(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),e.correct_state&&(this.Si(a),b&&b.call(this)))}},ty:function(a,b){var c=[],d=this.gF,e,g={},h={success:!1,Wn:null};-1==a&&(a=null,g.start=0);e=d.df(a);0<e&&(g.count=e,d.Sd(a,g,{success:f.proxy(function(a){for(var e=a.Y(),f,g=0;g<e;g++){b={};(f=a.getData(g))&&(b.attr=f);b.title=a.Gd[g].title;
f.DW&&(b.metadata=a.Gd[g].metadata);var k=b.attr.id;f=d.df(k);0<f&&(f=this.ty(k,b),b.children=f.Wn);c.push(b)}h.success=!0;h.Wn=c},this),error:function(){h.success=!1}}));return h},PQ:function(a){a=this.na(a);if(!this.f.F.locked){var b=!a||-1!==a||!a.length;if(b||!a.hasClass("oj-disabled")){var c=this.options.data.json;!b&&this.f.za.ul&&(f.isFunction(c.data)||c.ajax)&&a.removeData("oj-tree-children");return this.vv(a)}}},LP:function(a,b,c){function d(){}function e(){}var g=this.Ug().data,h=g&&g.data||
null,k=g&&g.ajax||null;!g||h||k||(h=g);if((a=this.na(a))&&-1!==a&&(this.f.za.lx||this.f.za.ul)&&!a.is(".oj-tree-open, .oj-tree-leaf")&&0===a.children("ul").children("li").length&&a.data("oj-tree-children")){if(g=this.Xh(a.data("oj-tree-children"),a))a.append(g),this.f.za.ul||a.removeData("oj-tree-children");this.ge(a);b&&b.call(this)}else{if(a&&-1!==a){if(a.data("oj-tree-is-loading"))return;a.data("oj-tree-is-loading",!0)}switch(!0){case !h&&!k:throw"ojTree - neither data nor ajax settings supplied.";
case f.isFunction(h):h.call(this,a,f.proxy(function(d){(d=this.Xh(d,a))?(-1!==a&&a?(a.append(d).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")):this.aa.empty().append(d.children()),this.ge(a),b&&b.call(this)):(-1!==a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.f.za.Qd&&this.Si(a)):this.f.za.Qd&&this.aa.empty(),c&&c.call(this))},this));break;case !!h&&!k||!!h&&!!k&&(!a||-1===a):a&&-1!=a||
((g=this.Xh(h,a))?(this.aa.empty().append(g.children()),this.ge()):this.f.za.Qd&&this.aa.empty());b&&b.call(this);break;case !h&&!!k||!!h&&!!k&&a&&-1!==a:e=function(b,d,e){var f=this.Ug().data.ajax.error;f&&f.call(this,d,e,b);-1!=a&&a.length?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),"success"===d&&this.f.za.Qd&&this.Si(a)):"success"===d&&this.f.za.Qd&&this.aa.empty();c&&c.call(this)},d=function(c,d,g){var h=this.Ug().data.ajax.success;h&&(c=
h.call(this,c,d,g)||c);if(""===c||c&&c.toString&&""===c.toString().replace(/^[\s\n]+$/,"")||!f.isArray(c)&&!f.isPlainObject(c))return e.call(this,g,d,"");(c=this.Xh(c,a))?(-1!==a&&a?(a.append(c).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")):(d=this.aa,d.empty().append(c.children()),d.attr("role","tree").attr("tabindex","0").css("outline","none"),-1===this.f.F.Zd&&d.attr("aria-multiselectable",!0)),this.ge(a),b&&b.call(this)):-1!==a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),
a.removeData("oj-tree-is-loading"),this.f.za.Qd&&(this.Si(a),b&&b.call(this))):this.f.za.Qd&&(this.aa.empty(),b&&b.call(this))},g.ajax.context=this,g.ajax.error=e,g.ajax.success=d,g.dataType||(g.ajax.dataType="json"),f.isFunction(g.ajax.url)&&(g.ajax.url=g.ajax.url.call(this,a)),f.isFunction(g.ajax.data)&&(g.ajax.data=g.ajax.data.call(this,a)),f.ajax(g.ajax)}}},Xh:function(a,b,c){var d=!1,e,g,h,k;if(!a)return d;this.f.za.ul&&b&&-1!==b&&b.data("oj-tree-children",d);if("string"==typeof a)try{a=f.parseJSON(a)}catch(l){a=
[]}if(f.isArray(a)){d=f("\x3cul\x3e");if(!a.length)return!1;g=0;for(h=a.length;g<h;g++)e=this.Xh(a[g],b,!0),e.length&&(d=d.append(e));d=d.children()}else{"string"==typeof a&&(a={data:a});k="string"==typeof a.title?a.title:" ";d=f("\x3cli role\x3d'treeitem' /\x3e");a.attr&&(this.f.types.cl&&!a.attr.type&&(a.attr.type="oj-tree-deftype"),d.attr(a.attr));a.metadata&&d.data(a.metadata);(a.state||a.children&&0===a.children.length)&&d.addClass("oj-tree-"+("expanded"===a.state?"open":"closed"));a.data||(a.data=
{dummy:0});var m=this.f.F.ml,n=!1,q;e=f("\x3ca tabindex\x3d'-1' /\x3e");f.each(a.data,function(b,c){f.isFunction(c)&&(c=c.call(this,a));"string"!=typeof c&&("attr"==b?e.attr(c):"style"==b&&e.css(c),"language"==b&&e.addClass(c));n||(q=f("\x3cspan class\x3d'oj-tree-title'\x3e"),q[m?"html":"text"](k),e.prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e",q),n=!0);!c.icon&&a.icon&&(c.icon=a.icon);c.icon&&(-1===c.icon.indexOf("/")?e.children("ins").addClass(c.icon):e.children("ins").css("background",
"url('"+c.icon+"') center center no-repeat"))});d.append(e);d.prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e");a.children&&(this.f.za.lx&&"expanded"!==a.state?d.addClass("oj-tree-closed").attr("aria-expanded","false").data("oj-tree-children",a.children):(this.f.za.ul&&d.data("oj-tree-children",a.children),f.isArray(a.children)&&a.children.length&&(e=this.Xh(a.children,b,!0),e.length&&(b=f("\x3cul role\x3d'group' /\x3e"),b.append(e),d.append(b)))))}c||(c=f("\x3cul /\x3e"),c.append(d),
d=c);return d},Si:function(a){a=this.na(a);if(!a||-1===a)return!1;a.removeClass("oj-tree-closed oj-tree-open").removeAttr("aria-expanded").addClass("oj-tree-leaf").children("ul").remove();this.wa({obj:a},"correct_state")},AV:function(a,b){b.KW&&this.cg(a,!1,!0)},PC:function(){this.wa(null,"loaded")},KP:function(a,b,c){function d(){}function e(){}var g=this.Ug().data,h=g&&g.data||null,k=g&&g.ajax||null;if((a=this.na(a))&&-1!==a){if(a.data("oj-tree-is-loading"))return;a.data("oj-tree-is-loading",!0)}switch(!0){case !h&&
!k&&g&&"string"===typeof g:this.MC(g,a,b,c);break;case f.isFunction(h):h.call(this,a,f.proxy(function(d){this.MC(d,a,b,c)},this));break;case !h&&!k:a&&-1!=a||(this.aa.empty().append(this.f.html.Yq).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-icon").addClass("oj-tree-icon"),this.gq(this.aa),this.f.types.cl&&
this.Xl(this.aa),this.ge(),this.aa.find("ul").attr("role","group"),this.aa.find("li").attr("role","treeitem"),this.aa.find("a").attr("tabindex",-1));b&&b.call(this);break;case !!h&&!k||!!h&&!!k&&(!a||-1===a):a&&-1!=a||(g=f(h),g.is("ul")||(g=f("\x3cul /\x3e").append(g)),this.aa.empty().append(g.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-icon").addClass("oj-tree-icon"),
this.gq(this.aa),this.f.types.cl&&this.Xl(this.aa),this.ge(),this.aa.find("ul").attr("role","group"),this.aa.find("li").attr("role","treeitem"),this.aa.find("a").attr("tabindex","-1"));b&&b.call(this);break;case !h&&!!k||!!h&&!!k&&a&&-1!==a:a=this.na(a),e=function(b,d,e){var f=this.Ug().data.ajax.error;f&&f.call(this,b,d,e);-1!=a&&a.length?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),"success"===d&&this.f.za.Qd&&this.Si(a)):"success"===d&&this.f.za.Qd&&
this.aa.empty();c&&c.call(this)},d=function(c,d,g){var h=this.Ug().data.ajax.success;h&&(c=h.call(this,c,d,g)||c);if(""===c||c&&c.toString&&""===c.toString().replace(/^[\s\n]+$/,""))return e.call(this,g,d,"");c?(c=f(c),c.is("ul")||(c=f("\x3cul /\x3e").append(c)),-1!=a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),this.$Q(a),a.append(c).children("ul").find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-icon").addClass("oj-tree-icon"),
a.removeData("oj-tree-is-loading"),c=a):(this.aa.empty().append(c.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-icon").addClass("oj-tree-icon"),c=this.aa),this.uO(c),this.gq(c),this.f.types.cl&&c&&this.Xl(this.aa),this.ge(a),b&&b.call(this)):(a&&-1!==a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),
a.removeData("oj-tree-is-loading"),this.f.za.Qd&&(this.Si(a),b&&b.call(this))):this.f.za.Qd&&(this.aa.empty(),b&&b.call(this)),this.aa.find("ul").attr("role","group"),this.aa.find("li").attr("role","treeitem"))},g.ajax.context=this,g.ajax.error=e,g.ajax.success=d,g.ajax.dataType||(g.ajax.dataType="html"),f.isFunction(g.ajax.url)&&(g.ajax.url=g.ajax.url.call(this,a)),f.isFunction(g.ajax.data)&&(g.ajax.data=g.ajax.data.call(this,a)),f.ajax(g.ajax)}},uO:function(a){a=a.find(a.is("ul")?"li ul":"ul").filter(function(){return!this.firstChild||
0==this.childNodes.length||1==this.childNodes.length&&3==this.firstChild.nodeType});f.each(a,function(){f(this).closest("li").addClass("oj-tree-closed")})},$Q:function(a){a=a.find("ul").filter(function(){return!this.firstChild||0==this.childNodes.length||1==this.childNodes.length&&3==this.firstChild.nodeType});0<a.length&&a.remove()},MC:function(a,b,c){a&&""!==a&&a.toString&&""!==a.toString().replace(/^[\s\n]+$/,"")?(a=f(a),a.is("ul")||(a=f("\x3cul /\x3e").append(a)),-1!=b&&b?(b.children("a.oj-tree-loading").removeClass("oj-tree-loading"),
b.append(a).children("ul").find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-icon").addClass("oj-tree-icon"),b.removeData("oj-tree-is-loading"),a=b,this.Xl(this.Ai)):(this.aa.empty().append(a.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-icon").addClass("oj-tree-icon"),
a=this.aa,this.Xl(this.aa)),a&&this.gq(a),this.ge(b),c&&c.call(this)):b&&-1!==b?(b.children("a.oj-tree-loading").removeClass("oj-tree-loading"),b.removeData("oj-tree-is-loading"),this.f.za.Qd&&(this.Si(b),c&&c.call(this))):this.f.za.Qd&&(this.aa.empty(),c&&c.call(this))},gq:function(a){f.each(a.find("li a"),function(a,b){var c=b.innerHTML,c=c.replace("ins\x3e","ins\x3e\x3cspan class\x3d'oj-tree-title'\x3e");b.innerHTML=c+"\x3c/span\x3e"})},Xl:function(a){var b,c;this.f.types.cl&&(c=(b=this.options.types)?
b.attr:this.f.types.pc.attr,f.each(a.find("li"),function(a,b){b=f(b);b.attr(c)||b.attr(c,"oj-tree-deftype")}))},Ap:function(){var a=this.f.dnd.hb;if(a.ua&&a.ua.length){this.f.dnd.off=a.ua.offset();this.zf&&(this.f.dnd.off.right=this.f.dnd.off.left+a.ua.width()-a.ua.find("\x3ea").width()-18);this.f.dnd.LH=a.ua.find("a").width();if(this.f.dnd.fr)return a=this.options.dnd.drag_check.call(this,{o:a.Ya,r:a.ua}),this.f.dnd.after=a.after,this.f.dnd.before=a.before,this.f.dnd.inside=a.inside,this.f.dnd.ho=
!0,this.xt();this.Kk(a.Ya,a.ua,"before");this.f.dnd.before=this.check_move();this.Kk(a.Ya,a.ua,"after");this.f.dnd.after=this.check_move();this.Wg(a.ua)?(this.Kk(a.Ya,a.ua,"inside"),this.f.dnd.inside=this.check_move()):this.f.dnd.inside=!1;this.f.dnd.ho=!0;return this.xt()}},xt:function(){var a=this.f.dnd,b=!1,c;if(a.ho){var b=["before","inside","after"],d=!1,e=a.xb,g=a.hb,b=a.Xc<this.f.F.Ke/3?["before","inside","after"]:a.Xc<=2*this.f.F.Ke/3?a.Xc<this.f.F.Ke/2?["inside","before","after"]:["inside",
"after","before"]:["after","inside","before"];f.each(b,f.proxy(function(a,b){if(this.f.dnd[b])return e.helper.children("ins").removeClass("oj-tree-invalid").addClass("oj-tree-ok"),d=b,!1},this));!1===d&&e.helper.children("ins").removeClass("oj-tree-ok").addClass("oj-tree-invalid");c=this.zf?this.f.dnd.off.right-18:this.f.dnd.off.left+10;b=!this.isLeaf(g.ua);a=this.zf?c+this.f.dnd.LH+18:c;c=this.zf?a-this.f.dnd.fH:c+8;switch(d){case "before":g.dc.css({left:a+"px",top:this.f.dnd.off.top-8+"px"}).show();
g.tb&&g.tb.css({left:c+"px",top:this.f.dnd.off.top-3+"px"}).show();break;case "after":g.dc.css({left:a+"px",top:this.f.dnd.off.top+this.f.F.Ke-8+"px"}).show();g.tb&&g.tb.css({left:c+"px",top:this.f.dnd.off.top+this.f.F.Ke-3+"px"}).show();break;case "inside":g.dc.css({left:a+(this.zf?b?-4:0:4)+"px",top:this.f.dnd.off.top+this.f.F.Ke/2-5+"px"}).show();g.tb&&g.tb.hide();break;default:g.dc.hide(),g.tb&&g.tb.hide()}return g.Xw=d}},wt:function(a){var b=this.f.dnd,c=b.hb;b.wr&&(clearTimeout(b.wr),b.wr=!1);
b.ho=!1;c.ua=this.na(a);a=this.options.dnd;var d=a.check_timeout;d?(b.Of&&clearTimeout(b.Of),b.Of=setTimeout(f.proxy(this.Ap,this),d)):this.Ap();(a=a.open_timeout)?(b.mf&&clearTimeout(b.mf),c.ua&&c.ua.length&&c.ua.hasClass("oj-tree-closed")&&(b.mf=setTimeout(f.proxy(this.OA,this),a))):c.ua&&c.ua.length&&c.ua.hasClass("oj-tree-closed")&&this.OA()},vM:function(a){var b=this.f.dnd,c=this.f.dnd.hb;b.after=!1;b.before=!1;b.inside=!1;this.f.dnd.xb.helper.children("ins").removeClass("oj-tree-ok").addClass("oj-tree-invalid");
c.dc.hide();c.tb&&c.tb.hide();c.ua&&c.ua[0]===a.target.parentNode&&(b.Of&&(clearTimeout(b.Of),b.Of=!1),b.mf&&(clearTimeout(b.mf),b.mf=!1))},OA:function(){var a=this.f.dnd.hb;this.f.dnd.mf=!1;this.expand(a.ua,f.proxy(this.Ap,this),!0)},uM:function(a){var b=this.f.dnd,c=this.f.dnd.hb;b.fr?(b.after||b.before||b.inside)&&this.options.dnd.drag_finish.call(this,{o:c.Ya,r:c.ua,p:c.Xw}):(this.Ap(),this.Hk(c.Ya,c.ua,c.Xw,a[this.options.dnd.copy_modifier+"Key"]));c.Ya=!1;c.ua=!1;c.dc.hide();c.tb&&c.tb.hide()},
aS:function(a,b){var c=this.f.dnd,d=this.f.dnd.hb;d.Ya=this.na(a);if(!d.Ya.hasClass("oj-disabled")&&!this.f.F.locked){this.f.ui&&this.isSelected(d.Ya)&&(d.Ya=this.na(null,!0));var e=1<d.Ya.length?this.C("m_multisel"):this.getText(d.Ya),f=this.ea;this.f.F.ml||(e=e.replace(/</ig,"\x26lt;").replace(/>/ig,"\x26gt;"));this.TA(b,{Je:!0,Ai:d.Ya},"\x3cins class\x3d'oj-tree-icon'\x3e\x3c/ins\x3e"+e);this.f.Ia&&(d.dc&&d.dc.addClass("oj-tree-"+this.f.Ia.lf),c.xb.helper.addClass("oj-tree-dnd-helper oj-tree-"+
this.f.Ia.lf));c.al=f.offset();c.vw=parseInt(f.width(),10);c.ch=parseInt(f.height(),10);c.la=!0}},TA:function(a,b,c){var d=this.f.dnd.xb;d.Ie&&this.zt();try{a.currentTarget.unselectable="on",a.currentTarget.onselectstart=function(){return!1},a.currentTarget.style&&(a.currentTarget.style.MozUserSelect="none")}catch(e){}d.Qw=a.pageX;d.Rw=a.pageY;d.Cc=b;d.Tw=!0;d.helper=f("\x3cdiv class\x3d'ojtreeu-dragged' /\x3e").html(c);f(document).bind("mousemove",this.SA.bind(this));f(document).bind("mouseup",this.zt.bind(this));
return!1},SA:function(a){var b=this.f.dnd.xb,c=this.f.dnd.hb;if(b.Tw){if(!b.Ie)if(5<Math.abs(a.pageX-b.Qw)||5<Math.abs(a.pageY-b.Rw))b.helper.appendTo("body"),b.Ie=!0,f(document).triggerHandler("drag_start.ojtreeu",[{event:a,data:b.Cc}]);else return;if("mousemove"===a.type){var d=f(document),e=d.scrollTop(),d=d.scrollLeft();20>a.pageY-e?(c.Wc&&"down"===c.dl&&(clearInterval(c.Wc),c.Wc=void 0),c.Wc||(c.dl="up",c.Wc=setInterval(function(){f(document).scrollTop(f(document).scrollTop()-b.Fi)},150))):c.Wc&&
"up"===c.dl&&(clearInterval(c.Wc),c.Wc=void 0);20>f(window).height()-(a.pageY-e)?(c.Wc&&"up"===c.dl&&(clearInterval(c.Wc),c.Wc=void 0),c.Wc||(c.dl="down",c.Wc=setInterval(function(){f(document).scrollTop(Number(f(document).scrollTop())+b.Fi)},150))):c.Wc&&"down"===c.dl&&(clearInterval(c.Wc),c.Wc=void 0);20>a.pageX-d?(c.Vc&&"right"===c.el&&(clearInterval(c.Vc),c.Vc=void 0),c.Vc||(c.el="left",c.Vc=setInterval(function(){f(document).scrollLeft(f(document).scrollLeft()-b.Fi)},150))):c.Vc&&"left"===c.el&&
(clearInterval(c.Vc),c.Vc=void 0);20>f(window).width()-(a.pageX-d)?(c.Vc&&"left"===c.el&&(clearInterval(c.Vc),c.Vc=void 0),c.Vc||(c.el="right",c.Vc=setInterval(function(){f(document).scrollLeft(Number(f(document).scrollLeft())+b.Fi)},150))):c.Vc&&"right"===c.el&&(clearInterval(c.Vc),c.Vc=void 0)}b.helper.css({left:a.pageX+b.VT+"px",top:a.pageY+b.WT+"px"});f(document).triggerHandler("drag.ojtreeu",[{event:a,data:b.Cc}])}},zt:function(a){var b=this.f.dnd.hb,c=this.f.dnd.xb;b.Vc&&clearInterval(b.Vc);
b.Wc&&clearInterval(b.Wc);f(document).unbind("mousemove",this.SA.bind(this));f(document).unbind("mouseup",this.zt.bind(this));f(document).triggerHandler("drag_stop.ojtreeu",[{event:a?a:{},data:c.Cc}]);c.helper.remove();c.Qw=0;c.Rw=0;c.Cc={};c.Tw=!1;c.Ie=!1},uR:function(){var a=this;this.f.F.qc=[];this.aa.find("li.oj-tree-open").each(function(){this.id&&a.f.F.qc.push("#"+this.id.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,
"\\:"))});this.wa(a.f.F.qc,"save_opened")},Aq:function(a){var b=this,c=!0,d=[],e=[];a||(this.f.F.qx=!1,this.f.F.DU=!0,(a="all"===this.f.F.qc)?this.f.F.qc=[]:"array"===f.type(this.f.F.qc)&&0<this.f.F.qc.length&&"all"===this.f.F.qc[0]&&(this.f.F.qc.length=0,a=!0),a&&this.aa.find("li.oj-tree-closed").each(function(){f(this).attr("id");b.f.F.qc.push("#"+f(this).attr("id"))}),this.f.F.qc=f.map(f.makeArray(this.f.F.qc),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,
"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")}),this.f.F.Gi=f.map(f.makeArray(this.f.F.Gi),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")}),this.f.F.qc.length&&(this.f.F.Gi=this.f.F.Gi.concat(this.f.F.qc)));this.f.F.Gi.length&&(f.each(this.f.F.Gi,function(a,b){if("#"==b)return!0;f(b).length?d.push(b):e.push(b)}),d.length&&(this.f.F.Gi=e,f.each(d,function(a,d){b.Wg(d)||
(b.hg(d,function(){b.Aq(!0)},function(){b.Aq(!0)}),c=!1)})));this.f.F.qc.length&&f.each(this.f.F.qc,function(a,c){b.expand(c,!1,!0)});c&&(this.f.F.qx&&clearTimeout(this.f.F.qx),this.f.F.qx=setTimeout(function(){b.wa({},"reload_nodes")},50),this.f.F.DU=!1,this.jR())},set_theme:function(a,c){if(!a)return!1;c||(c=this.f.Ia.mn+a+"/style.css");-1==f.inArray(c,this.f.Ia.MH)&&(b({url:c}),this.f.Ia.MH.push(c));this.f.Ia.lf!=a&&(this.ea.removeClass("oj-tree-"+this.f.Ia.lf),this.f.Ia.lf=a);this.ea.addClass("oj-tree-"+
a);this.f.Ia.Bn?this.RE():this.hC();this.f.Ia.icons?this.Kv():this.Cu();this.wa(null,"set_theme")},isIcons:function(){return this.f.Ia.icons},Kv:function(){this.f.Ia.icons=!0;this.ea.children("ul").removeClass("oj-tree-no-icons")},Cu:function(){this.f.Ia.icons=!1;this.ea.children("ul").addClass("oj-tree-no-icons")},toggleIcons:function(){},DM:function(){this.f.keys.uT=!0},gP:function(){this.aP();this.$O();this.oC(!0);this.iP();this.qC();this.ZO();this.kP();this.fP();this.pC();this.jP();this.bP();
this.Km();this.Uk()},wa:function(a,b){if(b&&"string"===f.type(b)){var c,d;c=Array.prototype.slice.call(arguments);var e=b;d=this.ea;var g="before"===b,k=!1,l;if(!0!==this.f.F.locked||"unlock"===b||"isLocked"===b||"lock"===b){e=b;"rename_node"===e?e="rename":"set_focus"===e?e="focus":"unset_focus"===e?e="unfocus":"delete_node"===e?e="remove":"move_node"===e?e="move":"create_node"===e&&(e="create");(k=0<=f.inArray(e,h))||"create_node"!=e||(k=!0);k||(e="tree"+e);l=a?a.obj:void 0;"loaded"===e&&(l=-1);
var m={};m.item=l;m.inst=d;if(g)d=a.func,m.func=d,m.args=c,"rename"===d&&(m.title=a.title,m.prevTitle=a.prevTitle);else if(k)if("move"==e)m.position=a.th,m.reference=a.ua,m.data=a;else if("rename"==e)m.title=a.title,m.prevTitle=a.prevTitle;else if("remove"==e)m.parent=a.parent,m.prev=a.prev;else if("delete"==e)m.prev=a.prev,m.parent=a.parent;else if("expandAll"===e||"collapseAll"===e||"deselectAll"===e)m.targ=a.targ;if(k){if(c=this._trigger(e,new f.Event("oj"+e),m),g)return"undefined"!=typeof c&&
(c=c?!0:!1),c}else this.ea.trigger(e,m)}}},Oi:function(){return this.get_rollback()},wV:function(){},Uk:function(){this.xx();this.zf&&this.ea.addClass("oj-tree-rtl").css("direction","rtl");this.ea.html("\x3cul role\x3d'tree' tabindex\x3d'0' class\x3d'oj-tree-list' style\x3d'outline:none'"+(-1===this.f.F.Zd?" aria-multiselectable\x3d'true'":"")+"\x3e\x3cli class\x3d'oj-tree-last oj-tree-leaf'\x3e\x3cins\x3e\x26#160;\x3c/ins\x3e\x3ca class\x3d'oj-tree-loading' href\x3d'#'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e"+
this.C("m_loading")+"\x3c/a\x3e\x3c/li\x3e\x3c/ul\x3e");this.aa=this.ea.children("ul:eq(0)");this.ea.data("oj-tree-instance-id",this.yd);this.f.F.Ke=this.aa.find("li.oj-tree-closed, li.oj-tree-leaf").eq(0).height()||18;this.ea.delegate(".oj-tree-list li \x3e ins","click.ojtree",f.proxy(function(a){a=f(a.target);this.toggleExpand(a)},this)).bind("mousedown.ojtree",f.proxy(function(){this.xx()},this)).bind("dblclick.ojtree",function(){var a;if(document.selection&&document.selection.empty)document.selection.empty();
else if(window.getSelection){a=window.getSelection();try{a.removeAllRanges(),a.collapse(document.getElementsByTagName("body")[0],0)}catch(b){}}});this.aa.focus(f.proxy(function(){this.f.ui.Ud=!0},this)).blur(f.proxy(function(){this.f.ui.Ud=!1},this));this.f.F.lU&&this.ea.bind("treeload_node",f.proxy(function(a,b){var c=this.na(b.item);-1===c&&(c=this.aa);c.length&&c.find("li.oj-tree-open:not(:has(ul))").each(function(){this.hg(this,f.noop,f.noop)})},this));this.wa({},"init");this.NC();this.f.menu.pe&&
this.Zl();d({dC:this.CP,uE:this.aa,hF:this});this.DM()},ZO:function(){this.f.F.locked=!1;this.ea.addClass("oj-tree oj-tree-"+this.yd);this.ea.css("outline","none");this.ea.css("MozUserSelect","none");this.ea.css("WebkitTouchCallout","none");this.ea.css("WebkitUserSelect","none");this.ea.css("WebkitTapHighlightColor","rgba(0,0,0,0)")},kP:function(){this.f.ui.selected=f();this.f.ui.Ib=!1;this.f.ui.zb=null;this.ea.delegate(".oj-tree-list a","click.ojtree",f.proxy(function(a){a.preventDefault();a.currentTarget.blur();
f(a.currentTarget).hasClass("oj-tree-loading")||(this.xx(),this.Pk(a.currentTarget,!0,a))},this)).delegate(".oj-tree-list a","mouseenter.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.hover(a.target)},this)).delegate(".oj-tree-list a","mouseleave.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.dehover(a.target)},this)).bind("treereopen",f.proxy(function(){this.reselect()},this)).bind("treeget_rollback",f.proxy(function(){this.dehover();
this.save_selected()},this)).bind("treeset_rollback",f.proxy(function(){this.reselect()},this)).bind("ojcollapse",f.proxy(function(a,b){var c=this.na(b.item),d=c&&c.length?c.children("ul").find("a.oj-tree-clicked"):f();!1!==this.options.selectedParentCollapse&&d.length&&d.each(function(){this.deselect(this);"selectParent"===this.options.selectedParentCollapse&&this.select(c)})},this)).bind("ojremove",f.proxy(function(a,b){var c=this.options.selectPrevOnDelete,d=this.na(b.item),d=d&&d.length?d.find("a.oj-tree-clicked"):
[],e=this;d.each(function(){e.deselect(this)});c&&d.length&&b.prev.each(function(){if(this.parentNode)return e.select(this),!1})},this)).bind("ojmove",f.proxy(function(a,b){var c=b.data;c.cy&&(c.oc.find("a.oj-tree-clicked").removeClass("oj-tree-clicked"),c.oc.removeAttr("aria-selected"))},this))},pC:function(){this.hP();this.dP();this.cP()},hP:function(){1===this.f.za.type&&(this.gF=this.options.data||null,this.hg=this.HP,this.Wg=this.zP,this.Pb=this.OQ)},dP:function(){3===this.f.za.type&&(this.f.za.ul&&
this.ea.bind("treeafter_close",function(a,b){b.item.children("ul").remove()}),this.hg=this.JP,this.Wg=this.BP,this.Pb=this.PQ)},cP:function(){4===this.f.za.type&&(this.uD(),this.hg=this.IP,this.Wg=this.AP,this.Pb=this.vv)},uD:function(){this.f.html.Mr&&(this.f.html.pl||(this.f.html.pl=this.ea.find(" \x3e ul"),this.f.html.vr=f("\x3cdiv id\x3d'oj-tree-existing-markup-"+this.yd+"' style\x3d'display:none'\x3e").append(this.f.html.pl),this.ea.after(this.f.html.vr)),this.f.html.eH=this.f.html.pl.find(" \x3e li"),
this.f.html.Yq=this.f.html.eH.clone(!0),this.f.html.Yq.find("li").addBack().contents().filter(function(){return 3==this.nodeType}).remove())},fP:function(){!1===this.f.Ia.mn&&f("script").each(function(){if(this.src.toString().match(/jquery\.oj-tree[^\/]*?\.js(\?.*)?$/))return this.f.Ia.mn=this.src.toString().replace(/jquery\.oj-tree[^\/]*?\.js(\?.*)?$/,"")+"themes/",!1});!1===this.f.Ia.mn&&(this.f.Ia.mn="themes/");this.ea.bind("treeinit",f.proxy(function(){var a=this.options;this.f.Ia.Bn=a.dots;this.f.Ia.icons=
a.icons;this.set_theme(this.f.Ia.lf,this.f.Ia.url)},this)).bind("ojloaded",f.proxy(function(){this.f.Ia.Bn?this.RE():this.hC();this.f.Ia.icons?this.Kv():this.Cu()},this))},jP:function(){var a=this.options.types;a&&this.ea.bind("treeinit",f.proxy(function(){var c=f.extend(!0,{},a.types),d=a.attr||this.f.types.pc.attr,e="",g=this;f.each(c,function(a,b){f.each(b,function(a){/^(maxDepth|maxChildren|icon|validChildren)$/.test(a)||g.f.types.IF.push(a)});var c=typeof b.icon;if("undefined"===c){c=typeof b.image;
if("boolean"===c&&!b.image)b.image="ojt$none";else if(!b.image&&!b.position)return!0;b.icon={};b.image&&(b.icon.image=b.image,delete b.image);void 0!==b.position&&(b.icon.position=b.position,delete b.position)}if(b.icon.image||b.icon.position)"default"==a?(g.f.types.cl=!0,e+=".oj-tree-"+g.yd+" .oj-tree-list a \x3e .oj-tree-icon { ",e+=g.tz(b,e),e+="} ",e+=".oj-tree-"+g.yd+" .oj-tree-list li["+d+'\x3d"oj-tree-deftype"] \x3e a .oj-tree-icon { '):b.icon.image&&(e+=".oj-tree-"+g.yd+" .oj-tree-list li["+
d+'\x3d"'+a+'"] \x3e a \x3e ins.oj-tree-icon { '),e+=g.tz(b,e),e+="} "});""!==e&&b({Ir:e,title:"oj-tree-types"})},this)).bind("ojbefore",f.proxy(function(a,b){var c,d,e=b.func,g=b.item;if((c=(c=this.f.types.pc.useData?this.na(g):!1)&&-1!==c&&c.length?c.data("oj-tree"):!1)&&c.types&&!1===c[e]||-1!==f.inArray(e,this.f.types.IF)&&b.item&&(b.item.tagName||b.item.jquery)&&(c=this.options.types.types,d=this.ru(g),(c[d]&&"undefined"!==typeof c[d][e]||c["default"]&&"undefined"!==typeof c["default"][e])&&
!1===this.$z(e,g)))return a.stopImmediatePropagation(),!1},this))},tz:function(a){var b="",b="ojt$none"!==a.icon.image?b+(" background-image:url("+a.icon.image+"); "):b+" background-image:none; ";return b=a.icon.position?b+(" background-position:"+a.icon.position+"; "):b+" background-position:0 0; "},bP:function(){if(this.f.dnd.wl){var a=this.f.dnd.hb;a.dc=f("\x3cdiv /\x3e").addClass("oj-tree-marker").hide().html("\x26raquo;").bind("mouseleave mouseenter",f.proxy(function(a){var b=this.f.dnd.hb;b.dc.hide();
b.tb.hide();a.preventDefault();a.stopImmediatePropagation();return!1},this)).appendTo("body");this.zf&&a.dc.addClass("oj-tree-marker-rtl");a.tb=f("\x3cdiv /\x3e").addClass("oj-tree-marker-line").hide().bind("mouseup",function(a){var b=this.f.dnd.hb;if(b.ua&&b.ua.length)return b.ua.children("a").trigger(a),a.preventDefault(),a.stopImmediatePropagation(),!1}).bind("mouseleave",f.proxy(function(a){var b=this.f.dnd.hb,c=f(a.relatedTarget);if((c.is(".oj-tree")||0===c.closest(".oj-tree").length)&&b.ua&&
b.ua.length)return b.ua.children("a").trigger(a),b.dc.hide(),b.tb.hide(),a.preventDefault(),a.stopImmediatePropagation(),!1},this)).appendTo("body");this.f.dnd.fH=a.tb.width();f(document).bind("drag_start.ojtreeu",f.proxy(function(a,b){var c=this.f.dnd.hb;b.data.Je&&(c.dc.show(),c.tb&&c.tb.show())},this));f(document).bind("drag_stop.ojtreeu",f.proxy(function(a,b){var c=this.f.dnd.hb;b.data.Je&&(c.dc.hide(),c.tb&&c.tb.hide())},this));this.ea.bind("mouseenter.ojtree",f.proxy(function(a){var b=this.f.dnd.xb,
c=this.f.dnd.hb;b.Ie&&b.Cc.Je&&(this.options.themes&&(c.dc.addClass("oj-tree-"+this.f.Ia.lf),c.tb&&c.tb.addClass("oj-tree-"+this.f.Ia.lf),b.helper.addClass("oj-tree-dnd-helper oj-tree-"+this.f.Ia.lf)),a.currentTarget===a.target&&b.Cc.Ai&&f(b.Cc.Ai).length&&f(b.Cc.Ai).parents(".oj-tree:eq(0)")[0]!==a.target&&(a=this.HD(a.target),a.data.dnd.fr?(c=a.options.dnd.drag_check.call(this,{o:c.Ya,r:a.ea,is_root:!0}),!0!==c&&!0!==c.inside&&!0!==c.before&&!0!==c.after||b.helper.children("ins").removeClass("oj-tree-invalid").addClass("oj-tree-ok")):
(a.Kk(c.Ya,a.ea,"last"),a.check_move()&&b.helper.children("ins").removeClass("oj-tree-invalid").addClass("oj-tree-ok"))))},this)).bind("mouseup.ojtree",f.proxy(function(a){var b=this.f.dnd.hb,c=this.f.dnd.xb;c.Ie&&c.Cc.Je&&a.currentTarget===a.target&&c.Cc.Ai&&f(c.Cc.Ai).length&&f(c.Cc.Ai).parents(".oj-tree:eq(0)")[0]!==a.target&&(c=this.HD(a.currentTarget),c.data.dnd.foreign?(a=c.Ug().dnd.drag_check.call(this,{o:b.Ya,r:c.ea,is_root:!0}),!0!==a&&!0!==a.inside&&!0!==a.before&&!0!==a.after||c.Ug().dnd.drag_finish.call(this,
{o:b.Ya,r:c.ea,is_root:!0})):c.Hk(b.Ya,c.ea,"last",a[c.options.dnd.copy_modifier+"Key"]))},this)).bind("mouseleave.ojtree",f.proxy(function(a){var b=this.f.dnd.xb;if(a.relatedTarget&&f(a.relatedTarget).hasClass("oj-tree-marker-line"))return!1;b.Ie&&b.Cc.Je&&(this.f.dnd.Fe&&clearInterval(this.f.dnd.Fe),this.f.dnd.Ge&&clearInterval(this.f.dnd.Ge),this.f.dnd.Of&&clearTimeout(this.f.dnd.Of),this.f.dnd.mf&&clearTimeout(this.f.dnd.mf),b.helper.children("ins").hasClass("oj-tree-ok")&&b.helper.children("ins").removeClass("oj-tree-ok").addClass("oj-tree-invalid"))},
this)).bind("mousemove.ojtree",f.proxy(function(a){var b=this.f.dnd.xb;if(b.Ie&&b.Cc.Je){var c=this.ea[0];a.pageX+24>this.f.dnd.al.left+this.f.dnd.vw?(this.f.dnd.Fe&&clearInterval(this.f.dnd.Fe),this.f.dnd.Fe=setInterval(f.proxy(function(){this.scrollLeft+=b.Fi},c),100)):a.pageX-24<this.f.dnd.al.left?(this.f.dnd.Fe&&clearInterval(this.f.dnd.Fe),this.f.dnd.Fe=setInterval(f.proxy(function(){this.scrollLeft-=b.Fi},c),100)):this.f.dnd.Fe&&clearInterval(this.f.dnd.Fe);a.pageY+24>this.f.dnd.al.top+this.f.dnd.ch?
(this.f.dnd.Ge&&clearInterval(this.f.dnd.Ge),this.f.dnd.Ge=setInterval(f.proxy(function(){this.scrollTop+=b.Fi},c),100)):a.pageY-24<this.f.dnd.al.top?(this.f.dnd.Ge&&clearInterval(this.f.dnd.Ge),this.f.dnd.Ge=setInterval(f.proxy(function(){this.scrollTop-=b.Fi},c),100)):this.f.dnd.Ge&&clearInterval(this.f.dnd.Ge)}},this)).bind("scroll.ojtree",f.proxy(function(){var a=this.f.dnd.xb,b=this.f.dnd.hb;a.Ie&&a.Cc.Je&&b.dc&&b.tb&&(b.dc.hide(),b.tb.hide())},this)).delegate(".oj-tree-list a","mousedown.ojtree",
f.proxy(function(a){if(1===a.which)return this.aS(a.currentTarget,a),!1},this)).delegate(".oj-tree-list a","mouseenter.ojtree",f.proxy(function(a){var b=this.f.dnd.xb;b.Ie&&b.Cc.Je&&this.wt(a.currentTarget)},this)).delegate(".oj-tree-list a","mousemove.ojtree",f.proxy(function(a){var b=this.f.dnd.xb,c=this.f.dnd.hb;b.Ie&&b.Cc.Je&&(c.ua&&c.ua.length&&c.ua.children("a")[0]===a.currentTarget||this.wt(a.currentTarget),"undefined"===typeof this.f.dnd.off.top&&(this.f.dnd.off=f(a.target).offset()),"undefined"===
typeof this.f.dnd.off.top&&(this.f.dnd.off=f(a.target).offset()),this.f.dnd.Xc=(a.pageY-(this.f.dnd.off.top||0))%this.f.F.Ke,0>this.f.dnd.Xc&&(this.f.dnd.Xc+=this.f.F.Ke),this.xt())},this)).delegate(".oj-tree-list a","mouseleave.ojtree",f.proxy(function(a){var b=this.f.dnd.xb,c=this.f.dnd.hb;if(b.Ie&&b.Cc.Je){if(a.relatedTarget&&f(a.relatedTarget).hasClass("oj-tree-marker-line"))return!1;c.dc&&c.dc.hide();c.tb&&c.tb.hide();this.f.dnd.wr=setTimeout(function(b){return function(){b.vM(a)}}(this),0)}},
this)).delegate(".oj-tree-list a","mouseup.ojtree",f.proxy(function(a){var b=this.f.dnd.xb;b.Ie&&b.Cc.Je&&this.uM(a)},this));f(document).bind("drag_stop.ojtreeu",f.proxy(function(){var a=this.f.dnd,b=this.f.dnd.hb;a.Of&&clearTimeout(a.Of);a.mf&&clearTimeout(a.mf);a.Fe&&clearInterval(a.Fe);a.Ge&&clearInterval(a.Ge);a.after=!1;a.before=!1;a.inside=!1;a.off=!1;a.ho=!1;a.Xc=!1;a.Of=!1;a.mf=!1;a.Fe=!1;a.Ge=!1;a.la=!1;a.fr=!1;b.dc&&b.dc.css({top:"-2000px"});b.tb&&b.tb.css({top:"-2000px"})},this)).bind("drag_start.ojtreeu",
f.proxy(function(a,b){if(b.data.Je){var c=f(b.event.target);c.closest(".jstree").hasClass("oj-tree-"+this.yd)&&this.wt(c)}},this));a=this.options.dnd;a.drag_target&&f(document).delegate(a.drag_target,"mousedown.ojtree-"+this.yd,f.proxy(function(a){var b=this.f.dnd.xb,c=this.f.dnd,d=this.f.dnd.hb;d.Ya=a.target;this.TA(a,{Je:!0,Ai:a.target},"\x3cins class\x3d'oj-tree-icon'\x3e\x3c/ins\x3e"+f(a.target).text());this.f.Ia&&(d.dc&&d.dc.addClass("oj-tree-"+this.f.Ia.lf),d.tb&&d.tb.addClass("oj-tree-"+this.f.Ia.lf),
b.helper.addClass("oj-tree-dnd-helper oj-tree-"+this.f.Ia.lf));b.helper.children("ins").removeClass("oj-tree-ok").addClass("oj-tree-invalid");b=this.ea;c.al=b.offset();c.vw=parseInt(b.width(),10);c.ch=parseInt(b.height(),10);c.fr=!0;a.preventDefault()},this));a.drop_target&&f(document).delegate(a.drop_target,"mouseenter.ojtreex-"+this.yd,f.proxy(function(a){var b=this.f.dnd,c=this.f.dnd.hb;b.la&&this.options.dnd.drop_check.call(this,{o:c.Ya,r:f(a.target),e:a})&&b.xb.helper.children("ins").removeClass("oj-tree-invalid").addClass("oj-tree-ok")},
this)).delegate(a.drop_target,"mouseleave.ojtree-"+this.yd,f.proxy(function(){this.f.dnd.la&&this.f.dnd.xb.helper.children("ins").removeClass("oj-tree-ok").addClass("oj-tree-invalid")},this)).delegate(a.drop_target,"mouseup.ojtreex-"+this.yd,f.proxy(function(a){var b=this.f.dnd.hb;this.f.dnd.la&&this.f.dnd.xb.helper.children("ins").hasClass("oj-tree-ok")&&this.options.dnd.drop_finish.call(this,{o:b.Ya,r:f(a.target),e:a})},this))}},qC:function(){this.f.dnd.wl=!1;var a=this.options.dnd,b=!0;"object"===
typeof a&&(a=a.reorder,"string"===typeof a&&("enable"===a?(this.f.dnd.wl=!0,b=!1):"disable"==a&&(b=!1)));this.f.dnd.wl?(this.options.dnd={},this.yz(this.options.dnd,this.f.dnd.pc),this.options.dnd.reorder="enable"):b&&(this.options.dnd={reorder:"disable"})},YV:function(){},Km:function(a){var b,c;a||this.options.contextMenu||(b=this.ea.attr("contextmenu"))&&(this.options.contextMenu="#"+b);if(a||this.options.contextMenu){b=a||this.options.contextMenu;c=f.type(b);if("function"==c){try{b=b()}catch(d){b=
null}c=f.type(b)}if("string"===c){if(b=f(b))b.css("display","none"),c=this.f.menu,c.Jd=b,c.pe=!0;this.f.menu.pe&&a&&this.Zl()}}},Ph:function(a){this.f.menu.sg="keydown"===a.originalEvent.originalEvent.type?this.f.ui.zb:f(a.originalEvent.target.parentNode);this.f.menu.gV=this.f.menu.sg.closest("div").attr("id");this.f.menu.Jd.ojMenu("option","menuPosition",{my:"left top",at:"left bottom",of:this.f.menu.sg[0]});if(this.f.menu.pe&&this.f.menu.Al){a=this.f.menu.Al.hasClass("oj-disabled");var b=!this.f.Hb.bf&&
!this.f.Hb.tj;a||(a=!1);a!=b&&(b?this.f.menu.Al.addClass("oj-disabled"):this.f.menu.Al.removeClass("oj-disabled"),this.f.menu.Jd.ojMenu("refresh"))}},Qh:function(a,b){if(!b.inst&&this.f.menu.gV==this.WA.substr(1)){var c=b?b.item.attr("id"):void 0;"ojtreecopy"===c?this.bM(this.f.menu.sg):"ojtreecut"===c?this.dM(this.f.menu.sg):"ojtreepaste"===c?this.eM(this.f.menu.sg):"ojtreeremove"===c?this.isSelected(this.f.menu.sg)?this.wA():this.wA(this.f.menu.sg):"ojtreerename"===c?this.fM(this.f.menu.sg):"ojtreecreate"===
c&&this.cM(this.f.menu.sg)}},Zg:function(a,b){a.show(b,{launcher:this.aa,focus:"menu"})},$O:function(){var a=this.options.selectionMode,a=void 0==a?"single":a;"none"===a?a=0:"single"===a?a=1:"multiple"===a&&(a=-1);this.f.F.Zd=a;this.f.Ia.icons=this.options.icons;this.f.F.qc=this.options.initExpanded;null==this.f.F.qc&&(this.f.F.qc=[]);this.f.F.Gi=this.options.initLoaded},bW:function(){},oC:function(b){var c=this.options.data,d;this.f.za.type=0;this.f.html.Mr=!1;this.f.html.Yq=!1;if(c)if(d=f.type(c),
"string"===d)this.uP(c)?this.f.za.type=4:this.f.za.type=3;else if("array"===d)this.f.za.type=3;else if("object"===d){try{c instanceof a.Ub&&(this.f.za.type=1)}catch(e){this.f.za.type=-1}if(1!==this.f.za.type)try{c instanceof a.va&&(this.f.za.type=2)}catch(g){this.f.za.type=-1}1!==this.f.za.type&&2!==this.f.za.type&&(c.data||c.ajax)&&((d=c.dataType)?"json"===d?this.f.za.type=3:"html"===d&&(this.f.za.type=4):(c.dataType="json",this.f.za.type=3))}b&&0==this.f.za.type&&0<this.ea.find("ul").length&&(this.f.za.type=
4,this.f.html.Mr=!0)},aW:function(){},XV:function(){},WV:function(){},VV:function(){},ZV:function(){},$V:function(){},iP:function(){var a=this.options.types;"object"===typeof a&&this.yz(a,{attr:this.f.types.pc.attr})},aP:function(){var a=this.f;a.F={ml:!1,$T:[],Zd:1,lU:!1,Ke:0,HW:!1,qc:!1,Gi:!1,qd:{},yW:!1};a.ui={selected:f(),Ib:!1,zb:null,Kr:null,opacity:1,zx:!1,Ud:!1};a.ui.pc={selectMultipleModifier:"ctrl",selectRangeModifier:"shift",disableSelectingChildren:!1};a.Hb={};a.Hb.tj=!1;a.Hb.bf=!1;a.Hb.pc=
{inputWidthLimit:200,move:{alwaysCopy:!1,openOnMove:!0,defaultPosition:"last",checkMove:function(){return!0}}};a.Hb.qd={};a.za={};a.za.lx=!1;a.za.ul=!1;a.za.Qd=!0;a.za.type=0;a.iU={};a.iU.pc={data:!1,ajax:!1};a.html={};a.html.pc={data:!1,ajax:!1};a.html.Mr=!1;a.html.pl=!1;a.html.vr=!1;a.html.eH=!1;a.html.Yq=!1;a.Ia={};a.Ia.icons=!0;a.Ia.Bn=!1;a.Ia.lf="default";a.Ia.url=!1;a.Ia.MH=[];a.Ia.mn=!1;a.types={};a.types.IF=[];a.types.cl=!1;a.types.pc={maxChildren:-1,maxDepth:-1,validChildren:"all",useData:!1,
attr:"type",types:{"default":{maxChildren:-1,maxDepth:-1,validChildren:"all"}}};a.menu={};a.menu.pe=!1;a.menu.Jd=!1;a.menu.Al=!1;a.menu.sg=!1;a.keys={};a.keys.uT=!0;a.keys.bound=[];a.dnd={};a.dnd.wl=!1;a.dnd.la=!1;a.dnd.after=!1;a.dnd.inside=!1;a.dnd.before=!1;a.dnd.off=!1;a.dnd.ho=!1;a.dnd.Xc=0;a.dnd.Of=!1;a.dnd.mf=!1;a.dnd.al=!1;a.dnd.vw=!1;a.dnd.ch=!1;a.dnd.Fe=!1;a.dnd.Ge=!1;a.dnd.wr=!1;a.dnd.fH=100;a.dnd.LH=100;a.dnd.pc={copy_modifier:"ctrl",check_timeout:100,open_timeout:500,drop_target:".oj-tree-drop",
drop_check:function(){return!0},drop_finish:f.noop,drag_target:".oj-tree-draggable",drag_finish:f.noop,drag_check:function(){return{after:!1,before:!1,inside:!0}}};a.dnd.hb={};a.dnd.hb.Ya=!1;a.dnd.hb.ua=!1;a.dnd.hb.dc=!1;a.dnd.hb.tb=!1;a.dnd.hb.Vc=void 0;a.dnd.hb.Wc=void 0;a.dnd.hb.dl=!1;a.dnd.hb.el=!1;a.dnd.hb.Xw=!1;a.dnd.xb={};a.dnd.xb.Tw=!1;a.dnd.xb.Ie=!1;a.dnd.xb.helper=!1;a.dnd.xb.Fi=10;a.dnd.xb.Qw=0;a.dnd.xb.Rw=0;a.dnd.xb.aX=5;a.dnd.xb.VT=5;a.dnd.xb.WT=10;a.dnd.xb.Cc={}},hB:function(a){var b=
this.ea[0];b.scrollHeight>b.offsetHeight&&(a=this.na(a))&&-1!==a&&a.length&&a.is(":visible")&&(a=a.offset().top-this.ea.offset().top,0>a&&(b.scrollTop=b.scrollTop+a-1),a+this.f.F.Ke+(b.scrollWidth>b.offsetWidth?k:0)>b.offsetHeight&&(b.scrollTop+=a-b.offsetHeight+this.f.F.Ke+1+(b.scrollWidth>b.offsetWidth?k:0)))},xx:function(){this.kq()||(this.YM()&&this.hV(),this.ea.addClass("oj-tree-focused"),this.aa&&this.aa.focus(),this.f.ui.Ud=!0,this.wa(null,"set_focus"))},kq:function(){return this.f.ui.Ud},
hV:function(){this.kq()&&(this.ea.removeClass("oj-tree-focused"),this.f.ui.Ud=!1,this.aa&&this.aa.blur());this.wa(null,"unset_focus")},YM:function(){var a=null;f.each(t,function(b,c){if(c.f.ui.Ud)return a=c,!1});return a},cQ:function(){return++q},JV:function(){return this.yd},Ug:function(){return f.extend(!0,{},this.options)},DV:function(){return this.ea},CP:{up:function(){this.hover(this.Vg(this.f.ui.zb||this.f.ui.Ib||-1));return!1},"ctrl+up":function(){this.hover(this.Vg(this.f.ui.zb||this.f.ui.Ib||
-1));return!1},"shift+up":function(){this.select(this.Vg(this.f.ui.zb||this.f.ui.Ib||-1),-1!==this.f.ui.Zd);return!1},down:function(){this.hover(this.aj(this.f.ui.zb||this.f.ui.Ib||-1));return!1},"ctrl+down":function(){this.hover(this.aj(this.f.ui.zb||this.f.ui.Ib||-1));return!1},"shift+down":function(){this.select(this.aj(this.f.ui.zb||this.f.ui.Ib||-1),-1!==this.f.ui.Zd);return!1},left:function(){var a=this.f.ui.zb||this.f.ui.Ib;a&&(a.hasClass("oj-tree-open")?this.collapse(a):this.hover(this.Vg(a)));
return!1},"ctrl+left":function(){var a=this.f.ui.zb||this.f.ui.Ib;a&&(a.hasClass("oj-tree-open")?this.collapse(a):this.hover(this.Vg(a)));return!1},"shift+left":function(){var a=this.f.ui.zb||this.f.ui.Ib;a&&(a.hasClass("oj-tree-open")?this.collapse(a):this.hover(this.Vg(a)));return!1},right:function(){var a=this.f.ui.zb||this.f.ui.Ib;a&&a.length&&(a.hasClass("oj-tree-closed")?this.expand(a):this.hover(this.aj(a)));return!1},"ctrl+right":function(){var a=this.f.ui.zb||this.f.ui.Ib;a&&a.length&&(a.hasClass("oj-tree-closed")?
this.expand(a):this.hover(this.aj(a)));return!1},"shift+right":function(){var a=this.f.ui.zb||this.f.ui.Ib;a&&a.length&&(a.hasClass("oj-tree-closed")?this.expand(a):this.hover(this.aj(a)));return!1},space:function(){this.f.ui.zb&&(this.f.ui.zx=!0,this.f.ui.zb.children("a:eq(0)").click(),this.f.ui.zx=!1);return!1},home:function(){this.hover(this.aa.find("li:first"));return!1},end:function(){var a=this.aa.find("li.oj-tree-last:visible");this.hover(a[a.length-1]);return!1},"*":function(){this.aa.find("a");
this.Ct(-1,!1);return!1},"ctrl+space":function(){if(this.f.ui.zb){var a=f.Event("click");a.ctrlKey=!0;this.f.ui.zb.children("a:eq(0)").trigger(a)}return!1},"shift+space":function(){if(this.f.ui.zb){var a=f.Event("click");a.shiftKey=!0;this.f.ui.zb.children("a:eq(0)").trigger(a)}return!1},"shift+home":function(){var a=this.f.ui.zb;if(a){var b=!0,c=this,d=this.aa.find("li:visible"),a=a[0];f.each(d,function(d,e){e==a&&(b=!1);c.Pk(e,!0);return b})}return!1},"shift+pgdn":function(){var a=this.f.ui.zb;
if(a){var b=!1,c=this,d=this.aa.find("li:visible"),a=a[0];f.each(d,function(d,e){b||e==a&&(b=!0);b&&c.Pk(e,!0);return!0})}return!1},f2:function(){this.rename(this.f.ui.zb||this.f.ui.Ib);return!1},del:function(){this.remove(this.f.ui.zb||this.na(null));return!1}},Zl:function(){if(this.f.menu.pe){var a=this.f.menu.Jd,b=this;a.on("ojselect",f.proxy(this.Qh,this));a.on("ojbeforeshow",f.proxy(this.Ph,this));var c=!1;a.find("[data-oj-command]").each(function(){var a;0===f(this).children("a").length&&(a=
f(this).attr("data-oj-command").split("-"),f(this).replaceWith(b.Mg(a[a.length-1])),f(this).hasClass("oj-menu-divider")&&f(this).removeClass("oj-menu-divider").addClass("oj-menu-item"),c=!0)});c&&a.ojMenu("refresh");this.f.menu.Al=a.find("#ojtreepaste")}},pp:function(){var a=this.f.menu;a.pe&&(a.pe=!1,a.Jd.off("ojselect"),a.Jd.off("beforeshow"),a.Jd=null)},Mg:function(a){return f(this.fe(a))},fe:function(a){return"\x3cli id\x3d"+g[a]+"\x3e"+this.Ns(a)+"\x3c/li\x3e"},Ns:function(a){return'\x3ca href\x3d"#"\x3e'+
this.C("m_"+a)+"\x3c/a\x3e"},dM:function(a){a=this.na(a,!0);if(!a||!a.length)return!1;this.f.Hb.tj=!1;this.f.Hb.bf=a;this.wa({obj:a},"cut")},bM:function(a){a=this.na(a,!0);if(!a||!a.length)return!1;this.f.Hb.bf=!1;this.f.Hb.tj=a;this.wa({obj:a},"copy")},eM:function(a){a=this.na(a);if(!a||!a.length)return!1;var b=this.f.Hb.bf?this.f.Hb.bf:this.f.Hb.tj;if(!this.f.Hb.bf&&!this.f.Hb.tj)return!1;this.f.Hb.bf&&(this.pt(this.f.Hb.bf,a),this.f.Hb.bf=!1);this.f.Hb.bf&&(this.pt(this.f.Hb.bf,a),this.f.Hb.bf=
!1);this.f.Hb.tj&&this.pt(this.f.Hb.tj,a,!1,!0);this.wa({obj:a,nodes:b},"paste")},pt:function(a,b,c,d,e,f){var g=this.f.Hb.pc.move;if(!e)return"undefined"===typeof c&&(c=g.defaultPosition),"inside"!==c||g.defaultPosition.match(/^(before|after)$/)||(c=g.defaultPosition),this.Hk(a,b,c,d,!1,f);if(!0===g.alwaysCopy||"multitree"===g.alwaysCopy&&a.xl.yd!==a.Dj.yd)d=!0;this.Hk(a,b,c,d,!0,f)},wA:function(a){a=this.na(a,!0);this.Oi();this.remove(a)},fM:function(a){a=this.na(a);this.Oi();this.xA(a,function(){})},
xA:function(a,b){a=this.na(a);var c=this.zf,d=this.f.Hb.pc.inputWidthLimit,e=a.children("ins").width(),g=a.find("\x3e a:visible \x3e ins").width()*a.find("\x3e a:visible \x3e ins").length,h=this.getText(a),k=this,l=f("\x3cdiv /\x3e",{css:{position:"absolute",top:"-200px",left:c?"0px":"-1000px",visibility:"hidden"}}).appendTo("body"),m=a.css("position","relative").append(f("\x3cinput /\x3e",{value:h,"class":"oj-tree-rename-input",css:{padding:"0",border:"1px solid silver",position:"absolute",left:c?
"auto":e+g+4+"px",right:c?e+g+4+"px":"auto",top:"0px",height:this.f.F.Ke-2+"px",lineHeight:this.f.F.Ke-2+"px",width:"150px"},blur:f.proxy(function(){var c=a.children(".oj-tree-rename-input"),d=c.val();""===d&&(d=h);l.remove();c.remove();this.Hv(a,h);this.gE(a,d);b.call(this,a,d,h);a.css("position","")},this),keyup:function(a){a=a.keyCode||a.which;if(!k.yt)return k.yt=!0,!1;27==a?(k.yt=!1,this.value=h,this.blur()):13==a?(k.yt=!1,this.blur()):m.width(Math.min(l.text("pW"+this.value).width(),d))},keypress:function(a){if(13==
(a.keyCode||a.which))return!1}})).children(".oj-tree-rename-input");this.Hv(a,"");l.css({fontFamily:m.css("fontFamily")||"",fontSize:m.css("fontSize")||"",fontWeight:m.css("fontWeight")||"",fontStyle:m.css("fontStyle")||"",fontStretch:m.css("fontStretch")||"",fontVariant:m.css("fontVariant")||"",letterSpacing:m.css("letterSpacing")||"",wordSpacing:m.css("wordSpacing")||""});m.width(Math.min(l.text("pW"+m[0].value).width(),d))[0].select()},cM:function(a,b,c,d,e){var g=this;(a=this.na(a))||(a=-1);this.Oi();
return this.ot(a,b,c,function(a){var b=this.Nh(a),c=f(a).index();d&&d.call(this,a);b.length&&b.hasClass("oj-tree-closed")&&this.expand(b,!1,!0);e?g.wa({obj:a,name:this.getText(a),parent:b,position:c}):this.xA(a,function(a,d){g.wa({obj:a,name:d,parent:b,position:c})})})},BV:function(){return!1},uP:function(a){if(!a||3>a.length)return!1;a=a.trim();return"\x3c"===a.charAt(0)},JK:function(){var a=this.option.emptyText;"string"!==typeof a&&(a=this.C("m_emptyText"));a&&0<a.length&&(a="\x3cli class\x3d'oj-tree-empty'\x3e"+
a+"\x3c/li\x3e",this.aa.empty().append(a))},DQ:function(a){var b,c,d;d=null;var e;a&&(b=a.subId);if(!b)return null;d=b.split("[");if(3===d.length&&(d[0]=d[0].trim(),"oj-tree-node"===d[0]&&(d[1]=d[1].trim(),b=d[1].charAt(0),b=d[1].indexOf(b,1),0<=b&&(a=d[1].substring(1,b).trim(),d[2]=d[2].trim(),b=d[2].charAt(0),b=d[2].indexOf(b,1),0<=b)))){d=d[2].substring(1,b).trim();try{c=this.na(a)}catch(f){c=null}if(d&&c&&-1!==c)switch(d){case "icon":this.f.Ia.icons&&(e=c.find(" \x3e a \x3e ins:eq(0)"));break;
case "link":e=c.find(" \x3e a:eq(0)");break;case "disclosure":this.BC(c)||(e=c.find(" \x3e ins:eq(0)"));break;case "title":e=c.find(" \x3e a \x3e span")}}return e?e.length?e[0]:null:null},hC:function(){this.f.Ia.Bn=!1;this.ea.children("ul").addClass("oj-tree-no-dots")},RE:function(){this.f.Ia.Bn=!0;this.ea.children("ul").removeClass("oj-tree-no-dots")}})})()});
//# sourceMappingURL=oj-modular.map