define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){a.Fa("oj.ojTrain",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{steps:[],selection:"next",currentStep:"",optionChange:null},yc:0,ra:null,_create:function(){var a=this.options;this._super();this.yc=a.steps.length;this.Ek=(this.zf="rtl"===this.uc())?"margin-right":"margin-left";this.Pi=this.zf?"right":"left";var d=f("\x3cdiv class\x3d'oj-train-bar'\x3e\x3c/div\x3e");this.Fk=
this.element.width()<107*(this.yc-1)+72?(this.element.width()-72)/(this.yc-1):107;this.Ws=(this.element.width()-this.Fk*(this.yc-1)-72)/2;this.Af=f("\x3cul\x3e").attr({"aria-label":"Train Component"}).css({margin:"0",padding:"0"});1<this.yc&&d.css({"margin-top":"7px",width:(this.yc-1)*this.Fk+"px"}).css(this.Ek,36+this.Ws+"px").css(this.Pi,0);d.appendTo(this.element);this.BD=f("\x3cdiv class\x3d'oj-train-bar-overlay'\x3e\x3c/div\x3e");this.BD.appendTo(this.element);this.TR();this.Xe=this.kN(a.currentStep);
for(d=0;d<this.yc;d++){var c=f("\x3cli\x3e").attr({id:this.ra[d][1]}).css({"list-style-type":"none",position:"absolute"}).css(this.Ek,this.Ws+this.Fk*d+"px").css(this.Pi,0);this.Af.append(c);d==this.Xe+1&&"next"==a.selection&&(this.ra[d][2]="on");this.nm(d);this.VA(d);this.lm(d);this.UA(d)}this.tF();this.element.addClass("oj-train")},tF:function(){this.BD.css({"margin-top":"7px",width:(this.Xe===this.yc-1?(this.yc-1)*this.Fk:this.Fk*this.Xe+this.Fk/107*53.5)+"px"}).css(this.Ek,this.Ws+36+"px").css(this.Pi,
0);this.Af.appendTo(this.element)},TR:function(){var a=this.options;this.ra=[];for(var d=0;d<this.yc;d++){var c=a.steps[d];this.ra[d]=Array(5);this.ra[d][2]=a.selection&&"next"!=a.selection?a.selection:"off";this.ra[d][3]="unvisited";for(var e in c)"name"===e?this.ra[d][0]=c[e]:"id"===e?this.ra[d][1]=c[e]:"selection"===e?this.ra[d][2]=c[e]:"state"===e?this.ra[d][3]=c[e]:"messageType"===e&&(this.ra[d][4]=c[e])}},lm:function(a){var d=f("\x3cdiv/\x3e"),c=f("\x3cspan/\x3e"),e=this,g="";if(this.ra[a]){var h=
this.ra[a][3];this.Xe===a?(d.addClass("oj-train-button-current"),g=". This is the current step."):"visited"===h?(d.addClass("oj-train-button-visited"),g=". This step has been visited."):"unvisited"===h?(d.addClass("oj-train-button-unvisited"),g=". This step has not been visited yet."):d.addClass("oj-train-button-disabled");"disabled"===this.ra[a][3]||null!=this.options.disabled&&this.options.disabled||"on"!==this.ra[a][2]||(this._hoverable(d),d.bind("click"+this.eventNamespace,function(){var a=e.options.currentStep;
e.options.currentStep=this.parentNode.id;e.dg("currentStep",a,this.parentNode.id,!0)}));d.css({"margin-top":"4px",width:"12px",height:"12px"}).css(this.Ek,"29px").css(this.Pi,0);h=this.Af.children().eq(a).children();3<=h.length?(h[2].parentNode.removeChild(h[2]),d.insertAfter(h[1])):this.Af.children().eq(a).append(d);c.text(g);c.css("display","none");this.Af.children().eq(a).find("a").append(c)}},UA:function(a){var d=f("\x3cdiv/\x3e"),c=f("\x3cspan/\x3e"),e="",g=this;if(this.ra[a]){var h=this.ra[a][4];
"complete"===h?(d.addClass("oj-train-icon-complete"),e=" Complete"):"info"===h?(d.addClass("oj-train-icon-info"),e=" Info"):"error"===h?(d.addClass("oj-train-icon-error"),e=" Error"):"warning"===h&&(d.addClass("oj-train-icon-warning"),e=" Warning");var k=this.Af.children().eq(a).children();4<=k.length&&k[3].parentNode.removeChild(k[3]);"disabled"===this.ra[a][3]||null!=this.options.disabled&&this.options.disabled||"on"!==this.ra[a][2]||(this._hoverable(d),d.bind("click"+this.eventNamespace,function(){var a=
g.options.currentStep;g.options.currentStep=this.parentNode.id;g.dg("currentStep",a,this.parentNode.id,!0)}));null!=h&&"none"!=h&&(d.css({"margin-top":"9px",height:"9px",width:"9px"}).css(this.Ek,"34px").css(this.Pi,0),c.text(e),c.css("display","none"),this.Af.children().eq(a).find("a").append(c),this.Af.children().eq(a).append(d))}},dg:function(a,d,c,e){this._trigger("optionChange",e,{option:a,previousValue:d,value:c,optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}})},VA:function(a){var d=
f("\x3cdiv/\x3e");this.ra[a]&&(a<=this.Xe?d.addClass("oj-train-stepBackground-overlay"):d.addClass("oj-train-stepBackground"),d.css(this.Ek,"25px").css(this.Pi,0),a=this.Af.children().eq(a).children(),1<a.length&&a[1].parentNode.removeChild(a[1]),d.insertAfter(a[0]))},nm:function(a){var d=this;if(this.ra[a]){var c=f("\x3ca\x3e"+this.ra[a][0]+"\x3c/a\x3e");c.addClass("oj-train-label");c.css("margin-bottom","7px");c.css(this.Pi,0);a===this.Xe?c.addClass("oj-selected"):"visited"===this.ra[a][3]?c.addClass("oj-visited"):
"disabled"===this.ra[a][3]&&c.addClass("oj-disabled");"on"!==this.ra[a][2]||null!=this.options.disabled&&this.options.disabled||(c.attr("href","#"),this._hoverable(c),c.bind("click keydown"+this.eventNamespace,function(a){a.preventDefault();if(a.keyCode===f.ui.keyCode.ENTER||"click"==a.type)a=d.options.currentStep,d.options.currentStep=this.parentNode.id,d.dg("currentStep",a,this.parentNode.id,!0)}));var e=this.Af.children().eq(a).children();1<=e.length&&e[0].parentNode.removeChild(e[0]);this.Af.children().eq(a).prepend(c)}},
kN:function(a){for(var d=0;d<this.yc;d++)if(this.ra[d]&&this.ra[d][1]===a)return d;return 0},getStepName:function(a){for(var d=0;d<this.yc;d++)if(this.ra[d]&&this.ra[d][1]===a)return this.ra[d][0];return null},getStepId:function(a){for(var d=0;d<this.yc;d++)if(this.ra[d]&&this.ra[d][0]===a)return this.ra[d][1];return null},select:function(a){for(var d=0;d<this.yc;d++)if(this.ra[d]&&this.ra[d][1]===a){"next"===this.options.selection&&d+1<this.yc&&(this.ra[d+1][2]="on",this.nm(d+1),this.lm(d+1));this.ra[d][3]=
"current";this.Xe=d;this.options.currentStep=a;this.nm(d);this.lm(d);this.tF();break}for(d=0;d<this.yc;d++)this.VA(d)},deselect:function(a,d,c,e){for(var f=0;f<this.yc;f++)if(this.ra[f]&&this.ra[f][1]===a){d?this.ra[f][2]=d:this.ra[f][2]="off";c?this.ra[f][3]=c:this.ra[f][3]="visited";e?this.ra[f][4]=e:this.ra[f][4]="none";this.Xe=-1;"next"===this.options.selection&&f+1<this.yc&&(this.ra[f+1][2]="off",this.nm(f+1),this.lm(f+1));this.nm(f);this.lm(f);this.UA(f);break}},nextSelectableStep:function(){for(var a=
this.Xe;a<this.yc;a++)if(a+1<this.yc&&this.ra[a+1]&&"on"===this.ra[a+1][2])return this.ra[a+1][1];return this.ra[this.Xe][1]},previousSelectableStep:function(){for(var a=this.Xe;0<=a;a--)if(this.ra[a-1]&&"on"===this.ra[a-1][2])return this.ra[a-1][1];return this.ra[this.Xe][1]}})})()});
//# sourceMappingURL=oj-modular.map