/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtTreemap"],function(a,f){a.Fa("oj.ojTreemap",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{isolate:null,select:null},pf:function(a,d,c){return DvtTreemap.newInstance(a,d,c)},Ue:function(){var a=this._super();a.push("oj-treemap");return a},Ki:function(){var a=this._super();a["oj-treemap-isolate-icon"]={path:"_resources/isolate",property:"CSS_URL"};a["oj-treemap-isolate-icon oj-hover"]=
{path:"_resources/isolateOver",property:"CSS_URL"};a["oj-treemap-isolate-icon oj-active"]={path:"_resources/isolateDown",property:"CSS_URL"};a["oj-treemap-restore-icon"]={path:"_resources/restore",property:"CSS_URL"};a["oj-treemap-restore-icon oj-hover"]={path:"_resources/restoreOver",property:"CSS_URL"};a["oj-treemap-restore-icon oj-active"]={path:"_resources/restoreDown",property:"CSS_URL"};a["oj-treemap-attribute-type-text"]={path:"styleDefaults/_attributeTypeTextStyle",property:"CSS_TEXT_PROPERTIES"};
a["oj-treemap-attribute-value-text"]={path:"styleDefaults/_attributeValueTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-node"]={path:"nodeDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-node oj-hover"]={path:"nodeDefaults/hoverColor",property:"border-top-color"};a["oj-treemap-node oj-selected"]=[{path:"nodeDefaults/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/selectedInnerColor",property:"border-bottom-color"}];a["oj-treemap-node-header"]=[{path:"nodeDefaults/header/backgroundColor",
property:"background-color"},{path:"nodeDefaults/header/borderColor",property:"border-top-color"},{path:"nodeDefaults/header/labelStyle",property:"CSS_TEXT_PROPERTIES"}];a["oj-treemap-node-header oj-hover"]=[{path:"nodeDefaults/header/hoverBackgroundColor",property:"background-color"},{path:"nodeDefaults/header/hoverOuterColor",property:"border-top-color"},{path:"nodeDefaults/header/hoverInnerColor",property:"border-bottom-color"}];a["oj-treemap-node-header oj-selected"]=[{path:"nodeDefaults/header/selectedBackgroundColor",
property:"background-color"},{path:"nodeDefaults/header/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/header/selectedInnerColor",property:"border-bottom-color"}];return a},Rl:function(){var a=this._super();a["DvtTreemapBundle.COLOR"]=this.vc("labelColor");a["DvtTreemapBundle.SIZE"]=this.vc("labelSize");return a},Li:function(a){var d=a&&a.getType?a.getType():null,c,e;if(d===DvtSelectionEvent.TYPE){d=[];a=a.getSelection();for(c=0;c<a.length;c++)e={id:a[c]},d.push(e);this.options.selectedNodes=
a;this._trigger("select",null,{items:d})}else d===DvtTreemapIsolateEvent.TYPE?(d=this.options.GC,d||(this.options.GC=[],d=this.options.GC),(a=a.getId())?(c="on",d.push(a),this.options.isolatedNode=a):(c="off",a=d.pop(),this.options.isolatedNode=0<d.length?d[d.length]:null),this._trigger("isolate",null,{item:{id:a},type:c})):this._super(a)},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getNode:function(b){var d=this.ta.getAutomation();return new a.Te(d.getNode(b))}});
a.Te=function(a){this.f=a};o_("TreemapNode",a.Te,a);a.Te.prototype.nd=function(){return this.f?this.f.color:null};a.b.g("TreemapNode.prototype.getColor",{nd:a.Te.prototype.nd});a.Te.prototype.je=function(){return this.f?this.f.label:null};a.b.g("TreemapNode.prototype.getLabel",{je:a.Te.prototype.je});a.Te.prototype.Fn=function(){return this.f?this.f.size:null};a.b.g("TreemapNode.prototype.getSize",{Fn:a.Te.prototype.Fn});a.Te.prototype.le=function(){return this.f?this.f.tooltip:null};a.b.g("TreemapNode.prototype.getTooltip",
{le:a.Te.prototype.le});a.Te.prototype.isSelected=function(){return this.f?this.f.selected:!1};a.b.g("TreemapNode.prototype.isSelected",{isSelected:a.Te.prototype.isSelected})});
//# sourceMappingURL=oj-modular.map