define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(a,f){a.va=function(b){b=b||{};this.io=b.root;this.ZS=b.childCollectionCallback;this.ql=b.parseMetadata;this.Hj=null;this.yl="none";this.Ac={};a.va.t.constructor.call(this)};o_("CollectionTreeDataSource",a.va,a);a.va.prototype.ql=function(a){return{key:a.idAttribute+"\x3d"+a.id}};a.b.oa(a.va,a.sc,"oj.CollectionTreeDataSource");a.va.prototype.Init=function(){a.va.t.Init.call(this)};a.b.g("CollectionTreeDataSource.prototype.Init",
{Init:a.va.prototype.Init});a.va.prototype.df=function(a){var d=this.Ac[a];if(d&&0<d.length)return d.length;this.Cw(a,{success:function(a){return a.length}});return-1};a.b.g("CollectionTreeDataSource.prototype.getChildCount",{df:a.va.prototype.df});a.va.prototype.Cw=function(a,d){this.Sd(a,null,{success:function(a){d.success(a.ka)},error:d.error})};a.b.g("CollectionTreeDataSource.prototype.getChildCollection",{Cw:a.va.prototype.Cw});a.va.prototype.Sd=function(a,d,c){d=d||{};var e=d.start?d.start:
0,f=d.count?d.count:-1;if(null===a)this.Dl(null,e,f,c,null);else{var h=this;this.au(this.io,a,0).done(function(d){d?(d=h.wo(d.Id),h.Dl(d,e,f,c,a)):c&&c.error&&c.error(a)})}};a.b.g("CollectionTreeDataSource.prototype.fetchChildren",{Sd:a.va.prototype.Sd});a.va.prototype.mI=function(a,d,c){var e=0;c&&c.at&&(e=c.at);a=this.sp(this,"insert",e,this.Up(d),this.CD(a));this.handleEvent("insert",a)};a.va.prototype.nI=function(a,d,c){var e=0;c&&c.index&&(e=c.index);this.XQ(a);a=this.sp(this,"delete",e,this.Up(d),
null);this.handleEvent("delete",a)};a.va.prototype.oI=function(a){var d=this.gN(a),c=null,e=null;d&&(c=d.index,e=this.Up(d.ka));a=this.sp(this,"update",c,e,this.CD(a));this.handleEvent("update",a)};a.va.prototype.$H=function(a){a=this.sp(this,"refresh",null,this.Up(a),null);this.handleEvent("refresh",a)};a.va.prototype.CD=function(b){var d=[];d.push(b.attributes);var c={};c.idAttribute=b.idAttribute;b=new a.Z(d,c);b.fetch();return b};a.va.prototype.Up=function(b){var d=[],c=null;do c=this.NN(b),null!==
c&&(c!==a.va.Ux&&d.unshift(c),b=this.hN(c));while(null!=c);return d};a.va.Ux="%!@ROOT%#@!";a.va.prototype.Kp=function(b){var d=b instanceof a.q?this.ql(b).key:b;return b?d:a.va.Ux};a.va.prototype.kz=function(a){return this.Ac[this.Kp(a)]};a.va.prototype.yE=function(b,d){d.on(a.X.v.ADD,this.mI,this);d.on(a.X.v.REMOVE,this.nI,this);d.on(a.X.v.CHANGE,this.oI,this);d.on(a.X.v.SYNC,this.$H,this);this.Ac[this.Kp(b)]=d};a.va.prototype.XQ=function(a){a=this.Kp(a);for(var d in this.Ac)if(this.Ac.hasOwnProperty(d)&&
d===a){this.Ac[a].off(null,null,this);delete this.Ac[a];break}};a.va.prototype.DP=function(a,d){for(var c=d.length,e=0;e<c;e++){var f=this.Kp(d.at(e));if(a===f)return!0}return!1};a.va.prototype.gN=function(a){for(var d in this.Ac)if(this.Ac.hasOwnProperty(d))for(var c=this.Ac[d],e=0;e<c.length;e++)if(c.at(e)===a)return{index:e,ka:c};return null};a.va.prototype.hN=function(a){for(var d in this.Ac)if(this.Ac.hasOwnProperty(d)){var c=this.Ac[d];if(this.DP(a,c))return c}return null};a.va.prototype.NN=
function(a){for(var d in this.Ac)if(this.Ac.hasOwnProperty(d)&&this.Ac[d]===a)return d;return null};a.va.prototype.wo=function(a){var d=!0,c=this.kz(a);c||(d=!1,c=this.ZS(this.io,a),null!=c&&(this.Cz(c),this.yE(a,c)));return{ka:c,iw:d}};a.va.prototype.sp=function(a,d,c,e,f){return{source:a,operation:d,index:c,parent:e,data:f}};a.va.prototype.Dl=function(a,d,c,e,f){var h=this;null===a&&((a=this.kz(null))?a={ka:a,iw:!0}:(a={ka:h.io,iw:!1},h.yE(null,this.io)));a&&h.aB(a,function(a){e.success&&e.success(h.GN(a,
f,d,c))},e.error)};a.va.prototype.GN=function(b,d,c,e){return new a.Kc(d,b,this,c,e)};a.va.prototype.vR=function(a,d){function c(a,b,d){a<b.length?b.at(a,{deferred:!0}).done(function(f){if(f){var m=g.ql(f);if(d===m.key)return e.resolve(f),e}a++;c(a,b,d)}):e.resolve(null)}var e=f.Deferred(),g=this;c(0,a,d);return e};a.va.prototype.au=function(a,d,c){var e=f.Deferred(),g=this;this.vR(a,d).done(function(f){function k(f,g){if(f<l){var h=g.wo(a.at(f));h.ka?g.aB(h,function(a){g.au(a,d,c+1).done(function(a){a?
e.resolve(a):(f++,k(f,g))})},null):(f++,k(f,g))}else e.resolve(null)}if(f)return e.resolve({Id:f,depth:c}),e;var l=a.length;k(0,g)});return e.promise()};a.va.prototype.aB=function(a,d,c){a.iw?d(a.ka):(this.Hj&&"none"!==this.Hj&&(a.ka.af=this.Hj,a.ka.yx=this.yl),0<a.ka.length?d(a.ka):a.ka.fetch({success:function(a){d(a)},error:c}))};a.va.prototype.eh=function(a,d){var c=this;null===a?this.Dl(null,0,-1,{success:function(a){a.Lx({success:function(){d.success&&d.success(a)}})}},null):this.au(this.io,
a,0).done(function(e){e&&(e=c.wo(e.Id),c.Dl(e,0,-1,{success:function(a){a.Lx({success:function(){d.success&&d.success(a)}})}},a))})};a.b.g("CollectionTreeDataSource.prototype.fetchDescendants",{eh:a.va.prototype.eh});a.va.prototype.sort=function(a,d){var c=a.key,e=a.direction,f=!1;c!==this.Hj&&(this.Hj=c,f=!0);e!==this.yl&&(this.yl=e,f=!0);if(f){"none"===this.yl&&(this.Ac={});for(var h in this.Ac)this.Ac.hasOwnProperty(h)&&this.Cz(this.Ac[h])}d&&d.success&&d.success()};a.b.g("CollectionTreeDataSource.prototype.sort",
{sort:a.va.prototype.sort});a.va.prototype.Cz=function(a){a.comparator=this.Hj;a.sortDirection="ascending"===this.yl?1:-1;a.sort()};a.va.prototype.Gn=function(){return{key:this.Hj,direction:this.yl}};a.b.g("CollectionTreeDataSource.prototype.getSortCriteria",{Gn:a.va.prototype.Gn});a.va.prototype.move=function(){a.i.fa()};a.b.g("CollectionTreeDataSource.prototype.move",{move:a.va.prototype.move});a.va.prototype.$n=function(){return"invalid"};a.b.g("CollectionTreeDataSource.prototype.moveOK",{$n:a.va.prototype.$n});
a.va.prototype.getCapability=function(a){return"sort"===a?"default":"move"===a?"none":"batchFetch"===a||"fetchDescendants"===a?"disable":null};a.b.g("CollectionTreeDataSource.prototype.getCapability",{getCapability:a.va.prototype.getCapability});a.Kc=function(a,d,c,e,f){this.ix=a;this.ka=d;this.ow=[];this.oo=c;this.start=e<d.length?e:d.length-1;this.count=-1===f?d.length:Math.min(d.length,f)};o_("CollectionNodeSet",a.Kc,a);a.Kc.prototype.Lx=function(a){this.cB(this).done(function(){a.success&&a.success()})};
a.Kc.prototype.cB=function(a){function d(f){f<e?a.eI(f,{success:function(c){null!==c?a.cB(c).done(function(){d(f+1)}):d(f+1)}}):c.resolve()}var c=f.Deferred(),e=a.Y();d(0);return c.promise()};a.Kc.prototype.eI=function(a,d){var c=this.ka.at(a);if(this.oo.ql(c).leaf)this.ow[a]=null,d.success(null);else{var e=this.oo.wo(c),c=this.oo.ql(c).key,f=this;this.oo.Dl(e,0,-1,{success:function(c){f.ow[a]=c;d.success(c)}},c)}};a.Kc.prototype.getParent=function(){return this.ix};a.b.g("CollectionNodeSet.prototype.getParent",
{getParent:a.Kc.prototype.getParent});a.Kc.prototype.Da=function(){return this.start};a.b.g("CollectionNodeSet.prototype.getStart",{Da:a.Kc.prototype.Da});a.Kc.prototype.Y=function(){return this.count};a.b.g("CollectionNodeSet.prototype.getCount",{Y:a.Kc.prototype.Y});a.Kc.prototype.getData=function(a){this.Ys(a);return this.ka.at(a).attributes};a.b.g("CollectionNodeSet.prototype.getData",{getData:a.Kc.prototype.getData});a.Kc.prototype.Ys=function(a){if(a<this.start||a>this.start+this.count)throw"Out of range";
};a.Kc.prototype.getMetadata=function(a){this.Ys(a);var d={};a=this.ka.at(a);a=this.oo.ql(a);d.key=a.key;d.leaf=a.leaf;d.depth=a.depth;return d};a.b.g("CollectionNodeSet.prototype.getMetadata",{getMetadata:a.Kc.prototype.getMetadata});a.Kc.prototype.Ed=function(a){this.Ys(a);return this.ow[a]};a.b.g("CollectionNodeSet.prototype.getChildNodeSet",{Ed:a.Kc.prototype.Ed})});
//# sourceMappingURL=oj-modular.map