/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2008, 2013, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2008, 2013, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2008, 2013, Oracle and/or its affiliates. 
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojL10n!ojtranslations/nls/localeElements","ojs/ojmessaging"],function(a,f,b){a.Ca={};o_("LocaleData",a.Ca,a);a.Ca.tx=function(b){a.Ca.Ps=b};o_("LocaleData.setBundle",a.Ca.tx,a);a.Ca.qG=function(){return a.Ca.su("firstDay")};o_("LocaleData.getFirstDayOfWeek",a.Ca.qG,a);a.Ca.RT=function(){return a.Ca.su("weekendStart")};o_("LocaleData.getWeekendStart",a.Ca.RT,a);a.Ca.QT=function(){return a.Ca.su("weekendEnd")};o_("LocaleData.getWeekendEnd",a.Ca.QT,a);a.Ca.Dw=function(b){if(null==
b||"abbreviated"!==b&&"narrow"!==b)b="wide";b=a.Ca.Jt().days["stand-alone"][b];return[b.sun,b.mon,b.tue,b.wed,b.thu,b.fri,b.sat]};o_("LocaleData.getDayNames",a.Ca.Dw,a);a.Ca.kr=function(b){if(null==b||"abbreviated"!==b&&"narrow"!==b)b="wide";b=a.Ca.Jt().months["stand-alone"][b];return[b["1"],b["2"],b["3"],b["4"],b["5"],b["6"],b["7"],b["8"],b["9"],b["10"],b["11"],b["12"]]};o_("LocaleData.getMonthNames",a.Ca.kr,a);a.Ca.YG=function(){var b=a.Ca.Jt().dateFormats["long"].toUpperCase(),d=b.indexOf("M"),
b=b.indexOf("Y");return d<b};o_("LocaleData.isMonthPriorToYear",a.Ca.YG,a);a.Ca.su=function(b){var d=a.Ca.Jg(),c=a.Ca.RN()||"001";b=d.supplemental.weekData[b];c=b[c];void 0===c&&(c=b["001"]);return c};a.Ca.Jt=function(){var b=a.Ca.Jg().main,d,c;for(c in b)if(b.hasOwnProperty(c)){d=b[c];break}return d.dates.calendars.gregorian};a.Ca.RN=function(){var b=a.ha.De();if(b&&(b=b.toUpperCase().split(/-|_/),2<=b.length)){var d=b[1];if(4==d.length){if(3<=b.length)return b[2]}else return d}return null};a.Ca.Jg=
function(){var d=a.Ca.Ps;return d?d:a.Vl()?(a.i.assert(void 0!==b,"LocaleElements module must be loaded"),b):{}};a.Ca.rK=function(a){b=a};a.ba={};o_("Validation",a.ba,a);a.ba.kt={};a.ba.bw={};a.ba.EA={};a.ba.HA={};a.ba.Io={converter:{name:"oj.ConverterFactory",type:a.Pf},validator:{name:"oj.ValidatorFactory",type:a.kc}};a.ba.ji=function(b,d){var c;b&&!d?c=a.ba.Op(b,a.ba.kt):b&&d&&(c=a.ba.Mk(b,d,a.ba.kt,a.ba.Io.converter));return c};o_("Validation.converterFactory",a.ba.ji,a);a.ba.wh=function(b,d){var c;
b&&!d?c=a.ba.Op(b,a.ba.bw):b&&d&&(c=a.ba.Mk(b,d,a.ba.bw,a.ba.Io.validator));return c};o_("Validation.validatorFactory",a.ba.wh,a);a.ba.FT=function(b){return a.ba.Op(b,a.ba.EA)};o_("Validation.getDefaultConverterFactory",a.ba.FT,a);a.ba.GT=function(b){return a.ba.Op(b,a.ba.HA)};o_("Validation.getDefaultValidatorFactory",a.ba.GT,a);a.ba.nz=function(b,d){var c=a.ba.Io.converter;a.ba.Mk(b,d,a.ba.EA,c);a.ba.Mk(b,d,a.ba.kt,c)};a.ba.Yj=function(b,d){var c=a.ba.Io.validator;a.ba.Mk(b,d,a.ba.HA,c);a.ba.Mk(b,
d,a.ba.bw,c)};a.ba.zM=function(b,d,c){if(d&&!a.ba.IQ(b,d))throw Error("Factory instance does not implement the methods expected by the factory of type "+c);};a.ba.Op=function(b,d){a.i.vn(b);var c=null;b&&(b=b.toLowerCase(),c=(d[b]||{}).instance||null);return c};a.ba.IQ=function(b,d){var c=!0,e;a.i.Pd(b);a.i.Pd(d);for(e in d)if(d.hasOwnProperty(e)&&"function"===typeof d[e]&&!b[e]&&"function"!==typeof b[e]){c=!1;break}return c};a.ba.Mk=function(b,d,c,e){a.i.vn(b);a.i.Pd(d);if(b){var f={};f.instance=
d;a.ba.zM(d,e.type,e.name);c[b.toLowerCase()]=f}};a.Pf={CONVERTER_TYPE_NUMBER:"number",CONVERTER_TYPE_DATETIME:"datetime",createConverter:function(){}};o_("ConverterFactory",a.Pf,a);a.kc={VALIDATOR_TYPE_REQUIRED:"required",VALIDATOR_TYPE_REGEXP:"regexp",VALIDATOR_TYPE_NUMBERRANGE:"numberRange",VALIDATOR_TYPE_LENGTH:"length",VALIDATOR_TYPE_DATETIMERANGE:"dateTimeRange",VALIDATOR_TYPE_DATERESTRICTION:"dateRestriction",createValidator:function(){}};o_("ValidatorFactory",a.kc,a);a.Lc=function(b){this.Init(b)};
o_("Converter",a.Lc,a);a.b.oa(a.Lc,a.b,"oj.Converter");a.Lc.prototype.Init=function(b){a.Lc.t.Init.call(this);this.Ra=b};a.b.g("Converter.prototype.Init",{Init:a.Lc.prototype.Init});a.Lc.prototype.Qb=function(){a.i.fa();return null};a.b.g("Converter.prototype.getHint",{Qb:a.Lc.prototype.Qb});a.Lc.prototype.gf=function(){return this.Ra||{}};a.b.g("Converter.prototype.getOptions",{gf:a.Lc.prototype.gf});a.Lc.prototype.parse=function(){a.i.fa();return null};a.b.g("Converter.prototype.parse",{parse:a.Lc.prototype.parse});
a.Lc.prototype.format=function(){a.i.fa();return null};a.b.g("Converter.prototype.format",{format:a.Lc.prototype.format});a.Lc.prototype.resolvedOptions=function(){var b={};f.extend(b,this.Ra);return b};a.b.g("Converter.prototype.resolvedOptions",{resolvedOptions:a.Lc.prototype.resolvedOptions});a.sd=function(b,d){var c=new a.N(b,d,a.N.kb.ERROR);this.Init(c)};o_("ConverterError",a.sd,a);a.sd.prototype=Error();a.sd.prototype.Init=function(b){var a=b.detail,d=b.summary;this.Vu=b;this.name="Converter Error";
this.message=a||d};a.b.g("ConverterError.prototype.Init",{Init:a.sd.prototype.Init});a.sd.prototype.il=function(){return this.Vu};a.b.g("ConverterError.prototype.getMessage",{il:a.sd.prototype.il});a.Pe=function(){this.Init()};o_("NumberConverter",a.Pe,a);a.b.oa(a.Pe,a.Lc,"oj.NumberConverter");a.Pe.prototype.Init=function(b){a.Pe.t.Init.call(this,b)};a.b.g("NumberConverter.prototype.Init",{Init:a.Pe.prototype.Init});a.Pe.prototype.format=function(b){return a.Pe.t.format.call(this,b)};a.b.g("NumberConverter.prototype.format",
{format:a.Pe.prototype.format});a.Pe.prototype.parse=function(b){return a.Pe.t.parse.call(this,b)};a.b.g("NumberConverter.prototype.parse",{parse:a.Pe.prototype.parse});a.rb=function(b){this.Init(b)};o_("DateTimeConverter",a.rb,a);a.b.oa(a.rb,a.Lc,"oj.DateTimeConverter");a.rb.prototype.Init=function(b){a.rb.t.Init.call(this,b)};a.b.g("DateTimeConverter.prototype.Init",{Init:a.rb.prototype.Init});a.rb.prototype.format=function(b){return a.rb.t.format.call(this,b)};a.b.g("DateTimeConverter.prototype.format",
{format:a.rb.prototype.format});a.rb.prototype.Qn=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isHourInDaySet",{Qn:a.rb.prototype.Qn});a.rb.prototype.Pn=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isHourInAMPMSet",{Pn:a.rb.prototype.Pn});a.rb.prototype.Sn=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isMinuteSet",{Sn:a.rb.prototype.Sn});a.rb.prototype.Un=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isSecondSet",{Un:a.rb.prototype.Un});a.rb.prototype.Rn=
function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isMilliSecondSet",{Rn:a.rb.prototype.Rn});a.rb.prototype.Vn=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isYearSet",{Vn:a.rb.prototype.Vn});a.rb.prototype.Tn=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isMonthSet",{Tn:a.rb.prototype.Tn});a.rb.prototype.On=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isDaySet",{On:a.rb.prototype.On});a.rb.prototype.Nn=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isDayNameSet",
{Nn:a.rb.prototype.Nn});a.rb.prototype.parse=function(b){return a.rb.t.parse.call(this,b)};a.b.g("DateTimeConverter.prototype.parse",{parse:a.rb.prototype.parse});a.Ld=function(){this.Init()};o_("Validator",a.Ld,a);a.b.oa(a.Ld,a.b,"oj.Validator");a.Ld.prototype.Init=function(){a.Ld.t.Init.call(this)};a.b.g("Validator.prototype.Init",{Init:a.Ld.prototype.Init});a.Ld.prototype.validate=function(){a.i.fa()};a.b.g("Validator.prototype.validate",{validate:a.Ld.prototype.validate});a.Ld.prototype.Qb=function(){a.i.fa()};
a.b.g("Validator.prototype.getHint",{Qb:a.Ld.prototype.Qb});a.te=function(b,d){var c=new a.N(b,d,a.N.kb.ERROR);this.Init(c)};o_("ValidatorError",a.te,a);a.te.prototype=Error();a.te.prototype.Init=function(b){var a=b.detail,d=b.summary;this.Vu=b;this.name="Validator Error";this.message=a||d};a.b.g("ValidatorError.prototype.Init",{Init:a.te.prototype.Init});a.te.prototype.il=function(){return this.Vu};a.b.g("ValidatorError.prototype.getMessage",{il:a.te.prototype.il});var d;d=function(){function b(){return{format:function(b,
a,d,c){if("number"===typeof b)b=new Date(b);else if("string"===typeof b){if(""===e.trim(b))return null;b=m(b,a,d,c);b=b.value}if("Invalid Date"===b.toString())return"Invalid Date";if(2>=arguments.length||void 0===d)d={year:"numeric",month:"numeric",day:"numeric"};var g=f(b,a,d),h=e.wj(c,"nu");void 0===e.tg[h]&&(h="latn");if("latn"!==h){var p,l=[];for(p=0;p<g.length;p++)"0"<=g[p]&&"9">=g[p]?l.push(e.tg[h][g[p]]):l.push(g[p]);return l.join("")}return g},hr:function(b,a,d){return q(b,a,d)},parse:function(b,
a,d,c){return m(b,a,d,c)},resolvedOptions:function(b,a,c){if(3>arguments.length||void 0===c)c=e.hl(b);if(2>arguments.length||void 0===a)a={year:"numeric",month:"numeric",day:"numeric"};var g=!1,h;h=e.wj(c,"nu");void 0===e.tg[h]&&(h="latn");if(void 0!==a&&void 0!==a.pattern)return h=p(c,h,a.pattern),h.pattern=a.pattern,h;if(void 0!==a){h={locale:c,numberingSystem:h,calendar:"gregorian"};var f=0;for(f in a)f++;if(0==f)return h.year="numeric",h.month="numeric",h.day="numeric",h;var f=e.fh(a,"OraDateTimeConverter.resolvedOptions"),
l=f("year","string",["2-digit","numeric"]);void 0!==l&&(h.year=l,g=!0);l=f("era","string",["narrow","short","long"]);void 0!==l&&(h.era=l,g=!0);l=f("month","string",["2-digit","numeric","narrow","short","long"]);void 0!==l&&(h.month=l,g=!0);l=f("day","string",["2-digit","numeric"]);void 0!==l&&(h.day=l,g=!0);l=f("weekday","string",["narrow","short","long"]);void 0!==l&&(h.weekday=l,g=!0);l=f("hour","string",["2-digit","numeric"]);void 0!==l&&(h.hour=l,g=!0,l=f("hour12","boolean",[!0,!1]),void 0===
l&&(l=u(b)),h.hour12=l);l=f("minute","string",["2-digit","numeric"]);void 0!==l&&(h.minute=l,g=!0);l=f("second","string",["2-digit","numeric"]);void 0!==l&&(h.second=l,g=!0);h["two-digit-year-start"]=s(a);if(!g){g=f("formatType","string",["date","time","datetime"],"date");l=f("dateFormat","string",["short","medium","long","full"],"short");f=f("timeFormat","string",["short","medium","long","full"],"short");h.formatType=g;if("datetime"===g||"date"===g)h.dateFormat=l;if("datetime"===g||"time"===g)h.timeFormat=
f;return h}h.patternFromOptions=d(a,b,"OraDateTimeConverter.resolvedOptions");return h}g=d({year:"numeric",month:"numeric",day:"numeric"},b,"OraDateTimeConverter.resolvedOptions");return{calendar:"gregorian",locale:c,numberingSystem:h,year:"numeric",month:"numeric",day:"numeric",patternFromOptions:g}}}}var a,d,c,f,m,q,t,p,r,s,u,v,w,x={},E,A,Q,B,z,F,M,y,J,I,D,G,N,K,C,X,O,S,T,P,ca,R,Y,L,aa,V,da,W,ba,ea,ma,H,ha,na,fa,ga,oa,ia,ja,ka=/(\d{1,4})\D+?(\d{1,4})/g,la=/(\d{1,4})\D+?(\d{1,4})\D+?(\d{1,4})/g,
pa=/^[M][^M]|[^M]M[^M]/g,va=/^[L][^L]|[^L]L[^L]/g,qa=/^[d][^d]|[^d]d[^d]/g,ra=/(?:^|[^h])h[^h]|[^H]H[^H]|[^k]k[^k]|[^K]K[^K]/,sa=/(\d{1,2})(?:\D+?(\d{1,2}))?(?:\D+?(\d{1,2}))?(?:\D+?(\d{1,3}))?/g,ta=/h|H|K|k/g,ua=/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,Z=/ccccc|cccc|ccc|cc|c|EEEEE|EEEE|EEE|EE|E|dd|d|MMMMM|MMMM|MMM|MM|M|LLLLL|LLLL|LLL|LL|L|yyyy|yy|y|hh|h|HH|H|KK|K|kk|k|mm|m|ss|s|aa|a|SS|S|zzzz|zzz|zz|z|GGGGG|GGGG|GGG|GG|G/g,wa={0:"sun",1:"mon",2:"tue",3:"wed",4:"thu",5:"fri",6:"sat"},U={MMM:{token:"months",
style:"format",mLen:"abbreviated",matchIndex:0,key:"month",value:"short",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},MMMM:{token:"months",style:"format",mLen:"wide",matchIndex:0,key:"month",value:"long",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},MMMMM:{token:"months",style:"format",mLen:"narrow",matchIndex:0,key:"month",value:"narrow",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLL:{token:"months",style:"stand-alone",mLen:"abbreviated",matchIndex:1,key:"month",value:"short",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},
LLLL:{token:"months",style:"stand-alone",mLen:"wide",matchIndex:1,key:"month",value:"long",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLLLL:{token:"months",style:"stand-alone",mLen:"narrow",matchIndex:1,key:"month",value:"narrow",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},E:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},EE:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},
EEE:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},EEEE:{token:"days",style:"format",dLen:"wide",matchIndex:0,key:"weekday",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},EEEEE:{token:"days",style:"format",dLen:"narrow",matchIndex:0,key:"weekday",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},c:{token:"days",style:"stand-alone",dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},cc:{token:"days",style:"stand-alone",
dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},ccc:{token:"days",style:"stand-alone",dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},cccc:{token:"days",style:"stand-alone",dLen:"wide",matchIndex:1,key:"weekday",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},ccccc:{token:"days",style:"stand-alone",dLen:"narrow",matchIndex:1,key:"weekday",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},h:{token:"time",timePart:"hour",start1:0,
end1:11,start2:1,end2:12,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},hh:{token:"time",timePart:"hour",start1:0,end1:11,start2:1,end2:12,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},K:{token:"time",timePart:"hour",start1:0,end1:11,start2:0,end2:11,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},KK:{token:"time",timePart:"hour",start1:0,end1:11,start2:0,end2:11,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},H:{token:"time",timePart:"hour",start1:0,end1:23,start2:0,end2:23,key:"hour",value:"numeric",
regExp:"(\\d\\d?)"},HH:{token:"time",timePart:"hour",start1:0,end1:23,start2:0,end2:23,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},k:{token:"time",timePart:"hour",start1:0,end1:23,start2:1,end2:24,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},kk:{token:"time",timePart:"hour",start1:0,end1:23,start2:1,end2:24,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},m:{token:"time",timePart:"minute",start1:0,end1:59,start2:0,end2:59,key:"minute",value:"numeric",regExp:"(\\d\\d?)"},mm:{token:"time",timePart:"minute",
start1:0,end1:59,start2:0,end2:59,key:"minute",value:"2-digit",regExp:"(\\d\\d?)"},s:{token:"time",timePart:"second",start1:0,end1:59,start2:0,end2:59,key:"second",value:"numeric",regExp:"(\\d\\d?)"},ss:{token:"time",timePart:"second",start1:0,end1:59,start2:0,end2:59,key:"second",value:"2-digit",regExp:"(\\d\\d?)"},S:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},SS:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,
end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},d:{token:"dayOfMonth",key:"day",value:"numeric",getPartIdx:2,regExp:"(\\d\\d?)"},dd:{token:"dayOfMonth",key:"day",value:"2-digit",getPartIdx:2,regExp:"(\\d\\d?)"},M:{token:"monthIndex",key:"month",value:"numeric",getPartIdx:1,regExp:"(\\d\\d?)"},MM:{token:"monthIndex",key:"month",value:"2-digit",getPartIdx:1,regExp:"(\\d\\d?)"},L:{token:"monthIndex",key:"month",value:"numeric",getPartIdx:1,regExp:"(\\d\\d?)"},LL:{token:"monthIndex",key:"month",
value:"2-digit",getPartIdx:1,regExp:"(\\d\\d?)"},y:{token:"year",key:"year",value:"numeric",regExp:"(\\d{1,4})"},yy:{token:"year",key:"year",value:"2-digit",regExp:"(\\d\\d?)"},yyyy:{token:"year",key:"year",value:"numeric",regExp:"(\\d{1,4})"},a:{token:"ampm",key:"hour12",value:!0,regExp:"(\\D*)"},z:{token:"tz",key:"timeZoneName",value:"short",regExp:"([+-]?\\d{1,4})"},zz:{token:"tz",key:"timeZoneName",value:"short",regExp:"([+-]?\\d{1,4})"},zzz:{token:"tz",key:"timeZoneName",value:"short",regExp:"([+-]?\\d{1,4})"},
zzzz:{token:"tz",key:"timeZoneName",value:"long",regExp:"([+-]?\\d{1,4})"},G:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GG:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GGG:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GGGG:{token:"era",key:"era",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},GGGGG:{token:"era",key:"era",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},"/":{token:"slash",regExp:"(\\/)"}};s=function(b){b=b["two-digit-year-start"];
if(void 0===b||isNaN(b))b=1950;return b=parseInt(b,10)};u=function(b){var a=e.Ar(e.hl(b)).region||"001";return"h"===b.supplemental.prefferedHours[a]};E=function(b){return 0==b%400?!0:0==b%100?!1:0==b%4?!0:!1};A=function(b,a){switch(a){case 0:case 2:case 4:case 6:case 7:case 9:case 11:return 31;case 1:return E(b)?29:28;default:return 30}};w=function(b,a,d){a=e.Vd(a);var c=e.fh(b,d);b=c("formatType","string",["date","time","datetime"],"date");d=c("dateFormat","string",["short","medium","long","full"],
"short");var c=c("timeFormat","string",["short","medium","long","full"],"short"),g=a.dates.calendars.gregorian;a=g.dateFormats;var g=g.timeFormats,h,p,f;switch(d){case "full":h=a.full;break;case "long":h=a["long"];break;case "medium":h=a.medium;break;case "short":h=a["short"]}switch(c){case "full":p=g.full;break;case "long":p=g["long"];break;case "medium":p=g.medium;break;case "short":p=g["short"]}void 0===h||"datetime"!==b&&"date"!==b||(f=h);void 0===p||"datetime"!==b&&"time"!==b||(f=f?f+" "+p:p);
return f};a=function(b,a){for(var d=0,c=!1,e=0,g=b.length;e<g;e++){var h=b.charAt(e);switch(h){case "'":c?a.push("'"):d++;c=!1;break;case "\\":c&&a.push("\\");c=!c;break;default:a.push(h),c=!1}}return d};t=function(b,a,d){var c;c=void 0!==a.year||void 0!==a.month||void 0!==a.weekday||void 0!==a.day;a=void 0!==a.hour||void 0!==a.minute||void 0!==a.second;c=c&&a?"MM/dd/yy hh:mm:ss a":c?"MM/dd/yy":"hh:mm:ss a";d=new SyntaxError("Unexpected character(s) "+d+' encountered in the pattern "'+b+' An example of a valid pattern is "'+
c+'".');d.errorInfo={errorCode:"optionValueInvalid",parameterMap:{propertyName:"pattern",propertyValue:b,"propertyValueHint ":c}};throw d;};M=function(b,a,d,c){a=e.Vd(a).dates.calendars.gregorian.dateTimeFormats.availableFormats;d=d?["era","year","month","weekday","day"]:["weekday","hour","minute","second"];var g=-Infinity,h=void 0,p,f;for(f in a){var l={};l.pattern=a[f];for(var k=0;null!==(p=Z.exec(f));)p=p[0],("h"!==p&&"hh"!==p||c)&&("H"!==p&&"HH"!==p||!c)&&void 0!==U[p]&&(l[U[p].key]=U[p].value);
for(var m in d){p=b[d[m]];var r=l[d[m]];if(void 0===p&&void 0!==r)k-=20;else if(void 0!==p&&void 0===r)k-=120;else if(void 0!==p&&void 0!==r){var n={"2-digit":0,numeric:1,narrow:2,"short":3,"long":4};p=Math.max(Math.min(n[r]-n[p],2),-2);2===p?k-=6:1===p?k-=3:-1===p?k-=6:-2===p&&(k-=8)}}k>g&&(g=k,h=l)}return void 0!==h?h.pattern:null};B=function(b,a,d){var c="",g="",h={},p={};b=e.fh(b,d);d=b("era","string",["narrow","short","long"]);c+=y(h,"era",d,{narrow:"GGGGG","short":"GGG","long":"GGGG"});d=b("year",
"string",["2-digit","numeric"]);c+=y(h,"year",d,{"2-digit":"yy",numeric:"y"});d=b("month","string",["2-digit","numeric","narrow","short","long"]);c+=y(h,"month",d,{"2-digit":"MM",numeric:"M",narrow:"MMMMM","short":"MMM","long":"MMMM"});d=b("weekday","string",["narrow","short","long"]);c+=y(h,"weekday",d,{narrow:"EEEEE","short":"E","long":"EEEE"});d=b("day","string",["2-digit","numeric"]);var c=c+y(h,"day",d,{"2-digit":"dd",numeric:"d"}),f=b("hour12","boolean",[!0,!1]);void 0===f&&(f=u(a));d=b("hour",
"string",["2-digit","numeric"]);g=!0===f?g+y(p,"hour",d,{"2-digit":"hh",numeric:"h"}):g+y(p,"hour",d,{"2-digit":"HH",numeric:"H"});d=b("minute","string",["2-digit","numeric"]);g+=y(p,"minute",d,{"2-digit":"mm",numeric:"m"});d=b("second","string",["2-digit","numeric"]);g+=y(p,"second",d,{"2-digit":"ss",numeric:"s"});return[c,g,h,p]};y=function(b,a,d,c){return void 0!==d?(b[a]=d,c[d]):""};z=function(b,a,d){var c=b;a=e.fh(a,d);d=a("year","string",["2-digit","numeric"]);var g={"2-digit":"yy",numeric:"yyyy"};
void 0!==d&&(c=c.replace(/y{1,4}/,g[d]));d=a("month","string",["2-digit","numeric","narrow","short","long"]);if(void 0!==d){var g={"2-digit":"MM",numeric:"M",narrow:"MMMMM","short":"MMM","long":"MMMM"},h={"2-digit":"LL",numeric:"L",narrow:"LLLLL","short":"LLL","long":"LLLL"};void 0!==g[d]&&2<g[d].length?(c=c.replace(/M{3,5}/,g[d]),c=c.replace(/L{3,5}/,h[d])):"2-digit"===d&&(pa.lastIndex=0,(d=pa.test(b))&&(c=c.replace("M","MM")),(d=va.test(b))&&(c=c.replace("L","LL")))}d=a("weekday","string",["narrow",
"short","long"]);void 0!==d&&(c=c.replace(/E{1,5}/,{narrow:"EEEEE","short":"EEE","long":"EEEE"}[d]),c=c.replace(/c{1,5}/,{narrow:"ccccc","short":"ccc","long":"cccc"}[d]));d=a("day","string",["2-digit","numeric"]);void 0!==d&&"2-digit"===d&&(qa.lastIndex=0,(d=qa.test(b))&&(c=c.replace("d","dd")));return c};F=function(b,a,d){var c=b;"2-digit"===e.fh(a,d)("hour","string",["2-digit","numeric"])&&(ra.lastIndex=0,a=ra.exec(b),null!==a&&(c=a[0].length-2,c=b.replace(a[0][c],a[0][c]+a[0][c])));return c};d=
function(b,a,d){var c=e.Vd(a),g=e.hl(a),h=e.fh(b,d),p=h("formatMatcher","string",["basic","munger"],"munger"),f=0;for(f in b)f++;0==f&&(b={year:"numeric",month:"numeric",day:"numeric"});f=B(b,a,d);if(void 0!==x[g]&&void 0!==x[g].dates.calendars.gregorian.dateTimeFormats[f[0]+f[1]])return x[g].dates.calendars.gregorian.dateTimeFormats[f[0]+f[1]];if(""===f[0]&&""===f[1])return w(b,a,d);var l=c.dates.calendars.gregorian.dateTimeFormats.availableFormats,c=l[f[0]],h=h("hour12","boolean",[!0,!1]);void 0===
h&&(h=u(a));void 0===c&&""!==f[0]&&(c=M(f[2],a,!0,h),c=null!==c?"basic"===p?c:z(c,b,d):f[0]);l=l[f[1]];void 0===l&&""!==f[1]&&(a=M(f[3],a,!1,h),l=null!==a?"basic"===p?a:F(a,b,d):f[1]);b=c||"";void 0!==l&&(b=""!==b?b+(" "+l):l);void 0===x[g]&&(x[g]={},x[g].dates={},x[g].dates.calendars={},x[g].dates.calendars.gregorian={},x[g].dates.calendars.gregorian.dateTimeFormats={});return x[g].dates.calendars.gregorian.dateTimeFormats[f[0]+f[1]]=b};f=function(b,c,g){function p(b,a){switch(a){case 0:return b.getFullYear();
case 1:return b.getMonth()+1;case 2:return b.getDate();case 3:return wa[b.getDay()]}}function f(b,a,d,c){a=p(a,d);b.push(1<c?e.fo(a,c):a)}function l(b,a,d,c,g){var h;switch(c.timePart){case "hour":h=11===c.end1?a.getHours()%12:a.getHours();"h"===g||"hh"===g?0===h&&(h=12):"k"!==g&&"kk"!==g||0!==h||(h=24);break;case "minute":h=a.getMinutes();break;case "second":h=a.getSeconds();break;case "millisec":h=a.getMilliseconds()}b.push(1<d?e.fo(h,d):h)}var m=e.Vd(c),r=g.pattern||d(g,c,"OraDateTimeConverter.format");
c=[];for(var n,s=0,m=m.dates.calendars.gregorian;;){n=Z.lastIndex;var q=Z.exec(r);n=r.slice(n,q?q.index:r.length);s+=a(n,c);if(!q)break;if(s%2)c.push(q[0]);else{n=q[0];var q=n.length,u=U[n];switch(u.token){case "days":n=m[u.token][u.style][u.dLen];c.push(n[p(b,3)]);break;case "months":n=m[u.token][u.style][u.mLen];c.push(n[p(b,1)]);break;case "dayOfMonth":case "monthIndex":c.push(f(c,b,u.getPartIdx,q));break;case "year":n=b.getFullYear();2==q&&(n%=100);c.push(e.fo(n,q));break;case "time":l(c,b,q,
u,n);break;case "ampm":n=12>b.getHours()?m.dayPeriods.format.wide.am:m.dayPeriods.format.wide.pm;c.push(n);break;case "tz":n=b.getTimezoneOffset();c.push((0>=n?"+":"-")+e.fo(Math.floor(Math.abs(n/60)),2)+e.fo(Math.floor(Math.abs(n%60)),2));break;case "era":n=m.eras.eraAbbr;c.push(n["1"]);break;case "slash":c.push("/");break;default:t(r,g,n)}}}return c.join("")};D=function(b,a){return b.getFullYear()==a.getFullYear()};G=function(b,a){return 1==a.getFullYear()-b.getFullYear()};N=function(b,a){return G(a,
b)};K=function(b,a){return D(b,a)&&b.getMonth()===a.getMonth()};C=function(b,a){return D(b,a)?1==a.getMonth()-b.getMonth():G(b,a)?11==b.getMonth()&&0==a.getMonth():!1};X=function(b,a){return C(a,b)};J=function(b,a){var d=b.getDate(),c=a.getDate();C(b,a)&&(c+=A(b.getFullYear,b.getMonth()));return c-d};I=function(b,a){var d=e.Ar(e.hl(b)).region||"001",d=a-b.supplemental.weekData.firstDay[d];0>d&&(d+=7);return d};O=function(b,a,d){if(a>d){var c=a;a=d;d=c}if(!K(a,d)&&!C(a,d))return!1;b=J(a,d)+I(b,a.getDay());
return 0<=b&&6>=b};S=function(b,a,d){if(!K(a,d)&&!C(a,d))return!1;b=J(a,d)+I(b,a.getDay());return 7<=b&&13>=b};T=function(b,a,d){return S(b,d,a)};P=function(b,a){return D(b,a)&&K(b,a)&&b.getDate()===a.getDate()};ca=function(b,a){return K(b,a)||C(b,a)?1===J(b,a):!1};R=function(b,a){return ca(a,b)};q=function(b,a,d){var c=e.Vd(a).dates.fields;d=e.fh(d,"OraDateTimeConverter.formatRelative");d("formatUsing","string",["displayName"]);d=d("dateField","string",["day","week","month","year"]);var g=new Date;
switch(d){case "day":if(P(g,b))return c.day["relative-type-0"];if(ca(g,b))return c.day["relative-type-1"];if(R(g,b))return c.day["relative-type--1"];break;case "week":if(O(a,g,b))return c.week["relative-type-0"];if(S(a,g,b))return c.week["relative-type-1"];if(T(a,g,b))return c.week["relative-type--1"];break;case "month":if(K(g,b))return c.month["relative-type-0"];if(C(g,b))return c.month["relative-type-1"];if(X(g,b))return c.month["relative-type--1"];break;case "year":if(D(g,b))return c.year["relative-type-0"];
if(G(g,b))return c.year["relative-type-1"];if(N(g,b))return c.year["relative-type--1"]}return null};ga=function(b,a){var d;d=Error("The weekday "+b+" does not match the date "+a);d.errorInfo={errorCode:"dateToWeekdayMismatch",parameterMap:{weekday:b,date:a}};throw d;};fa=function(b,a,d){var c;2===d?(c='The value "'+b+'" does not match the expected date-time format "'+a+'"',d="datetimeFormatMismatch"):0===d?(c='The value "'+b+'" does not match the expected date format "'+a+'"',d="dateFormatMismatch"):
(c='The value "'+b+'" does not match the expected time format "'+a+'"',d="timeFormatMismatch");c=Error(c);c.errorInfo={errorCode:d,parameterMap:{value:b,format:a}};throw c;};Y=function(b,a){100>a&&(a+=100*Math.floor(b/100)+(a<b%100?100:0));return a};ha=function(b,a){var d={sun:0,mon:1,tue:2,wed:3,thu:4,fri:5,sat:6},c;for(c in b)if(e.trim(e.$d(b[c]))==e.trim(a))return d[c];return-1};na=function(b,a){for(var d in b)if(e.trim(e.$d(b[d]))===e.trim(a))return d-1;return-1};ba=function(b,a,d){var c=e.Vd(b),
g;b=c.dates.calendars.gregorian.days.format;c=c.dates.calendars.gregorian.days["stand-alone"];switch(d){case 0:g=[b.abbreviated,b.wide];break;case 1:g=[c.abbreviated,c.wide]}a=e.$d(a);d=ha(g[0],a);-1===d&&(d=ha(g[1],a));return d};ea=function(b,a,d){var c=-1,g=e.Vd(b);b=g.dates.calendars.gregorian.months.format;g=g.dates.calendars.gregorian.months["stand-alone"];switch(d){case 0:d=[b.wide,b.abbreviated];break;case 1:d=[g.wide,g.abbreviated];break;case 2:d=[b.wide,b.abbreviated,g.wide,g.abbreviated];
break;default:return-1}a=e.$d(a);for(var h in d)if(c=na(d[h],a),-1!==c)break;return c};ma=function(b,d){for(var c=b.replace(ua,"\\\\$1"),e=["^"],g=[],p=0,f=0,l;null!==(l=Z.exec(c));){var k=c.slice(p,l.index),p=Z.lastIndex,f=f+a(k,e);if(f%2)e.push(l[0]);else{var k=l[0],n;void 0!==U[k]?n=U[k].regExp:t(b,d,k);n&&e.push(n);g.push(l[0])}}a(c.slice(p),e);e.push("$");c={regExp:e.join("").replace(/\s+/g,"\\s+"),groups:g};return{}[b]=c};H=function(b,a,d,c,e,g,h){if(a<d||a>c)throw a=new RangeError(e+" is out of range.  Enter a value between "+
g+" and "+h+" for "+b),a.errorInfo={errorCode:"datetimeOutOfRange",parameterMap:{value:e,minValue:g,maxValue:h,propertyName:b}},a;};L=function(b,a){for(var d in b)for(var c in b[d])if(c===a)return parseInt(d,10);return 0};W=function(b,a,d,c){var g=e.Vd(c).dates.calendars.gregorian.dayPeriods.format.wide.pm,h=c=sa.lastIndex=0,p=0,f=0,l=sa.exec(a);null===l&&fa(a,d,1);void 0!==l[1]&&(c=parseInt(l[1],10));void 0!==l[2]&&(h=parseInt(l[2],10));void 0!==l[3]&&(p=parseInt(l[3],10));void 0!==l[4]&&(f=parseInt(l[4],
10));ta.lastIndex=0;l=ta.exec(d);switch(l[0]){case "h":12===c&&(c=0);H("hour",c,0,11,c,1,12);a=e.$d(a).indexOf(e.$d(g));-1!==a&&12>c&&(c+=12);break;case "K":H("hour",c,0,11,c,0,11);a=e.$d(a).indexOf(e.$d(g));-1!==a&&12>c&&(c+=12);break;case "H":H("hour",c,0,23,c,0,23);break;case "k":24===c&&(c=0),H("hour",c,0,23,c,1,24)}H("minute",h,0,59,h,0,59);H("second",p,0,59,p,0,59);H("millisec",f,0,999,f,0,999);b.setHours(c,h,p,f)};ja=function(b,a){var d=e.Vd(a),c=d.dates.calendars.gregorian.days.format,d=d.dates.calendars.gregorian.days["stand-alone"],
c=[c.wide,c.abbreviated,d.wide,d.abbreviated],d=!1,g,h,p;for(h in c){for(p in c[h])if(g=c[h][p],(new RegExp(g+"\\b","i")).test(b)){d=!0;break}if(d)break;g=null}return g};V=function(b,a,d,c,e){la.lastIndex=0;var g=la.exec(b);null===g&&fa(b,a,0);var h=[{y:a.indexOf("y")},{M:a.indexOf("M")},{d:a.indexOf("d")}];h.sort(function(b,a){for(var d in b)break;for(var c in a)break;return b[d]-a[c]});var p,f,l,k,n,m,r=!1,q=!1;for(m=1;3>=m;m++){var u=g[m];if(2<u.length||31<u)p=u,r=!0,k=m-1}r||(k=L(h,"y"),p=g[L(h,
"y")+1]);for(m=0;3>m;m++)if(m!==k&&12<g[m+1]){l=g[m+1];q=!0;n=m;break}if(q){for(m=0;3>m;m++)if(m!==n&&m!==k){f=g[m+1];break}void 0===f&&(f=g[L(h,"M")+1])}else k===L(h,"d")?(l=g[L(h,"y")+1],f=g[L(h,"M")+1]):k===L(h,"M")?(l=g[L(h,"d")+1],f=g[L(h,"y")+1]):(l=g[L(h,"d")+1],f=g[L(h,"M")+1]);f-=1;g=A(p,f);H("month",f,0,11,f+1,1,12);H("day",l,1,g,l,1,g);p=Y(s(d),parseInt(p,10));H("year",p,0,9999,p,0,9999);d=new Date(p,f,l);p=ja(b,c);null!=p&&(f=ba(c,p,0),d.getDay()!==f&&ga(p,d.getDate()));d={value:d,warning:"lenient parsing was used"};
e&&(b=b.substr(la.lastIndex),0===b.length?d.value.setHours(0,0,0,0):W(d.value,b,a,c));return d};da=function(b,a,d,c,g){var h=b;b=e.$d(b);var p=e.Vd(c),f=p.dates.calendars.gregorian.months.format,p=p.dates.calendars.gregorian.months["stand-alone"],f=[f.wide,f.abbreviated,p.wide,p.abbreviated],p=!1,l,k,m,n;for(k in f){l=[];for(m in f[k])n=e.$d(f[k][m]),l.push({idx:m,name:n});l.sort(function(b,a){return a.idx-b.idx});for(m in l)if(n=l[m].name,-1!=b.indexOf(n)){p=!0;b=b.replace(n,"");break}if(p)break}if(!p)return V(h,
a,d,c,g);m=ea(c,n,2);H("month",m,0,11,m,1,12);n=ja(h,c);k=new RegExp(n+"\\W","i");null!==n&&(b=b.replace(k,""));ka.lastIndex=0;f=ka.exec(b);null===f&&fa(h,a,0);h=[{y:a.indexOf("y")},{d:a.indexOf("d")}];h.sort(function(b,a){for(var d in b)break;for(var c in a)break;return b[d]-a[c]});var r,q,p=!1;for(k=1;2>=k;k++)if(l=f[k],2<l.length||31<l)r=l,p=!0,q=k-1;p||(q=L(h,"y"),r=f[L(h,"y")+1]);q=q===L(h,"d")?f[L(h,"y")+1]:f[L(h,"d")+1];r=Y(s(d),parseInt(r,10));H("year",r,0,9999,r,0,9999);d=new Date(r,m,q);
null!=n&&(k=ba(c,n,0),d.getDay()!==k&&ga(n,d.getDate()));r=A(r,m);H("day",q,1,r,q,1,r);r={value:d,warning:"lenient parsing was used"};g&&(b=b.substr(ka.lastIndex),0===b.length?r.value.setHours(0,0,0,0):W(r.value,b,a,c));return r};aa=function(b,a,d,c){switch(r(d,"OraDateTimeConverter.parse")){case 0:return da(b,a,d,c,!1);case 1:return d=new Date,W(d,b,a,c),{value:d,warning:"lenient parsing was used"};case 2:return da(b,a,d,c,!0)}return null};ia=function(b,a,d,c,g,h,p,f,l,k,m){g=e.Vd(b).dates.calendars.gregorian[a][g];
b="months"===a?ea(b,d,h):ba(b,d,h);H(m,b,p,f,d,g[c][l],g[c][k]);return b};oa=function(b,a,d,c,e){a[d.timePart]=b;"h"===e||"hh"===e?12===b&&(a[d.timePart]=0):"k"===e||"kk"===e?24===b&&(a[d.timePart]=0):"S"===e&&(a[d.timePart]=b*Math.pow(10,3-c));H(d.timePart,a[d.timePart],d.start1,d.end1,b,d.start2,d.end2)};c=function(b,a,d,c){var g=e.Vd(c);b=e.trim(b);var h=g.dates.calendars.gregorian.eras.eraAbbr["1"],p=e.ug(h);b=b.replace(h,p);var h=ma(a,d),f=(new RegExp(h.regExp)).exec(b);if(null===f)return aa(b,
a,d,c);var l=h.groups,k=p=h=null,m=null,n;n=null;for(var r=!1,q,u,t={hour:0,minute:0,second:0,millisec:0},g=g.dates.calendars.gregorian.dayPeriods.format.wide.pm,w=s(d),v=0,x=l.length;v<x;v++){var C=f[v+1];if(C){var K=l[v],X=K.length;q=parseInt(C,10);var O=U[K];switch(O.token){case "months":p=ia(c,O.token,C,O.mLen,O.style,O.matchIndex,0,11,"1","12","month name");break;case "days":u=C;m=ia(c,O.token,C,O.dLen,O.style,O.matchIndex,0,6,"sun","sat","weekday");break;case "time":oa(q,t,O,X,K);break;case "dayOfMonth":k=
q;if(31<k)return aa(b,a,d,c);break;case "monthIndex":p=q-1;if(11<p)return aa(b,a,d,c);break;case "year":h=Y(w,q);H("year",h,0,9999,h,0,9999);break;case "ampm":r=e.$d(C)===e.$d(g);break;case "tz":n=q/100<<0,H("TZ Offset",n,-12,13,q,-12,13),q=Math.abs(q%100),H("TZ Offset",q,0,59,q,0,59),n=60*n+(e.lo(C,"-")?-q:q)}}}b=new Date;a=b.getFullYear();null===h&&(h=a);null===p&&null===k?(p=b.getMonth(),k=b.getDate()):null===k&&(k=1);a=A(h,p);H("day",k,1,a,k,1,a);b.setFullYear(h,p,k);null!==m&&b.getDay()!==m&&
ga(u,b.getDate());r&&12>t.hour&&(t.hour+=12);b.setHours(t.hour,t.minute,t.second,t.millisec);null!==n&&(u=b.getMinutes()-(n+b.getTimezoneOffset()),b.setHours(b.getHours()+(u/60<<0),u%60));return{value:b}};p=function(b,d,c){var e=c.replace(ua,"\\\\$1"),g=["^"],p=0,f=0;for(b={locale:b,numberingSystem:d,calendar:"gregorian"};null!==(d=Z.exec(e));){var l=e.slice(f,d.index),f=Z.lastIndex,p=p+a(l,g);if(!(p%2)&&(d=d[0],"/"!==d&&"zzzz"!==d&&"zzz"!==d&&"zz"!==d&&"zz"!==d&&"z"!==d))if(void 0!==U[d])if(b[U[d].key]=
U[d].value,"kk"===d||"HH"===d||"H"===d||"k"===d)b.hour12=!1;else{if("KK"===d||"hh"===d||"h"===d||"K"===d)b.hour12=!0}else t(c,b,d)}return b};v=function(b){b=p("","",b);var a=void 0!==b.hour||void 0!==b.minute||void 0!==b.second;return void 0===b.year&&void 0===b.month&&void 0===b.weekday&&void 0===b.day||!a?a?1:0:2};r=function(b,a){if(void 0!==b.pattern)return v(b.pattern);var d=e.fh(b,a),c=void 0!==d("hour","string",["2-digit","numeric"])||void 0!==d("minute","string",["2-digit","numeric"])||void 0!==
d("second","string",["2-digit","numeric"]),g=void 0!==d("year","string",["2-digit","numeric"])||void 0!==d("month","string",["2-digit","numeric","narrow","short","long"])||void 0!==d("day","string",["2-digit","numeric"])||void 0!==d("weekday","string",["narrow","short","long"]);if(g&&c)return 2;if(c)return 1;if(g)return 0;d=d("formatType","string",["date","time","datetime"],"date");return"datetime"===d?2:"time"===d?1:0};m=function(b,a,g,h){var p=e.wj(h,"nu");void 0===e.tg[p]&&(p="latn");if("latn"!==
p){var f,m=[];for(f=0;f<b.length;f++){var n=e.tg[p].indexOf(b[f]);-1!=n?m.push(n):m.push(b[f])}b=m.join("")}if(2>=arguments.length||void 0===g)g={year:"numeric",month:"numeric",day:"numeric"};p=g.pattern||d(g,a,"OraDateTimeConverter.parse");return c(b,p,g,a)};return{Ew:function(){Q||(Q=b());return Q}}}();a.ic=function(b){this.Init(b)};o_("IntlNumberConverter",a.ic,a);a.b.oa(a.ic,a.Pe,"oj.IntlNumberConverter");a.ic.prototype.Init=function(b){a.ic.t.Init.call(this,b)};a.b.g("IntlNumberConverter.prototype.Init",
{Init:a.ic.prototype.Init});a.ic.prototype.Oh=function(){this.rn||(this.rn=c.Ew());return this.rn};a.ic.prototype.format=function(b){if(null==b||"string"===typeof b&&0===a.fb.trim(""+b).length||"number"===typeof b&&isNaN(b))return"";var d=a.Ca.Jg(),c=a.ha.De(),e=this.resolvedOptions();try{return this.Oh().format(b,d,e,c)}catch(f){throw b=this.Yh(f,b),b;}};a.b.g("IntlNumberConverter.prototype.format",{format:a.ic.prototype.format});a.ic.prototype.Qb=function(){return a.ic.t.Qb.call(this)};a.b.g("IntlNumberConverter.prototype.getHint",
{Qb:a.ic.prototype.Qb});a.ic.prototype.gf=function(){return a.ic.t.gf.call(this)};a.b.g("IntlNumberConverter.prototype.getOptions",{gf:a.ic.prototype.gf});a.ic.prototype.parse=function(b){var d=a.Ca.Jg(),c=a.ha.De(),e=this.resolvedOptions();if(null==b||""===b)return null;try{return this.Oh().parse(a.fb.trim(b),d,e,c)}catch(f){throw b=this.Yh(f,b),b;}};a.b.g("IntlNumberConverter.prototype.parse",{parse:a.ic.prototype.parse});a.ic.prototype.resolvedOptions=function(){var b,d=a.ha.De();if(d!==this.Dk||
!this.hn){b=a.Ca.Jg();try{this.hn=this.Oh().resolvedOptions(b,this.gf(),d),this.Dk=d}catch(c){throw b=this.Yh(c),b;}}return this.hn};a.b.g("IntlNumberConverter.prototype.resolvedOptions",{resolvedOptions:a.ic.prototype.resolvedOptions});a.ic.prototype.Yh=function(b,d){var c=b.errorInfo,e,f,m;if(c)if(e=c.errorCode,c=c.parameterMap,a.i.Pd(c),b instanceof TypeError){if("optionTypesMismatch"===e||"optionTypeInvalid"===e)f=a.$c.Xj(e,c)}else b instanceof RangeError?"optionOutOfRange"===e&&(f=a.$c.Xj(e,
c)):b instanceof SyntaxError?"optionValueInvalid"===e&&(f=a.$c.Xj(e,c)):b instanceof Error&&("decimalFormatMismatch"===e?m="oj-converter.number.decimalFormatMismatch.summary":"currencyFormatMismatch"===e?m="oj-converter.number.currencyFormatMismatch.summary":"percentFormatMismatch"===e&&(m="oj-converter.number.percentFormatMismatch.summary"),m&&(e=a.da.C(m,{value:d||c.value,format:c.format}),f=a.da.C("oj-converter.hint.detail",{exampleValue:this.Tt()}),f=new a.sd(e,f)));f||(f=e=b.message,f=new a.sd(e,
f));return f};a.ic.prototype.Tt=function(){var b="";try{b=this.format(12345.98765)}catch(d){d instanceof a.sd&&(b="")}finally{return b}};var c;c=function(){function b(){return{format:function(b,a,c,e){if(2>=arguments.length||void 0===c)c={useGrouping:!0,style:"decimal"};p(c,"OraNumberConverter.format");var g={};t(a,g,c,e);return d(b,c,a,g,e)},parse:function(b,a,d,c){if("number"===typeof b)return b;if("[object Number]"===Object.prototype.toString.call(b))return Number(b);if(2>=arguments.length||void 0===
d)d={useGrouping:!0,style:"decimal"};var g=b;p(d,"OraNumberConverter.parse");var h=e.Vd(a),l={},k=e.wj(c,"nu");void 0===e.tg[k]&&(k="latn");if("latn"!==k){var r,s=[];for(r=0;r<b.length;r++){var u=e.tg[k].indexOf(b[r]);-1!=u?s.push(u):s.push(b[r])}b=s.join("")}t(a,l,d,c);r=h.numbers[l.numberingSystem].decimal;k=h.numbers[l.numberingSystem].group;s=NaN;s=b.replace(/ /g,"");if(z.test(s))return s=parseFloat(b);var u=f(b,d,l,h),s=u[0],u=u[1],s=s||"+",u=u.replace(/ /g,""),w=l.exponential,v,x=u.indexOf(w.toLowerCase());
0>x&&(x=u.indexOf(e.$d(w)));0>x?(v=u,u=null):(v=u.substr(0,x),u=u.substr(x+w.length));x=v.indexOf(r);0>x?(w=v,r=null):(w=v.substr(0,x),r=v.substr(x+r.length));w=w.split(k).join("");v=k.replace(/\u00A0/g," ");k!==v&&(w=w.split(v).join(""));k=s+w;null!==r&&(k+="."+r);null!==u&&(r=q(u,h,l),k+="e"+(r[0]||"+")+r[1]);F.test(k)?s=parseFloat(k):(k=m(b,l,h),s=parseFloat(k[0]+k[1]));if(isNaN(s)){var A,h="Unparsable number "+g+" The expected number pattern is "+l.pat;switch(d.style){case "decimal":A="decimalFormatMismatch";
break;case "currency":A="currencyFormatMismatch";break;case "percent":A="percentFormatMismatch"}h=Error(h);h.errorInfo={errorCode:A,parameterMap:{value:g,format:l.pat}};throw h;}!0===l.isPercent||"percent"===d.style?s/=100:!0===l.isPerMill&&(s/=1E3);return s},resolvedOptions:function(b,a,d){if(3>arguments.length||void 0===d)d=e.hl(b);if(2>arguments.length||void 0===a)a={useGrouping:!0,style:"decimal"};var c={};p(a,"OraNumberConverter.resolvedOptions");t(b,c,a,d);c.numberingSystemKey=e.wj(d,"nu");
void 0===e.tg[c.numberingSystemKey]&&(c.numberingSystemKey="latn");c={locale:d,style:void 0===a.style?"decimal":a.style,useGrouping:void 0===a.useGrouping?!0:a.useGrouping,minimumIntegerDigits:c.minimumIntegerDigits,minimumFractionDigits:c.minimumFractionDigits,maximumFractionDigits:c.maximumFractionDigits,numberingSystem:c.numberingSystemKey};"currency"===a.style&&(c.currency=a.currency,c.currencyDisplay=void 0===a.currencyDisplay?"symbol":a.currencyDisplay);void 0!==a.pattern&&(c.pattern=a.pattern);
return c}}}var a,d,c,f,m,q,t,p,r,s,u,v,w,x,E,A,Q,B,z=/^[+\-]?infinity$/i,F=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/,M=/(\D*)([+\-]?\d*\.?\d*(E[+\-]?\d+)?)/,y=/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,J=/(^0\.0*)([^0].*$)/;a=function(b,a,d){var c;for(c=b.length;c<a;c+=1)b=d?"0"+b:b+"0";return b};s=function(b,a,d,c){var e=new RangeError(b+" is out of range.  Enter a value between "+a+" and "+d+" for "+c);e.errorInfo={errorCode:"numberOptionOutOfRange",parameterMap:{value:b,minValue:a,maxValue:d,propertyName:c}};throw e;
};u=function(b,a,d,c,e){b=b[a];return void 0!==b?(b=Number(b),(isNaN(b)||b<d||b>c)&&s(b,d,c,a),Math.floor(b)):e};t=function(b,a,d,g){var h=e.Vd(b);g=e.IT(h,g);a.numberingSystemKey=g;a.numberingSystem="symbols-numberSystem-"+g;if(void 0!==d.pattern&&0<d.pattern.length)g=d.pattern;else{switch(d.style){case "decimal":g="decimalFormats-numberSystem-";break;case "currency":g="currencyFormats-numberSystem-";break;case "percent":g="percentFormats-numberSystem-";break;default:g="decimalFormats-numberSystem-"}g+=
a.numberingSystemKey;g=h.numbers[g].standard}b=e.Ar(e.hl(b)).language.language;a.lang=b;a.pat=g;a.minusSign=h.numbers[a.numberingSystem].minusSign;a.decimalSeparator=h.numbers[a.numberingSystem].decimal;a.exponential=h.numbers[a.numberingSystem].exponential;a.groupingSeparator=h.numbers[a.numberingSystem].group;a.currencyDisplay=d.currencyDisplay;void 0!==d.currency&&(a.currencyCode=d.currency.toUpperCase());a.style=d.style;c(d,g,h,a);void 0===d.pattern&&(a.minimumIntegerDigits=u(d,"minimumIntegerDigits",
1,21,a.minimumIntegerDigits),void 0!==d.maximumFractionDigits&&(a.maximumFractionDigits=u(d,"maximumFractionDigits",0,20,a.maximumFractionDigits),a.maximumFractionDigits<a.minimumFractionDigits&&(a.minimumFractionDigits=a.maximumFractionDigits)),void 0!==d.minimumFractionDigits&&(a.minimumFractionDigits=u(d,"minimumFractionDigits",0,20,a.minimumFractionDigits)),a.maximumFractionDigits<a.minimumFractionDigits&&(a.maximumFractionDigits=a.minimumFractionDigits))};r=function(b){var a=new TypeError('The property "currency" is required whenthe property "'+
b+'" is "currency". An accepted value is a three-letter ISO 4217 currency code.');a.errorInfo={errorCode:"optionTypesMismatch",parameterMap:{propertyName:b,propertyValue:"currency",requiredPropertyName:"currency",requiredPropertyValueValid:"a three-letter ISO 4217 currency code"}};throw a;};p=function(b,a){var d=e.fh(b,a),c=d("style","string",["currency","decimal","percent","perMill"],"decimal"),d=d("currency","string");"currency"===c&&void 0===d&&r("style")};w=function(b,d){var c=b+"",e=0,g=c.split(/e/i),
f=g[0];J.lastIndex=0;var p=J.exec(f);null!==p?(e=p[1].length-1,f=p[2]):f=f.replace(".","");var p=1<g.length?parseInt(g[1],10):0,g=parseInt(f,10),l=d.minimumIntegerDigits+d.maximumFractionDigits;f.length>l&&(l-=f.length,g=Math.round(g*Math.pow(10,l)));l=d.minimumIntegerDigits+d.minimumFractionDigits;g=a(g+"",l,!1);p=-1!==c.indexOf(".")?p-(d.minimumIntegerDigits-c.indexOf(".")+e):p-(l-f.length-d.minimumFractionDigits);c=Math.abs(p);c=a(c+"",d.minExponentDigits,!0);0>p&&(c=d.minusSign+c);e=g.slice(0,
d.minimumIntegerDigits);return e=0<g.slice(d.minimumIntegerDigits).length?e+(d.decimalSeparator+g.slice(d.minimumIntegerDigits)+d.exponential+c):e+(d.exponential+c)};v=function(b,d,c){var e=c.groupingSize,g,f=(b+"").split(/e/i),p=1<f.length?parseInt(f[1],10):0;g=f[0];var f=g.split("."),l=1<f.length?f[1]:"";if(1<f.length&&l.length>p){var k=Math.min(c.maximumFractionDigits,l.length-p);g=Math.pow(10,k);g=Math.round(b*g)/g;isFinite(g)||(g=b);b=g}f=(b+"").split(/e/i);p=1<f.length?parseInt(f[1],10):0;g=
f[0];f=g.split(".");g=f[0];l=1<f.length?f[1]:"";0<p?(l=a(l,p,!1),g+=l.slice(0,p),l=l.substr(p)):0>p&&(p=-p,g=a(g,p+1,!0),l=g.slice(-p,g.length)+l,g=g.slice(0,-p));l=0<k?c.decimalSeparator+(l.length>k?l.slice(0,k):a(l,k,!1)):0<c.minimumFractionDigits?c.decimalSeparator:"";l=a(l,c.decimalSeparator.length+c.minimumFractionDigits,!1);b=c.groupingSeparator;k="";!1===d.useGrouping&&void 0===d.pattern&&(b="");g=a(g,c.minimumIntegerDigits,!0);d=g.length-1;for(l=1<l.length?l:"";0<=d;){if(0===e||e>d)return e=
g.slice(0,d+1)+(k.length?b+k+l:l);k=g.slice(d-e+1,d+1)+(k.length?b+k:"");d-=e}return e=g.slice(0,d+1)+b+k+l};d=function(b,a,d,c,g){d=e.Vd(d);if(!isFinite(b))return Infinity===b||-Infinity===b?d.numbers[c.numberingSystem].infinity:d.numbers[c.numberingSystem].nan;d=Math.abs(b);!0===c.isPercent||"percent"===a.style?d*=100:!0===c.isPerMill&&(d*=1E3);d=!0==c.useExponentialNotation?w(d,c):v(d,a,c);a="";a=0>b?a+(c.negativePrefix+d+c.negativeSuffix):a+(c.positivePrefix+d+c.positiveSuffix);b=e.wj(g,"nu");
void 0===e.tg[b]&&(b="latn");if("latn"!==b){g=[];for(c=0;c<a.length;c++)"0"<=a[c]&&"9">=a[c]?g.push(e.tg[b][a[c]]):g.push(a[c]);return g.join("")}return a};f=function(b,a,d,c){b=e.ug(b);var g="",h=!1,f=new RegExp("^"+c.numbers[d.numberingSystem].plusSign.replace(y,"\\$1"));b=b.replace(f,"");var p=e.ug(d.positivePrefix),l=e.ug(d.positiveSuffix),k=e.ug(d.negativePrefix),f=e.ug(d.negativeSuffix),r=new RegExp("^"+(p||"").replace(y,"\\$1")),n=new RegExp((l||"").replace(y,"\\$1")+"$"),s=new RegExp("^"+
(k||"").replace(y,"\\$1")),q=new RegExp((f||"").replace(y,"\\$1")+"$");if(!0==s.test(b)&&!0==q.test(b))b=b.replace(s,""),b=b.replace(q,""),g="-",h=!0;else if(!0==r.test(b)&&!0==n.test(b))b=b.replace(r,""),b=b.replace(n,""),g="+",h=!0;else if("currency"===a.style){a=r=d.currencyCode;var u;void 0!==c.numbers.currencies[r]&&(a=c.numbers.currencies[r].symbol);void 0===d.currencyDisplay||"symbol"===d.currencyDisplay?u=a:"code"===d.currencyDisplay&&(u=r);void 0!==u&&(r=(p||"").replace(u,""),l=(l||"").replace(u,
""),k=(k||"").replace(u,""),u=(f||"").replace(u,""),r=new RegExp(("^"+r).replace(y,"\\$1")),n=new RegExp(l.replace(y,"\\$1")+"$"),s=new RegExp(("^"+k).replace(y,"\\$1")),q=new RegExp(u.replace(y,"\\$1")+"$"),!0==s.test(b)&&!0==q.test(b)?(b=b.replace(s,""),b=b.replace(q,""),g="-",h=!0):!0==r.test(b)&&!0==n.test(b)&&(b=b.replace(r,""),b=b.replace(n,""),g="+",h=!0))}return h?[g,b]:m(b,d,c)};m=function(b,a,d){var c=d.numbers[a.numberingSystem].group,g=d.numbers[a.numberingSystem].decimal,h="",f="";a=
e.$d(d.numbers[a.numberingSystem].exponential);b=e.$d(b);b=b.split(a).join("E");b=b.split(g).join(".");b=b.split(c).join("");g=c.replace(/\u00A0/g," ");c!==g&&(b=b.split(g).join(""));"."===b.charAt(0)&&(b=b.substr(1),f=".");c=M.exec(b);f+=c[2];e.lo(f,"-")?(f=f.substr(1),h="-"):e.lo(b,"+")&&(f=f.substr(1),h="+");return[h,f]};q=function(b,a,d){var c=a.numbers[d.numberingSystem].minusSign;a=a.numbers[d.numberingSystem].plusSign;var g;b=e.ug(b);c=e.ug(c);a=e.ug(a);e.lo(b,c)?g=["-",b.substr(c.length)]:
e.lo(b,e.ug(a))&&(g=["+",b.substr(a.length)]);return g||["",b]};var I,D,G,N;B=function(b){var a;a=new SyntaxError('Unexpected character(s) encountered in the pattern "'+b+' An example of a valid pattern is "#,##0.###".');a.errorInfo={errorCode:"optionValueInvalid",parameterMap:{propertyName:"pattern",propertyValue:b,propertyValueHint:"#,##0.###"}};throw a;};E=function(b,a,d){return null!==(new RegExp(d,"i")).exec(b.substr(a,d.length))};Q=function(b,a){var d={};null!=I&&(a.positivePrefix=A(I,b,a,d));
null!=D&&(a.positiveSuffix=A(D,b,a,d));null!=G&&(a.negativePrefix=A(G,b,a,d));null!=N&&(a.negativeSuffix=A(N,b,a,d));void 0!==d.name&&(a.positiveSuffix="\u00a0"+d.name,a.positivePrefix="","ar"===a.lang?(a.negativeSuffix=b.numbers[a.numberingSystem].minusSign+"\u00a0"+d.name,a.negativePrefix=""):(a.negativeSuffix="\u00a0"+d.name,a.negativePrefix=b.numbers[a.numberingSystem].minusSign))};A=function(b,a,d,c){for(var e="",g=0;g<b.length;){var h=b.charAt(g++);if("'"!=h){switch(h){case "\u00a4":var f=h=
d.currencyCode,p=h;void 0!==a.numbers.currencies[h]&&(f=a.numbers.currencies[h].displayName,p=a.numbers.currencies[h].symbol);void 0===d.currencyDisplay||"symbol"===d.currencyDisplay?h=p:"code"!==d.currencyDisplay&&(h=f,c.name=h);break;case "%":h=a.numbers[d.numberingSystem].percentSign;break;case "\u2030":h=a.numbers[d.numberingSystem].perMille;break;case "-":h=a.numbers[d.numberingSystem].minusSign}e=e.concat(h)}}return e};c=function(b,a,d,c){for(var e=!1,g=!1,h=0,f=0,p=!0,l=1;0<=l&&f<a.length;--l){for(var k=
!1,m="",n="",s=-1,q=1,u=0,t=0,w=0,v=-1,x,A=0,p=!0,z=f;z<a.length;++z){var y=a.charAt(z);switch(A){case 0:case 2:if(k){if("'"===y){z+1<a.length&&"'"===a.charAt(z+1)?(++z,p?m=m.concat("''"):n=n.concat("''")):k=!1;continue}}else if("#"===y||"0"===y||","===y||"."===y){A=1;--z;continue}else if("\u00a4"===y){void 0===b.currency&&r("pattern");b.style="currency";(y=z+1<a.length&&"\u00a4"===a.charAt(z+1))&&++z;p?m=m.concat(y?"'\u00a4\u00a4":"'\u00a4"):n=n.concat(y?"'\u00a4\u00a4":"'\u00a4");continue}else if("'"===
y){if("'"==y){z+1<a.length&&"'"==a.charAt(z+1)?(++z,p?m=m.concat("''"):n=n.concat("''")):k=!0;continue}}else if(";"===y){0!==A&&0!==l||B(a);f=z+1;z=a.length;continue}else if("%"===y){b.style="percent";1!=q&&B(a);c.isPercent=!0;q=100;p?m=m.concat("'%"):n=n.concat("'%");continue}else if("\u2030"===y){1!=q&&B(a);b.style="perMill";c.isPerMill=!0;q=1E3;p?m=m.concat("'\u2030"):n=n.concat("'\u2030");continue}else if("-"===y){p?m=m.concat("'-"):n=n.concat("'-");continue}p?m=m.concat(y):n=n.concat(y);break;
case 1:if(1===l)++h;else{0===--h&&(A=2,p=!1);continue}if("#"===y)0<t?++w:++u,0<=v&&0>s&&++v;else if("0"===y)0<w&&B(a),++t,0<=v&&0>s&&++v;else if(","===y)v=0;else if("."===y)0<=s&&B(a),s=u+t+w;else if(E(a,z,"E")){g&&B(a);g=!0;x=0;for(z+=1;z<a.length&&"0"===a.charAt(z);)++x,++h,++z;(1>u+t||1>x)&&B(a);A=2;p=!1;--z}else A=2,p=!1,--z,--h}}0===t&&0<u&&0<=s&&(t=s,0===t&&++t,w=u-t,u=t-1,t=1);(0>s&&0<w||0<=s&&(s<u||s>u+t)||0==v||k)&&B(a);1===l?(I=m,D=n,G=I,N=D,k=u+t+w,c.minimumIntegerDigits=(0<=s?s:k)-u,c.maximumIntegerDigits=
g?u+c.minimumIntegerDigits:2147483647,c.maximumFractionDigits=0<=s?k-s:0,c.minimumFractionDigits=0<=s?u+t-s:0,c.groupingSize=0<v?v:0):(G=m,N=n,e=!0)}0==a.length&&(I=D="",c.minimumIntegerDigits=0,c.maximumIntegerDigits=2147483647,c.minimumFractionDigits=0,c.maximumFractionDigits=2147483647);c.useExponentialNotation=g;c.minExponentDigits=x;if(!e||0==G.localeCompare(I)&&0==N.localeCompare(D))"currency"===b.style&&"ar"===c.lang?(N=D+"'\u200f-",G=I):(N=D,G="'-"+I);Q(d,c)};return{Ew:function(){x||(x=b());
return x}}}();a.Qf=function(b){this.Init(b)};o_("DateRestrictionValidator",a.Qf,a);a.b.oa(a.Qf,a.Ld,"oj.DateRestrictionValidator");a.Qf.prototype.Init=function(b){a.Qf.t.Init.call(this);this.hM=b.dayMetaData;b&&(this.Vi=b.message||{})};a.b.g("DateRestrictionValidator.prototype.Init",{Init:a.Qf.prototype.Init});a.Qf.prototype.kC=function(b){var a=this.hM,d=function q(b,a,d){if(!b||a===d.length)return b;var c=a+1;return q(b[d[a]],c,d)||q(b["*"],c,d)};if(a){var c=b.getFullYear(),e=b.getMonth()+1;b=b.getDate();
return(a=d(a,0,[c,e,b]))&&a.disabled}return!1};o_("DateRestrictionValidator.prototype._inDisabledMetaData",a.Qf.prototype.kC,a);a.Qf.prototype.validate=function(b){var d,c="",e="",e=a.da,c=this.Vi;if(this.kC(b))throw d=c.messageDayMetaData,c=e.C("oj-validator.restriction.date.dayMetaData.summary"),e=d?e.pb(d,{value:b}):e.C("oj-validator.restriction.date.dayMetaData.detail",{value:b}),new a.te(c,e);return b};a.b.g("DateRestrictionValidator.prototype.validate",{validate:a.Qf.prototype.validate});a.vd=
function(b){this.Init(b)};o_("RegExpValidator",a.vd,a);a.b.oa(a.vd,a.Ld,"oj.RegExpValidator");a.vd.as="oj-validator.regExp.detail";a.vd.bs="oj-validator.regExp.summary";a.vd.prototype.Init=function(b){a.vd.t.Init.call(this);this.Ra=b};a.b.g("RegExpValidator.prototype.Init",{Init:a.vd.prototype.Init});a.vd.prototype.validate=function(b){var d=this.Ra&&this.Ra.pattern||"",c,e,f;b=b?b.toString():b;var m;m=b.match("^("+d+")$");if(null===m||m[0]!==b)throw this.Ra&&(e=this.Ra.messageSummary||null,f=this.Ra.messageDetail||
null,c=this.Ra&&this.Ra.label||""),b={label:c,pattern:d,value:b},e=e?a.da.pb(e,b):a.da.C(this.ou(),b),f=f?a.da.pb(f,b):a.da.C(this.Nt(),b),new a.te(e,f);return!0};a.b.g("RegExpValidator.prototype.validate",{validate:a.vd.prototype.validate});a.vd.prototype.Qb=function(){var b=null,d={};this.Ra&&this.Ra.hint&&(d={pattern:this.Ra.pattern},b=a.da.pb(this.Ra.hint,d));return b};a.b.g("RegExpValidator.prototype.getHint",{Qb:a.vd.prototype.Qb});a.vd.prototype.ou=function(){return a.vd.bs};a.vd.prototype.Nt=
function(){return a.vd.as};a.Ha=function(b){this.Init(b)};o_("IntlDateTimeConverter",a.Ha,a);a.b.oa(a.Ha,a.rb,"oj.IntlDateTimeConverter");a.Ha.GI=new Date(1998,10,29,15,45,31);a.Ha.prototype.Init=function(b){a.Ha.t.Init.call(this,b)};a.b.g("IntlDateTimeConverter.prototype.Init",{Init:a.Ha.prototype.Init});a.Ha.prototype.Oh=function(){this.rn||(this.rn=d.Ew());return this.rn};a.Ha.prototype.format=function(b){var d=a.Ca.Jg(),c=a.ha.De(),e=this.resolvedOptions();if(null==b||"string"===typeof b&&0===
a.fb.trim(""+b).length)return"";try{return this.Oh().format(b,d,e,c)}catch(f){throw b=this.Yh(f,b),b;}};a.b.g("IntlDateTimeConverter.prototype.format",{format:a.Ha.prototype.format});a.Ha.prototype.hr=function(b,d){var c=a.Ca.Jg(),e=a.ha.De();try{return this.Oh().hr(b,c,d,e)}catch(f){throw c=this.Yh(f,b),c;}};a.b.g("IntlDateTimeConverter.prototype.formatRelative",{hr:a.Ha.prototype.hr});a.Ha.prototype.Qb=function(){var b=this.resolvedOptions().patternFromOptions;return b?b:""};a.b.g("IntlDateTimeConverter.prototype.getHint",
{Qb:a.Ha.prototype.Qb});a.Ha.prototype.Tt=function(){var b="";try{b=this.format(a.Ha.GI)}catch(d){d instanceof a.sd&&(b="")}finally{return b}};a.Ha.prototype.gf=function(){return a.Ha.t.gf.call(this)};a.b.g("IntlDateTimeConverter.prototype.getOptions",{gf:a.Ha.prototype.gf});a.Ha.prototype.resolvedOptions=function(){var b,d=a.ha.De(),c=this.gf();if(d!==this.Dk||!this.hn){b=a.Ca.Jg();try{this.hn=this.Oh().resolvedOptions(b,c,d),this.Dk=d}catch(e){throw b=this.Yh(e),b;}}return this.hn};a.b.g("IntlDateTimeConverter.prototype.resolvedOptions",
{resolvedOptions:a.Ha.prototype.resolvedOptions});a.Ha.prototype.Qn=function(){var b=this.resolvedOptions(),a=b.hour12;return b.hour&&!a?!0:!1};a.b.g("IntlDateTimeConverter.prototype.isHourInDaySet",{Qn:a.Ha.prototype.Qn});a.Ha.prototype.Pn=function(){var b=this.resolvedOptions(),a=b.hour12;return b.hour&&a?!0:!1};a.b.g("IntlDateTimeConverter.prototype.isHourInAMPMSet",{Pn:a.Ha.prototype.Pn});a.Ha.prototype.Sn=function(){return this.gj("minute")};a.b.g("IntlDateTimeConverter.prototype.isMinuteSet",
{Sn:a.Ha.prototype.Sn});a.Ha.prototype.Un=function(){return this.gj("second")};a.b.g("IntlDateTimeConverter.prototype.isSecondSet",{Un:a.Ha.prototype.Un});a.Ha.prototype.Rn=function(){return this.gj("millisecond")};a.b.g("IntlDateTimeConverter.prototype.isMilliSecondSet",{Rn:a.Ha.prototype.Rn});a.Ha.prototype.Vn=function(){return this.gj("year")};a.b.g("IntlDateTimeConverter.prototype.isYearSet",{Vn:a.Ha.prototype.Vn});a.Ha.prototype.Tn=function(){return this.gj("month")};a.b.g("IntlDateTimeConverter.prototype.isMonthSet",
{Tn:a.Ha.prototype.Tn});a.Ha.prototype.On=function(){return this.gj("day")};a.b.g("IntlDateTimeConverter.prototype.isDaySet",{On:a.Ha.prototype.On});a.Ha.prototype.Nn=function(){return this.gj("weekday")};a.b.g("IntlDateTimeConverter.prototype.isDayNameSet",{Nn:a.Ha.prototype.Nn});a.Ha.prototype.parse=function(b){var d,c;if(null==b||""===b)return null;var e=a.Ca.Jg(),f=a.ha.De(),m=this.resolvedOptions();try{return d=this.Oh().parse(b,e,m,f),c=d.value,"object"===typeof d&&c&&d.warning&&a.T.warn("The value "+
b+" was leniently parsed to represent a date "+c.toString?c.toString():c),c}catch(q){throw b=this.Yh(q,b),b;}};a.b.g("IntlDateTimeConverter.prototype.parse",{parse:a.Ha.prototype.parse});a.Ha.prototype.Yh=function(b,d){var c=b.errorInfo,e,f,m,q;if(c)if(e=c.errorCode,c=c.parameterMap,a.i.Pd(c),m=c.propertyName,b instanceof TypeError){if("optionTypesMismatch"===e||"optionTypeInvalid"===e)f=a.$c.Xj(e,c)}else b instanceof RangeError?"optionOutOfRange"===e?f=a.$c.Xj(e,c):"datetimeOutOfRange"===e&&(e=a.da.C("oj-converter.datetime.datetimeOutOfRange.summary",
{propertyName:m,value:c.value}),f=a.da.C("oj-converter.datetime.datetimeOutOfRange.detail",{minValue:c.minValue,maxValue:c.maxValue}),f=new a.sd(e,f)):b instanceof SyntaxError?"optionValueInvalid"===e&&(f=a.$c.Xj(e,c)):b instanceof Error&&("dateFormatMismatch"===e?q="oj-converter.datetime.dateFormatMismatch.summary":"timeFormatMismatch"===e?q="oj-converter.datetime.timeFormatMismatch.summary":"datetimeFormatMismatch"===e?q="oj-converter.datetime.datetimeFormatMismatch.summary":"dateToWeekdayMismatch"===
e&&(e=a.da.C("oj-converter.datetime.dateToWeekdayMismatch.summary",{date:c.date,weekday:c.weekday}),f=a.da.C("oj-converter.datetime.dateToWeekdayMismatch.detail"),f=new a.sd(e,f)),q&&(e=a.da.C(q,{value:d||c.value,format:c.format}),f=a.da.C("oj-converter.hint.detail",{exampleValue:this.Tt()}),f=new a.sd(e,f)));f||(f=e=b.message,f=new a.sd(e,f));return f};a.Ha.prototype.gj=function(b){return this.resolvedOptions()[b]?!0:!1};var e={tg:{latn:"0123456789",arab:"\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669",
thai:"\u0e50\u0e51\u0e52\u0e53\u0e54\u0e55\u0e56\u0e57\u0e58\u0e59"},XH:/^(?:(en-GB-oed|i-(?:ami|bnn|default|enochian|hak|klingon|lux|mingo|navajo|pwn|tao|tay|tsu)|sgn-(?:BE-FR|BE-NL|CH-DE))|(art-lojban|cel-gaulish|no-(?:bok|nyn)|zh-(?:guoyu|hakka|min|min-nan|xiang)))$|^(x(?:-[0-9a-z]{1,8})+)$|^(?:((?:[a-z]{2,3}(?:(?:-[a-z]{3}){1,3})?)|[a-z]{4}|[a-z]{5,8})(?:-([a-z]{4}))?(?:-([a-z]{2}|[0-9]{3}))?((?:-(?:[a-z0-9]{5,8}|[0-9][a-z0-9]{3}))*)?((?:-[0-9a-wy-z](?:-[a-z0-9]{2,8}){1,})*)?(-x(?:-[0-9a-z]{1,8})+)?)$/i,
EU:/^\s+|\s+$|\u200f|\u200e/g,FU:/\s+|\u200f|\u200e/g,jV:["0","00","000"],trim:function(b){return(b+"").replace(e.EU,"")},ug:function(b){return(b+"").replace(e.FU,"")},lo:function(b,a){return 0===b.indexOf(a)},$d:function(b){return b.split("\u00a0").join(" ").toUpperCase()},fo:function(b,a){var d;d=b+"";return 1<a&&d.length<a?(d=e.jV[a-2]+d,d.substr(d.length-a,a)):d},IT:function(b,a){if(void 0===a)return"latn";var d=e.wj(a,"nu")||"";void 0===b.numbers["symbols-numberSystem-"+d]&&(d="latn");return d},
Ar:function(b){b=e.XH.exec(b);if(!b)return null;var a=b[4],a=a?a.split("-"):null,d=null;a&&(d=a.shift());var c=b[7];(c=c?c.split("-"):null)&&c.shift();var f=b[9];if(f=f?f.split("-"):null)f.shift(),f.shift();var m=b[3];(m=m?m.split("-"):null)&&m.shift();return{language:{language:d,tW:a||[]},OW:b[5]||null,region:b[6]||null,variant:c||null,sW:e.yU(b[8]),LW:f||m||[],vW:{zW:b[1]||null,MW:b[2]||null}}},yU:function(b){if(!b)return[];for(var a=[],d,c,e=!1,f=!1,q="",t=!1,p=0,r=b.length;p<r;p++)c=b[p],"-"!==
c||e?e&&!f?(f=!0,d.singleton=c):"-"===c?t?1===q.length?(f=t=!1,a.push(d),d={singleton:null,extension:[]}):(d.extension.push(q),q=""):(q="",t=!0):q+=c:(e=!0,d={singleton:null,extension:[]});d.extension.push(q);a.push(d);return a},wj:function(b,a){var d=e.Ar(b||"en-US");if(null===d||void 0===d)return null;var d=d.extension,c,f;for(f in d)if("u"===d[f].singleton){for(var m in d[f].extension)if(d[f].extension[m]===a){m++;c=d[f].extension[m];break}break}return c},Vd:function(b){b=b.main;var a,d;for(d in b){a=
d;break}return b[a]},hl:function(b){b=b.main;var a,d;for(d in b){a=d;break}return a},fh:function(b,a){if(void 0===b)throw Error("Internal "+a+" error. Default options missing.");return function(d,c,e,f){if(void 0!==b[d]){f=b[d];switch(c){case "boolean":f=Boolean(f);break;case "string":f=String(f);break;case "number":f=Number(f);break;default:throw Error("Internal error. Wrong value type.");}if(void 0!==e&&-1===e.indexOf(f)){c=[];for(f=0;f<e.length;f++)c.push(e[f]);e=new RangeError("The value '"+b[d]+
"' is out of range for '"+a+"' options property '"+d+"'. Valid values: "+c);e.errorInfo={errorCode:"optionOutOfRange",parameterMap:{propertyName:d,propertyValue:b[d],propertyValueValid:c,caller:a}};throw e;}}return f}}};a.Rf=function(b){this.Init(b)};o_("DateTimeRangeValidator",a.Rf,a);a.b.oa(a.Rf,a.Ld,"oj.DateTimeRangeValidator");a.Rf.prototype.Init=function(b){a.Rf.t.Init.call(this);this.Ad=b.min||null;this.he=b.max||null;this.gd=a.$c.getConverterInstance(b.converter);b&&(this.Gm=b.hint||{},this.Vi=
b.message||{})};a.b.g("DateTimeRangeValidator.prototype.Init",{Init:a.Rf.prototype.Init});a.Rf.prototype.validate=function(b){var d,c,e;d=this.Ad;var f=this.he,m="",q="",q=a.da,m=this.Vi;e=d&&this.gd?this.gd.format(d):d;c=f&&this.gd?this.gd.format(f):f;if(null===b)return b;if(null!==d&&null!==f){if(b>=d&&b<=f||d>f)return b;d=m.messageNotInRange;m=q.C("oj-validator.range.datetime.range.summary");q=d?q.pb(d,{value:b,min:e,max:c}):q.C("oj-validator.range.datetime.range.detail",{min:e,max:c})}else if(null!==
d){if(b>=d)return b;c=m.messageMinimum;m=q.C("oj-validator.range.datetime.min.summary");q=c?q.pb(c,{value:b,min:e}):q.C("oj-validator.range.datetime.min.detail",{min:e})}else{if(null===f||b<=f)return b;e=m.messageMaximum;m=q.C("oj-validator.range.datetime.max.summary");q=e?q.pb(e,{value:b,max:c}):q.C("oj-validator.range.datetime.max.detail",{max:c})}throw new a.te(m,q);};a.b.g("DateTimeRangeValidator.prototype.validate",{validate:a.Rf.prototype.validate});a.Rf.prototype.Qb=function(){var b=null,d=
this.Gm,c=d.hintInRange,e=d.hintMinimum,d=d.hintMaximum,f=this.Ad,m=this.he,q=f&&this.gd?this.gd.format(f):f,t=m&&this.gd?this.gd.format(m):m,p=a.da;null!==f&&null!==m?b=c?p.pb(c,{min:q,max:t}):p.C("oj-validator.range.datetime.range.hint",{min:q,max:t}):null!==f?b=e?p.pb(e,{min:f}):p.C("oj-validator.range.datetime.min.hint",{min:q}):null!==m&&(b=d?p.pb(d,{max:m}):p.C("oj-validator.range.datetime.max.hint",{max:t}));return b};a.b.g("DateTimeRangeValidator.prototype.getHint",{Qb:a.Rf.prototype.Qb});
a.Nc=function(b){this.Init(b)};o_("RequiredValidator",a.Nc,a);a.b.oa(a.Nc,a.Ld,"oj.RequiredValidator");a.Nc.as="oj-validator.required.detail";a.Nc.bs="oj-validator.required.summary";a.Nc.prototype.Init=function(b){a.Nc.t.Init.call(this);this.Ra=b};a.b.g("RequiredValidator.prototype.Init",{Init:a.Nc.prototype.Init});a.Nc.prototype.validate=function(b){var d,c,e={},e="";if("number"===typeof b&&0===b||b&&0!==b.length)return!0;this.Ra&&(d=this.Ra.messageDetail||this.Ra.message||null,c=this.Ra.messageSummary||
null,e=this.Ra.label||"");e={label:e};b=c?a.da.pb(c,e):a.da.C(this.ou(),e);d=d?a.da.pb(d,e):a.da.C(this.Nt(),e);throw new a.te(b,d);};a.b.g("RequiredValidator.prototype.validate",{validate:a.Nc.prototype.validate});a.Nc.prototype.Qb=function(){var b="";this.Ra&&this.Ra.hint&&(b=a.da.C(this.Ra.hint));return b};a.b.g("RequiredValidator.prototype.getHint",{Qb:a.Nc.prototype.Qb});a.Nc.prototype.ou=function(){return a.Nc.bs};a.Nc.prototype.Nt=function(){return a.Nc.as};a.Cg=function(b){this.Init(b)};o_("LengthValidator",
a.Cg,a);a.b.oa(a.Cg,a.Ld,"oj.LengthValidator");a.Cg.prototype.Init=function(b){a.Cg.t.Init.call(this);this.Ad=b.min;this.he=b.max;b&&(this.Gm=b.hint||{},this.Vi=b.message||{})};a.b.g("LengthValidator.prototype.Init",{Init:a.Cg.prototype.Init});a.Cg.prototype.Qb=function(){var b=null,d=this.Gm,c=d.hintInRange,e=d.hintMinimum,d=d.hintMaximum,f=a.da,m=void 0!==this.Ad?parseInt(this.Ad,10):null,q=void 0!==this.he?parseInt(this.he,10):null;null!==m&&null!==q?m!==q?(b={min:m,max:q},b=c?f.pb(c,b):f.C("oj-validator.length.range.hint",
b)):b=f.C("oj-validator.length.exact.hint",{length:m}):null!==m?(b={min:m},b=e?f.pb(e,b):f.C("oj-validator.length.min.hint",b)):null!==q&&(b={max:q},b=d?f.pb(d,b):f.C("oj-validator.length.max.hint",b));return b};a.Cg.prototype.validate=function(b){var d="",c="",d=""+b,e=d.length,f=this.Vi,c=f.messageNotInRange,m=f.messageMinimum,f=f.messageMaximum,q=a.da,t=void 0!==this.Ad?parseInt(this.Ad,10):null,p=void 0!==this.he?parseInt(this.he,10):null;if((null===t||e>=this.Ad)&&(null===p||e<=this.he))return d;
0<this.Ad&&null!==p?this.Ad===this.he?(b={value:b,length:t},d=q.C("oj-validator.length.exact.summary"),c=q.C("oj-validator.length.exact.detail",b)):(b={value:b,min:t,max:p},d=q.C("oj-validator.length.range.summary"),c=c?q.pb(c,b):q.C("oj-validator.length.range.detail",b)):e<this.Ad?(b={value:b,min:t},d=q.C("oj-validator.length.min.summary"),c=m?q.pb(m,b):q.C("oj-validator.length.min.detail",b)):(b={value:b,max:p},d=q.C("oj-validator.length.max.summary"),c=f?q.pb(f,b):q.C("oj-validator.length.max.detail",
b));throw new a.te(d,c);};a.b.g("LengthValidator.prototype.validate",{validate:a.Cg.prototype.validate});a.Tf=function(b){this.Init(b)};o_("NumberRangeValidator",a.Tf,a);a.b.oa(a.Tf,a.Ld,"oj.NumberRangeValidator");a.Tf.prototype.Init=function(b){a.Tf.t.Init.call(this);this.Ad=b.min;this.he=b.max;this.gd=a.$c.getConverterInstance(b.converter);b&&(this.Gm=b.hint||{},this.Vi=b.message||{})};a.b.g("NumberRangeValidator.prototype.Init",{Init:a.Tf.prototype.Init});a.Tf.prototype.validate=function(b){var d=
b?b.toString():b,c=parseFloat(d),e=this.Vi,f=e.messageNotInRange,m=e.messageMinimum,e=e.messageMaximum,q=void 0!==this.Ad?parseFloat(this.Ad):null,t=void 0!==this.he?parseFloat(this.he):null,p=q&&this.gd?this.gd.format(q):q,r=t&&this.gd?this.gd.format(t):t,s="",u="",u=null,v=a.da;if(null===b)return b;if(null!==q&&null!==t){if(c>=q&&c<=t||q>t)return d;u={value:b,min:p,max:r};s=v.C("oj-validator.range.number.range.summary");u=f?v.pb(f,u):v.C("oj-validator.range.number.range.detail",u)}else if(null!==
q){if(c>=q)return d;u={value:b,min:p};s=v.C("oj-validator.range.number.min.summary");u=m?v.pb(m,u):v.C("oj-validator.range.number.min.detail",u)}else{if(null===t||c<=t)return d;u={value:b,max:r};s=v.C("oj-validator.range.number.max.summary");u=e?v.pb(e,u):v.C("oj-validator.range.number.max.detail",u)}throw new a.te(s,u);};a.b.g("NumberRangeValidator.prototype.validate",{validate:a.Tf.prototype.validate});a.Tf.prototype.Qb=function(){var b=null,d=this.Gm,c=d.hintInRange,e=d.hintMinimum,d=d.hintMaximum,
f=a.da,m=void 0!==this.Ad?parseFloat(this.Ad):null,q=void 0!==this.he?parseFloat(this.he):null,t=m&&this.gd?this.gd.format(m):m,p=q&&this.gd?this.gd.format(q):q;null!==m&&null!==q?b=c?f.pb(c,{min:t,max:p}):f.C("oj-validator.range.number.range.hint",{min:t,max:p}):null!==m?b=e?f.pb(e,{min:t}):f.C("oj-validator.range.number.min.hint",{min:t}):null!==q&&(b=d?f.pb(d,{max:p}):f.C("oj-validator.range.number.max.hint",{max:p}));return b};a.b.g("NumberRangeValidator.prototype.getHint",{Qb:a.Tf.prototype.Qb});
a.qI=function(){return{createConverter:function(b){return new a.ic(b)}}}();a.ba.nz(a.Pf.CONVERTER_TYPE_NUMBER,a.qI);a.cI=function(){return{createConverter:function(b){return new a.Ha(b)}}}();a.ba.nz(a.Pf.CONVERTER_TYPE_DATETIME,a.cI);a.tI=function(){return{createValidator:function(b){return new a.Nc(b)}}}();a.ba.Yj(a.kc.VALIDATOR_TYPE_REQUIRED,a.tI);a.sI=function(){return{createValidator:function(b){return new a.vd(b)}}}();a.ba.Yj(a.kc.VALIDATOR_TYPE_REGEXP,a.sI);a.dI=function(){return{createValidator:function(b){return new a.Rf(b)}}}();
a.ba.Yj(a.kc.VALIDATOR_TYPE_DATETIMERANGE,a.dI);a.bI=function(){return{createValidator:function(b){return new a.Qf(b)}}}();a.ba.Yj(a.kc.VALIDATOR_TYPE_DATERESTRICTION,a.bI);a.rI=function(){return{createValidator:function(b){return new a.Tf(b)}}}();a.ba.Yj(a.kc.VALIDATOR_TYPE_NUMBERRANGE,a.rI);a.kI=function(){return{createValidator:function(b){return new a.Cg(b)}}}();a.ba.Yj(a.kc.VALIDATOR_TYPE_LENGTH,a.kI);a.$c={};a.$c.getConverterInstance=function(b){var d="",c={},e=null;b&&("object"===typeof b&&
(b instanceof a.Lc||b.parse&&"function"===typeof b.parse||b.format&&"function"===typeof b.format?e=b:(d=b.type,c=b.options||{})),e||(d=d||b)&&"string"===typeof d&&(b=a.ba.ji(d),e=b.createConverter(c)));return e};a.$c.Xj=function(b,d){a.i.Pd(d);var c="",e="",f=d.propertyName,m;"optionTypesMismatch"===b?(e=d.requiredPropertyName,m=d.requiredPropertyValueValid,c=a.da.C("oj-converter.optionTypesMismatch.summary",{propertyName:f,propertyValue:d.propertyValue,requiredPropertyName:e}),e=a.$c.Tp(e,m)):"optionTypeInvalid"===
b?(f=d.propertyName,m=d.propertyValueValid,c=a.da.C("oj-converter.optionTypeInvalid.summary",{propertyName:f}),e=a.$c.Tp(f,m)):"optionOutOfRange"===b?(c=a.da.C("oj-converter.optionOutOfRange.summary",{propertyName:f,propertyValue:d.propertyValue}),m=d.propertyValueValid,e=a.$c.Tp(f,m)):"optionValueInvalid"===b&&(c=a.da.C("oj-converter.optionValueInvalid.summary",{propertyName:f,propertyValue:d.propertyValue}),m=d.propertyValueHint,e=a.$c.Tp(f,m));return new a.sd(c,e)};a.$c.Tp=function(b,d){var c;
return d?("string"===typeof d?c="oj-converter.optionHint.detail":(c="oj-converter.optionHint.detail-plural",d=d.join(a.da.C("oj-converter.plural-separator"))),a.da.C(c,{propertyName:b,propertyValueValid:d})):""};a.$c.xV=function(){return""}});
//# sourceMappingURL=oj-modular.map