define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Ds=(0,D.v)();(0,D.ta)("DvtAxis",D.Ds);D.F.o(D.Ds,D.Zd,"DvtAxis");D.Ds.newInstance=function(b,c,d){var e=new D.Ds;e.Init(b,c,d);return e};D.wq=function(b){return(0,D.aB)(new D.Us,b)};D.Ds.getDefaults=D.wq;D.Ds.prototype.Init=function(b,c,d){D.Ds.u.Init.call(this,b,c,d);this.ff=new D.Us;this.Ca=new D.lt(this);this.Ca.nf(this);this.tS=D.n;this.Ja=D.q};D.Ds.prototype.Wd=function(b){b?this.Q=this.ff.Pg(b):this.Q||(this.Q=(0,D.gd)(this))};
D.Ds.prototype.Bz=function(b,c,d){this.Wd(b);this.xa().isLayout=D.n;this.M(D.q,c,d);b=this.D();this.xa().isLayout=D.t;this.qi();var e=this.xa().position;if("top"==e||"bottom"==e)return b.j<=d&&(this.tS=D.t),new D.se(c,window.Math.min(b.j,d));e=0<b.g?window.Math.max(1,0.1*b.g):0;b.g+e<=c&&(this.tS=D.t);return new D.se(window.Math.min(b.g+e,c),d)};D.Ds.prototype.M=function(b,c,d,e,f){this.Wd(b);this.rb=c;this.Lb=d;this.qi();e||(e=0);f||(f=0);D.Qs.M(this,new D.M(e,f,c,d))};D.Ds.prototype.render=D.Ds.prototype.M;
D.D=D.Ds.prototype;D.D.Vf=function(b,c){this===c&&this.Ya(b)};D.D.xa=(0,D.C)("Q");D.D.Va=(0,D.C)("Ca");D.D.getWidth=(0,D.C)("rb");D.D.getHeight=(0,D.C)("Lb");D.D.W=function(){this.Ca&&(this.Ca.Fs(this),this.Ca.W(),this.Ca=D.q);D.Ds.u.W.call(this)};D.D.HZ=(0,D.A)("Ja");D.D.Ji=function(){return new D.Ws(this)};D.Ds.prototype.getAutomation=D.Ds.prototype.Ji;
D.pr={};(0,D.ta)("DvtAxisConstants",D.pr);D.F.o(D.pr,D.F,"DvtAxisConstants");D.pr.Ax="tickLabel";D.pr.TICK_LABEL=D.pr.Ax;D.pr.Gp="title";D.pr.TITLE=D.pr.Gp;
D.Vs=(0,D.A)("Eg");D.F.o(D.Vs,D.F,"DvtAbstractAxisValueFormatter");D.Vs.prototype.Cq=(0,D.v)();
D.Ws=function(b){this.Yh=b;this.Ec=this.Yh.xa();this.Aca=this.Yh.Db};(0,D.ta)("DvtAxisAutomation",D.Ws);D.F.o(D.Ws,D.fb,"DvtAxisAutomation");D.Ws.prototype.er=function(b){if((b=(0,D.gb)(this.Yh.Va(),b))&&b instanceof D.Xq&&this.Ec.groups){b=b.Ml().id;for(var c=0;c<this.Ec.groups.length;c++)if(this.Ec.groups[c]==b)return"item["+c+"]"}return D.q};D.Ws.prototype.Qk=function(b){if(this.Aca instanceof D.Fs){var c=b.indexOf("["),d=b.indexOf("]");if(0<c&&0<d)return b=b.substring(c+1,d),this.Aca.Iw(this.Yh.e)[b].oa()}return D.q};
D.Ws.prototype.getDomElementForSubId=D.Ws.prototype.Qk;
D.Us=function(){this.Init({skyros:D.Ss,alta:D.Ts})};D.F.o(D.Us,D.db,"DvtAxisDefaults");D.Ts={axisLine:{lineColor:"#9E9E9E"},majorTick:{lineColor:"rgba(196,206,215,0.4)"},minorTick:{lineColor:"rgba(196,206,215,0.2)"},tickLabel:{style:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},titleStyle:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;")};
D.Ss={position:D.q,baselineScaling:"zero",axisLine:{lineColor:"#8A8DAC",lineWidth:1,rendered:"on"},majorTick:{lineColor:"rgba(138,141,172,0.4)",lineWidth:1,rendered:"auto",lineStyle:"solid"},minorTick:{lineColor:"rgba(138,141,172,0.20)",lineWidth:1,rendered:"off",lineStyle:"solid"},tickLabel:{scaling:"auto",style:new D.O("font-size: 11px; color: #333333;"),rotation:"auto",rendered:"on"},titleStyle:new D.O("font-size: 11px; color: #737373;"),startGroupOffset:0,endGroupOffset:0,layout:{gapRatio:1,titleGap:4},
_useBaselineColor:D.t,isLayout:D.t};
D.lt=function(b){this.Init(b.e,b.Vf,b);this.Yh=b};D.F.o(D.lt,D.Uc,"DvtAxisEventManager");D.lt.prototype.Ts=function(b,c){c instanceof D.Xq&&c.Ml()!=D.q&&this.ah(new D.ir(b,c.Ml()),this.Yh)};
D.Qs={};D.F.o(D.Qs,D.F,"DvtAxisRenderer");D.Qs.xsa=5;D.Qs.M=function(b,c){var d=b.xa(),e=(0,D.Rs)(b.e,d,c);b.Db=e;"off"==d.rendered||(0>=c.g||0>=c.j)||(b.HZ(c.clone()),D.Qs.xT(b,e,c),D.Qs.YL(b,e,c))};
D.Qs.xT=function(b,c,d){var e=b.xa();if(e.title&&(c=e.position,!("radial"==c||"tangential"==c)))if(e.isLayout&&"bottom"==c&&(c="top"),b="top"==c||"bottom"==c?D.Qs.Dda(b.Va(),b,e.title,e.titleStyle,d.g,d.j):D.Qs.Dda(b.Va(),b,e.title,e.titleStyle,d.j,d.g)){var f=b.Vb(),e=window.Math.ceil(e.layout.titleGap*e.layout.gapRatio);"top"==c?(b.fa(d.x+d.g/2-f.g/2),b.ra(d.y),d.y+=f.j+e,d.j-=f.j+e):"bottom"==c?(b.fa(d.x+d.g/2-f.g/2),b.ra(d.y+d.j-f.j),d.j-=f.j+e):"left"==c?(b.Ti(3*window.Math.PI/2),(0,D.wa)(b,
d.x,d.y+d.j/2+f.g/2),d.x+=f.j+e,d.g-=f.j+e):"right"==c&&(b.Ti(3*window.Math.PI/2),(0,D.wa)(b,d.x+d.g-f.j,d.y+d.j/2+f.g/2),d.g-=f.j+e)}};D.Qs.YL=function(b,c,d){var e=b.xa();"on"==e.tickLabel.rendered&&(e=e.position,"top"==e||"bottom"==e?D.Qs.jza(b,c,d):"tangential"==e?D.Qs.kza(b,c,d):D.Qs.lza(b,c,d))};
D.Qs.jza=function(b,c,d){for(var e=c.Iw(b.e),f=b.xa().isLayout,g=0,h=(0,D.ya)(b.e),j=0;j<e.length;j++){var m=e[j];if(m!=D.q){if(c.GV()){!f&&b.tS&&(m=D.Pb.Tb(m,d.j,d.g,b)?m:D.q);if(!m)continue;h?m.Mk():m.Gi();m.P(d.y)}else{if(D.Pb.Ni(m).j>d.j)continue;m.ip();m.ra(d.y)}b.Va().la(m,new D.Xq(m.dp,D.q,D.q,{type:D.pr.Ax,id:m.Ae()}));b.k(m);g=window.Math.max(g,D.Pb.Ni(m).j)}}d.y+=g;d.j-=g;c=c.Iw(b.e,1);f=0;if(c!=D.q)for(j=0;j<c.length;j++)m=c[j],m!=D.q&&!(D.Pb.Ni(m).j>d.j)&&(b.Va().la(m,new D.Xq(D.q,D.q,
D.q,{type:D.pr.Ax,id:m.Ae()})),e[j]!=D.q&&(f=e[j].Vb().g/2),h?m.fa(m.ea()+f):m.fa(m.ea()-f),m.ip(),m.ra(d.y),b.k(m))};
D.Qs.lza=function(b,c,d){var e=b.xa(),f=e.isLayout,g=e._alwaysAlignRight,h=e.position,e=(0,D.ya)(b.e),j="radial"==h&&e||f&&"left"==h||!g&&!f&&"right"==h,m;"radial"==h?(m=d.x+d.g/2,m+=D.Qs.xsa*(e?1:-1)):m=j?d.x:d.x+d.g;for(var g=function(e){!f&&b.tS&&(e=D.Pb.Tb(e,d.g,d.j,b)?e:D.q);if(e){b.Va().la(e,new D.Xq(e.dp,D.q,D.q,{type:D.pr.Ax,id:e.Ae()}));e.fa(m);j?e.Mk():e.Gi();if("radial"==h){var g=e.ga();e.ra(d.y+d.j/2-g);var o=e.D(),p=0.15*o.j,g=g+o.j/2>c.ala()&&"circle"==b.xa().polarGridShape?1:0.3,o=
window.DvtPathUtils.Uz(o.x-p,o.y,o.g+2*p,o.j,2,2,2,2),o=new D.Ra(b.e,o);o.na("#FFFFFF",g);b.k(o)}b.k(e)}},o=c.Iw(b.e),e=0;e<o.length;e++){var p=o[e];p!=D.q&&g(p)}o=c.Iw(b.e,1);if(o!=D.q)for(e=0;e<o.length;e++)p=o[e],p!=D.q&&g(p)};
D.Qs.kza=function(b,c,d){c=c.Iw(b.e);for(var e=0;e<c.length;e++){var f=c[e];if(f!=D.q){var g=f.Ae(),h=d.g/2-window.Math.abs(f.ea()),j=d.j/2-window.Math.abs(f.ga());D.Pb.Tb(f,h,j,b)&&(b.Va().la(f,new D.Xq(f.bg()?g:D.q,D.q,D.q,{type:D.pr.Ax,id:g})),f.G(d.x+d.g/2),f.P(d.y+d.j/2),b.k(f))}}};D.Qs.Dda=function(b,c,d,e,f,g){var h={type:D.pr.Gp,id:D.k};d=new D.Ya(c.e,d,0,0);d.Ga(e);return D.Pb.Tb(d,f,g,c)?(b.la(d,new D.Xq(d.dp,D.q,D.q,h)),d):D.q};
D.Ys=(0,D.v)();D.F.o(D.Ys,D.F,"DvtAxisInfo");D.Rs=function(b,c,d){return c.timeAxisType&&"disabled"!=c.timeAxisType?new D.Gs(b,c,d):(0,window.isNaN)(c.dataMin)&&(0,window.isNaN)(c.dataMax)?new D.Fs(b,c,d):new D.Xs(b,c,d)};D.D=D.Ys.prototype;
D.D.Init=function(b,c,d){this.e=b;this.sd=c.position;this.Pj=c._radius;"top"==this.sd||"bottom"==this.sd?(this.eh=d.x,this.Ah=d.x+d.g):"left"==this.sd||"right"==this.sd?(this.eh=d.y,this.Ah=d.y+d.j):"radial"==this.sd?(this.eh=0,this.Ah=this.Pj):"tangential"==this.sd&&((0,D.ya)(b)?(this.eh=2*window.Math.PI,this.Ah=0):(this.eh=0,this.Ah=2*window.Math.PI));this.xHa=this.zh=this.Uh=this.Ff=this.sf=this.Vd=this.Cc=D.q;this.fo=this.xo=0;c.leftBuffer==D.q&&(c.leftBuffer=window.Infinity);c.rightBuffer==D.q&&
(c.rightBuffer=window.Infinity);this.Q=c};D.D.K=(0,D.C)("Q");D.D.Iw=(0,D.ba)(D.q);D.D.pH=(0,D.ba)(D.q);D.D.xz=function(){return[]};D.D.OC=function(){return[]};D.D.Vj=(0,D.ba)(D.q);D.D.EC=(0,D.ba)(D.q);D.D.DC=(0,D.ba)(D.q);D.D.Nn=(0,D.ba)(D.q);D.D.Zc=(0,D.ba)(D.q);D.D.pz=(0,D.ba)(D.q);D.D.GV=(0,D.ba)(D.t);
D.D.xp=function(b,c,d){if("tangential"==this.sd){var e=16/180*window.Math.PI,f=1/180*window.Math.PI,g=0.5*(0,window.parseInt)(this.Q.tickLabel.style.A("font-size")),h=this.Pj+g;if(d<f||d>2*window.Math.PI-f)h+=g;b=new D.Ya(b,c,window.Math.round(h*window.Math.sin(d)),window.Math.round(-h*window.Math.cos(d)));d<f||window.Math.abs(d-window.Math.PI)<f||d>2*window.Math.PI-f?b.Af():d<window.Math.PI?b.Mk():b.Gi();window.Math.abs(d-window.Math.PI/2)<e||window.Math.abs(d-3*window.Math.PI/2)<e?b.Pe():d<window.Math.PI/
2||d>3*window.Math.PI/2?b.ww():b.ip()}else b=new D.Ya(b,c,d,d),b.Pe(),b.Af();b.Ga(this.Q.tickLabel.style);return b};D.bt=function(b,c,d,e){var f=!(0,D.Vb)()||1<(0,D.kb)();"radial"==b.sd?("polygon"==b.Q.polarGridShape?(e=D.Er.DH(0,0,b.Q._numGroups,e),c=new D.Ma(c,e)):c=new D.Yf(c,0,0,e),(0,D.Xb)(c)):"tangential"==b.sd?(c=new D.Lp(c,0,0,b.Pj*window.Math.sin(e),-b.Pj*window.Math.cos(e)),0.01>e%window.Math.PI/2&&f&&(0,D.wb)(c)):(c=new D.Lp(c,e,e,e,e),f&&(0,D.wb)(c));c.Z(d);c.ja(D.t);return c};
D.ft=function(b,c,d){if(!c||0>=c.length)return D.t;var e=(0,window.parseInt)(b.Q.tickLabel.style.A("font-size")),f=b instanceof D.Fs?0.3*e:1*e,g=b instanceof D.Fs?0.1*e:0.35*e,f=(e="left"==b.sd||"right"==b.sd||"radial"==b.sd)||b.GV()?g:f;b=(0,D.ya)(b.e);for(var h,j,m,o=0;o<c.length;o+=d+1)if(c[o]!=D.q)if(h==D.q||j==D.q)e?(h=c[o].y,j=c[o].y+c[o].j):(h=c[o].x,j=c[o].x+c[o].g);else{if(e){if(g=c[o].y,m=c[o].y+c[o].j,g>=h&&g-f<j||g<h&&m+f>h)return D.n}else if(g=c[o].x,m=c[o].x+c[o].g,!b&&g-f<j||b&&m+f>
h)return D.n;h=g;j=m}return D.t};D.at=function(b,c,d){for(var e=0,f=(0,D.ft)(b,d,e);f;)e++,f=(0,D.ft)(b,d,e);if(0<e){b=[];for(d=0;d<c.length;d+=e+1)b.push(c[d]);return b}return c};D.$s=function(b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];f==D.q?d.push(D.q):(f=f.Vb(c),d.push(f))}return d};
D.it=function(b,c,d,e){var f=[];"undefined"==typeof e&&(e=1);for(var g=0;g<c.length;g++){var h=c[g];if(h==D.q)f.push(D.q);else{d.k(h);var j=D.Pb.Ni(h),m=j.g*e,j=j.j;d.removeChild(h);h=b.GV()?new D.M(h.N()-j/2,h.L()-m/2,j,m):new D.M(h.ea()-m/2,h.ga()-j/2,m,j);f.push(h)}}return f};D.D=D.Ys.prototype;D.D.hV=(0,D.ba)(D.q);D.D.EW=(0,D.v)();D.D.nV=(0,D.ba)(D.q);D.D.FW=(0,D.v)();D.D.hN=(0,D.ba)(D.q);D.D.mV=(0,D.ba)(D.q);D.D.Fw=(0,D.C)("sf");D.D.Ew=(0,D.C)("Ff");D.D.ws=(0,D.C)("Cc");D.D.Nw=(0,D.C)("Vd");
D.D.l6=(0,D.C)("Uh");D.D.k6=(0,D.C)("zh");D.D.Jw=(0,D.ba)(0);D.D.ala=(0,D.C)("Ah");D.D.vV=(0,D.C)("xo");D.D.WU=(0,D.C)("fo");
D.Xs=function(b,c,d){this.Init(b,c,d)};D.F.o(D.Xs,D.Ys,"DvtDataAxisInfo");D.D=D.Xs.prototype;
D.D.Init=function(b,c,d){D.Xs.u.Init.call(this,b,c,d);"top"==this.sd||"bottom"==this.sd?("off"!=c.tickLabel.rendered&&"off"!=c.rendered&&(this.xo=window.Math.max(10-c.leftBuffer,0),this.fo=window.Math.max(10-c.rightBuffer,0)),(0,D.ya)(b)?(this.Di=this.Ah-this.fo,this.Gk=this.eh+this.xo):(this.Di=this.eh+this.xo,this.Gk=this.Ah-this.fo)):"tangential"==this.sd||"radial"==this.sd?(this.Di=this.eh,this.Gk=this.Ah):(this.Di=this.Ah,this.Gk=this.eh);this.sf=c.min;this.Ff=c.max;this.Cc=c.viewportMin==D.q?
this.sf:c.viewportMin;this.Vd=c.viewportMax==D.q?this.Ff:c.viewportMax;this.mh=c.step;this.QB=c.minorStep;this.t2=c.minStep;this.ih=D.q;c.tickLabel!=D.q&&(this.ih=c.tickLabel.converter);this.Uh=c.dataMin;this.zh=c.dataMax;b="zero"==this.Q.baselineScaling;c="on"==this.Q._continuousExtent;b&&(this.Uh=window.Math.min(0,this.Uh),this.zh=window.Math.max(0,this.zh));d=(0,D.Zs)(this,this.sf!=D.q?this.sf:this.Uh,this.Ff!=D.q?this.Ff:this.zh);this.Uh==this.zh&&(0==this.Uh?this.zh+=5*d:(this.Uh-=3*d,this.zh+=
2*d));if(this.sf==D.q)if(b&&0<=this.Uh)this.sf=0;else if(c)this.sf=this.Uh-0.1*(this.zh-this.Uh),0<=this.Uh&&(this.sf=window.Math.max(this.sf,0));else if(!b&&this.Ff!=D.q)for(this.sf=this.Ff;this.sf>this.Uh;)this.sf-=d;else this.sf=window.Math.floor(this.Uh/d)*d;if(this.Ff==D.q)if(b&&0>=this.zh)this.Ff=0;else if(c)this.Ff=this.zh+0.1*(this.zh-this.Uh),0>=this.zh&&(this.Ff=window.Math.min(this.Ff,0));else if(b)this.Ff=(window.Math.floor(this.zh/d)+1)*d;else for(this.Ff=this.sf;this.Ff<=this.zh;)this.Ff+=
d;this.Ff==this.sf&&(this.Ff=100,this.sf=0,d=(this.Ff-this.sf)/10);this.Cc==D.q&&(this.Cc=this.sf);this.Vd==D.q&&(this.Vd=this.Ff);if(this.Cc!=this.sf||this.Vd!=this.Ff)d=(0,D.Zs)(this,this.Cc,this.Vd);this.mh=this.mh?this.mh:d;this.t2!=D.q&&this.mh<this.t2&&(this.mh=this.t2);this.UF=(this.Vd-this.AH())/this.mh;this.QB!=D.q&&2<=this.mh/this.QB?this.ZF=this.mh/this.QB:(this.ZF=2,this.QB=this.mh/this.ZF)};
D.D.AH=function(){return"zero"==this.Q.baselineScaling||"on"==this.Q._continuousExtent&&this.Q.min==D.q?window.Math.ceil(this.Cc/this.mh)*this.mh:window.Math.ceil((this.Cc-this.sf)/this.mh)*this.mh+this.sf};
D.D.Iw=function(b,c){if(c&&0<c)return D.q;var d=[],e=[],e=b.Sc,f="tangential"==this.sd;this.Q.tickLabel&&this.Q.tickLabel.scaling&&(this.bQ=new D.Aq(this.Cc,this.Vd,this.mh,this.Q.tickLabel.scaling,this.Q.tickLabel.autoPrecision?this.Q.tickLabel.autoPrecision:"on"));for(var g=0;g<=this.UF;g++){var h=g*this.mh+this.AH();if(!(f&&h==this.Vd)){var j=this.Ho(h),h=this.Zc(h),j=this.xp(b,j,h);d.push(j)}}f||(e=(0,D.$s)(d,e),d=(0,D.at)(this,d,e));return d};
D.D.pH=function(b){var c=this.Q.axisLine;return"on"==c.rendered?(c=new D.Hb(c.lineColor,1,c.lineWidth),(0,D.bt)(this,b,c,this.Gk)):D.q};
D.D.xz=function(b){var c=[],d,e,f=this.Q.majorTick;if("off"==f.rendered)return c;var g=new D.Hb(f.lineColor,1,f.lineWidth);f.lineStyle&&g.X((0,D.Gr)(f.lineStyle));f=g.clone();if(this.Q._useBaselineColor){var h=D.U.C(this.Q.axisLine.lineColor,0.75);f.Hs(h)}for(h=0;h<=this.UF;h++)d=h*this.mh+this.AH(),"tangential"==this.sd&&d==this.Vd||(e=0==d?f:g,d=this.Zc(d),e=(0,D.bt)(this,b,e,d),c.push(e));return c};
D.D.OC=function(b){var c=[],d,e=this.Q.minorTick;if("on"!=e.rendered)return c;var f=new D.Hb(e.lineColor,1,e.lineWidth);e.lineStyle&&f.X((0,D.Gr)(e.lineStyle));for(e=-1;e<=this.UF;e++)for(var g=e*this.mh+this.AH(),h=1;h<this.ZF;h++){d=g+h*this.QB;if(d>this.Vd)break;d<this.Cc||(d=this.Zc(d),d=(0,D.bt)(this,b,f,d),c.push(d))}return c};D.D.Vj=function(b){return b<this.Cc||b>this.Vd?D.q:this.Zc(b)};
D.D.EC=function(b){var c=window.Math.min(this.Di,this.Gk),d=window.Math.max(this.Di,this.Gk);b<c?b=c:b>d&&(b=d);return this.Nn(b)};D.D.DC=function(b){b<this.Cc?b=this.Cc:b>this.Vd&&(b=this.Vd);return this.Zc(b)};D.D.Nn=function(b){return this.Cc+(b-this.Di)/(this.Gk-this.Di)*(this.Vd-this.Cc)};D.D.Zc=function(b){return this.Di+(b-this.Cc)/(this.Vd-this.Cc)*(this.Gk-this.Di)};D.D.pz=function(){var b=0;0>this.Vd?b=this.Vd:0<this.Cc&&(b=this.Cc);return this.Vj(b)};
D.D.Ho=function(b){if(this.ih&&(this.ih.getAsString||this.ih.format)){if(this.bQ)return this.bQ.Cq(b,this.ih);if(this.ih.getAsString)return this.ih.getAsString(b);if(this.ih.format)return this.ih.format(b)}else{if(this.bQ)return this.bQ.Cq(b);var c=window.Math.log(this.mh)/window.Math.log(10),c=window.Math.max(window.Math.ceil(-c),0);return b.toFixed(c)}};
D.Zs=function(b,c,d){if(b.mh)return b.mh;b=d-c;if(0==b)return 0==c?10:window.Math.pow(10,window.Math.floor(window.Math.log(c)/window.Math.LN10)-1);c=window.Math.log(b)/window.Math.log(10);c=window.Math.pow(10,window.Math.ceil(c)-2);b=window.Math.round(b/c);return(10<=b&&14>=b?2:15<=b&&19>=b?3:20<=b&&24>=b?4:25<=b&&45>=b?5:46<=b&&80>=b?10:20)*c};D.D=D.Xs.prototype;D.D.hV=(0,D.C)("UF");D.D.EW=function(b){this.UF=b;this.mh=(this.Vd-this.Cc)/this.UF};D.D.nV=(0,D.C)("ZF");
D.D.FW=function(b){this.ZF=b;this.QB=this.mh/this.ZF};D.D.hN=(0,D.C)("mh");D.D.mV=(0,D.C)("QB");D.D.Jw=function(){return(this.Ff-this.sf)/64};D.D.vV=function(){return("top"==this.sd||"bottom"==this.sd)&&(0,D.ya)(this.e)?this.fo:this.xo};D.D.WU=function(){return("top"==this.sd||"bottom"==this.sd)&&(0,D.ya)(this.e)?this.xo:this.fo};
D.Fs=function(b,c,d){this.Init(b,c,d)};D.F.o(D.Fs,D.Ys,"DvtGroupAxisInfo");
D.Fs.prototype.Init=function(b,c,d){D.Fs.u.Init.call(this,b,c,d);b=(0,D.ya)(b);if(("top"==this.sd||"bottom"==this.sd)&&b)d=this.eh,this.eh=this.Ah,this.Ah=d;this.Ht=c.groups;d=0<c.endGroupOffset?(0,window.Number)(c.endGroupOffset):0;var e=0<c.startGroupOffset?(0,window.Number)(c.startGroupOffset):0;this.Uh=0;this.zh=this.Ht.length-1;this.sf=c.min==D.q?this.Uh-e:c.min;this.Ff=c.max==D.q?this.zh+d:c.max;this.Cc=c.viewportMin==D.q?this.sf:c.viewportMin;this.Vd=c.viewportMax==D.q?this.Ff:c.viewportMax;
var f=(0,D.gt)(this,c.viewportStartGroup),g=(0,D.gt)(this,c.viewportEndGroup);-1!=f&&(this.Cc=f-e);-1!=g&&(this.Vd=g+d);this.cja=b?c.rightBuffer:c.leftBuffer;this.kea=b?c.leftBuffer:c.rightBuffer;this.Cfa=D.t;this.dza=c._renderGridAtLabels;this.Vv=D.q};D.jt=function(b,c,d,e){var f,g=(0,D.ya)(b.e);b.Cfa=D.n;(0,D.ht)(b,e,e,c);for(var h=0;h<c.length;h++)e=c[h],e!=D.q&&(f=e.ea(),e.fa(0),e.ra(0),g?e.Ti(window.Math.PI/2):e.Ti(3*window.Math.PI/2),e.G(f));d=(0,D.it)(b,c,d);return(0,D.at)(b,c,d)};
D.Fs.prototype.GV=(0,D.C)("Cfa");D.ht=function(b,c,d,e){c=window.Math.max(c-b.cja,0);d=window.Math.max(d-b.kea,0);var f=(0,D.ya)(b.e);b.eh+=(c-b.xo)*(f?-1:1);b.Ah-=(d-b.fo)*(f?-1:1);for(f=0;f<e.length;f++){var g=e[f];g&&g.fa(b.Vj(f))}b.xo=c;b.fo=d};D.D=D.Fs.prototype;D.D.Iw=function(b,c){if(c&&0<c)return D.q;this.Vv||(this.Vv=this.Z0(b));return this.Vv};
D.D.Z0=function(b){for(var c=[],d=b.Sc,e="top"==this.sd||"bottom"==this.sd,f=(0,D.ya)(b),g=this.Ht.length,h,j,m=0;m<g;m++){var o=(0,D.Uq)(this,m),p=this.Vj(m);p!=D.q?(j=this.xp(b,o,p),c.push(j),h||(h=j)):c.push(D.q)}if("tangential"==this.sd)return c;b=h.Vb();e&&(this.Q._startOverflow!=D.q&&this.Q._endOverflow!=D.q?(g=this.Q._startOverflow,f=this.Q._endOverflow):(h=j.Vb(),g=f?b.g+b.x-this.eh:this.eh-b.x,f=f?this.Ah-h.x:h.g+h.x-this.Ah),(g>this.cja||f>this.kea)&&(0,D.ht)(this,g,f,c));f=[];f=(0,D.it)(this,
c,d,0.3);g=(0,D.it)(this,c,d);if(!(0,D.ft)(this,g,0))return c;if(e){if("auto"==this.Q.tickLabel.rotation){if((0,D.ft)(this,f,0))return(0,D.jt)(this,c,d,b.j/2);f=(0,D.$s)(c,d);return(0,D.ft)(this,f,0)?(0,D.jt)(this,c,d,b.j/2):c}f=(0,D.$s)(c,d);return(0,D.at)(this,c,f)}return(0,D.at)(this,c,g)};D.D.pH=function(b){var c=this.Q.axisLine;return"on"==c.rendered?(c=new D.Hb(c.lineColor,1,c.lineWidth),(0,D.bt)(this,b,c,0)):D.q};
D.D.xz=function(b){var c=[],d,e=this.Q.majorTick,f=new D.Hb(e.lineColor,1,e.lineWidth);e.lineStyle&&f.X((0,D.Gr)(e.lineStyle));e=e.rendered;if("on"==e||"auto"==e&&"tangential"==this.sd)for(var e=this.Ht.length,g=0;g<e;g++){if(this.dza)d=this.Vj(g);else if(this.Vj(g+0.5))d=this.Vj(g+0.5);else continue;d!=D.q&&(d=(0,D.bt)(this,b,f,d),c.push(d))}return c};D.D.Vj=function(b){return b<this.Cc||b>this.Vd?D.q:this.Zc(b)};
D.D.EC=function(b){var c=window.Math.min(this.eh,this.Ah),d=window.Math.max(this.eh,this.Ah);b<c?b=c:b>d&&(b=d);return this.Nn(b)};D.D.DC=function(b){b<this.Cc?b=this.Cc:b>=this.Vd&&(b=this.Vd);return this.Zc(b)};D.D.Nn=function(b){return this.Cc+(b-this.eh)/((this.Ah-this.eh)/(this.Vd-this.Cc))};D.D.Zc=function(b){return this.eh+(b-this.Cc)*((this.Ah-this.eh)/(this.Vd-this.Cc))};D.Uq=function(b,c){c=window.Math.round(c);if(0>c||c>=b.Ht.length)return D.q;var d=b.Ht[c];d&&d.name&&(d=d.name);return d};
D.gt=function(b,c){if(c==D.q)return-1;for(var d=-1,e=0;e<b.Ht.length;e++)if(c==(0,D.Uq)(b,e)){d=e;break}return d};D.Fs.prototype.Jw=(0,D.ba)(1);
D.Aq=function(b,c,d,e,f){this.Eg=new D.wc;this.Init(b,c,d,e,f)};D.F.o(D.Aq,D.Vs,"DvtLinearScaleAxisValueFormatter");
D.Aq.prototype.Init=function(b,c,d,e,f){this.Hia={};this.$r=[];this.mea={};var g=function(b,c,d){var e;this.Eg&&d&&(e=(0,D.ec)(this.Eg,d,D.q));d={Gs:c,vFa:e};this.Hia[b]=d;this.$r.push(d);this.mea[c]=d};g.call(this,"none",0);g.call(this,"thousand",3,"SCALING_SUFFIX_THOUSAND");g.call(this,"million",6,"SCALING_SUFFIX_MILLION");g.call(this,"billion",9,"SCALING_SUFFIX_BILLION");g.call(this,"trillion",12,"SCALING_SUFFIX_TRILLION");g.call(this,"quadrillion",15,"SCALING_SUFFIX_QUADRILLION");this.$r.sort(function(b,
c){return b.Gs<c.Gs?-1:b.Gs>c.Gs?1:0});var h=D.t,j,m,g=D.t;"off"!==f&&(g=D.n);e||(e="auto");if(e=this.Hia[e])m=e.Gs;"number"!==typeof m&&(h=D.n);if(h)if(h=window.Math.max(window.Math.abs(b),window.Math.abs(c)),h=(0,D.kt)(h),m=0,h<=this.$r[0].Gs)m=this.$r[0].Gs;else if(h>=this.$r[this.$r.length-1].Gs)m=this.$r[this.$r.length-1].Gs;else for(e=this.$r.length-1;0<=e;e--)if(this.$r[e].Gs<=h){m=this.$r[e].Gs;break}g===D.n&&(0==d&&b==c?(b=m-(0,D.kt)(c),j=0>=b?3+b:window.Math.max(b,4)):j=window.Math.max(m-
(0,D.kt)(d),0));this.pAa=g;this.Q3=m;this.u0=j};
D.Aq.prototype.Cq=function(b,c){var d=(0,window.parseFloat)(b);if((0,window.isNaN)(d))return b;var e;if(0<this.Q3){for(e=0;e<this.Q3;e++)d/=10;e=this.mea[this.Q3].vFa}if(c&&c.getAsString)d=c.getAsString(d);else if(c&&c.format)d=c.format(d);else if(this.pAa&&!(0,window.isNaN)((0,window.parseFloat)(d))&&(d=(0,window.parseFloat)((new window.Number(d)).toFixed(this.u0)),d=""+d,0<this.u0)){-1==d.indexOf(".")&&(d+=".");for(var f=d.substring(d.indexOf(".")+1).length;f<this.u0;)d+="0",f++}"string"===typeof e&&
(d+=e);return d};D.kt=function(b){b=0<=b?b:-b;var c=0;if(1E-15>b)return 0;if(window.Infinity==b)return window.Number.MAX_VALUE;if(10<=b)for(;10<=b;)c+=1,b/=10;else if(1>b)for(;1>b;)c-=1,b*=10;return c};
D.Gs=function(b,c,d){this.Init(b,c,d)};D.F.o(D.Gs,D.Ys,"DvtTimeAxisInfo");
D.Gs.prototype.Init=function(b,c,d){D.Gs.u.Init.call(this,b,c,d);"top"==this.sd||"bottom"==this.sd?(!c._isOverview&&"on"==c.tickLabel.rendered&&(this.xo=window.Math.max(10-c.leftBuffer,0),this.fo=window.Math.max(10-c.rightBuffer,0)),(0,D.ya)(b)?(this.Di=this.Ah-this.fo,this.Gk=this.eh+this.xo):(this.Di=this.eh+this.xo,this.Gk=this.Ah-this.fo)):(this.Di=this.eh,this.Gk=this.Ah);this.ih=D.q;c.tickLabel!=D.q&&(this.ih=c.tickLabel.converter);this.Ht=c.groups;this.Uh=c.dataMin;this.zh=c.dataMax;this.pr=
0<this.Ht.length?(this.zh-this.Uh)/(this.Ht.length-1):0;this.fu=c.step;b=0<c.endGroupOffset?c.endGroupOffset*this.pr:0;d=0<c.startGroupOffset?c.startGroupOffset*this.pr:0;this.sf=c.min!=D.q?c.min:this.Uh-d;this.Ff=c.max!=D.q?c.max:this.zh+b;this.Cc=c.viewportMin==D.q?this.sf:c.viewportMin;this.Vd=c.viewportMax==D.q?this.Ff:c.viewportMax;c.viewportStartGroup!=D.q&&(this.Cc=c.viewportStartGroup-d);c.viewportEndGroup!=D.q&&(this.Vd=c.viewportEndGroup+b);this.pja=0;this.J4=this.Vd-this.Cc;this.AS=this.KB=
this.iga=this.Vv=D.q;this.G1=D.n;c=new D.wc;this.Am=[(0,D.ec)(c,"MONTH_SHORT_JANUARY",D.q),(0,D.ec)(c,"MONTH_SHORT_FEBRUARY",D.q),(0,D.ec)(c,"MONTH_SHORT_MARCH",D.q),(0,D.ec)(c,"MONTH_SHORT_APRIL",D.q),(0,D.ec)(c,"MONTH_SHORT_MAY",D.q),(0,D.ec)(c,"MONTH_SHORT_JUNE",D.q),(0,D.ec)(c,"MONTH_SHORT_JULY",D.q),(0,D.ec)(c,"MONTH_SHORT_AUGUST",D.q),(0,D.ec)(c,"MONTH_SHORT_SEPTEMBER",D.q),(0,D.ec)(c,"MONTH_SHORT_OCTOBER",D.q),(0,D.ec)(c,"MONTH_SHORT_NOVEMBER",D.q),(0,D.ec)(c,"MONTH_SHORT_DECEMBER",D.q)]};
D.zq=function(b,c,d){var e=D.q,f=D.q,g="left"==b.sd||"right"==b.sd;if(b.ih&&b.ih.getAsString)e=b.ih.getAsString(c);else if(b.ih&&b.ih.format)e=b.ih.format(c);else if(31536E6<=b.fu)e=(0,D.ct)(b,c,D.t,D.t,D.n);else if(31536E6<=b.J4||24192E5<=b.fu){if(d==D.q||d.getMonth()!=c.getMonth())e=(0,D.ct)(b,c,D.t,D.n,D.t);if(d==D.q||d.getYear()!=c.getYear())f=(0,D.ct)(b,c,D.t,D.t,D.n)}else if(24192E5<=b.J4||864E5<=b.fu){if(d==D.q||d.getDate()!=c.getDate())e=(0,D.ct)(b,c,D.n,D.t,D.t);d==D.q||d.getYear()!=c.getYear()?
f=(0,D.ct)(b,c,D.t,D.n,D.n):d.getMonth()!=c.getMonth()&&(f=(0,D.ct)(b,c,D.t,D.n,D.t))}else{if(36E5<=b.J4||6E4<=b.fu){if(d==D.q||d.getHours()!=c.getHours()||d.getMinutes()!=c.getMinutes())e=(0,D.dt)(b,c,D.t)}else if(d==D.q||d.getSeconds()!=c.getSeconds())e=(0,D.dt)(b,c,D.n);if(g){if(d==D.q||d.getDate()!=c.getDate())f=(0,D.ct)(b,c,D.n,D.n,D.t)}else d==D.q||d.getYear()!=c.getYear()?f=(0,D.ct)(b,c,D.n,D.n,D.n):d.getMonth()!=c.getMonth()?f=(0,D.ct)(b,c,D.n,D.n,D.t):d.getDate()!=c.getDate()&&(f=(0,D.ct)(b,
c,D.n,D.t,D.t))}return[e,f]};D.ct=function(b,c,d,e,f){var g=c.getFullYear(),h;h=b.Am&&12<=b.Am.length?b.Am[c.getMonth()]:c.toString().split(" ")[1];c=c.getDate();if(b.Am&&17<b.Am.length){var j=b.Am[17],g=g+b.Am[16];c+=j}j="DMY";b.Am&&15<b.Am.length&&(j=b.Am[15]);b="";for(var m=0;m<j.length;m++)d&&"D"==j[m]?b+=c+" ":e&&"M"==j[m]?b+=h+" ":f&&"Y"==j[m]&&(b+=g+" ");return 0<b.length?b.slice(0,b.length-1):b};
D.dt=function(b,c,d){var e=c.getHours(),f=c.getMinutes();c=c.getSeconds();var g="",h="",j=D.t;b.Am!=D.q&&14<b.Am&&(g=b.Am[window.DvtTimeAxis.aHa],h=b.Am[window.DvtTimeAxis.CHa],j="t"==b.Am[14]);b=""!=g&&""!=h;var m;b&&(m=h,12<e?(e-=12,m=h):0==e?(m=g,e=12):12>e&&(m=g));e=(10>e?"0"+e:""+e)+":"+(10>f?"0"+f:""+f);d&&(e+=":"+(10>c?"0"+c:""+c));return b?j?m+" "+e:e+" "+m:e};
D.et=function(b,c,d){var e=(new window.Date((new window.Date(b)).getFullYear(),0,1,0,0,0)).getTime();b=e+window.Math.ceil((b-e)/d)*d;for(e=[];b<=c;)e.push(b),b+=d;return e};D.D=D.Gs.prototype;
D.D.Z0=function(b){var c=[],d=[],e=[],f=[],g=D.q,h=0,j=0,j=b.Sc,m=(0,D.ya)(b),o="left"==this.sd||"right"==this.sd,p="off"!=this.Q.zoomAndScroll;if(p)var r=D.n;var u=0;o&&(0,D.Ca)()&&(u=0.2*(0,window.parseInt)(this.Q.tickLabel.style.A("font-size")));var w=[],h=0;this.fu!=D.q?w=(0,D.et)(this.Cc,this.Vd,this.fu):"mixedFrequency"==this.Q.timeAxisType?(this.fu=316224E5<=this.pr?316224E5:26784E5<=this.pr?26784E5:864E5<=this.pr?864E5:36E5<=this.pr?36E5:6E4<=this.pr?6E4:1E3,w=(0,D.et)(this.Cc,this.Vd,this.fu),
h=window.Math.floor(this.pr/this.fu)-1):(w=this.Ht,this.fu=this.pr);for(var z=0;z<w.length;z++){window.time=w[z];var B=this.Vj(window.time);if(B!=D.q){var I=new window.Date(window.time+this.pja),E=(0,D.zq)(this,I,g),g=E[0],E=E[1];g!=D.q?(E!=D.q?c.push(this.xp(b,g,B+u)):c.push(this.xp(b,g,B)),e.push(B)):(c.push(D.q),e.push(D.q));p&&r&&(B=this.Cc?this.Vj(this.Cc):B,r=D.t);E!=D.q?(g=D.q,g=E!=D.q?this.xp(b,E,B-u):this.xp(b,E,B),f.push(B),o||(m?g.Gi():g.Mk()),d.push(g),this.G1=D.t):(d.push(D.q),f.push(D.q));
g=I}}b=c;m=(0,D.$s)(c,j);u=h;h=[];for(r=0;r<m.length;r++)m[r]!=D.q&&h.push(m[r]);m=u;for(r=(0,D.ft)(this,h,m);r;)m++,r=(0,D.ft)(this,h,m);h=h.length;if(0<m)for(r=u=0;r<b.length;r++)b[r]!=D.q&&(0!=u%(m+1)&&(b[r]=D.q,h--),u++);b=d;j=(0,D.$s)(d,j);if(!j||0>=j.length)j=D.t;else{for(var r="left"==this.sd||"right"==this.sd,m=(0,window.parseInt)(this.Q.tickLabel.style.A("font-size")),m=r?0.1*m:0.3*m,u=0,J,L,B=0;B<j.length;B++)j[B]!=D.q&&(r?(w=j[B].y,z=j[B].y+j[B].j):(w=j[B].x,z=j[B].x+j[B].g),J!=D.q&&(L!=
D.q&&(w>=J&&w-m<L||w<J&&z+m>J))&&(b[B]=D.q),b[B]!=D.q&&(J=w,L=z,u++));j=u}if(!p&&1<j&&h<=1.5*j){c=d;d=D.q;for(p=0;p<c.length;p++)c[p]!=D.q&&c[p].Af()}if(o&&d!=D.q){var o=c,p=d,N=0.1*(0,window.parseInt)(this.Q.tickLabel.style.A("font-size"));J=function(b,c){return c.y>=b.y&&c.y-N<b.y+b.j||c.y<b.y&&c.y+c.j+N>b.y?D.n:D.t};j=D.q;b=D.t;for(L=0;L<o.length;L++)if(o[L]&&p[L])if(o[L].ip(),p[L].ww(),j&&J(j,o[L].Vb())){b=D.n;break}else if(o[L+1]&&J(o[L].Vb(),o[L+1].Vb())){b=D.n;break}else j=p[L].Vb();else if(o[L]||
p[L])if(r=o[L]?o[L]:p[L],j&&J(j,r.Vb())){b=D.n;break}else j=r.Vb();if(b){r=b=j=D.q;for(L=0;L<o.length;L++)p[L]?(o[L]=D.q,p[L].Pe(),h=p[L].Vb(),b&&J(b,h)&&(o[j]=D.q),r=h):o[L]&&(h=o[L].Vb(),r&&J(r,h)?o[L]=D.q:(b=h,j=L))}}this.Vv=c;this.iga=d;this.KB=e;this.AS=f};D.D.Iw=function(b,c){if(c&&1<c)return D.q;this.Vv||this.Z0(b);return 1==c?this.iga:this.Vv};D.D.pH=function(b){var c=this.Q.axisLine;return"on"==c.rendered?(c=new D.Hb(c.lineColor,1,c.lineWidth),(0,D.bt)(this,b,c,10)):D.q};
D.D.xz=function(b){var c=this.Q.majorTick;if("on"!=c.rendered)return[];var d=[];if(this.G1)for(var e=0;e<this.KB.length;e++)this.KB[e]!=D.q&&this.Vv[e]!=D.q&&d.push(this.KB[e]);else for(e=0;e<this.AS.length;e++)this.AS[e]!=D.q&&d.push(this.AS[e]);var f=new D.Hb(c.lineColor,1,c.lineWidth);c.lineStyle&&f.X((0,D.Gr)(c.lineStyle));c=[];for(e=0;e<d.length;e++)d[e]>=this.Di&&d[e]<=this.Gk&&c.push((0,D.bt)(this,b,f,d[e]));return c};
D.D.OC=function(b){var c=this.Q.minorTick;if("on"!=c.rendered||this.G1)return[];for(var d=[],e=0;e<this.KB.length;e++)this.KB[e]!=D.q&&this.Vv[e]!=D.q&&d.push(this.KB[e]);var f=new D.Hb(c.lineColor,1,c.lineWidth);c.lineStyle&&f.X((0,D.Gr)(c.lineStyle));c=[];for(e=0;e<d.length;e++)d[e]>=this.Di&&d[e]<=this.Gk&&c.push((0,D.bt)(this,b,f,d[e]));return c};D.D.Vj=function(b){return b<this.Cc||b>this.Vd?D.q:this.Zc(b)};
D.D.EC=function(b){var c=window.Math.min(this.Di,this.Gk),d=window.Math.max(this.Di,this.Gk);b<c?b=c:b>d&&(b=d);return this.Nn(b)};D.D.DC=function(b){b<this.Cc?b=this.Cc:b>this.Vd&&(b=this.Vd);return this.Zc(b)};D.D.Nn=function(b){return this.Cc+(b-this.Di)/(this.Gk-this.Di)*(this.Vd-this.Cc)};D.D.Zc=function(b){return this.Di+(b-this.Cc)/(this.Vd-this.Cc)*(this.Gk-this.Di)};D.D.ZU=function(){return window.Math.abs(this.Zc(this.Cc+this.pr)-this.Zc(this.Cc))};D.D.Jw=(0,D.C)("pr");
D.D.vV=function(){return("top"==this.sd||"bottom"==this.sd)&&(0,D.ya)(this.e)?this.fo:this.xo};D.D.WU=function(){return("top"==this.sd||"bottom"==this.sd)&&(0,D.ya)(this.e)?this.xo:this.fo};
});