define(['./DvtToolkit', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.SD=(0,D.v)();(0,D.ta)("DvtBaseTreeView",D.SD);D.F.o(D.SD,D.Zd,"DvtBaseTreeView");D.D=D.SD.prototype;D.D.Init=function(b,c,d){D.SD.u.Init.call(this,b,c,d);this.Ca=this.WD(this,b,this.Ya,this);this.Ca.nf(this);this.Ak=new D.sl(b);this.I0=new D.wt(this);(0,D.wf)(this.Ca,this.Ak);this.fY=this.ya=D.q;this.bfa=D.t;this.BL=D.q};
D.D.M=function(b,c,d){this.rb=c;this.Lb=d;this.Ca&&this.Ca.sc();this.Um&&!b&&(b=this.fY);b&&(this.fY=b);b&&(c=this.Zu(b),this.CI(c));d=new D.M(0,0,this.rb,this.Lb);this.po(d);c=new D.G(this.e);this.k(c);this.D4&&(this.OZ=new D.Jf(this.e,this.Ca),this.OZ.uG=D.n);this.ti(c,d);this.Um&&(this.RW=D.n,this.Um.stop());var e=new D.M(0,0,this.rb,this.Lb);d=D.t;if(this.ha){if(this.AI&&b)if(D.ad.isSupported(this.AI))this.Um=D.ad.rz(this.e,this.AI,this.ha,c,e,this.RD),d=D.n;else if(this.JL&&"auto"==this.AI){this.aj=
this.AX();this.k(this.aj);var e=new D.rt(this.e,this.aj),f=this.JL,g=this.Pa,h=this.US,j=this.Ox;e.NJ=D.t;e.JL=f;e.US=h;(0,D.st)(j,f)||(0,D.st)(h,g)?(e.NJ=D.n,h=(0,D.zt)(f),j=(0,D.zt)(g),h.push(f),j.push(g),(0,D.Dd)(e,h,j)):(0,D.Dd)(e,[f],[g]);this.Um=e.Dq()}}else this.Um=this.CX(c,e);this.US=this.JL=D.q;this.Um&&(this.Ca.Fs(this),this.Um.qd(this.Dp,this),this.Um.play());d?this.Ik=this.ha:this.ha&&this.removeChild(this.ha);this.ha=c;b?(this.mG(),(0,D.IE)(this,!this.Um)):this.QY()};D.D.Zu=(0,D.ba)(D.q);
D.D.po=(0,D.v)();D.D.ti=(0,D.v)();D.VD=function(b,c){var d=new D.H(b.e,0,0,b.rb,b.Lb);(0,D.Xb)(d);c.k(d)};D.TD=function(b,c){if(b.Ox&&0<b.Ox.length){var d=b.Pa?b.Pa.vh():D.q;b.rl&&(0,D.Vi)(b.Ca,b.rl.Nc());b.rl=D.ot.M(b,c,b.Ox,d);(0,D.Wi)(b.Ca,b.rl.Nc())}else b.rl&&(0,D.Vi)(b.Ca,b.rl.Nc()),b.rl=D.q};D.UD=function(b,c){var d=D.q;if(b.hga&&b.ZZ)for(var e=0;e<b.ZZ.length;e++){var f=b.ZZ[e];if(f.id==b.hga){d=f.ou;break}}if(b.Xia||b.mda||d)b.ya=D.pt.M(b,c,b.oh.legendSize,b.oh.legendColor,b.Xia,b.mda,d)};
D.XD=function(b,c){if(b.Sp){var d=new D.Ya(b.e,b.Sp,b.rb/2,b.Lb/2);d.Af();d.Pe();D.Pb.Tb(d,b.rb-4,b.Lb-4,b);c.k(d)}};D.WD=function(b){return b.Pa&&0<b.Pa.rc()};D.D=D.SD.prototype;D.D.CX=function(b,c){return D.ad.isSupported(this.QW)?D.ad.xH(this.e,this.QW,b,c,this.RD):D.q};D.D.Dp=function(){this.aj&&(this.removeChild(this.aj),this.aj=D.q);this.Ik&&(this.removeChild(this.Ik),this.Ik=D.q);this.RW=D.t;this.Um=D.q;this.Ca.nf(this);(0,D.IE)(this,D.n)};D.D.AX=function(){return new D.G(this.e)};D.D.mx=function(b){return new D.kc(b)};
D.D.WD=function(b,c,d,e){return new D.pc(b,c,d,e)};D.D.o$=(0,D.aa)();D.D.Va=(0,D.C)("Ca");D.JE=function(b,c){var d=c,e=b.ib();if(e)for(var f=0;f<e.length;f++)var g=(0,D.JE)(e[f],c+1),d=window.Math.max(d,g);return d};
D.SD.prototype.CI=function(b){this.JL=this.Pa;this.US=this.Ox;this.Al=b.HFa;this.oh=b.Dna?b.Dna:{};this.Pa=b.root;this.Sp=b.P5;this.Ox=b.MAa;this.EIa=new D.Nf(b.JBa,b.KBa);this.FIa=new D.Hb(b.IBa);this.QW=b.k5;this.AI=b.PAa;this.RD=b.NAa;this.wP=b.SGa;this.An=b.VGa;this.D2=b.lna;b.R8&&(this.D4=b.R8);this.D2?(this.Kb=new D.dd(b.lna),this.zB=b.yGa):this.Kb=D.q;this.Ca.$z(this.Kb);this.Ca.lx=b.t5;this.Kb?(0,D.Ch)(this.Ca,this.mx(this.Ca)):(0,D.Ch)(this.Ca,D.q);this.Pa&&(this.hq=(0,D.JE)(this.Pa,0));
this.ZZ=b.ou;this.hga=b.mFa;this.Xia=b.QGa;this.mda=b.dBa};D.SD.prototype.QY=function(){for(var b=this.Kb?this.Kb.getSelection():[],c=0;c<b.length;c++)b[c].Nb(D.n)};D.SD.prototype.mG=function(){if(this.Kb&&this.zB){var b=[];(0,D.KE)(this,this.Pa,b);(0,D.Bd)(this.Kb,this.zB,b);this.zB=D.q}};D.IE=function(b,c){var d=D.q,e=b.BL;e&&(d=(0,D.Bt)(b.Pa,e),b.Ca.Xq(d));c&&(b.BL=D.q);d||(d=b.o$(b.Pa),b.Ca.Xq(d));c&&b.rp(b.FV())};D.SD.prototype.rp=function(b){this.bfa=b;this.Ca.rp(b)};D.SD.prototype.FV=(0,D.C)("bfa");
D.KE=function(b,c,d){if(c&&(d.push(c),c=c.ib()))for(var e=0;e<c.length;e++)(0,D.KE)(b,c[e],d)};D.SD.prototype.vE=function(b){return this.Kb?b[0]:D.q};D.SD.prototype.Mx=function(b){b.Ta()||(this.Kb.Si(b,D.t),this.Ca.Bq());b=[];for(var c=this.Kb.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b};D.SD.prototype.Lx=function(){for(var b=[],c=this.Kb.getSelection(),d=0;d<c.length;d++)b.push(c[d].IP());return b};D.SD.prototype.hta=function(b){b instanceof D.Tj&&(0,D.Ht)(this,b.getId(),D.t)};
D.Ht=function(b,c,d){d&&b.Pa&&c==b.Pa.getId()&&b.Ox&&0<b.Ox.length?(b.BL=c,b.Ya(new D.VA(b.Ox[0].id))):d||b.Ya(new D.VA(c));b.e.Kd().sc()};D.SD.prototype.C6=function(b){return(0,D.gb)(this.Ca,b)};D.SD.prototype.hd=function(){this.Eg||(this.Eg=new D.wc);return this.Eg};D.SD.prototype.Ji=function(){return new D.tt(this)};D.SD.prototype.getAutomation=D.SD.prototype.Ji;
D.SD.prototype.yj=function(b,c,d){return this.Ak.yj(d)};D.SD.prototype.Rk=function(b,c){return this.Ak.Rk(b,c)};

D.rt=function(b,c){this.Init(b,c)};D.F.o(D.rt,D.Od,"DvtBaseTreeAnimationHandler");D.st=function(b,c){if(!c||!b)return D.t;for(var d=0;d<b.length;d++)if(b[d].id==c.getId())return D.n;return D.t};
D.wt=(0,D.A)("J");D.F.o(D.wt,D.jd,"DvtBaseTreeDropTarget");
D.pc=function(b,c,d,e){this.Init(c,d,e);this.J=b};D.F.o(D.pc,D.Uc,"DvtBaseTreeEventManager");D.D=D.pc.prototype;D.D.qo=function(b){D.pc.u.qo.call(this,b);var c=(0,D.gb)(this,b.target);c&&(b=b.shiftKey,c.Rq&&c.Rq()&&(0,D.Ht)(this.J,c.getId(),b))};D.D.bh=function(b){D.pc.u.bh.call(this,b);b=(0,D.gb)(this,b.target);(0,D.It)(this,b)};D.D.ro=function(b){D.pc.u.ro.call(this,b);(b=(0,D.gb)(this,b.target))&&b.Pw&&b.Pw()};
D.D.ik=function(b){D.pc.u.ik.call(this,b);var c=(0,D.gb)(this,b.target);c&&c.Oq&&(b=(0,D.gb)(this,b.relatedTarget),(b&&b.getId?b.getId():D.q)!=c.getId()&&c.Oq())};D.D.am=function(b){var c=D.t,c=this.Re();13==b.keyCode&&!b.ctrlKey?(c=this.Re(),c.Rq&&c.Rq()&&(b.shiftKey&&(c=this.J.Pa),(0,D.Ht)(this.J,c.getId(),b.shiftKey)),b.preventDefault(),c=D.n):c=D.pc.u.am.call(this,b);return c};
D.D.Vu=function(b){b=(0,D.gb)(this,b.target);(0,D.It)(this,b);this.tK&&this.tK!=b&&(this.tK.Oq(),this.tK=D.q);b&&b instanceof D.pb&&this.tK!=b&&(this.tK=b,b.Pw())};D.D.oA=function(b){(b=(0,D.gb)(this,b.target))&&b.Rq&&b.Rq()&&(0,D.Ht)(this.J,b.getId(),D.t)};D.It=function(b,c){c&&(c instanceof D.Zb&&c.Tx)&&(0,D.Ht)(b.J,c.getId(),D.t)};
D.mc=(0,D.v)();D.F.o(D.mc,D.F,"DvtBaseTreeParser");D.D=D.mc.prototype;D.D.Init=function(b){this.J=b;this.Uo=new D.ie;this.s2=window.Infinity;this.m2=-window.Infinity};
D.D.parse=function(b){var c=this.Uo.parse(b);b=this.$l(c);var c=c.ib(),d;d=(0,D.Ct)(c,"f");var e=d.length;if(0<e){for(var f,g,h={},j=0;j<e;j++)f=d[j],g=f.q("name"),h[g]=D.T.Yk(f);d=h}else d=D.q;b.R8=d;this.Al=0;f=(0,D.Ct)(c,"n");e=[];for(d=0;d<f.length;d++)(g=this.kG(f[d],b.R8))&&e.push(g);b.HFa=this.Al;if(1==e.length)d=e[0];else{d=this.J;for(g=f=0;g<e.length;g++)f+=e[g].rc();d=this.Wm(d,{size:f,UAa:D.n,oka:D.n});(0,D.yt)(d,e)}b.root=d;for(d=0;d<c.length;d++)if(e=c[d],f=b,e)if(g=e.getName(),"spb"==
g)e=this.p3(e,f),f.Lna||(f.Lna=[]),f.Lna.push(e);else if("menus"==g)f.t5||(f.t5=new D.Ug(this.J.e)),f.t5.add(e);else if("ag"==g){j=e;e=f;h=D.k;f=j.q("id");g=j.q("T");if("continuous"==j.q("t")){var h=j.q("minValue"),m=j.q("maxValue"),o=j.q("minLabel"),p=j.q("maxLabel"),j=j.q("ramp").split(";");h==D.q&&(h=this.s2);m==D.q&&(m=this.m2);h=new D.Dt(h,m,o,p,j)}else{h=new D.Et;j=j.ib();for(m=0;m<j.length;m++){var r=j[m];r&&(o=r.q("g"),p=r.q("l"),r={color:r.q("c"),pattern:r.q("p")},h.add(o,p,r))}}e.ou||(e.ou=
[]);e.ou.push({ou:h,Q8:g,id:f})}else if("styles"==g)f.VGa=this.q3(e,f);else if("a"==g){g=[];e=e.ib();for(h=0;h<e.length;h++)j=e[h].q("id"),m=e[h].q("l"),g.push({id:j,text:m});f.MAa=g}else if("resources"==g){g={};e=e.getAttributes();for(h=0;h<e.length;h++)g[e[h].name]=e[h].value;f.Dna=g}this.Ao(b.root,b);return b};D.D.Wm=(0,D.ba)(D.q);
D.D.$l=function(b){var c={},d=b.q("sel");c.lna="none"==d?D.q:"single"==d?"s":"m";c.SGa=b.q("sort");if(d=b.q("selIds"))c.yGa=d.split(",");c.P5=b.q("emptyText");c.mFa=b.q("ls");c.QGa=b.q("sv");c.dBa=b.q("cv");if(d=b.q("adu"))c.NAa=d/1E3;c.PAa=b.q("adc");c.k5=b.q("adi");return c};
D.D.$u=function(b){var c={};c.Q8=b.q("T");c.DFa=b.q("M");c.sU=b.q("ag");c.id=b.q("id");c.size=(0,window.Number)(b.q("s"));c.color=b.q("c");c.pattern=b.q("p");c.label=b.q("l");c.YGa=b.q("tt");c.OV=b.q("ld");c.HBa=b.q("d");c.oka="t"==b.q("di")?D.n:D.t;c.xGa=b.q("nsel");var d=b.q("tn");d&&(c.Qna=d);if(b=b.q("ls"))c.Au=new D.O(b);c.sU!=D.q&&(this.m2=window.Math.max(this.m2,c.sU),this.s2=window.Math.min(this.s2,c.sU));return c};
D.D.kG=function(b,c){if(!b||"n"!=b.getName())return D.q;this.Al++;var d=this.$u(b),d=this.Wm(this.J,d,c);(0,D.yt)(d,this.kT(b,d,c));return d};D.D.kT=function(b,c,d){var e=[];b=b.ib();for(var f=0;f<b.length;f++){var g=b[f];g&&("el"==g.getName()?d&&c.aba&&c.aba((0,D.Ft)(g)):c.kb()&&e.push(this.kG(g,d)))}return e};D.D.p3=function(b,c){var d=(0,D.Gt)(b),e=b.q("T");c.wI||(c.wI={});c.wI[e]||(c.wI[e]=[]);c.wI[e].push(d)};
D.D.Ao=function(b,c){if(b){var d=b.ap;if(c.wI){var e=c.wI[d];e&&b.L8(e)}if(c.ou)for(var f=0;f<c.ou.length;f++)if(e=c.ou[f],e.Q8==d){if(e.ou instanceof D.Dt&&(d=b,e=e.ou.get(d.yta)))d.Fg=e;break}if(d=b.ib())for(e=0;e<d.length;e++)this.Ao(d[e],c)}};D.Ct=function(b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];f&&f.getName()==c&&d.push(f)}return d};
D.mc.prototype.q3=function(b,c){var d={},e=new D.O(b.q("top"));d.BACKGROUND_STYLE=e;d.ANIMATION_UPDATE_COLOR_STYLE=e.A("-tr-animation-update-color");e=new D.O(b.q("node"));d.LABEL_TEXT_DEFAULT_STYLE=e;var f=e.clone().Bb(new D.O(b.q("node-hover"))),g=e.clone().Bb(new D.O(b.q("node-selected")));c.JBa=b.q("dsf");c.IBa=b.q("dsb");c.KBa=b.q("dso");this.tY(e,f,g,d);this.Eaa(b,d);e=new D.O(b.q("rootText"));d.TEXT_STYLE=e;e=new D.O(b.q("attrType"));d.ATTRIBUTE_TYPE_STYLE=e;e=new D.O(b.q("attrValue"));d.ATTRIBUTE_VALUE_STYLE=
e;e=new D.O(b.q("drillText"));d.DRILL_TEXT_STYLE=e;e=new D.O(b.q("currentText"));d.CURRENT_TEXT_STYLE=e;return d};D.mc.prototype.tY=(0,D.v)();D.mc.prototype.Eaa=(0,D.v)();
D.pb=(0,D.v)();D.F.o(D.pb,D.F,"DvtBaseTreeNode");D.Db=new D.Ck("#000000",2,5,5,45,0.5);
D.pb.prototype.Init=function(b,c,d){this.J=b;this.ap=c.Q8;this.r2=c.DFa;this.yta=c.sU;this.Oa=c.id;this.Rj=c.size;this.Fg=c.color?c.color:"#000000";this.Wo=c.pattern;this.hz=c.label;this.ny=c.YGa;this.rm=c.Au;this.sR=c.HBa;this.kg=c.oka;this.IE=c.UAa;this.ht=1;this.xS=D.q;this.We=D.t;this.D4=d;c.Qna?(0,D.xt)(this,c.Qna):d&&d.content?(0,D.xt)(this,"content"):d&&d.rootContent&&(0,D.xt)(this,"rootContent");this.ZI=D.t;this.nE=c.xGa;this.ad=b.hd()};
D.yt=function(b,c){if(c!=D.q)for(var d=0;d<c.length;d++)c[d].mf=b;b.ce=c};D.pb.prototype.ib=(0,D.C)("ce");D.zt=function(b){var c=[],d,e;if(!b.Be())return c;for(var f=0;f<b.ce.length;f++)e=b.ce[f],d=(0,D.zt)(e),c.push(e),c=c.concat(d);return c};D.Kb=function(b){var c=b.mf;c&&(c.xS=b)};D.pb.prototype.bD=function(b){return!b||!this.mf?D.t:this.mf==b?D.n:this.mf.bD(b)};
D.Nb=function(b,c,d){var e=[];if(0>d)return e;if(0==d)return[b];if(c.Be()){b=c.ib();for(var f=0;f<b.length;f++)c=b[f],e=e.concat((0,D.Nb)(c,c,d-1))}return e};D.At=function(b){var c=[],d;if(!b.Be())return[b];for(var e=0;e<b.ce.length;e++)d=b.ce[e],d=(0,D.At)(d),c=c.concat(d);return c};D.Bt=function(b,c){if(b.getId()==c)return b;for(var d=D.q,e=b.ib(),f=e.length,d=D.q,g=0;g<f;g++)if(d=e[g],d=(0,D.Bt)(d,c))return d;return D.q};D.D=D.pb.prototype;D.D.getId=(0,D.C)("Oa");D.D.rc=(0,D.C)("Rj");D.D.Fb=(0,D.C)("Fg");
D.D.Bf=(0,D.C)("ny");D.D.uj=(0,D.C)("Fg");D.D.aa=(0,D.C)("ht");D.D.C=function(b){this.ht=b;this.I&&this.I.C(this.ht)};D.D.kb=(0,D.C)("kg");D.D.Rq=function(){return"r"==this.sR||"ir"==this.sR};D.D.L8=(0,D.A)("fd");D.D.Cd=(0,D.C)("fd");D.D.Cw=(0,D.C)("r2");D.D.M=(0,D.v)();D.D.Ku=function(b){var c=this.ib();if(c!=D.q)for(var d=0;d<c.length;d++)c[d].M(b)};D.D.wg=function(){(0,D.Kb)(this);return this};D.D.xe=function(){return new D.M(0,0,0,0)};D.D.Mn=(0,D.ba)(D.q);
D.D.yh=function(){this.Bc();this.Pw&&this.Pw();this.We=D.n};D.D.ne=function(){this.wh()&&this.nc();this.Oq&&this.Oq();this.We=D.t};D.D.wh=(0,D.C)("We");D.D.Pw=function(){this.ZI=D.n};D.D.Oq=function(){this.ZI=D.t};D.D.gc=(0,D.ba)(D.n);D.D.Ta=(0,D.C)("Jd");D.D.Nb=function(b){this.Jd=b;this.Wi()};D.D.Bc=(0,D.v)();D.D.nc=(0,D.v)();D.D.yj=function(b){return this.J.vE(b)};D.D.Rk=function(){return this.J.Mx(this)};D.D.KC=function(){return this.J.Lx()};D.D.IP=(0,D.C)("I");D.D.QC=(0,D.ba)(D.q);
D.D.contains=(0,D.ba)(D.t);D.D.fl=function(){return[]};D.D.vo=(0,D.v)();D.D.Pf=function(b,c){b.NJ||(0,D.Dd)(b,c.ib(),this.ib());var d=c.fl(),e=this.fl(),f;if(!D.$c.Rg(d,e)&&(f=new D.Sb(this.J.e,this,this.J.RD),(0,D.P)(f.S,"typeNumberArray",this,this.fl,this.vo,e),b.add(f,1),e=this.Rj!=c.Rj,f=D.U.qV(this.Fg)!=D.U.qV(c.Fg),this.vo(d),(d=(0,D.zb)(this,D.q,"ANIMATION_UPDATE_COLOR_STYLE"))&&(e||f)))this.Fg=d};
D.D.Og=function(b){if(!b.NJ||!b.NJ||!(b.JL.getId()==this.getId()||(0,D.st)(b.US,this))){this.C(0);var c=new D.pd(this.J.e,this,this.J.RD);b.add(c,2);for(c=0;c<this.ce.length;c++)this.ce[c].Og(b)}};D.D.ii=function(b,c){c.k(this.I);var d=new D.od(this.J.e,this,this.J.RD);b.add(d,0);if(!b.NJ)for(d=0;d<this.ce.length;d++)this.ce[d].ii(b,c)};D.D.Be=function(){return this.ce!=D.q&&0<this.ce.length};D.Mb=function(b){var c=0;for(b=b.mf;b;)c++,b=b.mf;return c};
D.pb.prototype.ZD=function(){return this.Wo?new D.qd(this.Wo,this.Fg):new D.Nf(this.Fg)};D.ac=function(b){if(b.Wo)return"#000000";var c=b.Fg;b=D.U.kd(c);var d=D.U.jd(c),c=D.U.gd(c);return 128<=(299*b+587*d+114*c)/1E3?"#000000":"#FFFFFF"};D.$b=function(b,c){var d=(0,D.ac)(b);c.na(d);d=[];d.push(b.J.An.LABEL_TEXT_DEFAULT_STYLE);b.rm&&d.push(b.rm);c.Ga((0,D.bc)(d))};D.zb=function(b,c,d){(b=b.J.An[d])&&(c=b);return c};
D.sb=function(b){var c=11;(b=b.J.An.LABEL_TEXT_DEFAULT_STYLE.wH())&&(c=(0,window.parseFloat)(b));return c};D.pb.prototype.Ia=(0,D.C)("I");D.pb.prototype.vh=(0,D.C)("hz");D.pb.prototype.aba=function(b){b&&!this.tM&&(0,D.xt)(this,"content");this.$h=b};D.xt=function(b,c){c&&(b.tM=b.D4[c])};D.pb.prototype.Tg=function(){return this.Rq()};D.pb.prototype.Wi=(0,D.v)();
D.Zb=function(b,c,d,e,f){this.Init(d,e,f);this.vb=b;this.Oa=c;this.Tx=D.t};D.F.o(D.Zb,D.Xq,"DvtBaseTreePeer");D.Zb.prototype.getId=(0,D.C)("Oa");D.Zb.prototype.wma=(0,D.C)("Tx");D.Zb.prototype.E8=(0,D.A)("Tx");D.Zb.prototype.Oq=function(){this.vb&&this.vb.Oq&&this.vb.Oq()};
D.ot=(0,D.v)();D.F.o(D.ot,D.F,"DvtTreeBreadcrumbsRenderer");D.ot.zra=6;D.ot.Ora="color: #003286;";
D.ot.M=function(b,c,d,e){var f=b.e,g=[];g.push(b.An.TEXT_STYLE);g.push(new D.O(D.ot.Ora));g.push(b.An.DRILL_TEXT_STYLE);var g=(0,D.bc)(g).toString(),h=g+"text-decoration: underline;",j=[];j.push(b.An.TEXT_STYLE);j.push(b.An.CURRENT_TEXT_STYLE);j=(0,D.bc)(j).toString();f=new D.Ui(f,b.hta,b,{Au:g,D7:h,C7:h,nka:j});b.k(f);d=d.slice(0).reverse();d.push({text:e});f.M({items:d},c.g);e=f.D();(0,D.wa)(f,c.x,c.y);e=e.j+D.ot.zra;c.y+=e;c.j-=e;b.removeChild(f);return f};
D.pt=(0,D.v)();D.F.o(D.pt,D.F,"DvtTreeLegendRenderer");D.pt.Wra=4;D.pt.et=7;D.pt.FP=24;D.pt.Vra=11;D.pt.Oba="#636363";D.pt.QHa="color:"+D.pt.Oba+";";
D.pt.M=function(b,c,d,e,f,g,h){var j=b.e,m=b.Va(),o=new D.G(j);b.k(o);var p=D.pt.YL(j,b,o,c.g,d,e,f,g,h),r=b.oh.alta?D.q:"#000000",u=[];u.push(b.An.TEXT_STYLE);var u={borderColor:r,Au:(0,D.bc)(u)},r=D.qt.m8(j,m,o,c.g,c.j,h,u),w=p?p.D():D.q,z=r?r.D():D.q;if(p&&!r)p.G(c.y+(c.g-w.g)/2);else if(r&&!p)r.G(c.y+(c.g-z.g)/2);else if(r&&p){var B=c.g-D.pt.FP;w.g+z.g>B&&(w.g>B/2&&z.g>B/2?(o.removeChild(p),o.removeChild(r),p=D.pt.YL(j,b,o,B/2,d,e,f,g,h),r=D.qt.m8(j,m,o,B/2,c.j,h,u)):w.g>z.g?(m=B-z.g,o.removeChild(p),
p=D.pt.YL(j,b,o,m,d,e,f,g,h)):(d=B-w.g,o.removeChild(r),r=D.qt.m8(j,m,o,d,c.j,h,u)),w=p.D(),z=r.D());(0,D.ya)(j)?(r.G(c.x),p.G(c.x+c.g-w.g)):(p.G(c.x),r.G(c.x+c.g-z.g))}h=o.D();o.P(c.y+c.j-h.j);c.j-=h.j+D.pt.Wra;b.removeChild(o);return o};
D.pt.YL=function(b,c,d,e,f,g,h,j){var m=(0,D.ya)(b),o=c.Va(),p=D.q;if(h||j){p=new D.G(b);d.k(p);var r=[];r.push(c.An.TEXT_STYLE);r.push(c.An.ATTRIBUTE_TYPE_STYLE);d=(0,D.bc)(r);r=[];r.push(c.An.TEXT_STYLE);r.push(c.An.ATTRIBUTE_VALUE_STYLE);var r=(0,D.bc)(r),u,w,z,B;c=0;h&&(u=new D.Ya(b,f,0,0),u.Ga(d),p.k(u),z=u.Vb().g,w=new D.Ya(b,h,0,0),w.Ga(r),p.k(w),B=w.Vb().g,c=z+B+D.pt.et);var I,E,J,L;f=0;j&&(I=new D.Ya(b,g,0,0),I.Ga(d),p.k(I),J=I.Vb().g,E=new D.Ya(b,j,0,0),E.Ga(r),p.k(E),L=E.Vb().g,f=J+L+D.pt.et);
e-=D.pt.FP;c+f>e&&(b=e/2,c>b&&f>b?(D.Pb.Tb(w,b-z-D.pt.et,window.Infinity,p)?(B=w.Vb().g,o.la(w,new D.Xq(h))):(p.removeChild(u),p.removeChild(w),w=D.q,B=0),D.Pb.Tb(E,b-J-D.pt.et,window.Infinity,p)?(L=E.Vb().g,o.la(E,new D.Xq(j))):(p.removeChild(I),p.removeChild(E),E=D.q,L=0)):c>f?D.Pb.Tb(w,e-f-z-D.pt.et,window.Infinity,p)?(B=w.Vb().g,o.la(w,new D.Xq(h))):(p.removeChild(u),p.removeChild(w),w=D.q,B=0):D.Pb.Tb(E,e-c-J-D.pt.et,window.Infinity,p)?(L=E.Vb().g,o.la(E,new D.Xq(j))):(p.removeChild(I),p.removeChild(E),
E=D.q,L=0));e=0;m?(E&&(E.fa(e),e+=L+D.pt.et,I.fa(e),e+=J+D.pt.FP),w&&(w.fa(e),e+=B+D.pt.et,u.fa(e))):(w&&(u.fa(e),e+=z+D.pt.et,w.fa(e),e+=B+D.pt.FP),E&&(I.fa(e),e+=J+D.pt.et,E.fa(e)))}return p};
D.kc=function(b){this.Init(b)};D.F.o(D.kc,D.Ec,"DvtBaseTreeKeyboardHandler");D.kc.prototype.VH=function(b){return this.ak(b)&&!b.ctrlKey};D.kc.prototype.dD=function(b){return 32==b.keyCode&&b.ctrlKey};
D.uc=(0,D.v)();D.F.o(D.uc,D.db,"DvtBaseTreeDefaults");D.mt={skin:"skyros",emptyText:"No data to display",nodeDefaults:{labelStyle:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px;")},styleDefaults:{_attributeTypeTextStyle:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;font-weight:bold;color:#4F4F4F"),_attributeValueTextStyle:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;")},_resources:{}};
D.uc.prototype.Init=function(b){b={skyros:D.Ta.Bb(b.skyros,D.mt),alta:D.Ta.Bb(b.alta,{})};D.uc.u.Init.call(this,b)};
D.Ac=(0,D.v)();D.F.o(D.Ac,D.F,"DvtBaseTreeJsonUtils");
D.Ac.prototype.T8=function(b){var c;c="\x3c"+this.NO();c+=this.sJ(b);c+="\x3e\n";if(b&&b.nodes)for(var d=b.nodes,e=0;e<d.length;e++)c+=(0,D.nt)(this,b,d[e]);d="\x3ca/\x3e\n"+this.nZ(b);d+=this.uJ(b);if(e=b.attributeGroups?b.attributeGroups[0]:D.q)if(b='\x3cag id\x3d"'+e.id+'"',"continuous"==e.attributeType)b+=this.Ea("t","continuous"),b+=this.Ea("ramp",e.colors.join(";")),b+=this.Ea("minValue",e.min),b+=this.Ea("maxValue",e.max),b+=this.Ea("minLabel",e.minLabel),b+=this.Ea("maxLabel",e.maxLabel),
b+="/\x3e";else{b+="\x3e\n";for(var e=e.groups,f=0;f<e.length;f++)b+="\x3ci",b+=this.Ea("g",e[f].id),b+=this.Ea("l",e[f].label),b+=this.Ea("c",e[f].color),b+=this.Ea("p",e[f].pattern),b+="/\x3e\n";b+="\x3c/ag\x3e\n"}else b="";d=d+b+("\x3c/"+this.NO()+"\x3e");return c+=d};D.Ac.prototype.Ea=function(b,c){return c!=D.q?" "+b+'\x3d"'+c+'"':""};D.Ac.prototype.NO=(0,D.ba)(D.q);
D.Ac.prototype.sJ=function(b){var c;c=""+this.Ea("sv",b.sizeLabel);c+=this.Ea("cv",b.colorLabel);var d=b.attributeGroups?b.attributeGroups[0]:D.q;d&&(c+=this.Ea("ls",d.id));for(var d=b.selectedNodes?b.selectedNodes:[],e="",f=0;f<d.length;f++)0<e.length&&(e+=","),e+=d[f];0<e.length&&(c+=this.Ea("selIds",e));c+=this.Ea("adu",b.animationDuration);c+=this.Ea("adc",b.animationOnDataChange);c+=this.Ea("emptyText",b.emptyText);c+=this.Ea("sel",b.selection);return c+=this.Ea("sort",b.sorting)};
D.nt=function(b,c,d){var e;e="\x3cn"+b.tJ(c,d);if(d&&d.nodes&&0<d.nodes.length){e+=b.Ea("di","t");e+="\x3e\n";d=d.nodes;for(var f=0;f<d.length;f++)e+=(0,D.nt)(b,c,d[f]);e+="\x3c/n\x3e\n"}else e+="/\x3e\n";return e};
D.Ac.prototype.tJ=function(b,c){var d;d=""+this.Ea("id",c.id);d+=this.Ea("s",c.value);d+=this.Ea("c",c.color);d+=this.Ea("l",c.label);d+=this.Ea("p",c.pattern);d+=this.Ea("tt",c.shortDesc?c.shortDesc:c.tooltip);d+=this.Ea("ls",c.labelStyle?c.labelStyle:b.nodeDefaults.labelStyle);var e=c.drilling?c.drilling:b.nodeDefaults.drilling;"insert"==e?d+=this.Ea("d","i"):"replace"==e?d+=this.Ea("d","r"):"insertAndReplace"==e&&(d+=this.Ea("d","ir"));return d+=this.Ea("nsel",c.selectable?c.selectable:"auto")};
D.Ac.prototype.nZ=(0,D.v)();D.Ac.prototype.uJ=function(b){var c;c="\x3cstyles "+this.Ea("attrType",b.styleDefaults._attributeTypeTextStyle);return c+=this.Ea("attrValue",b.styleDefaults._attributeValueTextStyle)};
D.tt=function(b){this.jAa=b;this.Pa=b.Pa};(0,D.ta)("DvtTreeAutomation",D.tt);D.F.o(D.tt,D.fb,"DvtTreeAutomation");D.tt.prototype.er=function(b){var c=this.jAa.C6(b);if(!c)return D.q;if(c instanceof D.pb){b="";if(!this.Pa.IE){if(c==this.Pa)return"node[0]";b+="[0]"}b=(c=this.FR(c,this.Pa.ib()))?b+c:b;if(0<b.length)return"node"+b}return D.q};D.tt.prototype.FR=function(b,c){if(c&&0<c.length)for(var d=0;d<c.length;d++){if(c[d]==b)return"["+d+"]";var e=this.FR(b,c[d].ib());if(e)return"["+d+"]"+e}return D.q};
D.tt.prototype.Qk=function(b){return!this.Pa.IE&&(b=b.substring(0,b.indexOf("["))+b.substring(b.indexOf("]")+1),"node"==b)?this.Pa.IP().oa():(b=(0,D.ut)(this,this.Pa,b))?b.Ia().oa():D.q};D.tt.prototype.getDomElementForSubId=D.tt.prototype.Qk;D.ut=function(b,c,d){var e=d.indexOf("["),f=d.indexOf("]");if(0<=e&&0<=f)return e=d.substring(e+1,f),d=d.substring(f+1),f=d.indexOf("]"),0<=d.indexOf("[")&&0<=f?(0,D.ut)(b,c.ib()[e],d):c.ib()[e]};
D.vt=function(b,c,d){var e=d.shift();c=c.ib();return 0==d.length?c[e]:0<d.length?(0,D.vt)(b,c[e],d):D.q};D.tt.prototype.ge=function(b){!this.Pa.IE&&0==b[0]&&b.shift();b=0==b.length?this.Pa:(0,D.vt)(this,this.Pa,b);return{color:b.Fb(),label:b.vh(),selected:b.Ta()==D.k?D.t:b.Ta(),size:b.rc(),tooltip:b.Bf()}};D.tt.prototype.getNode=D.tt.prototype.ge;
});