define([], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  var D={};var m=void 0,o=!0,r=null,t=!1;function aa(){return function(b){return b}}function ba(){return function(){}}function v(b){return function(c){this[b]=c}}function B(b){return function(){return this[b]}}function ca(b){return function(){return b}}var C,COMPILED=o,da=this==window?this:window,ea="";
if(!COMPILED){var fa={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},ga=function(){var b=da.document;return"undefined"!=typeof b&&"write"in b},ha=function(b){return ga()?(da.document.write('\x3cscript type\x3d"text/javascript" src\x3d"'+b+'"\x3e\x3c/script\x3e'),o):t};if(da.CLOSURE_BASE_PATH)ea=da.CLOSURE_BASE_PATH;else if(ga())for(var ia=da.document.getElementsByTagName("script"),ja=ia.length-1;0<=ja;--ja){var na=ia[ja].src,oa=na.lastIndexOf("?"),qa=-1==oa?na.length:oa;if("base.js"==
na.substr(qa-7,7)){ea=na.substr(0,qa-7);break}}if(!da.CLOSURE_NO_DEPS){var ra=ea+"deps.js",sa=da.CLOSURE_IMPORT_SCRIPT||ha;!fa.written[ra]&&sa(ra)&&(fa.written[ra]=o)}}Math.floor(2147483648*Math.random()).toString(36);function ta(b,c){var d=b.split("."),e=da;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)!d.length&&c!==m?e[f]=c:e=e[f]?e[f]:e[f]={}}var DVT_ADVANCED_CLOSURE=o;function SJ(b){this.t4=-1;this.eR=b;b=navigator&&navigator.userAgent?navigator.userAgent.toLowerCase():r;this.SBa=this.$X(b);this.platform=this.aY(b)}function TJ(b){if(-1==b.t4){var c=document.createElement("div");c.style.cssText="width:100px;height:100px;overflow:scroll;position:absolute;top:-9999px;";document.body.appendChild(c);b.t4=c.offsetWidth-c.clientWidth;document.body.removeChild(c)}return b.t4}
SJ.prototype.da=function(){if(this.cja==m){var b=navigator.userAgent.toLowerCase();this.cja=-1!=b.indexOf("mobile")||-1!=b.indexOf("android")?o:t}return this.cja};function UJ(b,c){var d,e;c!=r&&(d=b.className,e=VJ(d,c),-1==e&&(b.className=d?c+" "+d:c))}function WJ(b,c){var d,e,f;c!=r&&(d=b.className,e=VJ(d,c),-1!=e&&(f=e+c.length,e=0==e?r:d.substring(0,e),d=f==d.length?r:d.substring(f+1),b.className=e==r?d==r?"":d:d==r?e:e+d))}function XJ(b,c){return c!=r?-1!=VJ(b.className,c):t}
function VJ(b,c){var d,e,f,g,h,k;if(!b||!b.indexOf)return-1;if(c===b)return 0;d=c.length;e=b.length;f=b.indexOf(c);if(0<=f){g=0==f||" "==b.charAt(f-1);h=f+d;h=h==e||" "==b.charAt(h);if(g&&h)return f;k=b.lastIndexOf(c);if(k!=f)return g=b.charAt(k-1),h=k+d,h=h==e||" "==b.charAt(h),g&&h?k:b.indexOf(" "+c+" ")}return-1}function YJ(b,c){return"Mac"===b.SBa?c.metaKey:c.ctrlKey}
function ZJ(b,c,d){var e;b.eR.Y().isRTLMode()?"gecko"===b.platform?c.scrollLeft=0-d:"ie"==b.platform?c.scrollLeft=d:(b=$J(b.eR.yd.firstChild),e=parseInt(c.style.width,10),c.scrollLeft=b-e-d):c.scrollLeft=d}SJ.prototype.$X=function(b){if(b){if(-1!=b.indexOf("win"))return"Windows";if(-1!=b.indexOf("mac"))return"Mac";if(-1!=b.indexOf("sunos"))return"Solaris"}return"Unknown"};
SJ.prototype.aY=function(b){if(b&&-1==b.indexOf("opera")){if(-1!=b.indexOf("trident")||-1!=b.indexOf("msie"))return"ie";if(-1!=b.indexOf("applewebkit")||-1!=b.indexOf("safari"))return"webkit";if(-1!=b.indexOf("gecko/"))return"gecko"}return"unknown"};
function LK(b){this.options=b}function NK(b,c,d,e){return c!=r?(b=b.options[c],d!=r&&b!=r?(d=b[d],e!=r&&d!=r?d[e]:d):b):r}C=LK.prototype;C.evaluate=function(b,c){return"function"==typeof b?b.call(this,c):b};function rM(b,c,d){var e,f,g;"row"==d||"column"==d?(e="header",f=d,g=c):"cell"==d&&(e="cell",f=c);return NK(b,e,f,g)}C.ja=function(b,c,d){return this.evaluate(rM(this,b,c),d)};function rL(b){b=NK(b,"bandingInterval","row");return b!=r?b:0}
function fL(b){b=NK(b,"bandingInterval","column");return b!=r?b:0}C.yR=function(){return NK(this,"emptyText")};function gL(b){b=NK(b,"gridlines","horizontal");return b!=r?b:"visible"}function hL(b){b=NK(b,"gridlines","vertical");return b!=r?b:"visible"}function CL(b){var c;c=NK(b,"selectionMode");if(c==m)return"none";b=b.gk();c=c[b];return c!=r?c:"none"}C.gk=function(){var b;b=NK(this,"selectionMode");if(b==m)return"cell";b=b.row;return b!=r&&"none"!=b?"row":"cell"};
function tK(b,c,d){b=b.ja("resizable",c,d);return b!=r?b:t}C.Wq=function(b,c){return this.ja("style",b,c)};C.Nx=function(b,c){return this.ja("className",b,c)};function aL(b,c){return rM(b,"renderer",c)};
function KK(){this.sT={column:{},row:{}}}KK.prototype.qj=function(b,c,d){this.sT[b][c]=d};KK.prototype.sc=function(b,c){return this.sT[b].hasOwnProperty(c)?this.sT[b][c]:r};KK.prototype.clear=function(){this.sT={column:{},row:{}}};
function fK(){this.TIMEOUT=100;this.iM=20;this.GB=30;this.fF=[];this.eF=[];this.pj=new SJ(this);this.gF=t;this.VA=this.nv=0;this.WK=new KK;this.tS=this.ES=r;this.iF={};this.UK=this.YK=t;this.oja=this.pja=m;this.XK=this.HS=this.$K=this.ZK=t;this.wga={}}ta("DvtDataGrid",fK);fK.prototype.Jd=function(b){this.Bc=new LK(b)};fK.prototype.SetOptions=fK.prototype.Jd;fK.prototype.ona=v("ov");fK.prototype.SetResources=fK.prototype.ona;fK.prototype.Y=B("ov");fK.prototype.getResources=fK.prototype.Y;
fK.prototype.nna=function(b){b.on("change",this.Mia.bind(this),this);b.on("expand",this.Hia.bind(this),this);b.on("collapse",this.Eia.bind(this),this);this.Bd=b};fK.prototype.SetDataSource=fK.prototype.nna;fK.prototype.Tya=B("Bd");fK.prototype.getDataSource=fK.prototype.Tya;fK.prototype.mna=v("vS");fK.prototype.SetCreateContextCallback=fK.prototype.mna;function MK(b){b=NK(b.Bc,"scrollPolicy");b==r&&(b="auto");return"scroll"!=b}
fK.prototype.V=function(){delete this.mk;document.removeEventListener("mousemove",this.Wga,t);document.removeEventListener("mouseup",this.Xga,t);this.Bd.off("change",this.Mia);this.Bd.off("expand",this.Hia);this.Bd.off("collapse",this.Eia);delete this.iF;this.iF={}};fK.prototype.destroy=fK.prototype.V;fK.prototype.getWidth=function(){this.tja==r&&(this.tja=this.Pf.offsetWidth);return this.tja};fK.prototype.getHeight=function(){this.nja==r&&(this.nja=this.Pf.offsetHeight);return this.nja};
function OK(b){b=b.getWidth();return Math.round(1.5*b)}function PK(b){b=b.getHeight();return Math.round(1.5*b)}function QK(b,c){return"row"==c?(b.sja==r&&(b.sja=Math.round(PK(b)/lK(b))),b.sja):"column"==c?(b.kja==r&&(b.kja=Math.round(OK(b)/50)),b.kja):0}fK.prototype.yR=function(){var b;b=this.Bc.yR();b==r&&(b=this.Y(),b=b.getTranslatedText("empty"));return b};
function lK(b){var c,d;b.mja==r&&(c=document.createElement("div"),d=b.Y(),c.className=d.getMappedStyle("colheader")+" "+d.getMappedStyle("headercell"),c.style.visibilty="hidden",c.style.top="0px",c.style.visibilty="0px",c.style.height="auto",c.innerHTML="hq",b.Pf.appendChild(c),d=c.offsetHeight,b.Pf.removeChild(c),b.mja=Math.max(d,30));return b.mja}function RK(b){var c;c=b.className;b=b.style.cssText;return 0<b.indexOf("width")||0<b.indexOf("height")?c.concat(b):c}
function SK(b,c,d,e){var f;f=b.WK.sc("row",e);if(f!=r)return f;f=b.fF[d-b.VA];if(f==r)e=RK(c),f=b.iF[e],f==r&&(c.style.visibility="hidden",document.body.appendChild(c),f=c.offsetHeight,c.style.visibility="visible",b.iF[e]=f);else return f;0===f&&(f=lK(b));0>d-b.VA?b.fF.unshift(f):b.fF[d-b.VA]=f;return f}
function TK(b,c,d,e){var f;f=b.WK.sc("column",e);if(f!=r)return f;f=b.eF[d-b.nv];if(f==r)e=RK(c),f=b.iF[e],f==r&&(""===c.style.width&&wK(c,50),c.style.visibility="hidden",document.body.appendChild(c),f=c.offsetWidth,c.style.visibility="visible",b.iF[e]=f);else return f;0===f&&(f=50);0>d-b.nv?b.eF.unshift(f):b.eF[d-b.nv]=f;return f}function UK(b,c){var d=b.Pf.id;d==r&&(d="");return[d,c].join(":")}function VK(b){return b.mk.row===t&&b.mk.column===t}function hK(b){return VK(b)&&b.mk.cells===t}
fK.prototype.refresh=function(b){this.V();this.fF=[];this.eF=[];this.WK.clear();this.VA=this.nv=0;this.UK=this.YK=t;this.DS=this.uS=this.sS=this.I3=r;this.Un=this.Ml=m;this.yd=this.lb=this.Wd=this.Vd=r;this.oja=this.pja=m;this.XK=this.HS=this.$K=this.ZK=t;this.G(b)};fK.prototype.refresh=fK.prototype.refresh;
fK.prototype.G=function(b){this.rHa=new Date;this.mk={};this.ng=this.nj=this.Vn=this.Wn=this.YA=this.Vx=this.Xs=this.Jm=this.oj=this.Km=this.fh=this.jf=this.Ys=this.Nl=this.og=this.Nd=this.md=this.Hc=0;var c,d,e,f;this.Pf=b;this.Pf.className=this.Y().getMappedStyle("datagrid");this.Pf.setAttribute("role","application");this.Pf.setAttribute("aria-labelledby",UK(this,"info"));this.er=t;b.tabIndex=0;f=document.createElement("div");f.id=UK(this,"status");f.className=this.Y().getMappedStyle("status");
f.setAttribute("role","status");b.appendChild(f);this.hF=f;f=document.createElement("div");f.id=UK(this,"info");f.className=this.Y().getMappedStyle("info");f.setAttribute("role","status");b.appendChild(f);this.xBa=f;c=document.createElement("div");c.id=UK(this,"state");c.className=this.Y().getMappedStyle("info");b.appendChild(c);this.qHa=c;if(this.Bd!=r){c=this.Y().isRTLMode();d=WK(this,"column",this.Y().getMappedStyle("colheader"));e=WK(this,"row",this.Y().getMappedStyle("rowheader"));var g=document.createElement("div");
g.id=UK(this,"scroller");g.className=this.Y().getMappedStyle("scrollers");g.addEventListener?g.addEventListener("scroll",this.Nia.bind(this),t):g.attachEvent("onscroll",this.Nia.bind(this));var h=document.createElement("div");h.id=UK(this,"databody");h.className=this.Y().getMappedStyle("databody");this.fetchCells(h,g,0,0);c&&(d.style.direction="rtl",h.style.direction="rtl",g.style.direction="rtl");b.appendChild(d);b.appendChild(e);b.appendChild(g);b.appendChild(h);this.Vd=d;this.Wd=e;this.lb=h;this.yd=
g;b.addEventListener?(h.addEventListener("mousewheel",this.Gia.bind(this),t),h.addEventListener("mousedown",this.$R.bind(this),t),h.addEventListener("mousemove",this.wAa.bind(this),t),h.addEventListener("mouseup",this.zAa.bind(this),t),h.addEventListener("mouseout",this.xAa.bind(this),t),h.addEventListener("mouseover",this.yAa.bind(this),t),b.addEventListener("keydown",this.Fia.bind(this),t),b.addEventListener("focus",this.AAa.bind(this),t),this.xS=t,this.ue=r,this.wS=t,this.Wga=this.CAa.bind(this),
this.Xga=this.DAa.bind(this),document.addEventListener("mousemove",this.Wga,t),document.addEventListener("mouseup",this.Xga,t),e.addEventListener("mousedown",this.Jia.bind(this),t),d.addEventListener("mousedown",this.Jia.bind(this),t),e.addEventListener("mouseover",this.Lia.bind(this),t),d.addEventListener("mouseover",this.Lia.bind(this),t),e.addEventListener("mouseout",this.Kia.bind(this),t),d.addEventListener("mouseout",this.Kia.bind(this),t),e.addEventListener("click",this.Iia.bind(this),t),d.addEventListener("click",
this.Iia.bind(this),t),this.pj.da()?(h.addEventListener("touchstart",this.JAa.bind(this),t),h.addEventListener("touchmove",this.IAa.bind(this),t),h.addEventListener("touchend",this.HAa.bind(this),t),h.addEventListener("touchcancel",this.FK.bind(this),t)):(g.addEventListener("mousedown",this.FAa.bind(this),t),g.addEventListener("mouseup",this.GAa.bind(this),t))):(h.attachEvent("onmousewheel",this.Gia.bind(this)),h.attachEvent("onmousedown",this.$R.bind(this)),h.attachEvent("onmousemove",this.$R.bind(this)),
h.attachEvent("onmouseup",this.$R.bind(this)),b.attachEvent("onkeydown",this.Fia.bind(this)));c=this.Bd;b=c.getCount("row");c=c.getCount("column");d=!XK(this,"row")&&!XK(this,"column")?"summary-exact":"summary-estimate";b=this.Y().getTranslatedText(d,[b,c]);f.innerHTML=b;hK(this)&&!this.er?(YK(this),ZK(this)):VK(this)&&!this.er&&$K(this)}else b=this.yR(),f=document.createElement("div"),f.className=this.Y().getMappedStyle("emptytext"),f.setAttribute("id",UK(this,"empty")),f.innerHTML=b,this.Pf.appendChild(f)};
fK.prototype.render=fK.prototype.G;function $K(b){var c,d,e,f,g,h,k;b.Vd==r||b.Wd==r||(c=b.getWidth(),d=b.getHeight(),e=b.Vd,f=b.Wd,g=kK(e),h=$J(f),k=b.Y().isRTLMode()?"right":"left",zK(f,0,k),zK(f,g,"top"),BK(f,d-g),zK(e,h,k),wK(e,c-h),b.pj.da()||JK(b))}
function YK(b){var c,d,e,f,g,h,k,n,p,q,s,u,w,z,A;b.lb!=r&&(b.rja==r&&(b.rja=parseInt(document.defaultView.getComputedStyle(b.Pf,r).getPropertyValue("border-top-width"),10)),k=b.rja,c=b.getWidth()-2*k,d=b.getHeight()-2*k,e=b.Vd,f=b.Wd,g=b.yd,h=b.lb,k=kK(e),n=$J(f),p=$J(h.firstChild),c=Math.min(p,c-n),q=kK(h.firstChild),d=Math.min(q,d-k),s=b.pj.da(),z=TJ(b.pj),(u=HK(b,c))?w=GK(b,d-z):(w=GK(b,d),u&&(u=HK(b,c-z))),b.cr=u,b.dr=w,u&&w&&(d-=z,c-=z),A=b.Y().isRTLMode()?"right":"left",zK(f,0,A),zK(f,k,"top"),
BK(f,d),zK(e,n,A),wK(e,c),zK(h,k,"top"),zK(h,n,A),wK(h,c),BK(h,d),b.ABa=p-c,b.zBa=q-d,u&&(d+=z),w&&(c+=z),zK(g,k,"top"),zK(g,n,A),wK(g,c),BK(g,d),s||JK(b),!b.er&&(0==b.Hc&&0==b.Nd&&0==b.Km&&0==b.Jm)&&(f=b.yR(),e=document.createElement("div"),e.className=b.Y().getMappedStyle("emptytext"),zK(e,k,"top"),e.innerHTML=f,b.Pf.appendChild(e)),b.er=o)}
function JK(b){var c,d,e,f,g,h,k;c=$J(b.lb);d=kK(b.lb);e=TJ(b.pj);b.cr&&(d+=e);b.dr&&(c+=e);f=kK(b.Vd);g=$J(b.Wd);k=b.Y().isRTLMode()?"right":"left";b.I3!=r&&b.Pf.removeChild(b.I3);b.DS!=r&&b.Pf.removeChild(b.DS);b.uS!=r&&b.Pf.removeChild(b.uS);b.sS!=r&&b.Pf.removeChild(b.sS);1!==b.Wd.firstChild.childNodes.length&&(h=document.createElement("div"),h.id=UK(b,"corner"),h.className=b.Y().getMappedStyle("topcorner"),wK(h,g),BK(h,f),b.Pf.appendChild(h),b.I3=h);b.cr?(h=document.createElement("div"),h.id=
UK(b,"rhSbSpacer"),h.className=b.Y().getMappedStyle("rowheaderspacer"),zK(h,f+d-e,"top"),zK(h,0,k),wK(h,g),BK(h,e),b.Pf.appendChild(h),b.DS=h):b.DS=r;b.dr?(h=document.createElement("div"),h.id=UK(b,"chSbSpacer"),h.className=b.Y().getMappedStyle("colheaderspacer"),zK(h,g+c-e,k),wK(h,e),BK(h,f),b.Pf.appendChild(h),b.uS=h):b.uS=r;b.cr&&b.dr?(h=document.createElement("div"),h.id=UK(b,"bcorner"),h.className=b.Y().getMappedStyle("bottomcorner"),zK(h,f+d-e,"top"),zK(h,g+c-e,k),wK(h,e),BK(h,e),b.Pf.appendChild(h),
b.sS=h):b.sS=r}function ZK(b){var c,d,e;e=d=0;c=NK(b.Bc,"scrollPosition");c=c==m?r:c.key!=m?"key":c.index!=m?"index":r;if(b.yd!=m){if(c!=r){d=b.Bc;e=NK(d,"scrollPosition","key","column");d=e!=r?e:NK(d,"scrollPosition","index","column");e=b.Bc;var f;f=NK(e,"scrollPosition","key","row");e=f!=r?f:NK(e,"scrollPosition","index","row");"key"===c&&(c=b.Bd.indexes({gIa:e,aGa:d}),d=-1===c.column?0:c.column,e=-1===c.row?0:c.row);d*=b.Un;e*=b.Ml}ZJ(b.pj,b.yd,d);b.yd.scrollTop=e}}
function HK(b,c){var d;d=b.lb;return $J(d.firstChild)>(c==r?$J(d):c)?o:t}function GK(b,c){var d;d=b.lb;return kK(d.firstChild)>(c==r?kK(d):c)?o:t}function XK(b,c){var d,e;d=b.Bd;return"row"===c?(b.Tba===m&&(e=d.getCountPrecision("row"),d=d.getCount("row"),b.Tba="estimate"===e||0>d?o:t),b.Tba):"column"===c?(b.Sba===m&&(e=d.getCountPrecision("column"),d=d.getCount("column"),b.Sba="estimate"===e||0>d?o:t),b.Sba):t}
function WK(b,c,d){var e=document.createElement("div");e.id=UK(b,c+"Header");e.className=d+" "+b.Y().getMappedStyle("header");b.fetchHeaders(c,0,e);return e}C=fK.prototype;
C.fetchHeaders=function(b,c,d,e,f){var g,h;this.mk[b]||(this.mk[b]={start:c},e==m&&(e=QK(this,b),XK(this,b)||(g="row"==b?this.Hc:this.md,h="row"==b?this.Nd:this.og,c<g?e=Math.min(e,g):(g=this.Bd.getCount(b),0<=g&&(e=Math.min(e,Math.max(0,g-h)))))),b={axis:b,start:c,count:e,header:d},f=f!=r&&f.success!=r?f.success:this.aS,eK(this),this.Bd.fetchHeaders(b,{success:f,error:this.q3},{success:this,error:this}))};
C.aS=function(b,c){var d,e,f,g;if(c.start==this.mk[c.axis].start){d=c.axis;this.mk[d]=t;e=c.header;f=c.start;g=this.Bd.getCount(d);if("column"===d)a:{var h,k,n,p,q,s,u,w,z,A,F,I,L,N,S,P;d=lK(this);p=b.getCount();if(e.hasChildNodes()){if(0==p&&XK(this,"column")){this.XK=o;break a}d=e.firstChild}else 0==p?BK(e,0):BK(e,d),d=document.createElement("div"),d.className=this.Y().getMappedStyle("row")+" "+(this.pj.da()?this.Y().getMappedStyle("scroller-mobile"):this.Y().getMappedStyle("scroller"));h=aL(this.Bc,
"column");k=0;n=f<this.oj?this.YA:this.Vn;q=d.firstChild;s=this.Y().getMappedStyle("headercell")+" "+this.Y().getMappedStyle("colheadercell");u=this.Y().isRTLMode()?"right":"left";S=this.Y().getMappedAttribute("sortable");P=this.Y().getMappedAttribute("resizable");for(w=0;w<p;w+=1){z=f<this.oj?f+p-1-w:f+w;N=document.createElement("div");N.id=UK(this,"c"+z);A=b.getData(z);F=b.getMetadata(z);F=bL(this,"column",z,A,F,N);I=this.Bc.Wq("column",F);L=this.Bc.Nx("column",F);z===g-1&&("left"===u?N.style.borderRightStyle=
"none":N.style.borderLeftStyle="none");I!=r&&(N.style.cssText=I);N.className=L!=r?s+" "+L:s;this.tS==r&&""!=N.style.height&&(this.tS=kK(N),BK(e,this.tS));N.style.height="100%";f<this.oj?(z=TK(this,N,f+p-1-w,F.key),this.nv-=1):z=TK(this,N,f+w,F.key);wK(N,z);f<this.oj?zK(N,n-z,u):zK(N,n,u);cL(this,"column",F)&&N.setAttribute(P,"true");h!=r?(A=h.call(this,F),A!=r&&(A.parentNode===r?N.appendChild(A):A.parentNode==r&&A.toString&&N.appendChild(document.createTextNode(A.toString())))):N.appendChild(document.createTextNode(A.toString()));
A=m;A=this.Bd.getCapability("sort");F=this.Bc.ja("sortable","column",F);if(F!=r&&F&&("full"===A||"column"===A))I=F=A=m,A=document.createElement("div"),A.className=this.Y().getMappedStyle("sortindicators"),F=document.createElement("a"),F.className=this.Y().getMappedStyle("sortascending"),I=document.createElement("a"),I.className=this.Y().getMappedStyle("sortdescending"),A.appendChild(F),A.appendChild(I),N.appendChild(A),N.setAttribute(S,"true");n=f<this.oj?n-z:n+z;k+=z;f<this.oj?(d.insertBefore(N,
q),q=N):d.appendChild(N)}f<this.oj?(this.oj-=p,this.YA-=k):(this.Xs+=p,this.Vn+=k);e.hasChildNodes()||e.appendChild(d);if(0<p&&(e=k/p,0==this.jja||e!=this.jja))this.jja=e,wK(d,g*e);!XK(this,"column")&&(MK(this)&&this.Xs>=g)&&(this.XK=o)}else if("row"===d)a:{var W;lK(this);d=b.getCount();if(e.hasChildNodes()){if(0==d&&XK(this,"row")){this.$K=o;break a}p=e.firstChild;k=p.firstChild}else p=document.createElement("div"),p.className=this.pj.da()?this.Y().getMappedStyle("scroller-mobile"):this.Y().getMappedStyle("scroller"),
0==d?(wK(e,0),BK(p,0)):wK(e,50),k=document.createElement("div"),k.style.display="none",wK(k,1),BK(k,0),p.appendChild(k);n=aL(this.Bc,"row");s=(q=f>=this.Km?o:t)?this.Wn:this.Vx;-1==g&&(g=this.Jm+d);S=this.Y().getMappedAttribute("resizable");h=0;u=document.createDocumentFragment();for(w=0;w<d;w+=1)P=q?f+w:f+(d-1-w),N=document.createElement("div"),N.id=UK(this,"r"+P),z=b.getData(P),A=b.getMetadata(P),A=bL(this,"row",P,z,A,N),F=this.Bc.Wq("row",A),L=this.Bc.Nx("row",A),F!=r&&(N.style.cssText=F),this.ES==
r&&""!=N.style.width&&(this.ES=$J(N),wK(e,this.ES)),N.className=this.Y().getMappedStyle("row"),F=SK(this,N,f+w,A.key),BK(N,F),q?(N.style.top=s+"px",s+=F):(s-=F,N.style.top=s+"px"),I=document.createElement("div"),W=this.Y().getMappedStyle("headercell")+" "+this.Y().getMappedStyle("rowheadercell"),I.className=L!=r?W+" "+L:W,P===g-1&&(I.style.borderBottomStyle="none"),cL(this,"row",A)&&I.setAttribute(S,"true"),n!=r?(P=n.call(this,A),P!=r&&(P.parentNode===r?I.appendChild(P):P.parentNode==r&&P.toString&&
I.appendChild(document.createTextNode(P.toString())))):I.appendChild(document.createTextNode(z.toString())),N.appendChild(I),q?u.appendChild(N):u.insertBefore(N,u.firstChild),h+=F;q?(p.appendChild(u),0!=this.Jm&&0!=d&&(f=p.childNodes[this.Jm],f!=r&&(f.firstChild.style.borderBottomStyle="")),this.Jm+=d,this.Wn+=h):(BK(k,Math.max(0,kK(k)-h)),p.insertBefore(u,k.nextSibling),this.Km-=d,this.Vx=Math.max(0,this.Vx-h));e.appendChild(p);!XK(this,"row")&&(MK(this)&&this.Jm>=g)&&(this.$K=o)}hK(this)?(gK(this),
this.er||(YK(this),ZK(this))):VK(this)&&(this.er||$K(this));this.er&&dL(this)}};C.q3=function(b,c){this.mk[c.axis]=t};function bL(b,c,d,e,f,g){var h={};h.axis=c;h.index=d;h.data=e;h.datagrid=b;h.parentElement=g;c=f.key;c!=r&&(h.key=c,g.setAttribute(b.Y().getMappedAttribute("key"),c));b.vS!=r&&b.vS.call(b,h);return h}
C.fetchCells=function(b,c,d,e,f,g,h){var k;this.mk.cells||(this.mk.cells={row:d,column:e},f==r&&(f=QK(this,"row"),XK(this,"row")||(d<this.Hc?f=Math.min(f,this.Hc):(k=this.Bd.getCount("row"),0<=k&&(f=Math.min(f,Math.max(0,k-this.Nd)))))),g==r&&(g=QK(this,"column"),XK(this,"column")||(e<this.md?g=Math.min(g,this.md):(k=this.Bd.getCount("column"),0<=k&&(g=Math.min(g,Math.max(0,k-this.og)))))),d={axis:"row",start:d,count:f},b={axis:"column",start:e,count:g,databody:b,scroller:c},h=h!=r&&h.success!=r?
h.success:this.o3,eK(this),this.Bd.fetchCells([d,b],{success:h,error:this.q3},{success:this,error:this}))};C.C3=ca(t);
C.o3=function(b,c,d){var e,f,g,h,k,n,p,q,s,u,w,z,A,F,I;e=this.Bd.getCount("row");f=this.Bd.getCount("column");if(d===m){d=t;h=c[0].start;k=c[1].start;q=this.mk.cells;g=q.row;q=q.column;if(!(g==h&&q==k))return;if(h=this.Nl==this.jf&&this.Ys==this.fh){var L;isNaN(this.Ml)||isNaN(this.Un)?h=o:(g=c[0].start,h=b.getCount("row"),q=g+h,p=c[1].start,k=b.getCount("column"),g*=this.Ml,q*=this.Ml,s=this.Un*p,p=this.Un*(p+k),z=this.ng,A=this.ng+kK(this.lb),n=this.nj,L=this.nj+$J(this.lb),!XK(this,"row")&&(this.Bd.getCount("row")==
h&&q<A)&&(q=A),!XK(this,"column")&&(this.Bd.getCount("column")==k&&p<L)&&(p=L),h=z>=g&&A<=q&&n>=s&&L<=p);h=!h}if(h){this.mk.cells=t;this.UK||nK(this,this.nj,this.ng);return}}lK(this);g=c[0];h=g.start;k=b.getCount("row");n=0<k&&(h>=this.Nd||h+k<=this.Hc);if(0==k&&XK(this,"row")&&0<g.count||n&&MK(this)&&!XK(this,"row")&&this.Nd+k>=e)this.ZK=o;p=c[1];g=p.start;q=b.getCount("column");s=0<q&&(g==this.og||g+q==this.md);if(0==q&&XK(this,"column")&&0<p.count||s&&MK(this)&&!XK(this,"column")&&this.og+q>=f)this.HS=
o;c=this.lb;c==r&&(c=p.databody);z=this.yd;z==r&&(z=p.scroller);z.hasChildNodes()?p=z.firstChild:(p=document.createElement("div"),z.appendChild(p));c.hasChildNodes()?(z=c.firstChild,A=z.firstChild):(z=document.createElement("div"),z.className=this.pj.da()?this.Y().getMappedStyle("scroller-mobile"):this.Y().getMappedStyle("scroller"),A=document.createElement("div"),A.style.display="none",wK(A,1),BK(A,0),z.appendChild(A));if(n||d)if((F=!d&&h>=this.Hc?o:t)?u=this.jf:d?(w=z.childNodes[h-this.Hc+1],u=
parseInt(w.style.top)):u=this.Nl,n=document.createDocumentFragment(),u=iK(this,n,F||d,u,h,k,g,s,b),b=u.totalRowHeight,I=u.avgWidth,u=b/k,F){z.appendChild(n);if(0!=this.Nd&&0!=k&&(d=z.childNodes[this.Nd],d!=r)){d=d.childNodes;for(F=0;F<d.length;F+=1)d[F].style.borderBottomStyle=""}this.Nd+=k;this.jf+=b;c.hasChildNodes()||(c.appendChild(z),this.C3()&&(b=document.createElement("div"),bottomHotspot=document.createElement("div"),c.appendChild(b),c.appendChild(bottomHotspot)))}else d?(z.insertBefore(n,
w),h>this.Hc?(this.Nd+=k,this.jf=Math.max(0,this.jf+b)):(this.Hc=h,this.Nl=Math.max(0,this.Nl-b),BK(A,Math.max(0,kK(A)-b))),eL(w,b)):(z.insertBefore(n,A.nextSibling),this.Hc-=k,this.Nl=Math.max(0,this.Nl-b),BK(A,Math.max(0,kK(A)-b)));else if(s&&(d=z.childNodes,k==d.length-1)){I=aL(this.Bc,"cell");w=fL(this.Bc);A=gL(this.Bc);n=hL(this.Bc);for(L=0;L<k;L+=1)F=d[L+1],F=iL(this,b,F,h+L,I,t,g,L==k-1,w,A,n);I=F}b=-1!=f&&!MK(this)?f*I:this.fh;if(I!=m&&(0==this.Un||this.Un==m))this.Un=I,wK(z,b),wK(p,b);else if((-1==
f||MK(this))&&b>$J(z))wK(z,b),wK(p,b);b=-1!=e&&!MK(this)?e*u:this.jf;if(u!=m&&(0==this.Ml||this.Ml==m))this.Ml=u,BK(z,b),BK(p,b);else if((-1==e||MK(this))&&b>kK(z)||e*u!=kK(z))BK(z,b),BK(p,b);s&&(g<this.md?this.md-=q:this.og+=q);this.mk.cells=t;this.er&&(dL(this),jL(this));hK(this)&&(gK(this),this.er?(this.yd==r?e=t:(e=kK(this.yd),f=$J(this.yd),b=this.yd.firstChild,u=kK(b),b=$J(b),e=this.jf>e&&f==b||this.fh>f&&e==u?o:t),e&&YK(this)):(YK(this),ZK(this)),this.pv!=r&&(kL(this,this.pv),this.Md!=r?"row"===
this.Md.axis?lL(this,this.pv.row):"column"===this.Md.axis&&mL(this,this.pv.column):this.pv==this.uf?nL(this):oL(this,this.pv),this.pv=r),pL(this)&&(this.lb==r&&(this.lb=c),qL(this,h,h+k)))};
function iK(b,c,d,e,f,g,h,k,n){var p,q,s,u,w,z,A,F,I;p=aL(b.Bc,"cell");q=fL(b.Bc);s=rL(b.Bc);u=gL(b.Bc);w=hL(b.Bc);for(i=F=0;i<g;i+=1)I=d?f+i:f+(g-1-i),z=document.createElement("div"),z.className=1===Math.floor(I/s)%2?b.Y().getMappedStyle("row")+" "+b.Y().getMappedStyle("banded"):b.Y().getMappedStyle("row"),A=iL(b,n,z,I,p,o,h,i==g-1&&k,q,u,w),I=SK(b,z,I,z.getAttribute(b.Y().getMappedAttribute("key"))),BK(z,I),F+=I,d?(z.style.top=e+"px",e+=I,c.appendChild(z)):(e-=I,z.style.top=e+"px",c.insertBefore(z,
c.firstChild));return{avgWidth:A,totalRowHeight:F,top:e}}function eL(b,c){for(;b;)b.style.top=parseInt(b.style.top)+c+"px",b=b.nextSibling}C.Dia=ba();
function iL(b,c,d,e,f,g,h,k,n,p,q){var s,u,w,z,A,F,I,L,N,S,P,W,X,ma,ka;s=h>=b.md;u=d.firstChild;A=g||!s?b.Ys:b.fh;ka=b.Y().getMappedAttribute("key");F=b.Y().isRTLMode()?"right":"left";I=0;L=c.getCount("column");for(W=0;W<L;W+=1){ma=s||g?h+W:h+(L-1-W);w={row:e,column:ma};N=c.getData(w);S=c.getMetadata(w);X=document.createElement("div");X.setAttribute("tabIndex",-1);P=b;z=N;var la=m,la={};la.parentElement=X;la.indexes=w;la.keys=S.keys;la.data=z;la.datagrid=P;S.row&&S.column&&(la.metadata={row:S.row,
column:S.column});P.vS!=r&&P.vS.call(P,la);P=la;d.hasAttribute(ka)||d.setAttribute(ka,P.keys.row);if("hidden"===q||ma===b.Bd.getCount("column")-1)"left"===F?X.style.borderRight="none":X.style.borderLeftStyle="none";if("hidden"===p||e===b.Bd.getCount("row")-1)X.style.borderBottomStyle="none";w=b.Bc.Wq("cell",P);w!=r&&(X.style.cssText=w);z=1===Math.floor(ma/n)%2?b.Y().getMappedStyle("cell")+" "+b.Y().getMappedStyle("banded"):b.Y().getMappedStyle("cell");w=b.Bc.Nx("cell",P);X.className=w!=r?z+" "+w:
z;X.style.height="100%";ma=TK(b,X,ma,P.keys.column);wK(X,ma);s||g?zK(X,A,F):zK(X,A-ma,F);b.Pf.appendChild(X);f!=r?(N=f.call(b,P),N!=r&&(N.parentNode===r?X.appendChild(N):N.parentNode==r&&N.toString&&X.appendChild(document.createTextNode(N.toString())))):X.appendChild(document.createTextNode(N.toString()));s||g?(d.appendChild(X),A+=ma):(d.insertBefore(X,u),u=X,A-=ma);k&&(s||g?b.fh+=ma:b.Ys-=ma,I+=ma);b.K3!=r&&(X=b,N=b.K3,P=ma=P=m,N.setAttribute(X.Y().getMappedAttribute("expander"),"true"),N.firstChild.getAttribute("aria-expanded")!==
r&&(P=sL(X,N),ma=P.parentNode,P=Array.prototype.indexOf.call(ma.childNodes,P),ma.setAttribute(X.Y().getMappedAttribute("expanderIndex"),P),ma.setAttribute("aria-expanded","true"==N.firstChild.getAttribute("aria-expanded"))),b.K3=r)}return k&&0<L?I/L:r}C.Dia=function(){this.mk.cells=t};function eK(b){var c;c=b.Y().getTranslatedText("fetching");"block"!=b.hF.style.display&&(b.hF.innerHTML=c,b.hF.style.display="block",c=b.getWidth()/2-b.hF.offsetWidth/2,b.hF.style.left=c+"px")}
function gK(b){b.hF.style.display="none"}C.Nia=function(b){var c;b||(b=window.event);b=b.target?b.target:b.srcElement;c=this.pj;var d;c.eR.Y().isRTLMode()?"gecko"==c.platform||"ie"==c.platform?c=Math.abs(b.scrollLeft):(c=$J(c.eR.yd.firstChild),d=parseInt(b.style.width,10),c=Math.max(0,c-d-b.scrollLeft)):c=b.scrollLeft;this.scrollTo(c,b.scrollTop)};
function tL(b,c,d){0!=c&&0!=d&&(c>d?d=0:c=0);c=Math.max(0,Math.min(b.ABa,b.nj-c));d=Math.max(0,Math.min(b.zBa,b.ng-d));ZJ(b.pj,b.yd,c);b.yd.scrollTop=d}
C.scrollTo=function(b,c){this.nj=b;this.ng=c;b+OK(this)<this.Ys||b>this.fh||c+PK(this)<this.Nl||c>this.jf?nK(this,b,c):uL(this,b,c);var d;d=b+$J(this.lb);if(this.jf<c+kK(this.lb)||this.Nl>c||this.fh<d-2||this.Ys>b)this.YK=o;else{this.YK=t;dL(this);jL(this);var e,f,g;d=this.yd.firstChild;e=kK(d);f=$J(d);g=this.lb.firstChild;if(this.jf>e||this.Bd.getCount("row")==this.Nd&&!XK(this,"row")&&this.jf<e)BK(d,this.jf),BK(g,this.jf);if(this.fh>f||this.Bd.getCount("column")==this.og&&!XK(this,"column")&&this.fh<
f)wK(d,this.fh),wK(g,this.fh);this.WA!=r&&(this.WA.focus(),this.WA=r)}};function jL(b){var c,d,e;c=b.nj;d=b.ng;e=b.lb.firstChild;window.hasOwnProperty("WebKitCSSMatrix")&&(new WebKitCSSMatrix).hasOwnProperty("m11")?e.style.webkitTransform=b.Y().isRTLMode()?"translate3d("+c+"px, "+-d+"px, 0)":"translate3d("+-c+"px, "+-d+"px, 0)":(b=b.Y().isRTLMode()?"right":"left",zK(e,-c,b),zK(e,-d,"top"))}
function dL(b){var c,d,e,f;c=b.nj;d=b.ng;e=b.Vd.firstChild;f=b.Wd.firstChild;window.hasOwnProperty("WebKitCSSMatrix")&&(new WebKitCSSMatrix).hasOwnProperty("m11")?(e.style.webkitTransform=b.Y().isRTLMode()?"translate3d("+c+"px, 0, 0)":"translate3d("+-c+"px, 0, 0)",f.style.webkitTransform="translate3d(0, "+-d+"px, 0)"):(b=b.Y().isRTLMode()?"right":"left",zK(e,-c,b),zK(f,-d,"top"))}
function nK(b,c,d){var e,f;d=Math.round(Math.max(0,d-b.getHeight()/2)/b.Ml);c=Math.round(Math.max(0,c-b.getWidth()/2)/b.Un);e=d*b.Ml;f=c*b.Un;b.Hc=d;b.Nd=d;b.Km=d;b.Jm=d;b.Nl=e;b.jf=e;b.Vx=e;b.Wn=e;b.md=c;b.og=c;b.oj=c;b.Xs=c;b.Ys=f;b.fh=f;b.YA=f;b.Vn=f;b.fetchHeaders("row",d,b.Wd,m,{success:function(b,c){vL(this,b,c,e)}});b.fetchHeaders("column",c,b.Vd,m,{success:function(b,c){this.Vd.firstChild.innerHTML="";this.aS(b,c)}});b.fetchCells(b.lb,b.yd,d,c,r,r,{success:function(b,c){wL(this,b,c,e)}})}
function vL(b,c,d,e){var f=b.Wd.firstChild;headerResizer=f.firstChild.cloneNode();f.innerHTML="";f.appendChild(headerResizer);BK(headerResizer,e);b.aS(c,d)}function wL(b,c,d,e){databodyContent=b.lb.firstChild;databodyResizer=databodyContent.firstChild.cloneNode();databodyContent.innerHTML="";databodyContent.appendChild(databodyResizer);BK(databodyResizer,e);b.o3(c,d)}
function uL(b,c,d){var e,f,g;e=c+$J(b.lb);if(e>b.Vn||e==b.Vn&&(XK(b,"column")||MK(b))&&!b.XK){if(b.fetchHeaders("column",b.Xs,b.Vd),!MK(b)&&b.Xs-b.oj>b.iM){var h,k,n,p,q;g=b.Vd.firstChild;h=g.childNodes;for(n=k=f=0;n<h.length;n+=1)if(p=h[n],q=k,k=yK(p,"left"),k>b.nj-0){f=n-1;b.oj+=f;b.YA=q;break}for(h=0;h<f;h+=1)g.removeChild(g.firstChild),b.eF.splice(0,1);b.nv+=f}}else if(c<b.YA&&(f=Math.max(0,b.oj-QK(b,"column")),g=Math.max(0,b.oj-f),b.fetchHeaders("column",f,b.Vd,g),!MK(b)&&b.Xs-b.oj>b.iM&&(g=
b.Vd.firstChild,f=b.nj+OK(b)+0,!(b.Vn<=f)))){h=g.lastChild;for(k=h.offsetWidth;b.Vn+k>f;)g.removeChild(h),b.Vn-=k,b.Xs-=1,h=g.lastChild,k=h.offsetWidth}if(e>b.fh||e==b.fh&&(XK(b,"column")||MK(b))&&!b.HS){if(b.fetchCells(b.lb,b.yd,b.Hc,b.og,b.Nd-b.Hc),!MK(b)&&b.og-b.md>b.iM&&(c=b.lb.firstChild.childNodes,g=e=0,!(2>c.length))){f=c[1].childNodes;for(h=0;h<f.length;h+=1)if(k=f[h],n=g,g=yK(k,"left"),g>b.nj-0){e=h-1;b.md+=e;b.Ys=n;break}for(g=1;g<c.length;g+=1){f=c[g];for(h=0;h<e;h+=1)f.removeChild(f.firstChild)}}}else if(c<
b.Ys&&(f=Math.max(0,b.md-QK(b,"column")),g=Math.max(0,b.md-f),b.fetchCells(b.lb,b.yd,b.Hc,f,b.Nd-b.Hc,g),!MK(b)&&b.og-b.md>b.iM&&(g=b.lb.firstChild.childNodes,c=b.nj+OK(b)+0,!(b.fh<=c)))){e=g[1];f=e.lastChild;for(f=f.offsetWidth;b.fh+f>c;){for(h=1;h<g.length;h+=1)k=g[h],k.removeChild(k.lastChild);b.fh-=f;b.og-=1;f=e.lastChild;f=f.offsetWidth}}c=d+kK(b.lb);if(c>b.Wn||c==b.Wn&&(XK(b,"row")||MK(b))&&!b.$K){if(b.fetchHeaders("row",b.Jm,b.Wd),!MK(b)&&b.Jm-b.Km>b.GB&&(e=b.Wd.firstChild,g=e.firstChild,f=
kK(g),!(f>=b.ng-0))){h=g.nextSibling;for(k=h.offsetHeight;f+k<b.ng-0;)e.removeChild(h),b.fF.splice(0,1),b.VA-=1,b.Vx+=k,b.Km+=1,f+=k,h=g.nextSibling,k=h.offsetHeight;BK(g,f)}}else if(Math.max(0,d-0)<b.Vx){if(0==b.Km)return;e=Math.max(0,b.Km-QK(b,"row"));g=Math.max(0,b.Km-e);b.fetchHeaders("row",e,b.Wd,g);if(!MK(b)&&b.Jm-b.Km>b.GB&&(e=b.Wd.firstChild,g=b.ng+PK(b)+0,!(b.Wn<=g))){f=e.lastChild;for(h=f.offsetHeight;b.Wn+h>g;)e.removeChild(f),b.Wn-=h,b.Jm-=1,f=e.lastChild,h=f.offsetHeight}}c>b.jf||c==
b.jf&&(XK(b,"row")||MK(b))&&!b.ZK?(b.fetchCells(b.lb,b.yd,b.Nd,b.md,r,b.og-b.md),!MK(b)&&b.Nd-b.Hc>b.GB&&xL(b,b.lb)):Math.max(0,d-0)<b.Nl&&0!=b.Hc&&(c=Math.max(0,b.Hc-QK(b,"row")),d=Math.max(0,b.Hc-c),b.fetchCells(b.lb,b.yd,c,b.md,d,b.og-b.md),!MK(b)&&b.Nd-b.Hc>b.GB&&yL(b,b.lb))}
function xL(b,c){var d,e,f,g,h;d=c.firstChild;e=d.firstChild;f=kK(e);if(!(f>=b.ng-0)){g=e.nextSibling;for(h=g.offsetHeight;f+h<b.ng-0;){d.removeChild(g);b.Nl+=h;b.Hc+=1;f+=h;g=e.nextSibling;if(g==r)break;h=g.offsetHeight}BK(e,f)}}function yL(b,c){var d,e,f,g;d=c.firstChild;e=b.ng+PK(b)+0;if(!(b.jf>e)){f=d.lastChild;for(g=f.offsetHeight;b.jf+g>e;)d.removeChild(f),b.jf-=g,b.Nd-=1,f=d.lastChild,g=f.offsetHeight}}C.FAa=function(){this.UK=o};
C.GAa=function(){this.UK=t;hK(this)&&this.YK&&uL(this,this.nj,this.ng)};
C.vAa=function(b,c,d){var e,f;e=b.target;f=sL(this,e);if(c===this.ov.getMappedCommand("resizeHeight"))zL(this)&&(e=f!=r?AL(this,f,"row").firstChild:bK(this,e),IK(this,e,"resizeHeight",d));else if(c===this.ov.getMappedCommand("resizeWidth"))zL(this)&&(e=f!=r?AL(this,f,"column"):bK(this,e),IK(this,e,"resizeWidth",d));else if(c===this.ov.getMappedCommand("sortColAsc")||c===this.ov.getMappedCommand("sortColDsc"))c=c===this.ov.getMappedCommand("sortColAsc")?"ascending":"descending",f!=r?(e=AL(this,f,"column"),
BL(this,e)&&e!=r&&dK(this,b,e,c)):BL(this,e)&&cK(this,b,c);else if(c===this.ov.getMappedCommand("sortRowAsc")||c===this.ov.getMappedCommand("sortRowDsc"))c=c===this.ov.getMappedCommand("sortRowAsc")?"ascending":"descending",f!=r?(e=AL(this,f,"row"),BL(this,e)&&e!=r&&dK(this,b,e,c)):BL(this,e)&&cK(this,b,c)};fK.prototype.handleContextMenuReturn=fK.prototype.vAa;
function BL(b,c){if(XJ(c,b.Y().getMappedStyle("sortascending"))||XJ(c,b.Y().getMappedStyle("sortdescending")))c=c.parentNode.parentNode;return"true"==c.getAttribute(b.Y().getMappedAttribute("sortable"))}function pL(b){return"none"!=CL(b.Bc)}function DL(b){return"multiple"==CL(b.Bc)}function zL(b){var c=tK(b.Bc,"row");b=tK(b.Bc,"column");return"disable"!==c.width||"disable"!==c.height||"disable"!==b.width||"disable"!==b.height}
function cL(b,c,d){var e=tK(b.Bc,c,d);return"column"==c?"function"==typeof e.width?"enable"==e.width.call(b,d)?o:t:"enable"==e.width?o:t:"row"==c?"function"==typeof e.height?"enable"==e.height.call(b,d)?o:t:"enable"==e.height?o:t:t}C=fK.prototype;
C.CAa=function(b){if(zL(this)&&this.wS==t)if(this.xS===t)XJ(b.target,this.Y().getMappedStyle("colheadercell"))||XJ(b.target,this.Y().getMappedStyle("rowheadercell"))?(this.Ux=sK(this,b),document.body.style.cursor=this.Ux):(this.Ux="default",document.body.style.cursor="default");else{var c;this.J3=b.pageX;this.lja=b.pageY;b=XJ(this.ue,this.Y().getMappedStyle("colheadercell"))?"column":"row";"col-resize"===this.Ux?"column"===b?(b=isNaN($J(this.ue))?50:$J(this.ue),c=EK(this,"column",b),vK(this,b,c)):
"row"===b&&(b=$J(this.Wd),c=EK(this,"row",b),DK(this,b,c)):"row-resize"===this.Ux&&("row"===b?(b=isNaN(kK(this.ue.parentNode))?lK(this):kK(this.ue.parentNode),c=FK(this,"row",b),AK(this,b,c)):"column"===b&&(b=kK(this.Vd),c=FK(this,"column",b),CK(this,b,c)));JK(this);this.L3=this.J3;this.qja=this.lja}};C.Jia=function(b){b.preventDefault();if(zL(this)&&("col-resize"===this.Ux||"row-resize"===this.Ux))this.xS=o,this.L3=b.pageX,this.qja=b.pageY,this.zS=this.CS=this.BS=this.VK=this.AS=this.XA=0};
C.DAa=function(b){b.preventDefault();if(zL(this)){var c;this.xS===o&&(c="col-resize"===this.Ux?this.ue.style.width:this.ue.style.height,b={event:b,ui:{header:this.ue,size:c}},this.fireEvent("resize",b),this.xS=t,this.Ux=document.body.style.cursor="default")}};C.Lia=function(b){if(BL(this,b.target)){var c,d,e;c=b.target.className;d=this.Y().getMappedStyle("sortascending");e=this.Y().getMappedStyle("sortdescending");c==d||c==e||aK(this,b,t)}};
C.Kia=function(b){if(BL(this,b.target)){var c=r,d,e;b.relatedTarget!=r&&(c=b.relatedTarget.className);d=this.Y().getMappedStyle("sortascending");e=this.Y().getMappedStyle("sortdescending");c==d||c==e||aK(this,b,o)}};C.Iia=function(b){b.preventDefault();BL(this,b.target)&&cK(this,b)};C.$R=function(b){if(pL(this))EL(this,b),DL(this)&&(this.wS=o);else{var c;b=sL(this,b.target);b!=r&&(c=this.createIndex(this.zh(b.parentNode),this.lp(b)));c!=r&&c!=m&&(kL(this,c),this.tE(c))}};
C.xAa=function(b){var c=this.Bc.gk();"cell"===c?WJ(sL(this,b.target),this.Y().getMappedStyle("hover")):"row"===c&&WJ(sL(this,b.target).parentNode,this.Y().getMappedStyle("hover"))};C.yAa=function(b){var c=this.Bc.gk();"cell"===c?UJ(sL(this,b.target),this.Y().getMappedStyle("hover")):"row"===c&&UJ(sL(this,b.target).parentNode,this.Y().getMappedStyle("hover"))};C.wAa=function(b){if(this.wS){var c;c=sL(this,b.target);c!=r&&(c={row:this.zh(c.parentNode),column:this.lp(c)},FL(this,c));this.um(b)}};
C.zAa=function(){this.wS=t};
C.Fia=function(b){var c;if(!(this.uf==r&&this.Md==r))if(this.Md!=r){if(this.Md.elem==document.activeElement){var d;if(this.Md!=r)if(c=b.keyCode,GL(c)){b=c;var e;if(hK(this))switch(this.Y().isRTLMode()&&(37==b?b=39:39==b&&(b=37)),c=this.Md.axis,d=this.Md.index,e=this.Md.elem,b){case 37:"column"===c&&0<d&&(HL(this,d-1,e.previousSibling),VL(this));break;case 39:if("row"===c)HL(this,-1),this.Md=r,b=this.createIndex(d,0),pL(this)?this.iL(b):this.tE(b);else if(XK(this,"column")||d+1<this.Bd.getCount("column"))HL(this,
d+1,e.nextSibling),VL(this);break;case 38:"row"===c&&0<d&&(HL(this,d-1,e.previousSibling),VL(this));break;case 40:if("column"===c)HL(this,-1),this.Md=r,b=this.createIndex(0,d),pL(this)?this.iL(b):this.tE(b);else if(XK(this,"row")||d+1<this.Bd.getCount("row"))HL(this,d+1,e.nextSibling),VL(this)}}else 32==c?pL(this)&&DL(this)&&(c=this.Md.axis,d=this.Md.index,"row"===c?WL(this,d,b):"column"===c&&XL(this,d,b)):13==c&&(c=this.Md.elem,"true"==c.getAttribute(this.Y().getMappedAttribute("sortable"))&&(d=
c.getAttribute(this.Y().getMappedAttribute("sortDir")),dK(this,b,c,d==r||"descending"===d?"ascending":"descending")))}}else if(c=YL(this,this.createRange(this.uf)),!(c==r||c[0]!=document.activeElement)){if(pL(this))if(c=b.keyCode,"actionable"==this.yBa){27==c&&(ZL(this,t),nL(this));if(d=GL(c))d=sL(this,b.target),d=!(0<$L(d).length);d&&(ZL(this,t),d=YJ(this.pj,b),e=b.shiftKey,(c=aM(this,c,e&&!d&&DL(this)))&&this.um(b))}else if(113==c||13==c)ZL(this,o),c=sL(this,b.target),c=$L(c),0<c.length&&c[0].focus();
else if(9==c)b.preventDefault(),b.shiftKey?bM(this):cM(this);else if(GL(c)||36==c||35==c)d=YJ(this.pj,b),e=b.shiftKey,(c=aM(this,c,e&&!d&&DL(this)))&&this.um(b);else if(b.shiftKey&&119==c)this.gF=!this.gF;else{if(32==c&&(d=YJ(this.pj,b),e=b.shiftKey,"cell"==this.Bc.gk()&&DL(this)&&(e&&!d||d)))d?(c=this.uf.column,XL(this,c,b)):(c=this.uf.row,WL(this,c,b))}else dM(b.target)||(c=b.keyCode,GL(c)&&aM(this,c,t));c=sL(this,b.target);if(c!=r&&(c=c.parentNode,d=c.getAttribute(this.Y().getMappedAttribute("expanderIndex")),
d!=r&&!isNaN(d)&&(d=b.keyCode,(37===d||39===d)&&YJ(this.pj,b))))b=this.Bd,e=c.getAttribute(this.Y().getMappedAttribute("key")),c=c.getAttribute("aria-expanded"),39===d?"false"===c&&b.expand(e):"true"===c&&b.collapse(e)}};
function uK(b,c){var d,e;if(c){d=uK(b,c.offsetParent);e=c.parentNode;var f,g;e?(e=document.defaultView.getComputedStyle(e,r),e=e.getPropertyValue("-webkit-transform")||e.getPropertyValue("-moz-transform")||e.getPropertyValue("-ms-transform")||e.getPropertyValue("-o-transform")||e.getPropertyValue("transform"),f=e.substr(7,e.length-8).split(", "),e=isNaN(parseInt(f[4],10))?0:parseInt(f[4],10),g=isNaN(parseInt(f[5],10))?0:parseInt(f[5],10),f=isNaN(parseInt(f[6],10))?0:parseInt(f[6],10),e=[e,g,f]):e=
[0,0,0];return[parseInt(d[0],10)+parseInt(c.offsetLeft,10)+e[0],parseInt(d[1],10)+parseInt(c.offsetTop,10)+e[1]]}return[0,0]}C.Gia=function(b){var c;b.preventDefault();c=0;b.wheelDeltaX?(c=b.wheelDeltaX,b=b.wheelDeltaY):b=b.wheelDelta;tL(this,c,b)};C.JAa=function(b){b.preventDefault();1==b.touches.length?(this.ZA=b.touches[0].pageX,this.$A=b.touches[0].pageY,this.Sx=this.ZA,this.Tx=this.$A,this.M3=this.ZA,this.N3=this.$A,this.yS=0,this.O3=o):this.FK()};
C.IAa=function(b){var c;b.preventDefault();this.O3?(this.Sx=b.touches[0].pageX,this.Tx=b.touches[0].pageY,b=this.Sx-this.M3,c=this.Tx-this.N3,10>Math.abs(b)&&10>Math.abs(c)?(tL(this,b,c),this.yS++):(this.yS=0,this.ZA=this.Sx,this.$A=this.Tx),this.M3=this.Sx,this.N3=this.Tx):this.FK()};
C.HAa=function(b){var c;b.preventDefault();if(this.O3){if(pL(this)&&this.Sx==this.ZA&&this.Tx==this.$A){EL(this,b);return}if(1<this.yS){this.FK();return}b=Math.round(Math.sqrt(Math.pow(this.Sx-this.ZA,2)+Math.pow(this.Tx-this.$A,2)));0<b&&(c=Math.round(180*Math.atan2(this.Tx-this.$A,this.ZA-this.Sx)/Math.PI),0>c&&(c=360-Math.abs(c)),this.QA(b,45>=c&&0<=c?"left":360>=c&&315<=c?"left":135<=c&&225>=c?"right":45<c&&135>c?"down":"up"))}this.FK()};
C.FK=function(){this.O3=t;this.Tx=this.Sx=this.N3=this.M3=this.$A=this.ZA=this.yS=0};C.QA=function(b,c){b+=10;"down"==c?tL(this,0,b):"up"==c?tL(this,0,-b):"left"==c?tL(this,-b,0):"right"==c&&tL(this,b,0)};C.fireEvent=function(b,c){var d;b==r||c==r||(d=this.wga[b],d!=r&&d(c))};C.addListener=function(b,c){this.wga[b]=c};function BK(b,c){b.style.height=c+"px"}function kK(b){return parseInt(b.style.height,10)}function wK(b,c){b.style.width=c+"px"}function $J(b){return parseInt(b.style.width,10)}
function zK(b,c,d){b.style[d]=c+"px"}function yK(b,c){return parseInt(b.style[c],10)}function eM(b,c){var d,e;d=c.row;e=c.column;return-1===d&&-1===e?-1:-1===d?e<b.md?1:e>b.og?2:3:-1===e?d<b.Hc?1:d>b.Nd?2:3:e>=b.md&&e<=b.og&&d>=b.Hc&&d<=b.Nd?3:-1}
C.Mia=function(b){var c,d;c=b.operation;d=b.keys;if("insert"===c)b=b.result,b!=r?(d={axis:"row",start:b.$za("row"),count:b.getCount("row")},c={axis:"column",start:b.$za("column"),count:b.getCount("column")},this.pba(b,[d,c])):(b=this.Bd.indexes(d),3===eM(this,b)?d.row&&this.fetchCells(this.lb,this.yd,b.row,this.md,1,this.og-this.md,{success:this.pba}):(d=b.row*this.Ml,this.yd.scrollTop=d));else if("update"===c)d=this.Bd.indexes(d),3===eM(this,d)&&(d={axis:"row",start:d.row,count:1},b={axis:"column",
start:this.md,count:this.og-this.md},eK(this),this.Bd.fetchCells([d,b],{success:this.Qsa,error:this.q3},{success:this,error:this}));else if("delete"===c){b=d;var e,f,g;Array.isArray(b)||(b=Array(b));for(c=d=0;c<b.length;c++)if(e=b[c],e.row){e=e.row;a:{var h=g=f=m,k=m,n=m;if(this.lb!=r){f=this.lb.firstChild.childNodes;n=this.Y().getMappedAttribute("key");for(h=1;h<f.length;h++)if(g=f[h],k=g.getAttribute(n),k==e){e=g;break a}}e=r}e!=r?(f=kK(e),g=e.nextSibling,eL(g,0-f),e.parentNode.removeChild(e),e.style.display=
"none"):f=this.Ml;this.Nd-=1;this.jf-=f;d+=f}b=this.lb.firstChild;c=this.yd.firstChild;d=kK(b)-d;BK(b,d);BK(c,d);YK(this);this.ZK=t;uL(this,this.nj,this.ng)}else"refresh"===c?nK(this,this.nj,this.ng):"sync"===c&&(this.mk={},this.Vn=this.YA=this.fh=this.Ys=this.Xs=this.oj=this.og=this.md=this.Wn=this.Vx=this.jf=this.Nl=this.Jm=this.Km=this.Nd=this.Hc=0,this.fF=[],this.eF=[],this.nv=this.VA=0,this.UK=this.YK=t,this.oja=this.pja=this.Un=this.Ml=m,this.XK=this.HS=this.$K=this.ZK=t,this.uf=this.FS=r,this.er?
(this.fetchHeaders("row",0,this.Wd,m,{success:function(b,c){vL(this,b,c,0)}}),this.fetchHeaders("column",0,this.Vd,m,{success:function(b,c){this.Vd.firstChild.innerHTML="";this.aS(b,c)}}),this.fetchCells(this.lb,this.yd,0,0,r,r,{success:function(b,c){wL(this,b,c,0)}}),ZK(this)):(this.fetchHeaders("column",0,this.Vd),this.fetchHeaders("row",0,this.Wd),this.fetchCells(this.lb,this.yd,0,0)))};
C.pba=function(b,c){this.er=t;this.o3(b,c,this.Nd>c[0].start);var d,e,f;d=this.lb.firstChild.childNodes[c[0].start-this.Hc+1];d!=r&&(e=this.ng,f=this.ng+kK(this.lb),d=d.offsetTop,e-=d,0<e?tL(this,0,e):(e=f-d,0>e&&tL(this,0,e)));if(!MK(this)){f=this.ng;e=this.ng+kK(this.lb);f>this.Nl?this.Nd-this.Hc>this.GB&&xL(this,this.lb):e<this.jf&&this.Nd-this.Hc>this.GB&&yL(this,this.lb);var g,h;f=rL(this.Bc);if(0<f){e=this.lb.firstChild.childNodes;h=this.Y().getMappedStyle("banded");for(d=1;d<e.length;d++)g=
this.Hc+d-1,1===Math.floor(g/f)%2?XJ(e[d],h)||UJ(e[d],h):XJ(e[d],h)&&WJ(e[d],h)}var k,n;f=fL(this.Bc);if(0<f){e=this.lb.firstChild.childNodes;h=this.Y().getMappedStyle("banded");for(d=1;d<e.length;d+=1){n=e[d].childNodes;for(k=0;k<n.length;k+=1)g=this.md+k,1===Math.floor(g/f)%2?XJ(n[k],h)||UJ(n[k],h):XJ(n[k],h)&&WJ(e[k],h)}}}};
C.Qsa=function(b,c){var d,e,f,g,h;d=c[0].start;e=this.lb.firstChild;f=aL(this.Bc,"cell");g=fL(this.Bc);h=d-this.Hc;var k=e.childNodes[h+1],n=this.md;k.style.left=this.getWidth()+"px";setTimeout(function(){k.innerHTML="";iL(this,b,k,h,f,o,n,t,g);gK(this);setTimeout(function(){k.style.left="0px"},250)}.bind(this),250)};C.tE=function(b){this.uf!=r&&fM(this);this.uf=b;nL(this)};C.zh=function(b){for(var c=this.Hc;b.previousSibling;)c+=1,b=b.previousSibling;return c-1};
C.lp=function(b){for(var c=this.md;b.previousSibling;)c+=1,b=b.previousSibling;return c};function sL(b,c){return b.find(c,"cell")}C.find=function(b,c,d){if(b==r||b==this.Pf)return r;d==m&&(d=this.Y().getMappedStyle(c));return d==r?r:XJ(b,d)?b:this.find(b.parentNode,c,d)};function nL(b){var c=oL(b,b.uf,"active");c!=r&&gM(b,c,o)}
function fM(b,c){var d,e;d=b.createRange(b.uf);d=YL(b,d);d==r||0==d.length?d=m:(e=d[0],d=b.Y().getMappedStyle("active"),d!=r&&WJ(e,d),d=e);c&&(e=b.Y().getMappedStyle("selected"),e!=r&&oL(b,b.uf,e));d!=r&&hM(d)}function oL(b,c,d){var e;e=b.createRange(c);e=YL(b,e);if(!(e==r||0==e.length))return d==m&&(d="selected"),e=e[0],d=b.Y().getMappedStyle(d),d!=r&&(UJ(e,d),c.row&&c.column&&gM(b,e)),e}
function gM(b,c,d){c.setAttribute("tabIndex",0);var e,f,g;e="";b.Wd!=r&&(f=c.parentNode,f=iM(f),-1<f&&(g=b.Wd.firstChild.childNodes,f<g.length&&(e=g[f].id)));b.Vd!=r&&(f=iM(c),-1<f&&(g=b.Vd.firstChild.childNodes,f<g.length&&(e=""==e?g[f].id:[e,g[f].id].join())));e=""==e?UK(b,"state"):[e,UK(b,"state")].join();c.setAttribute("aria-labelledby",e);d!=m&&(b.WA==r||b.WA!=c)&&c.focus()}
function hM(b){b.setAttribute("tabIndex",-1);b.removeAttribute("contenteditable");b.removeAttribute("aria-labelledby")}function AL(b,c,d){if("row"===d){if(b.Wd!=r&&(c=c.parentNode,c=iM(c),-1<c&&(b=b.Wd.firstChild.childNodes,c<b.length)))return b[c]}else if("column"===d&&b.Vd!=r&&(c=iM(c),-1<c&&(b=b.Vd.firstChild.childNodes,c<b.length)))return b[c];return r}
function iM(b){var c,d,e,f;d=b.parentNode.childNodes;e=-1;for(f=0;f<d.length;f+=1){c=d[f];if(c===b)return e+1;"DIV"==c.nodeName&&e++}return e}C.createRange=function(b,c){var d,e,f,g;c&&(b.row<c.row||-1==c.row?(d=b.row,e=c.row):(d=c.row,e=b.row),!isNaN(b.column)&&!isNaN(c.column)?(b.column<c.column||-1==c.column?(f=b.column,g=c.column):(f=c.column,g=b.column),b={row:d,column:f},c={row:e,column:g}):(b={row:d},c={row:e}));return{startIndex:b,endIndex:c}};
function jM(b){return b.endIndex==r?b.startIndex:b.endIndex}
function YL(b,c,d,e){var f,g,h,k,n;d==m&&(d=b.Hc);e==m&&(e=b.Nd);f=c.startIndex;g=jM(c);h=f.row;c=g.row;-1==c&&(c=Number.MAX_VALUE);if(e<h||c<d||!isNaN(f.column)&&!isNaN(g.column)&&(k=f.column,n=g.column,-1==n&&(n=Number.MAX_VALUE),b.og<k||n<b.md))return r;d=[];e=b.lb.firstChild.childNodes;h=Math.max(0,h-b.Hc);c=Math.min(e.length-1,c-b.Hc+1);if(!isNaN(k)&&!isNaN(n)){k=Math.max(0,k-b.md);n=n-b.md+1;for(b=h;b<c;b+=1){h=e[b+1].childNodes;for(f=k;f<Math.min(h.length,n);f+=1)g=h[f],d.push(g)}}else for(b=
h;b<c;b+=1)k=e[b+1],d.push(k);return d}function dM(b){var c=b.tagName;return"INPUT"===c||"TEXTAREA"===c||"SELECT"===c||"BUTTON"===c||"A"===c||b.getAttribute("tabIndex")!=r&&0<=parseInt(b.getAttribute("tabIndex"))}function GL(b){return 38==b||40==b||37==b||39==b}C.createIndex=function(b,c){return b!=r?c!=r?{row:b,column:c}:{row:b}:r};
function HL(b,c,d,e){var f=b.Y().getMappedStyle("active");b.Md!=r&&b.Md.elem!=r&&("row"===b.Md.axis?b.Md.elem.firstChild!=r&&WJ(b.Md.elem.firstChild,f):WJ(b.Md.elem,f));-1!=c&&(b.Md==r&&(b.Md={}),e!=m&&(b.Md.axis=e),b.Md.index=c,d!=r&&(b.Md.elem=d,"row"===b.Md.axis?b.Md.elem.firstChild!=r&&UJ(b.Md.elem.firstChild,f):UJ(b.Md.elem,f)))}
function VL(b){var c,d,e,f;c=b.Md.axis;d=b.Md.index;e=b.Md.elem;"column"===c?f={row:0,column:d}:"row"===c&&(f={row:d,column:0});kL(b,f);b.WA!=r?(e.setAttribute("tabIndex",0),b.WA=e):e!=r&&kM(e)}
function aM(b,c,d){var e,f,g,h,k;if(hK(b)&&(e=d?b.GS:b.uf,e!=r)){b.Y().isRTLMode()&&(37==c?c=39:39==c&&(c=37));k=pL(b)?b.iL.bind(b):b.tE.bind(b);h=t;f=e.row;g=e.column;switch(c){case 37:0<g?("row"==b.Bc.gk()?(c=b.createIndex(b.uf.row,g-1),kL(b,c),b.tE(c)):(c=b.createIndex(f,g-1),kL(b,c),d?FL(b,c):k(c)),h=o):lL(b,f);break;case 39:XK(b,"column")||g+1<b.Bd.getCount("column")?("row"==b.Bc.gk()?(c=b.createIndex(b.uf.row,g+1),kL(b,c),b.tE(c)):(c=b.createIndex(f,g+1),kL(b,c),d?FL(b,c):k(c)),h=o):d||(k(e),
kL(b,e),h=o);break;case 38:0<f?(c=b.createIndex(f-1,g),kL(b,c),d?FL(b,c):k(c),h=o):mL(b,g);break;case 40:XK(b,"row")||f+1<b.Bd.getCount("row")?(c=b.createIndex(f+1,g),kL(b,c),d?FL(b,c):k(c),h=o):d||(k(e),kL(b,e),h=o);break;case 36:c=b.createIndex(f,0);k(c);kL(b,c);h=o;break;case 35:c=XK(b,"column")?b.createIndex(f,Math.max(0,b.og-1)):b.createIndex(f,Math.max(0,b.Bd.getCount("column")-1)),k(c),kL(b,c),h=o}d&&b.gF&&(b.gF=t);return h}}
function mL(b,c){var d,e;b.Vd!=r&&b.Vd.firstChild&&(d=c-b.oj,e=b.Vd.firstChild.childNodes,d<e.length&&(d=e[d],kM(d),b.uf!=r&&(fM(b),b.uf=r,pL(b)&&lM(b)),HL(b,c,d,"column")))}function kM(b){b.setAttribute("tabIndex",0);b.focus()}function lL(b,c){var d,e;b.Wd!=r&&b.Wd.firstChild&&(d=c-b.Km+1,e=b.Wd.firstChild.childNodes,d<e.length&&(d=e[d],kM(d),b.uf!=r&&(fM(b),b.uf=r,pL(b)&&lM(b)),HL(b,c,d,"row")))}
function kL(b,c){var d,e,f,g,h,k,n,p,q;d=c.row;e=c.column;g=f=0;d<b.Hc||d>=b.Nd?(g=d<b.Hc?b.Ml*d:b.Ml*(d+1)-kK(b.lb),g=b.ng-g,b.pv=c):(h=b.lb.firstChild,k=h.childNodes[d-b.Hc+1],h=b.ng,n=b.ng+kK(b.lb),p=parseInt(k.style.top),k=kK(k),p+k>n?g=n-(p+k):p<h&&(g=h-p));!isNaN(e)&&b.pv==r&&(e<b.md||e>=b.og?(f=e<b.md?b.Un*e:b.Un*(e+1)-$J(b.lb),f=b.nj-f,b.pv=c):(h=b.lb.firstChild,k=h.childNodes[d-b.Hc+1],q=k.childNodes[e-b.md],d=yK(q,"left"),e=q.offsetWidth,h=b.nj,n=b.nj+$J(b.lb),d<h?f=h-d:d+e>n&&(f=n-(d+e))));
if(0!=f||0!=g)q!=r&&(b.WA=q),tL(b,f,g)}function bK(b,c,d){d==m&&(d=b.Y().getMappedStyle("headercell"));if(d!=r){if(XJ(c,d))return c;if(c.parentNode)return bK(b,c.parentNode,d)}return r}C.AAa=function(){var b,c;this.uf!=r&&(b=document.activeElement,c=this.Y().getMappedStyle("active"),b!=r&&XJ(b,c)||nL(this))};C.gCa=v("K3");fK.prototype.registerRowExpander=fK.prototype.gCa;function mM(b,c){var d=b.Y().getTranslatedText(c);d!=r&&(b.xBa.innerHTML=d)}fK.prototype.Hia=function(){mM(this,"expand")};
fK.prototype.Eia=function(){mM(this,"collapse")};
function nM(b,c){var d=YL(b,c),e,f,g,h;if(!(d==r||0==d.length))if(f=b.Y().getMappedStyle("selected"),g=b.Y().getMappedStyle("active"),f!=r&&g!=r)for(e=0;e<d.length;e+=1)h=d[e],WJ(h,g),WJ(h,f),hM(h)}function oM(b,c){var d,e,f;if(!(c==r||0==c.length))if(d=b.Y().getMappedStyle("selected"),d!=r)for(e=0;e<c.length;e+=1)f=c[e],UJ(f,d),gM(b,f)}function qL(b,c,d){var e,f,g;f=b.mo();for(e=0;e<f.length;e+=1)g=YL(b,f[e],c,d),oM(b,g)}
fK.prototype.bI=function(b){var c=this.Y().getMappedStyle("selected");return c!=r?XJ(b,c):t};
function EL(b,c){var d,e,f,g;e=sL(b,c.target);e!=r&&(d={row:b.zh(e.parentNode),column:b.lp(e)});if(d!=r&&d!=m){kL(b,d);b.mo().slice(0);f=YJ(b.pj,c);g=c.shiftKey;if(DL(b))if(b.pj.da())if(b.bI(e)){e=d;var h,k,n,p,q;"row"==b.Bc.gk()&&(e=b.createIndex(e.row));d=e.row;e=e.column;f=-1;g=b.mo();for(h=0;h<g.length;h+=1)if(k=g[h],n=k.startIndex,k=jM(k),p=n.row,q=k.row,!(p!=d||q!=d))if(!isNaN(n.column)&&!isNaN(k.column)){if(n=n.column,k=k.column,!(n!=e||k!=e)){f=h;break}}else if(isNaN(e)){f=h;break}-1!=f&&
(nM(b,g[f]),g.splice(f,1))}else pM(b,d);else!f&&!g?b.iL(d):!f&&g?FL(b,d):pM(b,d);else b.iL(d);b.mo();b.um(c)}}function lM(b){var c,d;d=b.mo();for(c=0;c<d.length;c+=1)nM(b,d[c]);b.uf!=r&&"row"==b.Bc.gk()&&fM(b);b.mo().length=0}function ZL(b,c){b.yBa=c?"actionable":"navigation"}function WL(b,c,d){var e;e=b.createIndex(c,0);c=b.createIndex(c,-1);qM(b,e,c,d)}function XL(b,c,d){var e;e=b.createIndex(0,c);c=b.createIndex(-1,c);qM(b,e,c,d)}
function qM(b,c,d,e){lM(b);c=b.createRange(c,d);b.mo().push(c);c=YL(b,c);oM(b,c);b.uf!=r&&(b.GS=b.uf,nL(b));b.um(e)}function bM(b,c){var d;c==m&&(c=b.Pf);d=c.previousElementSibling;d!=r?dM(d)?d.focus():bM(b,d):(d=c.parentNode,d!=r&&(d=d.lastElementChild,d!=r&&dM(d)?d.focus():bM(b,d)))}function cM(b,c){var d;c==m&&(c=b.Pf);d=c.nextElementSibling;d!=r?dM(d)?d.focus():cM(b,d):(d=c.firstElementChild,d!=r&&(dM(d)?d.focus():cM(b,d)))}fK.prototype.mo=function(){this.FS==r&&(this.FS=[]);return this.FS};
fK.prototype.GetSelection=fK.prototype.mo;fK.prototype.pna=function(b){b!=m&&(b==r&&(b=[]),this.FS=b,this.lb!=r&&qL(this,this.Hc,this.Nd),this.um(r))};fK.prototype.SetSelection=fK.prototype.pna;fK.prototype.um=function(b){b={event:b,ui:{selection:this.mo()}};this.fireEvent("select",b)};
function FL(b,c){var d,e,f,g,h;d=b.uf;if(d!=r&&(b.GS=c,"row"==b.Bc.gk()&&(c=b.createIndex(c.row)),d=b.createRange(d,c),e=b.mo(),f=e[e.length-1],g=f.startIndex.row==d.startIndex.row,f.startIndex.column!=r&&d.startIndex.column!=r&&(g=g&&f.startIndex.column==d.startIndex.column),h=f.endIndex.row==d.endIndex.row,f.endIndex.column!=r&&d.endIndex.column!=r&&(h=h&&f.endIndex.column==d.endIndex.column),!g||!h))e.pop(),e.push(d),nM(b,f),d=YL(b,d),oM(b,d),nL(b)}
function pM(b,c){var d,e;d=b.mo();0<d.length&&b.uf!=r&&fM(b,!b.gF);b.uf=c;b.GS=c;"row"==b.Bc.gk()&&(c=b.createIndex(c.row));e=b.createRange(c,c);d.push(e);nL(b);oL(b,c,"selected")}fK.prototype.iL=function(b){this.gF?this.uf!=r&&this.GS==this.uf&&(fM(this),this.mo().pop()):lM(this);pM(this,b)};
function $L(b){var c,d,e,f,g;c=[];if(document.evaluate){b=document.evaluate(".//input|.//select|.//textarea|.//button|.//a|.//INPUT|.//SELECT|.//TEXTAREA|.//BUTTON|.//A",b,r,XPathResult.ANY_TYPE,r);for(d=b.iterateNext();d;)!d.disabled&&(!d.tabIndex||0<d.tabIndex)&&c.push(d),d=b.iterateNext()}else{b=b.getElementsByTagName("*");e=b.length;f=/^INPUT|SELECT|BUTTON|^A\b|TEXTAREA/;for(g=0;g<e;g+=1)d=b[g],d.tagName.match(f)&&(!d.disabled&&(!d.tabIndex||0<d.tabIndex))&&c.push(d)}return c};
function qK(b,c){return"true"===c.getAttribute(b.Y().getMappedAttribute("resizable"))}function rK(b,c){if(XJ(c,b.Y().getMappedStyle("colheadercell"))){if(c.previousSibling!==r)return"true"===c.previousSibling.getAttribute(b.Y().getMappedAttribute("resizable"))}else if(XJ(c,b.Y().getMappedStyle("rowheadercell"))&&c.parentNode.previousSibling.firstChild!==r)return"true"===c.parentNode.previousSibling.firstChild.getAttribute(b.Y().getMappedAttribute("resizable"));return t}
function sK(b,c){var d=c.target,e,f,g,h,k,n,p,q,d=c.target;if(XJ(d,b.Y().getMappedStyle("colheadercell")))e="column",n="enable"===tK(b.Bc,e).height?o:t,k=qK(b,d),p=rK(b,d);else if(XJ(d,b.Y().getMappedStyle("rowheadercell")))e="row",k="enable"===tK(b.Bc,e).width?o:t,n=qK(b,d),p=rK(b,d);else return"default";g=c.pageX;h=c.pageY;q=d;var s,u;s=uK(b,q);f=s[0];s=s[1];XJ(q,b.Y().getMappedStyle("colheadercell"))?(u=isNaN($J(q))?50:$J(q),q=kK(b.Vd)):(u=$J(b.Wd),q=isNaN(kK(q))?lK(b):kK(q));f=[f,s,f+u,s+q];q=
b.Y().isRTLMode();if(k&&(q?g<f[0]+5:g>f[2]-5))return b.ue=d,"col-resize";if("column"===e&&p&&(q?g>f[2]-5:g<f[0]+5))if(b.ue=d.previousSibling,b.ue!==r)return"col-resize";return n&&h>f[3]-5?(b.ue=d,"row-resize"):"row"===e&&(p&&h<f[1]+5)&&(b.ue=d.parentNode.previousSibling.firstChild,b.ue!==r)?"row-resize":"default"}
function vK(b,c,d){var e;c=d-c;e=$J(b.yd.firstChild)+c;if(e>=$J(b.lb)){wK(b.yd.firstChild,e);wK(b.lb.firstChild,e);wK(b.Vd.firstChild,e);xK(b);wK(b.ue,d);var f,g,h,k,n,p,q;f=b.Y().isRTLMode()?"right":"left";g=b.lb.firstChild.childNodes;h=b.ue.parentNode.childNodes;k=t;if(h.length===g[1].childNodes.length){b.lb.style.display="none";b.Vd.style.display="none";for(n=0;n<h.length;n+=1)if(h[n]!==b.ue&&k===o){p=yK(h[n],f)+c;zK(h[n],p,f);for(q=1;q<g.length;q+=1)zK(g[q].childNodes[n],p,f)}else if(h[n]===b.ue){k=
o;b.WK.qj("column",b.ue.getAttribute(b.Y().getMappedAttribute("key")),d);for(q=1;q<g.length;q+=1)wK(g[q].childNodes[n],d)}b.lb.style.display="block";b.Vd.style.display="block"}b.fh+=c;b.Vn+=c;b.Un=e/b.Bd.getCount("column")}else b.XA+=c}
function AK(b,c,d){var e,f;c=d-c;e=kK(b.yd.firstChild)+c;if(e>=kK(b.lb)){BK(b.ue.parentNode,d);f=kK(b.Wd.firstChild)+c;BK(b.Wd.firstChild,f);BK(b.yd.firstChild,e);BK(b.lb.firstChild,e);var g,h,k,n;f=b.lb.firstChild.childNodes;g=b.ue.parentNode.parentNode.childNodes;h=t;if(f.length===g.length){b.lb.style.display="none";b.Wd.style.display="none";for(k=1;k<g.length;k+=1)g[k].firstChild!==b.ue&&h===o?(n=yK(g[k],"top")+c,zK(g[k],n,"top"),zK(f[k],n,"top")):g[k].firstChild===b.ue&&(h=o,b.WK.qj("row",b.ue.parentNode.getAttribute(b.Y().getMappedAttribute("key")),
d),BK(f[k],d));b.lb.style.display="block";b.Wd.style.display="block"}xK(b);b.jf+=c;b.Wn+=c;b.Ml=e/b.Bd.getCount("row")}}function CK(b,c,d){var e,f,g,h;BK(b.Vd,d);b.tS=d+"px";e=b.lb;f=b.yd;g=b.Wd;c=d-c;h=kK(e);BK(e,h-c);zK(e,d,"top");BK(g,h-c);zK(g,d,"top");BK(f,kK(f)-c);zK(f,d,"top");xK(b)}function DK(b,c,d){var e,f,g,h;wK(b.Wd,d);b.ES=d+"px";xK(b);e=b.lb;f=b.yd;g=b.Vd;c=d-c;h=$J(e);b=b.Y().isRTLMode()?"right":"left";wK(e,h-c);zK(e,d,b);wK(g,h-c);zK(g,d,b);wK(f,$J(f)-c);zK(f,d,b)}
function EK(b,c,d){var e,f,g,h,k;e=$J(b.lb);f=b.Y().isRTLMode()?b.L3-b.J3:b.J3-b.L3;g=d+f+b.XA+b.AS+b.CS;h=$J(b.yd.firstChild);k=Math.round($J(b.Pf)/2);h+f+b.XA<e?(b.XA+=f-e+h,g=d+(e-h)):20>g?(b.AS+=f-20+d,g=20):(b.AS=0,b.XA=0);"row"===c&&(g>k?(b.CS+=f-k+d,g=k):b.CS=0);return g}
function FK(b,c,d){var e,f,g,h,k;e=kK(b.lb);f=b.lja-b.qja;g=d+f+b.VK+b.BS+b.zS;h=kK(b.yd.firstChild);k=Math.round(kK(b.Pf)/2);h+f+b.VK<e&&(b.VK+=f-e+h,g=d+e-h);20>g?(b.BS+=f-20+d,g=20):(b.BS=0,b.VK=0);"column"===c&&(g>k?(b.zS+=f-k+d,g=k):b.zS=0);return g}
function xK(b){var c,d,e,f,g,h,k,n,p;c=b.lb;d=b.yd;e=b.Vd;f=b.Wd;g=$J(c);h=kK(c);k=GK(b,h);n=HK(b,g);p=TJ(b.pj);n&&!k&&!b.cr&&!b.dr?k=GK(b,h-p):!n&&k&&!b.cr&&!b.dr?n=HK(b,g-p):n&&(k&&b.cr&&b.dr)&&(!GK(b,h+p)&&!HK(b,g+p))&&(k=n=t);!k&&!n&&b.cr&&b.dr?(wK(c,g+p),BK(c,h+p),wK(e,g+p),BK(f,h+p),d.style.overflow="visible"):!k&&b.dr?(wK(c,g+p),wK(e,g+p)):!n&&b.cr&&(BK(c,h+p),BK(f,h+p));k&&n&&!b.cr&&!b.dr?(d.style.overflow="auto",wK(c,g-p),BK(c,h-p),wK(e,g-p),BK(f,h-p)):k&&!b.dr?(d.style.overflow="auto",wK(c,
g-p),wK(e,g-p)):n&&!b.cr&&(d.style.overflow="auto",BK(c,h-p),BK(f,h-p));b.cr=n;b.dr=k}
function IK(b,c,d,e){e=parseInt(e,10);if(XJ(c,b.Y().getMappedStyle("sortascending"))||XJ(c,b.Y().getMappedStyle("sortdescending"))||XJ(c,b.Y().getMappedStyle("sortindicators")))c=bK(b,c);b.ue=c;"resizeWidth"===d?(c=c.offsetWidth,c!==e&&(XJ(b.ue,b.Y().getMappedStyle("colheadercell"))?qK(b,b.ue)&&vK(b,c,e):DK(b,c,e))):"resizeHeight"===d&&(c=c.offsetHeight,c!==e&&(XJ(b.ue,b.Y().getMappedStyle("colheadercell"))?CK(b,c,e):qK(b,b.ue)&&AK(b,c,e)));JK(b)};
function aK(b,c,d){c=bK(b,c.target);c!=r&&(c=c.lastChild,c!=r&&c.className==b.Y().getMappedStyle("sortindicators")&&(c.style.display=d?"none":"inline-block"))}function cK(b,c,d){var e,f,g,h;e=b.Y().getMappedStyle("sortascending");f=b.Y().getMappedStyle("sortdescending");g=c.target;h=bK(b,g);h!=r&&(c.direction==r&&(g.className==e?d="ascending":g.className==f&&(d="descending")),dK(b,c,h,d))}
function dK(b,c,d,e){var f;d.setAttribute(b.Y().getMappedAttribute("sortDir"),e);f=b.xO(d);var g,h;g=b.Y().getMappedStyle("colheadercell");h=b.Y().getMappedStyle("rowheadercell");d=XJ(d,g)?"column":XJ(d,h)?"row":r;e!=r&&(f!=r&&d!=r)&&(eK(b),d={axis:d,key:f,direction:e},b.Bd.sort(d,{success:b.Ysa.bind(b),error:b.Xsa.bind(b)}),c={event:c,ui:{header:f,direction:e}},b.fireEvent("sort",c))}fK.prototype.Xsa=function(){gK(this)};fK.prototype.xO=function(b){return b.getAttribute(this.Y().getMappedAttribute("key"))};
fK.prototype.Ysa=function(){gK(this);this.fetchCells(this.lb,this.yd,this.Hc,this.md,this.Nd-this.Hc,this.og-this.md,{success:this.uAa,error:this.Dia})};
fK.prototype.uAa=function(b,c){var d,e,f,g;this.mk.cells=t;hK(this)&&gK(this);d=c[0].start;e=b.getCount("row");f=c[1].start;b.getCount("column");g=document.createDocumentFragment();iK(this,g,o,this.Nl,d,e,f,t,b);d=this.lb.firstChild;var h,k,n,p,q,s,u,w,z,A,F,I,L;h=this;k=0;e=d.childElementCount;f=jK(this,d);n=jK(this,g);p=[];k=[];s=this.getHeight()-kK(this.Vd);u=lK(this);(w=parseInt(d.firstElementChild.attributes.style.value.split("height:")[1].split("px")[0],10))||(w=0);w=this.yd.scrollTop-w;s=[w,
w+s];w=[];z=0;I=this.Y().getMappedAttribute("key");for(q=0;q<f.length;q++)p[f[q]]=q;for(A=0;A<n.length;A++)p.hasOwnProperty(n[A])?p[n[A]]>A?(q=p[n[A]]-A,p[n[A]]="up_-"+q):p[n[A]]<A?(q=A-p[n[A]],p[n[A]]="down_"+q):p[n[A]]==A&&(p[n[A]]="no_0"):k[n[A]]=A;for(F in k)k.hasOwnProperty(F)&&(z++,n=k[F],q=s[1]+d.childNodes[1].clientHeight,A=s[0]-d.childNodes[1].clientHeight,L=n*d.childNodes[1].clientHeight,L<q&&L>A&&(n=g.children[n],w.push(n)));for(F=0;F<f.length;F++)p.hasOwnProperty(f[F])&&/^-{0,1}\d*\.{0,1}\d+$/.test(p[f[F]])&&
(p[f[F]]="up_30");for(g=0;g<w.length;g++){for(F=0;F<w[g].attributes.length;F++)z=r,w[g].attributes[F].nodeName==I&&(z=w[g].attributes[F].nodeValue,k.hasOwnProperty(z)&&(z=k[z],mK(w[g],0,0,s[1]-z*u)));d.appendChild(w[g])}for(g=0;g<d.childElementCount;g++)if(F=10*g+"ms",g<e-1?(k=parseInt(p[f[g]].split("_")[1],10)*u,k<s[1]-g*u||(k=s[1]-(g-1)*d.childNodes[1].clientHeight),mK(d.childNodes[g+1],"400ms",F,k)):mK(d.childNodes[g+1],"400ms",F,0),g==d.childElementCount-2){d.childNodes[g].addEventListener("transitionend",
function(){setTimeout(function(){nK(h,h.nj,h.ng)},1E3)},t);break}};function jK(b,c){var d,e,f,g;d=[];e=b.Y().getMappedAttribute("key");for(f=0;f<c.childElementCount;f++)for(g=0;g<c.children[f].attributes.length;g++)if(c.children[f].attributes[g].nodeName==e){d.push(c.children[f].attributes[g].nodeValue);break}return d}
function oK(b){function c(b){return b.replace(/\-([a-z])/gi,function(b,c){return c.toUpperCase()})}var d,e,f,g;d=" -moz- -webkit- -o- -ms- -khtml-".split(" ");e=document.documentElement;for(f=0;f<d.length;f++)if(g=c(d[f]+b),"Ms"==g.substr(0,2)&&(g="m"+g.substr(1)),g in e.style)return g}function pK(b,c,d){"undefined"!=typeof c&&(b.style[c]=d)}
function mK(b,c,d,e){pK(b,oK("transition-delay"),d);pK(b,oK("transition-timing-function"),"linear");pK(b,oK("transition-duration"),c);pK(b,oK("transform"),"translate3d(0,"+e+"px,0)")};
return DvtDataGrid;
});