define(['./DvtToolkit', './DvtAxis'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.WK=(0,D.v)();(0,D.ta)("DvtGauge",D.WK);D.F.o(D.WK,D.Zd,"DvtGauge");D.WK.prototype.Init=function(b,c,d,e){D.WK.u.Init.call(this,b,c,d);this.ad=new D.lA;e||(this.va=this.WD(),this.va.nf(this),(0,D.Vb)()||(0,D.Ch)(this.va,this.mx(this.va)),this.setId("gauge1000"+window.Math.floor(1E9*window.Math.random())),this.hB=new D.H(b,0,0),(0,D.Xb)(this.hB),this.k(this.hB));this.JA=D.t;this.bG=D.q};
D.WK.prototype.Wd=function(b){this.Q=b;(0,D.Ti)()||(this.Q.animationOnDisplay="none",this.Q.animationOnDataChange="none")};
D.WK.prototype.M=function(b,c,d){b?this.Wd(b):this.Q||this.Wd(D.q);this.Q.thresholds&&(this.Q.thresholds=this.Q.thresholds.sort(D.ZK));!(0,window.isNaN)(c)&&!(0,window.isNaN)(d)&&(this.rb=c,this.Lb=d);d=this.dv;this.dv=[];c=new D.G(this.e);this.Fa(c,0);this.ti(c,this.rb,this.Lb);var e=b!=D.q,f=this.rb,g=this.Lb;this.nb&&this.nb.stop();b=D.t;var h=this.JA?"none":this.xa().animationOnDataChange,j=this.JA?"none":this.xa().animationOnDisplay,m=this.xa().animationDuration/1E3;if(j||h){f=new D.M(0,0,f,
g);g=this.e;if(!this.ha&&"none"!==j&&this.dv[0]!=D.q)this.nb=D.ad.xH(g,j,c,f,m),this.nb||(this.nb=this.bX(this.dv,j,m));else if(this.ha&&"none"!=h&&e&&this.dv[0]!=D.q)if(this.nb=D.ad.rz(g,h,this.ha,c,f,m))b=D.n;else{e=this.dv;h=[];for(j=0;j<d.length;j++){var f=e[j],o=d[j].Pd(),g=f.Pd();f.pe(o);o=new D.Sb(this.e,f,m);(0,D.P)(o.S,"typeNumberArray",f,f.Pd,f.pe,g);h.push(o)}this.nb=new D.Cn(this.e,h)}b||this.removeChild(this.ha);this.nb&&(this.nb.play(),this.nb.qd(this.aC,this));b&&(this.Ik=this.ha);
this.ha=c}this.hB&&(this.Q.readOnly===D.t&&(0,D.Vb)()?(this.hB.ia(this.rb),this.hB.ta(this.Lb)):(this.hB.ia(0),this.hB.ta(0)));(0,D.tb)(c,"img");d=D.nA.yV(this);(0,D.ic)(c,"label",d)};D.WK.prototype.render=D.WK.prototype.M;D.D=D.WK.prototype;D.D.ti=(0,D.v)();D.D.bX=(0,D.ba)(D.q);D.D.Uu=(0,D.ba)(D.q);D.D.aC=function(){this.Ik&&(this.removeChild(this.Ik),this.Ik=D.q);this.nb=D.q};D.D.AJ=(0,D.C)("ad");D.D.xa=(0,D.C)("Q");D.D.Va=(0,D.C)("va");D.D.NP=function(){this.JA=D.n;this.bG=this.Q.value};
D.D.MP=function(b,c){this.Q.value=D.nA.rU(this.Q,this.Uu(b,c));this.M();this.Ya(new D.LA(this.bG,this.Q.value,D.t))};D.D.LP=function(b,c){this.MP(b,c);this.Ya(new D.LA(this.bG,this.Q.value,D.n));this.JA=D.t;this.bG=D.q};D.D.WD=function(){return new D.wA(this)};D.ZK=function(b,c){return b.max&&c.max?b.max-c.max:b.max?-window.Infinity:window.Infinity};D.WK.prototype.Ji=function(){return new D.vA(this)};D.WK.prototype.getAutomation=D.WK.prototype.Ji;D.WK.prototype.mx=function(b){return new D.KA(b,this)};
D.vA=(0,D.A)("ee");(0,D.ta)("DvtGaugeAutomation",D.vA);D.F.o(D.vA,D.fb,"DvtGaugeAutomation");D.vA.prototype.getValue=function(){return this.ee.xa().value};D.vA.prototype.getValue=D.vA.prototype.getValue;D.vA.prototype.eDa=function(){return D.nA.Jq(this.getValue(),this.ee)};D.vA.prototype.getMetricLabel=D.vA.prototype.eDa;
D.lA=(0,D.v)();D.F.o(D.lA,D.mA,"DvtGaugeBundle");D.lA._defaults={EMPTY_TEXT:"No data to display"};D.lA.prototype.ho=function(b){return D.lA._defaults[b]};D.lA.prototype.nx=(0,D.ba)("DvtGaugeBundle");
D.kA=(0,D.v)();D.F.o(D.kA,D.db,"DvtGaugeDefaults");D.pA={skin:"alta",color:"#393737",metricLabel:{style:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};D.qA={skin:"skyros",min:0,max:100,color:"#313842",borderColor:D.q,visualEffects:"auto",emptyText:D.q,animationOnDataChange:"none",animationOnDisplay:"none",animationDuration:500,readOnly:"true",metricLabel:{rendered:"off",scaling:"auto",style:new D.O,textType:"number"},__layout:{outerGap:1,labelGap:3}};
D.kA.prototype.Init=function(b){b={skyros:D.Ta.Bb(b.skyros,D.qA),alta:D.Ta.Bb(b.alta,D.pA)};D.kA.u.Init.call(this,b)};D.rA=function(b){return"skyros"==b.xa().skin};
D.oA={};D.F.o(D.oA,D.F,"DvtGaugeDataUtils");D.oA.uu=function(b){b=b.xa();return!b||(0,window.isNaN)(b.value)||b.value===D.q?D.t:D.n};D.oA.VC=function(b,c){var d=b.xa(),e=c?c:d.value,d=d.thresholds;if(!d)return-1;for(var f=0;f<d.length;f++)if(e<=d[f].max)return f;return d.length-1};D.oA.GH=function(b,c){var d=b.xa().thresholds;return d&&0<=c&&c<d.length?d[c]:D.q};D.oA.hKa=function(b,c){var d=b.xa().referenceLines;return d&&0<=c&&c<d.length?d[c]:D.q};
D.wA=function(b){this.Init(b.e,b.Ya,b);this.ee=b;this.Tk=D.t};D.F.o(D.wA,D.Uc,"DvtGaugeEventManager");D.D=D.wA.prototype;D.D.il=function(b){this.ee.xa().readOnly===D.t?(this.Tk=D.n,this.sc(),b=(0,D.xA)(this,b.pageX,b.pageY),this.ee.NP(b.x,b.y)):D.wA.u.il.call(this,b)};D.D.Zm=function(b){this.Tk?(this.Tk=D.t,b=(0,D.xA)(this,b.pageX,b.pageY),this.ee.LP(b.x,b.y)):D.wA.u.Zm.call(this,b)};
D.D.Ep=function(b){if(this.Tk){var c=(0,D.xA)(this,b.pageX,b.pageY);this.ee.MP(c.x,c.y)}(this.eaa()||!this.Tk)&&D.wA.u.Ep.call(this,b)};D.D.eaa=(0,D.ba)(D.t);
D.D.kJ=function(b){if(D.Jt.Xd===b.type&&this.ee.xa().readOnly===D.t){this.Tk=D.n;var c=(0,D.xA)(this,b.touches[0].pageX,b.touches[0].pageY);this.ee.NP(c.x,c.y);b.preventDefault()}else D.Jt.Bh===b.type&&this.Tk?(c=(0,D.xA)(this,b.touches[0].pageX,b.touches[0].pageY),this.ee.MP(c.x,c.y),b.preventDefault()):D.Jt.gg===b.type&&this.Tk?(this.Tk=D.t,c=(0,D.xA)(this,b.changedTouches[0].pageX,b.changedTouches[0].pageY),this.ee.LP(c.x,c.y),b.preventDefault()):D.wA.u.kJ.call(this,b)};
D.xA=function(b,c,d){c=(0,D.Fa)(b.e,c,d);return b.ee.Cb(c)};
D.KA=function(b,c){this.Init(b,c)};D.F.o(D.KA,D.Ec,"DvtGaugeKeyboardHandler");D.KA.prototype.Init=function(b,c){D.KA.u.Init.call(this,b);this.ee=c};
D.KA.prototype.Vn=function(b){var c=b.keyCode,d=(0,D.ya)(this.ee.e);if(38==c||c==(d?37:39))c=this.ee,d=c.Q.value,c.Q.value=c.Q.step!=D.q?D.nA.rU(c.Q,c.Q.value+c.Q.step):window.Math.min(window.Math.max(c.Q.value+(c.Q.max-c.Q.min)/100,c.Q.min),c.Q.max),c.M(),c.Ya(new D.LA(d,c.Q.value,D.n)),b.preventDefault();else if(40==c||c==(d?39:37))c=this.ee,d=c.Q.value,c.Q.value=c.Q.step!=D.q?D.nA.rU(c.Q,c.Q.value-c.Q.step):window.Math.min(window.Math.max(c.Q.value-(c.Q.max-c.Q.min)/100,c.Q.min),c.Q.max),c.M(),
c.Ya(new D.LA(d,c.Q.value,D.n)),b.preventDefault()};
D.uA={};D.F.o(D.uA,D.F,"DvtGaugeStyleUtils");D.uA.$ba=["#ed6647","#fad55c","#68c182"];D.uA.Yba=["#D62800","#FFCF21","#84AE31"];D.uA.Yba=["#D62800","#FFCF21","#84AE31"];D.uA.ira={Wl:202.5,ks:225,Bn:100,Cn:103,Es:{x:80,y:86,width:40,height:34},xs:0.85,Ns:20,Os:30,op:60,Cs:6};D.uA.jra={Wl:202.5,ks:225,Bn:100,Cn:103,Es:{x:83,y:86,width:34,height:34},xs:0.85,Ns:20,Os:30,op:60,Cs:6};D.uA.lra={Wl:202.5,ks:225,Bn:100,Cn:103,Es:{x:83,y:86,width:34,height:34},xs:0.85,Ns:20,Os:30,op:60,Cs:6};
D.uA.mra={Wl:220.5,ks:261.1,Bn:100,Cn:100,Es:{x:82,y:133,width:36,height:34},xs:0.85,Ns:20,Os:30,op:61,Cs:6};D.uA.nra={Wl:195.5,ks:210.8,Bn:100,Cn:100,Es:{x:84,y:135,width:32,height:35},xs:0.98,Ns:20,Os:30,op:63,Cs:6};D.uA.pra={Wl:207.6,ks:235,Bn:100,Cn:95.8,Es:{x:83,y:125,width:34,height:40},xs:1.05,Ns:20,Os:30,op:64,Cs:6};D.uA.Yra={Wl:220.5,ks:261.1,Bn:100,Cn:100,Es:{x:80,y:82,width:40,height:40},xs:0.82,Ns:20,Os:30,op:58,Cs:6};
D.uA.Zra={Wl:201,ks:222,Bn:100.2,Cn:89,Es:{x:80,y:70,width:41,height:39},xs:1.23,Ns:20,Os:30,op:56,Cs:6};D.uA.asa={Wl:211,ks:242,Bn:100,Cn:91.445,Es:{x:78,y:75,width:44,height:38},xs:1.1,Ns:20,Os:30,op:58,Cs:6};D.uA.Ara={Wl:220.5,ks:261.5,Es:{x:80,y:82,width:40,height:40},xs:0.85,Ns:20,Os:30,op:60,Cs:6};D.uA.Bra={Wl:201,ks:222,Bn:100.2,Cn:89,Es:{x:80,y:73,width:40,height:36},xs:1.23,Ns:20,Os:30,op:56,Cs:6};
D.uA.Dra={Wl:201,ks:222,Bn:100.2,Cn:99.5,Es:{x:80,y:83,width:41,height:36},xs:1.1,Ns:20,Os:30,op:58,Cs:6};D.uA.ora={Bn:42,Cn:510};D.uA.kra={Bn:187,Cn:388};D.uA.$ra={Bn:227,Cn:425};D.uA.Cra={Bn:227,Cn:425};D.uA.Fb=function(b){var c=b.xa(),d=D.oA.VC(b),e=D.oA.GH(b,d);return e&&(!(b instanceof D.GA)||b instanceof D.GA&&"onIndicator"==c.thresholdDisplay)?D.uA.mN(b,e,d):c.color};
D.uA.sh=function(b){var c=b.xa(),d=D.oA.GH(b,D.oA.VC(b));return d&&d.borderColor&&(!(b instanceof D.GA)||b instanceof D.GA&&"onIndicator"==c.thresholdDisplay)?d.borderColor:c.borderColor};D.uA.Fla=function(b){var c=b.xa(),d=D.oA.VC(b),e=D.oA.GH(b,d);return e&&(!(b instanceof D.GA)||b instanceof D.GA&&"onIndicator"!=c.thresholdDisplay)?D.uA.mN(b,e,d):c.plotArea.color};D.uA.mN=function(b,c,d){if(c.color)return c.color;if(d<D.uA.$ba.length)return(0,D.rA)(b)?D.uA.Yba[d]:D.uA.$ba[d]};
D.uA.ACa=function(b){return"rectangleAlta"===b?D.uA.lra:"domeAlta"===b?D.uA.jra:"circleAntique"===b?D.uA.mra:"rectangleAntique"===b?D.uA.pra:"domeAntique"===b?D.uA.nra:"circleLight"===b?D.uA.Yra:"rectangleLight"===b?D.uA.asa:"domeLight"===b?D.uA.Zra:"circleDark"===b?D.uA.Ara:"rectangleDark"===b?D.uA.Dra:"domeDark"===b?D.uA.Bra:D.uA.ira};D.uA.BCa=function(b){return"needleAntique"===b?D.uA.ora:"needleLight"===b?D.uA.$ra:"needleDark"===b?D.uA.Cra:D.uA.kra};
D.nA={};D.F.o(D.nA,D.F,"DvtGaugeRenderer");D.nA.tZ=2;D.nA.Iba=1;D.nA.Tz=function(b,c,d){var e=b.xa(),f=e.emptyText;f||(f=(0,D.ec)(b.AJ(),"EMPTY_TEXT",D.q));var g=d.g-2*D.nA.tZ,h=d.j-2*D.nA.Iba;d=new D.Ya(b.e,f,d.x+d.g/2,d.y+d.j/2);e.metricLabel.style.A("font-size")||e.metricLabel.style.X("font-size","13px");d.Ga(e.metricLabel.style);d.Af();d.Pe();D.Pb.Tb(d,g,h,c)&&d.bg()&&b.Va().la(d,new D.Xq(f))};
D.nA.Jq=function(b,c){var d=c.xa(),e="percent"==d.metricLabel.textType;e&&(b=100*D.nA.vH(d,d.min,b));var f=D.q;"on"==d.metricLabel.rendered&&d.metricLabel.converter&&(f=d.metricLabel.converter);var g=D.q;"on"==d.metricLabel.rendered&&d.metricLabel.scaling&&(g=d.metricLabel.scaling);return D.nA.uea(b,c,f,g,d.metricLabel.autoPrecision?d.metricLabel.autoPrecision:"on",e)};
D.nA.LU=function(b,c){var d=c.xa(),e="percent"==d.tickLabel.textType;e&&(b=100*D.nA.vH(d,d.min,b));var f=D.q;"on"==d.tickLabel.rendered&&d.tickLabel.converter&&(f=d.tickLabel.converter);var g=D.q;"on"==d.tickLabel.rendered&&d.tickLabel.scaling&&(g=d.tickLabel.scaling);return D.nA.uea(b,c,f,g,d.tickLabel.autoPrecision?d.tickLabel.autoPrecision:"on",e)};
D.nA.uea=function(b,c,d,e,f,g){var h=c.xa();c=b;c=h.min;var h=h.max,j=h-c,m=D.q;(0,window.isNaN)(j)||(m=j/(1E3>j?100:1E3));e=new D.Aq(c,h,m,e,f);if(d&&d.getAsString)c=e.Cq(b,d);else{if(d&&d.format)return e.Cq(b,d);c=e.Cq(b)}return g?(0,window.String)(c)+"%":c};D.nA.vH=function(b,c,d){b=(d-c)/(b.max-b.min);return b=window.Math.min(window.Math.max(0,b),1)};D.nA.yV=function(b){var c=b.xa(),d=D.oA.GH(b,D.oA.VC(b));return d&&d.shortDesc!=D.q?d.shortDesc:c.shortDesc!=D.q?c.shortDesc:D.nA.Jq(c.value,b)};
D.nA.o8=function(b,c,d,e){var f=b.xa();if("on"==f.metricLabel.rendered){var g=D.nA.Jq(f.value,b),h=d.g,j=d.j;b=new D.Ya(b.e,g,d.x+d.g/2,d.y+d.j/2);b.Ga(f.metricLabel.style);var m=f.metricLabel.style.A("font-size");if(!f.metricLabel.style.A("font-size")){var m=window.Math.max(f.max.toString().length,f.min.toString().length,g.length),o="";"percent"==f.metricLabel.textType&&(m=window.Math.max(3,g.length),o+="%");for(f=0;f<m;f++)o+="0";b.xd(o);m=b.Kw(d);b.xd(g);b.Ef(m)}b.Pe();b.Af();e!=D.q&&b.na(e);D.Pb.Tb(b,
h,j,c)&&b.ja(D.t)}};D.nA.rU=function(b,c){var d=(0,window.Number)(b.step);if(d&&0<d){var e=(c-b.min)/d;return 0.5<e?window.Math.max(window.Math.min(b.max,window.Math.round(e)*d+b.min),b.min):b.min}return c};
D.YK=(0,D.v)();(0,D.ta)("DvtLedGauge",D.YK);D.F.o(D.YK,D.WK,"DvtLedGauge");D.dv=function(b,c,d,e){var f=new D.YK;f.Init(b,c,d,e);return f};D.YK.newInstance=D.dv;D.YK.prototype.Init=function(b,c,d,e){D.YK.u.Init.call(this,b,c,d,e);this.ff=new D.NA};D.YK.prototype.Wd=function(b){D.YK.u.Wd.call(this,this.ff.Pg(b));"auto"==this.Q.animationOnDisplay&&(this.Q.animationOnDisplay="zoom");"auto"==this.Q.animationOnDataChange&&(this.Q.animationOnDataChange="alphaFade");this.Q.readOnly=D.n};
D.YK.prototype.ti=function(b,c,d){D.tA.M(this,b,c,d)};
D.NA=function(){this.Init({skyros:D.MA,alta:{}})};D.F.o(D.NA,D.kA,"DvtLedGaugeDefaults");D.MA={type:"circle"};
D.tA={};D.F.o(D.tA,D.F,"DvtLedGaugeRenderer");D.tA.ZHa=1/6;D.tA.Msa="M-42,36.6Q-50,36.6,-46.54,28.6L-4,-43.07Q0,-50,4,-43.07L46.54,28.6Q50,36.6,42,36.6Z";D.tA.Hsa=[-50,36.6,0,-50,50,36.6];D.tA.Nsa=[-50,36.6,0,-50,50,36.6];D.tA.Xba=[-13.05,-12.94,-50,-11.13,-21.06,11.9,-30.74,47.6,0.1,27.18,31.06,47.44,21.17,11.79,50,-11.39,13.05,-13.01,-0.06,-47.59];D.tA.Gsa=[-50,-11.22,-16.69,-17.94,0,-47.55,16.69,-17.94,50,-11.22,26.69,13.8,30.9,47.56,0,33.42,-30.9,47.56,-26.69,13.8];D.tA.Ksa="M0,45L21,45Q24.414,44.414,25,41L25,10L42,10Q48.5,9.1,45,4L2,-38Q0,-39,-2,-38L-45,4Q-48.5,9.1,-42,10L-25,10L-25,41Q-24.414,44.414,-21,45Z";
D.tA.Fsa=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];D.tA.Lsa=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];
D.tA.M=function(b,c,d,e){if(D.oA.uu(b)){var f=b.xa(),g=f.__layout.outerGap,h=f&&(0<=f.size||1>f.size)?window.Math.sqrt(f.size):1;d=new D.M(g+(d-2*g)*(1-h)/2,g+(e-2*g)*(1-h)/2,(d-2*g)*h,(e-2*g)*h);D.tA.aM(b,c,d);D.tA.H3(b,c,d);"on"==f.metricLabel.rendered&&(f.metricLabel.style.A("color")!=D.q?D.nA.o8(b,c,D.tA.Jea(b,d),D.q):(e=D.uA.Fb(b),e=D.U.Jl(e),f.metricLabel.style.X("color",e),D.nA.o8(b,c,D.tA.Jea(b,d),e)))}else D.nA.Tz(b,c,new D.M(0,0,d,e))};
D.tA.aM=function(b,c,d){var e=b.e,f=b.xa(),g=f.type,h=D.uA.Fb(b),j=D.uA.sh(b),m=d.x+d.g/2,o=d.y+d.j/2,p=window.Math.min(d.g,d.j)/2,r=(0,D.rA)(b),u,w=window.Math.min(d.g/100,d.j/100);"rectangle"==g?e=new D.H(e,d.x,d.y,d.g,d.j):"diamond"==g?e=new D.Ma(e,[m-p,o,m,o-p,m+p,o,m,o+p]):"star"==g||"triangle"==g||"arrow"==g?("star"==g?u=r?D.tA.Xba:D.tA.Gsa:"triangle"==g?u=r?D.tA.Msa:D.tA.Hsa:"arrow"==g&&(u=r?D.tA.Ksa:D.tA.Fsa),r&&"triangle"==g||r&&"arrow"==g?(u=window.DvtPathUtils.JW(u,d.x+d.g/2,d.y+d.j/2,
w,w),e=new D.Ra(e,u)):(u=D.Er.scale(u,w,w),u=D.Er.translate(u,d.x+d.g/2,d.y+d.j/2),e=new D.Ma(e,u))):e=new D.Yf(e,m,o,p);r||"none"==f.visualEffects?e.na(h):(m=[D.U.ug(h,-0.09,0.04),D.U.ug(h,-0.04,-0.05)],o=f&&0==f.rotation%90?f.rotation:0,e.H(new D.Gd("arrow"==g||"star"==g||"triangle"==g?o-90:270,m,[1,1],[0,1])));j&&e.La(j);j=b.Va();(m=D.nA.yV(b))&&j&&j.la(e,new D.Xq(D.q,m,h));o=r?f.rotation+90:f.rotation;if(0!=o&&("arrow"==g||"triangle"==g))e=D.tA.N3(b,c,e,d);c.k(e)};
D.tA.N3=function(b,c,d,e){var f=b.xa();b=new D.G(b.e);c.k(b);b.k(d);c=f&&0==f.rotation%90?f.rotation:0;f=new D.sd;f.rotate(window.Math.PI*c/180);d.qa(f);c=b.D();d=e.x+e.g/2-(c.x+c.g/2);e=e.y+e.j/2-(c.y+c.j/2);c=new D.sd;c.translate(d,e);b.qa(c);return b};D.tA.H3=function(b,c,d){var e=b.xa(),f=e.type;"none"!=e.visualEffects&&(0,D.rA)(b)&&("rectangle"==f?D.tA.tza(b,c,d):"diamond"==f?D.tA.sza(b,c,d):"triangle"==f?D.tA.vza(b,c,d):"star"==f?D.tA.uza(b,c):"arrow"==f?D.tA.qza(b,c,d):D.tA.rza(b,c,d))};
D.tA.tza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.M(d.x+e,d.y+f,d.g-2*e,d.j-2*f);b=new D.H(b.e,d.x,d.y,d.g,d.j);b.ja(D.t);c.k(b);c=new D.Gd(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.H(c)};
D.tA.sza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j,f=new D.M(d.x+e,d.y+f,d.g-2*e,d.j-2*f);d=f.x+f.g/2;e=f.y+f.j/2;f=window.Math.min(f.g,f.j)/2;b=new D.Ma(b.e,[d-f,e,d,e-f,d+f,e,d,e+f]);b.ja(D.t);c.k(b);c=new D.Gd(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.H(c)};
D.tA.vza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j,g=(0,D.rA)(b),e=new D.M(d.x+e,d.y+f,d.g-2*e,d.j-2*f),f=D.tA.Nsa,h=window.Math.min(e.g/100,e.j/100),f=D.Er.scale(f,h,h),f=D.Er.translate(f,d.x+d.g/2,d.y+d.j/2);d=new D.Ma(b.e,f);f=(f=b.xa())&&0==f.rotation%90?f.rotation:0;g=new D.Gd(g?f-90:360-f,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);d.H(g);d=D.tA.N3(b,c,d,e);d.ja(D.t);c.k(d)};
D.tA.qza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j,g=(0,D.rA)(b),e=new D.M(d.x+e,d.y+f,d.g-2*e,d.j-2*f),f=D.tA.Lsa,h=window.Math.min(e.g/100,e.j/100),f=D.Er.scale(f,h,h),f=D.Er.translate(f,d.x+d.g/2,d.y+d.j/2);d=new D.Ma(b.e,f);f=(f=b.xa())&&0==f.rotation%90?f.rotation:0;g=new D.Gd(g?f-90:360-f,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);d.H(g);d=D.tA.N3(b,c,d,e);d.ja(D.t);c.k(d)};
D.tA.uza=function(b,c){var d=new D.Ra(b.e,D.tA.Xba),e=b.xa(),e=360-(e&&0==e.rotation%90?e.rotation:0),f=D.uA.Fb(b),f=[D.U.Kl(f,0.9),f,D.U.Nka(f)],e=new D.Gd(e,f,[1,1,1],[0.1,0.4,0.8]);d.H(e);d.ja(D.t);c.k(d)};
D.tA.rza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.M(d.x+e,d.y+f,d.g-2*e,d.j-2*f);var e=d.x+d.g/2,f=d.y+d.j/2,g=window.Math.min(d.g,d.j)/2,h=new D.Yf(b.e,e,f,g);h.ja(D.t);c.k(h);var j=new D.oe(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.25,0.5],[0.15,0.7,0.95],e,f-0.6*g,1.5*g,[d.x,d.y,d.g,d.j]);h.H(j);h=0.6*g;g*=0.4;f-=0.3*g;b=new D.Ax(b.e,e,f-g,h,g);b.ja(D.t);c.k(b);c=new D.oe(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.2,0.5],[0.6,0.8,1],e,f,h,[d.x,d.y,d.g,d.j]);b.H(c)};
D.tA.Jea=function(b,c){var d=b.xa(),e=d.type,d=0==d.rotation%90?d.rotation:0,f=window.Math.min(c.g,c.j),g=c.x+c.g/2-f/2,h=c.y+c.j/2-f/2,j=f,m=f;"triangle"==e?0==d?(g+=0.2*f,h+=0.25*f,j-=0.4*f,m-=0.3*f):90==d?(g+=0.05*f,h+=0.2*f,j-=0.3*f,m-=0.4*f):180==d?(g+=0.2*f,h+=0.05*f,j-=0.4*f,m-=0.3*f):270==d&&(g+=0.25*f,h+=0.2*f,j-=0.3*f,m-=0.4*f):"arrow"==e?0==d?(g+=0.2*f,h+=0.2*f,j-=0.4*f,m-=0.4*f):90==d?(g+=0.05*f,h+=0.2*f,j-=0.28*f,m-=0.4*f):180==d?(g+=0.2*f,h+=0.2*f,j-=0.4*f,m-=0.4*f):270==d&&(g+=0.23*
f,h+=0.2*f,j-=0.28*f,m-=0.4*f):"star"==e?(g+=0.25*f,h+=0.25*f,j-=0.5*f,m-=0.4*f):"diamond"==e?(g+=0.15*f,h+=0.15*f,j-=0.3*f,m-=0.3*f):"rectangle"==e?(g+=0.1*f,h+=0.1*f,j-=0.2*f,m-=0.2*f):"circle"==e&&(g+=0.15*f,h+=0.15*f,j-=0.3*f,m-=0.3*f);return new D.M(g,h,j,m)};
D.GA=(0,D.v)();(0,D.ta)("DvtStatusMeterGauge",D.GA);D.F.o(D.GA,D.WK,"DvtStatusMeterGauge");D.cv=function(b,c,d){var e=new D.GA;e.Init(b,c,d);return e};D.GA.newInstance=D.cv;D.D=D.GA.prototype;D.D.Init=function(b,c,d){D.GA.u.Init.call(this,b,c,d);this.ff=new D.JA;this.FZ=D.q};D.D.Wd=function(b){D.GA.u.Wd.call(this,this.ff.Pg(b))};D.D.ti=function(b,c,d){D.FA.M(this,b,c,d)};
D.D.bX=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.Pd();"horizontal"==this.Q.orientation||"vertical"==this.Q.orientation?f.pe([g[0],g[0],g[2],g[3]]):f.pe([g[0],g[1],0,g[3],g[4]]);var h=new D.Sb(this.e,f,d);(0,D.P)(h.S,"typeNumberArray",f,f.Pd,f.pe,g);h.S.Dj(function(b){return(0,D.vF)(b,0.7)});c.push(h)}return new D.Cn(this.e,c)};
D.D.Uu=function(b,c){if("horizontal"==this.Q.orientation)return this.FZ.EC(b);if("vertical"==this.Q.orientation)return this.FZ.EC(c);if("circular"==this.Q.orientation){var d=D.Cq.l8(window.Math.atan2(c-this.Lb/2,b-this.rb/2))-270,d=(d+720)%360;0<=d&&360>=d||(d=360<d?360-d<d-360?0:360:0-d<d?0:360);if((0,D.ya)(this.e))for(d=360-d;0>d;)d+=360;var e=this.Q.min;return d/360*(this.Q.max-e)+e}};
D.JA=function(){this.Init({skyros:D.HA,alta:D.IA})};D.F.o(D.JA,D.kA,"DvtStatusMeterGaugeDefaults");D.IA={color:"#393737",metricLabel:{style:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},plotArea:{color:"#f5f6f7",borderColor:"#D6DFE6"}};D.HA={color:"#313842",indicatorSize:1,metricLabel:{style:new D.O("color: #333333;")},orientation:"horizontal",plotArea:{color:"#AAAAAA",borderColor:"#C6C6C6",rendered:"auto"},thresholdDisplay:"onIndicator"};
D.FA={};D.F.o(D.FA,D.F,"DvtStatusMeterGaugeRenderer");D.FA.M=function(b,c,d,e){if(D.oA.uu(b)){var f=b.xa(),g=f.__layout.outerGap;d=new D.M(g,g,d-2*g,e-2*g);"horizontal"==f.orientation||"vertical"==f.orientation?(D.FA.Yr(b,c,d),D.FA.aM(b,c,d)):"circular"==f.orientation&&(f=window.Math.min(d.g,d.j),D.nA.o8(b,c,new D.M(d.x+d.g/2-0.325*f,d.y+d.j/2-0.25*f,0.65*f,0.5*f),D.q),D.FA.Zya(b,c,d))}else D.nA.Tz(b,c,new D.M(0,0,d,e))};
D.FA.Zya=function(b,c,d){var e=b.xa(),f=0,g=e.value,h=e.thresholds,j=window.Math.min(d.g,d.j),m=0.3125*j,o=0.4625*j,p=1.5*window.Math.PI,f=2*f*window.Math.PI;if(h&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(var r=0;r<h.length;r++){var u=D.uA.mN(b,h[r],r),f=h[r].max?h[r].max:e.max,w=0==r?e.min:h[r-1].max,p=1.5*window.Math.PI+2*window.Math.PI*D.nA.vH(e,e.min,w),f=D.nA.vH(e,w,f),f=2*f*window.Math.PI;D.FA.H0(b,c,d,p,f,m,o,u,D.t)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&
"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(u=D.uA.Fla(b),p=1.5*window.Math.PI,f=2*window.Math.PI,D.FA.H0(b,c,d,p,f,m,o,u,D.n));if((h=e.indicatorSize)&&1!=h)j*=0.075*(1-h),m+=j,o-=j;p=1.5*window.Math.PI;f=D.nA.vH(e,e.min,g);f=2*f*window.Math.PI;D.FA.H0(b,c,d,p,f,m,o,D.uA.Fb(b),D.t);if(m=e.referenceLines)for(o=0;o<m.length;o++)j=m[o].color?m[o].color:"black",h=m[o].lineWidth?m[o].lineWidth:2,p=m[o].lineStyle,g=m[o].value,window.angle=1.5*window.Math.PI+2*D.nA.vH(e,e.min,g)*window.Math.PI,
D.FA.Ava(b,c,d,j,h,p);d=new D.H(b.e,d.x,d.y,d.g,d.j);(0,D.Xb)(d);c.k(d);((c=D.nA.yV(b))||b.xa().readOnly===D.t)&&b.Va().la(d,new D.Xq(D.q,c,D.uA.Fb(b)))};
D.FA.aM=function(b,c,d){var e=b.xa(),f=(0,D.ya)(b.e),g="vertical"==e.orientation,h={layout:{}};h.layout.gapRatio=0;h.timeAxisType="disabled";h.position=g?"left":"bottom";h.min=e.min;h.max=e.max;h.dataMin=e.min;h.dataMax=e.max;h.tickLabel={rendered:"off"};h=(0,D.Rs)(b.e,h,d);b.FZ=h;var j=0;0>=e.max?j=e.max:0<=e.min&&(j=e.min);var m=h.Vj(j);"off"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&(m=h.Zc(e.min));var o=h.Zc(e.value),o=g?window.Math.max(d.y,window.Math.min(d.y+
d.j,o)):window.Math.max(d.x,window.Math.min(d.x+d.g,o)),p=0,p=0>e.min&&0>e.value?h.Zc(e.min):h.Zc(e.max),r,u,w,z,B,I,E,j=0;g?(r=d.x,u=d.x+d.g,z=m,w=window.Math.min(d.y,window.Math.min(d.y+d.j,p)),B=d.x+(1-e.indicatorSize)/2*d.g+0.5,I=d.x+d.g*(1-(1-e.indicatorSize)/2)-0.5,j=m-0.5,E=o+0.5):(r=m,u=window.Math.max(d.x,window.Math.max(d.x+d.g,p)),w=d.y,z=d.y+d.j,B=f?m-0.5:m+0.5,I=f?o+0.5:o-0.5,E=d.y+(1-e.indicatorSize)/2*d.j+0.5,j=d.y+d.j*(1-(1-e.indicatorSize)/2)-0.5);p=D.n;o==m&&(p=D.t);var J=D.uA.sh(b),
L=e.plotArea.borderColor,N=e.thresholds,m=g?0:270;if(N&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(o=N.length-1;0<=o;o--){var R=o,S=D.FA.wv(b,b.e,r,u,w,z,D.n),ea=new D.td("pacp"+b.getId());o==N.length-1?g?(0,D.ud)(ea,0,0,d.g+2,z-w+2,0,0):f?(0,D.ud)(ea,h.Zc(e.max),0,d.g+2,z-w+2,0,0):(0,D.ud)(ea,0,0,d.g+2,z-w+2,0,0):g?(0,D.ud)(ea,0,h.Zc(e.max),u-r+2,1*window.Math.abs(e.max-N[N.length-2-R].max)/window.Math.abs(e.min-e.max)*d.j,0,0):f?(0,D.ud)(ea,0,0,1*(e.max-(N[N.length-2-R].max==D.q?
100:N[N.length-2-R].max))/window.Math.abs(e.min-e.max)*d.g,z-w+2,0,0):(0,D.ud)(ea,0,0,1*window.Math.abs(N[R].max-e.min)/window.Math.abs(e.min-e.max)*d.g,z-w+2,0,0);(0,D.vd)(S,ea);if(f||g)R=N.length-1-o;S.na(D.uA.mN(b,N[R],R));S.La(L);D.FA.tia(b,c,S,D.uA.mN(b,N[R],R),m)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(S=g?D.FA.wv(b,b.e,r,u,h.Zc(e.max),h.Zc(e.min),D.n):D.FA.wv(b,b.e,h.Zc(e.min),h.Zc(e.max),w,z,D.n),o=D.uA.Fla(b),
S.na(o),S.La(L),D.FA.tia(b,c,S,o,m));o=D.FA.wv(b,b.e,B,I,E,j,D.n);b.dv.push(o);f=D.uA.Fb(b);!(0,D.rA)(b)&&"none"!=e.visualEffects?(r=[D.U.ug(f,-0.09,0.04),D.U.ug(f,-0.04,-0.05)],r=new D.Gd(m,r,[1,1],[0,1]),o.H(r)):o.na(f);J&&o.La(J);p&&c.k(o);j=D.FA.wv(b,b.e,B,I,E,j,D.n);D.FA.H3(b,c,j,p,m);if(j=e.referenceLines)for(o=0;o<j.length;o++)f=j[o].color?j[o].color:"white",p=j[o].value,B=e.indicatorSize,g?(window.referenceLineSize=((1-B)/2+B)*d.g,window.xCoord=d.x+(1-B)/4*d.g,window.yCoord=h.Zc(p),window.referenceLine=
new D.Lp(b.e,window.xCoord,window.yCoord,window.xCoord+window.referenceLineSize,window.yCoord)):(window.referenceLineSize=((1-B)/2+B)*d.j,window.xCoord=h.Zc(p),window.yCoord=d.y+(1-B)/4*d.j,window.referenceLine=new D.Lp(b.e,window.xCoord,window.yCoord,window.xCoord,window.yCoord+window.referenceLineSize)),p=new D.Hb(f,1,j[o].lineWidth?j[o].lineWidth:2),j[o].lineStyle&&p.X((0,D.Gr)(j[o].lineStyle)),window.referenceLine.Z(p),p=new D.Ck(D.U.Hu(0,0,0,0.8),0.75,3,3,50,1,2,D.t,D.t,D.t),c.k(window.referenceLine),
(0,D.Cb)(window.referenceLine,p);d=new D.H(b.e,d.x,d.y,d.g,d.j);(0,D.Xb)(d);c.k(d);((c=D.nA.yV(b))||e.readOnly===D.t)&&b.Va().la(d,new D.Xq(D.q,c,f))};D.FA.wv=function(b,c,d,e,f,g,h){return new window.DvtStatusMeterGaugeIndicator(b,c,d,e,f,g,h)};D.FA.H3=function(b,c,d,e,f){"none"!=b.xa().visualEffects&&(0,D.rA)(b)&&(f=new D.Gd(f,["#FFFFFF","#FFFFFF","#FFFFFF"],[0.5,0.3125,0],[0,0.3,1]),d.H(f),b.dv.push(d),d.ja(D.t),e&&c.k(d))};
D.FA.tia=function(b,c,d,e,f){var g=b.xa();d.ja(D.t);c.k(d);"none"!=g.visualEffects&&((0,D.rA)(b)?(b=[D.U.Kl(e,0.9),e,D.U.Nka(e)],f=new D.Gd(f,b,[1,1,1],[0,0.04,0.73])):(b=[D.U.ug(e,-0.04,-0.05),D.U.ug(e,-0.09,0.04)],f=new D.Gd(f,b,[1,1],[0,1])),d.H(f))};
D.FA.Yr=function(b,c,d){var e=b.xa(),f=(0,D.ya)(b.e),g="vertical"==e.orientation,h=new D.Ya(b.e,""),j=D.nA.Jq(e.value,b),m=e.__layout.labelGap;h.Ga(e.metricLabel.style);if(g&&"on"==e.metricLabel.rendered){var o=0<e.max?e.max:e.min,o=D.nA.Jq(o,b),p=new D.Ya(b.e,o);p.Ga(e.metricLabel.style);f=new D.M(d.x,d.y+0.8*d.j,d.g,0.2*d.j);g=(g=e.metricLabel.style.A("font-size"))?(0,window.parseInt)(g):p.Kw(f);p=p.Vb();d.j-=p.j;window.labelSpace=p.g;h.Ef(g);h.xd(j);h.fa(d.x+d.g/2);h.ra(d.y+d.j);d.j-=m;h.Af();
D.Pb.Tb(h,d.g,d.j,c)}else if(!g&&"on"==e.metricLabel.rendered){var g=(g=e.metricLabel.style.A("font-size"))?(0,window.parseInt)(g):13,r=D.nA.Jq(e.min,b),p=D.nA.Jq(e.max,b),p=window.Math.max(p.toString().length,r.toString().length),r="";"percent"==e.metricLabel.textType&&(p=3,r+="%");for(var u=0;u<p;u++)r+="0";h.xd(r);18>d.j&&(g=h.Kw(d));h.Ef(g);if(0<e.max||"off"!=e.plotArea.rendered||!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay))o=0<e.max?e.max:e.min,o=D.nA.Jq(o,b),p=new D.Ya(b.e,
o),p.Ga(e.metricLabel.style),p.Ef(g),p=h.Vb(),o=f?d.x+p.g:d.x+d.g,window.labelSpace=p.g,f&&(d.x+=p.g+m),d.g-=p.g+m;if(0>e.min&&"on"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)){g=D.nA.Jq(e.min,b);r=new D.Ya(b.e,g);r.Ga(e.metricLabel.style);b=r.Vb();if(0>e.value||0>=e.max)o=f?d.x+d.g:d.x+b.g,window.labelSpace=b.g;f||(d.x+=b.g+m);d.g-=b.g+m}h.xd(j);h.fa(o);h.ra(d.y+d.j/2);h.Pe();h.Gi();D.Pb.Tb(h,window.labelSpace,d.j,c)}};
D.FA.ot=function(b,c,d){return{x:window.Math.cos(d)*c+b.g/2+b.x,y:window.Math.sin(d)*c+b.j/2+b.y}};D.FA.H0=function(b,c,d,e,f,g,h,j,m){var o=b.e;(0,D.ya)(b.e)&&(e=window.Math.PI-e-f,e=0<e?e:e+2*window.Math.PI);d=new D.DA(o,d,e,f,g,h);b.dv.push(d);d.na(j);(b=D.uA.sh(b))&&!m&&d.La(b);c.k(d)};
D.FA.Ava=function(b,c,d,e,f,g){var h=window.angle,j=b.e,m=window.Math.min(d.g,d.j),o=0.275*m,m=0.5*m;(0,D.ya)(b.e)&&(h=window.Math.PI-h,h=0<h?h:h+2*window.Math.PI);window.p1=D.FA.ot(d,o,h);window.p2=D.FA.ot(d,m,h);b=new D.Lp(j,window.p1.x,window.p1.y,window.p2.x,window.p2.y);e=new D.Hb(e,1,f);g&&e.X((0,D.Gr)(g));b.Z(e);c.k(b)};
window.DvtStatusMeterGaugeIndicator=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.o(window.DvtStatusMeterGaugeIndicator,D.H,"DvtStatusMeterGaugeIndicator");window.DvtStatusMeterGaugeIndicator.isa=2.5;window.DvtStatusMeterGaugeIndicator.prototype.Init=function(b,c,d,e,f,g,h){window.DvtStatusMeterGaugeIndicator.u.Init.call(this,c);this.ee=b;this.Fza=h;this.oxa="vertical"==b.xa().orientation;this.Wz(d,e,f,g)};
window.DvtStatusMeterGaugeIndicator.prototype.Wz=function(b,c,d,e){this.ep=b;this.fp=c;this.CAa=d;this.DAa=e;var f=window.Math.min(b,c),g=window.Math.min(d,e);b=window.Math.abs(b-c);d=window.Math.abs(e-d);(0,D.Qb)(this,f,g,b,d);this.Fza&&(f=(this.oxa?b:d)*((0,D.rA)(this.ee)?0.25:0.15),f>=window.DvtStatusMeterGaugeIndicator.isa&&(0,D.cl)(this,f,f))};window.DvtStatusMeterGaugeIndicator.prototype.Pd=function(){return[this.ep,this.fp,this.CAa,this.DAa]};
window.DvtStatusMeterGaugeIndicator.prototype.pe=function(b){b&&4==b.length&&this.Wz(b[0],b[1],b[2],b[3])};
D.DA=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.o(D.DA,D.Ra,"DvtStatusMeterGaugeCircularIndicator");D.DA.prototype.Init=function(b,c,d,e,f,g){D.DA.u.Init.call(this,b);(0,D.EA)(this,c,d,e,f,g)};
D.EA=function(b,c,d,e,f,g){var h,j,m;c&&c instanceof D.M?b.Ja=c:c=b.Ja;b.Tc=d;b.bd=e;b.di=f;b.Kh=g;e<2*window.Math.PI?(h=D.FA.ot(c,g,d),j=D.FA.ot(c,g,d+e),m=D.FA.ot(c,f,d+e),c=D.FA.ot(c,f,d),g=window.DvtPathUtils.moveTo(h.x,h.y)+window.DvtPathUtils.arcTo(g,g,e,1,j.x,j.y)+window.DvtPathUtils.lineTo(m.x,m.y)+window.DvtPathUtils.arcTo(f,f,e,0,c.x,c.y)+window.DvtPathUtils.closePath()):(h=D.FA.ot(c,g,d),j=D.FA.ot(c,g,d+e/2),m=D.FA.ot(c,f,d),c=D.FA.ot(c,f,d+e/2),g=window.DvtPathUtils.moveTo(h.x,h.y)+window.DvtPathUtils.arcTo(g,
g,e/2,1,j.x,j.y)+window.DvtPathUtils.arcTo(g,g,e/2,1,h.x,h.y),0<f&&(g+=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(f,f,e/2,0,m.x,m.y)+window.DvtPathUtils.arcTo(f,f,e/2,0,c.x,c.y)),g+=window.DvtPathUtils.closePath());b.ek(g)};D.DA.prototype.Pd=function(){return[this.Ja,this.Tc,this.bd,this.di,this.Kh]};D.DA.prototype.pe=function(b){b&&5==b.length&&(0,D.EA)(this,b[0],b[1],b[2],b[3],b[4])};
D.VK=(0,D.v)();(0,D.ta)("DvtDialGauge",D.VK);D.F.o(D.VK,D.WK,"DvtDialGauge");D.ev=function(b,c,d){var e=new D.VK;e.Init(b,c,d);return e};D.VK.newInstance=D.ev;D.D=D.VK.prototype;D.D.Init=function(b,c,d){D.VK.u.Init.call(this,b,c,d);this.ff=new D.jA;this.EZ=D.q};
D.D.Wd=function(b){var c=b.background,d=b.indicator;"string"===typeof c&&(b.background=D.uA.ACa(c),b.background.images=b._backgroundImages);"string"===typeof d&&(b.indicator=D.uA.BCa(d),b.indicator.images=b._indicatorImages);D.VK.u.Wd.call(this,this.ff.Pg(b))};D.D.ti=function(b,c,d){D.OA.M(this,b,c,d)};
D.D.bX=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.Pd(),h=D.OA.fta(this);f.Vg(h);h=new D.Sb(this.e,f,d);(0,D.P)(h.S,"typeNumberArray",f,f.Pd,f.pe,g);h.S.Dj(function(b){return(0,D.vF)(b,0.7)});c.push(h)}return new D.Cn(this.e,c)};
D.D.Uu=function(b,c){var d=D.Cq.l8(window.Math.atan2(c-this.EZ.y,b-this.EZ.x));0>=d&&(d+=360);var e=(0,D.ya)(this.e),f=this.xa().background,g=e?180+f.startAngle:360-f.startAngle,f=f.angleExtent,h=g+f;if(e){h=g;for(g-=f;0>g;)g+=360,h+=360}d+360>=g&&d+360<=h?d+=360:d>=g&&d<=h||(d=d>h?g+360-d<d-h?g:h:g-d<d+360-h?g:h);d=(d-g)/f;e&&(d=1-d);e=this.Q.min;return d*(this.Q.max-e)+e};
D.jA=function(){this.Init({skyros:D.iA,alta:{}})};D.F.o(D.jA,D.kA,"DvtDialGaugeDefaults");D.iA={background:{startAngle:180,angleExtent:180,indicatorLength:0.7},metricLabel:{style:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},tickLabel:{scaling:"auto",style:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};
D.OA={};D.F.o(D.OA,D.F,"DvtDialGaugeRenderer");D.OA.M=function(b,c,d,e){D.oA.uu(b)?(d=new D.M(0,0,d,e),D.OA.aM(b,c,d),D.OA.Yr(b,c,d)):D.nA.Tz(b,c,new D.M(0,0,d,e))};
D.OA.aM=function(b,c,d){var e=b.xa(),f=D.OA.b0(b,d);c.k(f);e.background.majorTickCount&&e.background.radius&&D.OA.xza(b,c,d);var g=D.OA.bva(b,d),h=new D.G(b.e),j=new D.sA(b.e);c.k(h);h.k(j);j.k(g);var m=g.D(),o=D.OA.Nea(b,e.value),f=D.OA.Bea(b,d),p=D.OA.gwa(b,m);d=D.OA.hwa(b,d,m);m=new D.sd;m.translate(-p.x,-p.y);m.scale(d,d);g.qa(m);j.Vg(o);m=new D.sd;m.translate(f.x,f.y);h.qa(m);b.dv.push(j);((e=e.shortDesc)||b.xa().readOnly===D.t)&&b.Va().la(c,new D.Xq(D.q,e));b.EZ=f};
D.OA.b0=function(b,c){var d=b.xa().background,e=(0,D.ya)(b.e),f=(0,D.Vb)(),g=f?2*c.g:c.g,h=f?2*c.j:c.j,j=d.images;if(j&&0<j.length){var m,o,p,f=[];for(m=0;m<j.length;m++){var r="rtl"==j[m].dir;e&&r?f.push(j[m]):!e&&!r&&f.push(j[m])}j=0<f.length?f:j;for(m=0;m<j.length;m++){var u=j[m],r=u.src,f=u.width,u=u.height,w=r&&-1<r.search(".svg");0==m&&(o=f,p=u);if(w||f>=g&&u>=h||m==j.length-1){var g=new D.Wb(b.e,r,0,0,f,u),z=new D.sd,h=window.Math.min(c.g/f,c.j/u),j=(c.g-h*f)/2;m=(c.j-h*u)/2;z.scale(h,h);z.translate(j,
m);g.qa(z);w&&(0,D.ub)()&&(r=D.ol.zj(b.e,r,D.F.qj(g,g.IZ)))&&g.IZ(r);c.x+=j;c.y+=m;c.g=h*f;c.j=h*u;!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=e?c.x+c.g-c.g*d.anchorX/o:c.x+c.g*d.anchorX/o,d._anchorY=c.y+c.j*d.anchorY/p);d.metricLabelBounds&&(f={},f.width=c.g*d.metricLabelBounds.width/o,f.height=c.j*d.metricLabelBounds.height/p,f.y=c.y+c.j*d.metricLabelBounds.y/p,f.x=e?c.x+c.g-c.g*d.metricLabelBounds.x/o-f.width:c.x+c.g*d.metricLabelBounds.x/o,d._metricLabelBounds=f);e=
window.Math.min(c.g/o,c.j/p);d._radius=d.radius*e;d._tickLabelHeight=d.tickLabelHeight*c.j/p;d._tickLabelWidth=d.tickLabelWidth*c.g/o;return g}}}return D.q};
D.OA.bva=function(b,c){var d=b.xa().indicator,e=D.OA.Hea(b,c),f=(0,D.Vb)()?2*e:e,g,h,j=d.images;if(j&&0<j.length)for(var m=0;m<j.length;m++){var o=j[m],e=o.src,p=o.width,o=o.height,r=e&&-1<e.search(".svg");0==m&&(g=p,h=o);if(r||o>=f||m==j.length-1)return f=new D.Wb(b.e,e,0,0,p,o),r&&(0,D.ub)()&&D.ol.zj(b.e,e,D.F.qj(f,f.IZ))&&(f.ia(p),f.ta(o)),!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=d.anchorX*p/g,d._anchorY=d.anchorY*o/h),f}return D.q};
D.OA.fta=function(b){var c=b.xa().background;b=(0,D.ya)(b.e)?180-c.startAngle:c.startAngle;return window.Math.PI*(90-b)/180};D.OA.Nea=function(b,c){var d=b.xa(),e=d.background,f=d.min,d=d.max;c=window.Math.max(window.Math.min(c,d),f);f=(c-f)/(d-f);d=(0,D.ya)(b.e);return window.Math.PI*(90-((d?180-e.startAngle:e.startAngle)-f*(d?-e.angleExtent:e.angleExtent)))/180};
D.OA.Bea=function(b,c){var d=b.xa().background,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.K(e,d):new D.K(c.x+c.g/2,c.y+c.j/2)};D.OA.Hea=function(b,c){var d=window.Math.min(c.g,c.j)/2;return b.xa().background.indicatorLength*d};D.OA.gwa=function(b,c){var d=b.xa().indicator,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.K(e,d):new D.K(c.x+c.g/2,c.y+c.j)};D.OA.hwa=function(b,c,d){return D.OA.Hea(b,c)/d.j};
D.OA.Yr=function(b,c,d){var e=b.xa();if("on"==e.metricLabel.rendered){var f=D.nA.Jq(e.value,b),g=d.x+d.g/2,h=d.y+d.j/2,j=d.g,m=d.j,o=e.background._metricLabelBounds;o&&(g=o.x+o.width/2,h=o.y+o.height/2,d.g=o.width,d.j=o.height);g=new D.Ya(b.e,f,g,h);!e.metricLabel.style.A("color")&&e.background._isDark&&e.metricLabel.style.X("color","#CCCCCC");g.Ga(e.metricLabel.style);h=(0,window.parseInt)(e.metricLabel.style.wH());if(!h){h=window.Math.max(D.nA.Jq(e.max,b).length,D.nA.Jq(e.min,b).length,f.length);
o="";"percent"==e.metricLabel.textType&&(h=window.Math.max(3,f.length),o+="%");for(e=0;e<h;e++)o+="0";g.xd(o);h=g.Kw(d);g.xd(f);g.Ef(h)}g.Af();g.Pe();D.Pb.Tb(g,j,m,c)&&g.bg()&&b.Va().la(g,new D.Xq(f))}};
D.OA.xza=function(b,c,d){var e=b.xa(),f=(0,D.ya)(b.e);if(e.background.radius&&e.background.majorTickCount){var g=e.background._radius,h=e.min,j=e.max,m=e.background.majorTickCount,o=12,p=new D.M(B,w,d.g,d.j),r=e.metricLabel.style.A("font-size");e.background._tickLabelHeight&&!r&&(p.j=e.background._tickLabelHeight);e.background._tickLabelWidth&&!r&&(p.g=e.background._tickLabelWidth);if(!r){var u=new D.Ya(b.e,"",B,w),o=window.Math.max(D.nA.LU(e.max,b).length,D.nA.LU(e.min,b).length),r="";"percent"==
e.tickLabel.textType&&(o=window.Math.max(3,D.nA.LU(100,b).length-1),r+="%");for(B=0;B<o;B++)r+="0";u.xd(r);o=u.Kw(p)}for(r=0;r<m;r++){B=h+window.Math.abs(j-h)*r/(m-1);f&&(B=h+window.Math.abs(j-h)*(m-1-r)/(m-1));var u=D.nA.LU(B,b),w=D.OA.Nea(b,B),z=D.OA.Bea(b,d),B=z.x+g*window.Math.cos(w-window.Math.PI/2),w=z.y+g*window.Math.sin(w-window.Math.PI/2),u=new D.Ya(b.e,u,B,w);!e.tickLabel.style.A("color")&&e.background._isDark&&e.tickLabel.style.X("color","#CCCCCC");u.Ga(e.tickLabel.style);e.tickLabel.style.A("font-size")||
u.Ef(o);u.Af();u.Pe();D.Pb.Tb(u,p.g,p.j,c)&&u.bg()&&b.Va().la(u,new D.Xq(u.dp))}}};
D.sA=function(b){this.Init(b)};D.F.o(D.sA,D.G,"DvtDialGaugeIndicator");D.sA.prototype.Vg=function(b){var c=new D.sd;c.rotate(b);this.qa(c);this.Eta=b};D.sA.prototype.Pd=function(){return[this.Eta]};D.sA.prototype.pe=function(b){b&&1==b.length&&this.Vg(b[0])};
D.XK=(0,D.v)();(0,D.ta)("DvtRatingGauge",D.XK);D.F.o(D.XK,D.WK,"DvtRatingGauge");D.fv=function(b,c,d){var e=new D.XK;e.Init(b,c,d);return e};D.XK.newInstance=D.fv;D.XK.prototype.Init=function(b,c,d){D.XK.u.Init.call(this,b,c,d);this.ff=new D.RA};D.XK.prototype.Wd=function(b){D.XK.u.Wd.call(this,this.ff.Pg(b))};
D.XK.prototype.ti=function(b,c,d){var e=this.xa().__layout.outerGap,f=this.Q.max;this.Rj=window.Math.min(d-2*e,(c-2*e)/f);this.Ja=new D.M((this.rb-this.Rj*f)/2,e,this.Rj*f,this.Lb-2*e);D.yA.M(this,b,c,d)};D.XK.prototype.Uu=function(b){if(D.oA.uu(this)){b=window.Math.max(window.Math.min(b,this.Ja.x+this.Ja.g),this.Ja.x);var c=0,c=(0,D.ya)(this.e)?window.Math.max((this.Ja.x+this.Ja.g-b)/this.Rj,this.Q.min):window.Math.max((b-this.Ja.x)/this.Rj,this.Q.min);return D.nA.rU(this.Q,c)}return D.q};
D.CA=function(b){(0,D.zA)(b,b.Q.value,"render")};D.XK.prototype.NP=function(b,c){(0,D.zA)(this,this.Uu(b,c),"hover")};D.XK.prototype.MP=function(b,c){var d=this.Uu(b,c);(0,D.zA)(this,d,"hover");this.Ya(new D.LA(this.Q.value,d,D.t))};D.XK.prototype.LP=function(b,c){var d=this.Q.value;this.Q.value=this.Uu(b,c);this.Q.changed=D.n;this.M();this.Ya(new D.LA(d,this.Q.value,D.t));this.Ya(new D.LA(d,this.Q.value,D.n))};
D.zA=function(b,c,d,e){if(D.oA.uu(b)){e||(e=b.ha);var f=(0,D.ya)(b.e);c=window.Math.max(window.Math.min(c,b.Q.max),0);var g=0,h=c*b.Rj,j=c*b.Rj;"render"==d&&(g=c*b.Rj,h=0);f?(c=e.da(0),d=new D.td("unsel"+b.getId()),(0,D.ud)(d,b.Ja.x,b.Ja.y,b.Ja.g-j,b.Ja.j),(0,D.vd)(c,d),c=e.da(1),d=new D.td("sel"+b.getId()),(0,D.ud)(d,b.Ja.x+b.Ja.g-j,b.Ja.y,g,b.Ja.j),(0,D.vd)(c,d),e=e.da(2),g=new D.td("hover"+b.getId()),(0,D.ud)(g,b.Ja.x+b.Ja.g-j,b.Ja.y,h,b.Ja.j)):(c=e.da(0),d=new D.td("unsel"+b.getId()),(0,D.ud)(d,
b.Ja.x+j,b.Ja.y,b.Ja.g-j,b.Ja.j),(0,D.vd)(c,d),c=e.da(1),d=new D.td("sel"+b.getId()),(0,D.ud)(d,b.Ja.x,b.Ja.y,g,b.Ja.j),(0,D.vd)(c,d),e=e.da(2),g=new D.td("hover"+b.getId()),(0,D.ud)(g,b.Ja.x,b.Ja.y,h,b.Ja.j));(0,D.vd)(e,g)}};D.XK.prototype.WD=function(){return new D.BA(this)};
D.RA=function(){this.Init({skyros:D.PA,alta:D.QA})};D.F.o(D.RA,D.kA,"DvtRatingGaugeDefaults");D.QA={unselectedState:{shape:"star",color:"#C4CED7",borderColor:D.q},selectedState:{shape:"star",color:"#F8C15A",borderColor:D.q},hoverState:{shape:"star",color:"#007CC8",borderColor:D.q},changedState:{shape:"star",color:"#ED2C02",borderColor:D.q}};
D.PA={min:0,max:5,unselectedState:{shape:"star",color:"#F2F2F2",borderColor:"#B6B6B6"},selectedState:{shape:"star",color:"#F8C15A",borderColor:"#F5A700"},hoverState:{shape:"star",color:"#66A7DA",borderColor:"#4A86C5"},changedState:{shape:"star",color:"#F8C15A",borderColor:"#959595"},step:1};
D.AA=function(b){this.Init();this.ee=b};D.F.o(D.AA,D.Xq,"DvtRatingGaugePeer");D.AA.prototype.Bf=function(b,c,d){b=this.ee.xa();c=this.ee.Va().isEditing?D.oA.VC(this.ee,this.ee.Uu(c,d)):D.oA.VC(this.ee);return(c=D.oA.GH(this.ee,c))&&c.shortDesc?c.shortDesc:b.shortDesc};
D.yA={};D.F.o(D.yA,D.F,"DvtRatingGaugeRenderer");D.yA.HP=["circle","diamond","rectangle","star","triangle"];
D.yA.M=function(b,c,d,e){if(D.oA.uu(b)){var f=b.xa(),g=f.__layout.outerGap,h=f.max,j=window.Math.min(e-2*g,(d-2*g)/h);e=new D.M((d-j*h)/2,g,j*h,e-2*g);d=D.oA.GH(b,D.oA.VC(b));var m=f.selectedState.color,o=f.changedState.color,p=f.selectedState.borderColor,r=f.changedState.borderColor;d&&d.color&&(o=m=d.color);d&&d.borderColor&&(r=p=d.borderColor);g={value:0,type:f.unselectedState.shape,color:f.unselectedState.color,borderColor:f.unselectedState.borderColor,visualEffects:f.visualEffects};m={value:0,
type:f.selectedState.shape,color:m,borderColor:p,visualEffects:f.visualEffects};o={value:0,type:f.changedState.shape,color:o,borderColor:r,visualEffects:f.visualEffects};r={value:0,type:f.hoverState.shape,color:f.hoverState.color,borderColor:f.hoverState.borderColor,visualEffects:f.visualEffects};"dot"==f.unselectedState.shape&&(g.type="circle",g.visualEffects="none",g.size=0.05);p=new D.G(b.e);c.k(p);var u=new D.G(b.e);c.k(u);var w=new D.G(b.e);c.k(w);(0,D.zA)(b,f.value,"render",c);for(var z=0;z<
h;z++){if("none"!=f.unselectedState.shape){var B=(0,D.dv)(b.e,D.q,D.q,D.n);p.k(B);(0,D.wa)(B,e.x+z*j,e.y+e.j/2-j/2);-1==D.$c.Ha(D.yA.HP,g.type)&&(g.type="star");B.M(g,j,j)}f.changed?(B=(0,D.dv)(b.e,D.q,D.q,D.n),u.k(B),(0,D.wa)(B,e.x+z*j,e.y+e.j/2-j/2),-1==D.$c.Ha(D.yA.HP,o.type)&&(o.type="star"),B.M(o,j,j)):(B=(0,D.dv)(b.e,D.q,D.q,D.n),u.k(B),(0,D.wa)(B,e.x+z*j,e.y+e.j/2-j/2),-1==D.$c.Ha(D.yA.HP,m.type)&&(m.type="star"),B.M(m,j,j));B=(0,D.dv)(b.e,D.q,D.q,D.n);w.k(B);(0,D.wa)(B,e.x+z*j,e.y+e.j/2-j/
2);-1==D.$c.Ha(D.yA.HP,r.type)&&(r.type="star");B.M(r,j,j)}h=new D.H(b.e,e.x,e.y,e.g,e.j);(0,D.Xb)(h);c.k(h);(d&&d.shortDesc?d.shortDesc:f.shortDesc)&&b.Va().la(h,new D.AA(b))}else D.nA.Tz(b,c,new D.M(0,0,d,e))};
D.BA=function(b){this.Init(b.e,b.Ya,b);this.ee=b;this.cK=this.Tk=D.t;this.Bfa=(0,D.$d)();this.v4=D.t};D.F.o(D.BA,D.wA,"DvtRatingGaugeEventManager");D.D=D.BA.prototype;D.D.ro=function(b){if(this.ee.xa().readOnly===D.t&&!this.cK){var c=(0,D.xA)(this,b.pageX,b.pageY),d=this.ee;(0,D.zA)(d,d.Uu(c.x,c.y),"hover");this.Tk=D.n}D.wA.u.ro.call(this,b)};
D.D.ik=function(b){if(this.ee.xa().readOnly===D.t){if(this.Bfa&&this.cK&&this.v4){this.v4=D.t;return}(0,D.xA)(this,b.pageX,b.pageY);(0,D.CA)(this.ee);this.cK=D.t}D.wA.u.ik.call(this,b)};D.D.il=function(b){this.cK||(this.ee.xa().readOnly===D.t?(this.Tk=D.n,this.sc(),b=(0,D.xA)(this,b.pageX,b.pageY),this.ee.NP(b.x,b.y)):D.wA.u.il.call(this,b))};
D.D.Zm=function(b){this.Tk&&(this.ee.xa().readOnly===D.t?(this.Tk=D.t,b=(0,D.xA)(this,b.pageX,b.pageY),this.ee.LP(b.x,b.y),(0,D.CA)(this.ee),this.cK=D.n,this.Bfa&&(this.v4=D.n)):D.wA.u.Zm.call(this,b))};D.D.eaa=(0,D.ba)(D.n);
});