define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.LE=(0,D.v)();(0,D.ta)("DvtLegend",D.LE);D.F.o(D.LE,D.Zd,"DvtLegend");D.yd=function(b,c,d){var e=new D.LE;e.Init(b,c,d);return e};D.LE.newInstance=D.yd;D.LE.getDefaults=function(b){return(0,D.aB)(new D.qu,b)};D.D=D.LE.prototype;
D.D.Init=function(b,c,d){D.LE.u.Init.call(this,b,c,d);this.setId("legend1000"+window.Math.floor(1E9*window.Math.random()));this.ff=new D.qu;this.va=new D.Bu(this);this.va.nf(this);(0,D.Vb)()||(0,D.Ch)(this.va,new D.su(this.va,this));this.xf=[];this.IT=[];this.Ja=D.q;this.Eg=new D.wc};D.D.AJ=(0,D.C)("Eg");D.D.Wd=function(b){b?this.Q=this.ff.Pg(b):this.Q||(this.Q=(0,D.gd)(this))};D.D.Bz=function(b,c,d){this.Wd(b);this.xa().isLayout=D.n;b=D.yu.M(this,new D.M(0,0,c,d));this.xa().isLayout=D.t;return b};
D.D.M=function(b,c,d){this.Wd(b);this.xa().isLayout=D.t;this.qi();D.yu.M(this,new D.M(0,0,c,d))};D.LE.prototype.render=D.LE.prototype.M;D.LE.prototype.Km=function(b){(0,D.cr)(b,this.xf)};D.LE.prototype.highlight=D.LE.prototype.Km;D.D=D.LE.prototype;
D.D.Vf=function(b,c){var d=b.Da();if("categoryRollOver"==d||"categoryRollOut"==d){"dim"==this.xa().hoverBehavior&&(0,D.Ih)(b,this.xf);for(var e=0;e<this.IT.length;e++)for(var f=this.IT[e],g=b.im,g=g[0]?g[0]:g,h=0;h<f.xf.length;h++){var j=f.xf[h];if(j&&j.Sg&&-1<D.$c.Ha(j.Sg(),g)){f.scrollIntoView(h);break}}}(this==c||"showPopup"==d||"hidePopup"==d)&&this.Ya(b)};D.D.xa=(0,D.C)("Q");D.D.Va=(0,D.C)("va");D.D.GZ=function(b){this.xf.push(b)};
D.D.W=function(){this.va&&(this.va.Fs(this),this.va.W(),this.va=D.q);D.LE.u.W.call(this)};D.LE.prototype.destroy=D.LE.prototype.W;D.LE.prototype.HZ=(0,D.A)("Ja");D.LE.prototype.Ji=function(){return new D.Eu(this)};D.LE.prototype.getAutomation=D.LE.prototype.Ji;
D.mr={};(0,D.ta)("DvtLegendConstants",D.mr);D.F.o(D.mr,D.F,"DvtLegendConstants");D.mr.SD="background";D.mr.BACKGROUND=D.mr.SD;D.mr.dE="legendItem";D.mr.LEGEND_ITEM=D.mr.dE;D.mr.Gp="title";D.mr.TITLE=D.mr.Gp;
D.Eu=function(b){this.ya=b;this.Ec=this.ya.xa()};(0,D.ta)("DvtLegendAutomation",D.Eu);D.F.o(D.Eu,D.fb,"DvtLegendAutomation");D.Eu.prototype.er=function(b){if((b=(0,D.gb)(this.ya.Va(),b))&&b instanceof D.uu)if(b=b.getData(),b=(0,D.Fu)(this,b,this.Ec))return"section"+b;return D.q};
D.Fu=function(b,c,d){if(d.sections&&0<d.sections.length){for(var e=0;e<d.sections.length;e++){if(d.sections[e]==c)return"["+e+"]";var f=(0,D.Fu)(b,c,d.sections[e]);if(f)return"["+e+"]"+f}return D.q}if(d.items&&0<d.items.length){for(b=0;b<d.items.length;b++)if(d.items[b]==c)return":item["+b+"]";return D.q}};
D.Os=function(b,c,d){if(d.sections&&0<d.sections.length){for(var e=0;e<d.sections.length;e++){var f=(0,D.Os)(b,c,d.sections[e]);if(f)return"["+e+"]"+f}return D.q}if(d.items&&0<d.items.length){for(b=0;b<d.items.length;b++)if(d.items[b].text==c.name)return":item["+b+"]";return D.q}};
D.Ns=function(b,c,d){var e=d.indexOf("["),f=d.indexOf("]");if(0<=e&&0<=f){var e=d.substring(e+1,f),g=d.indexOf(":");d=d.substring(f+1);f=d.indexOf("]");return 0<=d.indexOf("[")&&0<=f?(0,D.Ns)(b,c.sections[e],d):0==g?c.items[e]:c.sections[e]}};D.Eu.prototype.Qk=function(b){b=(0,D.Ns)(this,this.Ec,b);for(var c=this.ya.xf,d=0;d<c.length;d++){var e=c[d].getData();if(b==e)return c[d].we()[0].oa()}return D.q};D.Eu.prototype.getDomElementForSubId=D.Eu.prototype.Qk;D.Eu.prototype.HH=function(){return this.Ec.title};
D.Eu.prototype.getTitle=D.Eu.prototype.HH;D.Eu.prototype.getItem=function(b){for(var c,d=b.shift(),e=this.Ec;d!=D.k;)0<b.length?e=e.sections[d]:c=e.items[d],d=b.shift();return{text:c.text?c.text:D.q}};D.Eu.prototype.getItem=D.Eu.prototype.getItem;D.Eu.prototype.yDa=function(b){for(var c,d=b.shift(),e=this.Ec;d!=D.k;)0<b.length?e=e.sections[d]:c=e.sections[d],d=b.shift();return{title:c.title?c.title:D.q,items:c.items?(0,D.Gu)(c.items):D.q,sections:c.sections?(0,D.Hu)(this,c.sections):D.q}};
D.Eu.prototype.getSection=D.Eu.prototype.yDa;D.Gu=function(b){for(var c=[],d=0;d<b.length;d++)c.push({text:b[d].text});return c};D.Hu=function(b,c){for(var d=[],e=0;e<c.length;e++)d.push({title:c[e].title?c[e].title:D.q,items:c[e].items?(0,D.Gu)(c[e].items):D.q,sections:c[e].sections?(0,D.Hu)(b,c[e].sections):D.q});return d};
D.qu=function(){this.Init({skyros:D.ou,alta:D.pu})};D.F.o(D.qu,D.db,"DvtLegendDefaults");D.pu={skin:"alta",textStyle:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"),titleStyle:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333;"),colors:D.Ks};
D.ou={skin:"skyros",orientation:"vertical",position:D.q,backgroundColor:D.q,borderColor:D.q,textStyle:new D.O("font-size: 11px; color: #333333;"),titleStyle:new D.O("font-size: 12px; color: #003d5b;"),titleHalign:"start",hideAndShowBehavior:"none",hoverBehavior:"none",scrolling:"asNeeded",colors:D.Ls,markerShape:"square",lineWidth:3,layout:{gapRatio:1,outerGapWidth:3,outerGapHeight:3,titleGap:3,markerSize:10,markerGap:5,rowGap:0,columnGap:8,sectionGap:6},isLayout:D.t};
D.ru=function(b,c){return window.Math.ceil(c*b.layout.gapRatio)};
D.Bu=function(b){this.Init(b.e,b.Vf,b);this.ya=b};D.F.o(D.Bu,D.Uc,"DvtLegendEventManager");D.D=D.Bu.prototype;D.D.Ts=function(b,c){var d=D.q;c instanceof D.Xq&&c.Ml()!=D.q?d=c.Ml():c instanceof D.uu&&(d=c.getId(),d={type:D.mr.dE,id:d});this.ah(new D.ir(b,d),this.ya)};D.D.bh=function(b){D.Bu.u.bh.call(this,b);var c=(0,D.gb)(this,b.target);if(c){var d=(0,D.tu)(this,c),c=(0,D.Cu)(this,c);(d||c)&&b.stopPropagation()}};
D.D.ro=function(b){D.Bu.u.ro.call(this,b);var c=(0,D.gb)(this,b.target);c&&(this.az(c,D.n)&&b.stopPropagation(),(0,D.Du)(this,c))};D.D.ik=function(b){D.Bu.u.ik.call(this,b);var c=(0,D.gb)(this,b.target);c&&this.az(c,D.t)&&b.stopPropagation()};D.D.Vu=function(b){var c=(0,D.gb)(this,b.target);if(c){b=b.Vna;var d=(0,D.tu)(this,c),c=(0,D.Cu)(this,c);(d||c)&&b&&b.preventDefault()}};D.D.ZX=function(b){var c=(0,D.gb)(this,b.target);this.az(c,D.n)&&b.stopPropagation()};
D.D.XX=function(b){var c=(0,D.gb)(this,b.target);this.az(c,D.t)&&b.stopPropagation()};D.D.dP=function(b){var c=(0,D.gb)(this,b.target);this.az(c,D.n)&&b.stopPropagation()};D.D.YX=function(b){var c=(0,D.gb)(this,b.target);this.az(c,D.t)&&b.stopPropagation()};
D.tu=function(b,c){if("none"==b.ya.xa().hideAndShowBehavior)return D.t;var d=c.Sg?c.Sg():D.q;if(!d||0>=d.length)return D.t;for(var e=c.getData(),f=e.categoryVisibility,g=c.we(),h=0;h<g.length;h++){var j=g[h];j instanceof D.va?j.CD(c.Fb()):j instanceof D.H&&c.Wi(j)}d=d[0];"hidden"==f?(e.categoryVisibility="visible",b.ah(new D.ed(D.ed.qE,d),b.ya)):(e.categoryVisibility="hidden",b.ah(new D.ed(D.ed.Bx,d),b.ya));return D.n};
D.Cu=function(b,c){return c&&c.zw&&c.hg?(b.ah(new D.Sh("action",c.hg,c.getId()),b.ya),D.n):D.t};D.Bu.prototype.az=function(b,c){if("none"==this.ya.xa().hoverBehavior)return D.t;var d=b&&b.Sg?b.Sg():D.q;if(!d||0>=d.length)return D.t;this.ah(new D.Gh(c?"categoryRollOver":"categoryRollOut",d[0]),this.ya);return D.n};
D.su=function(b,c){this.Init(b,c)};D.F.o(D.su,D.Ec,"DvtLegendKeyboardHandler");D.su.prototype.Init=function(b,c){D.su.u.Init.call(this,b);this.ya=c};D.su.prototype.Vn=function(b){var c=b.keyCode,d=this.va.Re();if(9==c){if(d)return b.preventDefault(),d;c=this.ya.xf;if(0<c.length)return b.preventDefault(),this.sH(c)}else if(13==c)d&&(0,D.tu)(this.ya.Va(),d);else return D.su.u.Vn.call(this,b)};
D.uu=function(b,c,d,e){this.Init(b,c,d,e)};D.F.o(D.uu,D.F,"DvtLegendObjPeer");D.uu.prototype.Init=function(b,c,d,e){this.ya=b;this.De=c;this.Hfa=d;this.Oa=d.id?d.id:d.text;this.hg=d.action;this.Xza=d._spb;this.af=e;this.We=D.t;if(this.hg)for(b=0;b<this.De.length;b++)this.De[b].setCursor("pointer")};D.vu=function(b,c,d,e){if(!b||!d)return D.q;d=new D.uu(c,b,d,e);c.GZ(d);for(e=0;e<b.length;e++)c.Va().la(b[e],d);return d};D.D=D.uu.prototype;D.D.getData=(0,D.C)("Hfa");D.D.Fb=function(){return this.Hfa.color};
D.D.getId=(0,D.C)("Oa");D.D.we=(0,D.C)("De");D.D.Sg=function(){return[this.Oa]};D.D.he=(0,D.C)("af");D.D.zw=(0,D.C)("hg");D.D.Cd=(0,D.C)("Xza");D.D.Qf=function(){if("none"!=this.ya.xa().hideAndShowBehavior){var b=this.ya.AJ(),c=[(0,D.ec)(b,"hidden"==this.getData().categoryVisibility?"STATE_HIDDEN":"STATE_VISIBLE")];return(0,D.gc)(this.getData().text,c,b)}return D.q};D.D.Wi=function(b){(0,D.hc)()||(0,D.ic)(b,"label",this.Qf())};D.D.wg=function(b){return b.type==D.Ib?this:(0,D.Ob)(this,b,this.ya.xf)};
D.D.xe=function(b){return this.De[0]?this.De[0].D(b):new D.M(0,0,0,0)};D.D.Mn=function(){return this.De[0]?this.De[0].oa():D.q};D.D.yh=function(){this.We=D.n;this.De[0]&&this.De[0].La((0,D.wu)())};D.D.ne=function(){this.We=D.t;this.De[0]&&this.De[0].Z(D.q)};D.D.wh=(0,D.C)("We");
D.yu={};D.F.o(D.yu,D.F,"DvtLegendRenderer");D.yu.Eba=10;D.yu.dsa=5;D.yu.esa=2;D.yu.bsa=6;
D.yu.M=function(b,c){var d=b.xa(),e=(0,D.ru)(d,d.layout.outerGapWidth),f=(0,D.ru)(d,d.layout.outerGapHeight),g=new D.M(c.x+e,c.y+f,c.g-2*e,c.j-2*f);b.HZ(g.clone());if(0>=g.g)return new D.se(0,0);var h;d.isLayout||(h=D.yu.b0(b,c));var j="vertical"==d.orientation?D.t:D.n,m=D.yu.xT(b,d.title,g,D.q);g.y+=m.j;g.j-=window.Math.floor(m.j);var o=D.yu.xwa(b),p="off"!==d.scrolling,g=j?D.yu.gza(b,g,o):D.yu.yza(b,g,o,p),j=(0,D.Xa)(m,g);if(0>=b.IT.length){for(o=new D.G(b.e);0<b.za();)o.k(b.da(0));b.k(o);o.G((c.g-
j.g)/2-j.x)}h&&b.Fa(h,0);return d.isLayout?new D.se(window.Math.max(m.g,g.g)+2*e,j.j+2*f):new D.se(j.g+2*e,j.j+2*f)};D.yu.b0=function(b,c){var d=b.xa(),e=d.backgroundColor,d=d.borderColor;if(e||d){var f=new D.H(b.e,c.x,c.y,c.g,c.j);e?f.na(e):(0,D.Xb)(f);d&&(f.La(d),(0,D.wb)(f));b.Va().la(f,new D.Xq(D.q,D.q,D.q,{type:D.mr.SD,id:D.k}));return f}return D.q};
D.yu.xT=function(b,c,d,e){var f=b.xa();if(!c)return new D.M(d.x,d.y,0,0);c=new D.Ya(b.e,c,d.x,d.y);var g=e&&e.titleStyle?new D.O(e.titleStyle):f.titleStyle;c.Ga(g);if(D.Pb.Tb(c,d.g,d.j,b)){b.Va().la(c,new D.Xq(c.dp,D.q,D.q,{type:D.mr.Gp,id:D.k}));var g=c.Vb(),h=(0,D.ru)(f,f.layout.titleGap);f.isLayout?b.removeChild(c):(0,D.Pr)(d,e&&e.titleHalign?e.titleHalign:f.titleHalign,c,g.g);g.j+=h;return g}return new D.M(d.x,d.y,0,0)};
D.yu.HR=function(b,c){var d=b.sections;c.push(b);if(d)for(var e=0;e<d.length;e++)D.yu.HR(d[e],c)};D.yu.yza=function(b,c,d,e){for(var f=b.xa(),g=D.yu.Cua(b,c,d,e),h=[],j=0;j<f.sections.length;j++)D.yu.HR(f.sections[j],h);var m=h.length,f=(0,D.ru)(f,f.layout.sectionGap);c=c.clone();for(var o=D.q,p,j=0;j<h.length;j++)c.j=g[j],p=D.yu.$L(b,h[j],j,c,d,e),j!=m-1&&h[j].items&&(c.y+=p.j+f),o=o?(0,D.Xa)(o,p):p;return o};
D.yu.gza=function(b,c,d){for(var e=b.xa(),f=(0,D.ya)(b.e),g=0,h=[],j=0;j<e.sections.length;j++)D.yu.HR(e.sections[j],h);for(var m=h.length,o=0,j=0;j<h.length;j++)h[j].items&&(o+=h[j].items.length);var p=(0,D.ru)(e,e.layout.sectionGap),r=c.g-p*(m-1),u,w;if(e.sections)for(var z=0,B=0,j=0;j<m;j++)e=c.clone(),(u=h[j].items)?(u=window.Math.round(u.length/o*r),e.g=u,e.x=f?c.x+c.g-g-e.g:c.x+g,0<z&&(e.y+=B,e.j-=B),u=D.yu.$L(b,h[j],j,e,d,D.t),0<z&&(e.j+=B,z--),g+=u.g,j!=m-1&&(g+=p)):(e.g=c.g-g,e.x=f?c.x:c.x+
g,u=D.yu.$L(b,h[j],j,e,d,D.t),B=u.j,z=h[j].sections.length),w=w?(0,D.Xa)(w,u):u;return w};
D.yu.$L=function(b,c,d,e,f,g){if(c){var h=e.clone(),j=b.xa(),m=b.e,o=h.y,p=j.layout.markerSize,r=(0,D.ru)(j,j.layout.markerGap),u=(0,D.ru)(j,j.layout.rowGap),w=(0,D.ru)(j,j.layout.columnGap),z=D.yu.xT(b,c.title,h,c);h.y+=z.j;if(c.items){h.j-=z.j;var o=o+z.j,B=D.yu.Dua(b,h,f,c.items,g),I=B.numCols,E=B.numRows,J=B.width;h.j=window.Math.ceil(window.Math.min(h.j,E*(f+u)-u)+z.j);h.g=J*I+w*(I-1);if(j.isLayout){if(1==E){for(d=e=0;d<c.items.length;d++)g=c.items[d],J=window.Math.ceil(D.yu.vF(b,g.text)),e+=
J+p+r+w;h.g=window.Math.min(h.g,e-w)}return h}if(0==E||0==I)return h;var L=D.q,N=b,R=E*(f+u)-u+z.j,B=c.items.length;"vertical"===j.orientation&&(g&&R>h.j)&&(N=D.yu.ava(b,m,h,d),L=D.yu.gva(b,m,h,N,R,B),b.IT.push(L));var R=J-p-r,S=(0,D.ya)(b.e),ea=0,oa=1;if(1==E){for(d=L=0;d<B;d++)g=c.items[d],J=window.Math.ceil(D.yu.vF(b,g.text)),J<R&&(L+=R-J);for(d=0;d<B;d++){g=c.items[d];var qa=S?h.x+h.g-p:h.x,ra=S?h.x+h.g-p-r:h.x+p+r,Wa=D.yu.yda(b,qa,h.y,f,p,g,d),La=g.text,J=window.Math.ceil(D.yu.vF(b,g.text)),
xa=D.q;La&&(J<R?xa=D.yu.e0(b,m,h,R,La,j.textStyle):(xa=D.yu.e0(b,m,h,R+L,La,j.textStyle),xa!=D.q&&(J=window.Math.ceil(D.yu.vF(b,xa.Ae())),L-=R-J)),J=xa!=D.q?window.Math.ceil(D.yu.vF(b,xa.Ae())):0,xa&&(xa.fa(ra),xa.ra(h.y+f/2),S&&xa.Gi()));b.k(Wa);J=J+p+r;qa=window.Math.min(qa,ra);ra=oa==I?J:J+w;qa=new D.H(m,qa,h.y,ra,f);(0,D.Xb)(qa);N.k(qa);ra=xa!=D.q?xa.dp:D.q;xa=(0,D.vu)([qa,Wa,xa],b,g,ra);"hidden"==g.categoryVisibility&&xa&&Wa.CD(xa.Fb());"none"!=b.xa().hideAndShowBehavior&&((0,D.tb)(qa,"img"),
xa.Wi(qa));h.y+=f+u;ea++;ea===E&&oa!==I&&(h.y=o,S?h.g-=J+w:h.x+=J+w,ea=0,oa++)}}else for(d=0;d<B;d++){g=c.items[d];qa=S?h.x+h.g-p:h.x;ra=S?h.x+h.g-p-r:h.x+p+r;Wa=D.yu.yda(b,qa,h.y,f,p,g,d);La=g.text;xa=D.q;if(La&&(xa=D.yu.e0(N,m,h,R,La,j.textStyle)))xa.fa(ra),xa.ra(h.y+f/2),S&&xa.Gi();N.k(Wa);qa=window.Math.min(qa,ra);ra=oa==I?J:J+w;qa=new D.H(m,qa,h.y,ra,f);(0,D.Xb)(qa);N.k(qa);ra=xa!=D.q?xa.dp:D.q;xa=(0,D.vu)([qa,Wa,xa],b,g,ra);L&&xa instanceof D.uu&&L.GZ(xa);"hidden"==g.categoryVisibility&&xa&&
Wa.CD(xa.Fb());"none"!=b.xa().hideAndShowBehavior&&((0,D.tb)(qa,"img"),xa.Wi(qa));h.y+=f+u;ea++;ea===E&&oa!==I&&(h.y=o,S?h.g-=J+w:h.x+=J+w,ea=0,oa++)}h.y=o+h.j-z.height;return new D.M(e.x,o-z.height,e.g,h.j)}h.j=z.j}};
D.yu.Cua=function(b,c,d,e){var f=b.xa(),g=f.isLayout;f.isLayout=D.n;for(var h=0,j=0,m=c.x,o=c.y,p=[],r=0;r<f.sections.length;r++)D.yu.HR(f.sections[r],p);for(var u=p.length,w=(0,D.ru)(f,f.layout.sectionGap),z=c.j-w*(u-1),B=c.g,I=[],E,r=0;r<u;r++)c.j=z,c.g=B,E=D.yu.$L(b,p[r],r,c,d,e),I[r]=E.j;window.arSectionSpaceNeeded=[];window.extraSpace=window.numShortSections=0;E=z/u;for(r=0;r<u;r++)z=I[r]-E,0>=z?(window.arSectionSpaceNeeded[r]=0,window.extraSpace-=z):(I[r]=E,window.arSectionSpaceNeeded[r]=z,
window.numShortSections++);for(;0<window.extraSpace&&0<window.numShortSections;){E=window.extraSpace/window.numShortSections;for(r=0;r<u;r++)0<window.arSectionSpaceNeeded[r]&&(z=window.arSectionSpaceNeeded[r]-E,0>=z?(I[r]+=window.arSectionSpaceNeeded[r],window.arSectionSpaceNeeded[r]=0,window.extraSpace-=E+z,window.numShortSections--):(I[r]+=E,window.extraSpace-=E,window.arSectionSpaceNeeded[r]=z))}c.x=m;c.y=o;c.g=B;for(r=0;r<u;r++)c.j=I[r],D.yu.$L(b,p[r],r,c,d,e),c.x=m,j=window.Math.max(c.g,j),h+=
c.j,r!=u-1&&(c.y=c.j+o+w,h+=w);c.g=j;c.j=h;c.x=m;c.y=o;f.isLayout=g;return I};
D.yu.Dua=function(b,c,d,e,f){for(var g=b.xa(),h=0,j=0;j<e.length;j++){var m=D.yu.vF(b,e[j].text);m>h&&(h=m)}b=g.layout.markerSize;var o=(0,D.ru)(g,g.layout.markerGap),j=(0,D.ru)(g,g.layout.rowGap),m=(0,D.ru)(g,g.layout.columnGap),h=g.isLayout?window.Math.ceil(b+o+h):c.g;"vertical"==g.orientation?f?(g=1,f=e.length):(f=window.Math.min(window.Math.floor((c.j+j)/(d+j)),e.length),g=window.Math.ceil(e.length/f)):(g=window.Math.min(window.Math.floor(c.g/h),e.length),f=window.Math.ceil(((h+m)*e.length-m)/
c.g),f*(d+j)-j>c.j&&(f=window.Math.floor(window.Math.ceil(c.j+j)/(d+j)),g=window.Math.ceil(e.length/f)));c=window.Math.min(h,(c.g-m*(g-1))/g);return c<b?{width:0,height:0,numCols:0,numRows:0}:{width:c,numCols:g,numRows:f}};D.yu.xwa=function(b){var c=b.xa();b=new D.Ya(b.e,"Test");b.Ga(c.textStyle);b.Pe();b=D.Pb.Ni(b);return window.Math.ceil(window.Math.max(b.j,c.layout.markerSize))};D.yu.vF=function(b,c){var d=b.xa(),e=new D.Ya(b.e,c);e.Ga(d.textStyle);return e.Vb().g};
D.yu.e0=function(b,c,d,e,f,g){c=new D.Ya(c,f);c.Pe();c.Ga(g);return c=D.Pb.Tb(c,e,d.j,b)?c:D.q};
D.yu.yda=function(b,c,d,e,f,g,h){var j=b.xa();g.markerShape||(g.markerShape=j.markerShape);if(!g.color){var m=j.colors;g.color=m[h%m.length]}g.lineWidth||(g.lineWidth=j.lineWidth);"line"==g.type?(g.lineWidth=window.Math.min(g.lineWidth,D.yu.dsa),f=D.yu.zda(b.e,c,d,e,g)):"lineWithMarker"==g.type?(g.lineWidth=window.Math.min(g.lineWidth,D.yu.esa),f=D.yu.zda(b.e,c,d,e,g),"hidden"!=g.categoryVisibility&&f.k(D.yu.Bda(b,c,d,e,D.yu.bsa,g))):f=D.yu.Bda(b,c,d,e,f,g);return f};
D.yu.Bda=function(b,c,d,e,f,g){var h=b.e,j=b.xa();b=g.markerShape;var m=g.markerColor?g.markerColor:g.color,o=g.pattern;d+=(e-f)/2;c="lineWithMarker"==g.type?c+(D.yu.Eba-f)/2:c;o?(f=new D.va(h,b,j.skin,0,0,f,f),f.H(new D.qd(o,m,"#FFFFFF")),(0,D.wa)(f,c,d)):(f=new D.va(h,b,j.skin,c,d,f,f),f.na(m));g.borderColor&&f.La(g.borderColor,D.q,g._borderWidth?g._borderWidth:1);"square"==b&&(0,D.wb)(f);return f};
D.yu.zda=function(b,c,d,e,f){d+=e/2;b=new D.Lp(b,c,d,c+D.yu.Eba,d);c=new D.Hb(f.color,1,f.lineWidth);f=f.lineStyle;"dashed"==f?c.Ui((0,D.Gr)(f),"4,2,4"):"dotted"==f&&c.Ui((0,D.Gr)(f),"2");b.Z(c);(0,D.wb)(b);return b};D.yu.ava=function(b,c,d,e){var f=[d.x,d.y,d.x+d.g,d.y+d.j];d=d.clone();e=b.getId()+"_"+e;c=new D.zu(c,"legendHandler",f,d,e);b.k(c);return c};D.yu.gva=function(b,c,d,e,f,g){c=new D.Au(c,d.x,d.y,d.g,d.j,f,e,g);c.uI(b.Va().Mq());b.k(c);e.M();return c};
});