define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.sp={Xl:function(){return(0,D.Vb)()}};D.F.o(D.sp,D.F,"DvtTimeUtils");D.sp.pf=function(b,c,d,e){d=(d-b)*e;b=c-b;return 0==d||0==b?0:d/b};D.sp.Se=function(b,c,d,e){c=d*(c-b);return 0==c||0==e?b:c/e+b};
D.Np=function(b,c,d){this.Init(b,c,d)};(0,D.ta)("DvtOverview",D.Np);D.F.o(D.Np,D.G,"DvtOverview");
D.Np.prototype.Init=function(b,c,d){D.Np.u.Init.call(this,b);this.fb=c;this.ka=d;this.qn=this.xu()?7:6;if(this.fb!=D.q||this.ka!=D.q)D.sp.Xl()?(this.U(D.Jt.Xd,this.aY,D.t,this),this.U(D.Jt.Bh,this.$X,D.t,this),this.U(D.Jt.gg,this.WX,D.t,this),this.U(D.Ib,this.WI,D.t,this)):(this.U(D.So,this.TX,D.t,this),this.U(D.To,this.SX,D.t,this),this.U(D.Ib,this.WI,D.t,this),this.U(D.Eh,this.lo,D.t,this),this.U(D.Ph,this.mo,D.t,this),this.U(D.Oh,this.lA,D.t,this),this.U(D.Ef,this.z$,D.t,this),this.U(D.Ff,this.A$,
D.t,this));this.A1=0};D.Np.prototype.aA=function(b,c){var d=this.pf(b),e=this.pf(c);if(!(d<this.cq||e>(0,D.Kt)(this))){var f=window.Math.max(e-d,(0,D.Lt)(this));0<f&&(0<=d&&e<=this.rb)&&(e=this.da(1),this.Pi()?(0,D.Mt)(this,e,this.rb-(d+f)):(0,D.Mt)(this,e,d),(0,D.Nt)(this,e,f),(0,D.Ot)(this))}};D.Pt=function(b){return b.zR==D.q?D.t:-1!=b.zR.indexOf("zoom")};
D.Np.prototype.M=function(b,c,d){if(b==D.q){var e=this.Mg,f=this.Gh,g=this.da(1),h=(0,D.Qt)(this,g);g!=D.q&&0!=h&&(this.uia=D.sp.Se(e,f,h,this.rb));this.qi()}c!=D.q&&d!=D.q&&(this.rb=c,this.Lb=d);b&&(b=this.Zu(b),this.Ao(b));b=this.fb!=D.q||this.ka!=D.q;this.kH(c,d);if(b){f=(e=this.tc())?new D.H(this.e,0,0,c,0,"window"):new D.H(this.e,0,0,0,d,"window");f.na(this.hU,this.tAa);(0,D.wb)(f);if(!(0,D.Pt)(this)){var j=(0,D.Rt)(),m=(0,D.St)();if(e){var o=(c-36)/2,p=window.DvtPathUtils.moveTo(o,0)+window.DvtPathUtils.Zb(o+
3,6,o+8,8)+window.DvtPathUtils.lineTo(o+28,8)+window.DvtPathUtils.Zb(o+33,6,o+36,0);window.DvtPathUtils.closePath();h=window.DvtPathUtils.moveTo(o,0)+window.DvtPathUtils.Zb(o+3,-6,o+8,-8)+window.DvtPathUtils.lineTo(o+28,-8)+window.DvtPathUtils.Zb(o+33,-6,o+36,0);window.DvtPathUtils.closePath();var g=new D.H(this.e,0,0,c,j,"lhb"),j=new D.H(this.e,0,0,c,j,"rhb"),r="row-resize";if(this.j1)var u=(0,D.Tt)(this,c,10),o=(0,D.Tt)(this,c,10);else u=(0,D.Ut)(this,o),o=(0,D.Ut)(this,o)}else o=(d-36)/2,p=window.DvtPathUtils.moveTo(0,
o)+window.DvtPathUtils.Zb(6,o+3,8,o+8)+window.DvtPathUtils.lineTo(8,o+28)+window.DvtPathUtils.Zb(6,o+33,0,o+36),window.DvtPathUtils.closePath(),h=window.DvtPathUtils.moveTo(0,o)+window.DvtPathUtils.Zb(-6,o+3,-8,o+8)+window.DvtPathUtils.lineTo(-8,o+28)+window.DvtPathUtils.Zb(-6,o+33,0,o+36),window.DvtPathUtils.closePath(),g=new D.H(this.e,0-m,0,j,d,"lhb"),j=new D.H(this.e,m,0,j,d,"rhb"),r="col-resize",this.j1?(u=(0,D.Tt)(this,10,d),o=(0,D.Tt)(this,10,d)):(u=(0,D.Ut)(this,o),o=(0,D.Ut)(this,o));g.na(this.hU,
0);j.na(this.hU,0);(0,D.wb)(g);(0,D.wb)(j);p=new D.Ra(this.e,p,"lh");h=new D.Ra(this.e,h,"rh");p.na(this.TK);p.La(this.TK);h.na(this.TK);h.La(this.TK);this.hU==this.TK&&((0,D.wb)(p),(0,D.wb)(h));g.setCursor(r);j.setCursor(r);p.setCursor(r);h.setCursor(r);u.setCursor(r);o.setCursor(r);f.k(g);f.k(p);f.k(u);f.k(j);f.k(h);f.k(o)}f.setCursor("move");this.k(f);f=e?new D.Lp(this.e,c-this.nN(),0,c-this.nN(),d,"tab"):"above"==this.eT?new D.Lp(this.e,0,this.Zj(),c,this.Zj(),"tab"):new D.Lp(this.e,0,d-this.Zj(),
c,d-this.Zj(),"tab");f.La(this.cAa,this.dAa);(0,D.wb)(f);this.k(f);this.Sq()&&(e?(f=new D.H(this.e,0,0,c,0,"lbg"),g=new D.H(this.e,0,0,c,0,"rbg")):(f=new D.H(this.e,0,0,0,d,"lbg"),g=new D.H(this.e,0,0,0,d,"rbg")),f.na(this.fga,this.Exa),this.k(f),g.na(this.Aia,this.Cza),this.k(g),D.sp.Xl()&&m!=D.k&&((0,D.St)(),e?(e=new D.H(this.e,0,0,c,m,"lbgrh"),m=new D.H(this.e,0,0,c,m,"rbgrh")):(e=new D.H(this.e,0,0,m,d,"lbgrh"),m=new D.H(this.e,0,0,m,d,"rbgrh")),e.na(this.fga,0),this.k(e),m.na(this.Aia,0),this.k(m)))}this.Yna(c,
d);if(this.Y0!=D.q)for(m=0;m<this.Y0.length;m++)g=this.Y0[m],e=c,f=d,r=(0,window.parseInt)(g.q("rs"),10),h=(0,window.parseInt)(g.q("re"),10),g=g.q("c"),r!=D.q&&h!=D.q&&(j=(0,D.Vt)(this),r=this.pf(r),h=this.pf(h)-r,this.Pi()&&(r=j-r-h),e=this.tc()?new D.H(this.e,0,r,e-this.nN(),h,"ftr"):new D.H(this.e,r,"above"==this.eT?this.Zj():0,h,f-this.Zj(),"ftr"),g!=D.q&&e.na(g,0.4),e.setCursor("move"),(0,D.wb)(e),this.k(e));this.o0==D.q||(0,window.isNaN)(this.o0)||(m=this.pf(this.o0),this.tc()?m=new D.Lp(this.e,
0,m,c,m,"ocd"):(this.Pi()&&(m=c-m),m=new D.Lp(this.e,m,0,m,d,"ocd")),m.La(this.lva),(0,D.wb)(m),this.k(m));this.ON(c,d);b&&(f=this.da(1),this.tc()?(b=f.ga(),m=f.ga()+f.getHeight()-1,this.xu()||(0,D.ub)()?(e=0,j=c-1):(e=1,j=c),f=new D.Lp(this.e,0,b,c,b,"lh"),g=new D.Lp(this.e,0,m,c,m,"rh"),h=new D.Lp(this.e,e,0,e,b,"ltb"),c=new D.Lp(this.e,e,m,e,d,"rtb"),d=new D.Lp(this.e,j,b,j,m,"bb"),b=new D.Lp(this.e,e,b,e,m,"tb")):(b=1,this.xu()&&(b=0),m=d-1,e=f.ea(),j=f.ea()+f.getWidth()-1,f=new D.Lp(this.e,e,
b,e,m,"lh"),g=new D.Lp(this.e,j,b,j,m,"rh"),h=new D.Lp(this.e,0,window.Math.max(0,b-1),e+1,window.Math.max(0,b-1),"ltb"),c=new D.Lp(this.e,j-1,window.Math.max(0,b-1),c,window.Math.max(0,b-1),"rtb"),d=new D.Lp(this.e,e,m,j,m,"bb"),b=new D.Lp(this.e,e,b,j,b,"tb")),(0,D.wb)(f),(0,D.wb)(g),(0,D.wb)(h),(0,D.wb)(c),(0,D.wb)(d),(0,D.wb)(b),"none"!=this.xAa&&f.La(this.wAa),this.k(f),"none"!=this.zAa&&g.La(this.yAa),this.k(g),"none"!=this.xua&&this.v_&&(h.La(this.v_),c.La(this.v_)),this.k(h),this.k(c),"none"!=
this.vAa&&d.La(this.uAa),this.k(d),"none"!=this.BAa&&b.La(this.AAa),this.k(b),this.xu()&&(c=this.tc()?window.DvtPathUtils.moveTo(6,0)+window.DvtPathUtils.lineTo(0,5)+window.DvtPathUtils.lineTo(5,5)+window.DvtPathUtils.lineTo(5,17)+window.DvtPathUtils.lineTo(0,17)+window.DvtPathUtils.lineTo(6,22)+window.DvtPathUtils.lineTo(12,17)+window.DvtPathUtils.lineTo(7,17)+window.DvtPathUtils.lineTo(7,5)+window.DvtPathUtils.lineTo(12,5)+window.DvtPathUtils.closePath():window.DvtPathUtils.moveTo(5,0)+window.DvtPathUtils.lineTo(0,
6)+window.DvtPathUtils.lineTo(5,12)+window.DvtPathUtils.lineTo(5,7)+window.DvtPathUtils.lineTo(17,7)+window.DvtPathUtils.lineTo(17,12)+window.DvtPathUtils.lineTo(22,6)+window.DvtPathUtils.lineTo(17,0)+window.DvtPathUtils.lineTo(17,4)+window.DvtPathUtils.lineTo(5,4)+window.DvtPathUtils.lineTo(5,0)+window.DvtPathUtils.closePath(),c=new D.Ra(this.e,c,"arr"),c.na("#ffffff"),c.La("#000000"),c.Za(D.t),this.k(c),this.rG=c),b=this.tc(),d=this.da(1),c=(0,D.Vt)(this),m=b?this.Lb:this.rb,f=this.R,g=this.Mg,
h=this.Gh,b=this.uia,e=D.sp.Se(g,h,0,f),f=D.sp.Se(g,h,m,f),e=this.pf(e),m=window.Math.min(m,this.pf(f)),b=this.pf(b),m-=e,this.Pi()?(0,D.Mt)(this,d,c-b-m):(0,D.Mt)(this,d,b),(0,D.Nt)(this,d,m),(0,D.Ot)(this),d=this.R,b=this.Mg,m=this.Gh,e=D.sp.Se(b,m,1,c),c=D.sp.Se(b,m,2,c),e=D.sp.pf(b,m,e,d),this.w1=D.sp.pf(b,m,c,d)-e);this.pfa!=D.q&&(this.A1=window.Math.max(0,D.sp.pf(this.Mg,this.Gh,this.pfa,this.R)));0<this.A1&&(c=this.A1/this.w1,this.Pi()&&(c=0-c),(0,D.Up)(this,c))};D.Np.prototype.render=D.Np.prototype.M;
D.D=D.Np.prototype;D.D.Dla=function(){return new D.Wt(this)};D.D.Zu=function(b){return this.Dla(b).parse(b)};
D.D.Ao=function(b){this.Mg=b.start;this.Gh=b.end;this.R=b.width;this.uia=b.r8;this.o0=b.currentTime;this.pfa=b.GEa;this.Ota=b.OAa;this.cq=window.Math.max(0,b.lFa);this.sG=window.Math.max(0,b.rGa);(0,window.isNaN)(this.cq)&&(this.cq=0);(0,window.isNaN)(this.sG)&&(this.sG=0);this.Ry=b.orientation;this.eT=b.pna;this.Gfa=b.KV;b.vka!=D.q&&(this.zR=b.vka.split(" "));b.P7!=D.q&&0<b.P7&&(this.Lga=b.P7);this.wua=b.XAa;this.xM=b.Tna;b.Tna!=D.q&&(this.wM=this.xM.XGa);this.Y0=b.aCa;this.xua=b.borderTopStyle;
this.v_=b.borderTopColor;this.hU=b.Y8;this.tAa=b.$na;this.BAa=b.g9;this.zAa=b.e9;this.vAa=b.a9;this.xAa=b.c9;this.AAa=b.f9;this.yAa=b.d9;this.uAa=b.Z8;this.wAa=b.b9;this.Swa=b.n7;this.TK=b.j7;this.j1=b.Ula;this.afa=b.ima;this.Yea=b.ema;this.sya=b.U7;this.lva=b.F5;this.eAa=b.S8;this.cAa=b.Rna;this.dAa=b.Sna;this.fga=b.Ima;this.Exa=b.Hma;this.Aia=b.Fna;this.Cza=b.Ena};D.D.pf=function(b){return window.Math.max(0,D.sp.pf(this.Mg,this.Gh,b,(0,D.Vt)(this)))+this.cq};
D.D.Se=function(b){return D.sp.Se(this.Mg,this.Gh,window.Math.max(0,b-this.cq),(0,D.Vt)(this))};D.D.Pi=function(){return!this.tc()&&"true"==this.Gfa};D.D.tc=function(){return"vertical"==this.Ry};D.Vt=function(b){return b.tc()?b.Lb-b.cq-b.sG:b.rb-b.cq-b.sG};D.Kt=function(b){return b.tc()?b.Lb-b.sG:b.rb-b.sG};D.Lt=function(b){return b.v2!=D.q?b.v2:b.Lga!=D.q?(b.v2=D.sp.pf(b.Mg,b.Gh,b.Mg+b.Lga,(0,D.Vt)(b)),b.v2):10};D.St=function(){return D.sp.Xl()?(0,D.Rt)()/2:0};
D.Rt=function(){return D.sp.Xl()?30:10};D.Xt=function(b){var c=b.getId();return"lh"==c||"rh"==c||"lhb"==c||"rhb"==c||"grpy"==c||"lbgrh"==c||"rbgrh"==c||b.getParent()!=D.q&&"grpy"==b.getParent().getId()};D.Np.prototype.nN=function(){if(this.xM==D.q)return 0;if(this.yM==D.q){var b=(0,window.parseInt)(this.xM.width,10);this.yM=!(0,window.isNaN)(b)&&b<this.rb?b:40}return this.yM};
D.Np.prototype.Zj=function(){if(this.xM==D.q)return 0;if(this.oja==D.q){var b=(0,window.parseInt)(this.xM.height,10);this.oja=!(0,window.isNaN)(b)&&b<this.Lb?b:20}return this.oja};D.Yt=function(b){return D.sp.Xl()&&b.targetTouches!=D.q?0<b.targetTouches.length?b.targetTouches[0].pageX:D.q:b.pageX};D.Zt=function(b){return D.sp.Xl()&&b.targetTouches!=D.q?0<b.targetTouches.length?b.targetTouches[0].pageY:D.q:b.pageY};D.Np.prototype.Sq=(0,D.ba)(D.t);D.$t=function(b){return b.Sq()?b.da(3):D.q};
D.au=function(b){return b.Sq()?b.da(4):D.q};D.bu=function(b){return b.Sq()&&!(0,D.Pt)(b)?b.da(6):D.q};D.cu=function(b,c,d,e){b.tc()?(-1!=d&&c.Ej(d),-1!=e&&c.al(e)):(-1!=d&&c.gk(d),-1!=e&&c.ri(e))};D.du=function(b,c){return b.tc()?c.Jm():c.$j()};D.Np.prototype.oF=function(b){b=b.target;if(b!=D.q){var c=b.getId();if(c==D.q)return D.q;if("_border"==c.substr(c.length-7))return this.h6(b);if("tick"!=c.substr(0,4)&&"ltb"!=c&&"rtb"!=c&&"bb"!=c&&"tab"!=c)return b}return D.q};
D.Sp=function(b){return"window"==b.getId()||"ftr"==b.getId()||"sta"==b.getId()||(0,D.Xt)(b)?D.n:D.t};D.Np.prototype.xu=function(){return window&&window.xu};D.Np.prototype.kH=function(b,c){var d=new D.H(this.e,0,0,b,c,"bg");d.na(this.sya);(0,D.wb)(d);this.k(d);return d};D.Tt=function(b,c,d){return new D.Wb(b.e,b.j1,(c-b.afa)/2,(d-b.Yea)/2,b.afa,b.Yea,"grpy")};
D.Ut=function(b,c){var d=new D.G(b.e,"grpy"),e=b.Swa;if(b.tc()){for(var f=8+c,g=3,h=0;9>h;h++){var j=new D.Lp(b.e,f+2*h,g,f+2*h+1,g,"dot1"+h);j.La(e);d.k(j);g+=2;j=new D.Lp(b.e,f+1+2*h,g,f+1+2*h+1,g,"dot2"+h);j.La(e);d.k(j);g+=2;j=new D.Lp(b.e,f+2*h,g,f+2*h+1,g,"dot3"+h);j.La(e);d.k(j);g=3}j=new D.Lp(b.e,f+18,g,f+18+1,g,"dot4");j.La(e);d.k(j);g+=4;j=new D.Lp(b.e,f+18,g,f+18+1,g,"dot5")}else{f=3;g=8+c;for(h=0;9>h;h++)j=new D.Lp(b.e,f,g+2*h,f,g+2*h+1,"dot1"+h),j.La(e),d.k(j),f+=2,j=new D.Lp(b.e,f,g+
1+2*h,f,g+1+2*h+1,"dot2"+h),j.La(e),d.k(j),f+=2,j=new D.Lp(b.e,f,g+2*h,f,g+2*h+1,"dot3"+h),j.La(e),d.k(j),f=3;j=new D.Lp(b.e,f,g+18,f,g+18+1,"dot4");j.La(e);d.k(j);f+=4;j=new D.Lp(b.e,f,g+18,f,g+18+1,"dot5")}j.La(e);d.k(j);(0,D.wb)(d);return d};D.eu=function(b,c){return b.tc()?c.getHeight():c.getWidth()};D.Qt=function(b,c){return b.tc()?c.L():c.N()};
D.Mt=function(b,c,d){d=window.Math.max(0,d);b.tc()?c.P(d):c.G(d);if(b.Sq()){(0,D.$t)(b).ia(d);c=d+(0,D.eu)(b,c);var e=(0,D.au)(b);e.fa(c);e.ia(window.Math.max(0,b.rb-c));D.sp.Xl()&&!(0,D.Pt)(b)&&(e=(0,D.St)(),(b.Sq()&&!(0,D.Pt)(b)?b.da(5):D.q).fa(d-e),(0,D.bu)(b).fa(c))}};
D.Nt=function(b,c,d){d=window.Math.max((0,D.Lt)(b),d);var e=d=window.Math.min(b.tc()?b.Lb:b.rb,d);b.tc()?c.ta(e):c.ia(e);if(b.Sq()){var e=(0,D.Qt)(b,c)+d,f=(0,D.au)(b);f.fa(e);f.ia(window.Math.max(0,b.rb-e));D.sp.Xl()&&!(0,D.Pt)(b)&&(0,D.bu)(b).fa(e)}(0,D.Pt)(b)||(e=c.da(3),f=c.da(4),c=c.da(5),b.tc()?(f.P(d),e.P(d-(0,D.Rt)()),c.P(d-10)):(f.G(d),e.G(d-(0,D.Rt)()),c.G(d-10)))};
D.Np.prototype.Yna=function(b,c){if(this.wM!=D.q){this.tc();for(var d=(0,D.Vt)(this),e=0;e<this.wM.length;e++){var f=this.wM[e],g=(0,window.parseInt)(f.q("time"),10),g=this.pf(g),f=f.q("label"),h=0;e+1<this.wM.length?(h=(0,window.parseInt)(this.wM[e+1].q("time"),10),h=this.pf(h)-g):h=d-g;this.Pi()&&(g=d-g);this.pU(g,b,c,"tick"+e);this.h5(g,f,b,c,h,"label"+e)}}};
D.Np.prototype.pU=function(b,c,d,e){b=this.tc()?new D.Lp(this.e,0,b,c,b,e):new D.Lp(this.e,b,0,b,d,e);c=new D.Hb(this.eAa);c.X(1,3);b.Z(c);(0,D.wb)(b);this.k(b)};D.Np.prototype.h5=function(b,c,d,e,f,g){this.tc()?b=new D.Ya(this.e,c,4,b,g):(d="above"==this.eT?2:e-this.Zj()+2,b=new D.Ya(this.e,c,b+5,d,g));b.Ga(new D.O("font-weight:bold"));D.Pb.Tb(b,f,window.Infinity,this);b.Qya=b.dp};D.Np.prototype.ON=(0,D.v)();
D.Up=function(b,c){var d=b.da(1);d.da(3);d.da(4);d.da(5);if(c!=(0,D.Qt)(b,d)){var e=b.da(b.za()-b.qn),f=b.da(b.za()-(b.qn-1)),g=b.da(b.za()-(b.qn-2)),h=b.da(b.za()-(b.qn-3)),j=b.da(b.za()-(b.qn-4)),m=b.da(b.za()-(b.qn-5));if(b.tc())var o=d.L,p=d.P,r=e.Jm,u=e.Ej,w=e.Nq,z=e.al,B=f.Jm,I=f.Ej,E=f.Nq,J=f.al,L=g.Nq,N=g.al,R=h.Jm,S=h.Ej,ea=j.Jm,oa=j.Ej,qa=j.Nq,ra=j.al,Wa=m.Jm,La=m.Ej,xa=m.Nq,Jb=m.al;else o=d.N,p=d.G,r=e.$j,u=e.gk,w=e.Pn,z=e.ri,B=f.$j,I=f.gk,E=f.Pn,J=f.ri,L=g.Pn,N=g.ri,R=h.$j,S=h.gk,ea=j.$j,
oa=j.gk,qa=j.Pn,ra=j.ri,Wa=m.$j,La=m.gk,xa=m.Pn,Jb=m.ri;var Eb=b.cq,Fd=(0,D.Kt)(b),tc=(0,D.eu)(b,d);c=window.Math.max(Eb,window.Math.min(Fd-tc,c));Eb="off"!==b.Ota?new D.Ge(b.e,0.5,0,D.Ep):D.q;(0,D.fu)(Eb,d,o,p,c);(0,D.fu)(Eb,e,r,u,c);(0,D.fu)(Eb,e,w,z,c);(0,D.fu)(Eb,f,B,I,c+tc);(0,D.fu)(Eb,f,E,J,c+tc);(0,D.fu)(Eb,g,L,N,c+1);(0,D.fu)(Eb,h,R,S,c+tc-1);(0,D.fu)(Eb,j,ea,oa,c);(0,D.fu)(Eb,m,Wa,La,c);(0,D.fu)(Eb,j,qa,ra,c+tc);(0,D.fu)(Eb,m,xa,Jb,c+tc);b.Sq()&&(d=(0,D.$t)(b),(0,D.fu)(Eb,d,d.getWidth,d.ia,
c),tc=c+tc,d=(0,D.au)(b),e=d.getWidth,f=d.ia,g=d.ea,h=d.fa,j=b.tc()?b.Lb:b.rb,(0,D.fu)(Eb,d,e,f,j-tc),(0,D.fu)(Eb,d,g,h,tc),D.sp.Xl()&&!(0,D.Pt)(b)&&(d=(0,D.St)(),e=b.Sq()&&!(0,D.Pt)(b)?b.da(5):D.q,f=e.ea,g=e.fa,h=(0,D.bu)(b),j=h.ea,m=h.fa,(0,D.fu)(Eb,e,f,g,c-d),(0,D.fu)(Eb,h,j,m,tc)));Eb!=D.q&&Eb.play()}};D.fu=function(b,c,d,e,f){b!=D.q?(0,D.P)(b,"typeNumber",c,d,e,f):e.call(c,f)};
D.Np.prototype.TX=function(b){var c=this.oF(b);if(c&&!("bg"==c.getId()||"ocd"==c.getId()))if("label"==c.getId().substr(0,5)&&c instanceof D.Ya)c.bg()&&this.e.Kd().vI(b.pageX,b.pageY,c.Qya,"#000000");else if(this.rG!=D.q&&(0,D.Xt)(c)&&(b=(0,D.Fa)(this.e,b.pageX,b.pageY),b=this.Cb(b),this.tc()?(0,D.wa)(this.rG,b.x+6,b.y-10):(0,D.wa)(this.rG,b.x-6,b.y-20),this.rG.Za(D.n)),"window"==c.getId()||"ftr"==c.getId()||"arr"==c.getId()||(0,D.Xt)(c))this.xu()&&this.setCursor("move");else return c};
D.Np.prototype.SX=function(b){this.tm==D.q&&this.setCursor("default");b=this.oF(b);if(b!=D.q)return(0,D.Xt)(b)&&this.rG!=D.q&&this.rG.Za(D.t),b};
D.Np.prototype.WI=function(b,c,d){b.stopPropagation();var e=this.oF(b);if(e&&!("window"==e.getId()||(0,D.Xt)(e)))if("bg"==e.getId()||"label"==e.getId().substr(0,5)||"ocd"==e.getId()||"lbg"==e.getId()||"rbg"==e.getId()){c==D.k&&(c=b.pageX);d==D.k&&(d=b.pageY);b=(0,D.Fa)(this.e,c,d);b=this.Cb(b);this.tc()?(d=b.y,e=this.Lb):(d=b.x,e=this.rb);b=this.da(1);c=d-(0,D.eu)(this,b)/2;(0,D.Up)(this,c);this.Pi()&&(d=this.rb-d);var f=this.Se(d);d=new D.aq("scrollTime");d.setTime(f);c=window.Math.max(0,window.Math.min(c,
e-(0,D.eu)(this,b)));this.Pi()?(e=this.Se(this.rb-(c+(0,D.eu)(this,b))),b=this.Se(this.rb-c)):(e=this.Se(c),b=this.Se(c+(0,D.eu)(this,b)));(0,D.gu)(d,e);(0,D.hu)(d,b);this.dispatchEvent(d)}else return e};D.Np.prototype.lo=function(b){(0,D.iu)(this,b)};
D.iu=function(b,c){c.stopPropagation();var d=b.oF(c);if(d!=D.q&&(0,D.Sp)(d)){if("ftr"==d.getId()||"sta"==d.getId())d=b.da(1);b.YR=(0,D.Yt)(c);b.ofa=(0,D.Zt)(c);if((0,D.Xt)(d)){var e=b.da(1);b.Pi()?(b.G2=b.rb-e.ea(),b.P2=b.G2-e.getWidth()):(b.P2=e.ea(),b.G2=b.P2+e.getWidth());"grpy"==d.getParent().getId()&&(d=d.getParent());var f=d.getId();"grpy"==f&&(d=e.SU(d),f=d.getId());if("lh"==f||"rh"==f)d=e.SU(d),f=d.getId();"lbgrh"==f&&(d=e.da(0));"rbgrh"==f&&(d=e.da(e.za()-3));D.sp.Xl()||(b.tc()?(d.ra(-20),
d.ta(2*(d.getHeight()+20))):(d.fa(-20),d.ia(2*(d.getWidth()+20))));e=d.getCursor();f=b.da(1);f!=D.q&&f.setCursor(e);if(b.Sq()){var f=(0,D.$t)(b),g=(0,D.au)(b);f!=D.q&&g!=D.q&&(f.setCursor(e),g.setCursor(e))}}b.tm=d;d=new D.aq("dropCallback");b.dispatchEvent(d)}};D.Np.prototype.mo=function(b){(0,D.ju)(this,b)};
D.ju=function(b,c){c!=D.q&&c.stopPropagation();if(b.tm!=D.q){if("window"==b.tm.getId())b.zka(0,0,0);else if((0,D.Xt)(b.tm)){b.U5();D.sp.Xl()||(b.tc()?(b.tm.ra(0),b.tm.ta((0,D.Rt)())):(b.tm.fa(0),b.tm.ia((0,D.Rt)())));var d=b.da(1);d!=D.q&&d.setCursor("move");if(b.Sq()){var d=(0,D.$t)(b),e=(0,D.au)(b);d!=D.q&&e!=D.q&&(d.setCursor("default"),e.setCursor("default"))}}b.tm=D.q;b.YR=-1}};D.Np.prototype.lA=function(b){(0,D.ku)(this,b)};
D.ku=function(b,c){c.stopPropagation();if(b.tm!=D.q&&-1!=b.YR){var d=(0,D.Yt)(c),e=(0,D.Zt)(c),f=d-b.YR,g=e-b.ofa;b.YR=d;b.ofa=e;"window"==b.tm.getId()?b.jma(0,f,g):"lh"==b.tm.getId()||"lhb"==b.tm.getId()?(0,D.lu)(b,c,f,g,D.n):("rh"==b.tm.getId()||"rhb"==b.tm.getId())&&b.m7(c,f,g)}};D.D=D.Np.prototype;
D.D.aY=function(b){var c=b.targetTouches[0];this.UG=c.pageX;this.vC=c.pageY;2==b.targetTouches.length?(b.preventDefault(),c=b.targetTouches[1],this.VG=c.pageX,this.FM=c.pageY,20>window.Math.abs(this.vC-this.FM)?this.rK=0:this.FM=this.VG=this.vC=this.UG=D.q):(0,D.iu)(this,b)};
D.D.$X=function(b){b.preventDefault();if(this.VG!=D.q&&this.FM!=D.q)if(50>this.rK)this.rK++;else{var c=b.targetTouches[1];this.m7(D.q,c.pageX-this.VG,0);this.VG=c.pageX;this.rK=0}else{c=b.targetTouches[0];if(this.UG!=c.pageX||this.vC!=c.pageY)this.vC=this.UG=D.q;(0,D.ku)(this,b)}};D.D.WX=function(b){this.VG!=D.q&&this.FM!=D.q?this.U5():((0,D.ju)(this,b),this.UG!=D.q&&this.vC!=D.q&&this.WI(b,this.UG,this.vC));this.FM=this.VG=this.vC=this.UG=D.q};
D.D.z$=function(b){var c=b.keyCode;if(37===c||39===c)c=37===c?-1:1,(b.shiftKey?this.m7:this.jma).call(this,b,c,c)};D.D.A$=function(b){var c=b.keyCode;if(37===c||39===c)c=37===c?-1:1,(b.shiftKey?this.U5:this.zka).call(this,b,c,c)};D.D.jma=function(b,c,d){(0,D.mu)(this,"scrollPos",c,d)};D.D.zka=function(b,c,d){(0,D.mu)(this,"scrollEnd",c,d)};
D.mu=function(b,c,d,e){var f=b.da(1),g=(0,D.Qt)(b,f),h=(0,D.eu)(b,f),j=b.cq,m=(0,D.Kt)(b);d=b.tc()?e:d;g+d<=j?((0,D.Mt)(b,f,j),h=b.Pi()?-2:-1):g+h+d>=m?((0,D.Mt)(b,f,m-h),h=b.Pi()?-1:-2):((0,D.Mt)(b,f,g+d),h=b.Pi()?(m-h-g-b.cq)*b.w1:(g-b.cq)*b.w1);(0,D.Ot)(b);c=new D.aq(c);c.Xg(h);b.Pi()?(h=b.Se(b.rb-(g+(0,D.eu)(b,f))),f=b.Se(b.rb-g)):(h=b.Se(g),f=b.Se(g+(0,D.eu)(b,f)));(0,D.gu)(c,h);(0,D.hu)(c,f);b.dispatchEvent(c)};D.Np.prototype.m7=function(b,c,d){(0,D.lu)(this,b,c,d,D.t)};
D.lu=function(b,c,d,e,f){var g=(0,D.Vt)(b);e=b.tc()?e:d;if(0!=e){d=b.da(1);var h=(0,D.Qt)(b,d),j=(0,D.eu)(b,d);if(f){if(j-e<=(0,D.Lt)(b)||h+e<=b.cq)return;c=b.tc()?(0,D.Fa)(b.e,(0,D.Yt)(c),(0,D.Zt)(c)).y:(0,D.Fa)(b.e,(0,D.Yt)(c),(0,D.Zt)(c)).x;c=b.Cb(c);if(0<e&&c<=h||0>e&&c>=h)return;(0,D.Mt)(b,d,h+e);(0,D.Nt)(b,d,j-e)}else{if(j+e<=(0,D.Lt)(b)||h+j+e>=(0,D.Kt)(b))return;c=b.tc()?(0,D.Fa)(b.e,(0,D.Yt)(c),(0,D.Zt)(c)).y:(0,D.Fa)(b.e,(0,D.Yt)(c),(0,D.Zt)(c)).x;c=b.Cb(c);if(0<e&&c<=h+j||0>e&&c>=h+j)return;
(0,D.Nt)(b,d,j+e)}(0,D.Ot)(b);c=b.Se((0,D.eu)(b,d));c=g*(b.Gh-b.Mg)/(c-b.Mg);b.Ama()&&(g=new D.aq("rangeChanging"),(0,D.Pc)(g,"newSize",c),c=b.Pi()?f:!f,(0,D.Pc)(g,"endHandle",c),f?(0,D.Pc)(g,"expand",0>e):(0,D.Pc)(g,"expand",0<e),b.Pi()?(f=b.Se(b.rb-((0,D.Qt)(b,d)+(0,D.eu)(b,d))),d=b.Se(b.rb-(0,D.Qt)(b,d))):(f=b.Se((0,D.Qt)(b,d)),d=b.Se((0,D.Qt)(b,d)+(0,D.eu)(b,d))),(0,D.gu)(g,f),(0,D.hu)(g,d),b.dispatchEvent(g))}};D.Np.prototype.Ama=(0,D.ba)(D.n);
D.Np.prototype.U5=function(){var b=this.Mg,c=this.Gh,d=this.R,e=(0,D.Vt)(this),f=this.da(1),g=this.Se((0,D.eu)(this,f)),b=e*(c-b)/(g-b),c=this.Se(this.P2),e=this.Se(this.G2);this.Pi()?(g=this.Se(this.rb-((0,D.Qt)(this,f)+(0,D.eu)(this,f))),f=this.Se(this.rb-(0,D.Qt)(this,f))):(g=this.Se((0,D.Qt)(this,f)),f=this.Se((0,D.Qt)(this,f)+(0,D.eu)(this,f)));var h=new D.aq("rangeChange");(0,D.Pc)(h,"oldSize",d);(0,D.Pc)(h,"newSize",b);(0,D.Pc)(h,"oldStartTime",c);(0,D.Pc)(h,"oldEndTime",e);(0,D.gu)(h,g);(0,D.hu)(h,
f);this.dispatchEvent(h)};D.Ot=function(b){var c=b.da(1),d=b.da(b.za()-b.qn),e=b.da(b.za()-(b.qn-1)),f=b.da(b.za()-(b.qn-2)),g=b.da(b.za()-(b.qn-3)),h=b.da(b.za()-(b.qn-4)),j=b.da(b.za()-(b.qn-5));(0,D.cu)(b,d,(0,D.Qt)(b,c),(0,D.Qt)(b,c));(0,D.cu)(b,e,(0,D.Qt)(b,c)+(0,D.eu)(b,c),(0,D.Qt)(b,c)+(0,D.eu)(b,c));(0,D.cu)(b,f,-1,(0,D.Qt)(b,c)+1);(0,D.cu)(b,g,(0,D.du)(b,e)-1,-1);(0,D.cu)(b,h,(0,D.du)(b,d),(0,D.du)(b,e));(0,D.cu)(b,j,(0,D.du)(b,d),(0,D.du)(b,e))};
D.Np.prototype.dispatchEvent=function(b){D.Ip.dispatchEvent(this.fb,this.ka,this,b)};
D.Wt=function(b){this.Init(b)};D.F.o(D.Wt,D.F,"DvtOverviewParser");D.Wt.prototype.Init=(0,D.A)("J");D.Wt.prototype.parse=function(b){return this.$l(b)};
D.Wt.prototype.$l=function(b){var c={};c.OAa=b.animationOnClick;b.startTime!=D.q&&(c.start=b.startTime);b.endTime!=D.q&&(c.end=b.endTime);c.start==D.q&&(c.start=(new window.Date).getTime());if(c.end==D.q||c.end<=c.start)c.end=c.start+864E5;b.currentTime!=D.q&&(c.currentTime=b.currentTime);b.initialFocusTime!=D.q&&(c.GEa=b.initialFocusTime);c.orientation="horizontal";b.orientation!=D.q&&(c.orientation=b.orientation);c.vka=b.featuresOff;c.P7=b.minimumWindowSize;c.lFa=b.leftMargin;c.rGa=b.rightMargin;
if(b.viewportEndTime!=D.q){var d=b.viewportEndTime,e=c.start;b.viewportStartTime!=D.q&&b.viewportStartTime<d&&(e=b.viewportStartTime);c.width=b.viewportEndPos!=D.q?(0,D.nu)(c.start,c.end,e,d,b.viewportEndPos):(0,D.nu)(c.start,c.end,e,d,this.J.rb);c.r8=e}else c.r8=c.start;0==c.width&&(c.width=1E3);c.pna="below";c.WN="none";c.KV=(0,D.ya)(this.J.e).toString();b.rtl!=D.q&&(c.KV=b.rtl.toString());c.j7="#FFFFFF";c.n7="#B3C6DB";c.Y8="#FFFFFF";c.$na=1;c.g9="solid";c.e9="solid";c.a9="solid";c.c9="solid";c.f9=
"#4F4F4F";c.d9="#4F4F4F";c.Z8="#4F4F4F";c.b9="#4F4F4F";c.U7="#E6ECF3";c.F5="#C000D1";c.S8="#BCC7D2";c.Rna="#e5e5e5";c.Sna=1;c.Ima="#FFFFFF";c.Hma=0.7;c.Fna="#FFFFFF";c.Ena=0.7;b.style!=D.q&&(b.style.handleFillColor!=D.q&&(c.j7=b.style.handleFillColor),b.style.handleTextureColor!=D.q&&(c.n7=b.style.handleTextureColor),b.style.handleBackgroundImage!=D.q&&(c.Ula=b.style.handleBackgroundImage),b.style.handleWidth!=D.q&&(c.ima=b.style.handleWidth),b.style.handleHeight!=D.q&&(c.ema=b.style.handleHeight),
b.style.windowBackgroundColor!=D.q&&(c.Y8=b.style.windowBackgroundColor),b.style.windowBackgroundAlpha!=D.q&&(c.$na=b.style.windowBackgroundAlpha),b.style.windowBorderTopStyle!=D.q&&(c.g9=b.style.windowBorderTopStyle),b.style.windowBorderRightStyle!=D.q&&(c.e9=b.style.windowBorderRightStyle),b.style.windowBorderBottomStyle!=D.q&&(c.a9=b.style.windowBorderBottomStyle),b.style.windowBorderLeftStyle!=D.q&&(c.c9=b.style.windowBorderLeftStyle),b.style.windowBorderTopColor!=D.q&&(c.f9=b.style.windowBorderTopColor),
b.style.windowBorderRightColor!=D.q&&(c.d9=b.style.windowBorderRightColor),b.style.windowBorderBottomColor!=D.q&&(c.Z8=b.style.windowBorderBottomColor),b.style.windowBorderLeftColor!=D.q&&(c.b9=b.style.windowBorderLeftColor),b.style.overviewBackgroundColor!=D.q&&(c.U7=b.style.overviewBackgroundColor),b.style.currentTimeIndicatorColor!=D.q&&(c.F5=b.style.currentTimeIndicatorColor),b.style.timeIndicatorColor!=D.q&&(c.S8=b.style.timeIndicatorColor),b.style.leftFilterPanelColor!=D.q&&(c.Ima=b.style.leftFilterPanelColor),
b.style.leftFilterPanelAlpha!=D.q&&(c.Hma=b.style.leftFilterPanelAlpha),b.style.rightFilterPanelColor!=D.q&&(c.Fna=b.style.rightFilterPanelColor),b.style.rightFilterPanelAlpha!=D.q&&(c.Ena=b.style.rightFilterPanelAlpha));return c};D.nu=function(b,c,d,e,f){b=f*(c-b);d=e-d;return 0==b||0==d?0:b/d};
D.aq=function(b){this.Init("overview");this.Fl=b};D.F.o(D.aq,D.oc,"DvtOverviewEvent");D.aq.prototype.Mi=(0,D.C)("Fl");D.aq.prototype.setTime=function(b){(0,D.Pc)(this,"time",b)};D.aq.prototype.getTime=function(){return this.wj("time")};D.gu=function(b,c){(0,D.Pc)(b,"newStartTime",c)};D.hu=function(b,c){(0,D.Pc)(b,"newEndTime",c)};D.aq.prototype.Xg=function(b){(0,D.Pc)(this,"pos",b)};D.aq.prototype.Rf=function(){return this.wj("pos")};
});