define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.el=function(b,c,d){this.Init(b,c,d)};D.F.o(D.el,D.G,"DvtComboBox");D.el.prototype.Init=function(b,c,d){D.el.u.Init.call(this,b,D.q,c);this.F=d;this.pS=[];this.tb=[];this.uja=[];this.zn=0;this.k_=this.wQ=D.t;this.o2=new D.M(0,0,0,0);this.lc=new D.M(0,0,0,0);this.zM=b.Kd();this.H1=(0,D.Vb)();this.Ib=(0,D.gE)(this,c+"_cl");this.k(this.Ib);this.oK=new D.G(b);this.oK.ja(D.t);this.k(this.oK);this.o1=new D.cf(b,100,this.wpa,this,1);this.Dha=new D.cf(b,100,this.Cpa,this,1);this.J0=D.t};
D.el.prototype.lO=function(b){this.zn=b;this.wQ||(0,D.hE)(this);b=new D.iE("cbItemChange",b,this.Gg);this.Gg=D.q;this.Rb(b)};
D.gE=function(b,c){var d=b.e,e=b.e,f=b.D(),f=new D.H(e,0,0,f.g,f.j,c+"_up");(0,D.cl)(f,D.W.JY);(0,D.Xb)(f);f.k((0,D.jE)(e,f.getWidth(),f.getHeight()));var g=b.e,e=b.D(),e=new D.H(g,0,0,e.g,e.j,c+"_up");e.La(D.W.yO);e.H(new D.Gd(0,[D.W.h$,D.W.g$]));(0,D.cl)(e,D.W.JY);e.k((0,D.jE)(g,e.getWidth(),e.getHeight()));var g=b.e,h=b.D(),h=new D.H(g,0,0,h.g,h.j,c+"_up");(0,D.cl)(h,D.W.JY);h.La(D.W.yO);h.H(new D.Gd(0,[D.W.g$,D.W.h$]));h.k((0,D.jE)(g,h.getWidth(),h.getHeight()));d=new D.Yb(d,f,e,h,D.q,c);(0,D.Yv)(d,
b.VI,b);d.setCursor("pointer");b.H1||d.U(D.Eh,b.u$,D.t,b);d.PA=D.n;return d};D.D=D.el.prototype;D.D.pj=function(b,c,d,e,f){b.ja(D.t);this.tb.push(b);this.uja.push(c);c=D.W.qm(this.e,d?d:b);var g=this.o2,h=this.D();c.g>g.g&&(g.g=c.g,h.g=c.g+16);c.j>g.j&&(g.j=c.j,h.j=c.j);this.o2=g;c=D.q;d&&(e&&f)&&(c=[],c[0]=d,c[1]=e,c[2]=f);this.pS.push(c);this.wQ||(this.removeChild(this.Ib),this.Ib=(0,D.gE)(this,b.getId()),this.Fa(this.Ib,0),(0,D.hE)(this))};D.D.getItem=function(b){return this.tb[b]};
D.D.R6=function(){var b=this.zn;return 0>b||b>this.tb.length-1?D.q:this.tb[b]};
D.D.VI=function(b){(0,D.Qe)(b);this.k_&&(this.k_=D.t,this.Rp&&(this.Rp.Za(D.t),this.Rp.getParent().removeChild(this.Rp),this.Rp=D.q));b=this.e;for(var c=this.F?this.F.comboBox:D.q,d=(0,D.Je)(c,"paddingLeft",0),e=(0,D.Je)(c,"paddingBottom",0),f=(0,D.Je)(c,"paddingRight",0),g=(0,D.Je)(c,"paddingInner",0),h=(0,D.Je)(c,"paddingTop",0),j=this.e,m,o,p,r=new D.G(j,"__dd"),u=0;u<this.tb.length;u++)p=this.tb[u],m=D.W.qm(j,p),o=new D.G(j,"__it"+u),(0,D.wa)(o,d,h),o.k(p),p.ja(D.n),p.setCursor("pointer"),h+=
m.j+g,this.va&&(m=new D.ml(this,this.upa,this.u$,D.q,D.q,D.q,this.uja[u]),this.va.la(p,m)),r.k(o);c=D.W.FBa(j,this.o2.g+d+f,h+e-g,c);c.k(r);r=(0,D.Je)(this.F,"background-color",D.q);d=(0,D.Je)(this.F,"backgroundAlpha",1);c.La((0,D.Je)(this.F,"border-color",D.q),(0,D.Je)(this.F,"borderAlpha",1));r&&c.na(r,d);this.Rp=c;c=D.W.qm(b,this.Rp);this.k(this.Rp);r=this.Ib.D();c=(0,D.ya)(b)?-c.g+1*r.g/4:3*r.g/4;(0,D.wa)(this.Rp,c,3*r.j/4);this.Ib.ja(D.t);(0,D.Ar)(this.Ib,D.n);this.Rb(new D.iE("cbShowDropdown"));
(b=b.Sc)&&(this.H1?b.U(D.Jt.Xd,this.cP,D.n,this):b.U(D.Ph,this.cP,D.n,this))};D.D.wpa=function(){(0,D.dl)(this);this.wQ||(0,D.hE)(this)};D.D.cP=function(){this.J0=D.t;this.Dha.reset();this.Dha.start()};D.D.Cpa=function(){this.J0||(this.o1.reset(),this.o1.start())};D.D.u$=function(){(0,D.Qe)()};
D.D.upa=function(b){this.J0=D.n;this.o1.stop();(0,D.Qe)(b);var c;c=b.target;for(var d,e;c;){if((e=c.getId())&&c instanceof D.G&&"__it"==e.substr(0,4)){d=c;break}c=c.getParent()}c=d;var f;this.Rp&&c&&(d=this.Rp.da(0))&&(f=d.Qe(c));(0,D.dl)(this);this.Gg=b;this.lO(f)};D.dl=function(b){b.Rp&&(b.Rp.Za(D.t),(0,D.Ar)(b.Ib,D.t),b.Rb(new D.iE("cbHideDropdown")),b.k_=D.n);var c=b.e.Sc;c&&(b.H1?c.Ra(D.Jt.Xd,b.cP,D.n,b):c.Ra(D.Ph,b.cP,D.n,b));b.Ib.ja(D.n)};D.el.prototype.D=(0,D.C)("lc");
D.hE=function(b){var c=D.n,d=b.zn;if(b.pS&&b.pS.length>d&&(d=b.pS[d])&&2<d.length)(0,D.fl)(b.Ib,d[0]),(0,D.hl)(b.Ib,d[1]),(0,D.gl)(b.Ib,d[2]),c=D.t;c&&(0<b.oK.za()&&b.oK.pp(0),b.oK.k(b.R6()))};D.jE=function(b,c,d){var e=[];e.push(c-12,d/2-2);e.push(c-4,d/2-2);e.push(c-8,d/2+2);e.push(c-12,d/2-2);b=new D.Ma(b,e,D.q);b.La(D.W.yO);b.na(D.W.yO);b.ja(D.t);return b};D.el.prototype.yW=(0,D.A)("va");D.kE=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.o(D.kE,D.H,"DropdownItemSprite");
D.kE.prototype.Init=function(b){D.H.u.Init.call(this,b)};
D.iE=function(b,c,d){this.Init(b,c,d)};D.F.o(D.iE,D.mE,"DvtComboBoxEvent");D.iE.prototype.Init=function(b,c,d){D.iE.u.Init.call(this,"comboBoxEvent");c===D.k&&(c=-1);this.xI=b;this.yB=c;this.lF=d};D.iE.prototype.Ha=(0,D.C)("yB");
D.Xv=function(b,c,d){this.Init(b,c,d)};D.F.o(D.Xv,D.G,"DvtBaseControl");D.Xv.prototype.Init=function(b,c,d){D.Xv.u.Init.call(this,b);this.ca=c;this.e=b;this.zM=b.Kd();this.ad=d};D.Xv.prototype.Kd=(0,D.C)("zM");
D.$D=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.$D,D.Xv,"DvtZoomInButton");D.D=D.$D.prototype;D.D.Init=function(b,c,d,e,f){D.$D.u.Init.call(this,b,d,e);this.o_=D.t;this.lU=new D.cf(b,100,this.Spa,this);this.zC=new D.cf(b,250,this.bY,this,1);this.Dm=c;(0,D.Yv)(this.Dm,this.Qpa,this);this.va=f;b=new D.ml(this,D.q,this.Rpa,this.Y$,this.Y$,D.q,(0,D.ec)(this.ad,"CONTROL_PANEL_ZOOMIN"));this.va.la(this.Dm,b);this.k(this.Dm)};
D.D.Qpa=function(){if(!this.lU.Ug()){var b=this.ca.Hc(),b=(0,D.Me)(this.ca,b),c=new D.Ge(this.e,this.ca.Qa());(0,D.Fe)(this.ca,b,D.k,D.k,c);c.play()}};D.D.Rpa=function(){this.o_=D.n;this.lU.stop();this.zC.stop();this.zC.start()};D.D.Y$=function(){this.o_&&(this.o_=D.t,this.lU.stop(),this.zC.stop())};D.D.bY=function(){this.lU.start()};D.D.Spa=function(){var b=this.ca.Hc();(0,D.Fe)(this.ca,(0,D.Me)(this.ca,b))};D.D.Wg=function(b){this.Dm.setCursor(b?"pointer":D.q);this.Dm.Wg(b);(0,D.Zv)(this.Dm)};
D.aE=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.aE,D.Xv,"DvtZoomOutButton");D.D=D.aE.prototype;D.D.Init=function(b,c,d,e,f){D.aE.u.Init.call(this,b,d,e);this.p_=D.t;this.mU=new D.cf(b,100,this.Vpa,this);this.zC=new D.cf(b,250,this.bY,this,1);this.Em=c;(0,D.Yv)(this.Em,this.Tpa,this);this.va=f;b=new D.ml(this,D.q,this.Upa,this.Z$,this.Z$,D.q,(0,D.ec)(this.ad,"CONTROL_PANEL_ZOOMOUT"));this.va.la(this.Em,b);this.k(this.Em)};
D.D.Tpa=function(){if(!this.mU.Ug()){var b=this.ca.Hc(),b=(0,D.Ne)(this.ca,b),c=new D.Ge(this.e,this.ca.Qa());(0,D.Fe)(this.ca,b,D.k,D.k,c);c.play()}};D.D.Upa=function(){this.p_=D.n;this.mU.stop();this.zC.stop();this.zC.start()};D.D.Z$=function(){this.p_&&(this.p_=D.t,this.mU.stop(),this.zC.stop())};D.D.bY=function(){this.mU.start()};D.D.Vpa=function(){var b=this.ca.Hc();(0,D.Fe)(this.ca,(0,D.Ne)(this.ca,b))};D.D.Wg=function(b){this.Em.setCursor(b?"pointer":D.q);this.Em.Wg(b);(0,D.Zv)(this.Em)};
D.ZD=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.ZD,D.Xv,"DvtZoomToFitButton");D.ZD.prototype.Init=function(b,c,d,e,f){D.ZD.u.Init.call(this,b,d,e);this.ku=c;(0,D.Yv)(this.ku,this.Wpa,this);this.ku.setCursor("pointer");this.va=f;b=new D.ml(this,D.q,D.q,D.q,D.q,D.q,(0,D.ec)(this.ad,"CONTROL_PANEL_ZOOMTOFIT"));this.va.la(this.ku,b);this.k(this.ku)};D.ZD.prototype.Wpa=function(){var b=new D.Ge(this.e,this.ca.Qa());this.ca.ao(b);b.play()};
D.YD=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.o(D.YD,D.Xv,"DvtPanControl");D.D=D.YD.prototype;
D.D.Init=function(b,c,d,e,f,g,h){D.YD.u.Init.call(this,b,e,f);this.Lha=new D.cf(b,50,this.Mpa,this);this.WJ=D.t;this.hT=new D.K(20,20);this.Do=g?g:16777215;c.k(d);d&&(this.Jk=d,this.Jk.Za(D.t),this.Jk.U(D.Jt.Xd,this.G$,D.t,this),(0,D.Vb)()||(this.Jk.U(D.Ib,this.G$,D.t,this),this.Jk.U(D.Eh,this.Dpa,D.t,this),this.Jk.U(D.Ph,this.Hpa,D.t,this),this.Jk.U(D.So,this.Gpa,D.t,this),this.Jk.U(D.To,this.Fpa,D.t,this)),this.Jk.U(D.Oh,this.Epa,D.t,this));this.vn=c;this.vn.U(D.Jt.Xd,this.H$,D.t,this);(0,D.Vb)()||
(this.vn.U(D.Ib,this.H$,D.t,this),this.vn.U(D.Eh,this.Ipa,D.t,this),this.vn.U(D.Ph,this.I$,D.t,this),this.vn.U(D.So,this.Lpa,D.t,this),this.vn.U(D.To,this.Kpa,D.t,this),this.vn.U(D.Oh,this.Jpa,D.t,this));this.Xt=D.W.mBa(b,h);this.Xt.k(this.vn);this.k(this.Xt)};D.D.H$=function(b){(0,D.Qe)(b)};D.D.Ipa=function(b){(0,D.Qe)(b);this.WJ=D.n;this.Jk&&this.Jk.Za(D.t);b=(0,D.Ke)(this.ca,b);b=this.vn.Cb(b);(0,D.fE)(this,b.x,b.y,this.vn.Qg);this.f3=new D.K(b.x,b.y);this.Lha.start();this.Mha=0};
D.D.I$=function(b){this.WJ&&((0,D.Qe)(b),this.WJ=D.t,this.Jk&&this.Jk.Za(D.n),this.Lha.stop());this.vn.Tr(b);this.Kd().sc()};D.D.Lpa=function(b){this.Jk&&this.Jk.Za(D.n);var c=(0,D.ec)(this.ad,"CONTROL_PANEL_PAN");this.Kd().qO(b.pageX,b.pageY,c,b.target)};D.D.Kpa=function(b){this.I$(b);this.Jk&&this.Jk.Za(D.t)};D.D.Jpa=function(b){(0,D.Qe)(b);b=(0,D.Ke)(this.ca,b);b=this.vn.Cb(b);this.WJ?((0,D.fE)(this,b.x,b.y,this.vn.Qg),this.f3=new D.K(b.x,b.y)):(0,D.fE)(this,b.x,b.y,this.vn.xh)};
D.D.Mpa=function(){if(this.WJ){var b=window.Math.atan2(this.hT.y-this.f3.y,this.hT.x-this.f3.x),c=window.Math.cos(b),b=window.Math.sin(b),d=15;this.Mha++;40<this.Mha&&(d*=3);this.ca.dk(d*c,d*b)}};D.D.G$=function(b){(0,D.Qe)(b);this.ca.KW()};D.D.Dpa=function(b){(0,D.Qe)(b)};D.D.Hpa=function(b){(0,D.Qe)(b);this.Kd().sc()};D.D.Gpa=function(b){var c=(0,D.ec)(this.ad,"CONTROL_PANEL_ZOOMANDCENTER");this.Kd().qO(b.pageX,b.pageY,c,b.target);this.Jk.Za(D.n);(0,D.Qe)(b)};
D.D.Fpa=function(b){this.Kd().sc();(0,D.Qe)(b)};D.D.Epa=function(b){(0,D.Qe)(b)};D.fE=function(b,c,d,e){e.Ti(window.Math.atan2(d-b.hT.y,c-b.hT.x)-window.Math.PI/4)};
D.lE=function(b){this.Init("dvtPZCPExpand");this.Fl=b};D.F.o(D.lE,D.oc,"DvtControlPanelEvent");D.lE.prototype.Mi=(0,D.C)("Fl");
D.je=function(b,c,d){this.Init(b,c,d)};D.F.o(D.je,D.G,"DvtControlPanel");D.nE=[0,0.25,0.5,0.75,1];
D.je.prototype.Init=function(b,c,d){D.je.u.Init.call(this,b);this.i_=this.sQ=D.t;this.ca=c.ca;this.Do=c.vl;this.ad=c.hd();this.sl=(0,D.ce)(c);this.zM=b.Kd();this.F=D.q;if(this.J=c)this.F=this.J.vs(),this.F.centerButtonDisplayed||(this.Do&=-17,this.J.vl=this.Do);this.HAa=D.nE;this.bn=D.t;this.Kj=this.F.backgroundAlpha;this.va=new D.Pe(b,D.q,c);this.va.Zr.push(D.je);this.va.nf(this);this.va.la(this,this);this.ud=d;this.LLa=D.t;(0,D.wb)(this)};D.je.prototype.Kd=(0,D.C)("zM");
D.Se=function(b){b.sQ=D.n;b.eb.ja(D.t);b.yd.ja(D.t);b.eb.C(b.F.backgroundDragAlpha);b.yd.C(b.F.borderDragAlpha)};D.bf=function(b){b.sQ=D.t;b.eb.ja(D.n);b.yd.ja(D.n);b.i_?b.Yl(D.q):b.hl(D.q)};D.je.prototype.WH=(0,D.ba)(D.n);D.je.prototype.On=function(){var b=0,b=this.WH()?D.Rm.zV():D.Rm.On();return window.Math.max((0,D.Je)(this.F,"tabSize",0),b)};
D.oE=function(b){var c=b.e,d=new D.G(c),e=b.On(),f=(0,D.ya)(c);b.eb=D.Rm.aka(c,e,b.F,f);b.yd=D.Rm.y5(c,e,b.F,f);b.Nua=D.W.qm(c,b.yd);b.Lc=D.W.BU(b.e,b.sl,b.On(),b.F,f);(0,D.Yv)(b.Lc,b.VI,b);b.Lc.setCursor("pointer");c=new D.ml(b,D.q,D.q,D.q,D.q,D.q,(0,D.ec)(b.ad,"CONTROL_PANEL"));b.va.la(b.Lc,c);b.yd.k(b.Lc);d.k(b.eb);d.k(b.yd);return d};
D.pE=function(b){var c=b.e,d=new D.G(c);b.eb=new D.G(c);b.yd=new D.G(c);d.k(b.eb);d.k(b.yd);var e=(0,D.ya)(c),f=0,g=new D.G(c),h;h=0;var j=b.e,m=b.WH();0!=(b.Do&16)&&(b.Xt=D.W.nBa(j,b.ca,b.ad,b.Do,b.sl,b.F),m&&(b.dw=D.W.gka(j,b.F),b.PL=D.W.gka(j,b.F),g.k(b.PL),g.k(b.dw)),g.k(b.Xt),h++);b.Ai=D.W.zU(b.e,b.sl,b.On(),b.F,(0,D.ya)(b.e));(0,D.Yv)(b.Ai,b.LX,b);b.Ai.setCursor("pointer");j=new D.ml(b,D.q,D.q,D.q,D.q,D.q,(0,D.ec)(b.ad,"CONTROL_PANEL"));b.va.la(b.Ai,j);g.k(b.Ai);b.nr=new D.G(b.e);b.jJ(b.nr);
0<b.nr.za()?(g.k(b.nr),h++):b.nr=D.q;var j=f,f=b.e,o=D.q,m=(0,D.Je)(b.F,"openCloseButtonWidth",0),p=(0,D.Je)(b.F,"buttonWidth",0),r=(0,D.Je)(b.F,"tabSize",0),u=b.On(),w=(0,D.Je)(b.F.hbar,"paddingLeft",0),z=(0,D.Je)(b.F.hbar,"paddingInner",0);e?(b.Ai.G(0),j+=m,b.nr&&(o=D.W.qm(f,b.nr),j+=z,(0,D.wa)(b.nr,j,(u-o.j)/2),j+=window.Math.max(o.g,p)),b.Xt&&(j+=z,o=3.5,(0,D.wa)(b.Xt,j,o),b.dw&&(0,D.wa)(b.dw,j,o),b.PL&&(0,D.wa)(b.PL,j,o),o=D.W.qm(f,b.Xt),j+=o.g),j+=w):(b.Xt&&(j+=w,o=3.5,(0,D.wa)(b.Xt,w,o),b.dw&&
(0,D.wa)(b.dw,w,o),b.PL&&(0,D.wa)(b.PL,w,o),o=D.W.qm(f,b.Xt),j+=z+o.g,j+=1),b.nr&&(o=D.W.qm(f,b.nr),0==j&&(j+=w),(0,D.wa)(b.nr,j,(u-o.j)/2),j+=o.g,j=window.Math.max(j+z,r)),b.Ai.G(j),j+=m);f=j;j=D.q;m=b.Do&16||b.F&&b.F.panelDrawerStyles&&0==h?(0,D.Je)(b.F.vbar,"paddingTop",0):0;b.WH()&&0!=(b.Do&16)&&(m+=D.Rm.On()-b.On());if(0!=(b.Do&256)||0!=(b.Do&4097))j=new D.G(c),j.P(g.L()+b.On()),r=j,0!=(b.Do&256)&&(u=(0,D.Je)(b.F.vbar,"paddingInner",0),w=(0,D.Je)(b.F.vbar,"paddingLeft",0),b.ku=D.W.zBa(b.e,b.ca,
b.ad,b.va,b.sl,b.F),(0,D.wa)(b.ku,w,b.ku.L()+m),w=D.W.qm(b.e,b.ku),r.k(b.ku),m+=w.j,m+=u),r=j,u=D.q,w=(0,D.Je)(b.F.vbar,"paddingInner",0),z=(0,D.Je)(b.F.vbar,"paddingLeft",0),0!=(b.Do&4097)&&(b.Dm=D.W.xBa(b.e,b.ca,b.ad,b.va,b.sl,b.F),(0,D.wa)(b.Dm,z,b.Dm.L()+m),u=D.W.qm(b.e,b.Dm),r.k(b.Dm),m+=u.j+w,b.Em=D.W.yBa(b.e,b.ca,b.ad,b.va,b.sl,b.F),(0,D.wa)(b.Em,z,b.Em.L()+m),u=D.W.qm(b.e,b.Em),r.k(b.Em),m+=u.j,r=b.ca.Hc(),u=(0,D.Me)(b.ca,r),w=(0,D.Ne)(b.ca,r),b.Dm&&b.Dm.Wg(r!=u),b.Em&&b.Em.Wg(r!=w)),b.yd.k(j);
var w=j,z=h,r=b.e,B=(0,D.Je)(b.F,"openCloseButtonWidth",0),u=(0,D.Je)(b.F,"tabSize",0),f=(o=(0,D.Je)(b.F,"panelDrawerStyles",D.q))?f:f-B,p=b.On(),I=0,E=0;o?o&&0==z&&(E=e?-u:u):(I=e?B:0,E=e?B:0);if(0<z||o){var J=B=D.q,J=(0,window.parseInt)((0,D.Je)(b.F,"border-radius",0));o?(e=0<z&&w!=D.q?D.Rm.jY:D.Rm.kY,B=D.Rm.fna(r,J,f,p,e,u),J=D.Rm.fna(r,J,f,p,e,u)):(B=D.Rm.bka(r,f,b.On(),!e,b.F),J=D.Rm.bka(r,f,b.On(),!e,b.F));B.La((0,D.Je)(b.F,"border-color",D.q));B.H(D.q);(0,D.wa)(B,g.N()+I,g.L());g.Fa(B,0);J.na((0,D.Je)(b.F,
"background-color",D.q));(0,D.wa)(J,g.N()+E,g.L());b.eb.k(J)}b.yd.k(g);e=j;f=b.e;r=(0,D.ya)(f);u=(0,D.Je)(b.F,"openCloseButtonWidth",0);!b.nr&&0==(b.Do&16)?r?(g.G(0-g.N()),g.P(0),e&&(D.W.qm(f,e),g.G(g.N()-u),e.P(0))):e?(f=(0,D.Je)(b.F,"tabSize",0),(0,D.wa)(e,0,0),(0,D.wa)(g,g.N()+f,0)):(0,D.wa)(g,g.N(),0):r&&e&&(f=D.W.qm(f,g),r=(0,D.Je)(b.F,"tabSize",0),g.G(0),e.G(f.g+f.x-r));e=j;r=m;j=b.e;e&&(f=e.za(),f=1<f||b.ku==D.q||1<h||0<h&&1==f,m=D.q,b.F&&b.F.panelDrawerStyles&&(m=0<h?D.Rm.mY:D.Rm.lY),g=D.W.qm(j,
g),r+=4,h=f?r:window.Math.max(g.j,r),h+=(0,D.Je)(b.F.vbar,"paddingBottom",0),g=D.Rm.hGa(j,h,b.F,m,b.On()),h=D.Rm.gGa(j,h,f,b.F,m,b.On()),(0,D.wa)(g,e.N(),e.L()),b.eb.k(g),e.Fa(h,0));b.Mva=D.W.qm(c,d);return d};D.je.prototype.jJ=(0,D.v)();D.je.prototype.sO=function(){this.bn||(2===this.ud?this.dB():1===this.ud&&this.GK())};D.je.prototype.VI=function(b){(0,D.Qe)(b);this.bn||(this.GK(),this.Kd()&&this.Kd().sc())};
D.je.prototype.GK=function(){this.bn=D.n;this.ja(D.t);var b=(0,D.pE)(this);this.k(b);(0,D.qE)(this);var c=this.da(0),d=c.D(),e=(0,D.Je)(this.F,"openCloseButtonWidth",0);if(d&&0!=d.g){var f=b.D(),g=new D.Ge(this.e,0.25);c.C(1);b.C(0);(0,D.P)(g,"typeNumber",c,c.aa,c.C,0);(0,D.P)(g,"typeNumber",b,b.aa,b.C,1);b.Fd(d.g/f.g);(0,D.P)(g,"typeNumber",b,b.Qb,b.Fd,1);if((0,D.ya)(this.e)){b.G(c.N());var h=f.g+f.x;(0,D.P)(g,"typeNumber",b,b.N,b.G,c.N()+e-h)}b.wd(d.j/f.j);(0,D.P)(g,"typeNumber",b,b.Ub,b.wd,1);
g.qd(function(){c.getParent().removeChild(c);this.bn=D.t;this.ja(D.n)},this);g.play()}else c.getParent().removeChild(c),(0,D.ya)(this.e)?(f=(0,D.Lf)(this.e,b),h=window.Math.floor(f.g+f.x),d=e-h):d=0,(0,D.wa)(b,d,0);this.ud=2;b=new D.lE("show");this.Rb(b)};D.qE=function(b){var c=D.t;b.e.Sc&&(c=D.n);c?(0,D.rE)(b):(0,D.sE)(b)};D.je.prototype.LX=function(b){(0,D.Qe)(b);this.bn||this.dB()};
D.je.prototype.dB=function(){this.bn=D.n;var b=(0,D.oE)(this);this.k(b);(0,D.qE)(this);var c=this.da(0),d=new D.Ge(this.e,0.25);c.C(1);b.C(0);(0,D.P)(d,"typeNumber",c,c.aa,c.C,0);(0,D.P)(d,"typeNumber",b,b.aa,b.C,1);var e=this.Nua,f=this.Mva;(0,D.P)(d,"typeNumber",c,c.Qb,c.Fd,e.g/f.g);(0,D.ya)(this.e)&&(0,D.P)(d,"typeNumber",c,c.N,c.G,b.N());(0,D.P)(d,"typeNumber",c,c.Ub,c.wd,e.j/f.j);d.qd(function(){c.getParent().removeChild(c);this.bn=D.t},this);d.play();this.ud=1;b=new D.lE("hide");this.Rb(b)};
D.je.prototype.Yl=function(){this.i_=D.n;this.sQ||(0,D.rE)(this)};D.je.prototype.hl=function(){this.i_=D.t;this.sQ||(0,D.sE)(this)};D.rE=function(b){b.eb.C(b.F.backgroundHoverAlpha);b.yd.C(b.F.borderHoverAlpha);b.dw&&b.dw.C(b.F.backgroundHoverAlpha)};D.sE=function(b){b.eb.C(b.Kj);b.yd.C(b.F.borderAlpha);b.dw&&b.dw.C(b.Kj)};D.je.prototype.D=function(){this.lc||(this.lc=D.je.u.D.call(this));return this.lc};
D.je.prototype.Pm=function(){var b;b=1==this.ud?(0,D.oE)(this):(0,D.pE)(this);this.eb.C(this.Kj);this.yd.C(this.F.borderAlpha);this.k(b)};D.je.prototype.Fq=(0,D.C)("sl");D.Ce=function(b,c){b.Dm&&b.Dm.Wg(c)};D.De=function(b,c){b.Em&&b.Em.Wg(c)};
D.fe={};D.F.o(D.fe,D.F,"DvtControlPanelDefaults");
D.fe.SY={"fill-type":"solid",backgroundAlpha:1,backgroundDragAlpha:1,borderDragAlpha:1,panelDrawerStyles:D.n,buttonWidth:42,buttonHeight:42,buttonRadius:0,openCloseButtonWidth:42,tabSize:42,paddingTop:15,paddingSide:-1,imageWidth:24,imageHeight:24,centerButtonDisplayed:D.t,scrollbarBackground:"linear-gradient(bottom, #dce2e7 0%, #f8f8f8 8%)",scrollbarBorderColor:"#dce2e7",scrollbarHandleColor:"#abb0b4",scrollbarHandleHoverColor:"#333333",scrollbarHandleActiveColor:"#333333",comboBox:{paddingTop:0,
paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0,itemHeight:30,imagePadding:0,itemPadding:10},vbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0},hbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0}};D.fe.TY={"fill-type":"solid"};
D.fe.fA={"fill-type":"gradient","border-color":"#ffffff","background-color":"#ffffff","border-radius":6,backgroundAlpha:0.5,backgroundHoverAlpha:1,backgroundDragAlpha:0.5,borderAlpha:1,borderHoverAlpha:1,borderDragAlpha:0.5,tabSize:26,buttonWidth:22,buttonHeight:22,buttonRadius:3,paddingTop:5,paddingSide:5,imageWidth:22,imageHeight:20,openCloseButtonWidth:10,centerButtonDisplayed:D.n,comboBox:{paddingTop:2,paddingBottom:6,paddingLeft:3,paddingRight:3,paddingInner:2,itemHeight:22,radius:4,imagePadding:2,
itemPadding:7},vbar:{paddingTop:2.5,paddingBottom:2.5,paddingLeft:2,paddingRight:2,paddingInner:2},hbar:{paddingTop:2,paddingBottom:2,paddingLeft:3,paddingRight:3,paddingInner:2}};D.fe.Pg=function(b){var c=D.fe.qB(b);return b?D.Ta.Bb(b,c):c};D.fe.qB=function(b){var c=D.q;return c=b&&"skyros"===b.skin?D.Ta.Bb(D.fe.TY,D.fe.fA):b&&"alta"===b.skin?D.Ta.Bb(D.fe.SY,D.fe.fA):D.Ta.clone(D.fe.fA)};
D.Pe=function(b,c,d){this.Init(b,c,d)};D.F.o(D.Pe,D.Uc,"DvtControlPanelEventManager");D.D=D.Pe.prototype;D.D.il=function(b){var c=(0,D.gb)(this,(0,D.Wc)(b));D.Pe.u.il.call(this,b);c&&(c.lo&&c.lo(b),b.stopPropagation())};D.D.Zm=function(b){var c=(0,D.gb)(this,(0,D.Wc)(b));D.Pe.u.Zm.call(this,b);c&&(c.mo&&c.mo(b),b.stopPropagation())};D.D.ik=function(b){var c=(0,D.gb)(this,(0,D.Wc)(b));D.Pe.u.ik.call(this,b);c&&(c.cE&&c.cE(b),b.stopPropagation())};
D.D.bh=function(b){var c=(0,D.gb)(this,(0,D.Wc)(b));D.Pe.u.bh.call(this,b);c&&(c.Pc&&c.Pc(b),b.stopPropagation())};D.D.Yu=function(b){D.Pe.u.Yu.call(this,b);var c=(0,D.gb)(this,(0,D.Wc)(b));c&&c.Yl&&c.Yl(b)};D.D.Xu=function(b){D.Pe.u.Xu.call(this,b);var c=(0,D.gb)(this,(0,D.Wc)(b));c&&c.hl&&c.hl(b)};D.D.ct=function(b){var c=(0,D.gb)(this,(0,D.Wc)(b));c&&(c.Pc&&c.Pc(b),b.stopPropagation())};D.D.bE=function(b){b.pu();(0,D.Qe)(b)};
D.ml=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.o(D.ml,D.F,"DvtControlPanelEventHandlerProxy");D.D=D.ml.prototype;D.D.Init=function(b,c,d,e,f,g,h){this.ka=b;this.vy=c;this.$ea=e;this.NR=d;this.OR=f;this.PR=g;this.af=h};D.D.Pc=function(b){this.vy&&this.vy.call(this.ka,b)};D.D.lo=function(b){this.NR&&this.NR.call(this.ka,b)};D.D.mo=function(b){this.$ea&&this.$ea.call(this.ka,b)};D.D.cE=function(b){this.OR&&this.OR.call(this.ka,b)};D.D.ZO=function(b){this.PR&&this.PR.call(this.ka,b)};
D.D.he=(0,D.C)("af");
D.Rm={};D.F.o(D.Rm,D.F,"DvtControlPanelLAFUtils");D.Rm.mY="top";D.Rm.lY="right";D.Rm.kY="left";D.Rm.jY="bottom";D.Rm.nba=47;D.Rm.mba=26;D.Rm.Gd=window.Math.sin(window.Math.PI/4);D.Rm.Hd=window.Math.tan(window.Math.PI/8);D.Rm.On=function(){return D.Rm.nba};D.Rm.zV=function(){return D.Rm.mba};D.Rm.bka=function(b,c,d,e,f){c||(c=86);d||(d=47);e===D.k&&(e=D.n);f=(0,window.parseInt)((0,D.Je)(f,"border-radius",0));return D.Rm.yFa(b,f,c-2*f,d-2*f,e)};
D.Rm.yFa=function(b,c,d,e,f){var g=d+c,h=e+c,j=window.DvtPathUtils.moveTo(g+c,h+c),j=j+window.DvtPathUtils.lineTo(g-d,h+c),g=g-d,j=j+window.DvtPathUtils.lineTo(g-c,h+c),j=j+window.DvtPathUtils.lineTo(g-c,h-e),h=h-e;f?(j+=window.DvtPathUtils.Zb(-c+g,-D.Rm.Hd*c+h,-D.Rm.Gd*c+g,-D.Rm.Gd*c+h)+window.DvtPathUtils.Zb(-D.Rm.Hd*c+g,-c+h,g,-c+h)+window.DvtPathUtils.lineTo(g,-c+h),j+=window.DvtPathUtils.lineTo(g+d+c,-c+h),j+=window.DvtPathUtils.lineTo(g+d+c,h+e)):(j+=window.DvtPathUtils.lineTo(g-c,-c+h),j+=
window.DvtPathUtils.lineTo(g+d,-c+h),g+=d,j+=window.DvtPathUtils.Zb(D.Rm.Hd*c+g,-c+h,D.Rm.Gd*c+g,-D.Rm.Gd*c+h)+window.DvtPathUtils.Zb(c+g,-D.Rm.Hd*c+h,c+g,h)+window.DvtPathUtils.lineTo(g+c,h+e));j+=window.DvtPathUtils.closePath();return new D.Ra(b,j)};
D.Rm.aka=function(b,c,d,e){c||(c=47);var f=(0,window.parseInt)((0,D.Je)(d,"border-radius",0)),g=(0,D.Je)(d,"openCloseButtonWidth",0);c=window.Math.max(c,(0,D.Je)(d,"buttonHeight",c));e=D.W.yX(g,c,f,e);e=e.concat("Z");b=new D.Ra(b,e,"cls_shape");(e=(0,D.Je)(d,"tab-color-inactive",D.q))||(e=(0,D.Je)(d,"background-color",D.q));b.na(e);return b};
D.Rm.y5=function(b,c,d,e){c||(c=47);var f=(0,window.parseInt)((0,D.Je)(d,"border-radius",0)),g=(0,D.Je)(d,"openCloseButtonWidth",0);c=window.Math.max(c,(0,D.Je)(d,"buttonHeight",c));e=D.W.yX(g,c,f,e);e=e.concat("Z");b=new D.Ra(b,e,"cls_shape");b.La((0,D.Je)(d,"border-color",D.q));b.H(D.q);return b};
D.Rm.hGa=function(b,c,d,e,f){c||(c=137);var g=(0,window.parseInt)((0,D.Je)(d,"border-radius",0)),h=(0,D.Je)(d,"tabSize",0),j=h-2*g,m=c+7-2*g;b=e&&f?D.Rm.hna(b,g,h,c,e,f):D.Rm.gna(b,g,j,m);b.na((0,D.Je)(d,"background-color",D.q));return b};D.Rm.gGa=function(b,c,d,e,f,g){c||(c=137);d||(d=D.n);var h=(0,window.parseInt)((0,D.Je)(e,"border-radius",0)),j=(0,D.Je)(e,"tabSize",0),m=j-2*h,o=c+7-2*h,p=D.q,p=f&&g?D.Rm.hna(b,h,j,c,f,g):D.Rm.gna(b,h,m,o,d);p.La((0,D.Je)(e,"border-color",D.q));p.H(D.q);return p};
D.Rm.gna=function(b,c,d,e,f){f||(f=D.n);var g=d+c,h=e,j=window.DvtPathUtils.moveTo(g+c,h),j=f?j+(window.DvtPathUtils.Zb(c+g,D.Rm.Hd*c+h,D.Rm.Gd*c+g,D.Rm.Gd*c+h)+window.DvtPathUtils.Zb(D.Rm.Hd*c+g,c+h,g,c+h)+window.DvtPathUtils.lineTo(g,c+h)):j+window.DvtPathUtils.lineTo(g+c,h+c),j=j+window.DvtPathUtils.lineTo(g-d,c+h),g=g-d,j=j+(window.DvtPathUtils.Zb(-D.Rm.Hd*c+g,c+h,-D.Rm.Gd*c+g,D.Rm.Gd*c+h)+window.DvtPathUtils.Zb(-c+g,D.Rm.Hd*c+h,-c+g,h)+window.DvtPathUtils.lineTo(-c+g,h)+window.DvtPathUtils.lineTo(-c+
g,h-e)),h=h-e,j=j+(window.DvtPathUtils.lineTo(g+d+c,h)+window.DvtPathUtils.lineTo(g+d+c,h+e)+window.DvtPathUtils.closePath());return new D.Ra(b,j)};D.Rm.hna=function(b,c,d,e,f,g){c=D.Rm.r$(d,e,c,f,g);return new D.Ra(b,c)};D.Rm.fna=function(b,c,d,e,f,g){c=D.Rm.r$(d,e,c,f,g);return new D.Ra(b,c)};
D.Rm.r$=function(b,c,d,e,f){var g,h=(0,D.ya)();e==D.Rm.mY&&!h&&(g=["M",b,0,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c,"L",0,0]);e==D.Rm.mY&&h?g=["M",b,0,"L",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",0,0]:e==D.Rm.lY&&!h?g=["M",b,f,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c,"L",0,0,"L",b,0]:e==D.Rm.lY&&h?g=["M",0,0,"L",b,0,"L",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",0,f]:e==D.Rm.kY&&!h?g=["M",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c]:e==D.Rm.kY&&h?g=["M",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",
0,d,"A",d,d,0,0,1,d,0,"L",b,0]:e==D.Rm.jY&&!h?g=["M",0,c,"L",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",f,c]:e==D.Rm.jY&&h&&(g=["M",b,c,"L",b,0,"L",d,0,"A",d,d,0,0,0,0,d,"L",0,c-d,"A",d,d,0,0,0,d,c,"L",b-f,c]);return g};
D.Yd=function(b,c,d){this.Init(b,c,d)};(0,D.ta)("DvtPanZoomComponent",D.Yd);D.F.o(D.Yd,D.Zd,"DvtPanZoomComponent");D.Yd.prototype.Init=function(b,c,d){D.Yd.u.Init.call(this,b,c,d);this.qK="initCollapsed";this.vl=16777215;this.Ce=!(0,D.$d)()&&!((0,D.Bb)()&&17>=(0,D.ae)());this.x4=this.I3=D.q;this.Eb=""};D.be=function(b){return b.ca};D.ce=function(b){b.I3||(b.I3=b.Q?b.Q.resources:{});return b.I3};D.Yd.prototype.hd=function(){this.Eg||(this.Eg=new D.de);return this.Eg};D.Yd.prototype.vs=(0,D.C)("x4");
D.ge=function(b,c){var d=(new D.O(c.inlineStyle)).A("background-color");d&&(b.R0=d);var d={},e=c.skin;e&&(b.Eb=e,d.skin=e);(0,D.ee)(d,"background-color",c.cpBackgroundColor);(0,D.ee)(d,"border-color",c.cpBorderColor);(0,D.ee)(d,"border-radius",c.cpBorderRadius);(0,D.ee)(d,"box-shadow",c.cpBoxShadow);(0,D.ee)(d,"tab-color-inactive",c.tabBgColorInactive);(0,D.ee)(d,"tab-border-color-inactive",c.tabBorderColorInactive);(0,D.ee)(d,"scrollbarBackground",c.scrollbarBg);(0,D.ee)(d,"scrollbarBorderColor",
c.scrollbarBorderColor);(0,D.ee)(d,"scrollbarHandleColor",c.scrollbarHandleColor);(0,D.ee)(d,"scrollbarHandleActiveColor",c.scrollbarHandleActiveColor);(0,D.ee)(d,"scrollbarHandleHoverColor",c.scrollbarHandleHoverColor);d=D.fe.Pg(d);b.x4=d};
D.he=function(b,c){var d=(new D.O(c.q("inlineStyle"))).A("background-color");d&&(b.R0=d);var d={},e=c.q("skin");e&&(b.Eb=e,d.skin=e);(0,D.ee)(d,"background-color",c.q("cpBackgroundColor"));(0,D.ee)(d,"border-color",c.q("cpBorderColor"));(0,D.ee)(d,"border-radius",c.q("cpBorderRadius"));(0,D.ee)(d,"box-shadow",c.q("cpBoxShadow"));(0,D.ee)(d,"tab-color-inactive",c.q("tabBgColorInactive"));(0,D.ee)(d,"tab-border-color-inactive",c.q("tabBorderColorInactive"));(0,D.ee)(d,"scrollbarBackground",c.q("scrollbarBg"));
(0,D.ee)(d,"scrollbarBorderColor",c.q("scrollbarBorderColor"));(0,D.ee)(d,"scrollbarHandleColor",c.q("scrollbarHandleColor"));(0,D.ee)(d,"scrollbarHandleActiveColor",c.q("scrollbarHandleActiveColor"));(0,D.ee)(d,"scrollbarHandleHoverColor",c.q("scrollbarHandleHoverColor"));d=D.fe.Pg(d);b.x4=d};
D.Yd.prototype.M=function(b,c,d){this.R=c;this.Y=d;this.By=!b;this.lJ();if(!this.By)if("object"==typeof b)this.Wd(b);else if(!(b==D.q||0==b.length)){var e=new D.ie;if(e&&(e=e.parse(b)))"r"===e.getName()&&(e=e.getFirstChild()),e&&this.kA().G7(e)}this.ti(b,c,d)};D.Yd.prototype.render=D.Yd.prototype.M;D.D=D.Yd.prototype;D.D.OO=function(){var b=this.ox();return"hidden"!=b?new D.je(this.e,this,"initCollapsed"==b?1:2):D.q};D.D.ox=(0,D.C)("qK");D.D.kA=(0,D.ba)(D.q);D.D.Ws=(0,D.v)();D.D.eg=(0,D.v)();
D.D.lJ=(0,D.v)();
D.D.ti=function(){if(this.R0||!this.Eb){var b=new D.H(this.e,0,0,0,0);this.k(b);b.ia(this.R);b.ta(this.Y);b.H((0,D.me)(this,this.R0))}if(this.By)this.ca.fk(this.R,this.Y);else{this.ca&&(this.removeChild(this.ca),this.ca=D.q);this.ca=new D.ne(this.e,this.R,this.Y,this);this.ca.U("dvtPan",this.Ws,D.t,this);this.ca.U("dvtZoom",this.eg,D.t,this);this.k(this.ca);if(b=this.OO())b.U("dvtPZCPExpand",this.Iwa,D.t,this),this.ca.Qc=b;this.ca.Pm()}b=new D.td("comp");(0,D.ud)(b,this.N(),this.L(),this.R,this.Y);
(0,D.vd)(this,b)};D.D.Wd=function(b){this.Q=this.ff?this.ff.Pg(b):b};
D.me=function(b,c){var d,e=1;if(c&&"#7396C8"!=c){e=D.U.aa(c);d=(D.U.kd("#AECDEA")-D.U.kd("#7396C8"))/(255-D.U.kd("#7396C8"));var f=(D.U.jd("#AECDEA")-D.U.jd("#7396C8"))/(255-D.U.jd("#7396C8")),g=(D.U.gd("#AECDEA")-D.U.gd("#7396C8"))/(255-D.U.gd("#7396C8")),h=D.U.kd(c),j=D.U.jd(c),m=D.U.gd(c);d=D.U.Ww(window.Math.round(h+d*(255-h)),window.Math.round(j+f*(255-j)),window.Math.round(m+g*(255-m)));f=D.U.Ki(c);d=["#FFFFFF","#FFFFFF",d,f]}else d=["#FFFFFF","#FFFFFF","#AECDEA","#7396C8"];var e=[e,e,e,e],
f=[0,45/255,190/255,1],j=b.R,g=1.7*1.7*j,h=1.7*b.Y,j=0+(j-g)/2,m=j+g/2,o=-35+h/2,p=1.5*window.Math.min(g/2,h/2);return new D.oe(d,e,f,m,o,p,[j,-35,g,h])};D.Yd.prototype.Iwa=function(b){var c=new D.Oc;(0,D.Pc)(c,"controlPanelBehavior","show"==b.Mi()?"initExpanded":"initCollapsed");this.Ya(c)};
D.ne=function(b,c,d,e){this.Init(b,c,d,e)};D.F.o(D.ne,D.G,"DvtPanZoomCanvas");
D.ne.prototype.Init=function(b,c,d,e){D.ne.u.Init.call(this,b);this.J=e;this.tg=c;this.Hg=d;this.Qt=this.Pt=this.bz=this.oG=0;this.jq=this.lq=this.iq=this.kq=D.q;this.zl=0.1;this.sm=1;this.iT=15;this.OM=0.05;this.oIa=D.t;this.hp=20;this.Qc=D.q;this.Lca=this.wr=this.Jj=D.n;this.zQ=new D.H(this.e,0,0,this.tg,this.Hg);this.k(this.zQ);(0,D.Xb)(this.zQ);this.$=new D.G(this.e);this.k(this.$);this.$.qa(new D.sd);this.it=0.5;this.va=new D.pe(b,this.Rb,this);this.va.nf(this);this.zIa=1;(0,D.qe)(this,c,d);
this.KA=D.t;this.Go=D.q};D.ne.prototype.fk=function(b,c,d){this.tg=b;this.Hg=c;d||(this.zQ.ia(b),this.zQ.ta(c),this.Qc&&(0,D.re)(this),(0,D.qe)(this,b,c))};D.ne.prototype.rc=function(){return new D.se(this.tg,this.Hg)};D.qe=function(b,c,d){var e=new D.td("pzc");(0,D.ud)(e,b.N(),b.L(),c,d);(0,D.vd)(b,e)};D.te=function(b){return b.$};D.ve=function(b,c){if(c){var d=(0,D.ue)(c,b.$,b.$.ma);if(d)return d}return b.$.ma()};D.ne.prototype.Hc=function(b){return(0,D.ve)(this,b).Kc};
D.ne.prototype.dk=function(b,c,d){if(this.Jj){var e=(0,D.ve)(this,d).Ab,f=(0,D.ve)(this,d).wb,g=(0,D.we)(this,e+b),h=(0,D.xe)(this,f+c);c=g-e;var j=h-f;b=D.q;d&&(b=(0,D.ue)(d,this.$,this.$.ma))&&(b=b.clone());b||(b=this.$.ma().clone());b.translate(c,j);var m=this;c=function(){var b=new D.ye("panning",g,h,e,f,d);m.Rb(b)};j=function(){var b=new D.ye("panned",g,h,e,f,d);m.Rb(b)};d?((0,D.P)(d,"typeMatrix",this.$,this.$.ma,this.$.qa,b),(0,D.ze)(d,c),(0,D.$a)(d,j)):(c(),this.$.qa(b),j())}};
D.Ae=function(b,c,d,e){b.Jj&&(c-=(0,D.ve)(b,e).Ab,d-=(0,D.ve)(b,e).wb,b.dk(c,d,e))};
D.ne.prototype.QD=function(b,c,d,e){if(this.wr){!c&&0!==c&&(c=this.tg/2);!d&&0!==d&&(d=this.Hg/2);var f=this.Hc(e),g=(0,D.Be)(this,f*b);this.Qc&&(b=this.Hc(),g==this.zl&&g==this.sm?((0,D.Ce)(this.Qc,D.t),(0,D.De)(this.Qc,D.t)):b<=g&&g==this.sm?((0,D.Ce)(this.Qc,D.t),(0,D.De)(this.Qc,D.n)):b>=g&&g==this.zl?((0,D.Ce)(this.Qc,D.n),(0,D.De)(this.Qc,D.t)):((0,D.Ce)(this.Qc,D.n),(0,D.De)(this.Qc,D.n)));if(window.Math.round(1E5*f)!=window.Math.round(1E5*g)){var h=g/f;b=D.q;e&&(b=(0,D.ue)(e,this.$,this.$.ma))&&
(b=b.clone());b||(b=this.$.ma().clone());b.scale(h,h,c,d);var j=(0,D.we)(this,b.Ab)-b.Ab,m=(0,D.xe)(this,b.wb)-b.wb;(0,D.Ee)(this,"adjustPanConstraints",g,f,e,D.q,c,d,j,m);j=(0,D.we)(this,b.Ab)-b.Ab;m=(0,D.xe)(this,b.wb)-b.wb;b.translate(j,m);var o=this,h=function(){(0,D.Ee)(o,"zooming",g,f,e,D.q,c,d,j,m)},p=function(){(0,D.Ee)(o,"zoomed",o.Hc(),f,e,D.q,c,d,j,m)};e?((0,D.P)(e,"typeMatrix",this.$,this.$.ma,this.$.qa,b),(0,D.ze)(e,h),(0,D.$a)(e,p)):(h(),this.$.qa(b),p())}}};
D.Fe=function(b,c,d,e,f){b.wr&&(c/=b.Hc(f),b.QD(c,d,e,f))};D.ne.prototype.Sja=function(b,c){var d=this.Jj;this.Jj=D.n;var e=c;e||(e=this.$.D());var f=(e.x+e.g/2)*this.Hc(),e=(e.y+e.j/2)*this.Hc();(0,D.Ae)(this,this.tg/2-f,this.Hg/2-e,b);this.Jj=d};
D.ne.prototype.ao=function(b,c){if(this.Lca){var d=this.Jj,e=this.wr;this.wr=this.Jj=D.n;try{var f=c?c:this.$.D();if(f=(0,D.Ee)(this,"zoomToFitCalcBounds",D.q,D.q,b,f).bH){var g=window.Math.min((this.tg-2*this.hp)/f.g,(this.Hg-2*this.hp)/f.j),g=(0,D.Be)(this,g),h=this.tg/2-(f.x+f.g/2)*g,j=this.Hg/2-(f.y+f.j/2)*g,m=this,o=function(){(0,D.Ee)(m,"zoomToFitBegin",D.q,D.q,b,f)},p=function(){(0,D.Ee)(m,"zoomToFitEnd",D.q,D.q,b,f)};b?(0,D.ze)(b,o):o();(0,D.Fe)(this,g,0,0,b);(0,D.Ae)(this,h,j,b);b?(0,D.$a)(b,
p):p()}}finally{this.Jj=d,this.wr=e}}};D.ne.prototype.Gz=function(){var b=(0,D.Ic)(this,new D.K(0,0)),c=(0,D.Ic)(this,new D.K(this.tg,this.Hg)),b=this.$.Cb(b),c=this.$.Cb(c);return new D.M(b.x,b.y,c.x-b.x,c.y-b.y)};
D.Ie=function(b,c){if(b.KA=c)b.Go&&(b.Go.Ug()&&b.Go.stop(),b.Go=D.q);else{var d=(0,D.ve)(b,D.k).Ab,e=(0,D.ve)(b,D.k).wb,f=b.Hc();b.gQ=d!=(0,D.we)(b,d)||e!=(0,D.xe)(b,e);b.hQ=f!=(0,D.Be)(b,f);if(b.gQ||b.hQ)b.Go=new D.Ge(b.e,0.4),b.Go.Dj(D.He),b.hQ&&b.QD(1,0.5*b.tg,0.5*b.Hg,b.Go),b.gQ&&b.dk(0,0,b.Go),(0,D.$a)(b.Go,b.Jva,b),b.gQ&&(d=new D.ye("elasticAnimBegin",D.q,D.q,D.q,D.q,b.Go),b.Rb(d)),b.hQ&&(0,D.Ee)(b,"elasticAnimBegin",D.q,D.q,D.q,D.q,b.Go),b.Go.play()}};
D.ne.prototype.Jva=function(){this.Go=D.q;if(this.gQ){var b=new D.ye("elasticAnimEnd",D.k,D.k,D.k,D.k,D.k);this.Rb(b)}this.hQ&&(0,D.Ee)(this,"elasticAnimEnd")};D.we=function(b,c){var d=c;b.kq!=D.q&&d<b.kq&&(b.KA?(d=b.kq-d,d=b.kq-window.Math.sqrt(4*(0.01*b.tg)*d)):d=b.kq);b.iq!=D.q&&d>b.iq&&(b.KA?(d-=b.iq,d=b.iq+window.Math.sqrt(4*(0.01*b.tg)*d)):d=b.iq);return d};
D.xe=function(b,c){var d=c;b.lq!=D.q&&d<b.lq&&(b.KA?(d=b.lq-d,d=b.lq-window.Math.sqrt(4*(0.01*b.Hg)*d)):d=b.lq);b.jq!=D.q&&d>b.jq&&(b.KA?(d-=b.jq,d=b.jq+window.Math.sqrt(4*(0.01*b.Hg)*d)):d=b.jq);return d};D.Be=function(b,c){var d=window.Math.max(0,c);b.zl&&d<b.zl&&(b.KA?(d=b.zl-d,d=b.zl-window.Math.sqrt(4*(0.002*(b.sm-b.zl))*d)):d=b.zl);b.sm&&d>b.sm&&(b.KA?(d-=b.sm,d=b.sm+window.Math.sqrt(4*(0.002*(b.sm-b.zl))*d)):d=b.sm);return d};
D.ne.prototype.Pm=function(){var b=this.Qc;b&&(this.k(b),(0,D.re)(this),b.Pm())};D.re=function(b){var c=b.J.vs(),d=(0,D.Je)(c,"paddingSide",0),e=(0,D.Je)(c,"paddingTop",0),c=(0,D.Je)(c,"openCloseButtonWidth",0),d=(0,D.ya)(b.e)?b.tg-c-d:d;(0,D.wa)(b.Qc,d,e)};D.Ke=function(b,c){return(0,D.Fa)(b.e,c.pageX,c.pageY)};D.Ee=function(b,c,d,e,f,g,h,j,m,o){c=new D.Le(c,d,e,f,g,new D.K(h,j),m,o);b.Rb(c);return c};D.ne.prototype.KW=function(){(0,D.Ee)(this,"zoomAndCenter")};
D.Me=function(b,c){var d;d=c+b.OM;d>b.sm&&(d=b.sm);return d};D.Ne=function(b,c){var d;d=c-b.OM;d<b.zl&&(d=b.zl);return d};D.ne.prototype.Js=(0,D.A)("zl");D.ne.prototype.Nu=function(b){0>b&&(b=1);this.sm=b};D.ne.prototype.Wn=(0,D.A)("it");D.ne.prototype.Qa=(0,D.C)("it");
D.pe=function(b,c,d){this.Init(b,c,d)};D.F.o(D.pe,D.Uc,"DvtPanZoomCanvasEventManager");D.D=D.pe.prototype;D.D.Init=function(b,c,d){D.pe.u.Init.call(this,b,c,d);this.Mb=d;this.js=D.q;this.vr=this.ME=D.t;this.qQ=D.n};D.D.nf=function(b){D.pe.u.nf.call(this,b);(0,D.Bb)()?b.U("DOMMouseScroll",this.qA,D.t,this):b.U(D.Re,this.qA,D.t,this)};
D.D.il=function(b){2!=b.button&&(b=(0,D.Ke)(this.ka,b),this.Pt=b.x,this.Qt=b.y,this.oG=this.Pt,this.bz=this.Qt,this.c_=D.n,this.$S=(0,D.ve)(this.ka,D.k).Ab,this.aT=(0,D.ve)(this.ka,D.k).wb,this.bT=this.ka.Hc(),this.qQ&&(this.Qp=(new window.Date).getTime()));this.gj&&this.gj.Ug()&&(this.gj.stop(),this.gj.reset())};
D.D.Ep=function(b){if(this.c_){var c=(0,D.Ke)(this.ka,b),d=c.x,c=c.y;b.ctrlKey?(this.vr||(this.fb.call(this.ka,new D.Le("dragZoomBegin")),this.vr=D.n,this.Mb.Qc&&(0,D.Se)(this.Mb.Qc),(0,D.Ie)(this.ka,D.n)),b=this.bT*window.Math.pow(1+0.01*(this.bz>=c?1:-1),window.Math.abs(this.bz-c)),this.ka.Jj?(0,D.Fe)(this.ka,b,this.oG,this.bz):(0,D.Fe)(this.ka,b,D.q,D.q)):(0,D.Te)(this,d,c);this.Pt=d;this.Qt=c}};D.D.Zm=function(){this.c_=D.t;this.ME&&(0,D.Ue)(this);this.vr&&(0,D.Ve)(this)};
D.D.ik=function(b){if(this.c_&&(this.ME||this.vr))(!b.relatedTarget||b.relatedTarget==D.q)&&this.Zm(b);D.pe.u.ik.call(this,b)};
D.D.qA=function(b){if(b.wheelDelta&&0!==b.wheelDelta){var c=this.ka.Hc();this.js&&(c=this.js,this.js.stop(),c=this.ka.Hc(c),this.js=D.q);this.js=D.q;var d=b.wheelDelta;(0,D.Bb)()&&(d=-d);c*=1+this.ka.OM*d/window.Math.abs(d);d=(0,D.Ke)(this.ka,b);this.e.sz().aBa(b);this.ka.Jj?(0,D.Fe)(this.ka,c,d.x,d.y,this.js):(0,D.Fe)(this.ka,c,D.q,D.q,this.js);this.js&&((0,D.$a)(this.js,this.Kua,this),this.js.play())}};D.D.Kua=function(){this.js=D.q};D.D.Nwa=(0,D.v)();
D.D.Owa=function(){var b=1-0.04*this.B2,b=b*b,c=this.gj.bV(),d=b*this.Wxa*c,b=b*this.Xxa*c;this.z2+=d;this.A2+=b;var c=this.$S+this.Pt-this.oG+this.z2,e=this.aT+this.Qt-this.bz+this.A2;(0,D.Ae)(this.ka,c,e);var f=D.t;if(24<=this.B2)f=D.n;else{var g=(0,D.ve)(this.ka,D.k).Ab,h=(0,D.ve)(this.ka,D.k).wb;if(window.Math.abs(g-c)>window.Math.abs(d)||window.Math.abs(h-e)>window.Math.abs(b))f=D.n}f?(this.gj.stop(),this.gj.reset(),(0,D.Ie)(this.ka,D.t)):this.B2++};
D.D.bE=function(b){this.ka.wr&&(0,D.We)(b,this.era,this);this.ka.Jj&&(0,D.We)(b,this.xqa,this)};D.D.WO=function(b){this.ka.wr&&(0,D.Xe)(this.Pb,b,"zoomTouch");this.ka.Jj&&(0,D.Xe)(this.Pb,b,"panTouch");b&&b.preventDefault()};D.D.VO=function(b){this.ka.wr&&(0,D.Ye)(this.Pb,b,"zoomTouch");this.ka.Jj&&(0,D.Ye)(this.Pb,b,"panTouch")};
D.D.era=function(b,c){var d=(0,D.Ze)(this.Pb,"zoomTouch");1>=d.length&&((0,D.$e)(this.Pb,c.identifier,"zoomTouch",D.q,"zoomTouch","zoomTouch",this.dra,this.cra,this),this.Pt=c.pageX,this.Qt=c.pageY,this.oG=this.Pt,this.bz=this.Qt,this.$S=(0,D.ve)(this.ka,D.k).Ab,this.aT=(0,D.ve)(this.ka,D.k).wb,this.bT=this.ka.Hc(),this.ZS=D.q,d=(0,D.Ze)(this.Pb,"zoomTouch"),d=(0,D.af)(this.Pb,d),this.ka.l0=d);this.gj&&this.gj.Ug()&&(this.gj.stop(),this.gj.reset())};
D.D.dra=function(){var b=(0,D.Ze)(this.Pb,"zoomTouch");if(2==b.length){var c;var d=this.Pb;if(2==b.length)if(c=d.rh[b[0]],d=d.rh[b[1]],c==D.q||d==D.q||0==c.rka&&0==d.ska)c=D.q;else{var e=c.pageX-d.pageX,f=c.pageY-d.pageY,e=window.Math.sqrt(e*e+f*f),f=c.c8-d.c8,g=c.d8-d.d8,h=(c.pageX+d.pageX)/2,j=(c.pageY+d.pageY)/2;c={TBa:e-window.Math.sqrt(f*f+g*g),DU:h,mH:j,BBa:h-(c.c8+d.c8)/2,CBa:j-(c.d8+d.d8)/2,pka:e}}else c=D.q;c&&(this.vr||(this.vr=D.n,this.Pb.pu(),this.fb.call(this.ka,new D.Le("dragZoomBegin")),
this.Mb.Qc&&(0,D.Se)(this.Mb.Qc)),(0,D.Ie)(this.ka,D.n),this.ZS==D.q&&(this.ZS=c.pka-c.TBa),d=this.bT*(c.pka/this.ZS),e=(0,D.Fa)(this.Mb.e,c.DU,c.mH),this.sc(),b=(0,D.af)(this.Pb,b),this.ka.l0=b,(0,D.Fe)(this.ka,d,e.x,e.y),this.ka.dk(c.BBa,c.CBa))}};D.D.cra=function(){this.vr&&(this.ZS=D.q,this.Pb.t_=D.t,(0,D.Ve)(this));var b=(0,D.Ze)(this.Pb,"zoomTouch"),c=(0,D.af)(this.Pb,b);this.ka.l0=c;0==b.length&&this.fb.call(this.ka,new D.Le("zoomEnd"))};
D.D.xqa=function(b,c){!this.vr&&1>=(0,D.Ze)(this.Pb,"panTouch").length&&((0,D.$e)(this.Pb,c.identifier,"panTouch",D.q,"panTouch","panTouch",this.wqa,this.vqa,this),this.Pt=c.pageX,this.Qt=c.pageY,this.oG=this.Pt,this.bz=this.Qt,this.$S=(0,D.ve)(this.ka,D.k).Ab,this.aT=(0,D.ve)(this.ka,D.k).wb,this.bT=this.ka.Hc(),this.qQ&&(this.Qp=(new window.Date).getTime()));this.gj&&this.gj.Ug()&&(this.gj.stop(),this.gj.reset())};
D.D.wqa=function(b,c){if(!this.vr&&1==(0,D.Ze)(this.Pb,"panTouch").length){var d=c.pageX,e=c.pageY;(0,D.Te)(this,d,e);this.Pt=d;this.Qt=e}};D.D.vqa=function(){!this.vr&&this.ME&&(0,D.Ue)(this)};D.Ve=function(b){b.fb.call(b.ka,new D.Le("dragZoomEnd"));b.vr=D.t;b.Mb.Qc&&(0,D.bf)(b.Mb.Qc);(0,D.Ie)(b.ka,D.t)};
D.Te=function(b,c,d){b.ME||(b.fb.call(b.ka,new D.ye("dragPanBegin")),b.ME=D.n,b.Mb.Qc&&(0,D.Se)(b.Mb.Qc),(0,D.Ie)(b.ka,D.n),b.qQ&&(b.GA=[]));(0,D.Ae)(b.ka,b.$S+c-b.oG,b.aT+d-b.bz);b.qQ&&(b.yxa=b.Qp,b.Qp=(new window.Date).getTime(),b.Zv?(b.Zv.Ug()&&b.Zv.stop(),b.Zv.reset()):b.Zv=new D.cf(b.e,50,b.Nwa,b,1),b.GA.push({LBa:b.Qp-b.yxa,rka:c-b.Pt,ska:d-b.Qt}),5<b.GA.length&&b.GA.splice(0,1),b.Zv.start())};
D.Ue=function(b){b.fb.call(b.ka,new D.ye("dragPanEnd"));b.ME=D.t;b.Mb.Qc&&(0,D.bf)(b.Mb.Qc);if(b.Zv&&b.Zv.Ug()){b.Zv.stop();b.Zv.reset();b.gj?b.gj.reset():b.gj=new D.cf(b.e,50,b.Owa,b);for(var c=0,d=0,e=0,f=b.GA.length;0<b.GA.length;)var g=b.GA.pop(),c=c+g.LBa,d=d+g.rka,e=e+g.ska;b.GA=D.q;b.Wxa=d/c;b.Xxa=e/c;b.gj.setInterval(window.Math.ceil(c/f));b.B2=1;b.z2=0;b.A2=0;b.Mb.Jj&&b.gj.start()}else(0,D.Ie)(b.ka,D.t)};
D.df=function(b,c){this.Init(b,c)};D.F.o(D.df,D.Ec,"DvtPanZoomCanvasKeyboardHandler");D.df.prototype.Init=function(b,c){D.df.u.Init(c);this.Sua=b};
D.df.prototype.Vn=function(b){var c=b.keyCode,d=this.Sua.ca;if(33==c)b.ctrlKey||b.shiftKey?d.dk(d.iT,0):d.dk(0,d.iT);else if(34==c)b.ctrlKey||b.shiftKey?d.dk(-d.iT,0):d.dk(0,-d.iT);else if(191==c)(b=d.Qc)&&b.sO();else if((0,D.ef)(b)||(0,D.ff)(b))(0,D.Fe)(d,d.Hc()+d.OM);else if((0,D.jf)(b)||(0,D.kf)(b))(0,D.Fe)(d,d.Hc()-d.OM);else if((48==c||96==c)&&!b.ctrlKey&&!b.shiftKey)d.ao();else return D.df.u.Vn.call(this,b)};
D.wl=function(b,c,d,e,f,g,h,j){this.Init(b,c,d,e,f,g,h,j)};D.F.o(D.wl,D.G,"DvtCollapsiblePanel");
D.wl.prototype.Init=function(b,c,d,e,f,g,h,j){D.wl.u.Init.call(this,b);this.og=c;this.wc=d;this.Bi=e?e:"col_northeast";(0,D.ya)(this.e)&&("col_northeast"==this.Bi?this.Bi="col_northwest":"col_northwest"==this.Bi?this.Bi="col_northeast":"col_southeast"==this.Bi?this.Bi="col_southwest":"col_southwest"==this.Bi&&(this.Bi="col_southeast"));this.sl=f;this.Sv=j?j:(0,D.sy)();this.nb=this.UA=this.jB=D.q;this.F=g;this.Lp=(0,D.Je)(this.F,"border-color",D.q);this.Eh=(0,window.parseInt)((0,D.Je)(this.F,"border-radius",
D.q));this.qv=(0,D.Je)(this.F,"background-color",D.q);this.Kj=(0,D.Je)(this.F,"backgroundAlpha",1);this.KQ=h!==D.k?!h:D.t;this.Rc=new D.nd(b,0,0,c-10,d-10,3,"collapsiblePanel");this.k(this.Rc);this.Rc.XK=D.t;(0,D.wa)(this.Rc,5,5);this.U(D.So,this.ZO,D.t,this);this.U(D.To,this.cE,D.t,this)};
D.wl.prototype.RX=function(){this.Rc.refresh();var b=this.Rc.D(),c=b.g+10,b=b.j+10;this.eb.ek((0,D.bE)(this,c,b));var d="col_northwest"==this.Bi||"col_southwest"==this.Bi;this.ig&&d&&this.ig.G(c);this.Rb(new D.Lm(c,b,0,0))};D.wl.prototype.isCollapsed=(0,D.C)("KQ");D.xl=function(b,c){b.KQ!=c&&(b.KQ=c,(0,D.cE)(b,D.n),b.Rb(new D.dE(c?"hide":"show")))};D.wl.prototype.F6=function(){return this.og-27};D.wl.prototype.E6=function(){return this.wc-27};
D.eE=function(b,c,d){return!b.isCollapsed()?d?new D.K(1/c.x,1/c.y):new D.K(-c.x,-c.y):c};
D.cE=function(b,c){b.nb&&(b.BJ=D.n,b.nb.stop(D.n));var d="col_northwest"==b.Bi||"col_northeast"==b.Bi,e="col_northwest"==b.Bi||"col_southwest"==b.Bi,f=e?0:b.R,g=d?0:b.Y,h=new D.K(1/b.R,1/b.Y),f=new D.K(f,g),d=new D.K(e?-b.R:b.R,g-(d?0:25));c||(b.eb.C(0),b.ig&&b.ig.C(0));h=new D.rq(b.e,b.eb,(0,D.eE)(b,h,D.n),c?0.25:1E-5);d=new D.sq(b.e,b.ig,(0,D.eE)(b,d),c?0.25:1E-5);f=new D.sq(b.e,b.eb,(0,D.eE)(b,f),c?0.25:1E-5);b.nb=new D.Cn(b.e,h,d,f);b.nb&&(b.e.Kd().sc(),b.Ra(D.So,b.ZO,D.t,b),b.Ra(D.To,b.cE,D.t,
b),b.Mj&&(b.Mj.Ra(D.Jt.Xd,b.hE,D.t,b),b.Mj.Ra(D.Ib,b.hE,D.t,b),b.Mj.Ra(D.So,b.pY,D.t,b),b.Mj.Ra(D.To,b.oY,D.t,b)),b.isCollapsed()&&b.Rc.C(0),b.nb.qd(b.Dp,b),b.nb.play())};
D.bE=function(b,c,d){var e=b.Eh,f,g="col_northwest"==b.Bi||"col_southwest"==b.Bi;25>=d&&(d=25);f=b.Sv||g?window.DvtPathUtils.moveTo(e,0):window.DvtPathUtils.moveTo(0,0);f+=window.DvtPathUtils.lineTo(c-e,0);!b.Sv&&g?(f+=window.DvtPathUtils.lineTo(c,0),f+=window.DvtPathUtils.lineTo(c,e)):f+=window.DvtPathUtils.Zb(c,0,c,e);!b.Sv&&25==d&&g?f+=window.DvtPathUtils.lineTo(c,d):(f+=window.DvtPathUtils.lineTo(c,d-e),f+=window.DvtPathUtils.Zb(c,d,c-e,d));f+=window.DvtPathUtils.lineTo(e,d);f=!b.Sv&&25==d&&!g?
f+window.DvtPathUtils.lineTo(0,d):f+window.DvtPathUtils.Zb(0,d,0,d-e);if(b.Sv||g)f+=window.DvtPathUtils.lineTo(0,e),f+=window.DvtPathUtils.Zb(0,0,e,0);return f+=window.DvtPathUtils.closePath()};D.D=D.wl.prototype;
D.D.Dp=function(){this.BJ=D.t;this.nb=D.q;var b=this.eb.mc().clone();b.C(this.F.borderAlpha);this.eb.Z(b);var b=this.F[D.je.eHa],c=this.eb.Gc().clone();c.C(b);this.eb.H(c);this.ig&&this.ig.C(this.F.borderAlpha);this.isCollapsed()||this.Rc.C(1);this.U(D.So,this.ZO,D.t,this);this.U(D.To,this.cE,D.t,this);this.Mj&&(this.Mj=this.isCollapsed()?D.W.BU(this.e,this.sl,25,this.F,D.t):D.W.zU(this.e,this.sl,25,this.F,D.t),this.ig.k(this.Mj),this.ig.pp(0),(0,D.Vb)()?this.Mj.U(D.Jt.Xd,this.hE,D.t,this):(this.Mj.U(D.Ib,
this.hE,D.t,this),this.Mj.U(D.So,this.pY,D.t,this),this.Mj.U(D.To,this.oY,D.t,this)))};D.D.hE=function(){this.e.Kd().sc();(0,D.xl)(this,!this.isCollapsed())};D.D.pY=function(b){var c=this.isCollapsed()?this.jB:this.UA;c!=D.q&&this.e.Kd().qO(b.pageX,b.pageY,c,this.Mj,D.n)};D.D.oY=function(){this.e.Kd().sc()};D.D.ZO=function(){var b=this.eb.mc().clone();b.C(this.F.borderHoverAlpha);this.eb.Z(b);var b=this.F.backgroundHoverAlpha,c=this.eb.Gc().clone();c.C(b);this.eb.H(c);this.ig&&this.ig.C(this.F.borderHoverAlpha)};
D.D.cE=function(){var b=this.eb.mc().clone();b.C(this.F.borderAlpha);this.eb.Z(b);b=this.eb.Gc().clone();b.C(this.Kj);this.eb.H(b);this.ig&&this.ig.C(this.F.borderAlpha)};
D.dE=function(b){this.Init("dvtCollapsiblePanelEvent");this.Fl=b};D.F.o(D.dE,D.oc,"DvtCollapsiblePanelEvent");D.dE.prototype.Mi=(0,D.C)("Fl");
D.vw={};D.F.o(D.vw,D.F,"DvtImageLAFUtils");D.vw.XH=function(b,c){var d=new D.Wb(b,c);d.ja(D.t);D.ol.zj(b,c,function(b){b!=D.q&&(b.width&&b.height)&&(d.ia(b.width),d.ta(b.height))});return d};
D.W={};D.F.o(D.W,D.F,"DvtButtonLAFUtils");D.W.kHa=-6;D.W.w9=23;D.W.v9=21;D.W.LHa=20;D.W.AHa=22;D.W.zHa=20;D.W.nba=47;D.W.mba=26;D.W.Gd=window.Math.sin(window.Math.PI/4);D.W.Hd=window.Math.tan(window.Math.PI/8);D.W.yO="#7C8191";D.W.g$="#E0E1E1";D.W.h$="#F0F1F2";D.W.JY=8;D.W.Joa="solid";D.W.Goa="#7BA0D9";D.W.mX="#3474D3";D.W.G9="#BFD8FB";D.W.Xsa="zoominUp";D.W.Ysa="zoominOver";D.W.Wsa="zoominDown";D.W.Vsa="zoominDisabled";D.W.dta="zoomtofitUp";D.W.eta="zoomtofitOver";D.W.cta="zoomtofitDown";
D.W.ata="zoomoutUp";D.W.bta="zoomoutOver";D.W.$sa="zoomoutDown";D.W.Zsa="zoomoutDisabled";D.W.rsa="pandialUp";D.W.ssa="pandialOver";D.W.qsa="pandialDown";D.W.zsa="recenterUp";D.W.Asa="recenterOver";D.W.ysa="recenterDown";D.W.Tba="resetUp";D.W.Csa="resetOver";D.W.Bsa="resetDown";D.W.Gba="drillupUp";D.W.Nra="drillupOver";D.W.Mra="drillupDown";D.W.Fba="drilldownUp";D.W.Lra="drilldownOver";D.W.Kra="drilldownDown";D.W.THa="maxUp";D.W.UHa="maxOver";D.W.SHa="maxDown";D.W.WHa="restoreUp";D.W.XHa="restoreOver";
D.W.VHa="restoreDown";D.W.wra="collapseEna";D.W.xra="collapseOvr";D.W.vra="collapseDwn";D.W.Qra="expandEna";D.W.Rra="expandOvr";D.W.Pra="expandDwn";D.W.usa="quickQueryEna";D.W.vsa="quickQueryOvr";D.W.tsa="quickQueryDwn";D.W.tra="clearResultsEna";D.W.ura="clearResultsOvr";D.W.sra="clearResultsDwn";D.W.Tsa="Up";D.W.psa="Over";D.W.Jra="Down";D.W.Esa="Sel";D.W.wsa="_r";D.W.Osa="synchronize";
D.W.nBa=function(b,c,d,e,f,g){var h=D.W.g0(b,f[D.W.rsa],g),j=new D.G(b);(0,D.wa)(j,20,20);var m=D.W.g0(b,f[D.W.qsa],g);(0,D.wa)(m,-20,-20);j.k(m);m=new D.G(b);(0,D.wa)(m,20,20);var o=D.W.g0(b,f[D.W.ssa],g);(0,D.wa)(o,-20,-20);m.k(o);h=new D.Yb(b,h,m,j);if(0<(e&16)){var p=new D.Yb(b,D.W.i0(b,f[D.W.zsa],g),D.W.i0(b,f[D.W.Asa],g),D.W.i0(b,f[D.W.ysa],g));(0,D.wa)(p,9,9)}return new D.YD(b,h,p,c,d,e,g)};
D.W.iBa=function(b,c,d,e,f,g,h){var j=D.W.jg(b,0,f[D.W.Gba],h),m=D.W.jg(b,1,f[D.W.Nra],h),o=D.W.jg(b,2,f[D.W.Mra],h);f=D.W.jg(b,0,f[D.W.Gba],h);return new D.Wv(b,new D.Yb(b,j,m,o,f),c,d,0,e,g)};D.W.hBa=function(b,c,d,e,f,g,h){var j=D.W.jg(b,0,f[D.W.Fba],h),m=D.W.jg(b,1,f[D.W.Lra],h),o=D.W.jg(b,2,f[D.W.Kra],h);f=D.W.jg(b,0,f[D.W.Fba],h);return new D.Wv(b,new D.Yb(b,j,m,o,f),c,d,1,e,g)};
D.W.tBa=function(b,c,d,e,f,g,h){var j=D.W.jg(b,0,f[D.W.Tba],h),m=D.W.jg(b,1,f[D.W.Csa],h),o=D.W.jg(b,2,f[D.W.Bsa],h);f=D.W.jg(b,0,f[D.W.Tba],h);return new D.Wv(b,new D.Yb(b,j,m,o,f),c,d,2,e,g)};D.W.zBa=function(b,c,d,e,f,g){var h=D.W.jg(b,0,f[D.W.dta],g),j=D.W.jg(b,1,f[D.W.eta],g);f=D.W.jg(b,2,f[D.W.cta],g);return new D.ZD(b,new D.Yb(b,h,j,f),c,d,e)};
D.W.xBa=function(b,c,d,e,f,g){var h=D.W.jg(b,0,f[D.W.Xsa],g),j=D.W.jg(b,1,f[D.W.Ysa],g),m=D.W.jg(b,2,f[D.W.Wsa],g);f=D.W.jg(b,3,f[D.W.Vsa],g);return new D.$D(b,new D.Yb(b,h,j,m,f),c,d,e)};D.W.yBa=function(b,c,d,e,f,g){var h=D.W.jg(b,0,f[D.W.ata],g),j=D.W.jg(b,1,f[D.W.bta],g),m=D.W.jg(b,2,f[D.W.$sa],g);f=D.W.jg(b,3,f[D.W.Zsa],g);return new D.aE(b,new D.Yb(b,h,j,m,f),c,d,e)};
D.W.jBa=function(b,c,d,e,f){var g=(0,D.Je)(f,"buttonRadius",0),h=(0,D.Je)(f,"buttonWidth",0),j=(0,D.Je)(f,"buttonWidth",0),m=D.W.c0(b,g,h,j,f);D.W.f4(d,m,h,j+2*g,f,D.n);c=D.W.f1(b,d,c);(b=D.W.rga(b,e[c],h,j))&&m.k(b);return m};D.W.f1=function(b,c,d,e){var f="";0==c?c=D.W.Tsa:1==c?c=D.W.psa:2==c&&(c=D.W.Jra);e&&(d+=D.W.Esa,(0,D.ya)(b)&&(f=D.W.wsa));return d+(c+f)};D.W.C5=function(b,c,d,e){var f=D.W.f1(b,c,D.W.Osa,D.n);return D.W.jg(b,c,e[f],d)};
D.W.oBa=function(b,c,d,e,f){var g=(0,D.Je)(f,"buttonRadius",0);b=D.W.c0(b,g,d,e,f);D.W.f4(c,b,d,e+2*g,f,D.n);return b};D.W.gBa=function(b,c,d,e,f){c=D.W.f1(b,d,c);return D.W.jg(b,d,e[c],f)};D.W.BU=function(b,c,d,e,f){var g=D.W.WE(b,0,d,c[D.W.Qra],e,f),h=D.W.WE(b,1,d,c[D.W.Rra],e,f);c=D.W.WE(b,2,d,c[D.W.Pra],e,f);return new D.Yb(b,g,h,c)};D.W.zU=function(b,c,d,e,f){var g=D.W.WE(b,0,d,c[D.W.wra],e,f),h=D.W.WE(b,1,d,c[D.W.xra],e,f);c=D.W.WE(b,2,d,c[D.W.vra],e,f);return new D.Yb(b,g,h,c)};
D.W.rBa=function(b,c){var d=D.W.XE(b,c[D.W.usa]),e=D.W.XE(b,c[D.W.vsa]),f=D.W.XE(b,c[D.W.tsa]);return new D.Yb(b,d,e,f)};D.W.fBa=function(b,c){var d=D.W.XE(b,c[D.W.tra]),e=D.W.XE(b,c[D.W.ura]),f=D.W.XE(b,c[D.W.sra]);return new D.Yb(b,d,e,f)};D.W.jg=function(b,c,d,e){var f,g,h=(0,D.Je)(e,"buttonRadius",0);if("undefined"===f||f==D.q)f=(0,D.Je)(e,"buttonWidth",0);if("undefined"===g||g==D.q)g=(0,D.Je)(e,"buttonWidth",0);c=D.W.zva(b,c,h,f,g,e);(b=D.W.rga(b,d,f,g))&&c.k(b);return c};
D.W.rga=function(b,c,d,e){var f=new D.Wb(b,c);f.ja(D.t);D.ol.zj(b,c,function(b){b!=D.q&&(b.width&&b.height)&&(f.ia(b.width),f.ta(b.height),(0,D.wa)(f,d/2-b.width/2,e/2-b.height/2))});return f};D.W.g0=function(b,c,d){var e=new D.G(b),f=new D.Yf(b,20,20,20);f.C(0);f.na((0,D.Je)(d,"background-color",D.q));e.k(f);(b=D.vw.XH(b,c))&&e.k(b);return e};D.W.i0=function(b,c,d){var e=new D.G(b),f=new D.Yf(b,11,11,8);f.C(0);f.na((0,D.Je)(d,"background-color",D.q));e.k(f);(b=D.vw.XH(b,c))&&e.k(b);return e};
D.W.WE=function(b,c,d,e,f,g){d||(d=47);c=D.W.Cva(b,c,d,f,g);if(b=D.vw.XH(b,e))e=(0,D.Je)(f,"imageWidth",0),g=(0,D.Je)(f,"imageHeight",0),c.k(b),(0,D.wa)(b,((0,D.Je)(f,"openCloseButtonWidth",0)-e)/2,(d-g)/2);return c};D.W.XE=function(b,c){var d=D.vw.XH(b,c);d.ja(D.n);return d};
D.W.mBa=function(b,c){var d=D.W.$da(b),e=(0,D.Je)(c,"background-color",D.q),f=(0,D.Je)(c,"border-color",D.q);"solid"==(0,D.Je)(c,"fill-type",D.q)?(d.La(f),d.na(e)):(d.Z(new D.Eq(36,["#8D93A5","#E0EAEB",f],[1,1,1],[0,125/255,1],[0,0,40,40],1)),d.H(new D.Gd(90,[e,e,"#5A83BE",e],[0.9,0.1,0,0.7],[0,105/255,150/255,1],[0,0,40,40])));return d};D.W.gka=function(b,c){var d=D.W.$da(b),e=(0,D.Je)(c,"background-color",D.q);d.La(e);d.na(e);return d};
D.W.$da=function(b){var c=window.DvtPathUtils.moveTo(40,20)+window.DvtPathUtils.Zb(40,20*D.W.Hd+20,20*D.W.Gd+20,20*D.W.Gd+20)+window.DvtPathUtils.Zb(20*D.W.Hd+20,40,20,40)+window.DvtPathUtils.Zb(20*-D.W.Hd+20,40,20*-D.W.Gd+20,20*D.W.Gd+20)+window.DvtPathUtils.Zb(0,20*D.W.Hd+20,0,20)+window.DvtPathUtils.Zb(0,20*-D.W.Hd+20,20*-D.W.Gd+20,20*-D.W.Gd+20)+window.DvtPathUtils.Zb(20*-D.W.Hd+20,0,20,0)+window.DvtPathUtils.Zb(20*D.W.Hd+20,0,20*D.W.Gd+20,20*-D.W.Gd+20)+window.DvtPathUtils.Zb(40,20*-D.W.Hd+20,
40,20)+window.DvtPathUtils.closePath();return new D.Ra(b,c,"draw_pan_button")};D.W.OT=function(b,c,d,e,f){b.La("#FFFFFF");b.Z(new D.Eq(63,["#8D93A5","#E0EAEB","#FFFFFF"],[1,1,1],[0,155/255,1],[e,f,c,d],1))};
D.W.f4=function(b,c,d,e,f,g){if((0,D.Je)(f,"panelDrawerStyles",D.q))!g||g&&0==b?(0,D.Xb)(c):(1==b||2==b)&&c.H(new D.Nf("#EBECED"));else if("skyros"==f.skin)switch(b){case 1:c.H(new D.Nf("#FFFFFF",0.7));c.Z(new D.Hb((0,D.Je)(f,"border-color",D.q)));break;case 2:c.H(new D.Nf("#B3C6DB"));c.Z(new D.Hb((0,D.Je)(f,"border-color",D.q)));break;default:(0,D.Xb)(c)}else{var h,j,m;switch(b){case 3:case 0:h=["#5B868A","#FFFFFF","#FFFFFF","#5B868A"];j=[0.01,0,0.05,0.01];m=[0,120/255,130/255,1];break;case 1:D.W.OT(c,
d,e,0,0);h=["#FFFFFF","#4671B0","#4671B0","#FFFFFF"];j=[0.5,0.2,0.1,0.7];m=[0,120/255,130/255,1];break;case 2:D.W.OT(c,d,e,0,0),h=["#E0EAEB","#5B868A","#4671B0"],j=[0.1,0.3,0.6],m=[0,130/255,1]}c.H(new D.Gd(90,h,j,m,[0,0,d,e]))}};
D.W.Qza=function(b,c,d,e,f){if((0,D.Je)(f,"panelDrawerStyles",D.q))(0,D.Xb)(c);else{var g;g=(0,D.Je)(f,"border-color",D.q);if("solid"==(0,D.Je)(f,"fill-type",D.q)){d=(0,D.Je)(f,"background-color",D.q);switch(b){case 0:window.bgAlpha=(0,D.Je)(f,"backgroundAlpha",1);window.strokeAlpha=(0,D.Je)(f,"borderAlpha",1);break;case 2:case 1:window.bgAlpha=(0,D.Je)(f,"backgroundHoverAlpha",1),window.strokeAlpha=(0,D.Je)(f,"borderHoverAlpha",1)}b=new D.Nf(d,window.bgAlpha);g=new D.Hb(g,window.strokeAlpha)}else{var h,
j,m;switch(b){case 0:h=["#FFFFFF","#5B868A","#5B868A"];j=[0,0.2,0.3];m=[0,130/255,1];break;case 1:h=["#FFFFFF","#FFFFFF","#4671B0","#4671B0"];j=[0.1,0.2,0.1,0.6];m=[0,120/255,130/255,1];break;case 2:h=["#4671B0","#5B868A","#5B868A"],j=[0.5,0.2,0.4],m=[0,130/255,1]}b=new D.Gd(0,h,j,m,[0,0,d,e]);g=new D.Hb(g,1,0.8)}c.Z(g);c.H(b)}};
D.W.qJa=function(b,c,d,e,f,g){var h,j,m;switch(b){case 0:c.La("#FFFFFF",1,0.25);h=["#FFFFFF","#4671B0","#E0EAEB","#FFFFFF"];j=[0.6,0.3,0.3,0.8];m=[0,125/255,130/255,1];break;case 1:D.W.OT(c,d,e,f,g);h=["#4671B0","#FFFFFF","#FFFFFF","#FFFFFF"];j=[0.4,0.3,0.7,1];m=[0,70/255,200/255,1];break;case 2:D.W.OT(c,d,e,f,g),h=["#FFFFFF","#4671B0","#E0EAEB"],j=[0.6,0.5,0.8],m=[0,130/255,1]}c.H(new D.Gd(90,h,j,m,[f,g,d,e]))};
D.W.yX=function(b,c,d,e){return e?["M",b,0,"L",d,0,"A",d,d,0,0,0,0,d,"L",0,c-d,"A",d,d,0,0,0,d,c,"L",b,c]:["M",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c]};D.W.Cva=function(b,c,d,e,f){d||(d=47);var g=(0,window.parseInt)((0,D.Je)(e,"border-radius",0)),h=(0,D.Je)(e,"openCloseButtonWidth",0);d=window.Math.max(d,(0,D.Je)(e,"buttonHeight",d));b=new D.Ra(b,D.W.yX(h,d,g,f));D.W.Qza(c,b,h,d,e);return b};D.W.zva=function(b,c,d,e,f,g){b=D.W.c0(b,d,e,f,g);D.W.f4(c,b,e,f+2*d,g);return b};
D.W.c0=function(b,c,d,e,f){if("skyros"==f.skin)return new D.H(b,0,0,d,e);d-=2*c;e-=2*c;f=d+c;var g=e+c,h=window.DvtPathUtils.moveTo(f+c,g)+window.DvtPathUtils.Zb(c+f,D.W.Hd*c+g,D.W.Gd*c+f,D.W.Gd*c+g)+window.DvtPathUtils.Zb(D.W.Hd*c+f,c+g,f,c+g)+window.DvtPathUtils.lineTo(f,g+c)+window.DvtPathUtils.lineTo(f-d,c+g);f-=d;h+=window.DvtPathUtils.Zb(-D.W.Hd*c+f,c+g,-D.W.Gd*c+f,D.W.Gd*c+g)+window.DvtPathUtils.Zb(-c+f,D.W.Hd*c+g,-c+f,g)+window.DvtPathUtils.lineTo(f-c,g)+window.DvtPathUtils.lineTo(f-c,g-e);
g-=e;h+=window.DvtPathUtils.Zb(-c+f,-D.W.Hd*c+g,-D.W.Gd*c+f,-D.W.Gd*c+g)+window.DvtPathUtils.Zb(-D.W.Hd*c+f,-c+g,f,-c+g)+window.DvtPathUtils.lineTo(f,-c+g)+window.DvtPathUtils.lineTo(f+d,-c+g);f+=d;h+=window.DvtPathUtils.Zb(D.W.Hd*c+f,-c+g,D.W.Gd*c+f,-D.W.Gd*c+g)+window.DvtPathUtils.Zb(c+f,-D.W.Hd*c+g,c+f,g)+window.DvtPathUtils.lineTo(f+c,g+e)+window.DvtPathUtils.closePath();return new D.Ra(b,h)};
D.W.FBa=function(b,c,d,e){e=(0,D.Je)(e,"radius",0);c-=2*e;d-=e;var f=c+e,g=d,h=window.DvtPathUtils.moveTo(f+e,g)+window.DvtPathUtils.Zb(e+f,D.W.Hd*e+g,D.W.Gd*e+f,D.W.Gd*e+g)+window.DvtPathUtils.Zb(D.W.Hd*e+f,e+g,f,e+g)+window.DvtPathUtils.lineTo(f,e+g)+window.DvtPathUtils.lineTo(f-c,e+g),f=f-c,h=h+(window.DvtPathUtils.Zb(-D.W.Hd*e+f,e+g,-D.W.Gd*e+f,D.W.Gd*e+g)+window.DvtPathUtils.Zb(-e+f,D.W.Hd*e+g,-e+f,g)+window.DvtPathUtils.lineTo(-e+f,g)+window.DvtPathUtils.lineTo(-e+f,g-d)),g=g-d,h=h+(window.DvtPathUtils.lineTo(f+
c+e,g)+window.DvtPathUtils.lineTo(f+c+e,g+d)+window.DvtPathUtils.closePath());return new D.Ra(b,h)};D.W.RJa=function(b,c){var d=new window.DvtDropShadowFilter(7,45,"#5A83BE",0.9,14,14,1,3,D.t,D.t,D.t),e=[];e.push(d);c.filters=e};D.W.qm=function(b,c){c instanceof D.Yb&&(c=c.da(0));return(0,D.Lf)(b,c)};
D.W.Y7=function(b,c){var d=D.W.Joa,e=D.W.Goa,f=D.W.mX,g;c&&(c.A("fill-type")&&(d=c.A("fill-type")),c.A("border-color")&&(e=c.A("border-color")),c.A("background-color")&&(f=c.A("background-color")),c.A("background")&&(g=c.A("background")));var e=new D.Hb(e),h;if("solid"==d)h=new D.Nf(f);else{var j,m,o;if(g&&0<=g.indexOf("linear-gradient")){if(d=(0,D.Ed)(g))o=d.Uj(),h=d.ml,j=d.ll,m=d.jv}else h=f,j=D.W.G9,h!=D.W.mX&&(j=D.U.kp(D.W.mX,D.W.G9,h)),h=[h,j],j=[0.6,0.8],m=[0,1],o=-270;h=new D.Gd(o,h,j,m)}b.H(h);
b.Z(e)};
D.tE={};D.F.o(D.tE,D.F,"DvtCommonLegendDefaults");D.tE.SY={rowColGap:6,separatorGap:7,indicatorSize:16,buttonSize:12,dwn:"#0572CE",ovr:"#5D5D5D",ena:"#7E7F80",separatorColor:"#D9DFE3"};D.tE.TY={dwn:"#202F48",ovr:"#184DD8",ena:"#003D5B"};D.tE.fA={rowColGap:4,separatorGap:4,indicatorSize:11,buttonSize:11,dwn:"#000000",ovr:"#245EDD",ena:"#495D7C",separatorColor:"#ADB6C7"};D.tE.Pg=function(b){var c=D.tE.qB(b);return b?D.Ta.Bb(b,c):c};
D.tE.qB=function(b){var c=D.q;return c=b&&"skyros"===b.skin?D.Ta.Bb(D.tE.TY,D.tE.fA):b&&"alta"===b.skin?D.Ta.Bb(D.tE.SY,D.tE.fA):D.Ta.clone(D.tE.fA)};
D.DvtCommonLegend=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.DvtCommonLegend,D.G,"DvtCommonLegend");D.DvtCommonLegend.iaa="isLegendDisclosed";D.DvtCommonLegend.Lqa="skin";D.D=D.DvtCommonLegend.prototype;D.D.Init=function(b,c,d,e,f){D.DvtCommonLegend.u.Init.call(this,b,D.q,c,d);this.Jh=(0,D.ya)();this.R=this.tJa=c;this.Y=d;this.ZP={};this.n1={};this.IJ=[];this.yE=D.t;this.cu=[];this.Dza=this.nM=D.t;this.yF=[];this.ej=e;this.F=D.tE.Pg(f?{skin:f}:D.q);this.I1=D.t;this.Eg=new D.wc};D.D.AJ=(0,D.C)("Eg");
D.D.Kz=(0,D.C)("I1");D.D.HW=(0,D.A)("NF");D.D.F8=function(b){b&&(this.IB=b)};D.D.kb=(0,D.C)("GF");D.D.Ie=(0,D.A)("GF");
D.wE=function(b,c,d,e,f){var g=c.q("label"),g=new D.uE(b.e,b,g,b.a4,b.F);g.M(d,e,f);if(c=c.ib())for(var h=0;h<c.length;h++){var j=c[h],m;if("item"==j.getName()){m=b;var o={};o.itemId=j.q("itemId");o.attributeGroupId=j.q("attributeGroupId");o.hideAttrs=j.q("hideAttrs");m=new D.vE(m.e,m,o,m.kL,m.F);j=j.ib();for(o=0;o<j.length;o++)if("marker"==j[o].getName()){var p=m,r=j[o],u=r.q("url"),w=r.q("shapeType"),z=r.q("color"),B=r.q("pattern");(r=r.q("opacity"))&&(r=(0,window.parseFloat)(r));p.setMarker(u,
w,z,B,r)}else"text"==j[o].getName()&&m.Yg(j[o].q("value"))}else"text"==j.getName()&&(m=new D.vE(b.e,b,D.q,b.kL,b.F),m.Yg(j.q("value")));m&&(m.M(g,e,f),g.pj(m))}d.k(g);e.y=e.y-b.F.rowColGap+b.F.rowColGap;return g};
D.xE=function(b,c,d,e,f){var g=new D.uE(b.e,b,c.label,b.a4,b.F);g.M(d,e,f);var h=c.item,j;if(h)for(var m=0;m<h.length;m++){var o=b;j=h[m];var p={};p.itemId=j.itemId;p.attributeGroupId=j.attributeGroupId;p.hideAttrs=j.hideAttrs;var o=new D.vE(o.e,o,p,o.kL,o.F),r=j.marker,p=r.url,u=r.shapeType,w=r.color,z=r.pattern;(r=r.opacity)&&(r=(0,window.parseFloat)(r));o.setMarker(p,u,w,z,r);o.Yg(j.text.value);if(j=o)j.M(g,e,f),g.pj(j)}if(c=c.text)for(m=0;m<c.length;m++)j=new D.vE(b.e,b,D.q,b.kL,b.F),j.Yg(c[m].value),
j&&(j.M(g,e,f),g.pj(j));d.k(g);e.y=e.y-b.F.rowColGap+b.F.rowColGap;return g};D.zE=function(b,c,d,e,f){var g=c.q("label"),h="true"==c.q("disclosed"),j=c.q("expandTooltip"),m=c.q("collapseTooltip"),g=new D.yE(b.e,b,g,b.Y3,m,j,h,b.F);g.M(d,e,f);d=f?-1:1;if(c=c.ib())for(h=0;h<c.length;h++)j=c[h],"section"==j.getName()&&(e.x+=(b.F.buttonSize+b.F.rowColGap)*d,j=(0,D.wE)(b,j,g,e,f),e.x-=(b.F.buttonSize+b.F.rowColGap)*d,g.pj(j));e.y=e.y-b.F.rowColGap+b.F.rowColGap;return g};
D.AE=function(b,c,d,e,f){var g=new D.yE(b.e,b,c.label,b.Y3,c.collapseTooltip,c.expandTooltip,"true"==c.disclosed,b.F);g.M(d,e,f);d=f?-1:1;if(c=c.section)for(var h=0;h<c.length;h++){e.x+=(b.F.buttonSize+b.F.rowColGap)*d;var j=(0,D.xE)(b,c[h],g,e,f);e.x-=(b.F.buttonSize+b.F.rowColGap)*d;g.pj(j)}e.y=e.y-b.F.rowColGap+b.F.rowColGap;return g};
D.BE=function(b,c,d){d.y=d.y-b.F.rowColGap+b.F.separatorGap;var e=new D.Lp(b.e,d.x,d.y,d.x,d.y);(0,D.wb)(e);e.La(b.F.separatorColor);b.cu.push(e);var f;if("alta"==b.F.skin)f=e;else{d.y++;var g=new D.Lp(b.e,d.x,d.y,d.x,d.y);g.La("#FFFFFF");(0,D.wb)(g);f=new D.G(b.e);f.k(e);f.k(g);b.cu.push(g)}c.k(f);d.y+=b.F.separatorGap;return f};
D.DvtCommonLegend.prototype.update=function(b,c){for(var d=this.ce.indexOf(b),d=d+1;d<this.ce.length;){var e=this.ce[d].L();this.ce[d].P(e+c);d++}this.lc.j+=c;this.Rb(new D.Lm(this.lc.g,this.lc.j,0,0))};D.DvtCommonLegend.prototype.Nc=(0,D.C)("Ca");
D.DvtCommonLegend.prototype.M=function(){if(this.NF){this.Ca=new D.CE(this.e,this.Hxa,this);this.Bd=this.NF.q("label");this.GF="true"==this.NF.q("disclosed");var b=this.NF.getElementsByTagName("style");if(b&&(b=b[0].ib()))for(var c=0;c<b.length;c++){var d=b[c];"legend-title"==d.getName()?this.lL=d.getTextContent():"sectionGroup-title"==d.getName()?this.Y3=d.getTextContent():"section-title"==d.getName()?this.a4=d.getTextContent():"legend-item"==d.getName()&&(this.kL=d.getTextContent())}if(b=this.NF.q("noWrap"))this.I1=
"false"==b;b=this.Jh?new D.M(this.R,0,this.R,this.Y):new D.M(0,0,this.R,this.Y);this.sn=new D.G(this.e);this.k(this.sn);if(this.Bd&&(c=this.Kz()?new D.Oq(this.e):new D.Ya(this.e),d=b.g-b.x,this.Jh&&(d=b.g-d),0<d&&(this.Jh&&c.Gi(),this.lL&&c.Ga(new D.O(this.lL)),c.xd(this.Bd),c.fa(b.x),c.ra(b.y),D.Pb.Tb(c,d,b.j,this.sn),c.bg()&&this.Ca.la(c,new D.Xq(this.Bd)),(c=c.D())&&0<c.j)))b.y=b.y+c.j+this.F.rowColGap;this.ce=[];if(d=this.NF.ib()){for(c=0;c<d.length;c++){var e=d[c];if("separatorDef"==e.getName()&&
(e=e.ib(),0<e.length&&"separator"==e[0].getName())){this.yE=D.n;break}}for(c=0;c<d.length;c++)e=d[c],b.x=this.Jh?this.R:0,"sectionGroup"==e.getName()?(this.yE&&(this.Bd||1<c)&&this.ce.push((0,D.BE)(this,this.sn,b)),this.ce.push((0,D.zE)(this,e,this.sn,b,this.Jh))):"section"==e.getName()&&(this.yE&&(this.Bd||1<c)&&this.ce.push((0,D.BE)(this,this.sn,b)),this.ce.push((0,D.wE)(this,e,this.sn,b,this.Jh)))}this.lc=this.vj();for(b=0;b<this.cu.length;b++)this.Jh?this.cu[b].ri(this.lc.x):this.cu[b].ri(this.lc.g);
this.Ca.nf(this);for(c=0;c<this.IJ.length;c++)b=this.IJ[c],this.Ca.la(b,b),this.yF&&-1<D.$c.Ha(this.yF,b.sj()+":"+b.Gw())&&(0,D.DE)(b,D.n)}else{this.Ca=new D.CE(this.e,this.Hxa,this);this.Bd=this.IB.label;this.GF="true"==this.IB.disclosed;if(b=this.IB.style)this.lL=b["legend-title"],this.Y3=b["sectionGroup-title"],this.a4=b["section-title"],this.kL=b["legend-item"];if(b=this.IB.noWrap)this.I1="false"==b;b=this.Jh?new D.M(this.R,0,this.R,this.Y):new D.M(0,0,this.R,this.Y);this.sn=new D.G(this.e);this.k(this.sn);
if(this.Bd&&(c=this.Kz()?new D.Oq(this.e):new D.Ya(this.e),d=b.g-b.x,this.Jh&&(d=b.g-d),0<d&&(this.Jh&&c.Gi(),this.lL&&c.Ga(new D.O(this.lL)),c.xd(this.Bd),c.fa(b.x),c.ra(b.y),D.Pb.Tb(c,d,b.j,this.sn),c.bg()&&this.Ca.la(c,new D.Xq(this.Bd)),(c=c.D())&&0<c.j)))b.y=b.y+c.j+this.F.rowColGap;this.ce=[];if(d=this.IB.separatorDef)for(c=0;c<d.length;c++)if((e=d[c].separator)&&0<e.length){this.yE=D.n;break}d=this.IB.sectionGroup;b.x=this.Jh?this.R:0;if(d)for(c=0;c<d.length;c++)this.yE&&(this.Bd||1<c)&&this.ce.push((0,D.BE)(this,
this.sn,b)),this.ce.push((0,D.AE)(this,d[c],this.sn,b,this.Jh));if(d=this.IB.section)for(c=0;c<d.length;c++)this.yE&&(this.Bd||1<c)&&this.ce.push((0,D.BE)(this,this.sn,b)),this.ce.push((0,D.xE)(this,d[c],this.sn,b,this.Jh));this.lc=this.vj();for(b=0;b<this.cu.length;b++)this.Jh?(this.lc.x=this.cu[b].$j()-this.lc.g,this.cu[b].ri(this.lc.x)):this.cu[b].ri(this.lc.g+this.cu[b].$j());this.Ca.nf(this);for(c=0;c<this.IJ.length;c++)b=this.IJ[c],this.Ca.la(b,b),this.yF&&-1<D.$c.Ha(this.yF,b.sj()+":"+b.Gw())&&
(0,D.DE)(b)}this.yF&&(this.lc=this.vj(),this.Rb(new D.Lm(this.lc.g,this.lc.j,this.lc.x,this.lc.y)));this.Jh&&this.sn.G(-this.lc.x)};D.yE=function(b,c,d,e,f,g,h,j){this.Init(b,c,d,e,f,g,h,j)};D.F.o(D.yE,D.G,"DvtCommonLegendSection");D.yE.prototype.Init=function(b,c,d,e,f,g,h,j){D.uE.u.Init.call(this,b);this.Bd=d;this.iz=e;this.tb=[];this.ya=c;this.UA=f;this.jB=g;this.fK=h?0:1;this.F=j};
D.EE=function(b,c,d,e,f,g,h){if(!c)return new D.Yb(b.e);switch(h){case 1:h=new D.Wb(b.e,c.groupColEna,d,e,f,g);var j=new D.Wb(b.e,c.groupColOvr,d,e,f,g);c=new D.Wb(b.e,c.groupColDwn,d,e,f,g);return new D.Yb(b.e,h,j,c);default:return h=new D.Wb(b.e,c.groupExpDwn,d,e,f,g),j=new D.Wb(b.e,c.groupExpOvr,d,e,f,g),c=new D.Wb(b.e,c.groupExpDwn,d,e,f,g),new D.Yb(b.e,h,j,c)}};D.D=D.yE.prototype;
D.D.Zea=function(){var b=(0,D.ya)()?-1:1;this.Z3||(this.Z3=this.vj().j-this.Nv);0==this.fK?("alta"==this.F.skin?(b=this.Ib.getParent(),b.removeChild(this.Ib),this.Ib=this.$x,b.k(this.Ib)):this.Ib.Jc([this.Ar+1.5*b,this.Br+1.5,this.Ar+9.5*b,this.Br+5.5,this.Ar+1.5*b,this.Br+9.5]),this.Lfa=D.t,this.fK=1,b=-this.Z3):("alta"==this.F.skin?(b=this.Ib.getParent(),b.removeChild(this.Ib),this.Ib=this.Ev,b.k(this.Ib)):this.Ib.Jc([this.Ar+1.5*b,this.Br+1.5,this.Ar+9.5*b,this.Br+1.5,this.Ar+5.5*b,this.Br+9.5]),
this.Lfa=D.n,this.fK=0,b=this.Z3);if(this.Lfa)for(var c=0;c<this.tb.length;c++)this.k(this.tb[c]);else for(c=0;c<this.tb.length;c++)this.removeChild(this.tb[c]);this.ya.update(this,b)};D.D.PR=function(){"alta"==!this.F.skin&&this.Ib.na(this.F.ovr)};D.D.OR=function(){"alta"==!this.F.skin&&this.Ib.na(this.F.ena)};D.D.NR=function(){"alta"==!this.F.skin&&this.Ib.na(this.F.dwn)};D.D.pj=function(b){return this.tb.push(b)};
D.D.M=function(b,c,d){b.k(this);b=new D.G(this.e);this.k(b);this.Ar=c.x;this.Br=c.y;var e=d?-1:1;if("alta"==this.F.skin){var f=this.ya.ej;this.Ev=(0,D.EE)(this,f,this.Ar,this.Br,this.F.buttonSize,this.F.buttonSize,0);this.$x=(0,D.EE)(this,f,this.Ar,this.Br,this.F.buttonSize,this.F.buttonSize,1);this.Ib=this.Ev}else this.Ib=new D.Ma(this.e,[this.Ar+1.5*e,this.Br+1.5,this.Ar+9.5*e,this.Br+1.5,this.Ar+5.5*e,this.Br+9.5]),this.Ib.na(this.F.ena);b.k(this.Ib);if((0,D.Vb)())b.U(D.Jt.Xd,this.Zea,D.t,this);
else{var g=this;this.ya.Nc().la(b,{he:function(){return 0==g.fK?g.UA:g.jB}});b.U(D.Ib,this.Zea,D.t,this);b.U(D.So,this.PR,D.t,this);b.U(D.To,this.OR,D.t,this);b.U(D.Eh,this.NR,D.t,this)}this.fK=0;c.x+=(("alta"==this.F.skin&&d?0:this.F.buttonSize)+this.F.rowColGap)*e;this.Bd&&(e=this.ya.Kz()?new D.Oq(this.e):new D.Ya(this.e),f=c.g-c.x,d&&(f=c.g-f),0<f&&(d&&e.Gi(),this.iz&&e.Ga(new D.O(this.iz)),e.xd(this.Bd),e.fa(c.x),e.ra(c.y),D.Pb.Tb(e,f,c.j,b),e.bg()&&this.ya.Nc().la(e,new D.Xq(this.Bd)),b=e.D(),
c.y=c.y+window.Math.max(b?b.j:0,this.F.buttonSize)+this.F.rowColGap));c.x+=(this.F.buttonSize+this.F.rowColGap)*(d?1:-1);this.Nv=this.vj().j};D.uE=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.uE,D.G,"DvtCommonLegendSection");D.uE.prototype.Init=function(b,c,d,e,f){D.uE.u.Init.call(this,b);this.Bd=d;this.iz=e;this.tb=[];this.ya=c;this.F=f};D.uE.prototype.pj=function(b){return this.tb.push(b)};D.uE.prototype.cV=(0,D.C)("tb");
D.uE.prototype.M=function(b,c,d){b.k(this);if(this.Bd){b=this.ya.Kz()?new D.Oq(this.e):new D.Ya(this.e);var e=c.g-c.x;d&&(e=c.g-e);0<e&&(d&&b.Gi(),this.iz&&b.Ga(new D.O(this.iz)),b.xd(this.Bd),b.fa(c.x),b.ra(c.y),D.Pb.Tb(b,e,c.j,this),b.bg()&&this.ya.Nc().la(b,new D.Xq(this.Bd)),d=b.D(),c.y=c.y+(d?d.j:0)+this.F.rowColGap)}};D.vE=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.vE,D.G,"DvtCommonLegendRow");D.D=D.vE.prototype;
D.D.Init=function(b,c,d,e,f){D.vE.u.Init.call(this,b);this.ya=c;this.Xo=d;this.Jfa=e;this.kQ=D.t;this.F=f};D.D.sj=function(){return this.Xo.attributeGroupId};D.D.Gw=function(){return this.Xo.itemId};D.D.w6=function(){return this.Xo.hideAttrs};D.D.Yg=(0,D.A)("Xa");D.D.setMarker=function(b,c,d,e,f){this.dU=b;this.I=c;this.Fg=d?d:"#000000";this.Wo=e;this.U2=f};D.DE=function(b,c){b.kQ=!b.kQ;b.tn.CD(b.Fg);b.Wi();c||(b.ya.lc=b.ya.vj(),b.ya.Rb(new D.Lm(b.ya.lc.g,b.ya.lc.j,b.ya.lc.x,b.ya.lc.y)))};
D.vE.prototype.Qf=function(){if(this.ya.nM){var b=this.ya.AJ(),c=[(0,D.ec)(b,this.kQ?"STATE_HIDDEN":"STATE_VISIBLE")];return(0,D.gc)(this.Xa,c,b)}return D.q};D.vE.prototype.Wi=function(){(0,D.hc)()||(0,D.ic)(this,"label",this.Qf())};
D.vE.prototype.M=function(b,c,d){if(this.Xo){var e=this.ya,f=this.Xo.attributeGroupId,g=this.Xo.itemId;e.ZP[f]==D.q&&(e.ZP[f]={});e.ZP[f][g]=this;this.ya.IJ.push(this);e=this.ya;f=this.Xo.hideAttrs;e.n1[f]||(e.n1[f]=this)}b.k(this);b=c.x;d&&(c.x-=this.F.indicatorSize);var h;if(this.dU||this.I!=D.q)h=new D.va(this.e,this.dU?[this.dU]:this.I,this.F[D.DvtCommonLegend.Lqa],c.x,c.y,this.F.indicatorSize,this.F.indicatorSize),e=D.lg.Vka(this.e,this.I),!this.dU&&!e&&(this.Wo?h.H(new D.qd(this.Wo,this.Fg)):
h.na(this.Fg,this.U2)),this.k(h),c.x=d?c.x-this.F.rowColGap:c.x+this.F.indicatorSize+this.F.rowColGap;this.tn=h;h=new D.M;this.Xa&&(this.ya.nM&&((0,D.tb)(this,"img"),this.Wi()),e=c.g-c.x,d&&(e=c.g-e),0>e?this.ya.Nc().la(this.tn,new D.Xq(this.Xa)):(f=this.ya.Kz()?new D.Oq(this.e):new D.Ya(this.e),d&&f.Gi(),this.Jfa&&f.Ga(new D.O(this.Jfa)),f.xd(this.Xa),f.fa(c.x),f.ra(c.y),D.Pb.Tb(f,e,c.j,this)?(h=f.D(),f.bg()&&this.ya.Nc().la(f,new D.Xq(this.Xa))):this.ya.Nc().la(this.tn,new D.Xq(this.Xa))));c.y=
c.y+window.Math.max(this.F.indicatorSize,h.j)+this.F.rowColGap;c.x=b};D.CE=function(b,c,d){this.Init(b,c,d);this.ya=d};D.F.o(D.CE,D.Uc,"DvtCommonLegendEventManager");D.D=D.CE.prototype;D.D.bh=function(b){D.CE.u.bh.call(this,b);this.vy(b)};D.D.ro=function(b){D.CE.u.ro.call(this,b);(0,D.FE)(this,b)};D.D.ik=function(b){D.CE.u.ik.call(this,b);(0,D.FE)(this,b)};D.D.ct=function(b){D.CE.u.ct.call(this,b);this.vy(b)};
D.D.vy=function(b){if(this.ya.nM){var c=(0,D.gb)(this,b.target);if(c instanceof D.vE){var d=c.Gw(),e=c.sj();(0,D.DE)(c);b=new D.GE(d,e,c.kQ?"hide":"show",b);this.ya.Rb(b)}}};D.FE=function(b,c){var d=(0,D.gb)(b,c.target);if(d instanceof D.vE){if(b.ya.Dza){var e=d.Gw(),f=d.sj(),e=new D.HE(e,f,d.w6(),c.type,c);b.ya.Rb(e)}b.ya.nM&&(0,D.Du)(b,d)}};
});