define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.XA=function(b,c){this.Init(c===D.t?"sunburstRotationInput":"sunburstRotation");this.Tc=b};(0,D.ta)("DvtSunburstRotationEvent",D.XA);D.F.o(D.XA,D.oc,"DvtSunburstRotationEvent");D.XA.TYPE="sunburstRotation";D.XA.TYPE_INPUT="sunburstRotationInput";D.XA.prototype.Nla=(0,D.C)("Tc");D.XA.prototype.getStartAngle=D.XA.prototype.Nla;
D.TK=function(b,c,d){this.Init(b,c,d)};D.F.o(D.TK,D.SD,"DvtBaseSunburst");D.D=D.TK.prototype;D.D.Init=function(b,c,d){D.TK.u.Init.call(this,b,c,d);this.ff=new D.aA;this.bd=2*window.Math.PI};D.D.Zu=function(b){return(new D.gA(this)).parse(b)};D.D.CI=function(b){D.TK.u.CI.call(this,b);this.Dia=b.rotation;this.Bia=(0,D.$d)()?"url("+this.oh.cursorRotate+"), auto":"url("+this.oh.cursorRotate+") 8 8, auto";this.Tc=(360-b.Wl)*D.Mz/360;this.Tc>window.Math.PI&&(this.Tc-=D.Mz)};
D.D.po=function(b){var c=window.Math.max(window.Math.ceil(3*window.Math.min(b.g,b.j)/400),2);b.x+=c;b.y+=c;b.g-=2*c;b.j-=2*c;(0,D.TD)(this,b);(0,D.UD)(this,b);this.wja=window.Math.floor(window.Math.min(b.g,b.j)/2);this.Pa&&D.hA.Rn(this.wja,this.Pa,this.Tc,this.bd,this.wP)};
D.D.ti=function(b,c){(0,D.VD)(this,b);this.rl&&b.k(this.rl);this.ya&&(b.k(this.ya),this.ya=D.q);this.WG=new D.K(c.x+c.g/2,c.y+c.j/2);if("on"==this.Dia&&(0,D.WD)(this)){var d=(0,D.Vb)()?60:15,d=new D.Yf(this.e,c.x+c.g/2,c.y+c.j/2,this.wja+d);(0,D.Xb)(d);d.setCursor(this.Bia);b.k(d);this.Va().la(d,new D.Zb(D.q,"_rotationShape"))}d=new D.G(this.e);(0,D.wa)(d,this.WG.x,this.WG.y);b.k(d);if((0,D.WD)(this)){var e=new D.G(this.e);d.k(e);this.Pa.M(e);this.au=new D.G(this.e);d.k(this.au);this.ifa=new D.G(this.e);
d.k(this.ifa)}else(0,D.XD)(this,b)};D.D.WD=function(b,c,d,e){return new D.bA(b,c,d,e)};D.D.CX=function(b,c){if("fan"===this.QW&&(0,D.WD)(this)){this.TZ(0);var d=new D.Sb(this.e,this,this.RD);(0,D.P)(d.S,"typeNumber",this,this.Uva,this.TZ,2*window.Math.PI);return d}return D.TK.u.CX.call(this,b,c)};D.D.AX=function(){var b=D.TK.u.AX.call(this);b&&(0,D.wa)(b,this.WG.x,this.WG.y);return b};
D.D.Dp=function(){if(!this.RW){this.ha.qi();var b=new D.M(0,0,this.rb,this.Lb);this.po(b);this.ti(this.ha,b);for(var b=this.Kb?this.Kb.getSelection():[],c=0;c<b.length;c++)b[c].Nb(D.n)}this.bd<2*window.Math.PI&&this.TZ(2*window.Math.PI);D.TK.u.Dp.call(this)};D.D.KP=function(b){this.au.k(b);!(0,D.Ab)()&&!(0,D.Bb)()&&((0,D.Fb)(this.au),(0,D.Cb)(this.au,D.Db))};D.D.Uva=(0,D.C)("bd");D.D.TZ=function(b){this.bd=b;this.po(new D.M(0,0,this.rb,this.Lb));this.Pa&&(0,D.Sz)(this.Pa,D.n)};
D.cA=function(b,c){b.m0=c;b.wG=new D.H(b.e,0,0,b.rb,b.Lb);(0,D.Xb)(b.wG);b.wG.setCursor(b.Bia);b.k(b.wG);b.Va().la(b.wG,new D.Zb(D.q,"_rotationShape"))};D.eA=function(b,c){var d=c-b.m0;b.m0=c;b.Tc+=d;b.Tc<-window.Math.PI?b.Tc+=2*window.Math.PI:b.Tc>window.Math.PI&&(b.Tc-=2*window.Math.PI);b.po(new D.M(0,0,b.rb,b.Lb));b.Pa&&(0,D.Sz)(b.Pa,D.n);b.Ya(new D.XA(360-window.Math.round(180*b.Tc/window.Math.PI),D.t))};
D.fA=function(b){b.m0=D.q;b.removeChild(b.wG);b.wG=D.q;var c=360-window.Math.round(180*b.Tc/window.Math.PI);b.Ya(new D.XA(c,D.t));b.Ya(new D.XA(c,D.n))};D.dA=function(b,c,d){return window.Math.atan2(d-b.WG.y,c-b.WG.x)};
D.UK=(0,D.v)();(0,D.ta)("DvtSunburst",D.UK);D.F.o(D.UK,D.TK,"DvtSunburst");D.UK.newInstance=function(b,c,d){var e=new D.UK;e.Init(b,c,d);return e};D.UK.getDefaults=function(b){return(0,D.aB)(new D.aA,b)};D.UK.prototype.M=function(b,c,d){b?(this.Q=this.ff.Pg(b),(0,D.Ti)()||(this.Q.animationOnDisplay="none",this.Q.animationOnDataChange="none")):this.Q||(this.Q=(0,D.gd)(this));b=(new D.Jz).T8(this.Q);D.UK.u.M.call(this,b,c,d)};D.UK.prototype.render=D.UK.prototype.M;
D.UK.prototype.hd=function(){this.Eg||(this.Eg=new D.Kz);return this.Eg};
D.gA=function(b){this.Init(b)};D.F.o(D.gA,D.mc,"DvtSunburstParser");D.gA.prototype.Wm=function(b,c,d){return new D.Lz(b,c,d)};D.gA.prototype.$l=function(b){var c=D.gA.u.$l.call(this,b);c.rotation=b.q("r");c.Wl=b.q("sa");if(c.Wl===D.q||(0,window.isNaN)(c.Wl))c.Wl=90;return c};D.gA.prototype.$u=function(b){var c=D.gA.u.$u.call(this,b);c.PV=b.q("ha");c.op=b.q("r");return c};
D.gA.prototype.tY=function(b,c,d,e){e.NODE_DEFAULT_COLOR_STYLE=b.A("border-color");e.NODE_HOVER_COLOR_STYLE=c.A("border-color");e.NODE_SELECTED_INNER_COLOR_STYLE=d.A("-tr-inner-color");e.NODE_SELECTED_OUTER_COLOR_STYLE=d.A("-tr-outer-color")};
D.Lz=function(b,c,d){this.Init(b,c,d);this.Lo=c.OV?c.OV:"auto";this.JF=c.PV;this.Pj=c.op};D.F.o(D.Lz,D.pb,"DvtSunburstNode");D.Mz=2*window.Math.PI;
D.Lz.prototype.M=function(b){if(this.Mv){this.RS=b;this.I=this.j0();b.k(this.I);var c=this.tM;if(!this.mf&&(0==this.di&&this.bd==D.Mz)&&c){var d=window.Math.sqrt(2),e=this.Kh*d-4;this.$a=-this.Kh/d+2;this.Ma=-this.Kh/d+2;d=this.J.OZ;d.Fo=this.$h;0<e&&0<e&&((0,D.qb)(d,e),(0,D.rb)(d,e),d.Ef((0,D.sb)(this)),this.Z_=c=D.T.xD(d,c,this.I),d=c.D(),(0,D.wa)(c,this.$a+(e-d.g)/2,this.Ma+(e-d.j)/2))}else this.Xa=this.sK(this.I),this.Xa!=D.q&&(this.I.k(this.Xa),this.Wo&&(d=this.Xa.Vb(),this.bp=new D.H(this.J.e,
d.x,d.y,d.g,d.j),this.bp.na("#FFFFFF"),this.bp.ja(D.t),this.I.k(this.bp),e=this.Xa.ma(),(0,D.Nz)(e)||this.bp.qa(e),this.I.k(this.Xa)));(0,D.tb)(this.I,"img");this.Wi();this.Ku(b)}};D.Lz.prototype.Nb=function(b){"off"!=this.nE&&(D.Lz.u.Nb.call(this,b),this.Ta()?(this.I.Nb(D.n),this.J.KP(this.I)):(this.I.Nb(D.t),this.RS&&this.RS.k(this.I)))};D.Lz.prototype.Bc=function(){this.I&&this.Mv&&(this.I.Bc(),this.Ta()?this.J.KP(this.I):this.J.ifa.k(this.I))};
D.Lz.prototype.nc=function(){this.I&&(this.Mv&&!this.wh())&&(this.I.nc(),!this.Ta()&&this.RS&&this.RS.k(this.I))};D.Oz=function(b){return"i"==b.sR||"ir"==b.sR};
D.Lz.prototype.wg=function(b){var c,d,e,f;if(b.type==D.Ib)return D.Lz.u.wg.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;for(f=this;f.mf;)f=f.mf;d=(0,D.Nb)(this,f,(0,D.Mb)(this));a:{for(e=0;e<d.length;e++)if(this===d[e])break a;e=-1}var g=this.Tc+this.bd/2,g=(0,D.Pz)(g);switch(c){case 38:if(this===f||180<g){if(c=this.xS)if(d=c.Tc+c.bd/2,d=(0,D.Pz)(d),180<d)return c;b=(0,D.qn)(this,b,(0,D.zt)(this))}else b=(0,D.Qz)(this);break;case 40:if(this===f||0<=g&&180>=g){if(c=this.xS)if(d=c.Tc+c.bd/
2,d=(0,D.Pz)(d),0<=d&&180>=d)return c;b=(0,D.qn)(this,b,(0,D.zt)(this))}else b=(0,D.Qz)(this);break;case 37:b=1==d.length?this:0==e?d[d.length-1]:d[e-1];break;case 39:b=1==d.length?this:e==d.length-1?d[0]:d[e+1];break;default:b=this}(0,D.Kb)(b);return b};D.Qz=function(b){var c=b.mf;c&&(b=c,(0,D.Kb)(c));(0,D.Kb)(b);return b};D.Pz=function(b){b=D.Cq.l8(b);0>b?b+=360:360<b&&(b-=360);return b};D.D=D.Lz.prototype;
D.D.xe=function(){if(this.I){var b=this.I.D(),c=new D.K(b.x,b.y),c=(0,D.Ic)(this.I,c);b.x=c.x;b.y=c.y;return b}return new D.M(0,0,0,0)};D.D.Mn=function(){return this.I?this.I.oa():D.q};D.D.UU=function(){return(0,D.Ic)(this.I,(0,D.Rz)(0.5*(this.Kh+this.di),this.Tc+this.bd/2))};D.D.fO=function(b,c,d,e){this.di=b;this.Kh=c;this.Tc=d;this.bd=e;this.Mv=D.n};D.D.ZD=function(){return this.IE?(0,D.Op)():D.Lz.u.ZD.call(this)};
D.D.fl=function(){var b=D.U.kd(this.Fg),c=D.U.jd(this.Fg),d=D.U.gd(this.Fg);return[this.di,this.Kh,this.Tc,this.bd,b,c,d]};D.D.vo=function(b){this.fO(b[0],b[1],b[2],b[3]);this.Fg=D.U.Ww(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));(0,D.Sz)(this,D.t)};D.D.Pf=function(b,c){c.Mv&&0<c.bd?D.Lz.u.Pf.call(this,b,c):this.Og(b)};D.D.contains=function(b,c){var d=(0,D.Tz)(b,c);return window.Math.sqrt(b*b+c*c)>=this.di&&window.Math.sqrt(b*b+c*c)<=this.Kh&&(0,D.Uz)(this,d)};
D.Uz=function(b,c){for(;c<b.Tc;)c+=D.Mz;for(;c-b.Tc>D.Mz;)c-=D.Mz;return c>=b.Tc&&c<=b.Tc+b.bd};D.Rz=function(b,c){return{x:window.Math.cos(c)*b,y:window.Math.sin(c)*b}};D.Tz=function(b,c){var d=window.Math.atan2(c,b);0>d?d+=D.Mz:d>D.Mz&&(d-=D.Mz);return d};
D.Lz.prototype.j0=function(){if(!this.bd||0>=this.bd)return D.q;var b=(0,D.Vz)(this),b=new D.Ra(this.J.e,b);this.J.Va().la(b,this);b.C(this.aa());b.H(this.ZD());var c=(0,D.zb)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR_STYLE"),d=(0,D.zb)(this,"#000000","NODE_SELECTED_OUTER_COLOR_STYLE"),e=(0,D.zb)(this,"#FFFFFF","NODE_HOVER_COLOR_STYLE");b.Z(new D.Hb((0,D.zb)(this,"#FFFFFF","NODE_DEFAULT_COLOR_STYLE"),0.3));b.Yq(new D.Hb(e,1,3));b.$q(new D.Hb(c,1,1.5),new D.Hb(d,1,3.5));b.Ou(new D.Hb(e,1,3));b.Bg(this.J.D2!=
D.q&&"off"!=this.nE);this.IE&&(b.C(0.001),b.ja(D.t));return b};
D.Vz=function(b){var c,d,e,f;b.bd<D.Mz?(c=(0,D.Rz)(b.Kh,b.Tc),d=(0,D.Rz)(b.Kh,b.Tc+b.bd),e=(0,D.Rz)(b.di,b.Tc+b.bd),f=(0,D.Rz)(b.di,b.Tc),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.Kh,b.Kh,b.bd,1,d.x,d.y)+window.DvtPathUtils.lineTo(e.x,e.y)+window.DvtPathUtils.arcTo(b.di,b.di,b.bd,0,f.x,f.y)+window.DvtPathUtils.closePath()):(c=(0,D.Rz)(b.Kh,b.Tc),d=(0,D.Rz)(b.Kh,b.Tc+b.bd/2),e=(0,D.Rz)(b.di,b.Tc),f=(0,D.Rz)(b.di,b.Tc+b.bd/2),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.Kh,
b.Kh,b.bd/2,1,d.x,d.y)+window.DvtPathUtils.arcTo(b.Kh,b.Kh,b.bd/2,1,c.x,c.y),0<b.di&&(c+=window.DvtPathUtils.moveTo(f.x,f.y)+window.DvtPathUtils.arcTo(b.di,b.di,b.bd/2,0,e.x,e.y)+window.DvtPathUtils.arcTo(b.di,b.di,b.bd/2,0,f.x,f.y)),c+=window.DvtPathUtils.closePath());return c};
D.Lz.prototype.sK=function(b){if(!this.hz||!b||!this.Lo||"off"==this.Lo)return D.q;var c=D.t;if("auto"==this.Lo){if(c=!(0,D.$d)())(0,D.Wz)(),c="Windows"==D.Xz;c=c?D.t:D.n}else"rotated"==this.Lo&&(c=D.n);if(c&&this.bd<2*window.Math.PI){var d=window.Math.max(this.di,10),e=this.Kh-d-6,f=1.1*this.bd*(d+6);if(6>=f)b=D.q;else if(c=new D.Ya(this.J.e,this.hz,0,0),c.Ef((0,D.sb)(this)),(0,D.$b)(this,c),D.Pb.Tb(c,e,f,b)){f=(d+this.Kh)/2;if("s"==this.JF||"e"==this.JF)b.k(c),b=c.D().g,"s"==this.JF?f=d+4.5+b/2:
"e"==this.JF&&(f=d+e-4.5-b/2);b=(0,D.Rz)(f,this.Tc+this.bd/2);c.Af();c.Pe();d=this.Tc+this.bd/2;d=d>=D.Mz?d-D.Mz:d;d=0>d?d+D.Mz:d;d>0.5*window.Math.PI&&d<1.5*window.Math.PI&&(d+=window.Math.PI);c.Ti(d);(0,D.wa)(c,b.x,b.y);c.ja(D.t);b=c}else b=D.q}else{if(0==this.di)c={x:0,y:0};else if(c=(0,D.Rz)((this.di+this.Kh)/2,this.Tc+this.bd/2),d=3*(0,D.sb)(this)/2,e=(0,D.Tz)(c.x+d/2,c.y),!(0,D.Uz)(this,(0,D.Tz)(c.x-d/2,c.y))||!(0,D.Uz)(this,e))c=D.q;if(c){d=new D.Ya(this.J.e,this.hz,c.x,c.y,D.q);d.Ef((0,D.sb)(this));
(0,D.$b)(this,d);d.Af();d.Pe();d.ja(D.t);for(var e=D.Pb.Ni(d),g=f=c.x,h=c.y-e.j/2,j=c.y+e.j/2;this.contains(f,h)&&this.contains(f,j);)f--;for(;this.contains(g,h)&&this.contains(g,j);)g++;f+=3;g-=3;c=2*window.Math.min(c.x-f,g-c.x);c<e.g&&(d.fa((f+g)/2),c=g-f);b=D.Pb.Tb(d,c,e.j,b)?d:D.q}else b=D.k}return b};
D.Lz.prototype.Pw=function(){if(!this.Lc){var b;b=this.I;if(!b||!(0,D.Oz)(this))b=D.q;else{var c;if(this.kg){c=this.J.e;var d=this.J.oh,e=new D.Wb(c,d.collapseUp,0,0,16,16),f=new D.Wb(c,d.collapseOver,0,0,16,16),d=new D.Wb(c,d.collapseDown,0,0,16,16)}else c=this.J.e,d=this.J.oh,e=new D.Wb(c,d.expandUp,0,0,16,16),f=new D.Wb(c,d.expandOver,0,0,16,16),d=new D.Wb(c,d.expandDown,0,0,16,16);(0,D.Xb)(e);(0,D.Xb)(f);(0,D.Xb)(d);c=new D.Yb(c,e,f,d);c.U(D.Ib,this.S5,D.t,this);e=(0,D.Rz)(this.Kh,this.Tc+this.bd/
2);(0,D.wa)(c,e.x-8,e.y-8);b.k(c);b=this.kg?this.J.oh.collapse:this.J.oh.expand;this.J.Va().la(c,new D.Zb(this,this.getId(),b));b=c}this.Lc=b}D.Lz.u.Pw.call(this)};D.Lz.prototype.Oq=function(){this.Lc&&this.I&&(this.I.removeChild(this.Lc),this.Lc=D.q);D.Lz.u.Oq.call(this)};
D.Sz=function(b,c){if(b.I){var d=(0,D.Vz)(b);b.I.ek(d);if(b.mf||!(0==b.di&&b.bd==D.Mz))b.Xa&&b.I.removeChild(b.Xa),b.Xa=b.sK(b.I),b.bp&&(b.I.removeChild(b.bp),b.bp=D.q);b.I.H(b.ZD());if(c)for(var d=b.ib(),e=0;e<d.length;e++)(0,D.Sz)(d[e],D.n)}};
D.Lz.prototype.S5=function(){this.kg=!this.kg;var b=this.J,c=this.kg,d=this.getId();b.BL=d;if(c)b.Ya(new D.Yz("sunburstExpand",this.getId()));else{var c=b.fY,d=this.getId(),d=c.indexOf('\x3cn id\x3d"'+d),e=c.indexOf("\x3e",d),f=c.substring(d,e),f=-1<f.indexOf("di\x3d")?f.replace('di\x3d"t"','di\x3d"f"'):f+'di\x3d"f"';b.M(c.substring(0,d)+f+c.substring(e),b.rb,b.Lb);b.Ya(new D.Yz("sunburstCollapse",this.getId()))}this.Wi()};D.Lz.prototype.kb=(0,D.C)("kg");
D.Zz=function(b){return b.Pj!=D.q?(0,window.Number)(b.Pj):b.mf?1:b.IE?0.25:b.tM?1:0.5};D.Lz.prototype.Qf=function(){var b=[];"off"!=this.nE&&b.push((0,D.ec)(this.ad,this.Ta()?"STATE_SELECTED":"STATE_UNSELECTED"));(0,D.Oz)(this)&&b.push((0,D.ec)(this.ad,this.kb()?"STATE_EXPANDED":"STATE_COLLAPSED"));return(0,D.gc)(this.ny,b,this.ad)};D.Lz.prototype.Wi=function(){!(0,D.hc)()&&this.I&&(0,D.ic)(this.I,"label",this.Qf())};
D.hA={};D.F.o(D.hA,D.F,"DvtSunburstLayout");D.hA.Rn=function(b,c,d,e,f){var g=D.hA.$ca(c);D.hA.Kf(b/g,c,d,e,f,0)};D.hA.Kf=function(b,c,d,e,f,g){var h=g+(0,D.Zz)(c)*b;c.fO(g,h,d,e);g=c.ib();if(g!=D.q&&c.kb()){"on"==f&&(g=g.slice(0),g.sort(function(b,c){return c.rc()-b.rc()}));(0,D.ya)(c.J.e)&&(g=g.slice(0).reverse());var j=0;for(c=0;c<g.length;c++)j+=0<g[c].rc()?g[c].rc():0;for(c=0;c<g.length;c++){var m=g[c];if(!(0>=m.rc())){var o=m.rc()/j*e;D.hA.Kf(b,m,d,o,f,h);d+=o}}}};
D.hA.$ca=function(b){var c=0,d=b.ib();if(d&&0<d.length){for(var e=0;e<d.length;e++)var f=D.hA.$ca(d[e]),c=window.Math.max(c,f);return c+(0,D.Zz)(b)}return(0,D.Zz)(b)};
D.Yz=function(b,c){this.Init(b);this.Oa=c?c:D.q};D.F.o(D.Yz,D.oc,"DvtSunburstExpandCollapseEvent");D.Yz.prototype.getId=(0,D.C)("Oa");
D.bA=function(b,c,d,e){D.pc.call(this,b,c,d,e)};D.F.o(D.bA,D.pc,"DvtSunburstEventManager");D.D=D.bA.prototype;D.D.il=function(b){var c=(0,D.gb)(this,b.target);c&&c.getId&&"_rotationShape"==c.getId()&&!this.tQ?(this.tQ=D.n,b=(0,D.Fa)(this.e,b.pageX,b.pageY),c=this.J,(0,D.cA)(c,(0,D.dA)(c,b.x,b.y))):D.bA.u.il.call(this,b)};D.D.Ep=function(b){if(this.tQ){b=(0,D.Fa)(this.e,b.pageX,b.pageY);var c=this.J;(0,D.eA)(c,(0,D.dA)(c,b.x,b.y))}else D.bA.u.Ep.call(this,b)};
D.D.Zm=function(b){this.tQ?(this.tQ=D.t,(0,D.fA)(this.J)):D.bA.u.Zm.call(this,b)};D.D.am=function(b){var c=D.n,d=b.keyCode,e=this.Re(),f=this.J;(0,D.Oz)(e)&&((0,D.ff)(b)&&!e.kb()||(0,D.jf)(b)&&e.kb()||b.ctrlKey&&13==d)?(e.S5(),b.preventDefault()):f&&"on"==f.Dia&&(37==d||39==d)&&!b.ctrlKey&&b.altKey&&b.shiftKey?(d=37==d?-5*(window.Math.PI/180):5*(window.Math.PI/180),(0,D.cA)(f,0),(0,D.eA)(f,d),(0,D.fA)(f),b.preventDefault()):c=D.bA.u.am.call(this,b);return c};
D.D.bE=function(b){var c=(0,D.gb)(this,b.target);c&&(c.getId&&"_rotationShape"==c.getId())&&(0,D.We)(b,this.Fqa,this)};D.D.WO=function(b){(0,D.Xe)(this.Pb,b,"rotateKey")};D.D.VO=function(b){(0,D.Ye)(this.Pb,b,"rotateKey")};D.D.Fqa=function(b,c){if(1>=(0,D.Ze)(this.Pb,"rotateKey").length){(0,D.$e)(this.Pb,c.identifier,"rotateKey",D.q,"rotateKey","rotateKey",this.Eqa,this.Dqa,this);(0,D.Il)(this.Pb,c.identifier,D.t);var d=(0,D.Fa)(this.e,c.pageX,c.pageY),e=this.J;(0,D.cA)(e,(0,D.dA)(e,d.x,d.y));b.pu()}};
D.D.Eqa=function(b,c){var d=(0,D.Fa)(this.e,c.pageX,c.pageY),e=this.J;(0,D.eA)(e,(0,D.dA)(e,d.x,d.y));b.preventDefault()};D.D.Dqa=function(){(0,D.fA)(this.J)};
D.Kz=(0,D.v)();D.F.o(D.Kz,D.wc,"DvtSunburstBundle");D.Kz._defaults={COLOR:"Color",SIZE:"Size"};D.Kz.prototype.ho=function(b){var c=D.Kz.u.ho.call(this,b);return c?c:D.Kz._defaults[b]};D.Kz.prototype.nx=(0,D.ba)("DvtSunburstBundle");
D.aA=function(){this.Init({skyros:D.$z,alta:{}})};D.F.o(D.aA,D.uc,"DvtSunburstDefaults");D.$z={rotation:"on"};
D.Jz=(0,D.v)();D.F.o(D.Jz,D.Ac,"DvtSunburstJsonUtils");D.D=D.Jz.prototype;D.D.NO=(0,D.ba)("sunburst");D.D.sJ=function(b){var c=D.Jz.u.sJ.call(this,b),c=c+this.Ea("r",b.rotation),c=c+this.Ea("sa",(b.startAngle+360)%360);b=b.animationOnDisplay;return c="auto"==b?c+this.Ea("adi","fan"):c+this.Ea("adi",b)};
D.D.tJ=function(b,c){var d=D.Jz.u.tJ.call(this,b,c),d=d+this.Ea("ld",c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay),e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"inner"==e?d+=this.Ea("ha","s"):"outer"==e&&(d+=this.Ea("ha","e"));e=c.radius;e!=D.q&&!(0,window.isNaN)(e)&&(d+=this.Ea("r",e));return d};
D.D.nZ=function(b){var c,d=new D.Kz;c="\x3cresources"+this.Ea("legendSize",(0,D.ec)(d,"SIZE"));c+=this.Ea("legendColor",(0,D.ec)(d,"COLOR"));c+=this.Ea("cursorRotate",b._resources.rotateCursor);c+=this.Ea("alta","true");return c+"/\x3e\n"};
D.D.uJ=function(b){var c=D.Jz.u.uJ.call(this,b),d=b.animationUpdateColor;d&&(c+=this.Ea("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.borderColor)&&(c+=this.Ea("node","border-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.Ea("node-hover","border-color: "+d));(b=b.nodeDefaults.selectedColor)&&(c+=this.Ea("node-selected","border-color: "+b));return c+"/\x3e\n"};
});