define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.RD=function(b,c,d){this.Init(b,c,d)};D.F.o(D.RD,D.SD,"DvtBaseTreemap");D.D=D.RD.prototype;D.D.Init=function(b,c,d){D.RD.u.Init.call(this,b,c,d);this.ff=new D.sc};D.D.Zu=function(b){return(new D.lc(this)).parse(b)};D.D.CI=function(b){D.RD.u.CI.call(this,b);this.Kf=b.Rn;this.Ewa=b.h7;this.Kf&&(this.Kf.wP=this.wP);this.Xc=[];if((b=b.Dma)&&this.Pa){var c=(0,D.zt)(this.Pa);c.push(this.Pa);for(var d=0;d<c.length;d++)if(c[d].getId()==b){this.Xc.push(c[d]);break}}};
D.D.po=function(b){var c=window.Math.max(window.Math.ceil(7*window.Math.min(b.g,b.j)/400),2);b.x+=c;b.y+=c;b.g-=2*c;b.j-=2*c;c=this.Kf.r6(this,1);b.x+=c;b.g-=2*c;(0,D.TD)(this,b);(0,D.UD)(this,b);b.x-=c;b.g+=2*c;c=this.Xc.length;if(0<c&&this.oS)this.Kf.Rn(this,this.Xc[c-1],b.x,b.y,b.g,b.j,D.n);else{this.Pa&&this.Kf.Rn(this,this.Pa,b.x,b.y,b.g,b.j,D.t);for(var d=0;d<c;d++)this.Kf.Rn(this,this.Xc[d],b.x,b.y,b.g,b.j,D.n)}};
D.D.ti=function(b){(0,D.VD)(this,b);this.rl&&b.k(this.rl);this.ya&&(b.k(this.ya),this.ya=D.q);if((0,D.WD)(this)){this.i1=new D.G(this.e);b.k(this.i1);this.txa?this.txa.M(b):this.Pa.Be()?this.Pa.Ku(b):this.Pa.M(b);this.K1=new D.G(this.e);b.k(this.K1);this.au=new D.G(this.e);b.k(this.au);b.k(this.i1);this.xy=new D.bl(this.e,[]);this.xy.Za(D.t);this.xy.ja(D.t);(0,D.wb)(this.xy);b.k(this.xy);for(b=0;b<this.Xc.length;b++){var c=this.Xc[b].Ia();this.K1.k(c)}}else(0,D.XD)(this,b)};
D.D.Dp=function(){this.RW||(this.ha.qi(),this.po(new D.M(0,0,this.rb,this.Lb)),this.ti(this.ha),this.QY());D.RD.u.Dp.call(this)};D.D.QY=function(){for(var b=this.Kb?this.Kb.getSelection():[],c=0;c<b.length;c++)if(0<this.Xc.length){var d=this.Xc[this.Xc.length-1];(b[c]==d||b[c].bD(d))&&b[c].Nb(D.n)}else b[c].Nb(D.n)};D.D.mx=function(b){return new D.jc(b)};D.D.WD=function(b,c,d,e){return new D.qc(b,c,d,e)};
D.D.o$=function(b){var c=(0,D.Gb)(this);return c?(0,D.Lb)(this,(0,D.At)(c)):b?(0,D.Lb)(this,(0,D.At)(b)):D.q};D.D.KP=function(b){for(var c=0,d=this.au.za(),e=0;e<d;e++){var f=this.au.da(e);b.zIndex>f.zIndex&&(c=e+1)}c<d?this.au.Fa(b,c):this.au.k(b)};D.Gb=function(b){return b.Xc&&0<b.Xc.length?b.Xc[b.Xc.length-1]:D.q};
D.dc=function(b,c){if(b.AI){for(var d=b.Kb?b.Kb.getSelection():[],e=0;e<d.length;e++)d[e].Nb(D.t);for(var d=[(0,D.Tb)(c)],e=(0,D.zt)(c),f=0;f<e.length;f++)d.push((0,D.Tb)(e[f]));b.Um=new D.Cn(b.e,d);b.Um.qd(b.Dp,b);b.Ca.Fs(b);b.Um.play()}else b.M(D.q,b.rb,b.Lb,D.n)};D.Lb=function(b,c){var d=b.Ca.Vi;return d?d.sH(c):c&&0<c.length?c[0]:D.q};
D.QD=(0,D.v)();(0,D.ta)("DvtTreemap",D.QD);D.F.o(D.QD,D.RD,"DvtTreemap");D.QD.newInstance=function(b,c,d){var e=new D.QD;e.Init(b,c,d);return e};D.QD.getDefaults=function(b){return(0,D.aB)(new D.sc,b)};D.QD.prototype.M=function(b,c,d,e){b?(this.Q=this.ff.Pg(b),(0,D.Ti)()||(this.Q.animationOnDisplay="none",this.Q.animationOnDataChange="none")):this.Q||(this.Q=(0,D.gd)(this));b=e?D.q:(new D.zc(this.e)).T8(this.Q);D.QD.u.M.call(this,b,c,d)};D.QD.prototype.render=D.QD.prototype.M;
D.QD.prototype.hd=function(){this.Eg||(this.Eg=new D.vc);return this.Eg};
D.lc=function(b){this.Init(b)};D.F.o(D.lc,D.mc,"DvtTreemapParser");D.D=D.lc.prototype;D.D.Wm=function(b,c,d){return new D.ob(b,c,d)};D.D.$l=function(b){var c=D.lc.u.$l.call(this,b),d=b.q("layout");c.Rn="h"==d?new D.lb(D.n):"v"==d?new D.lb(D.t):new D.nc;c.h7=b.q("gg");c.h7||(c.h7="o");c.Dma=b.q("irk");this.rxa=c.Dma;return c};
D.D.$u=function(b){var c=D.lc.u.$u.call(this,b);c.Tla=b.q("gld");c.PV=b.q("ha");c.Gma=b.q("va");c.Cma=b.q("hi");c.CEa=b.q("unc");c.nma=b.q("hha");if(b=b.q("hls"))c.BEa=new D.O(b);this.rxa==c.id&&(c.Uk=D.n);return c};D.D.tY=function(b,c,d,e){e.NODE_HOVER_COLOR=c.A("border-color");e.NODE_SELECTED_OUTER_COLOR=d.A("-tr-outer-color");e.NODE_SELECTED_INNER_COLOR=d.A("-tr-inner-color")};
D.D.Eaa=function(b,c){var d=new D.O(b.q("nodeHeader"));c.HEADER_TEXT_DEFAULT_STYLE=d;c.HEADER_BACKGROUND_STYLE=d;var e=d.clone().Bb(new D.O(b.q("nodeHeader-hover")));c.HEADER_TEXT_HOVER_DEFAULT_STYLE=e;c.HEADER_BACKGROUND_HOVER_STYLE=e;var f=d.clone().Bb(new D.O(b.q("nodeHeader-selected")));c.HEADER_TEXT_SELECTED_DEFAULT_STYLE=f;c.HEADER_BACKGROUND_SELECTED_STYLE=f;d=d.clone().Bb(new D.O(b.q("nodeHeaderDrill")));c.HEADER_DRILL_TEXT_DEFAULT_STYLE=d;c.HEADER_DRILL_TEXT_HOVER_DEFAULT_STYLE=d.clone().Bb(new D.O(b.q("nodeHeaderDrill-hover")));
c.HEADER_DRILL_TEXT_SELECTED_DEFAULT_STYLE=d.clone().Bb(new D.O(b.q("nodeHeaderDrill-selected")));c.HEADER_HOVER_OUTER_COLOR_STYLE=e.A("-tr-outer-color");c.HEADER_HOVER_INNER_COLOR_STYLE=e.A("-tr-inner-color");c.HEADER_SELECTED_OUTER_COLOR_STYLE=f.A("-tr-outer-color");c.HEADER_SELECTED_INNER_COLOR_STYLE=f.A("-tr-inner-color")};
D.ob=function(b,c,d){this.Init(b,c,d);this.Lo=c.OV?c.OV:"n";this.Fwa=c.Tla?c.Tla:"h";this.JF=c.PV?c.PV:"c";this.P1=c.Gma?c.Gma:"c";this.Xwa=c.nma?c.nma:"s";this.cfa=c.BEa;this.m1="on"==c.CEa;this.qxa=c.Cma?c.Cma:"on";this.Tv=c.Uk};D.F.o(D.ob,D.pb,"DvtTreemapNode");D.D=D.ob.prototype;
D.D.M=function(b){if(this.Mv){this.I=this.j0();b.k(this.I);var c;this.Be()?(this.IQ=new D.G(this.J.e),this.I.k(this.IQ),this.Ku(this.IQ)):c=this.tM;if(c){var d=this.J.OZ;d.Fo=this.$h;var e=this.R-8-2,f=this.Y-4-2;0<e&&0<f&&((0,D.qb)(d,e),(0,D.rb)(d,f),d.Ef((0,D.sb)(this)),this.Z_=c=D.T.xD(d,c,this.I),(0,D.ya)(b.e)?(b=c.D(),b=this.$a+this.R-4-1-b.g):b=this.$a+4+1,(0,D.wa)(c,b,this.Ma+2+1))}else this.Xa=this.sK(this.I),this.Xa!=D.q&&(this.Wo&&"h"!=this.nj)&&(b=this.Xa.Vb(),this.bp=new D.H(this.J.e,
b.x,b.y,b.g,b.j),this.bp.na("#FFFFFF"),this.bp.ja(D.t),this.I.k(this.bp),b=this.Xa,"n"==this.nj&&this.Be()?this.J.i1.k(b):this.I.k(b));(0,D.tb)(this.I,"img");this.Wi()}};
D.D.Nb=function(b){if("off"!=this.nE&&(D.ob.u.Nb.call(this,b),this.I))if(this.Ta()){b=this.$a;var c=this.Ma+1,d=this.R-1,e=this.Y-1;(0,D.ub)()&&(c-=1);(0,D.vb)(this,this.Nf);(0,D.vb)(this,this.bu);this.bu=this.Nf=D.q;this.Nf=new D.H(this.J.e,b,c,d,e);this.Nf.ja(D.t);this.Nf.H(D.q);(0,D.wb)(this.Nf);this.I.k(this.Nf);this.bu=new D.H(this.J.e,b+1,c+1,d-2,e-2);this.bu.ja(D.t);this.bu.H(D.q);(0,D.wb)(this.bu);this.I.k(this.bu);"h"==this.nj?(this.ZI||this.wh()?(0,D.xb)(this,this.I,this.$p,"background-color:#C4DCFF;",
"HEADER_BACKGROUND_HOVER_STYLE"):((0,D.xb)(this,this.I,this.$p,"background-color:#9CACC9;","HEADER_BACKGROUND_SELECTED_STYLE"),this.Xa&&(0,D.yb)(this,this.Xa,"HEADER_TEXT_SELECTED_DEFAULT_STYLE","#003D5B")),this.Nf.La((0,D.zb)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),1),this.bu.La((0,D.zb)(this,"#FFFFFF","HEADER_SELECTED_INNER_COLOR_STYLE"),1)):(this.Nf.La((0,D.zb)(this,"#000000","NODE_SELECTED_OUTER_COLOR"),1),this.bu.La((0,D.zb)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR"),1),!(0,D.Ab)()&&
!(0,D.Bb)()&&(0,D.Cb)(this.I,D.Db),this.J.KP(this.I))}else(0,D.vb)(this,this.bu),this.bu=D.q,"h"==this.nj?(this.ZI||this.wh()?(0,D.xb)(this,this.I,this.$p,"background-color:#C4DCFF;","HEADER_BACKGROUND_HOVER_STYLE"):((0,D.xb)(this,this.I,this.$p,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),this.Xa&&(this.Rq()?(0,D.yb)(this,this.Xa,"HEADER_TEXT_DEFAULT_STYLE","#003286"):(0,D.yb)(this,this.Xa,"HEADER_TEXT_DEFAULT_STYLE","#003D5B"))),this.Nf&&(this.ZI||this.wh()?this.Nf.La((0,D.zb)(this,
"#00AEFF","HEADER_HOVER_OUTER_COLOR_STYLE"),"1"):((0,D.vb)(this,this.Nf),this.Nf=D.q))):((0,D.Fb)(this.I),this.Nf&&((0,D.vb)(this,this.Nf),this.Nf=D.q),(b=this.mf)&&b.IQ&&b.IQ.k(this.I))};
D.D.Bc=function(){if(this.I&&this.Mv){var b=(0,D.Gb)(this.J);if(!(b!=D.q&&b!=this&&!this.bD(b))){var b=[],c,d,e,f;"h"==this.nj?((0,D.xb)(this,this.I,this.$p,"background-color:#C4DCFF;","HEADER_BACKGROUND_HOVER_STYLE"),this.Nf||(d=this.$a,c=this.Ma+1,e=this.R-1,f=this.Y-1,(0,D.ub)()&&(c-=1),this.Nf=new D.H(this.J.e,d,c,e,f),this.Nf.ja(D.t),this.Nf.H(D.q),(0,D.wb)(this.Nf),this.I.k(this.Nf)),this.Ta()?this.Nf.La((0,D.zb)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),D.ob.npa):this.Nf.La((0,D.zb)(this,
"#00AEFF","HEADER_HOVER_OUTER_COLOR_STYLE"),"1"),d=this.$a+1.5+1,e=this.$a+this.R-1.5-1,c=this.Ma+this.Hl,f=this.Ma+this.Y-1.5-1,b.push(e,c,e,f,d,f,d,c),c=new D.Hb((0,D.zb)(this,"#C4DCFF","HEADER_HOVER_INNER_COLOR_STYLE"),0.8,3),this.Xa&&(this.Rq()?(0,D.yb)(this,this.Xa,"HEADER_DRILL_TEXT_HOVER_DEFAULT_STYLE","#000000"):(0,D.yb)(this,this.Xa,"HEADER_TEXT_HOVER_DEFAULT_STYLE","#000000"))):(d=this.$a+1,e=this.$a+this.R-1,c=this.Ma+1,f=this.Ma+this.Y-1,b.push(this.$a,c,e,c,e,f,d,f,d,c),c=new D.Hb((0,D.zb)(this,
"#FFFFFF","NODE_HOVER_COLOR"),1,2));d=this.J;d.xy.Jc(b);d.xy.Z(c);d.xy.Za(D.n)}}};
D.D.nc=function(){this.I&&this.Mv&&("h"==this.nj&&(this.Ta()?((0,D.xb)(this,this.I,this.$p,"background-color:#9CACC9;","HEADER_BACKGROUND_SELECTED_STYLE"),this.Nf.La((0,D.zb)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),D.ob.npa),this.Xa&&(this.Rq()?(0,D.yb)(this,this.Xa,"HEADER_DRILL_TEXT_SELECTED_DEFAULT_STYLE","#003D5B"):(0,D.yb)(this,this.Xa,"HEADER_TEXT_SELECTED_DEFAULT_STYLE","#003D5B"))):((0,D.xb)(this,this.I,this.$p,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),
this.Nf&&(this.I.removeChild(this.Nf),this.Nf=D.q),this.Xa&&(this.Rq()?(0,D.yb)(this,this.Xa,"HEADER_DRILL_TEXT_DEFAULT_STYLE","#003286"):(0,D.yb)(this,this.Xa,"HEADER_TEXT_DEFAULT_STYLE","#003D5B")))),this.J.xy.Za(D.t))};D.D.cD=function(){return"on"==this.qxa&&"h"==this.nj};D.D.QC=function(b){return!b||!b.CC()?D.ob.u.QC.call(this,b):new D.M(this.$a,this.Ma,this.R,this.Y)};
D.D.wg=function(b){var c;if(b.type==D.Ib)return D.ob.u.wg.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;if(38==c&&b.altKey||221==c)(c=this.mf)&&c.getId()!=this.J.Pa.getId()?(b=c,(0,D.Kb)(c)):b=this;else if(40==c&&b.altKey||219==c)b=(b=this.xS)?b:this.Be()?(0,D.Lb)(this.J,this.ib()):this;else{var d=(0,D.Gb)(this.J),e=0;if(d)if(this==d)e=0;else{c=this.mf;for(e=1;d!=c;)e++,c=c.mf}else{for(d=this;d.mf;)d=d.mf;e=(0,D.Mb)(this)}c=(0,D.Nb)(this,d,e);b=(0,D.Ob)(this,b,c)}(0,D.Kb)(b);return b};
D.D.xe=function(){return new D.M(this.$a,this.Ma,this.R,this.Y)};D.D.Mn=function(){return this.I?this.I.oa():D.q};
D.D.fO=function(b,c,d,e){if(!(0>=d||0>=e)){this.Mv=D.n;this.wha=this.fl();this.$a=b;this.Ma=c;this.R=d?d:0;this.Y=e?e:0;this.nj=this.Be()?this.Fwa:this.Lo;this.hz||(this.nj="o");if("h"==this.nj){this.Hl=15;b=new D.Ya(this.J.e,this.hz);b.Ef((0,D.sb)(this));(0,D.yb)(this,b,"HEADER_TEXT_DEFAULT_STYLE","#003D5B");b=D.Pb.Ni(b).j;this.Hl=window.Math.max(this.Hl,b);this.cD()&&(this.Hl=window.Math.max(this.Hl,15));b=this.$a;c=this.Ma+this.Hl;d=this.R;e=this.Y-this.Hl;if(0<=d&&0<=e)return new D.M(b,c,d,e);
this.nj=D.q}return new D.M(this.$a,this.Ma,this.R,this.Y)}};D.D.contains=function(b,c){return b>=this.$a&&b<=this.$a+this.R&&c>=this.Ma&&c<=this.Ma+this.Y};D.D.fl=function(){var b=D.U.kd(this.Fg),c=D.U.jd(this.Fg),d=D.U.gd(this.Fg);return[this.$a,this.Ma,this.R,this.Y,b,c,d,this.Be()?0:window.Math.random()]};
D.D.vo=function(b){this.fO(b[0],b[1],b[2],b[3]);this.Fg=D.U.Ww(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));this.I&&((0,D.Qb)(this.I,this.$a,this.Ma,this.R,this.Y),this.$p&&(0,D.Qb)(this.$p,this.$a+1,this.Ma+1,this.R-2,this.Y-2),("h"!=this.nj||this.m1)&&this.I.H(this.ZD()),this.Ta()&&this.Nb(D.t),(0,D.vb)(this,this.Fv),(0,D.vb)(this,this.CM),this.CM=this.Fv=D.q,(0,D.Rb)(this),this.tM?((0,D.vb)(this,this.Z_),this.Z_=D.q):((0,D.vb)(this,this.bp),this.bp=D.q,this.Xa&&this.Xa.getParent().removeChild(this.Xa),
this.Xa=this.sK(this.I)))};D.Tb=function(b){if(b.wha){var c=new D.Sb(b.J.e,b,0.3);(0,D.P)(c.S,"typeNumberArray",b,b.fl,b.vo,b.fl());b.vo(b.wha);return c}return D.q};D.ob.prototype.Pf=function(b,c){return 0==(0,D.Mb)(this)||c.Mv&&0<c.R&&0<c.Y?D.ob.u.Pf.call(this,b,c):this.Og(b)};
D.ob.prototype.j0=function(){var b=this.J.e,c;if("h"==this.nj)c=new D.H(b,this.$a,this.Ma,this.R,this.Y),this.$p=new D.H(b,this.$a+1,this.Ma+1,this.R-2,this.Y-2),(0,D.xb)(this,c,this.$p,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),this.$p.ja(D.t),c.k(this.$p),this.Tv&&(this.te=(0,D.Ub)(this,c));else{var d=this.ZD();c=new D.H(b,this.$a,this.Ma,this.R,this.Y);if((1E3>this.J.Al||!(0,D.Vb)())&&2<=this.R&&2<=this.Y){new D.Hb((0,D.zb)(this,"#FFFFFF","LEAF_NODE_TOP_BORDER_COLOR_STYLE"),
0.3);new D.Hb((0,D.zb)(this,"#000000","LEAF_NODE_BOTTOM_BORDER_COLOR_STYLE"),0.3);this.Wo&&new D.Hb(this.Fg,0.15);var e=this.Fb(),f=(0,D.zb)(this,"#FFFFFF","LEAF_NODE_TOP_BORDER_COLOR_STYLE"),f=D.U.NH(f,e,0.7),g=(0,D.zb)(this,"#000000","LEAF_NODE_BOTTOM_BORDER_COLOR_STYLE"),g=D.U.NH(g,e,0.7),e=window.Math.min(this.R,this.Y);4<=e?(c.na(g),this.CM=new D.H(b,this.$a,this.Ma,this.R-1,this.Y-1),this.CM.na(f),this.CM.ja(D.t),c.k(this.CM),this.Fv=new D.H(b,this.$a+1,this.Ma+1,this.R-2,this.Y-2),this.Fv.H(d),
this.Fv.ja(D.t),c.k(this.Fv)):2<=e?(c.na(g),this.Fv=new D.H(b,this.$a,this.Ma,this.R-1,this.Y-1),this.Fv.H(d),this.Fv.ja(D.t),c.k(this.Fv)):c.H(d)}else c.H(d)}this.J.Va().la(c,this);this.J.D2!=D.q&&"off"!=this.nE?c.Bg(D.n):c.setCursor("default");c.zIndex=this.jU;return c};
D.Ub=function(b,c){if("h"!=b.nj||!b.cD())return D.q;var d=D.q,e=b.$a,f=b.$a+b.R-1,g=b.Ma+1,h=b.Ma+b.Hl;if(12<f-e-2){if(b.Tv){var d=b.J.e,j=b.J.oh,m=new D.Wb(d,j.restoreUp,0,0,12,12),o=new D.Wb(d,j.restoreOver,0,0,12,12),j=new D.Wb(d,j.restoreDown,0,0,12,12);(0,D.Xb)(m);(0,D.Xb)(o);(0,D.Xb)(j);d=new D.Yb(d,m,o,j);d.U(D.Ib,b.jca,D.t,b)}else d=b.J.e,j=b.J.oh,m=new D.Wb(d,j.maximizeUp,0,0,12,12),o=new D.Wb(d,j.maximizeOver,0,0,12,12),j=new D.Wb(d,j.maximizeDown,0,0,12,12),(0,D.Xb)(m),(0,D.Xb)(o),(0,D.Xb)(j),
d=new D.Yb(d,m,o,j),d.U(D.Ib,b.ica,D.t,b);e=(0,D.ya)(c.e)?e+1:f-12-1;(0,D.wa)(d,e,(h+g-12)/2);c.k(d);(0,D.Vb)()&&(g=new D.H(c.e,-2,-2,16,16),(0,D.Xb)(g),d.k(g));"true"==b.J.oh.alta?b.J.Va().la(d,b):(g=b.Tv?b.J.oh.restore:b.J.oh.isolate,b.J.Va().la(d,new D.Zb(b,b.getId(),g)))}return d};D.Rb=function(b){b.te&&((0,D.vb)(b,b.te),b.te=D.q)};
D.ob.prototype.sK=function(b){var c=(0,D.ya)(b.e);if(!this.hz||!b||!this.nj||"o"==this.nj)return D.q;var d=this.Y;if((0,D.sb)(this)>d)return D.q;var e="n"==this.nj?this.JF:this.Xwa;c&&("s"==e?e="e":"e"==e&&(e="s"));var f=this.R-6,g=0;this.cD()&&(g=13,f="c"==e?f-2*g:f-g);if(0>=f)return D.q;var h=new D.Ya(this.J.e,this.hz);h.Ef((0,D.sb)(this));"s"==e?(c?h.fa(this.$a+4+g):h.fa(this.$a+4),h.Mk()):"c"==e?(h.fa(this.$a+this.R/2),h.Af()):"e"==e&&(c?h.fa(this.$a+this.R-4):h.fa(this.$a+this.R-4-g),h.Gi());
"n"==this.nj?(d=this.Y-4,"t"==this.P1?(h.ra(this.Ma+2),h.ip()):"c"==this.P1?(h.ra(this.Ma+this.Y/2),h.Pe()):"b"==this.P1&&(h.ra(this.Ma+this.Y-2),h.ww()),(0,D.$b)(this,h)):"h"==this.nj&&(c=(0,D.ub)()?1:0,h.ra(this.Ma+1+this.Hl/2+c),h.Pe(),(0,D.yb)(this,h,"HEADER_TEXT_DEFAULT_STYLE","#003D5B"));if(h!=D.q)return"h"==this.nj&&this.Rq()?((0,D.yb)(this,h,"HEADER_DRILL_TEXT_DEFAULT_STYLE","#003286"),h.setCursor("pointer"),c=new D.Zb(this,this.getId(),D.q,this.Bf(),this.uj()),c.E8(D.n),this.J.Va().la(h,
c)):h.ja(D.t),D.Pb.Tb(h,f,d,b)?h:D.q};D.xb=function(b,c,d,e,f){var g=new D.O(e);g.Bb(b.J.An[f]);e=g.A("background-color");g=g.A("border-color");b.m1&&"HEADER_BACKGROUND_STYLE"==f?(b=b.Fb(),d.na(b),g=D.U.NH(g,b,0.5),c.na(g)):(c.na(g),d.na(e))};D.yb=function(b,c,d,e){b.m1&&"HEADER_TEXT_DEFAULT_STYLE"==d?c.na((0,D.ac)(b)):c.na(e);e=[];1>=(0,D.Mb)(b)&&b.Be()&&e.push(new D.O("font-weight:bold;"));e.push(b.J.An[d]);b.cfa&&e.push(b.cfa);c.Ga((0,D.bc)(e))};
D.ob.prototype.Pw=function(){this.te||(this.te=(0,D.Ub)(this,this.I));D.ob.u.Pw.call(this)};D.ob.prototype.Oq=function(){this.Tv!==D.n&&(0,D.Rb)(this);D.ob.u.Oq.call(this)};D.vb=function(b,c){c&&b.I.removeChild(c)};D.D=D.ob.prototype;D.D.ica=function(){this.Tv=D.n;this.nc();var b=this.J,c=b.Va().Re();c&&c.ne();b.Xc.push(this);b.Ya(new D.cc(this.getId()));b.oS=D.n;b.po(new D.M(0,0,b.rb,b.Lb));b.oS=D.t;c=this.Ia();b.K1.k(c);(0,D.dc)(b,this);(0,D.Rb)(this);this.Wi()};
D.D.jca=function(){this.Tv=D.t;this.nc();var b=this.J,c=b.Xc.pop(),d=b.Va().Re();d&&d.ne();d=c.getId();b.BL=d;b.Ya(new D.cc);b.oS=D.n;b.po(new D.M(0,0,b.rb,b.Lb));b.oS=D.t;(0,D.dc)(b,c);(0,D.Rb)(this);this.Wi()};D.D.Bf=function(b,c,d){return b&&b instanceof D.Yb?D.q:D.ob.u.Bf.call(this,b,c,d)};D.D.uj=function(b){return b&&b instanceof D.Yb?D.q:D.ob.u.uj.call(this,b)};D.D.he=function(b){return b&&b instanceof D.Yb?this.Tv?this.J.oh.restore:this.J.oh.isolate:D.q};
D.D.Qf=function(){var b=[];"off"!=this.nE&&b.push((0,D.ec)(this.ad,this.Ta()?"STATE_SELECTED":"STATE_UNSELECTED"));this.Tv&&b.push((0,D.ec)(this.ad,"STATE_ISOLATED"));return(0,D.gc)(this.ny,b,this.ad)};D.D.Wi=function(){!(0,D.hc)()&&this.I&&(0,D.ic)(this.I,"label",this.Qf())};
D.mb=function(){this.Init()};D.F.o(D.mb,D.F,"DvtBaseTreemapLayout");D.mb.prototype.Init=function(){this.jU=0};D.mb.prototype.Rn=(0,D.v)();D.nb=function(b,c,d,e,f,g,h){c.jU=b.jU;b.jU++;if(!h||!c.Be()){b=b.r6(c.J,(0,D.Mb)(c));h=window.Math.round(d+b);var j=window.Math.round(e+b);if(c=c.fO(h,j,window.Math.round(d+f-b)-h,window.Math.round(e+g-b)-j))return c}return new D.M(d,e,f,g)};D.mb.prototype.r6=function(b,c){var d=b.Ewa;return"o"==d?1==c&&2<=b.hq?3:0:"a"==d?c<b.hq?3:0:0};
D.nc=function(){this.Init()};D.F.o(D.nc,D.mb,"DvtSquarifyingLayout");D.nc.prototype.Rn=function(b,c,d,e,f,g,h){this.Kf(c,d,e,f,g,h?D.t:D.n)};D.nc.prototype.Kf=function(b,c,d,e,f,g){c=(0,D.nb)(this,b,c,d,e,f,g);b=b.ib();if(b!=D.q&&0<b.length){d=b;f=c.g*c.j;for(e=e=g=0;e<d.length;e++)g+=0<d[e].rc()?d[e].rc():0;f=0==f?0:f/g;for(e=0;e<d.length;e++)g=d[e],g.zA=g.rc()*f;b=b.slice(0).sort(function(b,c){return b.rc()-c.rc()});d=window.Math.min(c.g,c.j);(0,D.xc)(this,b,d,new D.M(c.x,c.y,c.g,c.j))}};
D.xc=function(b,c,d,e){var f=[],g=window.Infinity;if(c==D.q||0==c.length)(0,D.yc)(b,f,d,e);else for(;0<c.length;){var h=c.pop();if(0>h.zA){(0,D.yc)(b,f,d,e);break}f.push(h);var j,m=f,o=d,p=0;j=window.Infinity;for(var r=-window.Infinity,u=0;u<m.length;u++)p+=m[u].zA,j=window.Math.min(j,m[u].zA),r=window.Math.max(r,m[u].zA);m=p*p;o*=o;j=window.Math.max(o*r/m,m/(o*j));if(j>g){c.push(h);f.pop();e=(0,D.yc)(b,f,d,e);(0,D.xc)(b,c,window.Math.min(e.g,e.j),e);break}else if(0==c.length){(0,D.yc)(b,f,d,e);break}else g=
j}};D.yc=function(b,c,d,e){var f=0,g;for(g=0;g<c.length;g++)f+=c[g].zA;var h=e.x,j=e.y;if(d==e.g){f=0==d?0:f/d;for(g=0;g<c.length;g++)d=c[g].zA/f,b.Kf(c[g],h,j,d,f,D.t),h+=d;return new D.M(e.x,e.y+f,e.g,e.j-f)}d=0==d?0:f/d;for(g=0;g<c.length;g++)f=c[g].zA/d,b.Kf(c[g],h,j,d,f,D.t),j+=f;return new D.M(e.x+d,e.y,e.g-d,e.j)};
D.lb=function(b){this.Init();this.Jt=b};D.F.o(D.lb,D.mb,"DvtSliceAndDiceLayout");D.lb.prototype.Rn=function(b,c,d,e,f,g,h){this.Kf(this.Jt,b,c,d,e,f,g,h?D.t:D.n)};
D.lb.prototype.Kf=function(b,c,d,e,f,g,h,j){e=(0,D.nb)(this,d,e,f,g,h,j);d=d.ib();if(d!=D.q){f=e.x;g=e.y;h=e.g;j=e.j;var m=0,o;for(o=0;o<d.length;o++)m+=0<d[o].rc()?d[o].rc():0;"on"==this.wP&&(d=d.slice(0),d.sort(function(b,c){return c.rc()-b.rc()}));b&&(0,D.ya)(c.e)&&(d=d.slice(0).reverse());for(o=0;o<d.length;o++){var p=d[o];if(!(0>=p.rc())){var r=p.rc()/m;b?h=e.g*r:j=e.j*r;this.Kf(!b,c,p,f,g,h,j,D.t);b?f+=h:g+=j}}}};
D.cc=function(b){this.Init("treemapIsolate");this.Oa=b?b:D.q};(0,D.ta)("DvtTreemapIsolateEvent",D.cc);D.F.o(D.cc,D.oc,"DvtTreemapIsolateEvent");D.cc.TYPE="treemapIsolate";D.cc.prototype.getId=(0,D.C)("Oa");D.cc.prototype.getId=D.cc.prototype.getId;
D.jc=function(b){this.Init(b)};D.F.o(D.jc,D.kc,"DvtTreemapKeyboardHandler");D.jc.prototype.ak=function(b){var c=D.jc.u.ak.call(this,b);if(!c&&(b=b.keyCode,219==b||221==b))c=D.n;return c};
D.qc=function(b,c,d,e){D.pc.call(this,b,c,d,e)};D.F.o(D.qc,D.pc,"DvtTreemapEventManager");D.qc.prototype.am=function(b){var c=D.n;if(13==b.keyCode&&b.ctrlKey){var d=this.Re();d.cD()&&(d.Tv?d.jca():d.ica());b.preventDefault()}else c=D.qc.u.am.call(this,b);return c};D.qc.prototype.t7=(0,D.ba)(D.t);
D.vc=(0,D.v)();D.F.o(D.vc,D.wc,"DvtTreemapBundle");D.vc._defaults={COLOR:"Color",SIZE:"Size"};D.vc.prototype.ho=function(b){var c=D.vc.u.ho.call(this,b);return c?c:D.vc._defaults[b]};D.vc.prototype.nx=(0,D.ba)("DvtTreemapBundle");
D.sc=function(){this.Init({skyros:D.rc,alta:{}})};D.F.o(D.sc,D.uc,"DvtTreemapDefaults");D.rc={nodeDefaults:{header:{labelStyle:new D.O("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;")}}};
D.zc=(0,D.A)("e");D.F.o(D.zc,D.Ac,"DvtTreemapJsonUtils");D.D=D.zc.prototype;D.D.NO=(0,D.ba)("treemap");D.D.sJ=function(b){var c=D.zc.u.sJ.call(this,b),c=c+this.Ea("irk",b.isolatedNode),d=b.groupGaps;"all"==d?c+=this.Ea("gg","a"):"none"==d&&(c+=this.Ea("gg","n"));d=b.layout;"sliceAndDiceHorizontal"==d?c+=this.Ea("layout","h"):"sliceAndDiceVertical"==d&&(c+=this.Ea("layout","v"));b=b.animationOnDisplay;return c="auto"==b?c+this.Ea("adi","alphaFade"):c+this.Ea("adi",b)};
D.D.tJ=function(b,c){var d=D.zc.u.tJ.call(this,b,c);if("off"==(c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay))d+=this.Ea("ld","o");var e=c.groupLabelDisplay?c.groupLabelDisplay:b.nodeDefaults.groupLabelDisplay;"node"==e?d+=this.Ea("gld","n"):"off"==e&&(d+=this.Ea("gld","o"));e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"start"==e?d+=this.Ea("ha","s"):"end"==e&&(d+=this.Ea("ha","e"));e=c.labelValign?c.labelValign:b.nodeDefaults.labelValign;"top"==e?d+=this.Ea("va","t"):"bottom"==
e&&(d+=this.Ea("va","b"));var e=c.header,d=d+this.Ea("hls",e&&e.labelStyle?e.labelStyle:b.nodeDefaults.header.labelStyle),f=e&&e.labelHalign?e.labelHalign:b.nodeDefaults.header.labelHalign;"center"==f?d+=this.Ea("hha","c"):"end"==f&&(d+=this.Ea("hha","e"));if("off"==(e&&e.isolate?e.isolate:b.nodeDefaults.header.isolate))d+=this.Ea("hi","off");if("on"==(e&&e.useNodeColor?e.useNodeColor:b.nodeDefaults.header.useNodeColor))d+=this.Ea("unc","on");return d};
D.D.nZ=function(b){var c,d=new D.vc;c="\x3cresources"+this.Ea("legendSize",(0,D.ec)(d,"SIZE"));c+=this.Ea("legendColor",(0,D.ec)(d,"COLOR"));b=b._resources;d=(0,D.ya)(this.e);c+=this.Ea("maximizeUp",d&&b.isolateRtl?b.isolateRtl:b.isolate);c+=this.Ea("maximizeDown",d&&b.isolateDownRtl?b.isolateDownRtl:b.isolateDown);c+=this.Ea("maximizeOver",d&&b.isolateOverRtl?b.isolateOverRtl:b.isolateOver);c+=this.Ea("restoreUp",d&&b.restoreRtl?b.restoreRtl:b.restore);c+=this.Ea("restoreDown",d&&b.restoreDownRtl?
b.restoreDownRtl:b.restoreDown);c+=this.Ea("restoreOver",d&&b.restoreOverRtl?b.restoreOverRtl:b.restoreOver);c+=this.Ea("alta","true");return c+"/\x3e\n"};
D.D.uJ=function(b){var c=D.zc.u.uJ.call(this,b),d=b.animationUpdateColor;d&&(c+=this.Ea("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.Ea("node-hover","border-color: "+d));var d=b.nodeDefaults.selectedInnerColor,e=b.nodeDefaults.selectedOuterColor;(d=(d?"-tr-inner-color:"+d+";":"")+(e?"-tr-outer-color:"+e:""))&&(c+=this.Ea("node-selected",d));d=b.nodeDefaults.header.backgroundColor;e=b.nodeDefaults.header.borderColor;(d=(d?"background-color:"+d+";":"")+(e?"border-color:"+
e:""))&&(c+=this.Ea("nodeHeader",d));var e=b.nodeDefaults.header.hoverBackgroundColor,f=b.nodeDefaults.header.hoverInnerColor,d=b.nodeDefaults.header.hoverOuterColor,e=(e?"background-color:"+e+";":"")+(f?"-tr-inner-color:"+f+";":"");(e+=d?"-tr-outer-color:"+d:"")&&(c+=this.Ea("nodeHeader-hover",e));d=b.nodeDefaults.header.selectedBackgroundColor;e=b.nodeDefaults.header.selectedInnerColor;b=b.nodeDefaults.header.selectedOuterColor;d=(d?"background-color:"+d+";":"")+(e?"-tr-inner-color:"+e+";":"");
(d+=b?"-tr-outer-color:"+b:"")&&(c+=this.Ea("nodeHeader-selected",d));return c+"/\x3e\n"};
});