define(['./DvtToolkit', './DvtPanZoomCanvas', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.WE=function(b,c,d){this.Init(b,c,d)};(0,D.ta)("DvtAmxThematicMap",D.WE);D.F.o(D.WE,D.G,"DvtAmxThematicMap");D.WE.Gx=10;D.WE.prototype.Init=function(b,c,d){D.WE.u.Init.call(this,b);this.O=new D.Rv(b,c,d);this.$T=new D.G(b);this.$T.k(this.O);this.k(this.$T);this.ff=new D.Iv};D.WE.newInstance=function(b,c,d){return new D.WE(b,c,d)};D.WE.newInstance=D.WE.newInstance;D.WE.prototype.M=function(b,c,d){this.Q=this.ff.Pg(b);this.R=c;this.Y=d;c=new D.M(0,0,c,d);this.ZL(this,c);this.O.M(b,c.g,c.j)};
D.WE.prototype.render=D.WE.prototype.M;
D.WE.prototype.ZL=function(b,c){this.ya&&(b.removeChild(this.ya),this.ya=D.q);var d=new D.M(D.WE.Gx,D.WE.Gx,c.g-2*D.WE.Gx,c.j-2*D.WE.Gx),e=this.Q,f=e.legend.rendered,g=e.legend.scrolling,h=D.Ta.clone(e.legend);this.LZ(this.Q,h);if(f&&!(h.wGa&&0==h.wGa.length)){f=e.legend.position;delete h.position;h.layout.gapRatio=this.uz();h.hideAndShowBehavior="none";h.rolloverBehavior="none";h.scrolling=e.legend.scrolling;var j=(0,D.yd)(this.O.e,D.q,D.q);this.O.getId()!=D.q&&j.setId(this.O.getId()+"legend");b.k(j);
"auto"==f&&"asNeeded"!==g?f="bottom":"auto"==f&&"asNeeded"==g&&(f="end");g=(0,D.ya)(b.e);"start"==f?f=g?"right":"left":"end"==f&&(f=g?"left":"right");h.orientation="left"==f||"right"==f?"vertical":"horizontal";g="top"==f||"bottom"==f;g=j.Bz(h,g?d.g:e.layout.legendMaxSize*d.g,g?e.layout.legendMaxSize*d.j:d.j);if(0<g.g&&0<g.j)switch(j.M(h,g.g,g.j),this.ya=j,e=window.Math.ceil(e.layout.legendGap*this.uz()),(0,D.Jr)(d,f,j,g.g,g.j,e),f){case "top":this.$T.P(g.j+D.WE.Gx);case "bottom":c.j-=g.j+D.WE.Gx;
break;case "left":this.$T.G(g.g+D.WE.Gx);case "right":c.g-=g.g+D.WE.Gx}}};D.WE.prototype.uz=function(){if(this.Q.layout.gapRatio!==D.q&&!(0,window.isNaN)(this.Q.layout.gapRatio))return this.Q.layout.gapRatio;var b=window.Math.min(this.R/400,1),c=window.Math.min(this.Y/300,1);return window.Math.min(b,c)};
D.WE.prototype.LZ=function(b,c){c.title=b.legend?b.legend.title:D.q;c.sections=[];if(b&&b.legend&&b.legend.sections)for(var d=0;d<b.legend.sections.length;d++){var e=b.legend.sections[d];e&&c.sections.push({title:e.title,items:e.items,sections:e.sections})}return c};
D.Rv=function(b,c,d){this.Init(b,c,d)};(0,D.ta)("DvtThematicMap",D.Rv);D.F.o(D.Rv,D.Yd,"DvtThematicMap");
D.Rv.prototype.Init=function(b,c,d){D.Rv.u.Init.call(this,b,c,d);(0,D.ME)(this);this.Ke=[];this.Cv=[];this.Fxa=this.No=this.ic=this.ya=D.q;this.dQ=D.t;this.gF=[];this.DF={};this.pT=D.t;this.rR={};this.Q_={};this.pm=[];this.WZ=new D.G(this.e);this.uK=new D.G(this.e);this.yv=new D.G(this.e);this.Lt=new D.G(this.e);this.$R=D.t;this.fC=this.lz=D.n;this.q2=6;this.Qr=D.n;this.AG={};this.vl=16777215;this.ff=new D.Iv;this.Hf=D.t};D.Rv.newInstance=function(b,c,d){return new D.Rv(b,c,d)};
D.Rv.prototype.Wd=function(b){D.Rv.u.Wd.call(this,b);(0,D.Ti)()||(this.Q.animationOnDisplay="none",this.Q.animationOnMapChange="none",this.Q.animationOnDrill="none");this.Q.skin||(this.Q.skin="alta");(new D.rv(this)).parse(this.Q)};D.Vu=function(b,c){for(var d=0;d<b.Ke.length;d++)if(b.Ke[d].Gf==c)return b.Ke[d]};D.D=D.Rv.prototype;D.D.Wn=function(b){this.it=(0,window.parseFloat)(b)};D.D.Qa=(0,D.C)("it");
D.D.zW=function(b){b=(0,window.parseInt)(b);var c=this.vl;if(1==b||3==b||5==b||7==b)c&=-17,this.fC=D.t;if(2==b||3==b||6==b||7==b)c&=-4098,this.lz=D.t;if(4==b||5==b||6==b||7==b)c&=-257;this.vl=c};D.D.wW=function(b){this.Bk=b;this.Ca.wW(b)};
D.D.lJ=function(){D.Rv.u.lJ.call(this);!this.By&&this.Nya&&(this.Ke=[],this.gF=[],this.DF={},this.rR={},this.Q_={},this.pm=[],this.removeChild(this.ic),this.Fxa=this.No=this.ya=this.ic=D.q,this.vl=16777215,this.fC=this.lz=D.n,this.aG=this.Mb,this.WZ=new D.G(this.e),this.uK=new D.G(this.e),this.yv=new D.G(this.e),this.Lt=new D.G(this.e),(0,D.ME)(this),this.Ca.sc())};D.ME=function(b){b.Ca=new D.Jv(b.e,b.Ya,b);b.Ca.nf(b);(0,D.Vb)()?b.M1=D.q:(b.M1=new D.Ov(b,b.Ca),(0,D.Ch)(b.Ca,b.M1))};
D.Rv.prototype.Apa=function(b){(0,D.ya)(this.e)||(b=this.R-5-b.getWidth(),this.ic.G(b))};
D.Rv.prototype.ZL=function(){if(this.No){this.ic&&(this.ic.W(),this.removeChild(this.ic));var b="true"==this.No.q("disclosed"),c="fixed"==this.No.q("display")||(0,D.sy)();if(!c||b){var d=this.No.q("maxWidth"),e=d.indexOf("%"),d=-1!=e?(0,window.parseFloat)(d.substring(0,e))/100*this.R:(0,window.parseFloat)(d),e=this.Y-10;if("alta"==this.Eb)this.ic=new D.xd(this.e,D.q,this,"pd"),this.ic.U("dvtPanelDrawerEvent",this.B$,D.t,this),this.ic.Vl(d),this.ic.GD(e),this.ic.Sv=c,(0,D.ya)(this.e)?(this.ic.Gr="right",
this.ic.G(0)):this.ic.G(this.R);else{this.ic=new D.wl(this.e,d,e,f,(0,D.ce)(this),this.vs(),b,c);this.ic.U("dvtCollapsiblePanelEvent",this.B$,D.t,this);this.ic.U("dvtResizeEvent",this.Apa,D.t,this);var d=this.No.q("expandTooltip"),e=this.No.q("collapseTooltip"),f=(0,D.ya)(this.e)?"col_northwest":"col_northeast",f=this.ic;f.jB=d;f.UA=e}this.ya=new D.DvtCommonLegend(this.e,this.ic.F6(),this.ic.E6(),(0,D.ce)(this),this.Eb);this.ya.HW(this.No);this.k(this.ic);this.k(this.ya);this.ya.M();var g;if("alta"==
this.Eb){f=this.ya.D();(0,D.Ai)(this.ic,f.j);this.removeChild(this.ya);var f=new D.Wb(this.e,(0,D.ce)(this).legendEna,0,0,24,24),d=new D.Wb(this.e,(0,D.ce)(this).legendOvr,0,0,24,24),e=new D.Wb(this.e,(0,D.ce)(this).legendDwn,0,0,24,24),h=(0,D.ec)(this.hd(),"LEGEND");(0,D.zd)(this.ic,this.ya,f,d,e,h,"legend");this.ic.Pm();b&&this.ic.Ie(D.n,D.n)}else g=this.ic,b=this.ya,g.Rc.k(b),b.U("dvtResizeEvent",g.RX,D.t,g),f=g.Rc.D(),b=f.g+10,f=f.j+10,g.Y=f,g.R=b,g.eb?(g.eb.ek((0,D.bE)(g,b,f)),b="col_northwest"==
g.Bi||"col_southwest"==g.Bi,g.ig&&b&&g.ig.G(g.R)):(b=new D.Ra(g.e,(0,D.bE)(g,b,f)),f=g.F.borderAlpha,b.na(g.qv,g.Kj),b.La(g.Lp,f),g.eb=b,g.Fa(g.eb,0),g.Sv||(g.ig=D.Rm.y5(g.e,25,g.F,D.t),g.ig.C(g.F.borderAlpha),g.k(g.ig),g.Mj=g.isCollapsed()?D.W.BU(g.e,g.sl,25,g.F,D.t):D.W.zU(g.e,g.sl,25,g.F,D.t),g.ig.k(g.Mj),"col_northwest"==g.Bi||"col_southwest"==g.Bi||(g.ig.P(25),g.ig.Ti(-window.Math.PI)),(0,D.ya)(g.e)&&g.ig.G(g.R),(0,D.Vb)()?g.Mj.U(D.Jt.Xd,g.hE,D.t,g):(g.Mj.U(D.Ib,g.hE,D.t,g),g.Mj.U(D.So,g.pY,
D.t,g),g.Mj.U(D.To,g.oY,D.t,g)))),g.KQ&&(0,D.cE)(g,D.t),g=this.ic.D(),b=(0,D.ya)(this.e)?5:this.R-5-g.g-g.x,(0,D.wa)(this.ic,b,5),g.g+=5;if(this.hS=c)g||(g=this.ic.D()),this.mL=g.g}}};
D.Rv.prototype.ti=function(){D.Rv.u.ti.call(this);var b=new D.G(this.e),c=new D.G(this.e);this.Mb=this.ca;this.Mb.k(b);this.Mb.$.k(c);this.Lh(b,c);if(this.Sj){(this.Qc=this.Mb.Qc)&&this.Mb.k(this.Qc);(0,D.NE)(this);var d=new D.M(0,0,this.R,this.Y);if(!this.Hf&&!this.aG)D.ad.isSupported(this.UZ)&&(this.nb=D.ad.xH(this.e,this.UZ,this.Mb,d,this.it));else{var e=D.q;if(this.dQ&&!this.By)e=this.sca;else if(this.Sj&&this.Sj.Gf!=this.jya&&(e=this.Sj.Dq(),!e)){var f=this.Sj.$g,g;for(g in f)if(f[g].Dq()){e=
f[g].Dq();break}}e&&D.ad.isSupported(e)?(this.nb=D.ad.rz(this.e,e,this.aG,this.Mb,d,this.it))&&this.k(this.aG):this.Mb.$.removeChild(this.VE)}this.nb&&(this.Qc&&this.k(this.Qc),this.Ca.sc(),this.Ca.Fs(this),this.nb.qd(this.Dp,this),this.nb.play());this.Nya=b;this.VE=c;this.Sj&&(this.jya=this.Sj.Gf);this.Hf=D.n}};
D.Rv.prototype.Lh=function(b,c){this.ZL();c.k(this.WZ);c.k(this.uK);this.Qr?b.k(this.yv):c.k(this.yv);b.k(this.Lt);var d=this.Mb.$.ma();this.P4=D.t;for(var e=0;e<this.Ke.length;e++){var f=this.Ke[e];if(!this.P4&&f instanceof D.Mu||!(f instanceof D.Mu))f.M(d),!this.P4&&f instanceof D.Mu&&(this.P4=D.n,this.Sj=f)}this.Sj&&(d=(0,D.Nv)(this),0==d.length&&(d=(0,D.Pv)(this)),this.M1&&(d=d[0])&&D.Jv.u.Xq.call(this.Ca,d),this.Mb.Js(D.q),this.Mb.Nu(D.q),this.Mb.wr=D.n,this.Mb.Jj=D.n,!this.dQ&&!this.By&&this.C1!=
D.q?((0,D.Fe)(this.Mb,this.C1),(0,D.Ae)(this.Mb,this.ixa,this.jxa)):this.$R?(0,D.OE)(this):this.Mb.ao(D.q,this.Sj.MC()),(0,D.PE)(this),d=this.Mb.hp,e=this.Sj.MC(),f=this.Mb.rc(),f.g=this.hS?f.g-this.mL:f.g,d=window.Math.min((f.g-2*d)/e.g,(f.j-2*d)/e.j),this.Mb.Js(d),this.Mb.Nu(d*(this.lz?this.q2:1)),this.Mb.wr=this.lz,this.Mb.Jj=this.fC)};D.gw=function(b){(0,D.PE)(b);b.$R?(0,D.OE)(b):b.C1==D.q&&b.Mb.ao(D.q,b.Sj.MC())};D.Rv.prototype.J8=(0,D.A)("vG");D.Rv.prototype.kA=function(){return new D.Qu(this)};
D.QE=function(b,c){var d=new D.sd;d.translate(c.Ab,c.wb);b.Qr&&b.yv.qa(d);b.Lt.qa(d)};D.Rv.prototype.B$=function(b){var c=new D.Oc;(0,D.Pc)(c,D.DvtCommonLegend.iaa,"show"==b.Mi());this.Ya(c)};D.RE=function(b,c,d){if(c=c.S){var e=b.Mb.$,f=(0,D.ue)(c,e,e.ma);d&&(b.Jda=e.ma(),(0,D.P)(c,"typeMatrix",b,b.Yva,b.Pza,f));d=new D.sd(1,0,0,1,f.Ab,f.wb);b.Qr&&(0,D.P)(c,"typeMatrix",b.yv,b.yv.ma,b.yv.qa,d);(0,D.P)(c,"typeMatrix",b.Lt,b.Lt.ma,b.Lt.qa,d)}};
D.Rv.prototype.eg=function(b){switch(b.Mi()){case "adjustPanConstraints":if(this.fC){var c=b.Ny;b=this.Mb.hp;var d=this.Mb.rc();b=new D.M(b,b,d.g-2*b,d.j-2*b);var e=this.Sj.MC(),f=e.x*c,d=e.y*c,g=e.g*c,c=e.j*c;g>b.g?(this.Mb.kq=b.x+b.g-(f+g),this.Mb.iq=b.x-f):(e=0,this.hS&&((0,D.ya)(this.e)?e=this.J1?2*-this.mL:-this.mL:this.J1||(e=this.mL)),f=(b.x+b.g-e)/2-(f+g/2),this.Mb.kq=f,this.Mb.iq=f);c>b.j?(this.Mb.lq=b.y+b.j-(d+c),this.Mb.jq=b.y-d):(b=(b.y+b.j)/2-(d+c/2),this.Mb.lq=b,this.Mb.jq=b)}break;
case "zooming":case "elasticAnimBegin":(0,D.RE)(this,b,D.n);break;case "zoomed":if(b.Ny!=D.q){d=this.Mb.$.ma();(0,D.Pc)(b,"panX",d.Ab);(0,D.Pc)(b,"panY",d.wb);b.S=D.q;this.Ya(b);(0,D.QE)(this,d);for(c=0;c<this.Ke.length;c++)this.Ke[c].eg(b,d)}break;case "zoomAndCenter":(0,D.Mv)(this);break;case "zoomToFitBegin":this.J1=D.n;this.hS&&this.Mb.fk(this.R-this.mL,this.Y,D.n);break;case "zoomToFitEnd":this.J1=D.t,this.hS&&this.Mb.fk(this.R,this.Y,D.n),this.Ya(new D.Le)}};
D.Rv.prototype.Ws=function(b){var c=b.Mi();if("elasticAnimBegin"==c)(0,D.RE)(this,b,D.t);else if("panned"==c&&b.Vga!=D.q){var d=this.Mb.$.ma();(0,D.Pc)(b,"zoom",this.Mb.Hc());(0,D.Pc)(b,"panX",d.Ab);(0,D.Pc)(b,"panY",d.wb);b.S=D.q;this.Ya(b);(0,D.QE)(this,d);for(b=0;b<this.Ke.length;b++)this.Ke[b].Ws(d)}this.ic&&("alta"==this.Eb?"dragPanBegin"===c?this.ic.ja(D.t):"dragPanEnd"===c&&this.ic.ja(D.n):(d=this.vs(),b=this.ic.eb.mc().clone(),"dragPanBegin"===c?(this.ya.C(d.backgroundDragAlpha),b.C(d.borderDragAlpha),
this.ic.eb.Z(b),this.ic.ig&&this.ic.ig.C(d.borderDragAlpha),this.ic.ja(D.t)):"dragPanEnd"===c&&(this.ya.C(1),b.C(d.borderAlpha),this.ic.eb.Z(b),this.ic.ig&&this.ic.ig.C(d.borderAlpha),this.ic.ja(D.n))))};D.Rv.prototype.ox=function(){return"none"==this.Bk&&!this.lz&&(!this.fC||"alta"==this.Eb)?"hidden":D.Rv.u.ox.call(this)};D.Rv.prototype.OO=function(){var b=this.ox();return"hidden"!=b?new D.Tv(this.e,this,"initCollapsed"==b?1:2):D.q};
D.PE=function(b){b.pT=D.n;for(var c=0;c<b.Ke.length;c++){var d=b.Ke[c].Gf;d in b.DF&&(b.AG[d]=b.DF[d][1],b.Lj=d,b.uv=b.DF[d][0],b.HU())}b.pT=D.t};
D.Rv.prototype.s8=function(){(0,D.NE)(this);for(var b=[],c=[],d=this.Ke.length-1;-1<d;d--)this.Ke[d].Gf==this.Sj.Gf?this.Ke[d].reset(c):this.Ke[d].reset(b);for(d=0;d<b.length;d++)if(b[d]){var e=b[d].getParent();e&&e.removeChild(b[d])}for(d=0;d<c.length;d++)c[d]&&c[d].C(1);this.gF=[];b=new D.Ge(this.e,0.3);this.Mb.ao(b);b.play();this.pm=[];this.Qc&&"none"!=this.Bk&&((0,D.Uv)(this.Qc,D.t),(0,D.Vv)(this.Qc,D.t))};
D.OE=function(b){var c=b.uK.D(),d=b.yv.D();if(b.Qr){var e=b.Mb.$.ma();d.g/=e.Kc;d.j/=e.Je;d.x/=e.Kc;d.y/=e.Je}c=(0,D.Xa)(c,d);(0,D.NE)(b);(0,D.Ti)()&&(b.nb=new D.Ge(b.e,0.3));0<c.g&&0<c.j?b.Mb.ao(b.nb,c):b.Mb.ao(b.nb,b.Sj.MC());b.nb&&b.nb.play()};D.Rv.prototype.bH=function(b){var c=new D.Ge(this.e,0.3);this.Mb.ao(c,b);c.play()};
D.Mv=function(b){if(b.uv){var c=(0,D.Vu)(b,b.Lj).tj(b.uv);if(c&&(c=c.Kb)){for(var c=c.getSelection(),d=0;d<c.length;d++)c[d]=c[d].Ia();if(0<c.length){for(var e=c[0].D(),d=1;d<c.length;d++)e=(0,D.Xa)(e,c[d].D());b.bH(e)}}}};D.SE=function(b,c){var d=D.Uu.oDa(b.Le,c);return(0,D.Vu)(b,d)};D.Ev=function(b,c){var d=D.Uu.Pka(b.Le,c);return(0,D.Vu)(b,d)};D.Nv=function(b){var c=[];if(b.Sj)for(var d=0;d<b.Ke.length;d++){var e=b.Ke[d].$g,f;for(f in e)c=b.Sj.Gf==b.Ke[d].Gf?c.concat((0,D.xv)(e[f])):c.concat((0,D.yv)(e[f]))}return c};
D.Pv=function(b){var c=[];if(b.Sj)for(var d=0;d<b.Ke.length;d++){var e=b.Ke[d].$g;if(b.Sj.Gf==b.Ke[d].Gf||!(b.Ke[d]instanceof D.Mu))for(var f in e)c=c.concat(e[f].Fh)}return c};D.Rv.prototype.Pza=function(b){this.Jda=b;if(this.Qr){for(var c=(0,D.Pv)(this),d=0;d<c.length;d++)c[d].eg(b);c=this.Lt.za();for(d=0;d<c;d++)for(var e=this.Lt.da(d),f=e.za(),g=0;g<f;g++){var h=e.da(g);h instanceof D.gv&&h.update(b)}}};D.Rv.prototype.Yva=(0,D.C)("Jda");
D.Rv.prototype.HU=function(){(0,D.NE)(this);var b=(0,D.Ev)(this,this.Lj),c=(0,D.Vu)(this,this.Lj),d=[];if(b){this.rR[this.Lj]=this.uv;var e=this.AG[this.Lj];!this.pT&&"single"==this.Bk&&(this.pm.pop(),c.reset(d,e),b.reset(this.Cv));for(var f=[],g=0;g<e.length;g++){var h=e[g],j=(0,D.Bv)(c,h);f.push(j[0]);for(var m=0;m<j.length;m++)this.Q_[j[m]]=e[g];b.L5(j,d);if(j=c.tj(this.uv)){for(var m=h,o=this.Cv,p=0;p<j.hc.length;p++)if(j.hc[p].bl==m){j.hc[p].pI(D.n);j.pm.push(m);o.push(j.hc[p].Ia());if(p=j.hc[p].vh())o.push(p),
(p=p.Nj)&&o.push(p);break}for(p=0;p<j.Fh.length;p++)if(j.Fh[p].bl==m){o.push(j.Fh[p].Ia());break}}this.pm.push(h)}(0,D.TE)(this,this.Cv,d,D.t);(0,D.UE)(this,b.Gf);this.Lj=b.Gf;this.AG[this.Lj]=f}};
D.Rv.prototype.N5=function(){(0,D.NE)(this);for(var b=(0,D.Vu)(this,this.Lj),c=(0,D.SE)(this,this.Lj),d=[],e=[],f=this.AG[this.Lj],g=0;g<f.length;g++){var h=this.Q_[f[g]];e.push(h);if(-1!=D.$c.Ha(this.pm,h)){b.tO((0,D.Bv)(c,h),this.Cv);for(var j=c.tj(this.rR[c.Gf]),m=h,o=d,p=0;p<j.hc.length;p++)if(j.hc[p].bl==m){j.pm.splice(D.$c.Ha(j.pm,m),1);j.hc[p].pI(D.t);var r=j.hc[p].Ia();j.xk.k(r);o.push(r);if(p=j.hc[p].vh())p.update(j.pG),o.push(p),o.push(p.Nj);break}for(p=0;p<j.Fh.length;p++)if(j.Fh[p].bl==
m){r=j.Fh[p].Ia();j.Fr.k(r);o.push(r);break}h=D.$c.Ha(this.pm,h);-1!=h&&this.pm.splice(h,1)}}(0,D.TE)(this,this.Cv,d,D.n);this.Lj=c.Gf;this.uv=this.rR[this.Lj];this.AG[this.Lj]=e;(0,D.UE)(this,this.Lj)};D.NE=function(b){b.nb&&(b.nb.stop(D.n),b.nb=D.q)};
D.TE=function(b,c,d,e){b.Mb.$.ma();if(b.Gva&&!b.pT){var f=new D.Ge(b.e,0.3);(0,D.Ti)()||(f=D.q);e?b.Mb.ao(f):(0,D.Mv)(b);f&&f.play()}(0,D.NE)(b);b.nb=D.ad.rz(b.e,b.Pta,c,d,D.q,0.5);(0,D.Ti)()||(b.nb=D.q);b.nb?(b.Ca.sc(),b.Ca.Fs(b),b.nb.qd(b.pqa,b),b.nb.play()):(0,D.VE)(b)};
D.Rv.prototype.Ya=function(b){var c=b.Da();if("selection"==c)if(this.uv){this.c4=b.getSelection();for(var c=this.AG,d=this.Lj,e=this.c4,f=[],g=(0,D.Vu)(this,this.Lj).tj(this.uv).hc,h=0;h<e.length;h++)for(var j=0;j<g.length;j++)if(g[j].getId()==e[h]){f.push(g[j].bl);break}c[d]=f;(0,D.UE)(this,this.Lj);(0,D.Pc)(b,"clientId",this.uv);this.JQ&&!(this.JQ instanceof D.va)&&(this.Jja=this.JQ)}else(0,D.UE)(this,D.q),this.Jja=D.q;else c==D.pv.hba?((0,D.Pc)(b,"clientId",this.uR),this.gF="multiple"==this.Bk?
this.gF.concat(this.c4):this.c4,c=b.Eva,c==D.pv.Toa&&this.N5(),c==D.pv.nX?this.HU():c==D.pv.Aqa&&this.s8(),b.Ie(this.gF)):("showPopup"==c||"hidePopup"==c)&&(0,D.Pc)(b,"clientId",this.uR);D.Rv.u.Ya.call(this,b)};D.UE=function(b,c){if(b.Qc&&b.Bk&&"none"!=b.Bk){var d=(0,D.Ev)(b,c),e=(0,D.SE)(b,c);d?(0,D.Uv)(b.Qc,D.n):(0,D.Uv)(b.Qc,D.t);e?(0,D.Vv)(b.Qc,D.n):(0,D.Vv)(b.Qc,D.t)}};D.Rv.prototype.W=function(){D.Rv.u.W.call(this);this.Ca&&(this.Ca.W(),this.Ca=D.q)};D.Rv.prototype.destroy=D.Rv.prototype.W;
D.Rv.prototype.Dp=function(){this.Qc&&this.Mb.k(this.Qc);this.aG&&(this.removeChild(this.aG),this.aG=D.q);this.nb=D.q;this.Ca.nf(this)};D.Rv.prototype.pqa=function(){(0,D.VE)(this);this.nb=D.q;this.Ca.nf(this)};D.VE=function(b){if(0<b.Cv.length){for(var c=0;c<b.Cv.length;c++){var d=b.Cv[c];if(d)if(d instanceof D.gv)d.reset();else if(d.wu&&d.wu())d.C(0);else{var e=d.getParent();e&&e.removeChild(d)}}b.Cv=[]}};
D.Rv.prototype.CT=function(b){this.AR("mouseover"==b.Qga?"categoryRollOver":"categoryRollOut",b.w6())};D.Rv.prototype.AR=function(b,c){var d=new D.Gh(b,c),e=[],f;for(f in this.hh)for(var g in this.hh[f])e.push(this.hh[f][g]);for(f in this.Xv)for(g in this.Xv[f])e.push(this.Xv[f][g]);f=this.ya.n1;for(var h in f)g=new D.hw(f[h].$d(),h),e.push(g);(0,D.Ih)(d,e,0.1)};D.Rv.prototype.Ji=function(){this.jx||(this.jx=new D.bw(this));return this.jx};D.Rv.prototype.getAutomation=D.Rv.prototype.Ji;
D.Iv=function(){this.Init({fusion:D.Fv,skyros:D.Gv,alta:D.Hv})};D.F.o(D.Iv,D.db,"DvtThematicMapDefaults");
D.Fv={skin:D.q,animationDuration:500,animationOnDisplay:"none",animationOnDrill:"none",animationOnMapChange:"none",controlPanelBehavior:"hidden",drilling:"off",initialZooming:"none",maintainDrill:"off",markerZoomBehavior:"fixed",panning:"none",tooltipDisplay:"auto",zooming:"none",styleDefaults:{areaStyle:"background-color:#B8CDEC;border-color:#FFFFFF;",dataAreaDefaults:{borderColor:"#FFFFFF",drilledInnerColor:"#FFFFFF",drilledOuterColor:"#000000",hoverColor:"#FFFFFF",opacity:1,selectedInnerColor:"#FFFFFF",
selectedOuterColor:"#000000"},dataMarkerDefaults:{borderColor:"#FFFFFF",borderStyle:"solid",borderWidth:"0.5px",color:"#000000",height:8,labelStyle:"font-family:Tahoma;font-size:13pt;color:#000000",opacity:0.4,scaleX:1,scaleY:1,shape:"circle",width:8},labelStyle:"font-family:Tahoma;font-size:11pt;"},legend:{position:"auto",rendered:D.n,layout:{gapRatio:1}},layout:{gapRatio:D.q,legendMaxSize:0.3,legendGap:10},resources:{images:{},translations:{}}};D.Gv={styleDefaults:{backgroundColor:"#FFFFFF"}};
D.Hv={skin:"alta",styleDefaults:{areaStyle:"background-color:#DDDDDD;border-color:#FFFFFF;",backgroundColor:"#FFFFFF",dataAreaDefaults:{drilledOuterColor:"#0572CE"},dataMarkerDefaults:{color:"rgb(51,51,51)",labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;color:#333333',opacity:1},labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;'}};D.sv={animationOnLayerChange:"none",labelDisplay:"auto",labelType:"short"};
D.tv={animationOnDataChange:"none",selection:"none"};
D.Qv=function(b){for(var c=0;c<b.Ke.length;c++){var d=b.Ke[c].$g,e;for(e in d){var f=d[e].Ak;if(f&&f.fB)return f}}return D.q};D.Rv.prototype.yj=function(b,c,d){this.wva=D.t;return(b=(0,D.Qv)(this))?b.yj(d):D.t};D.Rv.prototype.Rk=function(b,c){var d=(0,D.Qv)(this);return d?d.Rk(b,c):D.q};

D.ov=function(b,c){this.cIa=b;this.qIa=c};D.F.o(D.ov,D.jd,"DvtThematicMapDropTarget");
D.bw=(0,D.A)("O");(0,D.ta)("DvtThematicMapAutomation",D.bw);D.F.o(D.bw,D.fb,"DvtThematicMapAutomation");
D.bw.prototype.er=function(b){b=(0,D.gb)(this.O.Ca,b);var c;if(b&&(b instanceof D.Zu||b instanceof D.$u))a:{for(var d=this.O.Ke,e=0;e<d.length;e++){var f=d[e].$g;for(c in f)if(b instanceof D.Zu)for(var g=f[c].hc,h=0;h<g.length;h++){if(g[h]===b){c=(0,D.cw)(c)+":area["+b.getId()+"]";break a}}else if(b instanceof D.$u){g=f[c].Fh;for(h=0;h<g.length;h++)if(g[h]===b){c=(0,D.cw)(c)+":marker["+b.getId()+"]";break a}}}c=D.q}else c=D.q;return c};
D.bw.prototype.Qk=function(b){var c=b.indexOf(":"),d=b.indexOf("[");b=0<c&&0<d?(b=(0,D.dw)(this,b.substring(0,c),b.substring(c+1,d),b.substring(d+1,b.length-1)))?b.Ia().oa():D.q:D.q;return b};D.bw.prototype.getDomElementForSubId=D.bw.prototype.Qk;D.bw.prototype.getData=function(b,c,d){return(b=(0,D.dw)(this,b,c,d))?(c={},c.color=b.uj(),c.tooltip=b.Bf(),d=b.vh(),c.label=d?d.Ae():D.q,c.isSelected=b.Ta(),c):D.q};D.bw.prototype.getData=D.bw.prototype.getData;
D.dw=function(b,c,d,e){b=b.O.Ke;for(var f=0;f<b.length;f++){var g=b[f].$g,h;for(h in g)if((0,D.cw)(h)==c)if("area"==d)for(var j=g[h].hc,m=0;m<j.length;m++){if(j[m].getId()===e)return j[m]}else if("marker"==d){j=g[h].Fh;for(m=0;m<j.length;m++)if(j[m].getId()===e)return j[m]}}return D.q};D.cw=function(b){var c=b.lastIndexOf(":");return 0<c?b.substring(c+1):b};
D.kv=function(b,c){this.Init(b,c)};D.F.o(D.kv,D.Ra,"DvtDrillablePath");D.D=D.kv.prototype;D.D.Init=function(b,c){D.kv.u.Init.call(this,b);this.py=this.oy=this.kR=this.jR=D.q;this.gS=D.t;this.Zoom=1;this.Ce=c};D.D.wu=(0,D.C)("gS");
D.D.pI=function(b){this.gS!=b&&(this.gS=b,this.wu()?(this.oy=this.Hi(),this.oy.H(D.q),this.oy.ja(D.t),this.py=this.Hi(),this.py.H(D.q),this.py.ja(D.t),b=this.getParent(),b.k(this.py),b.k(this.oy),this.oy.Z((0,D.ew)(this,this.jR,2)),this.py.Z((0,D.ew)(this,this.kR,4)),this.ja(D.t),this.Zs=D.t):(this.Qh()&&(this.xi(),this.Cg.Z((0,D.ew)(this,this.gr,1),2)),this.py.getParent().removeChild(this.py),this.oy.getParent().removeChild(this.oy),this.ja(D.n),this.C(1)))};
D.D.Nb=function(b){this.Ap!=b&&(b&&(this.Qh()?(this.JI(),this.jl=(0,D.ew)(this,this.jl,2),this.nk=(0,D.ew)(this,this.nk,6)):(this.jr=(0,D.ew)(this,this.jr,1),this.uo=(0,D.ew)(this,this.uo,4))),D.kv.u.Nb.call(this,b))};D.D.Bc=function(){this.Ta()?(this.JI(),this.jl=(0,D.ew)(this,this.jl,2),this.nk=(0,D.ew)(this,this.nk,6)):this.gr=(0,D.ew)(this,this.gr,2);D.kv.u.Bc.call(this)};
D.D.JI=function(){this.jl||(this.jl=this.gr.clone(),this.jl.ia(2),this.Ce&&(this.jl.dd=D.n));this.nk||(this.nk=this.uo.clone(),this.nk.ia(6),this.Ce&&(this.nk.dd=D.n))};D.D.nc=function(){this.Ta()&&(this.jr=(0,D.ew)(this,this.jr,1),this.uo=(0,D.ew)(this,this.uo,4));D.kv.u.nc.call(this)};D.D.Yq=function(b,c){D.kv.u.Yq.call(this,b,c);this.Ce&&(this.gr&&(this.gr.dd=D.n),this.eP&&(this.eP.dd=D.n));return this};
D.D.$q=function(b,c){D.kv.u.$q.call(this,b,c);this.Ce&&(this.jr&&(this.jr.dd=D.n),this.uo&&(this.uo.dd=D.n));return this};D.D.Ou=function(b,c){D.kv.u.Ou.call(this,b,c);this.Ce&&(this.jl&&(this.jl.dd=D.n),this.nk&&(this.nk.dd=D.n));return this};D.lv=function(b,c,d){b.jR=c;b.jR&&b.Ce&&(b.jR.dd=D.n);b.kR=d;b.kR&&b.Ce&&(b.kR.dd=D.n)};D.fw=function(b,c,d){if(!b.Ce){var e=c.mc();e&&(e=e.clone(),e.ia(d/b.Zoom),c.Z(e))}};D.ew=function(b,c,d){b.Ce||(c=c.clone(),c.ia(d/b.Zoom));return c};
D.Av=function(b,c){b.Zoom=c.Kc;b.wu()?((0,D.fw)(b,b.oy,2),(0,D.fw)(b,b.py,4)):b.Ta()?b.Qh()?((0,D.fw)(b,b.Cg,2),(0,D.fw)(b,b,6)):((0,D.fw)(b,b.Cg,1),(0,D.fw)(b,b,4)):b.Qh()?(0,D.fw)(b,b.Cg,2):(0,D.fw)(b,b,1)};
D.Uu=this.DvtBaseMapManager;D.Uu?(D.Uu.mr=D.Uu._UNPROCESSED_MAPS,D.Uu.tE=D.Uu._UNPROCESSED_PARENT_UPDATES):D.Uu={mr:[[],[],[]],tE:[[],[],[]]};"undefined"!=typeof D.DVT_ADVANCED_CLOSURE&&((0,D.ta)("DvtBaseMapManager",D.Uu),D.Uu._UNPROCESSED_MAPS=D.Uu.mr,D.Uu._UNPROCESSED_PARENT_UPDATES=D.Uu.tE);D.F.o(D.Uu,D.F,"DvtBaseMapManager");D.Uu.pE=0;D.Uu.pJ=1;D.Uu.eZ=2;D.Uu.dZ=3;D.Uu.yP=4;D.Uu.dt="__index";D.Uu.fh={};
D.Uu.Mka=function(b,c){D.Uu.xn();var d=D.Uu.fh[b][c];return d&&(d=d[D.Uu.yP])?new D.M(d[0],d[1],d[2],d[3]):D.q};D.Uu.Gka=function(b,c){D.Uu.xn();var d=D.Uu.fh[b][c];return d?d[D.Uu.dZ]:D.q};D.Uu.Hka=function(b,c){D.Uu.xn();var d=D.Uu.fh[b][c];return d?d[D.Uu.pE]:D.q};D.Uu.pla=function(b,c,d){D.Uu.xn();b=D.Uu.fh[b][c];var e;b&&(e=b[D.Uu.pE]);return e&&e[d]?e[d][1]:D.q};D.Uu.Ska=function(b,c){D.Uu.xn();var d=D.Uu.fh[b];if(d&&(d=d.cities))if(d=d[D.Uu.pJ][c])return new D.K(d[0],d[1]);return D.q};
D.Uu.Tka=function(b,c){D.Uu.xn();var d=D.Uu.fh[b];if(d&&(d=d.cities))if(d=d[D.Uu.pE][c])return d[1];return D.q};D.Uu.Fka=function(b,c,d){D.Uu.xn();var e=D.Uu.fh[b];if(e&&(e=e[c])){if((e=e[D.Uu.dZ])&&e[d])return(0,D.qv)(e[d][0]).Yc();b=D.Uu.fh[b][c][D.Uu.pJ][d];if(!b)return D.q;b=window.DvtPathUtils.CU(b);return window.DvtPathUtils.D(b).Yc()}return D.q};D.Uu.Pka=function(b,c){D.Uu.xn();var d=D.Uu.fh[b][c];return d?D.Uu.fh[b][D.Uu.dt][d.__index+1]:D.q};
D.Uu.oDa=function(b,c){D.Uu.xn();return D.Uu.fh[b][c]?D.Uu.fh[b][D.Uu.dt][D.Uu.fh[b][c].__index-1]:D.q};D.Uu.Ika=function(b,c){D.Uu.xn();return D.Uu.fh[b][c][D.Uu.pJ]};D.Uu.pDa=function(b,c,d){D.Uu.xn();return D.Uu.fh[b][c][D.Uu.pJ][d]};D.Uu.Qka=function(b,c){D.Uu.xn();var d=D.Uu.Pka(b,c);return d&&(d=D.Uu.fh[b][d][D.Uu.eZ])?d:[]};D.Uu.cKa=function(b,c){D.Uu.xn();return D.Uu.fh[b][D.Uu.dt][c]};
D.Uu.mW=function(b,c,d,e,f,g,h,j){var m=D.Uu.fh[b];m||(m={},m[D.Uu.dt]=[],D.Uu.fh[b]=m);b=m[c];b||(b={},m[c]=b,h!=D.q&&(m[D.Uu.dt][h]=c));b[D.Uu.pE]=d;b[D.Uu.pJ]=e;b[D.Uu.eZ]=f;b[D.Uu.dZ]=g;b[D.Uu.yP]=j;b[D.Uu.dt]=h};(0,D.ta)("DvtBaseMapManager.registerBaseMapLayer",D.Uu.mW);D.Uu.yna=function(b,c,d){var e=D.Uu.fh[b];e||(e={},D.Uu.fh[b]=e);b=e[c];b||(b={},e[c]=b);(b=e[c])&&(b[D.Uu.pE]=d)};(0,D.ta)("DvtBaseMapManager.registerResourceBundle",D.Uu.yna);
D.Uu.Xna=function(b,c,d){if(b=D.Uu.fh[b])if(c=b[c])for(var e in d)c[D.Uu.pE][e]=d[e]};(0,D.ta)("DvtBaseMapManager.updateResourceBundle",D.Uu.Xna);D.Uu.tFa=function(b,c){D.Uu.mr=b;D.Uu.tE=c;D.Uu.xn()};(0,D.ta)("DvtBaseMapManager.loadUnprocessedMaps",D.Uu.tFa);
D.Uu.xn=function(){var b,c;if(D.Uu.mr){for(b=0;b<D.Uu.mr[0].length;b++)c=D.Uu.mr[0][b],D.Uu.mW(c[0],c[1],c[2],c[3],c[4],c[5],c[6],c[7]);for(b=0;b<D.Uu.mr[1].length;b++)c=D.Uu.mr[1][b],D.Uu.yna(c[0],c[1],c[2]);for(b=0;b<D.Uu.mr[2].length;b++)c=D.Uu.mr[2][b],D.Uu.Xna(c[0],c[1],c[2]);D.Uu.mr=D.q}if(D.Uu.tE)for(b=0;b<D.Uu.tE[0].length;b++){c=D.Uu.tE[0][b];var d=c[1],e=c[2],f=D.Uu.fh[c[0]],g;if(f){if(d=f[d]){d[D.Uu.eZ]=c[3];g=d[D.Uu.yP];b=d[D.Uu.dt];d=f[D.Uu.dt];d.splice(b,0,e);f[e][D.Uu.dt]=b;for(b+=
1;b<d.length;b++)(e=f[d[b]])&&e[D.Uu.dt]++}(d=f[c[2]])&&(d[D.Uu.yP]=g)}}};D.Uu.OGa=function(b,c,d,e,f,g){if(0<g){c=1/(window.Math.min(e/c,f/d)*g);if(1>=c)return b;d=[];if(b)for(var h in b)e=b[h],(0,window.isNaN)(e)&&(e=window.DvtPathUtils.CU(b[h])),d[h]=window.DvtPathUtils.PGa(e,c);return d}return b};
D.hw=function(b,c){this.Init(b,c)};D.F.o(D.hw,D.F,"DvtThematicMapCategoryWrapper");D.hw.prototype.Init=function(b,c){this.cB=b;this.im=c};D.hw.prototype.Sg=(0,D.C)("im");D.hw.prototype.we=function(){return[this.cB]};
D.pv=function(b){this.Init(D.pv.hba);this.Eva=b};D.F.o(D.pv,D.oc,"DvtMapDrillEvent");D.pv.hba="drill";D.pv.Toa=0;D.pv.nX=1;D.pv.Aqa=2;D.pv.prototype.Ie=(0,D.A)("kg");
D.Xd=function(b,c,d){this.Init("action");this.rt=b;this.gM=c;this.hg=d};(0,D.ta)("DvtMapActionEvent",D.Xd);D.F.o(D.Xd,D.oc,"DvtMapActionEvent");D.Xd.TYPE="action";D.Xd.prototype.th=(0,D.C)("rt");D.Xd.prototype.getClientId=D.Xd.prototype.th;D.Xd.prototype.O6=(0,D.C)("gM");D.Xd.prototype.getRowKey=D.Xd.prototype.O6;D.Xd.prototype.zw=(0,D.C)("hg");D.Xd.prototype.getAction=D.Xd.prototype.zw;
D.gv=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.o(D.gv,D.Ya,"DvtMapLabel");D.D=D.gv.prototype;D.D.Init=function(b,c,d,e,f,g){D.gv.u.Init.call(this,b,c,0,0);this.Ce=g;this.sv=[];this.ja(D.t);this.Af();this.Pe();this.pt=D.q;this.Lo=e;this.iC=f;if(d&&(this.sv.push((0,D.qv)(d[0])),1<d.length)){this.V1=[];for(c=1;c<d.length;c++)e=d[c],this.sv.push((0,D.qv)(e[0])),e=new D.bl(b,e[1]),(0,D.wb)(e),f=new D.Hb("#000000"),this.Ce&&(f.dd=D.n),e.Z(f),this.V1.push(e)}};
D.D.update=function(b){b=b.Kc;for(var c=-1,d=D.Pb.Ni(this),e=D.t,f=0;f<this.sv.length;f++){var g=this.sv[f].g*b;if(d.g<=g){c=f;break}else if(this.getParent()||(e=D.n,this.iC.k(this)),this.D().g<=g){c=f;break}}-1==c&&"on"==this.Lo&&(c=this.sv.length-1);this.n0!=c?(-1==c?this.reset():(this.getParent()||this.iC.k(this),d=this.sv[c].Yc(),this.Xn(d),this.V1&&(this.iC.removeChild(this.Nj),this.Nj=D.q,0<c?(this.Nj=this.V1[c-1],this.iC.k(this.Nj),e=this.Mc(),e.X("color","#000000"),this.Ga(e),e=this.sv[c],
f=this.Nj.Gb(),g=f.length,e.x>f[g-2]?(this.Mk(),this.Pe(),this.Xn(new D.K(e.x,d.y))):e.y>f[g-1]?(this.ip(),this.Af(),this.Xn(new D.K(d.x,e.y))):e.x+e.g<f[g-2]?(this.Gi(),this.Pe(),this.Xn(new D.K(e.x+e.g,d.y))):e.y+e.j<f[g-1]&&(this.ww(),this.Af(),this.Xn(new D.K(d.x,e.y+e.j)))):(this.Af(),this.Pe(),e=this.Mc(),e.X("color",this.Nfa),this.Ga(e)))),this.n0=c):-1==c&&e&&this.iC.removeChild(this);-1!=this.n0&&(c=new D.sd,c.translate(b*this.pt.x-this.pt.x,b*this.pt.y-this.pt.y),this.qa(c),this.Nj&&(this.Nj.qa(new D.sd(b,
0,0,b)),this.Ce||(c=this.Nj.mc().clone(),c.ia(1/b),this.Nj.Z(c))))};D.D.Xn=function(b){this.pt=b;this.fa(b.x);this.ra(b.y)};D.D.Yc=(0,D.C)("pt");D.D.Ga=function(b){D.gv.u.Ga.call(this,b);this.Nfa||(this.Nfa=b.A("color"))};D.D.reset=function(){this.iC.removeChild(this);this.n0=-1;this.Nj&&(this.iC.removeChild(this.Nj),this.Nj=D.q)};
D.Ju=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.Ju,D.G,"DvtMapDataObject");D.D=D.Ju.prototype;D.D.Init=function(b,c,d,e,f){D.Ju.u.Init.call(this,b,D.q,e);this.fn=[];this.Hb=D.q;this.Oa=d;this.rt=e;this.bl=f;this.pJa=D.q;this.vK="#000000";this.Zoom=1;this.QR=D.t;this.fR=c;this.ad=c.O.hd()};D.D.getId=(0,D.C)("Oa");D.D.th=(0,D.C)("rt");D.D.Ud=function(b){(this.Hb=b)&&(0,D.tb)(this.Hb,"img")};D.D.Xn=(0,D.A)("hk");D.D.Yc=(0,D.C)("hk");D.D.Ia=(0,D.C)("Hb");D.D.Yn=(0,D.A)("oo");D.D.vh=(0,D.C)("oo");
D.D.Ic=(0,D.A)("maa");D.D.zw=(0,D.C)("hg");D.D.Za=function(b){D.Ju.u.Za.call(this,b);this.oo&&this.oo.Za(b)};D.D.we=function(){return[this.Hb]};D.D.Sg=(0,D.C)("fn");D.D.Bf=(0,D.C)("ny");D.D.uj=(0,D.C)("vK");D.D.B8=function(b){this.vK=b;this.Hb&&this.Hb.qp&&this.Hb.qp(b)};D.D.A8=function(b){this.ny=b;this.Wi()};D.D.Qf=function(){var b=[];this.gc()&&b.push((0,D.ec)(this.ad,this.Ta()?"STATE_SELECTED":"STATE_UNSELECTED"));return(0,D.gc)(this.Bf(),b,this.ad)};
D.D.Wi=function(){!(0,D.hc)()&&this.Hb&&(0,D.ic)(this.Hb,"label",this.Qf())};D.D.gc=function(){return this.Hb.gc()};D.D.Ta=function(){return this.Hb.Ta()};D.D.Bc=(0,D.v)();D.D.nc=function(){this.We||this.dY()};D.D.dY=(0,D.v)();D.D.L8=(0,D.A)("fd");D.D.Cd=(0,D.C)("fd");D.D.yj=function(b){for(var c=this.fR.th(),d=0;d<b.length&&b[d]!=c;d++);return c};D.D.tj=(0,D.C)("fR");D.D.Rk=function(){return this.fR.Mx(this)};D.D.KC=function(){return this.fR.Lx()};
D.D.wg=function(b){return b.type==D.Ib?this:32==b.keyCode&&b.ctrlKey?this:(0,D.qn)(this,b,this.GX())};D.D.GX=(0,D.ba)(D.q);D.D.xe=function(b){return this.Hb&&this.Hb.getParent()?this.Hb.D(b):new D.M(0,0,0,0)};D.D.Mn=function(){return this.Hb?this.Hb.oa():D.q};D.D.yh=function(){this.We=D.n;this.Bc()};D.D.ne=function(){this.We&&(this.We=D.t,this.nc())};D.D.wh=(0,D.C)("We");D.D.eg=function(b){this.Hb.getParent()&&(this.Zoom=b.Kc,this.TN())};D.D.Fp=(0,D.v)();D.D.TN=(0,D.v)();D.D.rc=(0,D.ba)(0);
D.Zu=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.Zu,D.Ju,"DvtMapDataArea");D.D=D.Zu.prototype;D.D.Init=function(b,c,d,e,f){D.Zu.u.Init.call(this,b,c,d,e,f);this.E1=D.t};D.D.Ud=function(b){D.Zu.u.Ud.call(this,b)};D.D.Nb=function(b){b&&!this.E1&&this.xk.k(this.Hb);this.Hb.Nb(b);this.Wi()};D.D.Bc=function(){this.xk.k(this.Hb);this.Hb.Bc();this.E1=D.n};D.D.dY=function(){this.Ta()?this.xk.k(this.Hb):this.xk.Fa(this.Hb,0);this.Hb.nc();this.E1=D.t};D.D.wu=function(){return this.Hb.wu()};
D.D.pI=function(b){(this.gS=b)?this.xk.k(this.Hb):this.xk.Fa(this.Hb,0);this.Hb.pI(b)};D.D.eg=function(b){this.Hb.getParent()&&(D.Zu.u.eg.call(this,b),(0,D.Av)(this.Hb,b),this.wu()||this.Fp(b))};D.D.Fp=function(b){this.oo&&this.oo.update(b)};D.D.GX=function(){return(0,D.Nv)(this.tj().O)};
D.$u=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.$u,D.Ju,"DvtMapDataMarker");D.D=D.$u.prototype;D.D.Init=function(b,c,d,e,f){D.$u.u.Init.call(this,b,c,d,e,f);this.rHa=1;this.Rj=0};D.D.Nb=function(b){this.Hb.Nb(b);this.Wi()};D.D.Bc=function(){this.Hb.Bc()};D.D.dY=function(){this.Hb.nc()};
D.D.Fp=function(){if(this.oo){this.oo.Af();var b=(this.Hb.ea()+(0,D.$v)(this.Hb)/2)*this.Zoom,c=this.Hb.ga()*this.Zoom,d=(0,D.aw)(this.Hb),e=this.Hb.Da();"top"==this.maa?(c-=4,this.oo.ww()):"bottom"==this.maa?(c+=d,this.oo.ip()):(c="triangleUp"==e?c+2*d/3:"triangleDown"==e?c+d/3:c+d/2,this.oo.Pe());this.oo.fa(b);this.oo.ra(c)}};
D.D.TN=function(){var b=this.Hb.getParent(),c=(0,D.aw)(this.Hb);(0,D.$v)(this.Hb)!=D.q&&(c!=D.q&&b)&&(c=this.Hb.RC(),this.oo&&this.Hb.RC()?((0,D.wa)(b,this.hk.x*this.Zoom-this.hk.x,this.hk.y*this.Zoom-this.hk.y),(0,D.Da)(b)):((0,D.wa)(this.Hb,this.hk.x*this.Zoom-(this.hk.x*window.Math.cos(c)-this.hk.y*window.Math.sin(c)),this.hk.y*this.Zoom-(this.hk.x*window.Math.sin(c)+this.hk.y*window.Math.cos(c))),(0,D.Da)(this.Hb)))};D.D.GX=function(){return(0,D.Pv)(this.tj().O)};D.D.fk=(0,D.A)("Rj");D.D.rc=(0,D.C)("Rj");
D.Iu=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.Iu,D.Ju,"DvtMapDataImage");D.D=D.Iu.prototype;D.D.Init=function(b,c,d,e,f){D.Iu.u.Init.call(this,b,c,d,e,f)};D.D.fW=function(b){b&&(b.width&&b.height)&&(this.Hb.getWidth()||this.Hb.ia(b.width),this.Hb.getHeight()||this.Hb.ta(b.height),this.fk(b.width*b.height),this.Hb.fa(this.hk.x-b.width/2),this.Hb.ra(this.hk.y-b.height/2),this.TN())};D.D.Ta=(0,D.ba)(D.t);
D.D.TN=function(){var b=this.Hb.getWidth(),c=this.Hb.getHeight();b!=D.q&&(c!=D.q&&this.Hb.getParent())&&(b=this.Hb.ea()+b/2,c=this.Hb.ga()+c/2,(0,D.wa)(this.Hb,b*this.Zoom-this.hk.x,c*this.Zoom-this.hk.y))};D.D.fk=(0,D.A)("Rj");D.D.rc=(0,D.C)("Rj");
D.bv=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.F.o(D.bv,D.Ju,"DvtMapDataComponent");D.D=D.bv.prototype;D.D.Init=function(b,c,d,e,f){D.bv.u.Init.call(this,b,c,d,e,f)};D.D.ia=(0,D.A)("R");D.D.getWidth=(0,D.C)("R");D.D.ta=(0,D.A)("Y");D.D.getHeight=(0,D.C)("Y");D.D.fa=(0,D.A)("$a");D.D.ra=(0,D.A)("Ma");D.D.TN=function(){if(this.Hb.getParent()){var b=this.Ma+this.Y/2;this.Hb.G(this.$a+(this.$a+this.R/2)*this.Zoom-this.hk.x);this.Hb.P(this.Ma+b*this.Zoom-this.hk.y)}};
D.Iu.prototype.rc=function(){return this.R*this.Y};
D.Ku=function(b,c,d,e){this.Init(b,c,d,e)};D.F.o(D.Ku,D.G,"DvtMapArea");D.D=D.Ku.prototype;D.D.Init=function(b,c,d,e){D.Ku.u.Init.call(this,b);this.mS=this.vQ=D.t;this.dIa=d;this.I=c;this.k(this.I);this.Ce=e;if(b=c.mc())this.wca=b.getWidth();this.I&&(0,D.tb)(this.I,"img")};D.D.he=(0,D.C)("af");D.D.bx=(0,D.A)("af");D.D.mc=function(){return this.I instanceof D.jo?this.I.mc():D.q};D.D.Z=function(b){this.I instanceof D.jo&&this.I.Z(b)};D.D.H=function(b){this.I instanceof D.jo&&this.I.H(b)};
D.D.Gc=function(){return this.I instanceof D.jo?this.I.Gc():D.q};D.D.FC=function(){return this.I instanceof D.Ra?this.I.FC():D.q};D.D.ek=function(b){this.I instanceof D.Ra&&this.I.ek(b)};D.D.LD=function(b){this.I instanceof D.Wb&&this.I.LD(b)};D.D.contains=function(b,c){var d=this.D();return b>=d.x&&b<=d.x+d.g&&c>=d.y&&c<=d.y+d.j};D.D.eg=function(b){if(!this.Ce&&this.I&&this.wca){var c=this.I.mc().clone();c.ia(this.wca/b.Kc);this.I.Z(c)}};
D.Xu=function(b,c){this.Init(b,c)};D.F.o(D.Xu,D.F,"DvtMapLayer");D.D=D.Xu.prototype;D.D.Init=function(b,c){this.O=b;this.Gf="cities";this.y9=D.q;this.RI=c;this.$g={};this.$m=new D.sd};D.D.Gaa=(0,D.v)();D.D.nP=(0,D.v)();
D.D.V8=function(b,c){this.nb&&(this.BJ=D.n,this.nb.stop(D.n));this.$m=c;this.Rt=this.tj(b.th());this.$g[b.th()]=b;b.M(this.$m);b.eg(new D.Le("zoomed"),this.$m);if(this.Rt){var d=b.Dq(),e=b.Qa();if(D.ad.isSupported(d)){for(var f=new D.M(0,0,this.O.R,this.O.Y),g=(0,D.wv)(this.Rt),h=0;h<g.length;h++){var j=new D.H(this.O.e,0,0,this.O.R,this.O.Y);j.H(D.q);g[h].k(j)}for(var m=(0,D.wv)(b),h=0;h<m.length;h++)j=new D.H(this.O.e,0,0,this.O.R,this.O.Y),j.H(D.q),m[h].k(j);f=D.ad.rz(this.O.e,d,g,m,f,e);g=new D.M(0,
0,this.O.R/this.$m.Kc,this.O.Y/this.$m.Kc);m=[this.Rt.xk];for(h=0;h<m.length;h++)j=new D.H(this.O.e,0,0,this.O.R/this.$m.Kc,this.O.Y/this.$m.Kc),j.H(D.q),m[h].k(j);for(var o=[b.xk],h=0;h<o.length;h++)j=new D.H(this.O.e,0,0,this.O.R/this.$m.Kc,this.O.Y/this.$m.Kc),j.H(D.q),o[h].k(j);h=D.ad.rz(this.O.e,d,m,o,g,e);this.nb=new D.Cn(this.O.e,[f,h])}else{d=[this.Rt.xk,this.Rt.Fr,this.Rt.$A];for(h=0;h<d.length;h++)d[h].getParent().removeChild(d[h]);this.nP()}this.Gaa();if(this.nb){this.RI.Fs(this.ka);var p=
this;this.nb.qd(function(){p.Dp(b)},this);this.nb.play()}}else this.nP(),(0,D.gw)(this.O)};D.D.tj=function(b){return this.$g?this.$g[b]:D.q};D.D.th=(0,D.C)("y9");D.D.M=function(b){this.$m=b;for(var c in this.$g)this.$g[c].M(b)};D.D.reset=function(b,c){for(var d in this.$g)this.$g[d].reset(b,c)};D.D.eg=function(b,c){this.$m=c;for(var d in this.$g)this.$g[d].eg(b,c)};D.D.Ws=function(b){this.$m=b;for(var c in this.$g)this.$g[c].Ws(b)};
D.D.Dp=function(b){if(this.Rt)for(var c=[this.Rt.xk,this.Rt.Fr,this.Rt.$A],d=0;d<c.length;d++){var e=c[d].getParent();e&&e.removeChild(c[d])}c=(0,D.wv)(b);for(d=0;d<c.length;d++)c[d].pp(c[d].za()-1);b=[b.xk];for(d=0;d<b.length;d++)b[d].pp(b[d].za()-1);this.nP();(0,D.gw)(this.O);this.BJ=D.t;this.nb=D.q;this.RI.nf(this.ka)};
D.Mu=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.o(D.Mu,D.Xu,"DvtMapAreaLayer");D.D=D.Mu.prototype;D.D.Init=function(b,c,d,e,f,g){D.Mu.u.Init.call(this,b,g);this.Lo=e;this.Gf=c;this.y9=d;this.O1=f;this.HJ={};this.vp={};this.Vm={};this.FB=this.bo=D.q;this.kg=[];this.mq={};this.Yr={};this.yT={};this.wO=new D.G(this.O.e);this.$I=new D.G(this.O.e);this.O.WZ.Fa(this.wO,0);this.O.Lt.Fa(this.$I,0);this.I0=new D.ov(this,this.O.Le)};D.D.kI=(0,D.A)("SZ");D.D.Dq=(0,D.C)("SZ");D.D.Wn=(0,D.A)("RZ");
D.D.Qa=(0,D.C)("RZ");D.Ou=function(b,c){b.bo=c;for(var d in b.bo)b.mq[d]=D.n,b.Yr[d]=D.n};D.Mu.prototype.dV=function(b){return!this.FB?D.q:this.FB[b]};D.Bv=function(b,c){return b.ce[c]?b.ce[c].split(","):[]};D.Mu.prototype.yH=(0,D.C)("Lo");D.iv=function(b,c){b.aL=c;b.LF=D.q;for(var d in b.Vm)d!=c&&(b.mq[d]=D.t)};
D.Mu.prototype.MC=function(){if(!this.LF)if(this.aL)this.LF=window.DvtPathUtils.D(window.DvtPathUtils.CU(D.Uu.pDa(this.O.Le,this.Gf,this.aL)));else if("world"!=this.O.Le&&"worldRegions"!=this.O.Le&&(this.LF=D.Uu.Mka(this.O.Le,this.Gf)),!this.LF){var b=(0,D.Xa)(this.wO.D(),this.O.uK.D());0<b.g&&0<b.j&&(this.LF=b)}return this.LF};
D.Cv=function(b,c,d){var e=b.Vm[c];if(e&&((d||!b.vp[c])&&b.Wna(c),b.vp[c]||(d=new D.Ku(b.O.e,e,c,b.O.Ce),b.vp[c]=d,b.RI.la(e,d),d.bx(b.bo&&b.bo[c]?b.bo[c][1]:D.q)),b.Yr[c]&&(d=b.HJ[c],!d&&("off"!=b.Lo&&b.bo)&&(d="short"==b.O1?b.bo[c][0]:b.bo[c][1]))))b.FB&&b.FB[c]?d=new D.gv(b.O.e,d,b.FB[c],b.Lo,b.$I,b.O.Ce):(e=(0,D.ll)(b.O.e,e),d=new D.gv(b.O.e,d,[[e.x,e.y,e.g,e.j]],b.Lo,b.$I,b.O.Ce)),b.HJ[c]=d,b.yS&&d.Ga(b.yS)};
D.Dv=function(b,c,d){if(b.Vm[c]){b.wO.k(b.vp[c]);var e=b.HJ[c];e&&(b.Yr[c]?e.update(b.$m):e.reset(),b.yT[c]=b.Yr[c]);d&&(d.push(b.vp[c]),e&&(d.push(e),d.push(e.Nj)))}};D.Mu.prototype.Wna=function(b){if(!this.Rha||this.Jca){this.Jca=D.t;var c;this.Rha=(c="world"==this.O.Le||"worldRegions"==this.O.Le?D.Uu.Mka(this.O.Le,this.Gf):this.MC())?D.Uu.OGa(D.Uu.Ika(this.O.Le,this.Gf),c.g,c.j,this.O.R,this.O.Y,this.O.lz?this.O.q2:1):D.Uu.Ika(this.O.Le,this.Gf)}c=this.Rha[b];this.Vm[b]&&c?this.Vm[b].ek(c):delete this.Vm[b]};
D.Wu=function(b){for(var c in b.bo)b.mq[c]=D.n,b.Yr[c]=D.n};D.D=D.Mu.prototype;D.D.V8=function(b,c,d){D.Mu.u.V8.call(this,b,c,d);if(d==this.Gf)for(var e in this.Vm)(0,D.Cv)(this,e,D.n),this.mq[e]&&(0,D.Dv)(this,e)};D.D.M=function(b){this.Jca=D.n;for(var c in this.Vm)(0,D.Cv)(this,c,D.n),this.mq[c]&&(0,D.Dv)(this,c);D.Mu.u.M.call(this,b)};D.D.Gaa=function(){for(var b in this.mq)this.mq[b]||((0,D.Cv)(this,b,D.t),(0,D.Dv)(this,b))};
D.D.nP=function(){for(var b in this.mq)if(!this.mq[b]){this.wO.removeChild(this.vp[b]);var c=this.HJ[b];c&&(this.yT[b]=D.t,this.$I.removeChild(c),(c=c.Nj)&&this.$I.removeChild(c))}};D.D.L5=function(b,c){for(var d=0;d<b.length;d++)(0,D.Cv)(this,b[d],D.t),this.mq[b[d]]&&(0,D.Dv)(this,b[d],c);for(var e in this.$g)this.$g[e].L5(b,c,this.$m);this.kg=this.kg.concat(b)};
D.D.tO=function(b,c){for(var d in this.$g)this.$g[d].tO(b,c);d=(0,D.Ev)(this.O,this.Gf);for(var e=0;e<b.length;e++){var f=b[e];if(this.vp[f]){var g=D.$c.Ha(this.kg,f);-1!==g&&(this.kg.splice(g,1),c.push(this.vp[f]))}d&&d.tO((0,D.Bv)(this,f),c)}};D.D.reset=function(b,c){D.Mu.u.reset.call(this,b,c);"none"!=this.O.Bk&&(this.tO(this.kg,b),this.kg=[])};D.D.eg=function(b,c){D.Mu.u.eg.call(this,b,c);if(!this.O.Ce)for(var d in this.vp)this.vp[d].eg(c);for(d in this.yT)if(this.yT[d]){var e=this.HJ[d];e&&e.update(c)}};
D.Lu=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.F.o(D.Lu,D.Mu,"DvtMapCustomAreaLayer");D.Lu.prototype.Init=function(b,c,d,e,f,g){D.Lu.u.Init.call(this,b,c,d,e,f,g)};D.Lu.prototype.Wna=(0,D.v)();D.Lu.prototype.MC=function(){return new D.M(0,0,this.Axa,this.zxa)};D.Nu=function(b){var c=b.O.R,d=b.O.Y;b=b.Vta;for(var e=0;e<b.length;e++){var f=b[e],g=f.source,h=f.width,f=f.height;if(g&&-1<g.search(".svg")||h>=c&&f>=d||e==b.length-1)return g}};
D.Pu=function(b,c){var d=D.q,e=(0,D.ya)(b.O.e);if(c&&0<c.length){var d=c[0].width,f=c[0].height;b.Axa=d;b.zxa=f;for(var g=[],h=0;h<c.length;h++)e&&"rtl"==c[h].dir?g.push(c[h]):!e&&"ltr"==c[h].dir&&g.push(c[h]);b.Vta=0<g.length?g:c;b.WR=(0,D.Nu)(b);d=new D.Wb(b.O.e,b.WR,0,0,d,f)}d&&((0,D.Ou)(b,{image:[D.q,D.q]}),b.Vm={image:d})};D.Lu.prototype.eg=function(b,c){D.Lu.u.eg.call(this,b,c);if(this.vp.image){var d=(0,D.Nu)(this);d!=this.WR&&(this.WR=d,this.vp[window.areaName].LD(this.WR))}};
D.Yu=function(b,c,d,e){this.Init(b,c,d,e)};D.F.o(D.Yu,D.F,"DvtMapDataLayer");D.Yu.prototype.Init=function(b,c,d,e){this.O=b;this.rt=d;this.hc=[];this.Fh=[];this.Ca=e;this.Ak=new D.sl(b.e);(0,D.wf)(this.Ca,this.Ak);this.xk=new D.G(this.O.e);this.Fr=new D.G(this.O.e);this.$A=new D.G(this.O.e);this.O.uK.Fa(this.xk,0);this.O.yv.Fa(this.Fr,0);this.O.Lt.Fa(this.$A,0);this.Oha=c;this.kg=[];this.pm=[]};D.wv=function(b){var c=[b.$A];b.O.Qr&&c.push(b.Fr);return c};
D.xv=function(b){for(var c=[],d=0;d<b.hc.length;d++)b.hc[d].wu()||c.push(b.hc[d]);return c};D.yv=function(b){for(var c=[],d=0;d<b.hc.length;d++)for(var e=0;e<b.kg.length;e++)b.hc[d].bl==b.kg[e]&&(b.hc[d].wu()||c.push(b.hc[d]));return c};D.hv=function(b,c){b.hc.push(c);b.Ca.la(c.Ia(),c);c.xk=b.xk};D.D=D.Yu.prototype;D.D.th=(0,D.C)("rt");D.D.kI=(0,D.A)("SZ");D.D.Dq=(0,D.C)("SZ");D.D.Wn=(0,D.A)("RZ");D.D.Qa=(0,D.C)("RZ");D.D.Ms=function(b){if(this.cs=b)this.Kb=new D.dd(this.cs),this.Ca.$z(this.rt,this.Kb)};
D.D.gc=function(){return this.cs!=D.q};D.zv=function(b,c){var d;d=b.hc[c];var e=d.Ia(),f=b.Oha.Vm[d.bl];f?(e.ek(f.FC()),d=D.n):(d=b.hc.indexOf(d),-1!==d&&b.hc.splice(d,1),d=D.t);if(d){e=b.hc[c].Ia();b.xk.k(e);if(d=b.hc[c].vh())0<d.sv.length||(e=e.D(),d.sv.push(e)),d.update(b.pG);return D.n}return D.t};D.D=D.Yu.prototype;
D.D.M=function(b){this.Eca=D.n;this.pG=b;var c={};this.Fh.sort(function(b,c){return b.rc()<c.rc()?1:b.rc()>c.rc()?-1:0});for(var d=0;d<this.Fh.length;d++){var e=this.Fh[d],f=e.Ia(),g=e.vh();if(g){if(f.RC()){var h=new D.G(f.e);this.Fr.k(h);h.k(f);h.k(g)}else this.Fr.k(f),f.k(g);e.Fp(b)}else this.Fr.k(f);if(e instanceof D.bv)if(g=e.xxa)f.M(window.JSON.parse(g),e.getWidth(),e.getHeight());else continue;(e=e.bl)&&(c[e]=D.n)}for(d=0;d<this.hc.length;d++)c[this.hc[d].bl]&&this.hc[d].Yn(D.q),(0,D.zv)(this,
d)||d--;this.XR&&this.mG()};D.D.L5=function(b,c,d){this.pG=d;for(var e=[],f=0;f<b.length;f++)for(var g=0;g<this.hc.length;g++)if(this.hc[g].bl==b[f]){e.push(this.hc[g].bl);(0,D.zv)(this,g);var h=this.hc[g].Ia();c.push(h);(0,D.Av)(h,d);if(g=this.hc[g].vh())c.push(g),(g=g.Nj)&&c.push(g);break}for(g=0;g<this.Fh.length;g++)for(f=0;f<b.length;f++)d=this.Fh[g].bl,h=this.Fh[g].Ia(),d!=D.q?d==b[f]&&(this.Fr.k(h),c.push(h)):(this.Fr.k(h),c.push(h));this.kg=this.kg.concat(e)};
D.D.tO=function(b,c){for(var d=0;d<b.length;d++)for(var e=0;e<this.hc.length;e++)if(this.hc[e].bl==b[d]){this.hc[e].wu()&&this.hc[e].pI(D.t);this.hc[e].Ta()&&this.Kb.VN(this.hc[e]);var f=D.$c.Ha(this.kg,b[d]);if(-1<f&&(this.kg.splice(f,1),c.push(this.hc[e].Ia()),e=this.hc[e].vh()))c.push(e),c.push(e.Nj);break}};
D.D.reset=function(b,c){if(this.Kb)for(var d=this.Kb.getSelection(),e=0;e<d.length;e++)(!c||c&&-1==D.$c.Ha(c,d[e].bl))&&this.Kb.VN(d[e]);if("none"!=this.O.Bk)for(d=0;d<this.pm.length;d++){for(e=0;e<this.hc.length;e++)if(this.hc[e].bl==this.pm[d]){this.hc[e].pI(D.t);var f=this.hc[e].Ia();this.xk.k(f);b.push(f);if(e=this.hc[e].vh())e.update(this.pG),b.push(e),b.push(e.Nj);break}for(e=0;e<this.Fh.length;e++)if(this.Fh[e].bl==this.pm[d]){f=this.Fh[e].Ia();this.Fr.k(f);b.push(f);break}}this.pm=[]};
D.D.eg=function(b,c){this.pG=c;var d=c.Kc,e=b.Mi();if(this.Eca&&"zoomed"==e){this.Eca=D.t;for(e=0;e<this.hc.length;e++){var f=this.hc[e].Ia(),g=f.gia;if(g){var h=new D.qd;g.Ed(h);h.qa(new D.sd(1/d,D.q,D.q,1/d));f.H(h)}}}e=this.hc;for(d=0;d<e.length;d++)e[d].eg(c);if(this.O.Qr){e=this.Fh;for(d=0;d<e.length;d++)e[d].eg(c)}};D.D.Ws=(0,D.A)("pG");D.D.mG=function(){this.Kb&&((0,D.Bd)(this.Kb,this.XR,this.Fh.concat(this.hc)),this.XR=D.q)};
D.D.Mx=function(b){if(this.Kb){b.Ta()||(this.Kb.Si(b,D.t),this.Ca.Bq(b));b=[];for(var c=this.Kb.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b}return D.q};D.D.Lx=function(){for(var b=[],c=this.Kb.getSelection(),d=0;d<c.length;d++)b.push(c[d].Ia());return b};
D.Ov=function(b,c){this.Init(b,c)};D.F.o(D.Ov,D.df,"DvtThematicMapKeyboardHandler");D.D=D.Ov.prototype;D.D.Init=function(b,c){D.Ov.u.Init(b,c);this.O=b};D.D.VH=function(b){return this.ak(b)&&!b.ctrlKey};
D.D.Vn=function(b){var c=b.keyCode;if(221==c){var c=this.va.Re(),d=(0,D.Pv)(this.O);c instanceof D.Zu&&0<d.length&&(c=(0,D.qn)(c,b,d));(0,D.Kv)(this.va,c)}else 219==c?(c=this.va.Re(),d=(0,D.Nv)(this.O),!(c instanceof D.Zu)&&0<d.length&&(c=(0,D.qn)(c,b,d)),(0,D.Kv)(this.va,c)):(c=D.Ov.u.Vn.call(this,b),this.ak(b)&&!b.ctrlKey&&(0,D.Kv)(this.va,c));return c};D.D.dD=function(b){return 32==b.keyCode&&b.ctrlKey};D.D.ak=function(b){var c=D.Ov.u.ak.call(this,b);if(!c&&(b=b.keyCode,219==b||221==b))c=D.n;return c};
D.Jv=function(b,c,d){this.Init(b,c,d)};D.F.o(D.Jv,D.Uc,"DvtThematicMapEventManager");D.D=D.Jv.prototype;D.D.Init=function(b,c,d){D.Jv.u.Init.call(this,b,c,d);this.mw={};this.O=d;this.mt=D.t};D.D.qf=function(b){if(b&&b.tj)return this.mw[b.tj().th()]};D.D.$z=function(b,c){this.mw[b]=c};D.D.wW=(0,D.A)("Bk");D.D.VN=function(b,c){var d=this.mw[b];d&&d.VN(c)};D.D.jH=function(b){(b=this.mw[b])&&b.jH()};
D.D.ro=function(b){var c=(0,D.gb)(this,b.target);c&&(c.Cd&&c.tj)&&(this.O.uR=c.tj().th());D.Jv.u.ro.call(this,b)};D.D.il=function(b){this.mt=D.t;D.Jv.u.il.call(this,b)};D.D.Ep=function(b){this.mt=D.n;D.Jv.u.Ep.call(this,b)};D.D.bh=function(b){if(!this.mt){var c=(0,D.gb)(this,b.target);(0,D.Kv)(this,c);if(!c||!c.gc||!c.gc())for(var d in this.mw)if(this.mw[d].Si(D.q,b.ctrlKey)){var e=new D.fd([]);(0,D.Pc)(e,"clientId",d);this.fb.call(this.ka,e)}D.Jv.u.bh.call(this,b);this.vy(c)}};
D.D.vy=function(b){b instanceof D.Ju&&(b.QR?(0,D.Lv)(this,b):b.Cd()&&(this.O.uR=b.tj().th()))};D.Lv=function(b,c){var d=new D.Xd(c.th(),c.getId(),c.hg);(0,D.Pc)(d,"clientId",c.tj().th());b.sc();b.fb.call(b.ka,d)};D.Kv=function(b,c){var d=D.q,e=D.q,f=D.q;c&&(c instanceof D.Ju?f=c.Ia():c instanceof D.Ku&&(f=c),c.tj&&(e=c.tj(),d=e.th(),e=e.Oha.Gf));var g=b.O;g.Lj=e;g.uv=d;g.JQ=f};D.D=D.Jv.prototype;
D.D.qo=function(b){D.Jv.u.qo.call(this,b);b=(0,D.gb)(this,b.target);this.qf(b)&&(this.Bk&&"none"!=this.Bk)&&(b=new D.pv(D.pv.nX),this.fb.call(this.ka,b))};
D.D.am=function(b){var c=D.n,d=b.keyCode;if((48==d||96==d)&&b.ctrlKey&&b.shiftKey)this.O.s8(),b.preventDefault();else if(220==d)(d=this.O.ic)&&(d instanceof D.wl?(0,D.xl)(d,!d.isCollapsed()):d instanceof D.xd&&d.Ie(!d.kb())),b.preventDefault();else if(13==d)d=this.Re(),d instanceof D.Ju&&d.QR?(0,D.Lv)(this,d):(b.shiftKey?this.O.N5():this.O.HU(),b.preventDefault());else if(32==d&&b.ctrlKey)d=this.Re(),(0,D.Kv)(this,d),(0,D.yf)(this,d,D.n),b.preventDefault();else if((48==d||96==d)&&b.ctrlKey){var e=
this.Re();b.altKey?(d=this.O,e=e.Ia(),e||(e=d.Jja),e||(e=d.JQ),d.bH(e.D())):(0,D.Mv)(this.O);b.preventDefault()}else c=D.Jv.u.am.call(this,b);return c};D.D.ct=function(b){var c=(0,D.gb)(this,b.target);(0,D.Kv)(this,c);if(!c||c.tKa)for(var d in this.mw)if(this.mw[d].Si(D.q,b.ctrlKey)){for(var e=this.mw[d].getSelection(),f=[],g=0;g<e.length;g++)f.push(e[g].getId());e=new D.fd(f);this.fb.call(this.ka,e)}D.Jv.u.ct.call(this,b);this.vy(c)};
D.D.dP=function(b){if((b=(0,D.gb)(this,b.target))&&b.Cd&&b.tj)this.O.uR=b.tj().th()};D.D.oA=function(b){var c=(0,D.gb)(this,b.target);c&&(this.qf(c)&&this.Bk&&"none"!=this.Bk)&&((0,D.yf)(this,c,b.ctrlKey),b=new D.pv(D.pv.nX),this.fb.call(this.ka,b))};
D.Qu=function(b){this.Init(b)};D.F.o(D.Qu,D.F,"DvtThematicMapParser");D.Ru="inlineStyle";D.Su="animationOnMapChange";D.Su="animationOnMapChange";D.Ru="inlineStyle";D.D=D.Qu.prototype;D.D.Init=function(b){this.O=b;this.Nda={};this.SP=this.UP=this.TP=this.kt=D.q;this.Dfa=(0,D.Vb)()};
D.D.G7=function(b){b=b.ib();for(var c,d,e=0;e<b.length;e++)if(c=b[e],d=c.getName(),"mapProperties"==d)this.DY(c);else if("customLayer"==d)this.DHa(c);else if("layers"==d)this.fJ(c);else if("legend"==d)this.mP(c);else if("childResources"==d){c=c.ib();for(d=0;d<c.length;d++){var f=c[d].getTextContent();f&&(0,D.Tu)(window.JSON.parse(f))}}};
D.D.DY=function(b){var c;if(c=b.q("source"))this.Rv=D.n;if(c=b.q("baseMapName")){var d=this.O;c=this.Rv?"$"+c:c;d.dQ=d.Le&&d.Le!=c;d.Le=c}if(c=b.q("animationOnDisplay"))this.O.UZ=c;if(c=b.q(D.Su))this.O.sca=c;(c=b.q("animationDuration"))&&this.O.Wn(c);if(c=b.q("displayTooltips"))this.O.C0=c;if(c=b.q("dropTargetStyle"))this.Uta=new D.O(c);if(c=b.q("controlPanelBehavior"))this.O.qK=c;(c=b.q("featuresOff"))&&this.O.zW(c);if(c=b.q("centerX"))this.O.ixa=(0,window.parseFloat)(c);if(c=b.q("centerY"))this.O.jxa=
(0,window.parseFloat)(c);if(c=b.q("curZoom"))this.O.C1=(0,window.parseFloat)(c);if((c=b.q("animationOnDrill"))&&"alphaFade"==c)this.O.Pta=c;(c=b.q("drillMode"))&&this.O.wW(c);if(c=b.q("drillZoomToFit"))this.O.Gva="true"==c;c=b.q("initialZooming");"auto"==c&&(this.O.$R=D.n);c=b.q("zooming");"none"==c&&(this.O.lz=D.t);c=b.q("panning");"none"==c&&(this.O.fC=D.t);c=(0,window.parseFloat)(b.q("maxZoom"));(0,window.isNaN)(c)||(this.O.q2=c);if(c=b.q("markerZoomBehavior"))this.O.Qr="fixed"==c;(0,D.he)(this.O,
b);b=b.ib();for(var e,d=0;d<b.length;d++)if(c=b[d],e=c.getName(),"mapHierarchy"==e){c=c.ib();e=this.O.Le;for(var f=D.k,g=D.k,h=D.k,j=D.k,g=D.k,m=0;m<c.length;m++){var o=c[m];if("pointLayer"!=o.getName()){var f=o.q("layerName"),g=o.q("labelDisplay"),h=o.q("clientId"),j=o.q("labelType"),p=o.q("areaStyle");p&&this.kt.Bb(new D.O(p));(p=o.q("labelStyle"))&&this.kt.Bb(new D.O(p));this.Rv?g=new D.Lu(this.O,f,h,g,j,this.O.Ca):(g=new D.Mu(this.O,f,h,g,j,this.O.Ca),p=D.Uu.Hka(e,f),h=this.h0(p),g.Vm=h,(0,D.Ou)(g,
p),p=D.Uu.Gka(e,f),g.FB=p,f=D.Uu.Qka(this.O.Le,f),g.ce=f,g.TP=this.TP,g.UP=this.UP,g.SP=this.SP);g.yS=this.kt;g.DIa=this.Uta;if(p=o.q("animationOnLayerChange")){(o=o.q("animationDuration"))&&(o=(0,window.parseFloat)(o));if(!o||(0,window.isNaN)(o))o=1;g.kI(p);g.Wn(o)}g&&this.O.Ke.push(g)}}}else if("regionLayer"==e){if(e=c.q(D.Ru))this.kt=new D.O(e);if(e=c.q("hoverStyle"))this.TP=new D.O(e);if(e=c.q("selectStyle"))this.UP=new D.O(e);if(e=c.q("disclosedStyle"))this.SP=new D.O(e)}else"markerStyle"==e?
(c=new D.O(c.q(D.Ru)),this.O.Ega=c):"basemap"==e&&this.O.Le=="$"+c.q("id")&&this.uY(c)};
D.D.fJ=function(b,c,d){var e=b.getElementsByTagName("layer");b=b.getElementsByTagName("legend");c&&(b&&b[0])&&this.mP(b[0]);for(b=0;b<e.length;b++){var f=e[b].q("clientId"),g=e[b].q("id"),h=(0,D.Vu)(this.O,g);h?h instanceof D.Mu&&(0,D.Wu)(h):(h=e[b].q("showWith"))?h=(0,D.Vu)(this.O,h):(h=new D.Xu(this.O,this.O.Ca),this.O.Ke.push(h));var f=new D.Yu(this.O,h,f,this.O.Ca),j=e[b].q("selectionMode");"single"==j?f.Ms("s"):"multiple"==j&&f.Ms("m");if(j=e[b].q("animationDataChange")){var m=e[b].q("animationDuration");
m&&(m=(0,window.parseFloat)(m));if(!m||(0,window.isNaN)(m))m=1;f.kI(j);f.Wn(m)}j=D.q;h instanceof D.Mu&&(j=e[b].q("isolatedRowKey"));for(var m=[],o=[],p=this.q3(e[b].getElementsByTagName("styles")),r=e[b].getElementsByTagName("row"),u=this.p3(e[b],p),w=0;w<r.length;w++){var z=r[w].q("styleId"),B;a:{var I=h,E=f;B=g;var J=r[w],L=p[z],N=m,R=o,S=j,ea=this.O.e,oa=J.q("rowKey"),qa=J.q("clientId"),z=J.q("id"),ra=D.k,Wa=L.getName();if("colorStyles"==Wa){if(S){if(S!=oa){B=D.q;break a}this.aL=z}I.mq[z]=D.t;
ra=new D.Zu(ea,E,oa,qa,z);this.l3(ea,z,I,J,ra)}else if("graduatedSymbol"==Wa)ra=new D.$u(ea,E,oa,qa,z),this.m3(ea,L,B,J,ra);else if("image"==Wa){var ra=new D.Iu(ea,E,oa,qa,z),L=ea,La=B,xa=J,S=ra,qa=xa.q("url"),Jb=D.q;if(La=(0,D.av)(this,La,xa,"cities"!=La)){Jb=new D.Wb(L,qa);S.Xn(La);S.Ud(Jb);var Eb=D.k,Fd=D.k;if(xa=xa.q(D.Ru))xa=new D.O(xa),(Eb=xa.A("width").substring(0,xa.A("width").indexOf("px")))&&Jb.ia(Eb),(Fd=xa.A("height").substring(0,xa.A("height").indexOf("px")))&&Jb.ta(Fd),Eb!=D.q&&Fd!=
D.q&&(Jb.fa(La.x-Eb/2),Jb.ra(La.y-Fd/2),S.fk(Eb*Fd));(!Eb||!Fd)&&D.ol.zj(L,qa,D.F.qj(S,S.fW))}}else if(ra=new D.bv(ea,E,oa,qa,z),Jb=ea,S=J,L=ra,La=Wa,qa=(0,D.av)(this,B,S,"cities"!=B)){"statusMeterGauge"==La?window.gauge=(0,D.cv)(Jb,D.q,D.q):"ledGauge"==La?window.gauge=(0,D.dv)(Jb,D.q,D.q):"dialGauge"==La?window.gauge=(0,D.ev)(Jb,D.q,D.q):"ratingGauge"==La&&(window.gauge=(0,D.fv)(Jb,D.q,D.q));L.Xn(qa);L.Ud(window.gauge);La=Jb=D.k;if(Jb=S.q(D.Ru))La=new D.O(Jb),Jb=La.width?(0,window.parseInt)(La.width.substring(0,
La.width.indexOf("px"))):50,L.ia(Jb),La=La.height?(0,window.parseInt)(La.height.substring(0,La.height.indexOf("px"))):50,L.ta(La),L.fa(qa.x-Jb/2),L.ra(qa.y-La/2);if(S=S.q("json"))L.xxa=S}if(L=ra.Ia()){if(S=(0,window.parseInt)(J.q("rotation")))S=S*window.Math.PI/180,L.Ti(S),qa=ra.Yc(),(0,D.wa)(L,qa.x-(qa.x*window.Math.cos(S)-qa.y*window.Math.sin(S)),qa.y-(qa.x*window.Math.sin(S)+qa.y*window.Math.cos(S)));z&&I instanceof D.Mu&&(I.Yr[z]=D.t);S="true"==J.q("hasAction");if(ra.QR=S)S=J.q("action"),ra.hg=
S;if(S=J.q("destination"))qa=[],qa.destination=S,qa.targetFrame="_blank",qa.focusable=D.n,(0,D.Za)(L,qa);"true"==J.q("selected")&&N.push(oa);"true"==J.q("drilled")&&(R.push(J.q("id")),this.O.gF.push(oa));N=J.q("label");R="off";N?R="on":"colorStyles"==Wa&&(R=I.yH());!N&&(z&&"off"!=R)&&(N="long"==I.O1?I.bo[z][1]:I.bo[z][0]);if(N){oa=D.k;I.dV&&(oa=I.dV(z));var tc=D.k,tc=oa?new D.gv(ea,N,oa,R,E.$A,this.O.Ce):"colorStyles"!=Wa?new D.Ya(ea,N,0,0):new D.gv(ea,N,D.q,R,E.$A,this.O.Ce);(E=J.q("labelPosition"))&&
ra.Ic(E);E=new D.O;"colorStyles"==Wa?E.Bb(I.yS):"graduatedSymbol"==Wa&&E.Bb(this.O.Ega);(I=J.q("labelStyle"))&&E.Bb(new D.O(I));tc instanceof D.gv&&(E.A("color")||E.X("color",D.U.Jl(ra.uj())));tc.Ga(E)}ra.Yn(tc);I=this.O.C0;"none"!=I&&(J=J.q("shortDesc"),"auto"==I&&(I=D.k,z&&(I="cities"==B||this.Rv?D.Uu.Tka(this.O.Le,z):D.Uu.pla(this.O.Le,B,z)),I&&(J=J?I+": "+J:I)),J&&ra.A8(J));B=ra}else B=D.q}B&&(z=B.Ia(),z.Bg&&z.Bg(f.gc()&&!(B instanceof D.Iu)),0<u.length&&B.L8(u),B instanceof D.Zu?(0,D.hv)(f,B):
(z=f,z.Fh.push(B),z.Ca.la(B.Ia(),B)))}j&&this.aL&&(f.sxa=j,(0,D.iv)(h,this.aL));f.gc()&&0<m.length&&(f.XR=m);0<o.length&&(this.O.DF[h.Gf]=[f.th(),o]);c||h.tj(f.th())?h.V8(f,c,d):h.$g[f.th()]=f}};D.D.mP=function(b){this.O.No=b};D.D.uY=function(b){b=b.ib();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),"layer"==d?this.j3(c):"points"==d&&this.k3(c)};
D.D.j3=function(b){var c=b.ib();b=b.q("id");for(var d,e,f=[],g=0;g<c.length;g++)if(d=c[g],e=d.getName(),"image"==e){e={};e.source=d.q("source");e.width=d.q("width");e.height=d.q("height");var h=d.q("bidi");d=d.q("dir");e.dir="true"==h||"rtl"==d?"rtl":"ltr";f.push(e)}(0,D.Pu)((0,D.Vu)(this.O,b),f)};
D.D.k3=function(b){b=b.ib();for(var c,d,e={},f={},g=0;g<b.length;g++)c=b[g],d=c.getName(),"point"==d&&(e[c.q("name")]=[c.q("x"),c.q("y")],f[c.q("name")]=[D.q,c.q("longLabel")]);D.Uu.mW(this.O.Le,"cities",f,e,D.q,D.q,1)};D.D.h0=function(b){var c={},d=this.O.e,e;for(e in b)c[e]=new D.Ra(d),(0,D.jv)(this,"colorStyles",this.kt,c[e]);return c};D.D.q3=function(b){var c={};if(b&&0<b.length){b=b[0].ib();for(var d=0;d<b.length;d++){var e=b[d].q("id");c[e]=b[d]}}return c};
D.D.p3=function(b,c){for(var d=b.getElementsByTagName("spb"),e=[],f=0;f<d.length;f++){var g=d[f].q("alignId"),h=(0,D.Gt)(d[f]),j;for(j in c)if(g==j){h=new D.Jd(h.zz(),h.Ph(),D.q,h.CC());break}e.push(h)}return e};D.av=function(b,c,d,e){b=b.O.Le;var f=d.q("id");if(f)return e?D.Uu.Fka(b,c,f):D.Uu.Ska(b,f);c=(0,window.parseFloat)(d.q("x"));d=(0,window.parseFloat)(d.q("y"));return new D.K(c,d)};
D.Qu.prototype.l3=function(b,c,d,e,f){if(d.Vm[c]){c=new D.O(e.q(D.Ru));b=new D.kv(b,this.O.Ce);var g=d.UP;e=d.SP;d=new D.Hb(d.TP.A("border-color"),1,2);var h=new D.Hb(g.A("-tr-inner-color"),1,1),g=new D.Hb(g.A("-tr-outer-color"),1,4);b.Yq(d,D.q).$q(h,g);e&&(d=new D.Hb(e.A("-tr-inner-color"),1,2),e=new D.Hb(e.A("-tr-outer-color"),1,4),(0,D.lv)(b,d,e));f.Ud(b);(0,D.jv)(this,"colorStyles",c,b,f)}};
D.Qu.prototype.m3=function(b,c,d,e,f){var g=D.q;if(d=(0,D.av)(this,d,e,"cities"!=d)){if(g=e.q("source"))g=[g,e.q("sourceSelected"),e.q("sourceHover"),e.q("sourceHoverSelected")];else if((g=e.q("shapeType"))||(g="c"),!(0,D.mv)(g)){c=c.getElementsByTagName("markerDef");for(var h=0;h<c.length;h++)!this.Nda[g]&&c[h].q("id")==g&&(this.Nda[g]=D.lg.eka(b,c[h]))}c=e.q("scaleX");c=(0,window.isNaN)(c)?1:(0,window.parseFloat)(c);var h=e.q("scaleY"),h=(0,window.isNaN)(h)?1:(0,window.parseFloat)(h),j=e.q("width"),
m=e.q("height"),j=!j||(0,window.isNaN)(j)?8:(0,window.parseInt)(j),m=!m||(0,window.isNaN)(m)?8:(0,window.parseInt)(m),g=new D.va(b,g,this.O.Eb,d.x-j*c/2,d.y-m*h/2,j,m,D.q,c,h);f.Xn(d);f.Ud(g);f.fk(j*c*m*h);if(b=e.q(D.Ru))b=new D.O(b),(0,D.jv)(this,"graduatedSymbol",b,g,f)}};
D.jv=function(b,c,d,e,f){d||(d={});var g=d.A("pattern"),h=d.A("pattern-color"),j=d.A("background-color"),m=b.Dfa||"alta"==b.O.Eb?D.t:d.A("gradient");j&&f?f.fn.push(j):h&&f&&f.fn.push(h);var o;o=d.A("opacity")?(0,window.parseFloat)(d.A("opacity")):1;f&&f.B8(j?j:h);if("graduatedSymbol"==c&&(0,D.mv)(e.Da())){c=b.O.Ega;f=d.A("border-style")?d.A("border-style"):c.A("border-style");if("none"!=f){var p=d.A("border-color")?d.A("border-color"):c.A("border-color");(d=d.A("border-width")?d.A("border-width"):
c.A("border-width"))&&(d=(0,window.parseFloat)(d.substring(0,d.indexOf("px"))));d=new D.Hb(p,1,d);d.Ui((0,D.Gr)(f));b.O.Qr||(d.dd=D.n);e.Z(d)}"true"==m&&j?e.H(new D.nv.B5(j,e,o)):g?e.H(new D.qd(g,h,j)):j?e.na(j,o):e.na(c.A("background-color"),o)}else if("colorStyles"==c){if((m=d.A("border-color"))&&"transparent"!=m)d=new D.Hb(m),b.O.Ce&&(d.dd=D.n),e.Z(d);g?(b=new D.qd(g,h,j),e.gia=b):j&&"transparent"!=j?e.na(j,o):e.H(D.q)}};
D.rv=function(b){this.Init(b)};D.F.o(D.rv,D.F,"DvtThematicMapJsonParser");D.D=D.rv.prototype;D.D.Init=function(b){this.O=b;this.Rv=D.t;this.kt=D.q;this.Dfa=(0,D.Vb)();this.Lda={}};
D.D.parse=function(b){b.skin="alta";this.DY(b);var c=b.styleDefaults;this.kt=new D.O(c.areaStyle+c.labelStyle);this.O.gs=c;this.Rv&&(c=(new D.ie).parse(b.sourceXml))&&this.uY(c);for(var c=b.areaLayers,d=this.O.Le,e=0;e<c.length;e++){var f=D.Ta.Bb(c[e],D.sv),g=f.layer;if(g){var h;f.areaStyle&&(0,D.ih)(this.kt,f.areaStyle);if(this.Rv)h=new D.Lu(this.O,g,D.q,f.labelDisplay,f.labelType,this.O.Ca),(0,D.Pu)(h,this.Lda[g]);else{h=new D.Mu(this.O,g,D.q,f.labelDisplay,f.labelType,this.O.Ca);var j=D.Uu.Hka(d,
g),m=this.h0(j);h.Vm=m;(0,D.Ou)(h,j);j=D.Uu.Gka(d,g);h.FB=j;g=D.Uu.Qka(this.O.Le,g);h.ce=g}h.yS=this.kt;h.kI("auto"==f.animationOnLayerChange?"alphaFade":f.animationOnLayerChange);h.Wn(this.O.Qa());this.O.Ke.push(h);f.areaDataLayer&&this.fJ([f.areaDataLayer],h,D.n);f.pointDataLayers&&this.fJ(f.pointDataLayers,h,D.t)}}this.fJ(b.pointDataLayers,D.q,D.t)};
D.D.DY=function(b){(0,D.ge)(this.O,b);this.O.Wn(b.animationDuration/1E3);this.O.UZ="auto"==b.animationOnDisplay?"alphaFade":b.animationOnDisplay;this.O.sca="auto"==b.animationOnMapChange?"alphaFade":b.animationOnMapChange;this.Rv=b.source!=D.q;var c=this.O,d=this.Rv?"$"+b.basemap:b.basemap;c.dQ=c.Le&&c.Le!=d;c.Le=d;this.O.qK=b.controlPanelBehavior;this.O.wW("none");this.O.$R="auto"==b.initialZooming;this.O.Qr="fixed"==b.markerZoomBehavior;this.O.fC="auto"==b.panning;c=b.tooltipDisplay;"shortDesc"==
c?c="shortDescOnly":"labelAndShortDesc"==c&&(c="auto");this.O.C0=c;this.O.lz="auto"==b.zooming};
D.D.fJ=function(b,c,d){if(b)for(var e=0;e<b.length;e++){var f=D.Ta.Bb(b[e],D.tv);c?c instanceof D.Mu&&(0,D.Wu)(c):(c=new D.Xu(this.O,this.O.Ca),this.O.Ke.push(c));var g=new D.Yu(this.O,c,f.id,this.O.Ca),h=f.selection;"single"==h?g.Ms("s"):"multiple"==h&&g.Ms("m");g.kI("auto"==f.animationOnDataChange?"alphaFade":f.animationOnDataChange);g.Wn(this.O.Qa());var j=D.q;c instanceof D.Mu&&(j=f.isolatedItem);var m=f.disclosedItems,h=[],o,p=f.areas;if(p)for(var r=0;r<p.length;r++){var u=p[r].location;if(j)if(j!=
p[r].id)continue;else o=u;m&&-1!=m.indexOf(p[r].id)&&h.push(u);if(u=this.l3(c,g,p[r])){if(g.gc()){var w=u.Ia();w.Bg(D.n)}(0,D.hv)(g,u)}}if(m=f.markers)for(r=0;r<m.length;r++){u=m[r].location;if(d&&j)if(j!=m[r].id)continue;else o=u;if(u=this.m3(c,g,m[r],d))g.gc()&&(w=u.Ia(),w.Bg(D.n)),p=g,p.Fh.push(u),p.Ca.la(u.Ia(),u)}o&&(g.sxa=j,(0,D.iv)(c,o));if((f=f.selectedItems)&&0<f.length)g.XR=f;h&&0<h.length&&(this.O.DF[c.Gf]=[g.th(),h]);c.$g[g.th()]=g}};
D.D.uY=function(b){b=b.ib();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),"layer"==d?this.j3(c):"points"==d&&this.k3(c)};D.D.j3=function(b){var c=b.ib();b=b.q("id");for(var d,e,f=[],g=0;g<c.length;g++)if(d=c[g],e=d.getName(),"image"==e){e={};e.source=d.q("source");e.width=d.q("width");e.height=d.q("height");var h=d.q("bidi");d=d.q("dir");e.dir="true"==h||"rtl"==d?"rtl":"ltr";f.push(e)}this.Lda[b]=f};
D.D.k3=function(b){b=b.ib();for(var c,d,e={},f={},g=0;g<b.length;g++)c=b[g],d=c.getName(),"point"==d&&(e[c.q("name")]=[c.q("x"),c.q("y")],f[c.q("name")]=[D.q,c.q("longLabel")]);D.Uu.mW(this.O.Le,"cities",f,e,D.q,D.q,1)};D.D.h0=function(b){var c={},d=this.O.e,e;for(e in b)c[e]=new D.Ra(d),(0,D.uv)(this,this.kt,c[e]);return c};
D.D.l3=function(b,c,d){var e=d.location;if(b.Vm[e]&&d.color){b.mq[e]=D.t;var f=this.O.e,g=new D.kv(f,this.O.Ce);d=D.Ta.Bb(d,this.O.gs.dataAreaDefaults);d.labelStyle||(d.labelStyle=this.O.gs.labelStyle);var h=new D.Hb(d.hoverColor,1,2),j=new D.Hb(d.selectedInnerColor,1,1),m=new D.Hb(d.selectedOuterColor,1,4);g.Yq(h,D.q).$q(j,m);h=new D.Hb(d.drilledInnerColor,1,2);j=new D.Hb(d.drilledOuterColor,1,4);(0,D.lv)(g,h,j);e=new D.Zu(f,c,d.id,d.clientId,e);e.Ud(g);(0,D.vv)(this,b,c,d,g,e,D.n);return e}return D.q};
D.D.m3=function(b,c,d,e){var f;f=d;var g=this.O.Le,h=f.location;f=h?e?D.Uu.Fka(g,b.Gf,h):D.Uu.Ska(g,h):D.Z.dGa(f.x,f.y,this.O.Le);if(!f)return D.q;g=this.O.e;window.dataObj=new D.$u(g,c,d.id,d.clientId,d.location);window.dataObj.Xn(f);d=D.Ta.Bb(d,this.O.gs.dataMarkerDefaults);(h=d.source)?h=[h,d.sourceSelected,d.sourceHover,d.sourceHoverSelected]:(h=d.shape)||(h="c");var j=d.scaleX;(0,window.isNaN)(j)&&(j=1);var m=d.scaleY;(0,window.isNaN)(m)&&(m=1);var o=d.width,p=d.height;if(!o||(0,window.isNaN)(o))o=
8;if(!p||(0,window.isNaN)(p))p=8;window.marker=new D.va(g,h,"alta",f.x-o*j/2,f.y-p*m/2,o,p,D.q,j,m);window.dataObj.Ud(window.marker);window.dataObj.fk(o*j*p*m);window.dataObj.Ic(d.labelPosition);if(f=d.rotation)g=f*window.Math.PI/180,window.marker.Ti(g),f=window.dataObj.Yc(),(0,D.wa)(window.marker,f.x-(f.x*window.Math.cos(g)-f.y*window.Math.sin(g)),f.y-(f.x*window.Math.sin(g)+f.y*window.Math.cos(g)));(0,D.vv)(this,b,c,d,window.marker,window.dataObj,e);return window.dataObj};
D.vv=function(b,c,d,e,f,g,h){var j=e.location;h&&"auto"==c.yH()&&(c.Yr[j]=D.t);e.action&&(g.QR=D.n,g.hg=e.action);if(j=e.destination){var m=[];m.destination=j;m.targetFrame="_blank";m.focusable=D.n;(0,D.Za)(f,m)}m=b.O.C0;if("none"!=m){j=e.shortDesc;if("auto"==m){var o;(m=e.location)&&(o=!h||b.Rv?D.Uu.Tka(b.O.Le,m):D.Uu.pla(b.O.Le,c.Gf,m));o&&(j=j?o+": "+j:o)}j&&g.A8(j)}o=new D.O;o.X("background-color",e.color);o.X("pattern",e.pattern);o.X("border-color",e.borderColor);o.X("border-style",e.borderStyle);
e.borderWidth&&o.X("border-width",e.borderWidth);o.X("opacity",e.opacity);(0,D.uv)(b,o,f,g);f=e.location;j=(o=e.label)?"on":"off";h&&(j=c.yH());if(!o&&h&&(g instanceof D.Zu&&"off"!=j||!(g instanceof D.Zu)&&"on"==j))o="long"==c.O1?c.bo[f][1]:c.bo[f][0];if(o){var p=b.O.e,p=g instanceof D.$u?new D.Ya(p,o,0,0):new D.gv(p,o,c.dV?c.dV(f):D.q,j,d.$A,b.O.Ce);b=new D.O(e.labelStyle);p instanceof D.gv&&(b.A("color")||b.X("color",D.U.Jl(g.uj())));p.Ga(b)}g.Yn(p)};
D.uv=function(b,c,d,e){c||(c={});var f=c.A("pattern"),g=c.A("background-color");e&&e.B8(g);if(d instanceof D.va&&(0,D.mv)(d.Da())){"none"!=c.A("border-style")&&(e=new D.Hb(c.A("border-color"),1,c.A("border-width")),b.O.Qr||(e.dd=D.n),e.Ui((0,D.Gr)(c.A("border-style"))),d.Z(e));var h=c.A("opacity");"true"==D.t&&g?d.H(new D.nv.B5(g,d,h)):f?d.H(new D.qd(f,g,"#FFFFFF")):g?d.na(g,h):d.na(c.A("background-color"),h)}else if(d instanceof D.Ra){if((c=c.A("border-color"))&&"transparent"!=c)e=new D.Hb(c),b.O.Ce&&
(e.dd=D.n),d.Z(e);f?(b=new D.qd(f,g,"#FFFFFF"),d.gia=b):"transparent"!=g?d.na(g,h):d.H(D.q)}};
D.Z={};D.F.o(D.Z,D.F,"DvtThematicMapProjections");D.Z.cv=new D.M(0,0,800,500);D.Z.GP=6378206.4;D.Z.xZ=new D.M(500,200,200,200);D.Z.wZ=new D.M(163,-49,17,17);D.Z.uba=new D.M(-17.379205428479874,-37.201510854305546,68.66391442808313,77.50071544582713);D.Z.xba=new D.M(-0.8436866097568272,-0.7626456732012923,1.8336308036296942,1.5748427214611724);D.Z.yba=new D.M(113.29667079927977,-52.89550592498755,65.25257389065216,42.123114617504626);
D.Z.Jba=new D.M(-0.47944476148667076,-0.0014669405958800579,0.7364925893845453,0.6293972741802124);D.Z.Sba=new D.M(-0.6154469465354344,-0.24589767758847714,1.2448236795108683,1.2631535127174947);D.Z.Zba=new D.M(-80.60817722658722,-60.796273249672765,46.608687602908056,66.96595767361796);D.Z.wba=new D.M(68.20516856593524,-52.89892708045518,111.65739821771903,116.55460214469134);D.Z.Hba=new D.M(-24.543831069368586,-37.202500659225905,204.54283106936856,164.9634493690208);
D.Z.Rba=new D.M(-117.12451221229134,-54.95921623126266,82.33223251442891,87.67786623127876);D.Z.cca=new D.M(-0.6154656300926513,0.0507209798775865,1.0153104799231851,0.966537441082997);D.Z.dca=new D.M(-171.9,-62.6,349.8,150.8);D.Z.fra=new D.M(172,51,8,3);D.Z.gra=new D.M(-180,51,51,21);D.Z.Tra=new D.M(-178.5,18.9,35,11);D.Z.Usa=new D.M(-124.8,24.4,58,25.5);D.Z.vba=new D.M(-187.5517578125,59.82610321044922,57.562225341796875,43.83738708496094);
D.Z.Nba=new D.M(-160.23606872558594,18.91549301147461,5.4374847412109375,3.3189010620117188);D.Z.bca=new D.M(-2386803.25,-1183550.5,4514111,2908402);D.Z.uZ=new D.M(165,400,100,100);D.Z.qZ=new D.M(-75,350,240,150);D.Z.kl=[[1,0],[0.9986,0.0314],[0.9954,0.0629],[0.99,0.0943],[0.9822,0.1258],[0.973,0.1572],[0.96,0.1887],[0.9427,0.2201],[0.9216,0.2515],[0.8962,0.2826],[0.8679,0.3132],[0.835,0.3433],[0.7986,0.3726],[0.7597,0.4008],[0.6732,0.4532],[0.6213,0.4765],[0.5722,0.4951],[0.5322,0.5072]];
D.Z.dGa=function(b,c,d){var e;switch(d){case "africa":e=D.Z.Iv(D.Z.uba,D.Z.RK(b,c));break;case "asia":e=D.Z.Iv(D.Z.xba,D.Z.DR(40,95,20,60,b,c),D.Z.Zg(5));break;case "australia":e=D.Z.Wva(b,c);break;case "europe":e=D.Z.Iv(D.Z.Jba,D.Z.DR(35,25,40,65,b,c),D.Z.Zg(10));break;case "northAmerica":e=D.Z.Iv(D.Z.Sba,D.Z.DR(23,-96,20,60,b,c));break;case "southAmerica":e=D.Z.Iv(D.Z.Zba,new D.K(b,c),D.Z.Zg(5));break;case "apac":e=D.Z.Iv(D.Z.wba,D.Z.RK(b,c));break;case "emea":e=D.Z.Iv(D.Z.Hba,D.Z.RK(b,c));break;
case "latinAmerica":e=D.Z.Iv(D.Z.Rba,new D.K(b,c));break;case "usaAndCanada":e=D.Z.Iv(D.Z.cca,D.Z.DR(23,-96,20,60,b,c));break;case "worldRegions":e=D.Z.Tea(b,c);break;case "usa":e=D.Z.Cwa(b,c);break;case "world":e=D.Z.Tea(b,c)}return e?new D.K(10*e.x,10*e.y):new D.K(b,c)};
D.Z.Cwa=function(b,c){var d;return(0,D.ur)(D.Z.fra,b,c)||(0,D.ur)(D.Z.gra,b,c)?(d=D.Z.nn(D.Z.vba,D.Z.qZ),D.Z.CJ(d,D.Z.RK(b,c))):(0,D.ur)(D.Z.Tra,b,c)?(d=D.Z.nn(D.Z.Nba,D.Z.uZ),D.Z.CJ(d,new D.K(b,c))):(0,D.ur)(D.Z.Usa,b,c)?(d=D.Z.nn(D.Z.bca,D.Z.cv),D.Z.CJ(d,D.Z.twa(new D.K(-95,36),b,c))):new D.K(b,c)};D.Z.Tea=function(b,c){var d=D.Z.nn(D.Z.dca,D.Z.cv);return D.Z.CJ(d,D.Z.wwa(b,c))};
D.Z.Wva=function(b,c){var d;d=(0,D.ur)(D.Z.wZ,b,c)?D.Z.nn(D.Z.wZ,D.Z.xZ):D.Z.nn(D.Z.yba,D.Z.cv);return D.Z.CJ(d,D.Z.RK(b,c))};D.Z.Iv=function(b,c,d){b=D.Z.nn(b,D.Z.cv);if(d){var e=new D.sd;e.rotate(d);b=D.Z.oda(b,e)}return(0,D.Ej)(b,c)};
D.Z.DR=function(b,c,d,e,f,g){c=D.Z.Zg(c);b=D.Z.Zg(b);d=D.Z.Zg(d);e=D.Z.Zg(e);e=0.5*(window.Math.sin(d)+window.Math.sin(e));d=window.Math.pow(window.Math.cos(d),2)+2*e*window.Math.sin(d);b=d-2*e*window.Math.sin(b);b=window.Math.sqrt(b)/e;f=e*(D.Z.Zg(f)-c);g=d-2*e*window.Math.sin(D.Z.Zg(g));g=window.Math.sqrt(g)/e;return new D.K(g*window.Math.sin(f),b-g*window.Math.cos(f))};D.Z.RK=function(b,c){var d=window.Math.log(window.Math.tan(0.25*window.Math.PI+0.5*D.Z.Zg(c)));return new D.K(b,D.Z.yI(d))};
D.Z.twa=function(b,c,d){c=D.Z.Zg(c);d=D.Z.Zg(d);var e=D.Z.Zg(b.x);b=D.Z.Zg(b.y);return new D.K(window.Math.cos(d)*window.Math.sin(c-e)*D.Z.GP,(window.Math.cos(b)*window.Math.sin(d)-window.Math.sin(b)*window.Math.cos(d)*window.Math.cos(c-e))*D.Z.GP)};
D.Z.wwa=function(b,c){var d=window.Math.floor(window.Math.abs(c)/5);d>=D.Z.kl.length-1&&(d=D.Z.kl.length-2);var e=(window.Math.abs(c)-5*d)/5,f=b*(D.Z.kl[d][0]+e*(D.Z.kl[d+1][0]-D.Z.kl[d][0])),d=D.Z.kl[d][1]+e*(D.Z.kl[d+1][1]-D.Z.kl[d][1]);0>c&&(d*=-1);return new D.K(f,180*d)};D.Z.CJ=function(b,c){return new D.K(c.x*b.Kc+b.Ab,c.y*b.Je+b.wb)};D.Z.oda=function(b,c){var d=b.Kc,e=b.Je;return new D.sd(c.Kc*d,c.Wf*d,c.vf*e,c.Je*e,b.Ab+c.Ab*d,b.wb+c.wb*e)};
D.Z.nn=function(b,c){var d=c.x,e=c.y,f=b.g,g=b.j,h=0,h=c.g/f,j=c.j/g,h=h<=j?h:j,d=d-b.x*h,e=e+b.y*h,d=d+(c.g-f*h)/2,e=e+(c.j-(c.j-g*h)/2);return new D.sd(h,0,0,-h,d,e)};D.Z.Zg=function(b){return b*(window.Math.PI/180)};D.Z.yI=function(b){return b*(180/window.Math.PI)};
D.Z.sKa=function(b,c,d){var e;b/=10;c/=10;switch(d){case "africa":e=D.Z.Jv(D.Z.uba,new D.K(b,c));e=D.Z.QK(e.x,e.y);break;case "asia":e=D.Z.Jv(D.Z.xba,new D.K(b,c),D.Z.Zg(5));e=D.Z.GR(40,95,20,60,e.x,e.y);break;case "australia":e=D.Z.iwa(b,c);break;case "europe":e=D.Z.Jv(D.Z.Jba,new D.K(b,c),D.Z.Zg(10));e=D.Z.GR(35,25,40,65,e.x,e.y);break;case "northAmerica":e=D.Z.Jv(D.Z.Sba,new D.K(b,c));e=D.Z.GR(23,-96,20,60,e.x,e.y);break;case "southAmerica":e=D.Z.Jv(D.Z.Zba,new D.K(b,c),D.Z.Zg(5));break;case "apac":e=
D.Z.Jv(D.Z.wba,new D.K(b,c));e=D.Z.QK(e.x,e.y);break;case "emea":e=D.Z.Jv(D.Z.Hba,new D.K(b,c));e=D.Z.QK(e.x,e.y);break;case "latinAmerica":e=D.Z.Jv(D.Z.Rba,new D.K(b,c));break;case "usaAndCanada":e=D.Z.Jv(D.Z.cca,new D.K(b,c));e=D.Z.GR(23,-96,20,60,e.x,e.y);break;case "worldRegions":e=D.Z.Iea(b,c);break;case "usa":e=D.Z.lwa(b,c);break;case "world":e=D.Z.Iea(b,c)}return e?e:new D.K(b,c)};
D.Z.lwa=function(b,c){var d;return(0,D.ur)(D.Z.qZ,b,c)?(d=D.Z.nn(D.Z.vba,D.Z.qZ),d.vu(),d=(0,D.Ej)(d,new D.K(b,c)),D.Z.QK(d.x,d.y)):(0,D.ur)(D.Z.uZ,b,c)?(d=D.Z.nn(D.Z.Nba,D.Z.uZ),d.vu(),(0,D.Ej)(d,new D.K(b,c))):(0,D.ur)(D.Z.cv,b,c)?(d=D.Z.nn(D.Z.bca,D.Z.cv),d.vu(),d=(0,D.Ej)(d,new D.K(b,c)),D.Z.jwa(new D.K(-95,36),d.x,d.y)):new D.K(b,c)};D.Z.Iea=function(b,c){var d=D.Z.nn(D.Z.dca,D.Z.cv);d.vu();d=(0,D.Ej)(d,new D.K(b,c));return D.Z.kwa(d.x,d.y)};
D.Z.iwa=function(b,c){var d;d=(0,D.ur)(D.Z.xZ,b,c)?D.Z.nn(D.Z.wZ,D.Z.xZ):D.Z.nn(D.Z.yba,D.Z.cv);d.vu();d=(0,D.Ej)(d,new D.K(b,c));return D.Z.QK(d.x,d.y)};D.Z.Jv=function(b,c,d){b=D.Z.nn(b,D.Z.cv);if(d){var e=new D.sd;e.rotate(d);b=D.Z.oda(b,e)}b.vu();return(0,D.Ej)(b,c)};
D.Z.GR=function(b,c,d,e,f,g){c=D.Z.Zg(c);b=D.Z.Zg(b);d=D.Z.Zg(d);e=D.Z.Zg(e);e=0.5*(window.Math.sin(d)+window.Math.sin(e));d=window.Math.pow(window.Math.cos(d),2)+2*e*window.Math.sin(d);b=d-2*e*window.Math.sin(b);b=window.Math.sqrt(b)/e;var h=window.Math.sqrt(f*f+(b-g)*(b-g));return new D.K(D.Z.yI(c+window.Math.atan(f/(b-g))/e),D.Z.yI(window.Math.asin((d-h*h*e*e)/(2*e))))};D.Z.QK=function(b,c){return new D.K(b,D.Z.yI(2*window.Math.atan(window.Math.exp(D.Z.Zg(c)))-0.5*window.Math.PI))};
D.Z.jwa=function(b,c,d){c/=D.Z.GP;d/=D.Z.GP;var e=D.Z.Zg(b.y),f=window.Math.sqrt(c*c+d*d),g=window.Math.asin(f);return new D.K(D.Z.yI(D.Z.Zg(b.x)+window.Math.atan(c*window.Math.sin(g)/(f*window.Math.cos(e)*window.Math.cos(g)-d*window.Math.sin(e)*window.Math.sin(g)))),D.Z.yI(window.Math.asin(window.Math.cos(g)*window.Math.sin(e)+d*window.Math.sin(g)*window.Math.cos(e)/f)))};
D.Z.kwa=function(b,c){var d=window.Math.floor(window.Math.abs(c)/5);d>=D.Z.kl.length-1&&(d=D.Z.kl.length-2);var e=(window.Math.abs(c/180)-D.Z.kl[d][1])/(D.Z.kl[d+1][1]-D.Z.kl[d][1]),f=5*e+5*d,d=b/(D.Z.kl[d][0]+e*(D.Z.kl[d+1][0]-D.Z.kl[d][0]));0>c&&(f*=-1);return new D.K(d,f)};
D.Wv=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.F.o(D.Wv,D.Xv,"DvtMapControlButton");
D.Wv.prototype.Init=function(b,c,d,e,f,g,h){D.Wv.u.Init.call(this,b,e,g);this.A_=f;this.Ib=c;this.va=h;(0,D.Yv)(this.Ib,this.Bpa,this);this.Ib.setCursor("pointer");b=new D.ml(this,D.q,D.q,D.q,D.q,D.q,0==this.A_?(0,D.ec)(this.ad,"CONTROL_PANEL_DRILLUP"):1==this.A_?(0,D.ec)(this.ad,"CONTROL_PANEL_DRILLDOWN"):2==this.A_?(0,D.ec)(this.ad,"CONTROL_PANEL_RESET"):D.q);this.va.la(this.Ib,b);this.k(this.Ib);this.yga=d;this.wfa=D.n};
D.Wv.prototype.Wg=function(b){this.C(b?1:0.4);this.Ib.setCursor(b?"pointer":D.q);this.wfa=b;this.Ib.Wg(b);(0,D.Zv)(this.Ib)};D.Wv.prototype.Bpa=function(b){(0,D.Qe)(b);this.wfa&&this.yga&&this.yga()};
D.Tv=function(b,c,d){this.Init(b,c,d)};D.F.o(D.Tv,D.je,"DvtThematicMapControlPanel");D.Tv.prototype.Init=function(b,c,d){D.Tv.u.Init.call(this,b,c,d);this.Bk=c.Bk;this.sl=(0,D.ce)(c);this.Fva=D.F.qj(c,c.N5);this.Dva=D.F.qj(c,c.HU);this.Aza=D.F.qj(c,c.s8);this.eF=this.fF=this.yia=D.q;this.bea=this.aea=D.t;this.F=c.vs()};D.Uv=function(b,c){b.aea=c;b.eF&&b.eF.Wg(c)};D.Vv=function(b,c){b.bea=c;b.fF&&b.fF.Wg(c)};
D.Tv.prototype.jJ=function(b){if(this.Bk&&"none"!=this.Bk){var c=(0,D.Je)(this.F,"buttonWidth",0);this.yia=D.W.tBa(this.e,this.Aza,this.ca,this.ad,this.sl,this.va,this.F);b.k(this.yia);this.eF=D.W.hBa(this.e,this.Dva,this.ca,this.ad,this.sl,this.va,this.F);this.eF.G(c);this.eF.Wg(this.aea);b.k(this.eF);this.fF=D.W.iBa(this.e,this.Fva,this.ca,this.ad,this.sl,this.va,this.F);this.fF.G(2*c);this.fF.Wg(this.bea);b.k(this.fF)}};
});